
(define (problem cochrantontaskographyv3medium10bagslots3problem35) (:domain taskographyv3medium10bagslots3scrub)
  (:objects
        bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	item10_apple_smallitem - item
	item21_potted_plant_largeitem - item
	item22_potted_plant_largeitem - item
	item23_potted_plant_largeitem - item
	item24_potted_plant_largeitem - item
	item25_potted_plant_largeitem - item
	item26_potted_plant_largeitem - item
	item27_potted_plant_largeitem - item
	item28_potted_plant_largeitem - item
	item29_potted_plant_largeitem - item
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item33_potted_plant_largeitem - item
	item45_mouse_smallitem - item
	item4_kite_largeitem - item
	item56_book_smallitem - item
	item57_book_smallitem - item
	item58_book_smallitem - item
	item59_book_smallitem - item
	item5_bottle_smallitem - item
	item60_book_smallitem - item
	item61_book_smallitem - item
	item62_clock_mediumitem - item
	item63_vase_mediumitem - item
	item64_vase_mediumitem - item
	item65_vase_mediumitem - item
	item66_vase_mediumitem - item
	item67_vase_mediumitem - item
	item68_vase_mediumitem - item
	item69_vase_mediumitem - item
	item6_bottle_smallitem - item
	item7_bottle_smallitem - item
	item8_cup_smallitem - item
	item9_spoon_smallitem - item
	location_xneg100_ypos0_place47_room1_floora - location
	location_xneg12_yneg43_place39_room13_floorb - location
	location_xneg13_yneg33_place23_room13_floorb - location
	location_xneg16_yneg3_place13_room11_floorc - location
	location_xneg17_yneg21_place43_room4_floorc - location
	location_xneg17_yneg26_place43_room4_floorc - location
	location_xneg17_yneg27_place43_room4_floorc - location
	location_xneg20_yneg18_place43_room4_floorc - location
	location_xneg28_yneg32_place24_room12_floorb - location
	location_xneg2_yneg2_place14_room15_floora - location
	location_xneg31_yneg29_place1_room4_floorc - location
	location_xneg31_yneg30_place5_room12_floorb - location
	location_xneg34_yneg32_place38_room12_floorb - location
	location_xneg35_yneg38_place27_room12_floorb - location
	location_xneg36_yneg40_place52_room4_floorc - location
	location_xneg38_yneg29_place28_room12_floorb - location
	location_xneg40_yneg32_place25_room12_floorb - location
	location_xneg41_yneg2_place11_room9_floora - location
	location_xneg41_yneg35_place26_room12_floorb - location
	location_xneg42_yneg22_place50_room4_floorc - location
	location_xneg42_yneg5_place12_room10_floorb - location
	location_xneg43_ypos4_place15_room16_floora - location
	location_xneg44_yneg30_place50_room4_floorc - location
	location_xneg44_yneg32_place50_room4_floorc - location
	location_xneg44_yneg36_place52_room4_floorc - location
	location_xneg44_ypos4_place16_room17_floorb - location
	location_xneg49_yneg14_place35_room7_floorc - location
	location_xneg49_yneg15_place35_room7_floorc - location
	location_xneg50_yneg18_place35_room7_floorc - location
	location_xneg50_yneg36_place35_room7_floorc - location
	location_xneg50_yneg38_place35_room7_floorc - location
	location_xneg58_yneg29_place35_room7_floorc - location
	location_xneg5_yneg29_place45_room13_floorb - location
	location_xneg60_yneg38_place32_room14_floorb - location
	location_xneg62_yneg12_place19_room9_floora - location
	location_xneg62_ypos0_place36_room8_floorc - location
	location_xneg63_yneg24_place6_room7_floorc - location
	location_xneg64_yneg44_place35_room7_floorc - location
	location_xneg71_yneg30_place33_room5_floora - location
	location_xneg73_yneg16_place31_room14_floorb - location
	location_xneg73_yneg24_place33_room5_floora - location
	location_xneg73_yneg31_place7_room14_floorb - location
	location_xneg73_yneg44_place18_room7_floorc - location
	location_xneg76_ypos2_place0_room8_floorc - location
	location_xneg76_ypos7_place21_room8_floorc - location
	location_xneg77_yneg47_place30_room14_floorb - location
	location_xneg77_yneg48_place30_room14_floorb - location
	location_xneg77_ypos7_place20_room8_floorc - location
	location_xneg78_ypos9_place22_room8_floorc - location
	location_xneg86_yneg37_place30_room14_floorb - location
	location_xneg86_ypos6_place46_room1_floora - location
	location_xneg89_yneg22_place2_room5_floora - location
	location_xneg89_yneg34_place33_room5_floora - location
	location_xneg89_ypos7_place46_room1_floora - location
	location_xneg93_yneg22_place29_room7_floorc - location
	location_xneg93_ypos3_place40_room1_floora - location
	location_xneg94_ypos2_place9_room1_floora - location
	location_xneg95_yneg34_place29_room7_floorc - location
	location_xneg96_yneg22_place30_room14_floorb - location
	location_xneg96_yneg34_place29_room7_floorc - location
	location_xneg98_yneg38_place29_room7_floorc - location
	location_xneg98_yneg42_place33_room5_floora - location
	location_xneg9_yneg33_place37_room13_floorb - location
	location_xneg9_yneg36_place37_room13_floorb - location
	location_xpos11_ypos0_place42_room3_floorc - location
	location_xpos13_yneg34_place34_room6_floorc - location
	location_xpos13_yneg9_place53_room13_floorb - location
	location_xpos14_yneg10_place53_room13_floorb - location
	location_xpos14_yneg4_place48_room2_floorb - location
	location_xpos14_yneg9_place53_room13_floorb - location
	location_xpos17_yneg4_place4_room3_floorc - location
	location_xpos17_ypos1_place10_room2_floorb - location
	location_xpos21_yneg11_place53_room13_floorb - location
	location_xpos21_yneg25_place34_room6_floorc - location
	location_xpos21_yneg3_place41_room2_floorb - location
	location_xpos21_yneg43_place49_room13_floorb - location
	location_xpos21_yneg4_place42_room3_floorc - location
	location_xpos22_yneg12_place51_room3_floorc - location
	location_xpos22_yneg29_place44_room13_floorb - location
	location_xpos23_yneg8_place53_room13_floorb - location
	location_xpos24_yneg21_place44_room13_floorb - location
	location_xpos24_yneg22_place44_room13_floorb - location
	location_xpos3_yneg2_place17_room18_floorc - location
	location_xpos4_yneg14_place53_room13_floorb - location
	location_xpos4_yneg27_place3_room13_floorb - location
	location_xpos5_yneg30_place8_room6_floorc - location
	location_xpos8_yneg43_place49_room13_floorb - location
	place0_door_room8_closet - place
	place10_door_room2_bathroom - place
	place11_door_room9_corridor - place
	place12_door_room10_corridor - place
	place13_door_room11_corridor - place
	place14_door_room15_lobby - place
	place15_door_room16_staircase - place
	place16_door_room17_staircase - place
	place17_door_room18_utility_room - place
	place18_item27_potted_plant - place
	place19_item62_clock - place
	place1_door_room4_bathroom - place
	place20_receptacle1_bench - place
	place21_receptacle2_bench - place
	place22_receptacle3_bench - place
	place23_receptacle11_chair - place
	place24_receptacle12_chair - place
	place25_receptacle13_chair - place
	place26_receptacle14_chair - place
	place27_receptacle15_chair - place
	place28_receptacle16_chair - place
	place29_receptacle17_chair - place
	place2_door_room5_bedroom - place
	place30_receptacle18_couch - place
	place31_receptacle19_couch - place
	place32_receptacle20_couch - place
	place33_receptacle34_bed - place
	place34_receptacle35_bed - place
	place35_receptacle36_bed - place
	place36_receptacle37_bed - place
	place37_receptacle38_dining_table - place
	place38_receptacle39_dining_table - place
	place39_receptacle40_dining_table - place
	place3_door_room13_kitchen - place
	place40_receptacle41_toilet - place
	place41_receptacle42_toilet - place
	place42_receptacle43_toilet - place
	place43_receptacle44_toilet - place
	place44_receptacle46_microwave - place
	place45_receptacle47_oven - place
	place46_receptacle48_sink - place
	place47_receptacle49_sink - place
	place48_receptacle50_sink - place
	place49_receptacle51_sink - place
	place4_door_room3_bathroom - place
	place50_receptacle52_sink - place
	place51_receptacle53_sink - place
	place52_receptacle54_sink - place
	place53_receptacle55_refrigerator - place
	place5_door_room12_dining_room - place
	place6_door_room7_bedroom - place
	place7_door_room14_living_room - place
	place8_door_room6_bedroom - place
	place9_door_room1_bathroom - place
	receptacle11_chair - receptacle
	receptacle12_chair - receptacle
	receptacle13_chair - receptacle
	receptacle14_chair - receptacle
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_couch - receptacle
	receptacle19_couch - receptacle
	receptacle1_bench - receptacle
	receptacle20_couch - receptacle
	receptacle2_bench - receptacle
	receptacle34_bed - receptacle
	receptacle35_bed - receptacle
	receptacle36_bed - receptacle
	receptacle37_bed - receptacle
	receptacle38_dining_table - receptacle
	receptacle39_dining_table - receptacle
	receptacle3_bench - receptacle
	receptacle40_dining_table - receptacle
	receptacle41_toilet - receptacle
	receptacle42_toilet - receptacle
	receptacle43_toilet - receptacle
	receptacle44_toilet - receptacle
	receptacle46_microwave - receptacle
	receptacle47_oven - receptacle
	receptacle48_sink - receptacle
	receptacle49_sink - receptacle
	receptacle50_sink - receptacle
	receptacle51_sink - receptacle
	receptacle52_sink - receptacle
	receptacle53_sink - receptacle
	receptacle54_sink - receptacle
	receptacle55_refrigerator - receptacle
	robot - agent
	room10_corridor - room
	room11_corridor - room
	room12_dining_room - room
	room13_kitchen - room
	room14_living_room - room
	room15_lobby - room
	room16_staircase - room
	room17_staircase - room
	room18_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bathroom - room
	room5_bedroom - room
	room6_bedroom - room
	room7_bedroom - room
	room8_closet - room
	room9_corridor - room
  )
  (:init 
	(atlocation robot location_xneg94_ypos2_place9_room1_floora)
	(inanyreceptacle item10_apple_smallitem)
	(inanyreceptacle item21_potted_plant_largeitem)
	(inanyreceptacle item22_potted_plant_largeitem)
	(inanyreceptacle item23_potted_plant_largeitem)
	(inanyreceptacle item24_potted_plant_largeitem)
	(inanyreceptacle item25_potted_plant_largeitem)
	(inanyreceptacle item26_potted_plant_largeitem)
	(inanyreceptacle item28_potted_plant_largeitem)
	(inanyreceptacle item29_potted_plant_largeitem)
	(inanyreceptacle item30_potted_plant_largeitem)
	(inanyreceptacle item31_potted_plant_largeitem)
	(inanyreceptacle item32_potted_plant_largeitem)
	(inanyreceptacle item33_potted_plant_largeitem)
	(inanyreceptacle item45_mouse_smallitem)
	(inanyreceptacle item4_kite_largeitem)
	(inanyreceptacle item56_book_smallitem)
	(inanyreceptacle item57_book_smallitem)
	(inanyreceptacle item58_book_smallitem)
	(inanyreceptacle item59_book_smallitem)
	(inanyreceptacle item5_bottle_smallitem)
	(inanyreceptacle item60_book_smallitem)
	(inanyreceptacle item61_book_smallitem)
	(inanyreceptacle item63_vase_mediumitem)
	(inanyreceptacle item64_vase_mediumitem)
	(inanyreceptacle item65_vase_mediumitem)
	(inanyreceptacle item66_vase_mediumitem)
	(inanyreceptacle item67_vase_mediumitem)
	(inanyreceptacle item68_vase_mediumitem)
	(inanyreceptacle item69_vase_mediumitem)
	(inanyreceptacle item6_bottle_smallitem)
	(inanyreceptacle item7_bottle_smallitem)
	(inanyreceptacle item8_cup_smallitem)
	(inanyreceptacle item9_spoon_smallitem)
	(inplace robot place9_door_room1_bathroom)
	(inreceptacle item10_apple_smallitem receptacle38_dining_table)
	(inreceptacle item21_potted_plant_largeitem receptacle18_couch)
	(inreceptacle item22_potted_plant_largeitem receptacle55_refrigerator)
	(inreceptacle item23_potted_plant_largeitem receptacle55_refrigerator)
	(inreceptacle item24_potted_plant_largeitem receptacle55_refrigerator)
	(inreceptacle item25_potted_plant_largeitem receptacle18_couch)
	(inreceptacle item26_potted_plant_largeitem receptacle36_bed)
	(inreceptacle item28_potted_plant_largeitem receptacle17_chair)
	(inreceptacle item29_potted_plant_largeitem receptacle17_chair)
	(inreceptacle item30_potted_plant_largeitem receptacle17_chair)
	(inreceptacle item31_potted_plant_largeitem receptacle54_sink)
	(inreceptacle item32_potted_plant_largeitem receptacle52_sink)
	(inreceptacle item33_potted_plant_largeitem receptacle44_toilet)
	(inreceptacle item45_mouse_smallitem receptacle36_bed)
	(inreceptacle item4_kite_largeitem receptacle44_toilet)
	(inreceptacle item56_book_smallitem receptacle34_bed)
	(inreceptacle item57_book_smallitem receptacle34_bed)
	(inreceptacle item58_book_smallitem receptacle51_sink)
	(inreceptacle item59_book_smallitem receptacle35_bed)
	(inreceptacle item5_bottle_smallitem receptacle34_bed)
	(inreceptacle item60_book_smallitem receptacle36_bed)
	(inreceptacle item61_book_smallitem receptacle36_bed)
	(inreceptacle item63_vase_mediumitem receptacle48_sink)
	(inreceptacle item64_vase_mediumitem receptacle55_refrigerator)
	(inreceptacle item65_vase_mediumitem receptacle46_microwave)
	(inreceptacle item66_vase_mediumitem receptacle18_couch)
	(inreceptacle item67_vase_mediumitem receptacle36_bed)
	(inreceptacle item68_vase_mediumitem receptacle36_bed)
	(inreceptacle item69_vase_mediumitem receptacle44_toilet)
	(inreceptacle item6_bottle_smallitem receptacle55_refrigerator)
	(inreceptacle item7_bottle_smallitem receptacle43_toilet)
	(inreceptacle item8_cup_smallitem receptacle52_sink)
	(inreceptacle item9_spoon_smallitem receptacle46_microwave)
	(inroom robot room1_bathroom)
	(itematlocation item10_apple_smallitem location_xneg9_yneg33_place37_room13_floorb)
	(itematlocation item21_potted_plant_largeitem location_xneg96_yneg22_place30_room14_floorb)
	(itematlocation item22_potted_plant_largeitem location_xpos14_yneg9_place53_room13_floorb)
	(itematlocation item23_potted_plant_largeitem location_xpos21_yneg11_place53_room13_floorb)
	(itematlocation item24_potted_plant_largeitem location_xpos23_yneg8_place53_room13_floorb)
	(itematlocation item25_potted_plant_largeitem location_xneg77_yneg47_place30_room14_floorb)
	(itematlocation item26_potted_plant_largeitem location_xneg49_yneg15_place35_room7_floorc)
	(itematlocation item27_potted_plant_largeitem location_xneg73_yneg44_place18_room7_floorc)
	(itematlocation item28_potted_plant_largeitem location_xneg95_yneg34_place29_room7_floorc)
	(itematlocation item29_potted_plant_largeitem location_xneg96_yneg34_place29_room7_floorc)
	(itematlocation item30_potted_plant_largeitem location_xneg98_yneg38_place29_room7_floorc)
	(itematlocation item31_potted_plant_largeitem location_xneg44_yneg36_place52_room4_floorc)
	(itematlocation item32_potted_plant_largeitem location_xneg44_yneg32_place50_room4_floorc)
	(itematlocation item33_potted_plant_largeitem location_xneg17_yneg26_place43_room4_floorc)
	(itematlocation item45_mouse_smallitem location_xneg50_yneg38_place35_room7_floorc)
	(itematlocation item4_kite_largeitem location_xneg17_yneg21_place43_room4_floorc)
	(itematlocation item56_book_smallitem location_xneg73_yneg24_place33_room5_floora)
	(itematlocation item57_book_smallitem location_xneg98_yneg42_place33_room5_floora)
	(itematlocation item58_book_smallitem location_xpos21_yneg43_place49_room13_floorb)
	(itematlocation item59_book_smallitem location_xpos21_yneg25_place34_room6_floorc)
	(itematlocation item5_bottle_smallitem location_xneg71_yneg30_place33_room5_floora)
	(itematlocation item60_book_smallitem location_xneg50_yneg18_place35_room7_floorc)
	(itematlocation item61_book_smallitem location_xneg50_yneg36_place35_room7_floorc)
	(itematlocation item62_clock_mediumitem location_xneg62_yneg12_place19_room9_floora)
	(itematlocation item63_vase_mediumitem location_xneg89_ypos7_place46_room1_floora)
	(itematlocation item64_vase_mediumitem location_xpos14_yneg10_place53_room13_floorb)
	(itematlocation item65_vase_mediumitem location_xpos24_yneg22_place44_room13_floorb)
	(itematlocation item66_vase_mediumitem location_xneg77_yneg48_place30_room14_floorb)
	(itematlocation item67_vase_mediumitem location_xneg49_yneg14_place35_room7_floorc)
	(itematlocation item68_vase_mediumitem location_xneg64_yneg44_place35_room7_floorc)
	(itematlocation item69_vase_mediumitem location_xneg17_yneg27_place43_room4_floorc)
	(itematlocation item6_bottle_smallitem location_xpos13_yneg9_place53_room13_floorb)
	(itematlocation item7_bottle_smallitem location_xpos11_ypos0_place42_room3_floorc)
	(itematlocation item8_cup_smallitem location_xneg44_yneg30_place50_room4_floorc)
	(itematlocation item9_spoon_smallitem location_xpos24_yneg21_place44_room13_floorb)
	(largeitem item21_potted_plant_largeitem)
	(largeitem item22_potted_plant_largeitem)
	(largeitem item23_potted_plant_largeitem)
	(largeitem item24_potted_plant_largeitem)
	(largeitem item25_potted_plant_largeitem)
	(largeitem item26_potted_plant_largeitem)
	(largeitem item27_potted_plant_largeitem)
	(largeitem item28_potted_plant_largeitem)
	(largeitem item29_potted_plant_largeitem)
	(largeitem item30_potted_plant_largeitem)
	(largeitem item31_potted_plant_largeitem)
	(largeitem item32_potted_plant_largeitem)
	(largeitem item33_potted_plant_largeitem)
	(largeitem item4_kite_largeitem)
	(locationinplace location_xneg100_ypos0_place47_room1_floora place47_receptacle49_sink)
	(locationinplace location_xneg12_yneg43_place39_room13_floorb place39_receptacle40_dining_table)
	(locationinplace location_xneg13_yneg33_place23_room13_floorb place23_receptacle11_chair)
	(locationinplace location_xneg16_yneg3_place13_room11_floorc place13_door_room11_corridor)
	(locationinplace location_xneg17_yneg21_place43_room4_floorc place43_receptacle44_toilet)
	(locationinplace location_xneg17_yneg26_place43_room4_floorc place43_receptacle44_toilet)
	(locationinplace location_xneg17_yneg27_place43_room4_floorc place43_receptacle44_toilet)
	(locationinplace location_xneg20_yneg18_place43_room4_floorc place43_receptacle44_toilet)
	(locationinplace location_xneg28_yneg32_place24_room12_floorb place24_receptacle12_chair)
	(locationinplace location_xneg2_yneg2_place14_room15_floora place14_door_room15_lobby)
	(locationinplace location_xneg31_yneg29_place1_room4_floorc place1_door_room4_bathroom)
	(locationinplace location_xneg31_yneg30_place5_room12_floorb place5_door_room12_dining_room)
	(locationinplace location_xneg34_yneg32_place38_room12_floorb place38_receptacle39_dining_table)
	(locationinplace location_xneg35_yneg38_place27_room12_floorb place27_receptacle15_chair)
	(locationinplace location_xneg36_yneg40_place52_room4_floorc place52_receptacle54_sink)
	(locationinplace location_xneg38_yneg29_place28_room12_floorb place28_receptacle16_chair)
	(locationinplace location_xneg40_yneg32_place25_room12_floorb place25_receptacle13_chair)
	(locationinplace location_xneg41_yneg2_place11_room9_floora place11_door_room9_corridor)
	(locationinplace location_xneg41_yneg35_place26_room12_floorb place26_receptacle14_chair)
	(locationinplace location_xneg42_yneg22_place50_room4_floorc place50_receptacle52_sink)
	(locationinplace location_xneg42_yneg5_place12_room10_floorb place12_door_room10_corridor)
	(locationinplace location_xneg43_ypos4_place15_room16_floora place15_door_room16_staircase)
	(locationinplace location_xneg44_yneg30_place50_room4_floorc place50_receptacle52_sink)
	(locationinplace location_xneg44_yneg32_place50_room4_floorc place50_receptacle52_sink)
	(locationinplace location_xneg44_yneg36_place52_room4_floorc place52_receptacle54_sink)
	(locationinplace location_xneg44_ypos4_place16_room17_floorb place16_door_room17_staircase)
	(locationinplace location_xneg49_yneg14_place35_room7_floorc place35_receptacle36_bed)
	(locationinplace location_xneg49_yneg15_place35_room7_floorc place35_receptacle36_bed)
	(locationinplace location_xneg50_yneg18_place35_room7_floorc place35_receptacle36_bed)
	(locationinplace location_xneg50_yneg36_place35_room7_floorc place35_receptacle36_bed)
	(locationinplace location_xneg50_yneg38_place35_room7_floorc place35_receptacle36_bed)
	(locationinplace location_xneg58_yneg29_place35_room7_floorc place35_receptacle36_bed)
	(locationinplace location_xneg5_yneg29_place45_room13_floorb place45_receptacle47_oven)
	(locationinplace location_xneg60_yneg38_place32_room14_floorb place32_receptacle20_couch)
	(locationinplace location_xneg62_yneg12_place19_room9_floora place19_item62_clock)
	(locationinplace location_xneg62_ypos0_place36_room8_floorc place36_receptacle37_bed)
	(locationinplace location_xneg63_yneg24_place6_room7_floorc place6_door_room7_bedroom)
	(locationinplace location_xneg64_yneg44_place35_room7_floorc place35_receptacle36_bed)
	(locationinplace location_xneg71_yneg30_place33_room5_floora place33_receptacle34_bed)
	(locationinplace location_xneg73_yneg16_place31_room14_floorb place31_receptacle19_couch)
	(locationinplace location_xneg73_yneg24_place33_room5_floora place33_receptacle34_bed)
	(locationinplace location_xneg73_yneg31_place7_room14_floorb place7_door_room14_living_room)
	(locationinplace location_xneg73_yneg44_place18_room7_floorc place18_item27_potted_plant)
	(locationinplace location_xneg76_ypos2_place0_room8_floorc place0_door_room8_closet)
	(locationinplace location_xneg76_ypos7_place21_room8_floorc place21_receptacle2_bench)
	(locationinplace location_xneg77_yneg47_place30_room14_floorb place30_receptacle18_couch)
	(locationinplace location_xneg77_yneg48_place30_room14_floorb place30_receptacle18_couch)
	(locationinplace location_xneg77_ypos7_place20_room8_floorc place20_receptacle1_bench)
	(locationinplace location_xneg78_ypos9_place22_room8_floorc place22_receptacle3_bench)
	(locationinplace location_xneg86_yneg37_place30_room14_floorb place30_receptacle18_couch)
	(locationinplace location_xneg86_ypos6_place46_room1_floora place46_receptacle48_sink)
	(locationinplace location_xneg89_yneg22_place2_room5_floora place2_door_room5_bedroom)
	(locationinplace location_xneg89_yneg34_place33_room5_floora place33_receptacle34_bed)
	(locationinplace location_xneg89_ypos7_place46_room1_floora place46_receptacle48_sink)
	(locationinplace location_xneg93_yneg22_place29_room7_floorc place29_receptacle17_chair)
	(locationinplace location_xneg93_ypos3_place40_room1_floora place40_receptacle41_toilet)
	(locationinplace location_xneg94_ypos2_place9_room1_floora place9_door_room1_bathroom)
	(locationinplace location_xneg95_yneg34_place29_room7_floorc place29_receptacle17_chair)
	(locationinplace location_xneg96_yneg22_place30_room14_floorb place30_receptacle18_couch)
	(locationinplace location_xneg96_yneg34_place29_room7_floorc place29_receptacle17_chair)
	(locationinplace location_xneg98_yneg38_place29_room7_floorc place29_receptacle17_chair)
	(locationinplace location_xneg98_yneg42_place33_room5_floora place33_receptacle34_bed)
	(locationinplace location_xneg9_yneg33_place37_room13_floorb place37_receptacle38_dining_table)
	(locationinplace location_xneg9_yneg36_place37_room13_floorb place37_receptacle38_dining_table)
	(locationinplace location_xpos11_ypos0_place42_room3_floorc place42_receptacle43_toilet)
	(locationinplace location_xpos13_yneg34_place34_room6_floorc place34_receptacle35_bed)
	(locationinplace location_xpos13_yneg9_place53_room13_floorb place53_receptacle55_refrigerator)
	(locationinplace location_xpos14_yneg10_place53_room13_floorb place53_receptacle55_refrigerator)
	(locationinplace location_xpos14_yneg4_place48_room2_floorb place48_receptacle50_sink)
	(locationinplace location_xpos14_yneg9_place53_room13_floorb place53_receptacle55_refrigerator)
	(locationinplace location_xpos17_yneg4_place4_room3_floorc place4_door_room3_bathroom)
	(locationinplace location_xpos17_ypos1_place10_room2_floorb place10_door_room2_bathroom)
	(locationinplace location_xpos21_yneg11_place53_room13_floorb place53_receptacle55_refrigerator)
	(locationinplace location_xpos21_yneg25_place34_room6_floorc place34_receptacle35_bed)
	(locationinplace location_xpos21_yneg3_place41_room2_floorb place41_receptacle42_toilet)
	(locationinplace location_xpos21_yneg43_place49_room13_floorb place49_receptacle51_sink)
	(locationinplace location_xpos21_yneg4_place42_room3_floorc place42_receptacle43_toilet)
	(locationinplace location_xpos22_yneg12_place51_room3_floorc place51_receptacle53_sink)
	(locationinplace location_xpos22_yneg29_place44_room13_floorb place44_receptacle46_microwave)
	(locationinplace location_xpos23_yneg8_place53_room13_floorb place53_receptacle55_refrigerator)
	(locationinplace location_xpos24_yneg21_place44_room13_floorb place44_receptacle46_microwave)
	(locationinplace location_xpos24_yneg22_place44_room13_floorb place44_receptacle46_microwave)
	(locationinplace location_xpos3_yneg2_place17_room18_floorc place17_door_room18_utility_room)
	(locationinplace location_xpos4_yneg14_place53_room13_floorb place53_receptacle55_refrigerator)
	(locationinplace location_xpos4_yneg27_place3_room13_floorb place3_door_room13_kitchen)
	(locationinplace location_xpos5_yneg30_place8_room6_floorc place8_door_room6_bedroom)
	(locationinplace location_xpos8_yneg43_place49_room13_floorb place49_receptacle51_sink)
	(mediumitem item62_clock_mediumitem)
	(mediumitem item63_vase_mediumitem)
	(mediumitem item64_vase_mediumitem)
	(mediumitem item65_vase_mediumitem)
	(mediumitem item66_vase_mediumitem)
	(mediumitem item67_vase_mediumitem)
	(mediumitem item68_vase_mediumitem)
	(mediumitem item69_vase_mediumitem)
	(placeinroom place0_door_room8_closet room8_closet)
	(placeinroom place10_door_room2_bathroom room2_bathroom)
	(placeinroom place11_door_room9_corridor room9_corridor)
	(placeinroom place12_door_room10_corridor room10_corridor)
	(placeinroom place13_door_room11_corridor room11_corridor)
	(placeinroom place14_door_room15_lobby room15_lobby)
	(placeinroom place15_door_room16_staircase room16_staircase)
	(placeinroom place16_door_room17_staircase room17_staircase)
	(placeinroom place17_door_room18_utility_room room18_utility_room)
	(placeinroom place18_item27_potted_plant room7_bedroom)
	(placeinroom place19_item62_clock room9_corridor)
	(placeinroom place1_door_room4_bathroom room4_bathroom)
	(placeinroom place20_receptacle1_bench room8_closet)
	(placeinroom place21_receptacle2_bench room8_closet)
	(placeinroom place22_receptacle3_bench room8_closet)
	(placeinroom place23_receptacle11_chair room13_kitchen)
	(placeinroom place24_receptacle12_chair room12_dining_room)
	(placeinroom place25_receptacle13_chair room12_dining_room)
	(placeinroom place26_receptacle14_chair room12_dining_room)
	(placeinroom place27_receptacle15_chair room12_dining_room)
	(placeinroom place28_receptacle16_chair room12_dining_room)
	(placeinroom place29_receptacle17_chair room7_bedroom)
	(placeinroom place2_door_room5_bedroom room5_bedroom)
	(placeinroom place30_receptacle18_couch room14_living_room)
	(placeinroom place31_receptacle19_couch room14_living_room)
	(placeinroom place32_receptacle20_couch room14_living_room)
	(placeinroom place33_receptacle34_bed room5_bedroom)
	(placeinroom place34_receptacle35_bed room6_bedroom)
	(placeinroom place35_receptacle36_bed room7_bedroom)
	(placeinroom place36_receptacle37_bed room8_closet)
	(placeinroom place37_receptacle38_dining_table room13_kitchen)
	(placeinroom place38_receptacle39_dining_table room12_dining_room)
	(placeinroom place39_receptacle40_dining_table room13_kitchen)
	(placeinroom place3_door_room13_kitchen room13_kitchen)
	(placeinroom place40_receptacle41_toilet room1_bathroom)
	(placeinroom place41_receptacle42_toilet room2_bathroom)
	(placeinroom place42_receptacle43_toilet room3_bathroom)
	(placeinroom place43_receptacle44_toilet room4_bathroom)
	(placeinroom place44_receptacle46_microwave room13_kitchen)
	(placeinroom place45_receptacle47_oven room13_kitchen)
	(placeinroom place46_receptacle48_sink room1_bathroom)
	(placeinroom place47_receptacle49_sink room1_bathroom)
	(placeinroom place48_receptacle50_sink room2_bathroom)
	(placeinroom place49_receptacle51_sink room13_kitchen)
	(placeinroom place4_door_room3_bathroom room3_bathroom)
	(placeinroom place50_receptacle52_sink room4_bathroom)
	(placeinroom place51_receptacle53_sink room3_bathroom)
	(placeinroom place52_receptacle54_sink room4_bathroom)
	(placeinroom place53_receptacle55_refrigerator room13_kitchen)
	(placeinroom place5_door_room12_dining_room room12_dining_room)
	(placeinroom place6_door_room7_bedroom room7_bedroom)
	(placeinroom place7_door_room14_living_room room14_living_room)
	(placeinroom place8_door_room6_bedroom room6_bedroom)
	(placeinroom place9_door_room1_bathroom room1_bathroom)
	(placelocation location_xneg100_ypos0_place47_room1_floora place47_receptacle49_sink)
	(placelocation location_xneg12_yneg43_place39_room13_floorb place39_receptacle40_dining_table)
	(placelocation location_xneg13_yneg33_place23_room13_floorb place23_receptacle11_chair)
	(placelocation location_xneg16_yneg3_place13_room11_floorc place13_door_room11_corridor)
	(placelocation location_xneg20_yneg18_place43_room4_floorc place43_receptacle44_toilet)
	(placelocation location_xneg28_yneg32_place24_room12_floorb place24_receptacle12_chair)
	(placelocation location_xneg2_yneg2_place14_room15_floora place14_door_room15_lobby)
	(placelocation location_xneg31_yneg29_place1_room4_floorc place1_door_room4_bathroom)
	(placelocation location_xneg31_yneg30_place5_room12_floorb place5_door_room12_dining_room)
	(placelocation location_xneg34_yneg32_place38_room12_floorb place38_receptacle39_dining_table)
	(placelocation location_xneg35_yneg38_place27_room12_floorb place27_receptacle15_chair)
	(placelocation location_xneg36_yneg40_place52_room4_floorc place52_receptacle54_sink)
	(placelocation location_xneg38_yneg29_place28_room12_floorb place28_receptacle16_chair)
	(placelocation location_xneg40_yneg32_place25_room12_floorb place25_receptacle13_chair)
	(placelocation location_xneg41_yneg2_place11_room9_floora place11_door_room9_corridor)
	(placelocation location_xneg41_yneg35_place26_room12_floorb place26_receptacle14_chair)
	(placelocation location_xneg42_yneg22_place50_room4_floorc place50_receptacle52_sink)
	(placelocation location_xneg42_yneg5_place12_room10_floorb place12_door_room10_corridor)
	(placelocation location_xneg43_ypos4_place15_room16_floora place15_door_room16_staircase)
	(placelocation location_xneg44_ypos4_place16_room17_floorb place16_door_room17_staircase)
	(placelocation location_xneg58_yneg29_place35_room7_floorc place35_receptacle36_bed)
	(placelocation location_xneg5_yneg29_place45_room13_floorb place45_receptacle47_oven)
	(placelocation location_xneg60_yneg38_place32_room14_floorb place32_receptacle20_couch)
	(placelocation location_xneg62_yneg12_place19_room9_floora place19_item62_clock)
	(placelocation location_xneg62_ypos0_place36_room8_floorc place36_receptacle37_bed)
	(placelocation location_xneg63_yneg24_place6_room7_floorc place6_door_room7_bedroom)
	(placelocation location_xneg73_yneg16_place31_room14_floorb place31_receptacle19_couch)
	(placelocation location_xneg73_yneg31_place7_room14_floorb place7_door_room14_living_room)
	(placelocation location_xneg73_yneg44_place18_room7_floorc place18_item27_potted_plant)
	(placelocation location_xneg76_ypos2_place0_room8_floorc place0_door_room8_closet)
	(placelocation location_xneg76_ypos7_place21_room8_floorc place21_receptacle2_bench)
	(placelocation location_xneg77_ypos7_place20_room8_floorc place20_receptacle1_bench)
	(placelocation location_xneg78_ypos9_place22_room8_floorc place22_receptacle3_bench)
	(placelocation location_xneg86_yneg37_place30_room14_floorb place30_receptacle18_couch)
	(placelocation location_xneg86_ypos6_place46_room1_floora place46_receptacle48_sink)
	(placelocation location_xneg89_yneg22_place2_room5_floora place2_door_room5_bedroom)
	(placelocation location_xneg89_yneg34_place33_room5_floora place33_receptacle34_bed)
	(placelocation location_xneg93_yneg22_place29_room7_floorc place29_receptacle17_chair)
	(placelocation location_xneg93_ypos3_place40_room1_floora place40_receptacle41_toilet)
	(placelocation location_xneg94_ypos2_place9_room1_floora place9_door_room1_bathroom)
	(placelocation location_xneg9_yneg36_place37_room13_floorb place37_receptacle38_dining_table)
	(placelocation location_xpos13_yneg34_place34_room6_floorc place34_receptacle35_bed)
	(placelocation location_xpos14_yneg4_place48_room2_floorb place48_receptacle50_sink)
	(placelocation location_xpos17_yneg4_place4_room3_floorc place4_door_room3_bathroom)
	(placelocation location_xpos17_ypos1_place10_room2_floorb place10_door_room2_bathroom)
	(placelocation location_xpos21_yneg3_place41_room2_floorb place41_receptacle42_toilet)
	(placelocation location_xpos21_yneg4_place42_room3_floorc place42_receptacle43_toilet)
	(placelocation location_xpos22_yneg12_place51_room3_floorc place51_receptacle53_sink)
	(placelocation location_xpos22_yneg29_place44_room13_floorb place44_receptacle46_microwave)
	(placelocation location_xpos3_yneg2_place17_room18_floorc place17_door_room18_utility_room)
	(placelocation location_xpos4_yneg14_place53_room13_floorb place53_receptacle55_refrigerator)
	(placelocation location_xpos4_yneg27_place3_room13_floorb place3_door_room13_kitchen)
	(placelocation location_xpos5_yneg30_place8_room6_floorc place8_door_room6_bedroom)
	(placelocation location_xpos8_yneg43_place49_room13_floorb place49_receptacle51_sink)
	(receptacleatlocation receptacle11_chair location_xneg13_yneg33_place23_room13_floorb)
	(receptacleatlocation receptacle12_chair location_xneg28_yneg32_place24_room12_floorb)
	(receptacleatlocation receptacle13_chair location_xneg40_yneg32_place25_room12_floorb)
	(receptacleatlocation receptacle14_chair location_xneg41_yneg35_place26_room12_floorb)
	(receptacleatlocation receptacle15_chair location_xneg35_yneg38_place27_room12_floorb)
	(receptacleatlocation receptacle16_chair location_xneg38_yneg29_place28_room12_floorb)
	(receptacleatlocation receptacle17_chair location_xneg93_yneg22_place29_room7_floorc)
	(receptacleatlocation receptacle18_couch location_xneg86_yneg37_place30_room14_floorb)
	(receptacleatlocation receptacle19_couch location_xneg73_yneg16_place31_room14_floorb)
	(receptacleatlocation receptacle1_bench location_xneg77_ypos7_place20_room8_floorc)
	(receptacleatlocation receptacle20_couch location_xneg60_yneg38_place32_room14_floorb)
	(receptacleatlocation receptacle2_bench location_xneg76_ypos7_place21_room8_floorc)
	(receptacleatlocation receptacle34_bed location_xneg89_yneg34_place33_room5_floora)
	(receptacleatlocation receptacle35_bed location_xpos13_yneg34_place34_room6_floorc)
	(receptacleatlocation receptacle36_bed location_xneg58_yneg29_place35_room7_floorc)
	(receptacleatlocation receptacle37_bed location_xneg62_ypos0_place36_room8_floorc)
	(receptacleatlocation receptacle38_dining_table location_xneg9_yneg36_place37_room13_floorb)
	(receptacleatlocation receptacle39_dining_table location_xneg34_yneg32_place38_room12_floorb)
	(receptacleatlocation receptacle3_bench location_xneg78_ypos9_place22_room8_floorc)
	(receptacleatlocation receptacle40_dining_table location_xneg12_yneg43_place39_room13_floorb)
	(receptacleatlocation receptacle41_toilet location_xneg93_ypos3_place40_room1_floora)
	(receptacleatlocation receptacle42_toilet location_xpos21_yneg3_place41_room2_floorb)
	(receptacleatlocation receptacle43_toilet location_xpos21_yneg4_place42_room3_floorc)
	(receptacleatlocation receptacle44_toilet location_xneg20_yneg18_place43_room4_floorc)
	(receptacleatlocation receptacle46_microwave location_xpos22_yneg29_place44_room13_floorb)
	(receptacleatlocation receptacle47_oven location_xneg5_yneg29_place45_room13_floorb)
	(receptacleatlocation receptacle48_sink location_xneg86_ypos6_place46_room1_floora)
	(receptacleatlocation receptacle49_sink location_xneg100_ypos0_place47_room1_floora)
	(receptacleatlocation receptacle50_sink location_xpos14_yneg4_place48_room2_floorb)
	(receptacleatlocation receptacle51_sink location_xpos8_yneg43_place49_room13_floorb)
	(receptacleatlocation receptacle52_sink location_xneg42_yneg22_place50_room4_floorc)
	(receptacleatlocation receptacle53_sink location_xpos22_yneg12_place51_room3_floorc)
	(receptacleatlocation receptacle54_sink location_xneg36_yneg40_place52_room4_floorc)
	(receptacleatlocation receptacle55_refrigerator location_xpos4_yneg14_place53_room13_floorb)
	(receptacleopeningtype receptacle46_microwave)
	(receptacleopeningtype receptacle47_oven)
	(receptacleopeningtype receptacle55_refrigerator)
	(roomplace place0_door_room8_closet room8_closet)
	(roomplace place10_door_room2_bathroom room2_bathroom)
	(roomplace place11_door_room9_corridor room9_corridor)
	(roomplace place12_door_room10_corridor room10_corridor)
	(roomplace place13_door_room11_corridor room11_corridor)
	(roomplace place14_door_room15_lobby room15_lobby)
	(roomplace place15_door_room16_staircase room16_staircase)
	(roomplace place16_door_room17_staircase room17_staircase)
	(roomplace place17_door_room18_utility_room room18_utility_room)
	(roomplace place1_door_room4_bathroom room4_bathroom)
	(roomplace place2_door_room5_bedroom room5_bedroom)
	(roomplace place3_door_room13_kitchen room13_kitchen)
	(roomplace place4_door_room3_bathroom room3_bathroom)
	(roomplace place5_door_room12_dining_room room12_dining_room)
	(roomplace place6_door_room7_bedroom room7_bedroom)
	(roomplace place7_door_room14_living_room room14_living_room)
	(roomplace place8_door_room6_bedroom room6_bedroom)
	(roomplace place9_door_room1_bathroom room1_bathroom)
	(roomsconnected room10_corridor room12_dining_room)
	(roomsconnected room10_corridor room14_living_room)
	(roomsconnected room10_corridor room16_staircase)
	(roomsconnected room10_corridor room17_staircase)
	(roomsconnected room11_corridor room18_utility_room)
	(roomsconnected room11_corridor room4_bathroom)
	(roomsconnected room12_dining_room room10_corridor)
	(roomsconnected room12_dining_room room13_kitchen)
	(roomsconnected room13_kitchen room12_dining_room)
	(roomsconnected room13_kitchen room2_bathroom)
	(roomsconnected room14_living_room room10_corridor)
	(roomsconnected room15_lobby room9_corridor)
	(roomsconnected room16_staircase room10_corridor)
	(roomsconnected room16_staircase room9_corridor)
	(roomsconnected room17_staircase room10_corridor)
	(roomsconnected room18_utility_room room11_corridor)
	(roomsconnected room18_utility_room room3_bathroom)
	(roomsconnected room18_utility_room room6_bedroom)
	(roomsconnected room1_bathroom room5_bedroom)
	(roomsconnected room2_bathroom room13_kitchen)
	(roomsconnected room2_bathroom room3_bathroom)
	(roomsconnected room3_bathroom room18_utility_room)
	(roomsconnected room3_bathroom room2_bathroom)
	(roomsconnected room4_bathroom room11_corridor)
	(roomsconnected room4_bathroom room7_bedroom)
	(roomsconnected room5_bedroom room1_bathroom)
	(roomsconnected room5_bedroom room9_corridor)
	(roomsconnected room6_bedroom room18_utility_room)
	(roomsconnected room7_bedroom room4_bathroom)
	(roomsconnected room7_bedroom room8_closet)
	(roomsconnected room8_closet room7_bedroom)
	(roomsconnected room9_corridor room15_lobby)
	(roomsconnected room9_corridor room16_staircase)
	(roomsconnected room9_corridor room5_bedroom)
	(smallitem item10_apple_smallitem)
	(smallitem item45_mouse_smallitem)
	(smallitem item56_book_smallitem)
	(smallitem item57_book_smallitem)
	(smallitem item58_book_smallitem)
	(smallitem item59_book_smallitem)
	(smallitem item5_bottle_smallitem)
	(smallitem item60_book_smallitem)
	(smallitem item61_book_smallitem)
	(smallitem item6_bottle_smallitem)
	(smallitem item7_bottle_smallitem)
	(smallitem item8_cup_smallitem)
	(smallitem item9_spoon_smallitem)
  )
  (:goal (and
	(inreceptacle item23_potted_plant_largeitem receptacle12_chair)
	(inreceptacle item66_vase_mediumitem receptacle13_chair)
	(inreceptacle item7_bottle_smallitem receptacle47_oven)
	(inreceptacle item27_potted_plant_largeitem receptacle1_bench)
	(inreceptacle item4_kite_largeitem receptacle3_bench)
	(inreceptacle item25_potted_plant_largeitem receptacle15_chair)
	(inreceptacle item29_potted_plant_largeitem receptacle1_bench)
	(inreceptacle item26_potted_plant_largeitem receptacle38_dining_table)
	(inreceptacle item65_vase_mediumitem receptacle39_dining_table)
	(inreceptacle item30_potted_plant_largeitem receptacle35_bed)))
)
