
(define (problem onagataskographyv5tiny5bagslots5problem105) (:domain taskographyv5tiny5bagslots5scrub)
  (:objects
        bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	bed - rclass
	book - iclass
	bottle - iclass
	chair - rclass
	couch - rclass
	item10_book_smallitem - item
	item11_book_smallitem - item
	item12_book_smallitem - item
	item16_vase_mediumitem - item
	item17_vase_mediumitem - item
	item18_vase_mediumitem - item
	item20_orange_smallitem - item
	item21_orange_smallitem - item
	item22_orange_smallitem - item
	item39_potted_plant_largeitem - item
	item3_bottle_smallitem - item
	item41_potted_plant_largeitem - item
	item42_potted_plant_largeitem - item
	item43_potted_plant_largeitem - item
	item44_potted_plant_largeitem - item
	item45_potted_plant_largeitem - item
	item46_potted_plant_largeitem - item
	item47_potted_plant_largeitem - item
	item48_potted_plant_largeitem - item
	item49_potted_plant_largeitem - item
	item4_bottle_smallitem - item
	item50_potted_plant_largeitem - item
	item5_bottle_smallitem - item
	item6_bottle_smallitem - item
	item7_bottle_smallitem - item
	item9_book_smallitem - item
	location_xneg11_ypos38_place25_room3_floorb - location
	location_xneg13_ypos21_place32_room10_floora - location
	location_xneg14_yneg12_place34_room9_floora - location
	location_xneg14_yneg19_place35_room9_floora - location
	location_xneg14_ypos21_place31_room10_floora - location
	location_xneg14_ypos42_place5_room3_floorb - location
	location_xneg16_yneg10_place41_room9_floora - location
	location_xneg16_yneg11_place41_room9_floora - location
	location_xneg16_yneg13_place34_room9_floora - location
	location_xneg16_ypos66_place39_room4_floorb - location
	location_xneg17_yneg12_place34_room9_floora - location
	location_xneg18_ypos49_place38_room10_floora - location
	location_xneg19_yneg13_place33_room9_floora - location
	location_xneg1_ypos36_place38_room10_floora - location
	location_xneg1_ypos56_place39_room4_floorb - location
	location_xneg22_ypos67_place1_room4_floorb - location
	location_xneg23_yneg12_place13_room5_floorb - location
	location_xneg23_yneg4_place16_room5_floorb - location
	location_xneg23_ypos44_place7_room10_floora - location
	location_xneg24_yneg10_place14_room5_floorb - location
	location_xneg24_yneg10_place15_room5_floorb - location
	location_xneg24_ypos38_place23_room3_floorb - location
	location_xneg25_ypos31_place9_room7_floorb - location
	location_xneg29_ypos64_place28_room10_floora - location
	location_xneg2_yneg13_place36_room8_floorb - location
	location_xneg2_ypos20_place30_room10_floora - location
	location_xneg2_ypos77_place39_room4_floorb - location
	location_xneg30_yneg3_place8_room6_floora - location
	location_xneg32_ypos67_place29_room10_floora - location
	location_xneg35_yneg7_place3_room5_floorb - location
	location_xneg39_yneg6_place22_room1_floora - location
	location_xneg3_yneg1_place0_room9_floora - location
	location_xneg3_yneg1_place4_room8_floorb - location
	location_xneg3_ypos57_place39_room4_floorb - location
	location_xneg41_yneg4_place22_room1_floora - location
	location_xneg42_yneg12_place2_room1_floora - location
	location_xneg42_yneg4_place22_room1_floora - location
	location_xneg44_yneg1_place40_room5_floorb - location
	location_xneg44_ypos25_place10_room11_floora - location
	location_xneg44_ypos56_place28_room10_floora - location
	location_xneg46_yneg6_place26_room1_floora - location
	location_xneg5_ypos20_place30_room10_floora - location
	location_xneg6_ypos31_place24_room2_floorb - location
	location_xneg6_ypos46_place38_room10_floora - location
	location_xpos0_yneg15_place37_room8_floorb - location
	location_xpos0_ypos16_place11_room9_floora - location
	location_xpos0_ypos58_place39_room4_floorb - location
	location_xpos11_yneg15_place36_room8_floorb - location
	location_xpos11_yneg2_place20_room9_floora - location
	location_xpos13_ypos16_place20_room9_floora - location
	location_xpos14_yneg14_place36_room8_floorb - location
	location_xpos14_yneg16_place37_room8_floorb - location
	location_xpos14_yneg17_place17_room8_floorb - location
	location_xpos1_yneg19_place36_room8_floorb - location
	location_xpos1_ypos17_place12_room9_floora - location
	location_xpos2_ypos27_place6_room2_floorb - location
	location_xpos2_ypos31_place27_room2_floorb - location
	location_xpos3_ypos16_place20_room9_floora - location
	location_xpos7_yneg15_place21_room9_floora - location
	orange - iclass
	oven - rclass
	place0_door_room9_kitchen - place
	place10_door_room11_staircase - place
	place11_item4_bottle - place
	place12_item5_bottle - place
	place13_item9_book - place
	place14_item10_book - place
	place15_item11_book - place
	place16_item43_potted_plant - place
	place17_item47_potted_plant - place
	place1_door_room4_bedroom - place
	place20_receptacle2_oven - place
	place21_receptacle8_refrigerator - place
	place22_receptacle13_sink - place
	place23_receptacle14_sink - place
	place24_receptacle15_sink - place
	place25_receptacle23_toilet - place
	place26_receptacle24_toilet - place
	place27_receptacle25_toilet - place
	place28_receptacle26_chair - place
	place29_receptacle27_chair - place
	place2_door_room1_bathroom - place
	place30_receptacle28_chair - place
	place31_receptacle29_chair - place
	place32_receptacle30_chair - place
	place33_receptacle31_chair - place
	place34_receptacle32_chair - place
	place35_receptacle33_chair - place
	place36_receptacle36_chair - place
	place37_receptacle37_chair - place
	place38_receptacle38_couch - place
	place39_receptacle51_bed - place
	place3_door_room5_childs_room - place
	place40_receptacle52_bed - place
	place41_receptacle53_dining_table - place
	place4_door_room8_home_office - place
	place5_door_room3_bathroom - place
	place6_door_room2_bathroom - place
	place7_door_room10_living_room - place
	place8_door_room6_corridor - place
	place9_door_room7_corridor - place
	pottedplant - iclass
	receptacle13_sink - receptacle
	receptacle14_sink - receptacle
	receptacle15_sink - receptacle
	receptacle23_toilet - receptacle
	receptacle24_toilet - receptacle
	receptacle25_toilet - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle2_oven - receptacle
	receptacle30_chair - receptacle
	receptacle31_chair - receptacle
	receptacle32_chair - receptacle
	receptacle33_chair - receptacle
	receptacle36_chair - receptacle
	receptacle37_chair - receptacle
	receptacle38_couch - receptacle
	receptacle51_bed - receptacle
	receptacle52_bed - receptacle
	receptacle53_dining_table - receptacle
	receptacle8_refrigerator - receptacle
	refrigerator - rclass
	robot - agent
	room10_living_room - room
	room11_staircase - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_childs_room - room
	room6_corridor - room
	room7_corridor - room
	room8_home_office - room
	room9_kitchen - room
	sink - rclass
	toilet - rclass
	vase - iclass
  )
  (:init 
	(atlocation robot location_xneg3_yneg1_place0_room9_floora)
	(classrelation book chair)
	(classrelation bottle bed)
	(classrelation bottle oven)
	(classrelation bottle sink)
	(classrelation orange chair)
	(classrelation pottedplant chair)
	(classrelation pottedplant couch)
	(classrelation pottedplant oven)
	(classrelation pottedplant sink)
	(classrelation vase bed)
	(inanyreceptacle item12_book_smallitem)
	(inanyreceptacle item16_vase_mediumitem)
	(inanyreceptacle item17_vase_mediumitem)
	(inanyreceptacle item18_vase_mediumitem)
	(inanyreceptacle item20_orange_smallitem)
	(inanyreceptacle item21_orange_smallitem)
	(inanyreceptacle item22_orange_smallitem)
	(inanyreceptacle item39_potted_plant_largeitem)
	(inanyreceptacle item3_bottle_smallitem)
	(inanyreceptacle item41_potted_plant_largeitem)
	(inanyreceptacle item42_potted_plant_largeitem)
	(inanyreceptacle item44_potted_plant_largeitem)
	(inanyreceptacle item45_potted_plant_largeitem)
	(inanyreceptacle item46_potted_plant_largeitem)
	(inanyreceptacle item48_potted_plant_largeitem)
	(inanyreceptacle item49_potted_plant_largeitem)
	(inanyreceptacle item50_potted_plant_largeitem)
	(inanyreceptacle item6_bottle_smallitem)
	(inanyreceptacle item7_bottle_smallitem)
	(inplace robot place0_door_room9_kitchen)
	(inreceptacle item12_book_smallitem receptacle36_chair)
	(inreceptacle item16_vase_mediumitem receptacle51_bed)
	(inreceptacle item17_vase_mediumitem receptacle51_bed)
	(inreceptacle item18_vase_mediumitem receptacle51_bed)
	(inreceptacle item20_orange_smallitem receptacle53_dining_table)
	(inreceptacle item21_orange_smallitem receptacle32_chair)
	(inreceptacle item22_orange_smallitem receptacle32_chair)
	(inreceptacle item39_potted_plant_largeitem receptacle26_chair)
	(inreceptacle item3_bottle_smallitem receptacle2_oven)
	(inreceptacle item41_potted_plant_largeitem receptacle38_couch)
	(inreceptacle item42_potted_plant_largeitem receptacle28_chair)
	(inreceptacle item44_potted_plant_largeitem receptacle36_chair)
	(inreceptacle item45_potted_plant_largeitem receptacle36_chair)
	(inreceptacle item46_potted_plant_largeitem receptacle37_chair)
	(inreceptacle item48_potted_plant_largeitem receptacle13_sink)
	(inreceptacle item49_potted_plant_largeitem receptacle38_couch)
	(inreceptacle item50_potted_plant_largeitem receptacle2_oven)
	(inreceptacle item6_bottle_smallitem receptacle51_bed)
	(inreceptacle item7_bottle_smallitem receptacle13_sink)
	(inroom robot room9_kitchen)
	(itematlocation item10_book_smallitem location_xneg24_yneg10_place14_room5_floorb)
	(itematlocation item11_book_smallitem location_xneg24_yneg10_place15_room5_floorb)
	(itematlocation item12_book_smallitem location_xpos1_yneg19_place36_room8_floorb)
	(itematlocation item16_vase_mediumitem location_xneg3_ypos57_place39_room4_floorb)
	(itematlocation item17_vase_mediumitem location_xpos0_ypos58_place39_room4_floorb)
	(itematlocation item18_vase_mediumitem location_xneg1_ypos56_place39_room4_floorb)
	(itematlocation item20_orange_smallitem location_xneg16_yneg11_place41_room9_floora)
	(itematlocation item21_orange_smallitem location_xneg17_yneg12_place34_room9_floora)
	(itematlocation item22_orange_smallitem location_xneg16_yneg13_place34_room9_floora)
	(itematlocation item39_potted_plant_largeitem location_xneg44_ypos56_place28_room10_floora)
	(itematlocation item3_bottle_smallitem location_xpos3_ypos16_place20_room9_floora)
	(itematlocation item41_potted_plant_largeitem location_xneg18_ypos49_place38_room10_floora)
	(itematlocation item42_potted_plant_largeitem location_xneg2_ypos20_place30_room10_floora)
	(itematlocation item43_potted_plant_largeitem location_xneg23_yneg4_place16_room5_floorb)
	(itematlocation item44_potted_plant_largeitem location_xpos11_yneg15_place36_room8_floorb)
	(itematlocation item45_potted_plant_largeitem location_xpos14_yneg14_place36_room8_floorb)
	(itematlocation item46_potted_plant_largeitem location_xpos14_yneg16_place37_room8_floorb)
	(itematlocation item47_potted_plant_largeitem location_xpos14_yneg17_place17_room8_floorb)
	(itematlocation item48_potted_plant_largeitem location_xneg41_yneg4_place22_room1_floora)
	(itematlocation item49_potted_plant_largeitem location_xneg1_ypos36_place38_room10_floora)
	(itematlocation item4_bottle_smallitem location_xpos0_ypos16_place11_room9_floora)
	(itematlocation item50_potted_plant_largeitem location_xpos13_ypos16_place20_room9_floora)
	(itematlocation item5_bottle_smallitem location_xpos1_ypos17_place12_room9_floora)
	(itematlocation item6_bottle_smallitem location_xneg2_ypos77_place39_room4_floorb)
	(itematlocation item7_bottle_smallitem location_xneg42_yneg4_place22_room1_floora)
	(itematlocation item9_book_smallitem location_xneg23_yneg12_place13_room5_floorb)
	(itemclass item10_book_smallitem book)
	(itemclass item11_book_smallitem book)
	(itemclass item12_book_smallitem book)
	(itemclass item16_vase_mediumitem vase)
	(itemclass item17_vase_mediumitem vase)
	(itemclass item18_vase_mediumitem vase)
	(itemclass item20_orange_smallitem orange)
	(itemclass item21_orange_smallitem orange)
	(itemclass item22_orange_smallitem orange)
	(itemclass item39_potted_plant_largeitem pottedplant)
	(itemclass item3_bottle_smallitem bottle)
	(itemclass item41_potted_plant_largeitem pottedplant)
	(itemclass item42_potted_plant_largeitem pottedplant)
	(itemclass item43_potted_plant_largeitem pottedplant)
	(itemclass item44_potted_plant_largeitem pottedplant)
	(itemclass item45_potted_plant_largeitem pottedplant)
	(itemclass item46_potted_plant_largeitem pottedplant)
	(itemclass item47_potted_plant_largeitem pottedplant)
	(itemclass item48_potted_plant_largeitem pottedplant)
	(itemclass item49_potted_plant_largeitem pottedplant)
	(itemclass item4_bottle_smallitem bottle)
	(itemclass item50_potted_plant_largeitem pottedplant)
	(itemclass item5_bottle_smallitem bottle)
	(itemclass item6_bottle_smallitem bottle)
	(itemclass item7_bottle_smallitem bottle)
	(itemclass item9_book_smallitem book)
	(largeitem item39_potted_plant_largeitem)
	(largeitem item41_potted_plant_largeitem)
	(largeitem item42_potted_plant_largeitem)
	(largeitem item43_potted_plant_largeitem)
	(largeitem item44_potted_plant_largeitem)
	(largeitem item45_potted_plant_largeitem)
	(largeitem item46_potted_plant_largeitem)
	(largeitem item47_potted_plant_largeitem)
	(largeitem item48_potted_plant_largeitem)
	(largeitem item49_potted_plant_largeitem)
	(largeitem item50_potted_plant_largeitem)
	(locationinplace location_xneg11_ypos38_place25_room3_floorb place25_receptacle23_toilet)
	(locationinplace location_xneg13_ypos21_place32_room10_floora place32_receptacle30_chair)
	(locationinplace location_xneg14_yneg12_place34_room9_floora place34_receptacle32_chair)
	(locationinplace location_xneg14_yneg19_place35_room9_floora place35_receptacle33_chair)
	(locationinplace location_xneg14_ypos21_place31_room10_floora place31_receptacle29_chair)
	(locationinplace location_xneg14_ypos42_place5_room3_floorb place5_door_room3_bathroom)
	(locationinplace location_xneg16_yneg10_place41_room9_floora place41_receptacle53_dining_table)
	(locationinplace location_xneg16_yneg11_place41_room9_floora place41_receptacle53_dining_table)
	(locationinplace location_xneg16_yneg13_place34_room9_floora place34_receptacle32_chair)
	(locationinplace location_xneg16_ypos66_place39_room4_floorb place39_receptacle51_bed)
	(locationinplace location_xneg17_yneg12_place34_room9_floora place34_receptacle32_chair)
	(locationinplace location_xneg18_ypos49_place38_room10_floora place38_receptacle38_couch)
	(locationinplace location_xneg19_yneg13_place33_room9_floora place33_receptacle31_chair)
	(locationinplace location_xneg1_ypos36_place38_room10_floora place38_receptacle38_couch)
	(locationinplace location_xneg1_ypos56_place39_room4_floorb place39_receptacle51_bed)
	(locationinplace location_xneg22_ypos67_place1_room4_floorb place1_door_room4_bedroom)
	(locationinplace location_xneg23_yneg12_place13_room5_floorb place13_item9_book)
	(locationinplace location_xneg23_yneg4_place16_room5_floorb place16_item43_potted_plant)
	(locationinplace location_xneg23_ypos44_place7_room10_floora place7_door_room10_living_room)
	(locationinplace location_xneg24_yneg10_place14_room5_floorb place14_item10_book)
	(locationinplace location_xneg24_yneg10_place15_room5_floorb place15_item11_book)
	(locationinplace location_xneg24_ypos38_place23_room3_floorb place23_receptacle14_sink)
	(locationinplace location_xneg25_ypos31_place9_room7_floorb place9_door_room7_corridor)
	(locationinplace location_xneg29_ypos64_place28_room10_floora place28_receptacle26_chair)
	(locationinplace location_xneg2_yneg13_place36_room8_floorb place36_receptacle36_chair)
	(locationinplace location_xneg2_ypos20_place30_room10_floora place30_receptacle28_chair)
	(locationinplace location_xneg2_ypos77_place39_room4_floorb place39_receptacle51_bed)
	(locationinplace location_xneg30_yneg3_place8_room6_floora place8_door_room6_corridor)
	(locationinplace location_xneg32_ypos67_place29_room10_floora place29_receptacle27_chair)
	(locationinplace location_xneg35_yneg7_place3_room5_floorb place3_door_room5_childs_room)
	(locationinplace location_xneg39_yneg6_place22_room1_floora place22_receptacle13_sink)
	(locationinplace location_xneg3_yneg1_place0_room9_floora place0_door_room9_kitchen)
	(locationinplace location_xneg3_yneg1_place4_room8_floorb place4_door_room8_home_office)
	(locationinplace location_xneg3_ypos57_place39_room4_floorb place39_receptacle51_bed)
	(locationinplace location_xneg41_yneg4_place22_room1_floora place22_receptacle13_sink)
	(locationinplace location_xneg42_yneg12_place2_room1_floora place2_door_room1_bathroom)
	(locationinplace location_xneg42_yneg4_place22_room1_floora place22_receptacle13_sink)
	(locationinplace location_xneg44_yneg1_place40_room5_floorb place40_receptacle52_bed)
	(locationinplace location_xneg44_ypos25_place10_room11_floora place10_door_room11_staircase)
	(locationinplace location_xneg44_ypos56_place28_room10_floora place28_receptacle26_chair)
	(locationinplace location_xneg46_yneg6_place26_room1_floora place26_receptacle24_toilet)
	(locationinplace location_xneg5_ypos20_place30_room10_floora place30_receptacle28_chair)
	(locationinplace location_xneg6_ypos31_place24_room2_floorb place24_receptacle15_sink)
	(locationinplace location_xneg6_ypos46_place38_room10_floora place38_receptacle38_couch)
	(locationinplace location_xpos0_yneg15_place37_room8_floorb place37_receptacle37_chair)
	(locationinplace location_xpos0_ypos16_place11_room9_floora place11_item4_bottle)
	(locationinplace location_xpos0_ypos58_place39_room4_floorb place39_receptacle51_bed)
	(locationinplace location_xpos11_yneg15_place36_room8_floorb place36_receptacle36_chair)
	(locationinplace location_xpos11_yneg2_place20_room9_floora place20_receptacle2_oven)
	(locationinplace location_xpos13_ypos16_place20_room9_floora place20_receptacle2_oven)
	(locationinplace location_xpos14_yneg14_place36_room8_floorb place36_receptacle36_chair)
	(locationinplace location_xpos14_yneg16_place37_room8_floorb place37_receptacle37_chair)
	(locationinplace location_xpos14_yneg17_place17_room8_floorb place17_item47_potted_plant)
	(locationinplace location_xpos1_yneg19_place36_room8_floorb place36_receptacle36_chair)
	(locationinplace location_xpos1_ypos17_place12_room9_floora place12_item5_bottle)
	(locationinplace location_xpos2_ypos27_place6_room2_floorb place6_door_room2_bathroom)
	(locationinplace location_xpos2_ypos31_place27_room2_floorb place27_receptacle25_toilet)
	(locationinplace location_xpos3_ypos16_place20_room9_floora place20_receptacle2_oven)
	(locationinplace location_xpos7_yneg15_place21_room9_floora place21_receptacle8_refrigerator)
	(mediumitem item16_vase_mediumitem)
	(mediumitem item17_vase_mediumitem)
	(mediumitem item18_vase_mediumitem)
	(placeinroom place0_door_room9_kitchen room9_kitchen)
	(placeinroom place10_door_room11_staircase room11_staircase)
	(placeinroom place11_item4_bottle room9_kitchen)
	(placeinroom place12_item5_bottle room9_kitchen)
	(placeinroom place13_item9_book room5_childs_room)
	(placeinroom place14_item10_book room5_childs_room)
	(placeinroom place15_item11_book room5_childs_room)
	(placeinroom place16_item43_potted_plant room5_childs_room)
	(placeinroom place17_item47_potted_plant room8_home_office)
	(placeinroom place1_door_room4_bedroom room4_bedroom)
	(placeinroom place20_receptacle2_oven room9_kitchen)
	(placeinroom place21_receptacle8_refrigerator room9_kitchen)
	(placeinroom place22_receptacle13_sink room1_bathroom)
	(placeinroom place23_receptacle14_sink room3_bathroom)
	(placeinroom place24_receptacle15_sink room2_bathroom)
	(placeinroom place25_receptacle23_toilet room3_bathroom)
	(placeinroom place26_receptacle24_toilet room1_bathroom)
	(placeinroom place27_receptacle25_toilet room2_bathroom)
	(placeinroom place28_receptacle26_chair room10_living_room)
	(placeinroom place29_receptacle27_chair room10_living_room)
	(placeinroom place2_door_room1_bathroom room1_bathroom)
	(placeinroom place30_receptacle28_chair room10_living_room)
	(placeinroom place31_receptacle29_chair room10_living_room)
	(placeinroom place32_receptacle30_chair room10_living_room)
	(placeinroom place33_receptacle31_chair room9_kitchen)
	(placeinroom place34_receptacle32_chair room9_kitchen)
	(placeinroom place35_receptacle33_chair room9_kitchen)
	(placeinroom place36_receptacle36_chair room8_home_office)
	(placeinroom place37_receptacle37_chair room8_home_office)
	(placeinroom place38_receptacle38_couch room10_living_room)
	(placeinroom place39_receptacle51_bed room4_bedroom)
	(placeinroom place3_door_room5_childs_room room5_childs_room)
	(placeinroom place40_receptacle52_bed room5_childs_room)
	(placeinroom place41_receptacle53_dining_table room9_kitchen)
	(placeinroom place4_door_room8_home_office room8_home_office)
	(placeinroom place5_door_room3_bathroom room3_bathroom)
	(placeinroom place6_door_room2_bathroom room2_bathroom)
	(placeinroom place7_door_room10_living_room room10_living_room)
	(placeinroom place8_door_room6_corridor room6_corridor)
	(placeinroom place9_door_room7_corridor room7_corridor)
	(placelocation location_xneg11_ypos38_place25_room3_floorb place25_receptacle23_toilet)
	(placelocation location_xneg13_ypos21_place32_room10_floora place32_receptacle30_chair)
	(placelocation location_xneg14_yneg12_place34_room9_floora place34_receptacle32_chair)
	(placelocation location_xneg14_yneg19_place35_room9_floora place35_receptacle33_chair)
	(placelocation location_xneg14_ypos21_place31_room10_floora place31_receptacle29_chair)
	(placelocation location_xneg14_ypos42_place5_room3_floorb place5_door_room3_bathroom)
	(placelocation location_xneg16_yneg10_place41_room9_floora place41_receptacle53_dining_table)
	(placelocation location_xneg16_ypos66_place39_room4_floorb place39_receptacle51_bed)
	(placelocation location_xneg19_yneg13_place33_room9_floora place33_receptacle31_chair)
	(placelocation location_xneg22_ypos67_place1_room4_floorb place1_door_room4_bedroom)
	(placelocation location_xneg23_yneg12_place13_room5_floorb place13_item9_book)
	(placelocation location_xneg23_yneg4_place16_room5_floorb place16_item43_potted_plant)
	(placelocation location_xneg23_ypos44_place7_room10_floora place7_door_room10_living_room)
	(placelocation location_xneg24_yneg10_place14_room5_floorb place14_item10_book)
	(placelocation location_xneg24_yneg10_place15_room5_floorb place15_item11_book)
	(placelocation location_xneg24_ypos38_place23_room3_floorb place23_receptacle14_sink)
	(placelocation location_xneg25_ypos31_place9_room7_floorb place9_door_room7_corridor)
	(placelocation location_xneg29_ypos64_place28_room10_floora place28_receptacle26_chair)
	(placelocation location_xneg2_yneg13_place36_room8_floorb place36_receptacle36_chair)
	(placelocation location_xneg30_yneg3_place8_room6_floora place8_door_room6_corridor)
	(placelocation location_xneg32_ypos67_place29_room10_floora place29_receptacle27_chair)
	(placelocation location_xneg35_yneg7_place3_room5_floorb place3_door_room5_childs_room)
	(placelocation location_xneg39_yneg6_place22_room1_floora place22_receptacle13_sink)
	(placelocation location_xneg3_yneg1_place0_room9_floora place0_door_room9_kitchen)
	(placelocation location_xneg3_yneg1_place4_room8_floorb place4_door_room8_home_office)
	(placelocation location_xneg42_yneg12_place2_room1_floora place2_door_room1_bathroom)
	(placelocation location_xneg44_yneg1_place40_room5_floorb place40_receptacle52_bed)
	(placelocation location_xneg44_ypos25_place10_room11_floora place10_door_room11_staircase)
	(placelocation location_xneg46_yneg6_place26_room1_floora place26_receptacle24_toilet)
	(placelocation location_xneg5_ypos20_place30_room10_floora place30_receptacle28_chair)
	(placelocation location_xneg6_ypos31_place24_room2_floorb place24_receptacle15_sink)
	(placelocation location_xneg6_ypos46_place38_room10_floora place38_receptacle38_couch)
	(placelocation location_xpos0_yneg15_place37_room8_floorb place37_receptacle37_chair)
	(placelocation location_xpos0_ypos16_place11_room9_floora place11_item4_bottle)
	(placelocation location_xpos11_yneg2_place20_room9_floora place20_receptacle2_oven)
	(placelocation location_xpos14_yneg17_place17_room8_floorb place17_item47_potted_plant)
	(placelocation location_xpos1_ypos17_place12_room9_floora place12_item5_bottle)
	(placelocation location_xpos2_ypos27_place6_room2_floorb place6_door_room2_bathroom)
	(placelocation location_xpos2_ypos31_place27_room2_floorb place27_receptacle25_toilet)
	(placelocation location_xpos7_yneg15_place21_room9_floora place21_receptacle8_refrigerator)
	(receptacleatlocation receptacle13_sink location_xneg39_yneg6_place22_room1_floora)
	(receptacleatlocation receptacle14_sink location_xneg24_ypos38_place23_room3_floorb)
	(receptacleatlocation receptacle15_sink location_xneg6_ypos31_place24_room2_floorb)
	(receptacleatlocation receptacle23_toilet location_xneg11_ypos38_place25_room3_floorb)
	(receptacleatlocation receptacle24_toilet location_xneg46_yneg6_place26_room1_floora)
	(receptacleatlocation receptacle25_toilet location_xpos2_ypos31_place27_room2_floorb)
	(receptacleatlocation receptacle26_chair location_xneg29_ypos64_place28_room10_floora)
	(receptacleatlocation receptacle27_chair location_xneg32_ypos67_place29_room10_floora)
	(receptacleatlocation receptacle28_chair location_xneg5_ypos20_place30_room10_floora)
	(receptacleatlocation receptacle29_chair location_xneg14_ypos21_place31_room10_floora)
	(receptacleatlocation receptacle2_oven location_xpos11_yneg2_place20_room9_floora)
	(receptacleatlocation receptacle30_chair location_xneg13_ypos21_place32_room10_floora)
	(receptacleatlocation receptacle31_chair location_xneg19_yneg13_place33_room9_floora)
	(receptacleatlocation receptacle32_chair location_xneg14_yneg12_place34_room9_floora)
	(receptacleatlocation receptacle33_chair location_xneg14_yneg19_place35_room9_floora)
	(receptacleatlocation receptacle36_chair location_xneg2_yneg13_place36_room8_floorb)
	(receptacleatlocation receptacle37_chair location_xpos0_yneg15_place37_room8_floorb)
	(receptacleatlocation receptacle38_couch location_xneg6_ypos46_place38_room10_floora)
	(receptacleatlocation receptacle51_bed location_xneg16_ypos66_place39_room4_floorb)
	(receptacleatlocation receptacle52_bed location_xneg44_yneg1_place40_room5_floorb)
	(receptacleatlocation receptacle53_dining_table location_xneg16_yneg10_place41_room9_floora)
	(receptacleatlocation receptacle8_refrigerator location_xpos7_yneg15_place21_room9_floora)
	(receptacleclass receptacle13_sink sink)
	(receptacleclass receptacle14_sink sink)
	(receptacleclass receptacle15_sink sink)
	(receptacleclass receptacle23_toilet toilet)
	(receptacleclass receptacle24_toilet toilet)
	(receptacleclass receptacle25_toilet toilet)
	(receptacleclass receptacle26_chair chair)
	(receptacleclass receptacle27_chair chair)
	(receptacleclass receptacle28_chair chair)
	(receptacleclass receptacle29_chair chair)
	(receptacleclass receptacle2_oven oven)
	(receptacleclass receptacle30_chair chair)
	(receptacleclass receptacle31_chair chair)
	(receptacleclass receptacle32_chair chair)
	(receptacleclass receptacle33_chair chair)
	(receptacleclass receptacle36_chair chair)
	(receptacleclass receptacle37_chair chair)
	(receptacleclass receptacle38_couch couch)
	(receptacleclass receptacle51_bed bed)
	(receptacleclass receptacle52_bed bed)
	(receptacleclass receptacle8_refrigerator refrigerator)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle8_refrigerator)
	(roomplace place0_door_room9_kitchen room9_kitchen)
	(roomplace place10_door_room11_staircase room11_staircase)
	(roomplace place1_door_room4_bedroom room4_bedroom)
	(roomplace place2_door_room1_bathroom room1_bathroom)
	(roomplace place3_door_room5_childs_room room5_childs_room)
	(roomplace place4_door_room8_home_office room8_home_office)
	(roomplace place5_door_room3_bathroom room3_bathroom)
	(roomplace place6_door_room2_bathroom room2_bathroom)
	(roomplace place7_door_room10_living_room room10_living_room)
	(roomplace place8_door_room6_corridor room6_corridor)
	(roomplace place9_door_room7_corridor room7_corridor)
	(roomsconnected room10_living_room room11_staircase)
	(roomsconnected room11_staircase room10_living_room)
	(roomsconnected room11_staircase room6_corridor)
	(roomsconnected room11_staircase room7_corridor)
	(roomsconnected room1_bathroom room6_corridor)
	(roomsconnected room2_bathroom room3_bathroom)
	(roomsconnected room2_bathroom room8_home_office)
	(roomsconnected room3_bathroom room2_bathroom)
	(roomsconnected room3_bathroom room4_bedroom)
	(roomsconnected room3_bathroom room7_corridor)
	(roomsconnected room4_bedroom room3_bathroom)
	(roomsconnected room5_childs_room room8_home_office)
	(roomsconnected room6_corridor room11_staircase)
	(roomsconnected room6_corridor room1_bathroom)
	(roomsconnected room6_corridor room9_kitchen)
	(roomsconnected room7_corridor room11_staircase)
	(roomsconnected room7_corridor room3_bathroom)
	(roomsconnected room8_home_office room2_bathroom)
	(roomsconnected room8_home_office room5_childs_room)
	(roomsconnected room9_kitchen room6_corridor)
	(smallitem item10_book_smallitem)
	(smallitem item11_book_smallitem)
	(smallitem item12_book_smallitem)
	(smallitem item20_orange_smallitem)
	(smallitem item21_orange_smallitem)
	(smallitem item22_orange_smallitem)
	(smallitem item3_bottle_smallitem)
	(smallitem item4_bottle_smallitem)
	(smallitem item5_bottle_smallitem)
	(smallitem item6_bottle_smallitem)
	(smallitem item7_bottle_smallitem)
	(smallitem item9_book_smallitem)
  )
  (:goal (and
	(classrelation pottedplant bed)
	(classrelation book bed)
	(classrelation vase toilet)
	(classrelation bottle chair)
	(classrelation book refrigerator)))
)
