
(define (problem springervilletaskographyv2medium1problem63) (:domain taskographyv2medium1scrub)
  (:objects
        item19_bottle_smallitem - item
	location_xneg17_ypos40_place1_room2_floorb - location
	location_xneg17_ypos54_place18_room2_floorb - location
	location_xneg18_ypos55_place18_room2_floorb - location
	location_xneg26_ypos41_place3_room8_floora - location
	location_xneg28_yneg8_place19_room9_floora - location
	location_xneg28_ypos6_place0_room9_floora - location
	location_xneg4_ypos5_place5_room13_floora - location
	location_xneg7_ypos6_place4_room4_floorb - location
	location_xpos11_ypos44_place6_room11_floora - location
	location_xpos18_ypos30_place10_room5_floora - location
	location_xpos1_ypos31_place2_room1_floora - location
	location_xpos22_ypos36_place12_room12_floora - location
	location_xpos29_ypos6_place9_room7_floora - location
	location_xpos32_ypos4_place7_room3_floorb - location
	location_xpos39_ypos66_place8_room10_floora - location
	location_xpos6_ypos31_place11_room6_floorb - location
	place0_door_room9_kitchen - place
	place10_door_room5_corridor - place
	place11_door_room6_corridor - place
	place12_door_room12_staircase - place
	place18_receptacle5_sink - place
	place19_receptacle6_sink - place
	place1_door_room2_bathroom - place
	place2_door_room1_bathroom - place
	place3_door_room8_home_office - place
	place4_door_room4_bedroom - place
	place5_door_room13_utility_room - place
	place6_door_room11_staircase - place
	place7_door_room3_bedroom - place
	place8_door_room10_living-room - place
	place9_door_room7_dining_room - place
	receptacle5_sink - receptacle
	receptacle6_sink - receptacle
	robot - agent
	room10_living-room - room
	room11_staircase - room
	room12_staircase - room
	room13_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bedroom - room
	room4_bedroom - room
	room5_corridor - room
	room6_corridor - room
	room7_dining_room - room
	room8_home_office - room
	room9_kitchen - room
  )
  (:init 
	(atlocation robot location_xpos22_ypos36_place12_room12_floora)
	(inanyreceptacle item19_bottle_smallitem)
	(inplace robot place12_door_room12_staircase)
	(inreceptacle item19_bottle_smallitem receptacle5_sink)
	(inroom robot room12_staircase)
	(itematlocation item19_bottle_smallitem location_xneg18_ypos55_place18_room2_floorb)
	(locationinplace location_xneg17_ypos40_place1_room2_floorb place1_door_room2_bathroom)
	(locationinplace location_xneg17_ypos54_place18_room2_floorb place18_receptacle5_sink)
	(locationinplace location_xneg18_ypos55_place18_room2_floorb place18_receptacle5_sink)
	(locationinplace location_xneg26_ypos41_place3_room8_floora place3_door_room8_home_office)
	(locationinplace location_xneg28_yneg8_place19_room9_floora place19_receptacle6_sink)
	(locationinplace location_xneg28_ypos6_place0_room9_floora place0_door_room9_kitchen)
	(locationinplace location_xneg4_ypos5_place5_room13_floora place5_door_room13_utility_room)
	(locationinplace location_xneg7_ypos6_place4_room4_floorb place4_door_room4_bedroom)
	(locationinplace location_xpos11_ypos44_place6_room11_floora place6_door_room11_staircase)
	(locationinplace location_xpos18_ypos30_place10_room5_floora place10_door_room5_corridor)
	(locationinplace location_xpos1_ypos31_place2_room1_floora place2_door_room1_bathroom)
	(locationinplace location_xpos22_ypos36_place12_room12_floora place12_door_room12_staircase)
	(locationinplace location_xpos29_ypos6_place9_room7_floora place9_door_room7_dining_room)
	(locationinplace location_xpos32_ypos4_place7_room3_floorb place7_door_room3_bedroom)
	(locationinplace location_xpos39_ypos66_place8_room10_floora place8_door_room10_living-room)
	(locationinplace location_xpos6_ypos31_place11_room6_floorb place11_door_room6_corridor)
	(placeinroom place0_door_room9_kitchen room9_kitchen)
	(placeinroom place10_door_room5_corridor room5_corridor)
	(placeinroom place11_door_room6_corridor room6_corridor)
	(placeinroom place12_door_room12_staircase room12_staircase)
	(placeinroom place18_receptacle5_sink room2_bathroom)
	(placeinroom place19_receptacle6_sink room9_kitchen)
	(placeinroom place1_door_room2_bathroom room2_bathroom)
	(placeinroom place2_door_room1_bathroom room1_bathroom)
	(placeinroom place3_door_room8_home_office room8_home_office)
	(placeinroom place4_door_room4_bedroom room4_bedroom)
	(placeinroom place5_door_room13_utility_room room13_utility_room)
	(placeinroom place6_door_room11_staircase room11_staircase)
	(placeinroom place7_door_room3_bedroom room3_bedroom)
	(placeinroom place8_door_room10_living-room room10_living-room)
	(placeinroom place9_door_room7_dining_room room7_dining_room)
	(placelocation location_xneg17_ypos40_place1_room2_floorb place1_door_room2_bathroom)
	(placelocation location_xneg17_ypos54_place18_room2_floorb place18_receptacle5_sink)
	(placelocation location_xneg26_ypos41_place3_room8_floora place3_door_room8_home_office)
	(placelocation location_xneg28_yneg8_place19_room9_floora place19_receptacle6_sink)
	(placelocation location_xneg28_ypos6_place0_room9_floora place0_door_room9_kitchen)
	(placelocation location_xneg4_ypos5_place5_room13_floora place5_door_room13_utility_room)
	(placelocation location_xneg7_ypos6_place4_room4_floorb place4_door_room4_bedroom)
	(placelocation location_xpos11_ypos44_place6_room11_floora place6_door_room11_staircase)
	(placelocation location_xpos18_ypos30_place10_room5_floora place10_door_room5_corridor)
	(placelocation location_xpos1_ypos31_place2_room1_floora place2_door_room1_bathroom)
	(placelocation location_xpos22_ypos36_place12_room12_floora place12_door_room12_staircase)
	(placelocation location_xpos29_ypos6_place9_room7_floora place9_door_room7_dining_room)
	(placelocation location_xpos32_ypos4_place7_room3_floorb place7_door_room3_bedroom)
	(placelocation location_xpos39_ypos66_place8_room10_floora place8_door_room10_living-room)
	(placelocation location_xpos6_ypos31_place11_room6_floorb place11_door_room6_corridor)
	(receptacleatlocation receptacle5_sink location_xneg17_ypos54_place18_room2_floorb)
	(receptacleatlocation receptacle6_sink location_xneg28_yneg8_place19_room9_floora)
	(roomplace place0_door_room9_kitchen room9_kitchen)
	(roomplace place10_door_room5_corridor room5_corridor)
	(roomplace place11_door_room6_corridor room6_corridor)
	(roomplace place12_door_room12_staircase room12_staircase)
	(roomplace place1_door_room2_bathroom room2_bathroom)
	(roomplace place2_door_room1_bathroom room1_bathroom)
	(roomplace place3_door_room8_home_office room8_home_office)
	(roomplace place4_door_room4_bedroom room4_bedroom)
	(roomplace place5_door_room13_utility_room room13_utility_room)
	(roomplace place6_door_room11_staircase room11_staircase)
	(roomplace place7_door_room3_bedroom room3_bedroom)
	(roomplace place8_door_room10_living-room room10_living-room)
	(roomplace place9_door_room7_dining_room room7_dining_room)
	(roomsconnected room10_living-room room11_staircase)
	(roomsconnected room11_staircase room10_living-room)
	(roomsconnected room11_staircase room12_staircase)
	(roomsconnected room11_staircase room6_corridor)
	(roomsconnected room12_staircase room11_staircase)
	(roomsconnected room12_staircase room5_corridor)
	(roomsconnected room13_utility_room room1_bathroom)
	(roomsconnected room13_utility_room room9_kitchen)
	(roomsconnected room1_bathroom room13_utility_room)
	(roomsconnected room1_bathroom room5_corridor)
	(roomsconnected room1_bathroom room8_home_office)
	(roomsconnected room2_bathroom room6_corridor)
	(roomsconnected room3_bedroom room6_corridor)
	(roomsconnected room4_bedroom room6_corridor)
	(roomsconnected room5_corridor room12_staircase)
	(roomsconnected room5_corridor room1_bathroom)
	(roomsconnected room5_corridor room7_dining_room)
	(roomsconnected room6_corridor room11_staircase)
	(roomsconnected room6_corridor room2_bathroom)
	(roomsconnected room6_corridor room3_bedroom)
	(roomsconnected room6_corridor room4_bedroom)
	(roomsconnected room7_dining_room room5_corridor)
	(roomsconnected room8_home_office room1_bathroom)
	(roomsconnected room9_kitchen room13_utility_room)
  )
  (:goal (and
	(inreceptacle item19_bottle_smallitem receptacle6_sink)))
)
