
(define (problem ancortaskographyv2medium1problem109) (:domain taskographyv2medium1scrub)
  (:objects
        item4_baseball_bat_largeitem - item
	location_xneg14_yneg12_place4_room2_floorc - location
	location_xneg15_ypos23_place1_room11_floora - location
	location_xneg16_yneg3_place10_room7_floorb - location
	location_xneg23_ypos7_place27_room4_floorc - location
	location_xneg24_ypos3_place5_room13_floora - location
	location_xneg29_ypos23_place2_room12_floorb - location
	location_xneg33_ypos28_place15_room12_floorb - location
	location_xneg42_yneg2_place0_room4_floorc - location
	location_xneg43_yneg2_place8_room10_floorb - location
	location_xneg46_ypos18_place6_room5_floora - location
	location_xneg8_ypos18_place12_room6_floorc - location
	location_xpos16_ypos22_place11_room8_floorc - location
	location_xpos16_ypos22_place7_room1_floorb - location
	location_xpos8_yneg2_place3_room9_floorb - location
	location_xpos9_yneg7_place9_room3_floorc - location
	place0_door_room4_bedroom - place
	place10_door_room7_dining_room - place
	place11_door_room8_home_office - place
	place12_door_room6_corridor - place
	place15_item4_baseball_bat - place
	place1_door_room11_staircase - place
	place27_receptacle14_refrigerator - place
	place2_door_room12_staircase - place
	place3_door_room9_kitchen - place
	place4_door_room2_bathroom - place
	place5_door_room13_storage - place
	place6_door_room5_corridor - place
	place7_door_room1_bathroom - place
	place8_door_room10_living_room - place
	place9_door_room3_bedroom - place
	receptacle14_refrigerator - receptacle
	robot - agent
	room10_living_room - room
	room11_staircase - room
	room12_staircase - room
	room13_storage - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bedroom - room
	room4_bedroom - room
	room5_corridor - room
	room6_corridor - room
	room7_dining_room - room
	room8_home_office - room
	room9_kitchen - room
  )
  (:init 
	(atlocation robot location_xpos16_ypos22_place11_room8_floorc)
	(inplace robot place11_door_room8_home_office)
	(inroom robot room8_home_office)
	(itematlocation item4_baseball_bat_largeitem location_xneg33_ypos28_place15_room12_floorb)
	(locationinplace location_xneg14_yneg12_place4_room2_floorc place4_door_room2_bathroom)
	(locationinplace location_xneg15_ypos23_place1_room11_floora place1_door_room11_staircase)
	(locationinplace location_xneg16_yneg3_place10_room7_floorb place10_door_room7_dining_room)
	(locationinplace location_xneg23_ypos7_place27_room4_floorc place27_receptacle14_refrigerator)
	(locationinplace location_xneg24_ypos3_place5_room13_floora place5_door_room13_storage)
	(locationinplace location_xneg29_ypos23_place2_room12_floorb place2_door_room12_staircase)
	(locationinplace location_xneg33_ypos28_place15_room12_floorb place15_item4_baseball_bat)
	(locationinplace location_xneg42_yneg2_place0_room4_floorc place0_door_room4_bedroom)
	(locationinplace location_xneg43_yneg2_place8_room10_floorb place8_door_room10_living_room)
	(locationinplace location_xneg46_ypos18_place6_room5_floora place6_door_room5_corridor)
	(locationinplace location_xneg8_ypos18_place12_room6_floorc place12_door_room6_corridor)
	(locationinplace location_xpos16_ypos22_place11_room8_floorc place11_door_room8_home_office)
	(locationinplace location_xpos16_ypos22_place7_room1_floorb place7_door_room1_bathroom)
	(locationinplace location_xpos8_yneg2_place3_room9_floorb place3_door_room9_kitchen)
	(locationinplace location_xpos9_yneg7_place9_room3_floorc place9_door_room3_bedroom)
	(placeinroom place0_door_room4_bedroom room4_bedroom)
	(placeinroom place10_door_room7_dining_room room7_dining_room)
	(placeinroom place11_door_room8_home_office room8_home_office)
	(placeinroom place12_door_room6_corridor room6_corridor)
	(placeinroom place15_item4_baseball_bat room12_staircase)
	(placeinroom place1_door_room11_staircase room11_staircase)
	(placeinroom place27_receptacle14_refrigerator room4_bedroom)
	(placeinroom place2_door_room12_staircase room12_staircase)
	(placeinroom place3_door_room9_kitchen room9_kitchen)
	(placeinroom place4_door_room2_bathroom room2_bathroom)
	(placeinroom place5_door_room13_storage room13_storage)
	(placeinroom place6_door_room5_corridor room5_corridor)
	(placeinroom place7_door_room1_bathroom room1_bathroom)
	(placeinroom place8_door_room10_living_room room10_living_room)
	(placeinroom place9_door_room3_bedroom room3_bedroom)
	(placelocation location_xneg14_yneg12_place4_room2_floorc place4_door_room2_bathroom)
	(placelocation location_xneg15_ypos23_place1_room11_floora place1_door_room11_staircase)
	(placelocation location_xneg16_yneg3_place10_room7_floorb place10_door_room7_dining_room)
	(placelocation location_xneg23_ypos7_place27_room4_floorc place27_receptacle14_refrigerator)
	(placelocation location_xneg24_ypos3_place5_room13_floora place5_door_room13_storage)
	(placelocation location_xneg29_ypos23_place2_room12_floorb place2_door_room12_staircase)
	(placelocation location_xneg33_ypos28_place15_room12_floorb place15_item4_baseball_bat)
	(placelocation location_xneg42_yneg2_place0_room4_floorc place0_door_room4_bedroom)
	(placelocation location_xneg43_yneg2_place8_room10_floorb place8_door_room10_living_room)
	(placelocation location_xneg46_ypos18_place6_room5_floora place6_door_room5_corridor)
	(placelocation location_xneg8_ypos18_place12_room6_floorc place12_door_room6_corridor)
	(placelocation location_xpos16_ypos22_place11_room8_floorc place11_door_room8_home_office)
	(placelocation location_xpos16_ypos22_place7_room1_floorb place7_door_room1_bathroom)
	(placelocation location_xpos8_yneg2_place3_room9_floorb place3_door_room9_kitchen)
	(placelocation location_xpos9_yneg7_place9_room3_floorc place9_door_room3_bedroom)
	(receptacleatlocation receptacle14_refrigerator location_xneg23_ypos7_place27_room4_floorc)
	(receptacleopeningtype receptacle14_refrigerator)
	(roomplace place0_door_room4_bedroom room4_bedroom)
	(roomplace place10_door_room7_dining_room room7_dining_room)
	(roomplace place11_door_room8_home_office room8_home_office)
	(roomplace place12_door_room6_corridor room6_corridor)
	(roomplace place1_door_room11_staircase room11_staircase)
	(roomplace place2_door_room12_staircase room12_staircase)
	(roomplace place3_door_room9_kitchen room9_kitchen)
	(roomplace place4_door_room2_bathroom room2_bathroom)
	(roomplace place5_door_room13_storage room13_storage)
	(roomplace place6_door_room5_corridor room5_corridor)
	(roomplace place7_door_room1_bathroom room1_bathroom)
	(roomplace place8_door_room10_living_room room10_living_room)
	(roomplace place9_door_room3_bedroom room3_bedroom)
	(roomsconnected room10_living_room room12_staircase)
	(roomsconnected room10_living_room room7_dining_room)
	(roomsconnected room11_staircase room13_storage)
	(roomsconnected room11_staircase room7_dining_room)
	(roomsconnected room12_staircase room10_living_room)
	(roomsconnected room12_staircase room6_corridor)
	(roomsconnected room13_storage room11_staircase)
	(roomsconnected room13_storage room5_corridor)
	(roomsconnected room1_bathroom room9_kitchen)
	(roomsconnected room2_bathroom room3_bedroom)
	(roomsconnected room2_bathroom room4_bedroom)
	(roomsconnected room3_bedroom room2_bathroom)
	(roomsconnected room3_bedroom room6_corridor)
	(roomsconnected room4_bedroom room2_bathroom)
	(roomsconnected room5_corridor room13_storage)
	(roomsconnected room6_corridor room12_staircase)
	(roomsconnected room6_corridor room3_bedroom)
	(roomsconnected room6_corridor room8_home_office)
	(roomsconnected room7_dining_room room10_living_room)
	(roomsconnected room7_dining_room room11_staircase)
	(roomsconnected room7_dining_room room9_kitchen)
	(roomsconnected room8_home_office room6_corridor)
	(roomsconnected room9_kitchen room1_bathroom)
	(roomsconnected room9_kitchen room7_dining_room)
  )
  (:goal (and
	(inreceptacle item4_baseball_bat_largeitem receptacle14_refrigerator)))
)
