
(define (problem duartetaskographyv2medium1problem43) (:domain taskographyv2medium1scrub)
  (:objects
        item68_book_smallitem - item
	location_xneg10_ypos43_place9_room4_floorc - location
	location_xneg11_yneg41_place6_room16_floorb - location
	location_xneg14_ypos26_place2_room15_floora - location
	location_xneg16_ypos1_place7_room11_floorb - location
	location_xneg27_ypos5_place15_room6_floorc - location
	location_xneg29_yneg44_place71_room2_floorc - location
	location_xneg38_yneg33_place14_room13_floorc - location
	location_xneg38_yneg53_place5_room2_floorc - location
	location_xneg39_yneg19_place18_room9_floorc - location
	location_xneg46_ypos23_place19_room10_floorc - location
	location_xneg4_yneg40_place13_room14_floorc - location
	location_xneg50_yneg17_place47_room12_floorb - location
	location_xneg51_ypos57_place17_room7_floora - location
	location_xneg51_ypos76_place20_room21_floora - location
	location_xneg52_ypos76_place21_room22_floorb - location
	location_xneg57_ypos23_place11_room8_floorb - location
	location_xneg62_yneg33_place8_room12_floorb - location
	location_xneg68_yneg40_place10_room18_floorc - location
	location_xneg6_ypos39_place0_room17_floorb - location
	location_xneg75_ypos55_place1_room19_floorb - location
	location_xneg81_ypos31_place16_room5_floorb - location
	location_xneg81_ypos5_place12_room1_floorb - location
	location_xpos13_yneg29_place4_room20_floorb - location
	location_xpos2_ypos0_place3_room3_floorc - location
	place0_door_room17_living_room - place
	place10_door_room18_living_room - place
	place11_door_room8_corridor - place
	place12_door_room1_bathroom - place
	place13_door_room14_empty_room - place
	place14_door_room13_empty_room - place
	place15_door_room6_closet - place
	place16_door_room5_closet - place
	place17_door_room7_corridor - place
	place18_door_room9_corridor - place
	place19_door_room10_corridor - place
	place1_door_room19_lobby - place
	place20_door_room21_staircase - place
	place21_door_room22_staircase - place
	place2_door_room15_garage - place
	place3_door_room3_bathroom - place
	place47_item68_book - place
	place4_door_room20_pantry - place
	place5_door_room2_bathroom - place
	place6_door_room16_kitchen - place
	place71_receptacle55_toilet - place
	place7_door_room11_dining_room - place
	place8_door_room12_dining_room - place
	place9_door_room4_bedroom - place
	receptacle55_toilet - receptacle
	robot - agent
	room10_corridor - room
	room11_dining_room - room
	room12_dining_room - room
	room13_empty_room - room
	room14_empty_room - room
	room15_garage - room
	room16_kitchen - room
	room17_living_room - room
	room18_living_room - room
	room19_lobby - room
	room1_bathroom - room
	room20_pantry - room
	room21_staircase - room
	room22_staircase - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_closet - room
	room6_closet - room
	room7_corridor - room
	room8_corridor - room
	room9_corridor - room
  )
  (:init 
	(atlocation robot location_xneg10_ypos43_place9_room4_floorc)
	(inplace robot place9_door_room4_bedroom)
	(inroom robot room4_bedroom)
	(itematlocation item68_book_smallitem location_xneg50_yneg17_place47_room12_floorb)
	(locationinplace location_xneg10_ypos43_place9_room4_floorc place9_door_room4_bedroom)
	(locationinplace location_xneg11_yneg41_place6_room16_floorb place6_door_room16_kitchen)
	(locationinplace location_xneg14_ypos26_place2_room15_floora place2_door_room15_garage)
	(locationinplace location_xneg16_ypos1_place7_room11_floorb place7_door_room11_dining_room)
	(locationinplace location_xneg27_ypos5_place15_room6_floorc place15_door_room6_closet)
	(locationinplace location_xneg29_yneg44_place71_room2_floorc place71_receptacle55_toilet)
	(locationinplace location_xneg38_yneg33_place14_room13_floorc place14_door_room13_empty_room)
	(locationinplace location_xneg38_yneg53_place5_room2_floorc place5_door_room2_bathroom)
	(locationinplace location_xneg39_yneg19_place18_room9_floorc place18_door_room9_corridor)
	(locationinplace location_xneg46_ypos23_place19_room10_floorc place19_door_room10_corridor)
	(locationinplace location_xneg4_yneg40_place13_room14_floorc place13_door_room14_empty_room)
	(locationinplace location_xneg50_yneg17_place47_room12_floorb place47_item68_book)
	(locationinplace location_xneg51_ypos57_place17_room7_floora place17_door_room7_corridor)
	(locationinplace location_xneg51_ypos76_place20_room21_floora place20_door_room21_staircase)
	(locationinplace location_xneg52_ypos76_place21_room22_floorb place21_door_room22_staircase)
	(locationinplace location_xneg57_ypos23_place11_room8_floorb place11_door_room8_corridor)
	(locationinplace location_xneg62_yneg33_place8_room12_floorb place8_door_room12_dining_room)
	(locationinplace location_xneg68_yneg40_place10_room18_floorc place10_door_room18_living_room)
	(locationinplace location_xneg6_ypos39_place0_room17_floorb place0_door_room17_living_room)
	(locationinplace location_xneg75_ypos55_place1_room19_floorb place1_door_room19_lobby)
	(locationinplace location_xneg81_ypos31_place16_room5_floorb place16_door_room5_closet)
	(locationinplace location_xneg81_ypos5_place12_room1_floorb place12_door_room1_bathroom)
	(locationinplace location_xpos13_yneg29_place4_room20_floorb place4_door_room20_pantry)
	(locationinplace location_xpos2_ypos0_place3_room3_floorc place3_door_room3_bathroom)
	(placeinroom place0_door_room17_living_room room17_living_room)
	(placeinroom place10_door_room18_living_room room18_living_room)
	(placeinroom place11_door_room8_corridor room8_corridor)
	(placeinroom place12_door_room1_bathroom room1_bathroom)
	(placeinroom place13_door_room14_empty_room room14_empty_room)
	(placeinroom place14_door_room13_empty_room room13_empty_room)
	(placeinroom place15_door_room6_closet room6_closet)
	(placeinroom place16_door_room5_closet room5_closet)
	(placeinroom place17_door_room7_corridor room7_corridor)
	(placeinroom place18_door_room9_corridor room9_corridor)
	(placeinroom place19_door_room10_corridor room10_corridor)
	(placeinroom place1_door_room19_lobby room19_lobby)
	(placeinroom place20_door_room21_staircase room21_staircase)
	(placeinroom place21_door_room22_staircase room22_staircase)
	(placeinroom place2_door_room15_garage room15_garage)
	(placeinroom place3_door_room3_bathroom room3_bathroom)
	(placeinroom place47_item68_book room12_dining_room)
	(placeinroom place4_door_room20_pantry room20_pantry)
	(placeinroom place5_door_room2_bathroom room2_bathroom)
	(placeinroom place6_door_room16_kitchen room16_kitchen)
	(placeinroom place71_receptacle55_toilet room2_bathroom)
	(placeinroom place7_door_room11_dining_room room11_dining_room)
	(placeinroom place8_door_room12_dining_room room12_dining_room)
	(placeinroom place9_door_room4_bedroom room4_bedroom)
	(placelocation location_xneg10_ypos43_place9_room4_floorc place9_door_room4_bedroom)
	(placelocation location_xneg11_yneg41_place6_room16_floorb place6_door_room16_kitchen)
	(placelocation location_xneg14_ypos26_place2_room15_floora place2_door_room15_garage)
	(placelocation location_xneg16_ypos1_place7_room11_floorb place7_door_room11_dining_room)
	(placelocation location_xneg27_ypos5_place15_room6_floorc place15_door_room6_closet)
	(placelocation location_xneg29_yneg44_place71_room2_floorc place71_receptacle55_toilet)
	(placelocation location_xneg38_yneg33_place14_room13_floorc place14_door_room13_empty_room)
	(placelocation location_xneg38_yneg53_place5_room2_floorc place5_door_room2_bathroom)
	(placelocation location_xneg39_yneg19_place18_room9_floorc place18_door_room9_corridor)
	(placelocation location_xneg46_ypos23_place19_room10_floorc place19_door_room10_corridor)
	(placelocation location_xneg4_yneg40_place13_room14_floorc place13_door_room14_empty_room)
	(placelocation location_xneg50_yneg17_place47_room12_floorb place47_item68_book)
	(placelocation location_xneg51_ypos57_place17_room7_floora place17_door_room7_corridor)
	(placelocation location_xneg51_ypos76_place20_room21_floora place20_door_room21_staircase)
	(placelocation location_xneg52_ypos76_place21_room22_floorb place21_door_room22_staircase)
	(placelocation location_xneg57_ypos23_place11_room8_floorb place11_door_room8_corridor)
	(placelocation location_xneg62_yneg33_place8_room12_floorb place8_door_room12_dining_room)
	(placelocation location_xneg68_yneg40_place10_room18_floorc place10_door_room18_living_room)
	(placelocation location_xneg6_ypos39_place0_room17_floorb place0_door_room17_living_room)
	(placelocation location_xneg75_ypos55_place1_room19_floorb place1_door_room19_lobby)
	(placelocation location_xneg81_ypos31_place16_room5_floorb place16_door_room5_closet)
	(placelocation location_xneg81_ypos5_place12_room1_floorb place12_door_room1_bathroom)
	(placelocation location_xpos13_yneg29_place4_room20_floorb place4_door_room20_pantry)
	(placelocation location_xpos2_ypos0_place3_room3_floorc place3_door_room3_bathroom)
	(receptacleatlocation receptacle55_toilet location_xneg29_yneg44_place71_room2_floorc)
	(roomplace place0_door_room17_living_room room17_living_room)
	(roomplace place10_door_room18_living_room room18_living_room)
	(roomplace place11_door_room8_corridor room8_corridor)
	(roomplace place12_door_room1_bathroom room1_bathroom)
	(roomplace place13_door_room14_empty_room room14_empty_room)
	(roomplace place14_door_room13_empty_room room13_empty_room)
	(roomplace place15_door_room6_closet room6_closet)
	(roomplace place16_door_room5_closet room5_closet)
	(roomplace place17_door_room7_corridor room7_corridor)
	(roomplace place18_door_room9_corridor room9_corridor)
	(roomplace place19_door_room10_corridor room10_corridor)
	(roomplace place1_door_room19_lobby room19_lobby)
	(roomplace place20_door_room21_staircase room21_staircase)
	(roomplace place21_door_room22_staircase room22_staircase)
	(roomplace place2_door_room15_garage room15_garage)
	(roomplace place3_door_room3_bathroom room3_bathroom)
	(roomplace place4_door_room20_pantry room20_pantry)
	(roomplace place5_door_room2_bathroom room2_bathroom)
	(roomplace place6_door_room16_kitchen room16_kitchen)
	(roomplace place7_door_room11_dining_room room11_dining_room)
	(roomplace place8_door_room12_dining_room room12_dining_room)
	(roomplace place9_door_room4_bedroom room4_bedroom)
	(roomsconnected room10_corridor room4_bedroom)
	(roomsconnected room10_corridor room6_closet)
	(roomsconnected room10_corridor room8_corridor)
	(roomsconnected room11_dining_room room17_living_room)
	(roomsconnected room11_dining_room room20_pantry)
	(roomsconnected room11_dining_room room8_corridor)
	(roomsconnected room12_dining_room room1_bathroom)
	(roomsconnected room13_empty_room room14_empty_room)
	(roomsconnected room13_empty_room room18_living_room)
	(roomsconnected room13_empty_room room2_bathroom)
	(roomsconnected room13_empty_room room9_corridor)
	(roomsconnected room14_empty_room room13_empty_room)
	(roomsconnected room15_garage room7_corridor)
	(roomsconnected room16_kitchen room20_pantry)
	(roomsconnected room17_living_room room11_dining_room)
	(roomsconnected room18_living_room room13_empty_room)
	(roomsconnected room19_lobby room22_staircase)
	(roomsconnected room19_lobby room5_closet)
	(roomsconnected room1_bathroom room12_dining_room)
	(roomsconnected room1_bathroom room5_closet)
	(roomsconnected room20_pantry room11_dining_room)
	(roomsconnected room20_pantry room16_kitchen)
	(roomsconnected room21_staircase room22_staircase)
	(roomsconnected room21_staircase room7_corridor)
	(roomsconnected room22_staircase room19_lobby)
	(roomsconnected room22_staircase room21_staircase)
	(roomsconnected room2_bathroom room13_empty_room)
	(roomsconnected room3_bathroom room6_closet)
	(roomsconnected room4_bedroom room10_corridor)
	(roomsconnected room5_closet room19_lobby)
	(roomsconnected room5_closet room1_bathroom)
	(roomsconnected room5_closet room8_corridor)
	(roomsconnected room6_closet room10_corridor)
	(roomsconnected room6_closet room3_bathroom)
	(roomsconnected room6_closet room9_corridor)
	(roomsconnected room7_corridor room15_garage)
	(roomsconnected room7_corridor room21_staircase)
	(roomsconnected room8_corridor room10_corridor)
	(roomsconnected room8_corridor room11_dining_room)
	(roomsconnected room8_corridor room5_closet)
	(roomsconnected room9_corridor room13_empty_room)
	(roomsconnected room9_corridor room6_closet)
  )
  (:goal (and
	(inreceptacle item68_book_smallitem receptacle55_toilet)))
)
