
(define (problem irvinetaskographyv2medium1problem210) (:domain taskographyv2medium1scrub)
  (:objects
        item66_vase_mediumitem - item
	location_xneg10_yneg30_place6_room3_floora - location
	location_xneg111_ypos0_place37_room16_floora - location
	location_xneg11_ypos11_place45_room13_floora - location
	location_xneg127_ypos2_place37_room16_floora - location
	location_xneg128_ypos19_place0_room16_floora - location
	location_xneg12_yneg30_place10_room4_floorb - location
	location_xneg134_yneg20_place7_room14_floora - location
	location_xneg160_yneg20_place8_room12_floora - location
	location_xneg2_ypos12_place1_room5_floorb - location
	location_xneg35_ypos17_place5_room6_floorb - location
	location_xneg44_yneg4_place15_room11_floora - location
	location_xneg46_yneg25_place12_room8_floorb - location
	location_xneg49_yneg30_place3_room1_floora - location
	location_xneg50_ypos12_place9_room15_floora - location
	location_xneg57_yneg43_place2_room2_floorb - location
	location_xneg66_yneg19_place14_room10_floora - location
	location_xneg66_ypos18_place11_room7_floorb - location
	location_xneg70_yneg38_place16_room17_floora - location
	location_xneg7_ypos12_place4_room13_floora - location
	location_xneg85_yneg33_place18_room19_floora - location
	location_xneg85_yneg8_place17_room18_floora - location
	location_xneg94_yneg4_place13_room9_floora - location
	place0_door_room16_living_room - place
	place10_door_room4_bedroom - place
	place11_door_room7_childs_room - place
	place12_door_room8_closet - place
	place13_door_room9_corridor - place
	place14_door_room10_corridor - place
	place15_door_room11_corridor - place
	place16_door_room17_lobby - place
	place17_door_room18_staircase - place
	place18_door_room19_staircase - place
	place1_door_room5_bedroom - place
	place2_door_room2_bathroom - place
	place37_receptacle20_couch - place
	place3_door_room1_bathroom - place
	place45_receptacle42_dining_table - place
	place4_door_room13_kitchen - place
	place5_door_room6_childs_room - place
	place6_door_room3_bedroom - place
	place7_door_room14_kitchen - place
	place8_door_room12_dining_room - place
	place9_door_room15_living_room - place
	receptacle20_couch - receptacle
	receptacle42_dining_table - receptacle
	robot - agent
	room10_corridor - room
	room11_corridor - room
	room12_dining_room - room
	room13_kitchen - room
	room14_kitchen - room
	room15_living_room - room
	room16_living_room - room
	room17_lobby - room
	room18_staircase - room
	room19_staircase - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bedroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_childs_room - room
	room7_childs_room - room
	room8_closet - room
	room9_corridor - room
  )
  (:init 
	(atlocation robot location_xneg160_yneg20_place8_room12_floora)
	(inanyreceptacle item66_vase_mediumitem)
	(inplace robot place8_door_room12_dining_room)
	(inreceptacle item66_vase_mediumitem receptacle20_couch)
	(inroom robot room12_dining_room)
	(itematlocation item66_vase_mediumitem location_xneg111_ypos0_place37_room16_floora)
	(locationinplace location_xneg10_yneg30_place6_room3_floora place6_door_room3_bedroom)
	(locationinplace location_xneg111_ypos0_place37_room16_floora place37_receptacle20_couch)
	(locationinplace location_xneg11_ypos11_place45_room13_floora place45_receptacle42_dining_table)
	(locationinplace location_xneg127_ypos2_place37_room16_floora place37_receptacle20_couch)
	(locationinplace location_xneg128_ypos19_place0_room16_floora place0_door_room16_living_room)
	(locationinplace location_xneg12_yneg30_place10_room4_floorb place10_door_room4_bedroom)
	(locationinplace location_xneg134_yneg20_place7_room14_floora place7_door_room14_kitchen)
	(locationinplace location_xneg160_yneg20_place8_room12_floora place8_door_room12_dining_room)
	(locationinplace location_xneg2_ypos12_place1_room5_floorb place1_door_room5_bedroom)
	(locationinplace location_xneg35_ypos17_place5_room6_floorb place5_door_room6_childs_room)
	(locationinplace location_xneg44_yneg4_place15_room11_floora place15_door_room11_corridor)
	(locationinplace location_xneg46_yneg25_place12_room8_floorb place12_door_room8_closet)
	(locationinplace location_xneg49_yneg30_place3_room1_floora place3_door_room1_bathroom)
	(locationinplace location_xneg50_ypos12_place9_room15_floora place9_door_room15_living_room)
	(locationinplace location_xneg57_yneg43_place2_room2_floorb place2_door_room2_bathroom)
	(locationinplace location_xneg66_yneg19_place14_room10_floora place14_door_room10_corridor)
	(locationinplace location_xneg66_ypos18_place11_room7_floorb place11_door_room7_childs_room)
	(locationinplace location_xneg70_yneg38_place16_room17_floora place16_door_room17_lobby)
	(locationinplace location_xneg7_ypos12_place4_room13_floora place4_door_room13_kitchen)
	(locationinplace location_xneg85_yneg33_place18_room19_floora place18_door_room19_staircase)
	(locationinplace location_xneg85_yneg8_place17_room18_floora place17_door_room18_staircase)
	(locationinplace location_xneg94_yneg4_place13_room9_floora place13_door_room9_corridor)
	(placeinroom place0_door_room16_living_room room16_living_room)
	(placeinroom place10_door_room4_bedroom room4_bedroom)
	(placeinroom place11_door_room7_childs_room room7_childs_room)
	(placeinroom place12_door_room8_closet room8_closet)
	(placeinroom place13_door_room9_corridor room9_corridor)
	(placeinroom place14_door_room10_corridor room10_corridor)
	(placeinroom place15_door_room11_corridor room11_corridor)
	(placeinroom place16_door_room17_lobby room17_lobby)
	(placeinroom place17_door_room18_staircase room18_staircase)
	(placeinroom place18_door_room19_staircase room19_staircase)
	(placeinroom place1_door_room5_bedroom room5_bedroom)
	(placeinroom place2_door_room2_bathroom room2_bathroom)
	(placeinroom place37_receptacle20_couch room16_living_room)
	(placeinroom place3_door_room1_bathroom room1_bathroom)
	(placeinroom place45_receptacle42_dining_table room13_kitchen)
	(placeinroom place4_door_room13_kitchen room13_kitchen)
	(placeinroom place5_door_room6_childs_room room6_childs_room)
	(placeinroom place6_door_room3_bedroom room3_bedroom)
	(placeinroom place7_door_room14_kitchen room14_kitchen)
	(placeinroom place8_door_room12_dining_room room12_dining_room)
	(placeinroom place9_door_room15_living_room room15_living_room)
	(placelocation location_xneg10_yneg30_place6_room3_floora place6_door_room3_bedroom)
	(placelocation location_xneg11_ypos11_place45_room13_floora place45_receptacle42_dining_table)
	(placelocation location_xneg127_ypos2_place37_room16_floora place37_receptacle20_couch)
	(placelocation location_xneg128_ypos19_place0_room16_floora place0_door_room16_living_room)
	(placelocation location_xneg12_yneg30_place10_room4_floorb place10_door_room4_bedroom)
	(placelocation location_xneg134_yneg20_place7_room14_floora place7_door_room14_kitchen)
	(placelocation location_xneg160_yneg20_place8_room12_floora place8_door_room12_dining_room)
	(placelocation location_xneg2_ypos12_place1_room5_floorb place1_door_room5_bedroom)
	(placelocation location_xneg35_ypos17_place5_room6_floorb place5_door_room6_childs_room)
	(placelocation location_xneg44_yneg4_place15_room11_floora place15_door_room11_corridor)
	(placelocation location_xneg46_yneg25_place12_room8_floorb place12_door_room8_closet)
	(placelocation location_xneg49_yneg30_place3_room1_floora place3_door_room1_bathroom)
	(placelocation location_xneg50_ypos12_place9_room15_floora place9_door_room15_living_room)
	(placelocation location_xneg57_yneg43_place2_room2_floorb place2_door_room2_bathroom)
	(placelocation location_xneg66_yneg19_place14_room10_floora place14_door_room10_corridor)
	(placelocation location_xneg66_ypos18_place11_room7_floorb place11_door_room7_childs_room)
	(placelocation location_xneg70_yneg38_place16_room17_floora place16_door_room17_lobby)
	(placelocation location_xneg7_ypos12_place4_room13_floora place4_door_room13_kitchen)
	(placelocation location_xneg85_yneg33_place18_room19_floora place18_door_room19_staircase)
	(placelocation location_xneg85_yneg8_place17_room18_floora place17_door_room18_staircase)
	(placelocation location_xneg94_yneg4_place13_room9_floora place13_door_room9_corridor)
	(receptacleatlocation receptacle20_couch location_xneg127_ypos2_place37_room16_floora)
	(receptacleatlocation receptacle42_dining_table location_xneg11_ypos11_place45_room13_floora)
	(roomplace place0_door_room16_living_room room16_living_room)
	(roomplace place10_door_room4_bedroom room4_bedroom)
	(roomplace place11_door_room7_childs_room room7_childs_room)
	(roomplace place12_door_room8_closet room8_closet)
	(roomplace place13_door_room9_corridor room9_corridor)
	(roomplace place14_door_room10_corridor room10_corridor)
	(roomplace place15_door_room11_corridor room11_corridor)
	(roomplace place16_door_room17_lobby room17_lobby)
	(roomplace place17_door_room18_staircase room18_staircase)
	(roomplace place18_door_room19_staircase room19_staircase)
	(roomplace place1_door_room5_bedroom room5_bedroom)
	(roomplace place2_door_room2_bathroom room2_bathroom)
	(roomplace place3_door_room1_bathroom room1_bathroom)
	(roomplace place4_door_room13_kitchen room13_kitchen)
	(roomplace place5_door_room6_childs_room room6_childs_room)
	(roomplace place6_door_room3_bedroom room3_bedroom)
	(roomplace place7_door_room14_kitchen room14_kitchen)
	(roomplace place8_door_room12_dining_room room12_dining_room)
	(roomplace place9_door_room15_living_room room15_living_room)
	(roomsconnected room10_corridor room15_living_room)
	(roomsconnected room10_corridor room17_lobby)
	(roomsconnected room10_corridor room1_bathroom)
	(roomsconnected room11_corridor room15_living_room)
	(roomsconnected room11_corridor room8_closet)
	(roomsconnected room12_dining_room room14_kitchen)
	(roomsconnected room13_kitchen room3_bedroom)
	(roomsconnected room14_kitchen room12_dining_room)
	(roomsconnected room14_kitchen room16_living_room)
	(roomsconnected room15_living_room room10_corridor)
	(roomsconnected room15_living_room room11_corridor)
	(roomsconnected room16_living_room room14_kitchen)
	(roomsconnected room16_living_room room9_corridor)
	(roomsconnected room17_lobby room10_corridor)
	(roomsconnected room17_lobby room19_staircase)
	(roomsconnected room18_staircase room19_staircase)
	(roomsconnected room18_staircase room9_corridor)
	(roomsconnected room19_staircase room17_lobby)
	(roomsconnected room19_staircase room18_staircase)
	(roomsconnected room1_bathroom room10_corridor)
	(roomsconnected room1_bathroom room3_bedroom)
	(roomsconnected room2_bathroom room8_closet)
	(roomsconnected room3_bedroom room13_kitchen)
	(roomsconnected room3_bedroom room1_bathroom)
	(roomsconnected room4_bedroom room5_bedroom)
	(roomsconnected room4_bedroom room8_closet)
	(roomsconnected room5_bedroom room4_bedroom)
	(roomsconnected room5_bedroom room6_childs_room)
	(roomsconnected room6_childs_room room5_bedroom)
	(roomsconnected room6_childs_room room7_childs_room)
	(roomsconnected room7_childs_room room6_childs_room)
	(roomsconnected room8_closet room11_corridor)
	(roomsconnected room8_closet room2_bathroom)
	(roomsconnected room8_closet room4_bedroom)
	(roomsconnected room9_corridor room16_living_room)
	(roomsconnected room9_corridor room18_staircase)
  )
  (:goal (and
	(inreceptacle item66_vase_mediumitem receptacle42_dining_table)))
)
