
(define (problem tokelandtaskographyv2medium1problem159) (:domain taskographyv2medium1scrub)
  (:objects
        item96_vase_mediumitem - item
	location_xneg26_ypos51_place11_room1_floora - location
	location_xneg26_ypos57_place3_room2_floorb - location
	location_xneg35_ypos35_place13_room6_floorb - location
	location_xneg40_ypos10_place6_room3_floorb - location
	location_xneg50_ypos52_place12_room16_floora - location
	location_xneg51_ypos56_place2_room10_floorb - location
	location_xneg58_yneg14_place14_room14_floorb - location
	location_xneg60_ypos15_place0_room12_floora - location
	location_xneg70_yneg4_place26_room13_floorb - location
	location_xneg72_ypos12_place26_room13_floorb - location
	location_xneg79_ypos20_place39_room12_floora - location
	location_xneg81_ypos13_place4_room13_floorb - location
	location_xneg84_ypos49_place7_room7_floorb - location
	location_xneg85_yneg14_place15_room15_floora - location
	location_xneg86_ypos54_place8_room9_floora - location
	location_xpos2_ypos49_place1_room8_floora - location
	location_xpos4_ypos12_place5_room4_floorb - location
	location_xpos4_ypos15_place10_room11_floora - location
	location_xpos4_ypos56_place9_room5_floorb - location
	place0_door_room12_liviing_room - place
	place10_door_room11_liviing_room - place
	place11_door_room1_bathroom - place
	place12_door_room16_utility_room - place
	place13_door_room6_corridor - place
	place14_door_room14_lobby - place
	place15_door_room15_staircase - place
	place1_door_room8_exercise_room - place
	place26_receptacle13_chair - place
	place2_door_room10_kitchen - place
	place39_receptacle26_chair - place
	place3_door_room2_bathroom - place
	place4_door_room13_living_room - place
	place5_door_room4_bedroom - place
	place6_door_room3_bedroom - place
	place7_door_room7_dining_room - place
	place8_door_room9_home_office - place
	place9_door_room5_bedroom - place
	receptacle13_chair - receptacle
	receptacle26_chair - receptacle
	robot - agent
	room10_kitchen - room
	room11_liviing_room - room
	room12_liviing_room - room
	room13_living_room - room
	room14_lobby - room
	room15_staircase - room
	room16_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bedroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_corridor - room
	room7_dining_room - room
	room8_exercise_room - room
	room9_home_office - room
  )
  (:init 
	(atlocation robot location_xneg84_ypos49_place7_room7_floorb)
	(inanyreceptacle item96_vase_mediumitem)
	(inplace robot place7_door_room7_dining_room)
	(inreceptacle item96_vase_mediumitem receptacle13_chair)
	(inroom robot room7_dining_room)
	(itematlocation item96_vase_mediumitem location_xneg70_yneg4_place26_room13_floorb)
	(locationinplace location_xneg26_ypos51_place11_room1_floora place11_door_room1_bathroom)
	(locationinplace location_xneg26_ypos57_place3_room2_floorb place3_door_room2_bathroom)
	(locationinplace location_xneg35_ypos35_place13_room6_floorb place13_door_room6_corridor)
	(locationinplace location_xneg40_ypos10_place6_room3_floorb place6_door_room3_bedroom)
	(locationinplace location_xneg50_ypos52_place12_room16_floora place12_door_room16_utility_room)
	(locationinplace location_xneg51_ypos56_place2_room10_floorb place2_door_room10_kitchen)
	(locationinplace location_xneg58_yneg14_place14_room14_floorb place14_door_room14_lobby)
	(locationinplace location_xneg60_ypos15_place0_room12_floora place0_door_room12_liviing_room)
	(locationinplace location_xneg70_yneg4_place26_room13_floorb place26_receptacle13_chair)
	(locationinplace location_xneg72_ypos12_place26_room13_floorb place26_receptacle13_chair)
	(locationinplace location_xneg79_ypos20_place39_room12_floora place39_receptacle26_chair)
	(locationinplace location_xneg81_ypos13_place4_room13_floorb place4_door_room13_living_room)
	(locationinplace location_xneg84_ypos49_place7_room7_floorb place7_door_room7_dining_room)
	(locationinplace location_xneg85_yneg14_place15_room15_floora place15_door_room15_staircase)
	(locationinplace location_xneg86_ypos54_place8_room9_floora place8_door_room9_home_office)
	(locationinplace location_xpos2_ypos49_place1_room8_floora place1_door_room8_exercise_room)
	(locationinplace location_xpos4_ypos12_place5_room4_floorb place5_door_room4_bedroom)
	(locationinplace location_xpos4_ypos15_place10_room11_floora place10_door_room11_liviing_room)
	(locationinplace location_xpos4_ypos56_place9_room5_floorb place9_door_room5_bedroom)
	(placeinroom place0_door_room12_liviing_room room12_liviing_room)
	(placeinroom place10_door_room11_liviing_room room11_liviing_room)
	(placeinroom place11_door_room1_bathroom room1_bathroom)
	(placeinroom place12_door_room16_utility_room room16_utility_room)
	(placeinroom place13_door_room6_corridor room6_corridor)
	(placeinroom place14_door_room14_lobby room14_lobby)
	(placeinroom place15_door_room15_staircase room15_staircase)
	(placeinroom place1_door_room8_exercise_room room8_exercise_room)
	(placeinroom place26_receptacle13_chair room13_living_room)
	(placeinroom place2_door_room10_kitchen room10_kitchen)
	(placeinroom place39_receptacle26_chair room12_liviing_room)
	(placeinroom place3_door_room2_bathroom room2_bathroom)
	(placeinroom place4_door_room13_living_room room13_living_room)
	(placeinroom place5_door_room4_bedroom room4_bedroom)
	(placeinroom place6_door_room3_bedroom room3_bedroom)
	(placeinroom place7_door_room7_dining_room room7_dining_room)
	(placeinroom place8_door_room9_home_office room9_home_office)
	(placeinroom place9_door_room5_bedroom room5_bedroom)
	(placelocation location_xneg26_ypos51_place11_room1_floora place11_door_room1_bathroom)
	(placelocation location_xneg26_ypos57_place3_room2_floorb place3_door_room2_bathroom)
	(placelocation location_xneg35_ypos35_place13_room6_floorb place13_door_room6_corridor)
	(placelocation location_xneg40_ypos10_place6_room3_floorb place6_door_room3_bedroom)
	(placelocation location_xneg50_ypos52_place12_room16_floora place12_door_room16_utility_room)
	(placelocation location_xneg51_ypos56_place2_room10_floorb place2_door_room10_kitchen)
	(placelocation location_xneg58_yneg14_place14_room14_floorb place14_door_room14_lobby)
	(placelocation location_xneg60_ypos15_place0_room12_floora place0_door_room12_liviing_room)
	(placelocation location_xneg72_ypos12_place26_room13_floorb place26_receptacle13_chair)
	(placelocation location_xneg79_ypos20_place39_room12_floora place39_receptacle26_chair)
	(placelocation location_xneg81_ypos13_place4_room13_floorb place4_door_room13_living_room)
	(placelocation location_xneg84_ypos49_place7_room7_floorb place7_door_room7_dining_room)
	(placelocation location_xneg85_yneg14_place15_room15_floora place15_door_room15_staircase)
	(placelocation location_xneg86_ypos54_place8_room9_floora place8_door_room9_home_office)
	(placelocation location_xpos2_ypos49_place1_room8_floora place1_door_room8_exercise_room)
	(placelocation location_xpos4_ypos12_place5_room4_floorb place5_door_room4_bedroom)
	(placelocation location_xpos4_ypos15_place10_room11_floora place10_door_room11_liviing_room)
	(placelocation location_xpos4_ypos56_place9_room5_floorb place9_door_room5_bedroom)
	(receptacleatlocation receptacle13_chair location_xneg72_ypos12_place26_room13_floorb)
	(receptacleatlocation receptacle26_chair location_xneg79_ypos20_place39_room12_floora)
	(roomplace place0_door_room12_liviing_room room12_liviing_room)
	(roomplace place10_door_room11_liviing_room room11_liviing_room)
	(roomplace place11_door_room1_bathroom room1_bathroom)
	(roomplace place12_door_room16_utility_room room16_utility_room)
	(roomplace place13_door_room6_corridor room6_corridor)
	(roomplace place14_door_room14_lobby room14_lobby)
	(roomplace place15_door_room15_staircase room15_staircase)
	(roomplace place1_door_room8_exercise_room room8_exercise_room)
	(roomplace place2_door_room10_kitchen room10_kitchen)
	(roomplace place3_door_room2_bathroom room2_bathroom)
	(roomplace place4_door_room13_living_room room13_living_room)
	(roomplace place5_door_room4_bedroom room4_bedroom)
	(roomplace place6_door_room3_bedroom room3_bedroom)
	(roomplace place7_door_room7_dining_room room7_dining_room)
	(roomplace place8_door_room9_home_office room9_home_office)
	(roomplace place9_door_room5_bedroom room5_bedroom)
	(roomsconnected room10_kitchen room2_bathroom)
	(roomsconnected room10_kitchen room7_dining_room)
	(roomsconnected room11_liviing_room room4_bedroom)
	(roomsconnected room11_liviing_room room8_exercise_room)
	(roomsconnected room12_liviing_room room15_staircase)
	(roomsconnected room12_liviing_room room16_utility_room)
	(roomsconnected room13_living_room room14_lobby)
	(roomsconnected room14_lobby room13_living_room)
	(roomsconnected room14_lobby room3_bedroom)
	(roomsconnected room15_staircase room12_liviing_room)
	(roomsconnected room16_utility_room room12_liviing_room)
	(roomsconnected room16_utility_room room1_bathroom)
	(roomsconnected room16_utility_room room9_home_office)
	(roomsconnected room1_bathroom room16_utility_room)
	(roomsconnected room1_bathroom room8_exercise_room)
	(roomsconnected room2_bathroom room10_kitchen)
	(roomsconnected room2_bathroom room5_bedroom)
	(roomsconnected room2_bathroom room6_corridor)
	(roomsconnected room3_bedroom room14_lobby)
	(roomsconnected room3_bedroom room4_bedroom)
	(roomsconnected room3_bedroom room6_corridor)
	(roomsconnected room4_bedroom room11_liviing_room)
	(roomsconnected room4_bedroom room3_bedroom)
	(roomsconnected room5_bedroom room2_bathroom)
	(roomsconnected room6_corridor room2_bathroom)
	(roomsconnected room6_corridor room3_bedroom)
	(roomsconnected room7_dining_room room10_kitchen)
	(roomsconnected room8_exercise_room room11_liviing_room)
	(roomsconnected room8_exercise_room room1_bathroom)
	(roomsconnected room9_home_office room16_utility_room)
  )
  (:goal (and
	(inreceptacle item96_vase_mediumitem receptacle26_chair)))
)
