
(define (problem pittsburgtaskographyv2medium1problem150) (:domain taskographyv2medium1scrub)
  (:objects
        item17_vase_mediumitem - item
	location_xpos10_yneg9_place0_room11_floorb - location
	location_xpos25_ypos20_place10_room7_floorb - location
	location_xpos2_ypos17_place3_room2_floorb - location
	location_xpos34_yneg13_place2_room3_floorc - location
	location_xpos34_yneg9_place7_room9_floorb - location
	location_xpos34_ypos14_place11_room8_floorc - location
	location_xpos40_yneg14_place35_room9_floorb - location
	location_xpos45_yneg5_place1_room1_floora - location
	location_xpos53_ypos19_place12_room13_floora - location
	location_xpos55_ypos21_place13_room14_floorb - location
	location_xpos58_ypos15_place9_room6_floora - location
	location_xpos62_yneg6_place4_room12_floorb - location
	location_xpos63_yneg6_place6_room5_floorc - location
	location_xpos66_yneg12_place5_room10_floora - location
	location_xpos76_yneg27_place19_room12_floorb - location
	location_xpos7_yneg6_place8_room4_floorc - location
	place0_door_room11_kitchen - place
	place10_door_room7_corridor - place
	place11_door_room8_corridor - place
	place12_door_room13_staircase - place
	place13_door_room14_staircase - place
	place19_item17_vase - place
	place1_door_room1_bathroom - place
	place2_door_room3_bathroom - place
	place35_receptacle29_chair - place
	place3_door_room2_bathroom - place
	place4_door_room12_living_room - place
	place5_door_room10_home_office - place
	place6_door_room5_bedroom - place
	place7_door_room9_dining_room - place
	place8_door_room4_bedroom - place
	place9_door_room6_corridor - place
	receptacle29_chair - receptacle
	robot - agent
	room10_home_office - room
	room11_kitchen - room
	room12_living_room - room
	room13_staircase - room
	room14_staircase - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_corridor - room
	room7_corridor - room
	room8_corridor - room
	room9_dining_room - room
  )
  (:init 
	(atlocation robot location_xpos34_ypos14_place11_room8_floorc)
	(inplace robot place11_door_room8_corridor)
	(inroom robot room8_corridor)
	(itematlocation item17_vase_mediumitem location_xpos76_yneg27_place19_room12_floorb)
	(locationinplace location_xpos10_yneg9_place0_room11_floorb place0_door_room11_kitchen)
	(locationinplace location_xpos25_ypos20_place10_room7_floorb place10_door_room7_corridor)
	(locationinplace location_xpos2_ypos17_place3_room2_floorb place3_door_room2_bathroom)
	(locationinplace location_xpos34_yneg13_place2_room3_floorc place2_door_room3_bathroom)
	(locationinplace location_xpos34_yneg9_place7_room9_floorb place7_door_room9_dining_room)
	(locationinplace location_xpos34_ypos14_place11_room8_floorc place11_door_room8_corridor)
	(locationinplace location_xpos40_yneg14_place35_room9_floorb place35_receptacle29_chair)
	(locationinplace location_xpos45_yneg5_place1_room1_floora place1_door_room1_bathroom)
	(locationinplace location_xpos53_ypos19_place12_room13_floora place12_door_room13_staircase)
	(locationinplace location_xpos55_ypos21_place13_room14_floorb place13_door_room14_staircase)
	(locationinplace location_xpos58_ypos15_place9_room6_floora place9_door_room6_corridor)
	(locationinplace location_xpos62_yneg6_place4_room12_floorb place4_door_room12_living_room)
	(locationinplace location_xpos63_yneg6_place6_room5_floorc place6_door_room5_bedroom)
	(locationinplace location_xpos66_yneg12_place5_room10_floora place5_door_room10_home_office)
	(locationinplace location_xpos76_yneg27_place19_room12_floorb place19_item17_vase)
	(locationinplace location_xpos7_yneg6_place8_room4_floorc place8_door_room4_bedroom)
	(placeinroom place0_door_room11_kitchen room11_kitchen)
	(placeinroom place10_door_room7_corridor room7_corridor)
	(placeinroom place11_door_room8_corridor room8_corridor)
	(placeinroom place12_door_room13_staircase room13_staircase)
	(placeinroom place13_door_room14_staircase room14_staircase)
	(placeinroom place19_item17_vase room12_living_room)
	(placeinroom place1_door_room1_bathroom room1_bathroom)
	(placeinroom place2_door_room3_bathroom room3_bathroom)
	(placeinroom place35_receptacle29_chair room9_dining_room)
	(placeinroom place3_door_room2_bathroom room2_bathroom)
	(placeinroom place4_door_room12_living_room room12_living_room)
	(placeinroom place5_door_room10_home_office room10_home_office)
	(placeinroom place6_door_room5_bedroom room5_bedroom)
	(placeinroom place7_door_room9_dining_room room9_dining_room)
	(placeinroom place8_door_room4_bedroom room4_bedroom)
	(placeinroom place9_door_room6_corridor room6_corridor)
	(placelocation location_xpos10_yneg9_place0_room11_floorb place0_door_room11_kitchen)
	(placelocation location_xpos25_ypos20_place10_room7_floorb place10_door_room7_corridor)
	(placelocation location_xpos2_ypos17_place3_room2_floorb place3_door_room2_bathroom)
	(placelocation location_xpos34_yneg13_place2_room3_floorc place2_door_room3_bathroom)
	(placelocation location_xpos34_yneg9_place7_room9_floorb place7_door_room9_dining_room)
	(placelocation location_xpos34_ypos14_place11_room8_floorc place11_door_room8_corridor)
	(placelocation location_xpos40_yneg14_place35_room9_floorb place35_receptacle29_chair)
	(placelocation location_xpos45_yneg5_place1_room1_floora place1_door_room1_bathroom)
	(placelocation location_xpos53_ypos19_place12_room13_floora place12_door_room13_staircase)
	(placelocation location_xpos55_ypos21_place13_room14_floorb place13_door_room14_staircase)
	(placelocation location_xpos58_ypos15_place9_room6_floora place9_door_room6_corridor)
	(placelocation location_xpos62_yneg6_place4_room12_floorb place4_door_room12_living_room)
	(placelocation location_xpos63_yneg6_place6_room5_floorc place6_door_room5_bedroom)
	(placelocation location_xpos66_yneg12_place5_room10_floora place5_door_room10_home_office)
	(placelocation location_xpos76_yneg27_place19_room12_floorb place19_item17_vase)
	(placelocation location_xpos7_yneg6_place8_room4_floorc place8_door_room4_bedroom)
	(receptacleatlocation receptacle29_chair location_xpos40_yneg14_place35_room9_floorb)
	(roomplace place0_door_room11_kitchen room11_kitchen)
	(roomplace place10_door_room7_corridor room7_corridor)
	(roomplace place11_door_room8_corridor room8_corridor)
	(roomplace place12_door_room13_staircase room13_staircase)
	(roomplace place13_door_room14_staircase room14_staircase)
	(roomplace place1_door_room1_bathroom room1_bathroom)
	(roomplace place2_door_room3_bathroom room3_bathroom)
	(roomplace place3_door_room2_bathroom room2_bathroom)
	(roomplace place4_door_room12_living_room room12_living_room)
	(roomplace place5_door_room10_home_office room10_home_office)
	(roomplace place6_door_room5_bedroom room5_bedroom)
	(roomplace place7_door_room9_dining_room room9_dining_room)
	(roomplace place8_door_room4_bedroom room4_bedroom)
	(roomplace place9_door_room6_corridor room6_corridor)
	(roomsconnected room10_home_office room12_living_room)
	(roomsconnected room10_home_office room1_bathroom)
	(roomsconnected room11_kitchen room2_bathroom)
	(roomsconnected room11_kitchen room9_dining_room)
	(roomsconnected room12_living_room room10_home_office)
	(roomsconnected room12_living_room room14_staircase)
	(roomsconnected room12_living_room room9_dining_room)
	(roomsconnected room13_staircase room6_corridor)
	(roomsconnected room14_staircase room12_living_room)
	(roomsconnected room14_staircase room8_corridor)
	(roomsconnected room1_bathroom room10_home_office)
	(roomsconnected room1_bathroom room6_corridor)
	(roomsconnected room2_bathroom room11_kitchen)
	(roomsconnected room2_bathroom room7_corridor)
	(roomsconnected room3_bathroom room4_bedroom)
	(roomsconnected room3_bathroom room5_bedroom)
	(roomsconnected room3_bathroom room8_corridor)
	(roomsconnected room4_bedroom room3_bathroom)
	(roomsconnected room5_bedroom room3_bathroom)
	(roomsconnected room6_corridor room13_staircase)
	(roomsconnected room6_corridor room1_bathroom)
	(roomsconnected room7_corridor room2_bathroom)
	(roomsconnected room8_corridor room14_staircase)
	(roomsconnected room8_corridor room3_bathroom)
	(roomsconnected room9_dining_room room11_kitchen)
	(roomsconnected room9_dining_room room12_living_room)
  )
  (:goal (and
	(inreceptacle item17_vase_mediumitem receptacle29_chair)))
)
