
(define (problem waipahutaskographyv2medium1problem114) (:domain taskographyv2medium1scrub)
  (:objects
        item2_handbag_largeitem - item
	location_xneg13_yneg16_place9_room5_floora - location
	location_xneg13_ypos4_place11_room11_floora - location
	location_xneg16_ypos40_place3_room2_floorb - location
	location_xneg18_ypos18_place10_room6_floorb - location
	location_xneg38_yneg15_place2_room10_floorb - location
	location_xneg38_yneg4_place7_room9_floora - location
	location_xneg42_ypos29_place5_room4_floorb - location
	location_xneg43_ypos31_place1_room7_floora - location
	location_xneg49_ypos32_place20_room7_floora - location
	location_xneg60_ypos26_place20_room7_floora - location
	location_xneg9_ypos27_place4_room8_floora - location
	location_xpos11_ypos39_place8_room1_floorb - location
	location_xpos17_ypos7_place6_room3_floorb - location
	location_xpos1_yneg5_place0_room12_floora - location
	location_xpos7_ypos1_place52_room12_floora - location
	place0_door_room12_utility_room - place
	place10_door_room6_corridor - place
	place11_door_room11_staircase - place
	place1_door_room7_dining_room - place
	place20_receptacle16_chair - place
	place2_door_room10_living_room - place
	place3_door_room2_bathroom - place
	place4_door_room8_kitchen - place
	place52_receptacle54_refrigerator - place
	place5_door_room4_bedroom - place
	place6_door_room3_bedroom - place
	place7_door_room9_living_room - place
	place8_door_room1_bathroom - place
	place9_door_room5_corridor - place
	receptacle16_chair - receptacle
	receptacle54_refrigerator - receptacle
	robot - agent
	room10_living_room - room
	room11_staircase - room
	room12_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bedroom - room
	room4_bedroom - room
	room5_corridor - room
	room6_corridor - room
	room7_dining_room - room
	room8_kitchen - room
	room9_living_room - room
  )
  (:init 
	(atlocation robot location_xpos1_yneg5_place0_room12_floora)
	(inanyreceptacle item2_handbag_largeitem)
	(inplace robot place0_door_room12_utility_room)
	(inreceptacle item2_handbag_largeitem receptacle16_chair)
	(inroom robot room12_utility_room)
	(itematlocation item2_handbag_largeitem location_xneg60_ypos26_place20_room7_floora)
	(locationinplace location_xneg13_yneg16_place9_room5_floora place9_door_room5_corridor)
	(locationinplace location_xneg13_ypos4_place11_room11_floora place11_door_room11_staircase)
	(locationinplace location_xneg16_ypos40_place3_room2_floorb place3_door_room2_bathroom)
	(locationinplace location_xneg18_ypos18_place10_room6_floorb place10_door_room6_corridor)
	(locationinplace location_xneg38_yneg15_place2_room10_floorb place2_door_room10_living_room)
	(locationinplace location_xneg38_yneg4_place7_room9_floora place7_door_room9_living_room)
	(locationinplace location_xneg42_ypos29_place5_room4_floorb place5_door_room4_bedroom)
	(locationinplace location_xneg43_ypos31_place1_room7_floora place1_door_room7_dining_room)
	(locationinplace location_xneg49_ypos32_place20_room7_floora place20_receptacle16_chair)
	(locationinplace location_xneg60_ypos26_place20_room7_floora place20_receptacle16_chair)
	(locationinplace location_xneg9_ypos27_place4_room8_floora place4_door_room8_kitchen)
	(locationinplace location_xpos11_ypos39_place8_room1_floorb place8_door_room1_bathroom)
	(locationinplace location_xpos17_ypos7_place6_room3_floorb place6_door_room3_bedroom)
	(locationinplace location_xpos1_yneg5_place0_room12_floora place0_door_room12_utility_room)
	(locationinplace location_xpos7_ypos1_place52_room12_floora place52_receptacle54_refrigerator)
	(placeinroom place0_door_room12_utility_room room12_utility_room)
	(placeinroom place10_door_room6_corridor room6_corridor)
	(placeinroom place11_door_room11_staircase room11_staircase)
	(placeinroom place1_door_room7_dining_room room7_dining_room)
	(placeinroom place20_receptacle16_chair room7_dining_room)
	(placeinroom place2_door_room10_living_room room10_living_room)
	(placeinroom place3_door_room2_bathroom room2_bathroom)
	(placeinroom place4_door_room8_kitchen room8_kitchen)
	(placeinroom place52_receptacle54_refrigerator room12_utility_room)
	(placeinroom place5_door_room4_bedroom room4_bedroom)
	(placeinroom place6_door_room3_bedroom room3_bedroom)
	(placeinroom place7_door_room9_living_room room9_living_room)
	(placeinroom place8_door_room1_bathroom room1_bathroom)
	(placeinroom place9_door_room5_corridor room5_corridor)
	(placelocation location_xneg13_yneg16_place9_room5_floora place9_door_room5_corridor)
	(placelocation location_xneg13_ypos4_place11_room11_floora place11_door_room11_staircase)
	(placelocation location_xneg16_ypos40_place3_room2_floorb place3_door_room2_bathroom)
	(placelocation location_xneg18_ypos18_place10_room6_floorb place10_door_room6_corridor)
	(placelocation location_xneg38_yneg15_place2_room10_floorb place2_door_room10_living_room)
	(placelocation location_xneg38_yneg4_place7_room9_floora place7_door_room9_living_room)
	(placelocation location_xneg42_ypos29_place5_room4_floorb place5_door_room4_bedroom)
	(placelocation location_xneg43_ypos31_place1_room7_floora place1_door_room7_dining_room)
	(placelocation location_xneg49_ypos32_place20_room7_floora place20_receptacle16_chair)
	(placelocation location_xneg9_ypos27_place4_room8_floora place4_door_room8_kitchen)
	(placelocation location_xpos11_ypos39_place8_room1_floorb place8_door_room1_bathroom)
	(placelocation location_xpos17_ypos7_place6_room3_floorb place6_door_room3_bedroom)
	(placelocation location_xpos1_yneg5_place0_room12_floora place0_door_room12_utility_room)
	(placelocation location_xpos7_ypos1_place52_room12_floora place52_receptacle54_refrigerator)
	(receptacleatlocation receptacle16_chair location_xneg49_ypos32_place20_room7_floora)
	(receptacleatlocation receptacle54_refrigerator location_xpos7_ypos1_place52_room12_floora)
	(receptacleopeningtype receptacle54_refrigerator)
	(roomplace place0_door_room12_utility_room room12_utility_room)
	(roomplace place10_door_room6_corridor room6_corridor)
	(roomplace place11_door_room11_staircase room11_staircase)
	(roomplace place1_door_room7_dining_room room7_dining_room)
	(roomplace place2_door_room10_living_room room10_living_room)
	(roomplace place3_door_room2_bathroom room2_bathroom)
	(roomplace place4_door_room8_kitchen room8_kitchen)
	(roomplace place5_door_room4_bedroom room4_bedroom)
	(roomplace place6_door_room3_bedroom room3_bedroom)
	(roomplace place7_door_room9_living_room room9_living_room)
	(roomplace place8_door_room1_bathroom room1_bathroom)
	(roomplace place9_door_room5_corridor room5_corridor)
	(roomsconnected room10_living_room room6_corridor)
	(roomsconnected room11_staircase room12_utility_room)
	(roomsconnected room11_staircase room6_corridor)
	(roomsconnected room11_staircase room8_kitchen)
	(roomsconnected room12_utility_room room11_staircase)
	(roomsconnected room12_utility_room room5_corridor)
	(roomsconnected room1_bathroom room2_bathroom)
	(roomsconnected room1_bathroom room3_bedroom)
	(roomsconnected room2_bathroom room1_bathroom)
	(roomsconnected room2_bathroom room6_corridor)
	(roomsconnected room3_bedroom room1_bathroom)
	(roomsconnected room4_bedroom room6_corridor)
	(roomsconnected room5_corridor room12_utility_room)
	(roomsconnected room5_corridor room9_living_room)
	(roomsconnected room6_corridor room10_living_room)
	(roomsconnected room6_corridor room11_staircase)
	(roomsconnected room6_corridor room2_bathroom)
	(roomsconnected room6_corridor room4_bedroom)
	(roomsconnected room7_dining_room room8_kitchen)
	(roomsconnected room8_kitchen room11_staircase)
	(roomsconnected room8_kitchen room7_dining_room)
	(roomsconnected room9_living_room room5_corridor)
  )
  (:goal (and
	(inreceptacle item2_handbag_largeitem receptacle54_refrigerator)))
)
