
(define (problem martinvilletaskographyv2medium1problem146) (:domain taskographyv2medium1scrub)
  (:objects
        item75_vase_mediumitem - item
	location_xneg13_yneg79_place8_room16_floorb - location
	location_xneg1_yneg36_place5_room5_floorb - location
	location_xneg20_yneg46_place18_room18_floora - location
	location_xneg23_yneg80_place10_room14_floora - location
	location_xneg26_yneg36_place16_room9_floorb - location
	location_xneg27_yneg1_place6_room6_floorb - location
	location_xneg27_ypos13_place15_room8_floorb - location
	location_xneg2_yneg2_place11_room4_floorb - location
	location_xneg31_yneg35_place2_room7_floora - location
	location_xneg38_yneg1_place57_room2_floorb - location
	location_xneg40_ypos4_place57_room2_floorb - location
	location_xneg43_yneg32_place63_room15_floorb - location
	location_xneg43_ypos2_place17_room13_floora - location
	location_xneg47_yneg49_place4_room15_floorb - location
	location_xneg47_ypos3_place3_room2_floorb - location
	location_xneg48_yneg18_place12_room1_floora - location
	location_xneg48_yneg43_place13_room19_floora - location
	location_xneg49_yneg20_place9_room3_floorb - location
	location_xneg49_yneg84_place7_room10_floorb - location
	location_xneg6_yneg39_place1_room12_floora - location
	location_xneg7_yneg1_place0_room11_floora - location
	location_xpos9_yneg55_place14_room17_floorb - location
	place0_door_room11_empty_room - place
	place10_door_room14_empty_room - place
	place11_door_room4_bedroom - place
	place12_door_room1_bathroom - place
	place13_door_room19_storage - place
	place14_door_room17_lobby - place
	place15_door_room8_corridor - place
	place16_door_room9_corridor - place
	place17_door_room13_empty_room - place
	place18_door_room18_staircase - place
	place1_door_room12_empty_room - place
	place2_door_room7_corridor - place
	place3_door_room2_bathroom - place
	place4_door_room15_kitchen - place
	place57_receptacle57_sink - place
	place5_door_room5_bedroom - place
	place63_receptacle63_refrigerator - place
	place6_door_room6_closet - place
	place7_door_room10_dining_room - place
	place8_door_room16_living_room - place
	place9_door_room3_bathroom - place
	receptacle57_sink - receptacle
	receptacle63_refrigerator - receptacle
	robot - agent
	room10_dining_room - room
	room11_empty_room - room
	room12_empty_room - room
	room13_empty_room - room
	room14_empty_room - room
	room15_kitchen - room
	room16_living_room - room
	room17_lobby - room
	room18_staircase - room
	room19_storage - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_closet - room
	room7_corridor - room
	room8_corridor - room
	room9_corridor - room
  )
  (:init 
	(atlocation robot location_xneg47_yneg49_place4_room15_floorb)
	(inanyreceptacle item75_vase_mediumitem)
	(inplace robot place4_door_room15_kitchen)
	(inreceptacle item75_vase_mediumitem receptacle57_sink)
	(inroom robot room15_kitchen)
	(itematlocation item75_vase_mediumitem location_xneg38_yneg1_place57_room2_floorb)
	(locationinplace location_xneg13_yneg79_place8_room16_floorb place8_door_room16_living_room)
	(locationinplace location_xneg1_yneg36_place5_room5_floorb place5_door_room5_bedroom)
	(locationinplace location_xneg20_yneg46_place18_room18_floora place18_door_room18_staircase)
	(locationinplace location_xneg23_yneg80_place10_room14_floora place10_door_room14_empty_room)
	(locationinplace location_xneg26_yneg36_place16_room9_floorb place16_door_room9_corridor)
	(locationinplace location_xneg27_yneg1_place6_room6_floorb place6_door_room6_closet)
	(locationinplace location_xneg27_ypos13_place15_room8_floorb place15_door_room8_corridor)
	(locationinplace location_xneg2_yneg2_place11_room4_floorb place11_door_room4_bedroom)
	(locationinplace location_xneg31_yneg35_place2_room7_floora place2_door_room7_corridor)
	(locationinplace location_xneg38_yneg1_place57_room2_floorb place57_receptacle57_sink)
	(locationinplace location_xneg40_ypos4_place57_room2_floorb place57_receptacle57_sink)
	(locationinplace location_xneg43_yneg32_place63_room15_floorb place63_receptacle63_refrigerator)
	(locationinplace location_xneg43_ypos2_place17_room13_floora place17_door_room13_empty_room)
	(locationinplace location_xneg47_yneg49_place4_room15_floorb place4_door_room15_kitchen)
	(locationinplace location_xneg47_ypos3_place3_room2_floorb place3_door_room2_bathroom)
	(locationinplace location_xneg48_yneg18_place12_room1_floora place12_door_room1_bathroom)
	(locationinplace location_xneg48_yneg43_place13_room19_floora place13_door_room19_storage)
	(locationinplace location_xneg49_yneg20_place9_room3_floorb place9_door_room3_bathroom)
	(locationinplace location_xneg49_yneg84_place7_room10_floorb place7_door_room10_dining_room)
	(locationinplace location_xneg6_yneg39_place1_room12_floora place1_door_room12_empty_room)
	(locationinplace location_xneg7_yneg1_place0_room11_floora place0_door_room11_empty_room)
	(locationinplace location_xpos9_yneg55_place14_room17_floorb place14_door_room17_lobby)
	(placeinroom place0_door_room11_empty_room room11_empty_room)
	(placeinroom place10_door_room14_empty_room room14_empty_room)
	(placeinroom place11_door_room4_bedroom room4_bedroom)
	(placeinroom place12_door_room1_bathroom room1_bathroom)
	(placeinroom place13_door_room19_storage room19_storage)
	(placeinroom place14_door_room17_lobby room17_lobby)
	(placeinroom place15_door_room8_corridor room8_corridor)
	(placeinroom place16_door_room9_corridor room9_corridor)
	(placeinroom place17_door_room13_empty_room room13_empty_room)
	(placeinroom place18_door_room18_staircase room18_staircase)
	(placeinroom place1_door_room12_empty_room room12_empty_room)
	(placeinroom place2_door_room7_corridor room7_corridor)
	(placeinroom place3_door_room2_bathroom room2_bathroom)
	(placeinroom place4_door_room15_kitchen room15_kitchen)
	(placeinroom place57_receptacle57_sink room2_bathroom)
	(placeinroom place5_door_room5_bedroom room5_bedroom)
	(placeinroom place63_receptacle63_refrigerator room15_kitchen)
	(placeinroom place6_door_room6_closet room6_closet)
	(placeinroom place7_door_room10_dining_room room10_dining_room)
	(placeinroom place8_door_room16_living_room room16_living_room)
	(placeinroom place9_door_room3_bathroom room3_bathroom)
	(placelocation location_xneg13_yneg79_place8_room16_floorb place8_door_room16_living_room)
	(placelocation location_xneg1_yneg36_place5_room5_floorb place5_door_room5_bedroom)
	(placelocation location_xneg20_yneg46_place18_room18_floora place18_door_room18_staircase)
	(placelocation location_xneg23_yneg80_place10_room14_floora place10_door_room14_empty_room)
	(placelocation location_xneg26_yneg36_place16_room9_floorb place16_door_room9_corridor)
	(placelocation location_xneg27_yneg1_place6_room6_floorb place6_door_room6_closet)
	(placelocation location_xneg27_ypos13_place15_room8_floorb place15_door_room8_corridor)
	(placelocation location_xneg2_yneg2_place11_room4_floorb place11_door_room4_bedroom)
	(placelocation location_xneg31_yneg35_place2_room7_floora place2_door_room7_corridor)
	(placelocation location_xneg40_ypos4_place57_room2_floorb place57_receptacle57_sink)
	(placelocation location_xneg43_yneg32_place63_room15_floorb place63_receptacle63_refrigerator)
	(placelocation location_xneg43_ypos2_place17_room13_floora place17_door_room13_empty_room)
	(placelocation location_xneg47_yneg49_place4_room15_floorb place4_door_room15_kitchen)
	(placelocation location_xneg47_ypos3_place3_room2_floorb place3_door_room2_bathroom)
	(placelocation location_xneg48_yneg18_place12_room1_floora place12_door_room1_bathroom)
	(placelocation location_xneg48_yneg43_place13_room19_floora place13_door_room19_storage)
	(placelocation location_xneg49_yneg20_place9_room3_floorb place9_door_room3_bathroom)
	(placelocation location_xneg49_yneg84_place7_room10_floorb place7_door_room10_dining_room)
	(placelocation location_xneg6_yneg39_place1_room12_floora place1_door_room12_empty_room)
	(placelocation location_xneg7_yneg1_place0_room11_floora place0_door_room11_empty_room)
	(placelocation location_xpos9_yneg55_place14_room17_floorb place14_door_room17_lobby)
	(receptacleatlocation receptacle57_sink location_xneg40_ypos4_place57_room2_floorb)
	(receptacleatlocation receptacle63_refrigerator location_xneg43_yneg32_place63_room15_floorb)
	(receptacleopeningtype receptacle63_refrigerator)
	(roomplace place0_door_room11_empty_room room11_empty_room)
	(roomplace place10_door_room14_empty_room room14_empty_room)
	(roomplace place11_door_room4_bedroom room4_bedroom)
	(roomplace place12_door_room1_bathroom room1_bathroom)
	(roomplace place13_door_room19_storage room19_storage)
	(roomplace place14_door_room17_lobby room17_lobby)
	(roomplace place15_door_room8_corridor room8_corridor)
	(roomplace place16_door_room9_corridor room9_corridor)
	(roomplace place17_door_room13_empty_room room13_empty_room)
	(roomplace place18_door_room18_staircase room18_staircase)
	(roomplace place1_door_room12_empty_room room12_empty_room)
	(roomplace place2_door_room7_corridor room7_corridor)
	(roomplace place3_door_room2_bathroom room2_bathroom)
	(roomplace place4_door_room15_kitchen room15_kitchen)
	(roomplace place5_door_room5_bedroom room5_bedroom)
	(roomplace place6_door_room6_closet room6_closet)
	(roomplace place7_door_room10_dining_room room10_dining_room)
	(roomplace place8_door_room16_living_room room16_living_room)
	(roomplace place9_door_room3_bathroom room3_bathroom)
	(roomsconnected room10_dining_room room15_kitchen)
	(roomsconnected room11_empty_room room13_empty_room)
	(roomsconnected room12_empty_room room18_staircase)
	(roomsconnected room13_empty_room room11_empty_room)
	(roomsconnected room13_empty_room room1_bathroom)
	(roomsconnected room14_empty_room room18_staircase)
	(roomsconnected room15_kitchen room10_dining_room)
	(roomsconnected room15_kitchen room9_corridor)
	(roomsconnected room16_living_room room17_lobby)
	(roomsconnected room17_lobby room16_living_room)
	(roomsconnected room17_lobby room5_bedroom)
	(roomsconnected room18_staircase room12_empty_room)
	(roomsconnected room18_staircase room14_empty_room)
	(roomsconnected room18_staircase room7_corridor)
	(roomsconnected room18_staircase room9_corridor)
	(roomsconnected room19_storage room7_corridor)
	(roomsconnected room1_bathroom room13_empty_room)
	(roomsconnected room1_bathroom room7_corridor)
	(roomsconnected room2_bathroom room3_bathroom)
	(roomsconnected room2_bathroom room6_closet)
	(roomsconnected room3_bathroom room2_bathroom)
	(roomsconnected room3_bathroom room9_corridor)
	(roomsconnected room4_bedroom room6_closet)
	(roomsconnected room5_bedroom room17_lobby)
	(roomsconnected room5_bedroom room9_corridor)
	(roomsconnected room6_closet room2_bathroom)
	(roomsconnected room6_closet room4_bedroom)
	(roomsconnected room6_closet room8_corridor)
	(roomsconnected room7_corridor room18_staircase)
	(roomsconnected room7_corridor room19_storage)
	(roomsconnected room7_corridor room1_bathroom)
	(roomsconnected room8_corridor room6_closet)
	(roomsconnected room9_corridor room15_kitchen)
	(roomsconnected room9_corridor room18_staircase)
	(roomsconnected room9_corridor room3_bathroom)
	(roomsconnected room9_corridor room5_bedroom)
  )
  (:goal (and
	(inreceptacle item75_vase_mediumitem receptacle63_refrigerator)))
)
