
(define (problem edsontaskographyv2medium1problem121) (:domain taskographyv2medium1scrub)
  (:objects
        item71_vase_mediumitem - item
	location_xneg14_ypos17_place17_room17_floora - location
	location_xneg22_ypos3_place2_room13_floorb - location
	location_xneg26_ypos9_place62_room13_floorb - location
	location_xneg29_ypos4_place15_room19_floora - location
	location_xneg30_ypos44_place5_room14_floora - location
	location_xneg33_ypos14_place62_room13_floorb - location
	location_xneg40_ypos39_place7_room15_floorb - location
	location_xneg56_ypos3_place6_room10_floorb - location
	location_xneg59_ypos44_place9_room9_floora - location
	location_xpos21_yneg24_place8_room12_floorb - location
	location_xpos26_yneg43_place57_room16_floora - location
	location_xpos35_yneg63_place10_room6_floorb - location
	location_xpos36_ypos48_place11_room5_floorb - location
	location_xpos38_yneg32_place0_room16_floora - location
	location_xpos38_ypos39_place1_room4_floora - location
	location_xpos41_ypos7_place3_room2_floorb - location
	location_xpos42_yneg35_place14_room7_floorb - location
	location_xpos43_yneg15_place12_room3_floorb - location
	location_xpos47_ypos9_place13_room1_floora - location
	location_xpos5_yneg2_place4_room11_floorb - location
	location_xpos5_ypos38_place18_room18_floora - location
	location_xpos8_ypos31_place16_room8_floorb - location
	place0_door_room16_playroom - place
	place10_door_room6_bedroom - place
	place11_door_room5_bedroom - place
	place12_door_room3_bathroom - place
	place13_door_room1_bathroom - place
	place14_door_room7_closet - place
	place15_door_room19_utility_room - place
	place16_door_room8_corridor - place
	place17_door_room17_staircase - place
	place18_door_room18_storage - place
	place1_door_room4_bedroom - place
	place2_door_room13_kitchen - place
	place3_door_room2_bathroom - place
	place4_door_room11_dining_room - place
	place57_receptacle47_dining_table - place
	place5_door_room14_living_room - place
	place62_receptacle55_microwave - place
	place6_door_room10_dining_room - place
	place7_door_room15_living_room - place
	place8_door_room12_home_office - place
	place9_door_room9_dining_room - place
	receptacle47_dining_table - receptacle
	receptacle55_microwave - receptacle
	robot - agent
	room10_dining_room - room
	room11_dining_room - room
	room12_home_office - room
	room13_kitchen - room
	room14_living_room - room
	room15_living_room - room
	room16_playroom - room
	room17_staircase - room
	room18_storage - room
	room19_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_bedroom - room
	room7_closet - room
	room8_corridor - room
	room9_dining_room - room
  )
  (:init 
	(atlocation robot location_xpos42_yneg35_place14_room7_floorb)
	(inanyreceptacle item71_vase_mediumitem)
	(inplace robot place14_door_room7_closet)
	(inreceptacle item71_vase_mediumitem receptacle55_microwave)
	(inroom robot room7_closet)
	(itematlocation item71_vase_mediumitem location_xneg33_ypos14_place62_room13_floorb)
	(locationinplace location_xneg14_ypos17_place17_room17_floora place17_door_room17_staircase)
	(locationinplace location_xneg22_ypos3_place2_room13_floorb place2_door_room13_kitchen)
	(locationinplace location_xneg26_ypos9_place62_room13_floorb place62_receptacle55_microwave)
	(locationinplace location_xneg29_ypos4_place15_room19_floora place15_door_room19_utility_room)
	(locationinplace location_xneg30_ypos44_place5_room14_floora place5_door_room14_living_room)
	(locationinplace location_xneg33_ypos14_place62_room13_floorb place62_receptacle55_microwave)
	(locationinplace location_xneg40_ypos39_place7_room15_floorb place7_door_room15_living_room)
	(locationinplace location_xneg56_ypos3_place6_room10_floorb place6_door_room10_dining_room)
	(locationinplace location_xneg59_ypos44_place9_room9_floora place9_door_room9_dining_room)
	(locationinplace location_xpos21_yneg24_place8_room12_floorb place8_door_room12_home_office)
	(locationinplace location_xpos26_yneg43_place57_room16_floora place57_receptacle47_dining_table)
	(locationinplace location_xpos35_yneg63_place10_room6_floorb place10_door_room6_bedroom)
	(locationinplace location_xpos36_ypos48_place11_room5_floorb place11_door_room5_bedroom)
	(locationinplace location_xpos38_yneg32_place0_room16_floora place0_door_room16_playroom)
	(locationinplace location_xpos38_ypos39_place1_room4_floora place1_door_room4_bedroom)
	(locationinplace location_xpos41_ypos7_place3_room2_floorb place3_door_room2_bathroom)
	(locationinplace location_xpos42_yneg35_place14_room7_floorb place14_door_room7_closet)
	(locationinplace location_xpos43_yneg15_place12_room3_floorb place12_door_room3_bathroom)
	(locationinplace location_xpos47_ypos9_place13_room1_floora place13_door_room1_bathroom)
	(locationinplace location_xpos5_yneg2_place4_room11_floorb place4_door_room11_dining_room)
	(locationinplace location_xpos5_ypos38_place18_room18_floora place18_door_room18_storage)
	(locationinplace location_xpos8_ypos31_place16_room8_floorb place16_door_room8_corridor)
	(placeinroom place0_door_room16_playroom room16_playroom)
	(placeinroom place10_door_room6_bedroom room6_bedroom)
	(placeinroom place11_door_room5_bedroom room5_bedroom)
	(placeinroom place12_door_room3_bathroom room3_bathroom)
	(placeinroom place13_door_room1_bathroom room1_bathroom)
	(placeinroom place14_door_room7_closet room7_closet)
	(placeinroom place15_door_room19_utility_room room19_utility_room)
	(placeinroom place16_door_room8_corridor room8_corridor)
	(placeinroom place17_door_room17_staircase room17_staircase)
	(placeinroom place18_door_room18_storage room18_storage)
	(placeinroom place1_door_room4_bedroom room4_bedroom)
	(placeinroom place2_door_room13_kitchen room13_kitchen)
	(placeinroom place3_door_room2_bathroom room2_bathroom)
	(placeinroom place4_door_room11_dining_room room11_dining_room)
	(placeinroom place57_receptacle47_dining_table room16_playroom)
	(placeinroom place5_door_room14_living_room room14_living_room)
	(placeinroom place62_receptacle55_microwave room13_kitchen)
	(placeinroom place6_door_room10_dining_room room10_dining_room)
	(placeinroom place7_door_room15_living_room room15_living_room)
	(placeinroom place8_door_room12_home_office room12_home_office)
	(placeinroom place9_door_room9_dining_room room9_dining_room)
	(placelocation location_xneg14_ypos17_place17_room17_floora place17_door_room17_staircase)
	(placelocation location_xneg22_ypos3_place2_room13_floorb place2_door_room13_kitchen)
	(placelocation location_xneg26_ypos9_place62_room13_floorb place62_receptacle55_microwave)
	(placelocation location_xneg29_ypos4_place15_room19_floora place15_door_room19_utility_room)
	(placelocation location_xneg30_ypos44_place5_room14_floora place5_door_room14_living_room)
	(placelocation location_xneg40_ypos39_place7_room15_floorb place7_door_room15_living_room)
	(placelocation location_xneg56_ypos3_place6_room10_floorb place6_door_room10_dining_room)
	(placelocation location_xneg59_ypos44_place9_room9_floora place9_door_room9_dining_room)
	(placelocation location_xpos21_yneg24_place8_room12_floorb place8_door_room12_home_office)
	(placelocation location_xpos26_yneg43_place57_room16_floora place57_receptacle47_dining_table)
	(placelocation location_xpos35_yneg63_place10_room6_floorb place10_door_room6_bedroom)
	(placelocation location_xpos36_ypos48_place11_room5_floorb place11_door_room5_bedroom)
	(placelocation location_xpos38_yneg32_place0_room16_floora place0_door_room16_playroom)
	(placelocation location_xpos38_ypos39_place1_room4_floora place1_door_room4_bedroom)
	(placelocation location_xpos41_ypos7_place3_room2_floorb place3_door_room2_bathroom)
	(placelocation location_xpos42_yneg35_place14_room7_floorb place14_door_room7_closet)
	(placelocation location_xpos43_yneg15_place12_room3_floorb place12_door_room3_bathroom)
	(placelocation location_xpos47_ypos9_place13_room1_floora place13_door_room1_bathroom)
	(placelocation location_xpos5_yneg2_place4_room11_floorb place4_door_room11_dining_room)
	(placelocation location_xpos5_ypos38_place18_room18_floora place18_door_room18_storage)
	(placelocation location_xpos8_ypos31_place16_room8_floorb place16_door_room8_corridor)
	(receptacleatlocation receptacle47_dining_table location_xpos26_yneg43_place57_room16_floora)
	(receptacleatlocation receptacle55_microwave location_xneg26_ypos9_place62_room13_floorb)
	(receptacleopeningtype receptacle55_microwave)
	(roomplace place0_door_room16_playroom room16_playroom)
	(roomplace place10_door_room6_bedroom room6_bedroom)
	(roomplace place11_door_room5_bedroom room5_bedroom)
	(roomplace place12_door_room3_bathroom room3_bathroom)
	(roomplace place13_door_room1_bathroom room1_bathroom)
	(roomplace place14_door_room7_closet room7_closet)
	(roomplace place15_door_room19_utility_room room19_utility_room)
	(roomplace place16_door_room8_corridor room8_corridor)
	(roomplace place17_door_room17_staircase room17_staircase)
	(roomplace place18_door_room18_storage room18_storage)
	(roomplace place1_door_room4_bedroom room4_bedroom)
	(roomplace place2_door_room13_kitchen room13_kitchen)
	(roomplace place3_door_room2_bathroom room2_bathroom)
	(roomplace place4_door_room11_dining_room room11_dining_room)
	(roomplace place5_door_room14_living_room room14_living_room)
	(roomplace place6_door_room10_dining_room room10_dining_room)
	(roomplace place7_door_room15_living_room room15_living_room)
	(roomplace place8_door_room12_home_office room12_home_office)
	(roomplace place9_door_room9_dining_room room9_dining_room)
	(roomsconnected room10_dining_room room13_kitchen)
	(roomsconnected room10_dining_room room15_living_room)
	(roomsconnected room11_dining_room room12_home_office)
	(roomsconnected room11_dining_room room13_kitchen)
	(roomsconnected room11_dining_room room8_corridor)
	(roomsconnected room12_home_office room11_dining_room)
	(roomsconnected room12_home_office room7_closet)
	(roomsconnected room13_kitchen room10_dining_room)
	(roomsconnected room13_kitchen room11_dining_room)
	(roomsconnected room13_kitchen room17_staircase)
	(roomsconnected room14_living_room room17_staircase)
	(roomsconnected room14_living_room room9_dining_room)
	(roomsconnected room15_living_room room10_dining_room)
	(roomsconnected room16_playroom room1_bathroom)
	(roomsconnected room17_staircase room13_kitchen)
	(roomsconnected room17_staircase room14_living_room)
	(roomsconnected room17_staircase room18_storage)
	(roomsconnected room17_staircase room19_utility_room)
	(roomsconnected room18_storage room17_staircase)
	(roomsconnected room18_storage room4_bedroom)
	(roomsconnected room19_utility_room room17_staircase)
	(roomsconnected room1_bathroom room16_playroom)
	(roomsconnected room1_bathroom room4_bedroom)
	(roomsconnected room2_bathroom room3_bathroom)
	(roomsconnected room3_bathroom room2_bathroom)
	(roomsconnected room3_bathroom room7_closet)
	(roomsconnected room4_bedroom room18_storage)
	(roomsconnected room4_bedroom room1_bathroom)
	(roomsconnected room5_bedroom room8_corridor)
	(roomsconnected room6_bedroom room7_closet)
	(roomsconnected room7_closet room12_home_office)
	(roomsconnected room7_closet room3_bathroom)
	(roomsconnected room7_closet room6_bedroom)
	(roomsconnected room8_corridor room11_dining_room)
	(roomsconnected room8_corridor room5_bedroom)
	(roomsconnected room9_dining_room room14_living_room)
  )
  (:goal (and
	(inreceptacle item71_vase_mediumitem receptacle47_dining_table)))
)
