
(define (problem couderaytaskographyv2medium1problem135) (:domain taskographyv2medium1scrub)
  (:objects
        item21_vase_mediumitem - item
	location_xneg14_ypos13_place0_room13_floora - location
	location_xneg1_ypos40_place10_room12_floorb - location
	location_xneg26_ypos9_place7_room9_floorb - location
	location_xneg28_ypos40_place8_room5_floorc - location
	location_xneg31_ypos9_place17_room10_floorc - location
	location_xneg32_ypos39_place12_room17_floorb - location
	location_xneg35_ypos10_place18_room11_floord - location
	location_xneg36_yneg4_place14_room19_floora - location
	location_xneg36_yneg6_place13_room21_floorc - location
	location_xneg36_yneg6_place20_room20_floorb - location
	location_xneg41_ypos14_place16_room8_floora - location
	location_xneg41_ypos31_place15_room7_floord - location
	location_xneg4_yneg17_place11_room4_floorc - location
	location_xneg5_yneg6_place9_room14_floord - location
	location_xneg5_ypos13_place3_room16_floord - location
	location_xneg7_yneg13_place19_room18_floorb - location
	location_xpos12_yneg9_place38_room1_floorb - location
	location_xpos12_ypos29_place46_room12_floorb - location
	location_xpos1_ypos3_place4_room2_floorc - location
	location_xpos3_ypos20_place6_room6_floorc - location
	location_xpos3_ypos43_place2_room3_floorc - location
	location_xpos4_ypos10_place1_room15_floorb - location
	location_xpos6_ypos26_place46_room12_floorb - location
	location_xpos7_yneg14_place5_room1_floorb - location
	place0_door_room13_garage - place
	place10_door_room12_dining_room - place
	place11_door_room4_bedroom - place
	place12_door_room17_living_room - place
	place13_door_room21_staircase - place
	place14_door_room19_staircase - place
	place15_door_room7_closet - place
	place16_door_room8_corridor - place
	place17_door_room10_corridor - place
	place18_door_room11_corridor - place
	place19_door_room18_lobby - place
	place1_door_room15_kitchen - place
	place20_door_room20_staircase - place
	place2_door_room3_bathroom - place
	place38_receptacle34_toilet - place
	place3_door_room16_kitchen - place
	place46_receptacle42_chair - place
	place4_door_room2_bathroom - place
	place5_door_room1_bathroom - place
	place6_door_room6_closet - place
	place7_door_room9_corridor - place
	place8_door_room5_bedroom - place
	place9_door_room14_home_office - place
	receptacle34_toilet - receptacle
	receptacle42_chair - receptacle
	robot - agent
	room10_corridor - room
	room11_corridor - room
	room12_dining_room - room
	room13_garage - room
	room14_home_office - room
	room15_kitchen - room
	room16_kitchen - room
	room17_living_room - room
	room18_lobby - room
	room19_staircase - room
	room1_bathroom - room
	room20_staircase - room
	room21_staircase - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_closet - room
	room7_closet - room
	room8_corridor - room
	room9_corridor - room
  )
  (:init 
	(atlocation robot location_xpos1_ypos3_place4_room2_floorc)
	(inanyreceptacle item21_vase_mediumitem)
	(inplace robot place4_door_room2_bathroom)
	(inreceptacle item21_vase_mediumitem receptacle42_chair)
	(inroom robot room2_bathroom)
	(itematlocation item21_vase_mediumitem location_xpos12_ypos29_place46_room12_floorb)
	(locationinplace location_xneg14_ypos13_place0_room13_floora place0_door_room13_garage)
	(locationinplace location_xneg1_ypos40_place10_room12_floorb place10_door_room12_dining_room)
	(locationinplace location_xneg26_ypos9_place7_room9_floorb place7_door_room9_corridor)
	(locationinplace location_xneg28_ypos40_place8_room5_floorc place8_door_room5_bedroom)
	(locationinplace location_xneg31_ypos9_place17_room10_floorc place17_door_room10_corridor)
	(locationinplace location_xneg32_ypos39_place12_room17_floorb place12_door_room17_living_room)
	(locationinplace location_xneg35_ypos10_place18_room11_floord place18_door_room11_corridor)
	(locationinplace location_xneg36_yneg4_place14_room19_floora place14_door_room19_staircase)
	(locationinplace location_xneg36_yneg6_place13_room21_floorc place13_door_room21_staircase)
	(locationinplace location_xneg36_yneg6_place20_room20_floorb place20_door_room20_staircase)
	(locationinplace location_xneg41_ypos14_place16_room8_floora place16_door_room8_corridor)
	(locationinplace location_xneg41_ypos31_place15_room7_floord place15_door_room7_closet)
	(locationinplace location_xneg4_yneg17_place11_room4_floorc place11_door_room4_bedroom)
	(locationinplace location_xneg5_yneg6_place9_room14_floord place9_door_room14_home_office)
	(locationinplace location_xneg5_ypos13_place3_room16_floord place3_door_room16_kitchen)
	(locationinplace location_xneg7_yneg13_place19_room18_floorb place19_door_room18_lobby)
	(locationinplace location_xpos12_yneg9_place38_room1_floorb place38_receptacle34_toilet)
	(locationinplace location_xpos12_ypos29_place46_room12_floorb place46_receptacle42_chair)
	(locationinplace location_xpos1_ypos3_place4_room2_floorc place4_door_room2_bathroom)
	(locationinplace location_xpos3_ypos20_place6_room6_floorc place6_door_room6_closet)
	(locationinplace location_xpos3_ypos43_place2_room3_floorc place2_door_room3_bathroom)
	(locationinplace location_xpos4_ypos10_place1_room15_floorb place1_door_room15_kitchen)
	(locationinplace location_xpos6_ypos26_place46_room12_floorb place46_receptacle42_chair)
	(locationinplace location_xpos7_yneg14_place5_room1_floorb place5_door_room1_bathroom)
	(placeinroom place0_door_room13_garage room13_garage)
	(placeinroom place10_door_room12_dining_room room12_dining_room)
	(placeinroom place11_door_room4_bedroom room4_bedroom)
	(placeinroom place12_door_room17_living_room room17_living_room)
	(placeinroom place13_door_room21_staircase room21_staircase)
	(placeinroom place14_door_room19_staircase room19_staircase)
	(placeinroom place15_door_room7_closet room7_closet)
	(placeinroom place16_door_room8_corridor room8_corridor)
	(placeinroom place17_door_room10_corridor room10_corridor)
	(placeinroom place18_door_room11_corridor room11_corridor)
	(placeinroom place19_door_room18_lobby room18_lobby)
	(placeinroom place1_door_room15_kitchen room15_kitchen)
	(placeinroom place20_door_room20_staircase room20_staircase)
	(placeinroom place2_door_room3_bathroom room3_bathroom)
	(placeinroom place38_receptacle34_toilet room1_bathroom)
	(placeinroom place3_door_room16_kitchen room16_kitchen)
	(placeinroom place46_receptacle42_chair room12_dining_room)
	(placeinroom place4_door_room2_bathroom room2_bathroom)
	(placeinroom place5_door_room1_bathroom room1_bathroom)
	(placeinroom place6_door_room6_closet room6_closet)
	(placeinroom place7_door_room9_corridor room9_corridor)
	(placeinroom place8_door_room5_bedroom room5_bedroom)
	(placeinroom place9_door_room14_home_office room14_home_office)
	(placelocation location_xneg14_ypos13_place0_room13_floora place0_door_room13_garage)
	(placelocation location_xneg1_ypos40_place10_room12_floorb place10_door_room12_dining_room)
	(placelocation location_xneg26_ypos9_place7_room9_floorb place7_door_room9_corridor)
	(placelocation location_xneg28_ypos40_place8_room5_floorc place8_door_room5_bedroom)
	(placelocation location_xneg31_ypos9_place17_room10_floorc place17_door_room10_corridor)
	(placelocation location_xneg32_ypos39_place12_room17_floorb place12_door_room17_living_room)
	(placelocation location_xneg35_ypos10_place18_room11_floord place18_door_room11_corridor)
	(placelocation location_xneg36_yneg4_place14_room19_floora place14_door_room19_staircase)
	(placelocation location_xneg36_yneg6_place13_room21_floorc place13_door_room21_staircase)
	(placelocation location_xneg36_yneg6_place20_room20_floorb place20_door_room20_staircase)
	(placelocation location_xneg41_ypos14_place16_room8_floora place16_door_room8_corridor)
	(placelocation location_xneg41_ypos31_place15_room7_floord place15_door_room7_closet)
	(placelocation location_xneg4_yneg17_place11_room4_floorc place11_door_room4_bedroom)
	(placelocation location_xneg5_yneg6_place9_room14_floord place9_door_room14_home_office)
	(placelocation location_xneg5_ypos13_place3_room16_floord place3_door_room16_kitchen)
	(placelocation location_xneg7_yneg13_place19_room18_floorb place19_door_room18_lobby)
	(placelocation location_xpos12_yneg9_place38_room1_floorb place38_receptacle34_toilet)
	(placelocation location_xpos1_ypos3_place4_room2_floorc place4_door_room2_bathroom)
	(placelocation location_xpos3_ypos20_place6_room6_floorc place6_door_room6_closet)
	(placelocation location_xpos3_ypos43_place2_room3_floorc place2_door_room3_bathroom)
	(placelocation location_xpos4_ypos10_place1_room15_floorb place1_door_room15_kitchen)
	(placelocation location_xpos6_ypos26_place46_room12_floorb place46_receptacle42_chair)
	(placelocation location_xpos7_yneg14_place5_room1_floorb place5_door_room1_bathroom)
	(receptacleatlocation receptacle34_toilet location_xpos12_yneg9_place38_room1_floorb)
	(receptacleatlocation receptacle42_chair location_xpos6_ypos26_place46_room12_floorb)
	(roomplace place0_door_room13_garage room13_garage)
	(roomplace place10_door_room12_dining_room room12_dining_room)
	(roomplace place11_door_room4_bedroom room4_bedroom)
	(roomplace place12_door_room17_living_room room17_living_room)
	(roomplace place13_door_room21_staircase room21_staircase)
	(roomplace place14_door_room19_staircase room19_staircase)
	(roomplace place15_door_room7_closet room7_closet)
	(roomplace place16_door_room8_corridor room8_corridor)
	(roomplace place17_door_room10_corridor room10_corridor)
	(roomplace place18_door_room11_corridor room11_corridor)
	(roomplace place19_door_room18_lobby room18_lobby)
	(roomplace place1_door_room15_kitchen room15_kitchen)
	(roomplace place20_door_room20_staircase room20_staircase)
	(roomplace place2_door_room3_bathroom room3_bathroom)
	(roomplace place3_door_room16_kitchen room16_kitchen)
	(roomplace place4_door_room2_bathroom room2_bathroom)
	(roomplace place5_door_room1_bathroom room1_bathroom)
	(roomplace place6_door_room6_closet room6_closet)
	(roomplace place7_door_room9_corridor room9_corridor)
	(roomplace place8_door_room5_bedroom room5_bedroom)
	(roomplace place9_door_room14_home_office room14_home_office)
	(roomsconnected room10_corridor room20_staircase)
	(roomsconnected room10_corridor room21_staircase)
	(roomsconnected room10_corridor room5_bedroom)
	(roomsconnected room11_corridor room16_kitchen)
	(roomsconnected room11_corridor room21_staircase)
	(roomsconnected room11_corridor room7_closet)
	(roomsconnected room12_dining_room room15_kitchen)
	(roomsconnected room12_dining_room room17_living_room)
	(roomsconnected room13_garage room8_corridor)
	(roomsconnected room14_home_office room16_kitchen)
	(roomsconnected room15_kitchen room12_dining_room)
	(roomsconnected room15_kitchen room1_bathroom)
	(roomsconnected room16_kitchen room11_corridor)
	(roomsconnected room16_kitchen room14_home_office)
	(roomsconnected room17_living_room room12_dining_room)
	(roomsconnected room18_lobby room1_bathroom)
	(roomsconnected room18_lobby room9_corridor)
	(roomsconnected room19_staircase room8_corridor)
	(roomsconnected room19_staircase room9_corridor)
	(roomsconnected room1_bathroom room15_kitchen)
	(roomsconnected room1_bathroom room18_lobby)
	(roomsconnected room20_staircase room10_corridor)
	(roomsconnected room20_staircase room9_corridor)
	(roomsconnected room21_staircase room10_corridor)
	(roomsconnected room21_staircase room11_corridor)
	(roomsconnected room2_bathroom room4_bedroom)
	(roomsconnected room2_bathroom room6_closet)
	(roomsconnected room3_bathroom room5_bedroom)
	(roomsconnected room3_bathroom room6_closet)
	(roomsconnected room4_bedroom room2_bathroom)
	(roomsconnected room5_bedroom room10_corridor)
	(roomsconnected room5_bedroom room3_bathroom)
	(roomsconnected room6_closet room2_bathroom)
	(roomsconnected room6_closet room3_bathroom)
	(roomsconnected room7_closet room11_corridor)
	(roomsconnected room8_corridor room13_garage)
	(roomsconnected room8_corridor room19_staircase)
	(roomsconnected room9_corridor room18_lobby)
	(roomsconnected room9_corridor room19_staircase)
	(roomsconnected room9_corridor room20_staircase)
  )
  (:goal (and
	(inreceptacle item21_vase_mediumitem receptacle34_toilet)))
)
