
(define (problem tylertaskographyv2medium1problem91) (:domain taskographyv2medium1scrub)
  (:objects
        item46_potted_plant_largeitem - item
	location_xneg11_ypos11_place10_room3_floora - location
	location_xneg15_ypos26_place7_room11_floorb - location
	location_xneg8_ypos3_place46_room3_floora - location
	location_xpos13_ypos2_place8_room12_floorb - location
	location_xpos16_ypos38_place38_room4_floora - location
	location_xpos29_ypos33_place6_room9_floorb - location
	location_xpos37_ypos2_place5_room7_floora - location
	location_xpos47_ypos15_place0_room4_floora - location
	location_xpos49_ypos3_place9_room6_floorb - location
	location_xpos58_ypos38_place1_room13_floora - location
	location_xpos5_ypos7_place46_room3_floora - location
	location_xpos62_ypos26_place11_room5_floorb - location
	location_xpos80_ypos3_place2_room10_floorb - location
	location_xpos86_ypos33_place3_room2_floorb - location
	location_xpos88_ypos29_place4_room1_floora - location
	location_xpos91_ypos6_place12_room8_floora - location
	place0_door_room4_corridor - place
	place10_door_room3_bedroom - place
	place11_door_room5_corridor - place
	place12_door_room8_empty_room - place
	place1_door_room13_staricase - place
	place2_door_room10_kitchen - place
	place38_receptacle37_chair - place
	place3_door_room2_bathroom - place
	place46_receptacle49_bed - place
	place4_door_room1_bathroom - place
	place5_door_room7_empty_room - place
	place6_door_room9_empty_room - place
	place7_door_room11_living_room - place
	place8_door_room12_living_room - place
	place9_door_room6_dining_room - place
	receptacle37_chair - receptacle
	receptacle49_bed - receptacle
	robot - agent
	room10_kitchen - room
	room11_living_room - room
	room12_living_room - room
	room13_staricase - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bedroom - room
	room4_corridor - room
	room5_corridor - room
	room6_dining_room - room
	room7_empty_room - room
	room8_empty_room - room
	room9_empty_room - room
  )
  (:init 
	(atlocation robot location_xpos29_ypos33_place6_room9_floorb)
	(inanyreceptacle item46_potted_plant_largeitem)
	(inplace robot place6_door_room9_empty_room)
	(inreceptacle item46_potted_plant_largeitem receptacle49_bed)
	(inroom robot room9_empty_room)
	(itematlocation item46_potted_plant_largeitem location_xpos5_ypos7_place46_room3_floora)
	(locationinplace location_xneg11_ypos11_place10_room3_floora place10_door_room3_bedroom)
	(locationinplace location_xneg15_ypos26_place7_room11_floorb place7_door_room11_living_room)
	(locationinplace location_xneg8_ypos3_place46_room3_floora place46_receptacle49_bed)
	(locationinplace location_xpos13_ypos2_place8_room12_floorb place8_door_room12_living_room)
	(locationinplace location_xpos16_ypos38_place38_room4_floora place38_receptacle37_chair)
	(locationinplace location_xpos29_ypos33_place6_room9_floorb place6_door_room9_empty_room)
	(locationinplace location_xpos37_ypos2_place5_room7_floora place5_door_room7_empty_room)
	(locationinplace location_xpos47_ypos15_place0_room4_floora place0_door_room4_corridor)
	(locationinplace location_xpos49_ypos3_place9_room6_floorb place9_door_room6_dining_room)
	(locationinplace location_xpos58_ypos38_place1_room13_floora place1_door_room13_staricase)
	(locationinplace location_xpos5_ypos7_place46_room3_floora place46_receptacle49_bed)
	(locationinplace location_xpos62_ypos26_place11_room5_floorb place11_door_room5_corridor)
	(locationinplace location_xpos80_ypos3_place2_room10_floorb place2_door_room10_kitchen)
	(locationinplace location_xpos86_ypos33_place3_room2_floorb place3_door_room2_bathroom)
	(locationinplace location_xpos88_ypos29_place4_room1_floora place4_door_room1_bathroom)
	(locationinplace location_xpos91_ypos6_place12_room8_floora place12_door_room8_empty_room)
	(placeinroom place0_door_room4_corridor room4_corridor)
	(placeinroom place10_door_room3_bedroom room3_bedroom)
	(placeinroom place11_door_room5_corridor room5_corridor)
	(placeinroom place12_door_room8_empty_room room8_empty_room)
	(placeinroom place1_door_room13_staricase room13_staricase)
	(placeinroom place2_door_room10_kitchen room10_kitchen)
	(placeinroom place38_receptacle37_chair room4_corridor)
	(placeinroom place3_door_room2_bathroom room2_bathroom)
	(placeinroom place46_receptacle49_bed room3_bedroom)
	(placeinroom place4_door_room1_bathroom room1_bathroom)
	(placeinroom place5_door_room7_empty_room room7_empty_room)
	(placeinroom place6_door_room9_empty_room room9_empty_room)
	(placeinroom place7_door_room11_living_room room11_living_room)
	(placeinroom place8_door_room12_living_room room12_living_room)
	(placeinroom place9_door_room6_dining_room room6_dining_room)
	(placelocation location_xneg11_ypos11_place10_room3_floora place10_door_room3_bedroom)
	(placelocation location_xneg15_ypos26_place7_room11_floorb place7_door_room11_living_room)
	(placelocation location_xneg8_ypos3_place46_room3_floora place46_receptacle49_bed)
	(placelocation location_xpos13_ypos2_place8_room12_floorb place8_door_room12_living_room)
	(placelocation location_xpos16_ypos38_place38_room4_floora place38_receptacle37_chair)
	(placelocation location_xpos29_ypos33_place6_room9_floorb place6_door_room9_empty_room)
	(placelocation location_xpos37_ypos2_place5_room7_floora place5_door_room7_empty_room)
	(placelocation location_xpos47_ypos15_place0_room4_floora place0_door_room4_corridor)
	(placelocation location_xpos49_ypos3_place9_room6_floorb place9_door_room6_dining_room)
	(placelocation location_xpos58_ypos38_place1_room13_floora place1_door_room13_staricase)
	(placelocation location_xpos62_ypos26_place11_room5_floorb place11_door_room5_corridor)
	(placelocation location_xpos80_ypos3_place2_room10_floorb place2_door_room10_kitchen)
	(placelocation location_xpos86_ypos33_place3_room2_floorb place3_door_room2_bathroom)
	(placelocation location_xpos88_ypos29_place4_room1_floora place4_door_room1_bathroom)
	(placelocation location_xpos91_ypos6_place12_room8_floora place12_door_room8_empty_room)
	(receptacleatlocation receptacle37_chair location_xpos16_ypos38_place38_room4_floora)
	(receptacleatlocation receptacle49_bed location_xneg8_ypos3_place46_room3_floora)
	(roomplace place0_door_room4_corridor room4_corridor)
	(roomplace place10_door_room3_bedroom room3_bedroom)
	(roomplace place11_door_room5_corridor room5_corridor)
	(roomplace place12_door_room8_empty_room room8_empty_room)
	(roomplace place1_door_room13_staricase room13_staricase)
	(roomplace place2_door_room10_kitchen room10_kitchen)
	(roomplace place3_door_room2_bathroom room2_bathroom)
	(roomplace place4_door_room1_bathroom room1_bathroom)
	(roomplace place5_door_room7_empty_room room7_empty_room)
	(roomplace place6_door_room9_empty_room room9_empty_room)
	(roomplace place7_door_room11_living_room room11_living_room)
	(roomplace place8_door_room12_living_room room12_living_room)
	(roomplace place9_door_room6_dining_room room6_dining_room)
	(roomsconnected room10_kitchen room5_corridor)
	(roomsconnected room11_living_room room12_living_room)
	(roomsconnected room12_living_room room11_living_room)
	(roomsconnected room12_living_room room9_empty_room)
	(roomsconnected room13_staricase room1_bathroom)
	(roomsconnected room13_staricase room4_corridor)
	(roomsconnected room13_staricase room5_corridor)
	(roomsconnected room1_bathroom room13_staricase)
	(roomsconnected room1_bathroom room8_empty_room)
	(roomsconnected room2_bathroom room5_corridor)
	(roomsconnected room3_bedroom room7_empty_room)
	(roomsconnected room4_corridor room13_staricase)
	(roomsconnected room4_corridor room7_empty_room)
	(roomsconnected room5_corridor room10_kitchen)
	(roomsconnected room5_corridor room13_staricase)
	(roomsconnected room5_corridor room2_bathroom)
	(roomsconnected room5_corridor room6_dining_room)
	(roomsconnected room5_corridor room9_empty_room)
	(roomsconnected room6_dining_room room5_corridor)
	(roomsconnected room7_empty_room room3_bedroom)
	(roomsconnected room7_empty_room room4_corridor)
	(roomsconnected room8_empty_room room1_bathroom)
	(roomsconnected room9_empty_room room12_living_room)
	(roomsconnected room9_empty_room room5_corridor)
  )
  (:goal (and
	(inreceptacle item46_potted_plant_largeitem receptacle37_chair)))
)
