
(define (problem byerstaskographyv2medium1problem185) (:domain taskographyv2medium1scrub)
  (:objects
        item21_potted_plant_largeitem - item
	location_xneg19_yneg15_place3_room7_floora - location
	location_xneg19_ypos19_place10_room3_floorc - location
	location_xneg23_ypos14_place6_room11_floorb - location
	location_xneg25_yneg5_place55_room14_floorb - location
	location_xneg26_yneg10_place12_room14_floorb - location
	location_xneg42_yneg14_place7_room13_floora - location
	location_xneg4_ypos17_place53_room11_floorb - location
	location_xneg52_ypos13_place8_room4_floorc - location
	location_xneg57_yneg15_place2_room5_floorc - location
	location_xneg57_ypos14_place4_room8_floorb - location
	location_xneg7_yneg8_place11_room1_floora - location
	location_xneg7_ypos12_place53_room11_floorb - location
	location_xpos0_ypos22_place1_room6_floorc - location
	location_xpos16_yneg15_place5_room10_floora - location
	location_xpos17_yneg12_place13_room9_floorc - location
	location_xpos22_ypos20_place9_room2_floorc - location
	location_xpos9_ypos0_place0_room12_floorb - location
	place0_door_room12_living_room - place
	place10_door_room3_bathroom - place
	place11_door_room1_bathroom - place
	place12_door_room14_staircase - place
	place13_door_room9_empty_room - place
	place1_door_room6_closet - place
	place2_door_room5_closet - place
	place3_door_room7_corridor - place
	place4_door_room8_dining_room - place
	place53_receptacle45_sink - place
	place55_receptacle47_refrigerator - place
	place5_door_room10_home_office - place
	place6_door_room11_kitchen - place
	place7_door_room13_staircase - place
	place8_door_room4_bedroom - place
	place9_door_room2_bathroom - place
	receptacle45_sink - receptacle
	receptacle47_refrigerator - receptacle
	robot - agent
	room10_home_office - room
	room11_kitchen - room
	room12_living_room - room
	room13_staircase - room
	room14_staircase - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_closet - room
	room6_closet - room
	room7_corridor - room
	room8_dining_room - room
	room9_empty_room - room
  )
  (:init 
	(atlocation robot location_xneg7_yneg8_place11_room1_floora)
	(inanyreceptacle item21_potted_plant_largeitem)
	(inplace robot place11_door_room1_bathroom)
	(inreceptacle item21_potted_plant_largeitem receptacle45_sink)
	(inroom robot room1_bathroom)
	(itematlocation item21_potted_plant_largeitem location_xneg4_ypos17_place53_room11_floorb)
	(locationinplace location_xneg19_yneg15_place3_room7_floora place3_door_room7_corridor)
	(locationinplace location_xneg19_ypos19_place10_room3_floorc place10_door_room3_bathroom)
	(locationinplace location_xneg23_ypos14_place6_room11_floorb place6_door_room11_kitchen)
	(locationinplace location_xneg25_yneg5_place55_room14_floorb place55_receptacle47_refrigerator)
	(locationinplace location_xneg26_yneg10_place12_room14_floorb place12_door_room14_staircase)
	(locationinplace location_xneg42_yneg14_place7_room13_floora place7_door_room13_staircase)
	(locationinplace location_xneg4_ypos17_place53_room11_floorb place53_receptacle45_sink)
	(locationinplace location_xneg52_ypos13_place8_room4_floorc place8_door_room4_bedroom)
	(locationinplace location_xneg57_yneg15_place2_room5_floorc place2_door_room5_closet)
	(locationinplace location_xneg57_ypos14_place4_room8_floorb place4_door_room8_dining_room)
	(locationinplace location_xneg7_yneg8_place11_room1_floora place11_door_room1_bathroom)
	(locationinplace location_xneg7_ypos12_place53_room11_floorb place53_receptacle45_sink)
	(locationinplace location_xpos0_ypos22_place1_room6_floorc place1_door_room6_closet)
	(locationinplace location_xpos16_yneg15_place5_room10_floora place5_door_room10_home_office)
	(locationinplace location_xpos17_yneg12_place13_room9_floorc place13_door_room9_empty_room)
	(locationinplace location_xpos22_ypos20_place9_room2_floorc place9_door_room2_bathroom)
	(locationinplace location_xpos9_ypos0_place0_room12_floorb place0_door_room12_living_room)
	(placeinroom place0_door_room12_living_room room12_living_room)
	(placeinroom place10_door_room3_bathroom room3_bathroom)
	(placeinroom place11_door_room1_bathroom room1_bathroom)
	(placeinroom place12_door_room14_staircase room14_staircase)
	(placeinroom place13_door_room9_empty_room room9_empty_room)
	(placeinroom place1_door_room6_closet room6_closet)
	(placeinroom place2_door_room5_closet room5_closet)
	(placeinroom place3_door_room7_corridor room7_corridor)
	(placeinroom place4_door_room8_dining_room room8_dining_room)
	(placeinroom place53_receptacle45_sink room11_kitchen)
	(placeinroom place55_receptacle47_refrigerator room14_staircase)
	(placeinroom place5_door_room10_home_office room10_home_office)
	(placeinroom place6_door_room11_kitchen room11_kitchen)
	(placeinroom place7_door_room13_staircase room13_staircase)
	(placeinroom place8_door_room4_bedroom room4_bedroom)
	(placeinroom place9_door_room2_bathroom room2_bathroom)
	(placelocation location_xneg19_yneg15_place3_room7_floora place3_door_room7_corridor)
	(placelocation location_xneg19_ypos19_place10_room3_floorc place10_door_room3_bathroom)
	(placelocation location_xneg23_ypos14_place6_room11_floorb place6_door_room11_kitchen)
	(placelocation location_xneg25_yneg5_place55_room14_floorb place55_receptacle47_refrigerator)
	(placelocation location_xneg26_yneg10_place12_room14_floorb place12_door_room14_staircase)
	(placelocation location_xneg42_yneg14_place7_room13_floora place7_door_room13_staircase)
	(placelocation location_xneg52_ypos13_place8_room4_floorc place8_door_room4_bedroom)
	(placelocation location_xneg57_yneg15_place2_room5_floorc place2_door_room5_closet)
	(placelocation location_xneg57_ypos14_place4_room8_floorb place4_door_room8_dining_room)
	(placelocation location_xneg7_yneg8_place11_room1_floora place11_door_room1_bathroom)
	(placelocation location_xneg7_ypos12_place53_room11_floorb place53_receptacle45_sink)
	(placelocation location_xpos0_ypos22_place1_room6_floorc place1_door_room6_closet)
	(placelocation location_xpos16_yneg15_place5_room10_floora place5_door_room10_home_office)
	(placelocation location_xpos17_yneg12_place13_room9_floorc place13_door_room9_empty_room)
	(placelocation location_xpos22_ypos20_place9_room2_floorc place9_door_room2_bathroom)
	(placelocation location_xpos9_ypos0_place0_room12_floorb place0_door_room12_living_room)
	(receptacleatlocation receptacle45_sink location_xneg7_ypos12_place53_room11_floorb)
	(receptacleatlocation receptacle47_refrigerator location_xneg25_yneg5_place55_room14_floorb)
	(receptacleopeningtype receptacle47_refrigerator)
	(roomplace place0_door_room12_living_room room12_living_room)
	(roomplace place10_door_room3_bathroom room3_bathroom)
	(roomplace place11_door_room1_bathroom room1_bathroom)
	(roomplace place12_door_room14_staircase room14_staircase)
	(roomplace place13_door_room9_empty_room room9_empty_room)
	(roomplace place1_door_room6_closet room6_closet)
	(roomplace place2_door_room5_closet room5_closet)
	(roomplace place3_door_room7_corridor room7_corridor)
	(roomplace place4_door_room8_dining_room room8_dining_room)
	(roomplace place5_door_room10_home_office room10_home_office)
	(roomplace place6_door_room11_kitchen room11_kitchen)
	(roomplace place7_door_room13_staircase room13_staircase)
	(roomplace place8_door_room4_bedroom room4_bedroom)
	(roomplace place9_door_room2_bathroom room2_bathroom)
	(roomsconnected room10_home_office room1_bathroom)
	(roomsconnected room11_kitchen room12_living_room)
	(roomsconnected room11_kitchen room14_staircase)
	(roomsconnected room11_kitchen room8_dining_room)
	(roomsconnected room12_living_room room11_kitchen)
	(roomsconnected room13_staircase room14_staircase)
	(roomsconnected room13_staircase room7_corridor)
	(roomsconnected room14_staircase room11_kitchen)
	(roomsconnected room14_staircase room13_staircase)
	(roomsconnected room1_bathroom room10_home_office)
	(roomsconnected room1_bathroom room7_corridor)
	(roomsconnected room2_bathroom room6_closet)
	(roomsconnected room2_bathroom room9_empty_room)
	(roomsconnected room3_bathroom room4_bedroom)
	(roomsconnected room3_bathroom room6_closet)
	(roomsconnected room4_bedroom room3_bathroom)
	(roomsconnected room4_bedroom room5_closet)
	(roomsconnected room4_bedroom room8_dining_room)
	(roomsconnected room5_closet room4_bedroom)
	(roomsconnected room6_closet room2_bathroom)
	(roomsconnected room6_closet room3_bathroom)
	(roomsconnected room7_corridor room13_staircase)
	(roomsconnected room7_corridor room1_bathroom)
	(roomsconnected room8_dining_room room11_kitchen)
	(roomsconnected room8_dining_room room4_bedroom)
	(roomsconnected room9_empty_room room2_bathroom)
  )
  (:goal (and
	(inreceptacle item21_potted_plant_largeitem receptacle47_refrigerator)))
)
