
(define (problem sussextaskographyv2medium1problem171) (:domain taskographyv2medium1scrub)
  (:objects
        item48_potted_plant_largeitem - item
	location_xneg11_ypos54_place13_room7_floora - location
	location_xneg11_ypos55_place14_room8_floora - location
	location_xneg25_yneg2_place2_room13_floorb - location
	location_xneg2_ypos89_place12_room16_floorb - location
	location_xneg31_yneg4_place5_room6_floora - location
	location_xneg32_ypos71_place10_room15_floorb - location
	location_xneg37_ypos103_place15_room10_floora - location
	location_xneg37_ypos22_place8_room4_floora - location
	location_xneg37_ypos68_place4_room1_floora - location
	location_xneg41_ypos25_place11_room9_floorb - location
	location_xneg48_ypos46_place59_room4_floora - location
	location_xpos0_ypos13_place9_room17_floorb - location
	location_xpos1_yneg13_place33_room13_floorb - location
	location_xpos1_ypos97_place7_room14_floora - location
	location_xpos2_ypos6_place1_room5_floora - location
	location_xpos4_ypos34_place6_room12_floorb - location
	location_xpos8_ypos38_place16_room11_floora - location
	location_xpos8_ypos59_place3_room2_floora - location
	location_xpos8_ypos89_place17_room18_floora - location
	location_xpos9_ypos60_place0_room3_floorb - location
	place0_door_room3_bathroom - place
	place10_door_room15_living_room - place
	place11_door_room9_dining_room - place
	place12_door_room16_lobby - place
	place13_door_room7_corridor - place
	place14_door_room8_corridor - place
	place15_door_room10_empty_room - place
	place16_door_room11_empty_room - place
	place17_door_room18_staircase - place
	place1_door_room5_bedroom - place
	place2_door_room13_kitchen - place
	place33_item48_potted_plant - place
	place3_door_room2_bathroom - place
	place4_door_room1_bathroom - place
	place59_receptacle47_couch - place
	place5_door_room6_closet - place
	place6_door_room12_home_office - place
	place7_door_room14_living_room - place
	place8_door_room4_bedroom - place
	place9_door_room17_pantry - place
	receptacle47_couch - receptacle
	robot - agent
	room10_empty_room - room
	room11_empty_room - room
	room12_home_office - room
	room13_kitchen - room
	room14_living_room - room
	room15_living_room - room
	room16_lobby - room
	room17_pantry - room
	room18_staircase - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_closet - room
	room7_corridor - room
	room8_corridor - room
	room9_dining_room - room
  )
  (:init 
	(atlocation robot location_xpos1_ypos97_place7_room14_floora)
	(inplace robot place7_door_room14_living_room)
	(inroom robot room14_living_room)
	(itematlocation item48_potted_plant_largeitem location_xpos1_yneg13_place33_room13_floorb)
	(locationinplace location_xneg11_ypos54_place13_room7_floora place13_door_room7_corridor)
	(locationinplace location_xneg11_ypos55_place14_room8_floora place14_door_room8_corridor)
	(locationinplace location_xneg25_yneg2_place2_room13_floorb place2_door_room13_kitchen)
	(locationinplace location_xneg2_ypos89_place12_room16_floorb place12_door_room16_lobby)
	(locationinplace location_xneg31_yneg4_place5_room6_floora place5_door_room6_closet)
	(locationinplace location_xneg32_ypos71_place10_room15_floorb place10_door_room15_living_room)
	(locationinplace location_xneg37_ypos103_place15_room10_floora place15_door_room10_empty_room)
	(locationinplace location_xneg37_ypos22_place8_room4_floora place8_door_room4_bedroom)
	(locationinplace location_xneg37_ypos68_place4_room1_floora place4_door_room1_bathroom)
	(locationinplace location_xneg41_ypos25_place11_room9_floorb place11_door_room9_dining_room)
	(locationinplace location_xneg48_ypos46_place59_room4_floora place59_receptacle47_couch)
	(locationinplace location_xpos0_ypos13_place9_room17_floorb place9_door_room17_pantry)
	(locationinplace location_xpos1_yneg13_place33_room13_floorb place33_item48_potted_plant)
	(locationinplace location_xpos1_ypos97_place7_room14_floora place7_door_room14_living_room)
	(locationinplace location_xpos2_ypos6_place1_room5_floora place1_door_room5_bedroom)
	(locationinplace location_xpos4_ypos34_place6_room12_floorb place6_door_room12_home_office)
	(locationinplace location_xpos8_ypos38_place16_room11_floora place16_door_room11_empty_room)
	(locationinplace location_xpos8_ypos59_place3_room2_floora place3_door_room2_bathroom)
	(locationinplace location_xpos8_ypos89_place17_room18_floora place17_door_room18_staircase)
	(locationinplace location_xpos9_ypos60_place0_room3_floorb place0_door_room3_bathroom)
	(placeinroom place0_door_room3_bathroom room3_bathroom)
	(placeinroom place10_door_room15_living_room room15_living_room)
	(placeinroom place11_door_room9_dining_room room9_dining_room)
	(placeinroom place12_door_room16_lobby room16_lobby)
	(placeinroom place13_door_room7_corridor room7_corridor)
	(placeinroom place14_door_room8_corridor room8_corridor)
	(placeinroom place15_door_room10_empty_room room10_empty_room)
	(placeinroom place16_door_room11_empty_room room11_empty_room)
	(placeinroom place17_door_room18_staircase room18_staircase)
	(placeinroom place1_door_room5_bedroom room5_bedroom)
	(placeinroom place2_door_room13_kitchen room13_kitchen)
	(placeinroom place33_item48_potted_plant room13_kitchen)
	(placeinroom place3_door_room2_bathroom room2_bathroom)
	(placeinroom place4_door_room1_bathroom room1_bathroom)
	(placeinroom place59_receptacle47_couch room4_bedroom)
	(placeinroom place5_door_room6_closet room6_closet)
	(placeinroom place6_door_room12_home_office room12_home_office)
	(placeinroom place7_door_room14_living_room room14_living_room)
	(placeinroom place8_door_room4_bedroom room4_bedroom)
	(placeinroom place9_door_room17_pantry room17_pantry)
	(placelocation location_xneg11_ypos54_place13_room7_floora place13_door_room7_corridor)
	(placelocation location_xneg11_ypos55_place14_room8_floora place14_door_room8_corridor)
	(placelocation location_xneg25_yneg2_place2_room13_floorb place2_door_room13_kitchen)
	(placelocation location_xneg2_ypos89_place12_room16_floorb place12_door_room16_lobby)
	(placelocation location_xneg31_yneg4_place5_room6_floora place5_door_room6_closet)
	(placelocation location_xneg32_ypos71_place10_room15_floorb place10_door_room15_living_room)
	(placelocation location_xneg37_ypos103_place15_room10_floora place15_door_room10_empty_room)
	(placelocation location_xneg37_ypos22_place8_room4_floora place8_door_room4_bedroom)
	(placelocation location_xneg37_ypos68_place4_room1_floora place4_door_room1_bathroom)
	(placelocation location_xneg41_ypos25_place11_room9_floorb place11_door_room9_dining_room)
	(placelocation location_xneg48_ypos46_place59_room4_floora place59_receptacle47_couch)
	(placelocation location_xpos0_ypos13_place9_room17_floorb place9_door_room17_pantry)
	(placelocation location_xpos1_yneg13_place33_room13_floorb place33_item48_potted_plant)
	(placelocation location_xpos1_ypos97_place7_room14_floora place7_door_room14_living_room)
	(placelocation location_xpos2_ypos6_place1_room5_floora place1_door_room5_bedroom)
	(placelocation location_xpos4_ypos34_place6_room12_floorb place6_door_room12_home_office)
	(placelocation location_xpos8_ypos38_place16_room11_floora place16_door_room11_empty_room)
	(placelocation location_xpos8_ypos59_place3_room2_floora place3_door_room2_bathroom)
	(placelocation location_xpos8_ypos89_place17_room18_floora place17_door_room18_staircase)
	(placelocation location_xpos9_ypos60_place0_room3_floorb place0_door_room3_bathroom)
	(receptacleatlocation receptacle47_couch location_xneg48_ypos46_place59_room4_floora)
	(roomplace place0_door_room3_bathroom room3_bathroom)
	(roomplace place10_door_room15_living_room room15_living_room)
	(roomplace place11_door_room9_dining_room room9_dining_room)
	(roomplace place12_door_room16_lobby room16_lobby)
	(roomplace place13_door_room7_corridor room7_corridor)
	(roomplace place14_door_room8_corridor room8_corridor)
	(roomplace place15_door_room10_empty_room room10_empty_room)
	(roomplace place16_door_room11_empty_room room11_empty_room)
	(roomplace place17_door_room18_staircase room18_staircase)
	(roomplace place1_door_room5_bedroom room5_bedroom)
	(roomplace place2_door_room13_kitchen room13_kitchen)
	(roomplace place3_door_room2_bathroom room2_bathroom)
	(roomplace place4_door_room1_bathroom room1_bathroom)
	(roomplace place5_door_room6_closet room6_closet)
	(roomplace place6_door_room12_home_office room12_home_office)
	(roomplace place7_door_room14_living_room room14_living_room)
	(roomplace place8_door_room4_bedroom room4_bedroom)
	(roomplace place9_door_room17_pantry room17_pantry)
	(roomsconnected room10_empty_room room1_bathroom)
	(roomsconnected room11_empty_room room2_bathroom)
	(roomsconnected room11_empty_room room5_bedroom)
	(roomsconnected room12_home_office room17_pantry)
	(roomsconnected room12_home_office room3_bathroom)
	(roomsconnected room13_kitchen room17_pantry)
	(roomsconnected room13_kitchen room9_dining_room)
	(roomsconnected room14_living_room room18_staircase)
	(roomsconnected room15_living_room room16_lobby)
	(roomsconnected room16_lobby room15_living_room)
	(roomsconnected room16_lobby room18_staircase)
	(roomsconnected room16_lobby room3_bathroom)
	(roomsconnected room17_pantry room12_home_office)
	(roomsconnected room17_pantry room13_kitchen)
	(roomsconnected room18_staircase room14_living_room)
	(roomsconnected room18_staircase room16_lobby)
	(roomsconnected room18_staircase room2_bathroom)
	(roomsconnected room1_bathroom room10_empty_room)
	(roomsconnected room1_bathroom room7_corridor)
	(roomsconnected room2_bathroom room11_empty_room)
	(roomsconnected room2_bathroom room18_staircase)
	(roomsconnected room2_bathroom room7_corridor)
	(roomsconnected room3_bathroom room12_home_office)
	(roomsconnected room3_bathroom room16_lobby)
	(roomsconnected room4_bedroom room6_closet)
	(roomsconnected room5_bedroom room11_empty_room)
	(roomsconnected room5_bedroom room6_closet)
	(roomsconnected room6_closet room4_bedroom)
	(roomsconnected room6_closet room5_bedroom)
	(roomsconnected room7_corridor room1_bathroom)
	(roomsconnected room7_corridor room2_bathroom)
	(roomsconnected room7_corridor room8_corridor)
	(roomsconnected room8_corridor room7_corridor)
	(roomsconnected room9_dining_room room13_kitchen)
  )
  (:goal (and
	(inreceptacle item48_potted_plant_largeitem receptacle47_couch)))
)
