
(define (problem hordvilletaskographyv2medium1problem52) (:domain taskographyv2medium1scrub)
  (:objects
        item6_cup_smallitem - item
	location_xneg21_yneg3_place15_room11_floorc - location
	location_xneg24_yneg39_place6_room12_floorb - location
	location_xneg25_yneg37_place10_room3_floorc - location
	location_xneg32_ypos2_place12_room17_floorb - location
	location_xneg32_ypos2_place16_room16_floora - location
	location_xneg36_yneg10_place5_room10_floorb - location
	location_xneg38_yneg5_place14_room9_floora - location
	location_xneg54_yneg2_place0_room8_floorc - location
	location_xneg58_yneg27_place9_room5_floorc - location
	location_xneg5_yneg3_place11_room15_floora - location
	location_xneg60_yneg31_place7_room14_floorb - location
	location_xneg61_yneg32_place4_room4_floora - location
	location_xneg68_yneg14_place51_room4_floora - location
	location_xneg68_yneg2_place3_room1_floora - location
	location_xneg72_yneg12_place51_room4_floora - location
	location_xpos0_yneg1_place1_room2_floorb - location
	location_xpos0_yneg3_place13_room7_floorc - location
	location_xpos17_yneg22_place64_room13_floorb - location
	location_xpos2_yneg33_place8_room6_floorc - location
	location_xpos6_yneg33_place2_room13_floorb - location
	place0_door_room8_closet - place
	place10_door_room3_bathroom - place
	place11_door_room15_lobby - place
	place12_door_room17_staircase - place
	place13_door_room7_closet - place
	place14_door_room9_corridor - place
	place15_door_room11_corridor - place
	place16_door_room16_staircase - place
	place1_door_room2_bathroom - place
	place2_door_room13_kitchen - place
	place3_door_room1_bathroom - place
	place4_door_room4_bedroom - place
	place51_receptacle40_dining_table - place
	place5_door_room10_corridor - place
	place64_receptacle54_refrigerator - place
	place6_door_room12_dining_room - place
	place7_door_room14_living_room - place
	place8_door_room6_childs_room - place
	place9_door_room5_bedroom - place
	receptacle40_dining_table - receptacle
	receptacle54_refrigerator - receptacle
	robot - agent
	room10_corridor - room
	room11_corridor - room
	room12_dining_room - room
	room13_kitchen - room
	room14_living_room - room
	room15_lobby - room
	room16_staircase - room
	room17_staircase - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_childs_room - room
	room7_closet - room
	room8_closet - room
	room9_corridor - room
  )
  (:init 
	(atlocation robot location_xneg61_yneg32_place4_room4_floora)
	(inanyreceptacle item6_cup_smallitem)
	(inplace robot place4_door_room4_bedroom)
	(inreceptacle item6_cup_smallitem receptacle40_dining_table)
	(inroom robot room4_bedroom)
	(itematlocation item6_cup_smallitem location_xneg72_yneg12_place51_room4_floora)
	(locationinplace location_xneg21_yneg3_place15_room11_floorc place15_door_room11_corridor)
	(locationinplace location_xneg24_yneg39_place6_room12_floorb place6_door_room12_dining_room)
	(locationinplace location_xneg25_yneg37_place10_room3_floorc place10_door_room3_bathroom)
	(locationinplace location_xneg32_ypos2_place12_room17_floorb place12_door_room17_staircase)
	(locationinplace location_xneg32_ypos2_place16_room16_floora place16_door_room16_staircase)
	(locationinplace location_xneg36_yneg10_place5_room10_floorb place5_door_room10_corridor)
	(locationinplace location_xneg38_yneg5_place14_room9_floora place14_door_room9_corridor)
	(locationinplace location_xneg54_yneg2_place0_room8_floorc place0_door_room8_closet)
	(locationinplace location_xneg58_yneg27_place9_room5_floorc place9_door_room5_bedroom)
	(locationinplace location_xneg5_yneg3_place11_room15_floora place11_door_room15_lobby)
	(locationinplace location_xneg60_yneg31_place7_room14_floorb place7_door_room14_living_room)
	(locationinplace location_xneg61_yneg32_place4_room4_floora place4_door_room4_bedroom)
	(locationinplace location_xneg68_yneg14_place51_room4_floora place51_receptacle40_dining_table)
	(locationinplace location_xneg68_yneg2_place3_room1_floora place3_door_room1_bathroom)
	(locationinplace location_xneg72_yneg12_place51_room4_floora place51_receptacle40_dining_table)
	(locationinplace location_xpos0_yneg1_place1_room2_floorb place1_door_room2_bathroom)
	(locationinplace location_xpos0_yneg3_place13_room7_floorc place13_door_room7_closet)
	(locationinplace location_xpos17_yneg22_place64_room13_floorb place64_receptacle54_refrigerator)
	(locationinplace location_xpos2_yneg33_place8_room6_floorc place8_door_room6_childs_room)
	(locationinplace location_xpos6_yneg33_place2_room13_floorb place2_door_room13_kitchen)
	(placeinroom place0_door_room8_closet room8_closet)
	(placeinroom place10_door_room3_bathroom room3_bathroom)
	(placeinroom place11_door_room15_lobby room15_lobby)
	(placeinroom place12_door_room17_staircase room17_staircase)
	(placeinroom place13_door_room7_closet room7_closet)
	(placeinroom place14_door_room9_corridor room9_corridor)
	(placeinroom place15_door_room11_corridor room11_corridor)
	(placeinroom place16_door_room16_staircase room16_staircase)
	(placeinroom place1_door_room2_bathroom room2_bathroom)
	(placeinroom place2_door_room13_kitchen room13_kitchen)
	(placeinroom place3_door_room1_bathroom room1_bathroom)
	(placeinroom place4_door_room4_bedroom room4_bedroom)
	(placeinroom place51_receptacle40_dining_table room4_bedroom)
	(placeinroom place5_door_room10_corridor room10_corridor)
	(placeinroom place64_receptacle54_refrigerator room13_kitchen)
	(placeinroom place6_door_room12_dining_room room12_dining_room)
	(placeinroom place7_door_room14_living_room room14_living_room)
	(placeinroom place8_door_room6_childs_room room6_childs_room)
	(placeinroom place9_door_room5_bedroom room5_bedroom)
	(placelocation location_xneg21_yneg3_place15_room11_floorc place15_door_room11_corridor)
	(placelocation location_xneg24_yneg39_place6_room12_floorb place6_door_room12_dining_room)
	(placelocation location_xneg25_yneg37_place10_room3_floorc place10_door_room3_bathroom)
	(placelocation location_xneg32_ypos2_place12_room17_floorb place12_door_room17_staircase)
	(placelocation location_xneg32_ypos2_place16_room16_floora place16_door_room16_staircase)
	(placelocation location_xneg36_yneg10_place5_room10_floorb place5_door_room10_corridor)
	(placelocation location_xneg38_yneg5_place14_room9_floora place14_door_room9_corridor)
	(placelocation location_xneg54_yneg2_place0_room8_floorc place0_door_room8_closet)
	(placelocation location_xneg58_yneg27_place9_room5_floorc place9_door_room5_bedroom)
	(placelocation location_xneg5_yneg3_place11_room15_floora place11_door_room15_lobby)
	(placelocation location_xneg60_yneg31_place7_room14_floorb place7_door_room14_living_room)
	(placelocation location_xneg61_yneg32_place4_room4_floora place4_door_room4_bedroom)
	(placelocation location_xneg68_yneg14_place51_room4_floora place51_receptacle40_dining_table)
	(placelocation location_xneg68_yneg2_place3_room1_floora place3_door_room1_bathroom)
	(placelocation location_xpos0_yneg1_place1_room2_floorb place1_door_room2_bathroom)
	(placelocation location_xpos0_yneg3_place13_room7_floorc place13_door_room7_closet)
	(placelocation location_xpos17_yneg22_place64_room13_floorb place64_receptacle54_refrigerator)
	(placelocation location_xpos2_yneg33_place8_room6_floorc place8_door_room6_childs_room)
	(placelocation location_xpos6_yneg33_place2_room13_floorb place2_door_room13_kitchen)
	(receptacleatlocation receptacle40_dining_table location_xneg68_yneg14_place51_room4_floora)
	(receptacleatlocation receptacle54_refrigerator location_xpos17_yneg22_place64_room13_floorb)
	(receptacleopeningtype receptacle54_refrigerator)
	(roomplace place0_door_room8_closet room8_closet)
	(roomplace place10_door_room3_bathroom room3_bathroom)
	(roomplace place11_door_room15_lobby room15_lobby)
	(roomplace place12_door_room17_staircase room17_staircase)
	(roomplace place13_door_room7_closet room7_closet)
	(roomplace place14_door_room9_corridor room9_corridor)
	(roomplace place15_door_room11_corridor room11_corridor)
	(roomplace place16_door_room16_staircase room16_staircase)
	(roomplace place1_door_room2_bathroom room2_bathroom)
	(roomplace place2_door_room13_kitchen room13_kitchen)
	(roomplace place3_door_room1_bathroom room1_bathroom)
	(roomplace place4_door_room4_bedroom room4_bedroom)
	(roomplace place5_door_room10_corridor room10_corridor)
	(roomplace place6_door_room12_dining_room room12_dining_room)
	(roomplace place7_door_room14_living_room room14_living_room)
	(roomplace place8_door_room6_childs_room room6_childs_room)
	(roomplace place9_door_room5_bedroom room5_bedroom)
	(roomsconnected room10_corridor room12_dining_room)
	(roomsconnected room10_corridor room14_living_room)
	(roomsconnected room10_corridor room16_staircase)
	(roomsconnected room10_corridor room17_staircase)
	(roomsconnected room11_corridor room17_staircase)
	(roomsconnected room11_corridor room7_closet)
	(roomsconnected room11_corridor room8_closet)
	(roomsconnected room12_dining_room room10_corridor)
	(roomsconnected room12_dining_room room13_kitchen)
	(roomsconnected room13_kitchen room12_dining_room)
	(roomsconnected room13_kitchen room2_bathroom)
	(roomsconnected room14_living_room room10_corridor)
	(roomsconnected room15_lobby room16_staircase)
	(roomsconnected room16_staircase room10_corridor)
	(roomsconnected room16_staircase room15_lobby)
	(roomsconnected room16_staircase room9_corridor)
	(roomsconnected room17_staircase room10_corridor)
	(roomsconnected room17_staircase room11_corridor)
	(roomsconnected room1_bathroom room4_bedroom)
	(roomsconnected room1_bathroom room9_corridor)
	(roomsconnected room2_bathroom room13_kitchen)
	(roomsconnected room3_bathroom room6_childs_room)
	(roomsconnected room4_bedroom room1_bathroom)
	(roomsconnected room5_bedroom room8_closet)
	(roomsconnected room6_childs_room room3_bathroom)
	(roomsconnected room6_childs_room room7_closet)
	(roomsconnected room7_closet room11_corridor)
	(roomsconnected room7_closet room6_childs_room)
	(roomsconnected room8_closet room11_corridor)
	(roomsconnected room8_closet room5_bedroom)
	(roomsconnected room9_corridor room16_staircase)
	(roomsconnected room9_corridor room1_bathroom)
  )
  (:goal (and
	(inreceptacle item6_cup_smallitem receptacle54_refrigerator)))
)
