
(define (problem chilhowietaskographyv2medium1problem112) (:domain taskographyv2medium1scrub)
  (:objects
        item52_vase_mediumitem - item
	location_xneg10_ypos30_place10_room15_floora - location
	location_xneg16_ypos0_place4_room14_floora - location
	location_xneg19_ypos93_place0_room5_floorb - location
	location_xneg26_ypos45_place7_room4_floorb - location
	location_xneg33_ypos85_place1_room2_floorb - location
	location_xneg47_ypos64_place54_room3_floorb - location
	location_xneg50_ypos15_place14_room6_floora - location
	location_xneg51_ypos72_place12_room3_floorb - location
	location_xneg54_ypos39_place11_room1_floora - location
	location_xneg54_ypos8_place2_room16_floora - location
	location_xneg55_ypos99_place39_room13_floora - location
	location_xneg60_ypos46_place15_room7_floorb - location
	location_xneg62_yneg21_place5_room8_floora - location
	location_xneg69_ypos101_place39_room13_floora - location
	location_xneg73_ypos75_place9_room13_floora - location
	location_xneg80_ypos86_place8_room11_floorb - location
	location_xneg84_ypos42_place6_room10_floora - location
	location_xneg86_ypos39_place3_room9_floorb - location
	location_xneg89_ypos14_place13_room12_floora - location
	place0_door_room5_closet - place
	place10_door_room15_lobby - place
	place11_door_room1_bathroom - place
	place12_door_room3_bathroom - place
	place13_door_room12_kitchen - place
	place14_door_room6_corridor - place
	place15_door_room7_corridor - place
	place1_door_room2_bathroom - place
	place2_door_room16_staircase - place
	place39_receptacle24_couch - place
	place3_door_room9_empty_room - place
	place4_door_room14_living_room - place
	place54_receptacle46_sink - place
	place5_door_room8_dining_room - place
	place6_door_room10_home_office - place
	place7_door_room4_bedroom - place
	place8_door_room11_home_office - place
	place9_door_room13_living_room - place
	receptacle24_couch - receptacle
	receptacle46_sink - receptacle
	robot - agent
	room10_home_office - room
	room11_home_office - room
	room12_kitchen - room
	room13_living_room - room
	room14_living_room - room
	room15_lobby - room
	room16_staircase - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_closet - room
	room6_corridor - room
	room7_corridor - room
	room8_dining_room - room
	room9_empty_room - room
  )
  (:init 
	(atlocation robot location_xneg26_ypos45_place7_room4_floorb)
	(inanyreceptacle item52_vase_mediumitem)
	(inplace robot place7_door_room4_bedroom)
	(inreceptacle item52_vase_mediumitem receptacle24_couch)
	(inroom robot room4_bedroom)
	(itematlocation item52_vase_mediumitem location_xneg69_ypos101_place39_room13_floora)
	(locationinplace location_xneg10_ypos30_place10_room15_floora place10_door_room15_lobby)
	(locationinplace location_xneg16_ypos0_place4_room14_floora place4_door_room14_living_room)
	(locationinplace location_xneg19_ypos93_place0_room5_floorb place0_door_room5_closet)
	(locationinplace location_xneg26_ypos45_place7_room4_floorb place7_door_room4_bedroom)
	(locationinplace location_xneg33_ypos85_place1_room2_floorb place1_door_room2_bathroom)
	(locationinplace location_xneg47_ypos64_place54_room3_floorb place54_receptacle46_sink)
	(locationinplace location_xneg50_ypos15_place14_room6_floora place14_door_room6_corridor)
	(locationinplace location_xneg51_ypos72_place12_room3_floorb place12_door_room3_bathroom)
	(locationinplace location_xneg54_ypos39_place11_room1_floora place11_door_room1_bathroom)
	(locationinplace location_xneg54_ypos8_place2_room16_floora place2_door_room16_staircase)
	(locationinplace location_xneg55_ypos99_place39_room13_floora place39_receptacle24_couch)
	(locationinplace location_xneg60_ypos46_place15_room7_floorb place15_door_room7_corridor)
	(locationinplace location_xneg62_yneg21_place5_room8_floora place5_door_room8_dining_room)
	(locationinplace location_xneg69_ypos101_place39_room13_floora place39_receptacle24_couch)
	(locationinplace location_xneg73_ypos75_place9_room13_floora place9_door_room13_living_room)
	(locationinplace location_xneg80_ypos86_place8_room11_floorb place8_door_room11_home_office)
	(locationinplace location_xneg84_ypos42_place6_room10_floora place6_door_room10_home_office)
	(locationinplace location_xneg86_ypos39_place3_room9_floorb place3_door_room9_empty_room)
	(locationinplace location_xneg89_ypos14_place13_room12_floora place13_door_room12_kitchen)
	(placeinroom place0_door_room5_closet room5_closet)
	(placeinroom place10_door_room15_lobby room15_lobby)
	(placeinroom place11_door_room1_bathroom room1_bathroom)
	(placeinroom place12_door_room3_bathroom room3_bathroom)
	(placeinroom place13_door_room12_kitchen room12_kitchen)
	(placeinroom place14_door_room6_corridor room6_corridor)
	(placeinroom place15_door_room7_corridor room7_corridor)
	(placeinroom place1_door_room2_bathroom room2_bathroom)
	(placeinroom place2_door_room16_staircase room16_staircase)
	(placeinroom place39_receptacle24_couch room13_living_room)
	(placeinroom place3_door_room9_empty_room room9_empty_room)
	(placeinroom place4_door_room14_living_room room14_living_room)
	(placeinroom place54_receptacle46_sink room3_bathroom)
	(placeinroom place5_door_room8_dining_room room8_dining_room)
	(placeinroom place6_door_room10_home_office room10_home_office)
	(placeinroom place7_door_room4_bedroom room4_bedroom)
	(placeinroom place8_door_room11_home_office room11_home_office)
	(placeinroom place9_door_room13_living_room room13_living_room)
	(placelocation location_xneg10_ypos30_place10_room15_floora place10_door_room15_lobby)
	(placelocation location_xneg16_ypos0_place4_room14_floora place4_door_room14_living_room)
	(placelocation location_xneg19_ypos93_place0_room5_floorb place0_door_room5_closet)
	(placelocation location_xneg26_ypos45_place7_room4_floorb place7_door_room4_bedroom)
	(placelocation location_xneg33_ypos85_place1_room2_floorb place1_door_room2_bathroom)
	(placelocation location_xneg47_ypos64_place54_room3_floorb place54_receptacle46_sink)
	(placelocation location_xneg50_ypos15_place14_room6_floora place14_door_room6_corridor)
	(placelocation location_xneg51_ypos72_place12_room3_floorb place12_door_room3_bathroom)
	(placelocation location_xneg54_ypos39_place11_room1_floora place11_door_room1_bathroom)
	(placelocation location_xneg54_ypos8_place2_room16_floora place2_door_room16_staircase)
	(placelocation location_xneg55_ypos99_place39_room13_floora place39_receptacle24_couch)
	(placelocation location_xneg60_ypos46_place15_room7_floorb place15_door_room7_corridor)
	(placelocation location_xneg62_yneg21_place5_room8_floora place5_door_room8_dining_room)
	(placelocation location_xneg73_ypos75_place9_room13_floora place9_door_room13_living_room)
	(placelocation location_xneg80_ypos86_place8_room11_floorb place8_door_room11_home_office)
	(placelocation location_xneg84_ypos42_place6_room10_floora place6_door_room10_home_office)
	(placelocation location_xneg86_ypos39_place3_room9_floorb place3_door_room9_empty_room)
	(placelocation location_xneg89_ypos14_place13_room12_floora place13_door_room12_kitchen)
	(receptacleatlocation receptacle24_couch location_xneg55_ypos99_place39_room13_floora)
	(receptacleatlocation receptacle46_sink location_xneg47_ypos64_place54_room3_floorb)
	(roomplace place0_door_room5_closet room5_closet)
	(roomplace place10_door_room15_lobby room15_lobby)
	(roomplace place11_door_room1_bathroom room1_bathroom)
	(roomplace place12_door_room3_bathroom room3_bathroom)
	(roomplace place13_door_room12_kitchen room12_kitchen)
	(roomplace place14_door_room6_corridor room6_corridor)
	(roomplace place15_door_room7_corridor room7_corridor)
	(roomplace place1_door_room2_bathroom room2_bathroom)
	(roomplace place2_door_room16_staircase room16_staircase)
	(roomplace place3_door_room9_empty_room room9_empty_room)
	(roomplace place4_door_room14_living_room room14_living_room)
	(roomplace place5_door_room8_dining_room room8_dining_room)
	(roomplace place6_door_room10_home_office room10_home_office)
	(roomplace place7_door_room4_bedroom room4_bedroom)
	(roomplace place8_door_room11_home_office room11_home_office)
	(roomplace place9_door_room13_living_room room13_living_room)
	(roomsconnected room10_home_office room12_kitchen)
	(roomsconnected room10_home_office room13_living_room)
	(roomsconnected room10_home_office room1_bathroom)
	(roomsconnected room10_home_office room9_empty_room)
	(roomsconnected room11_home_office room3_bathroom)
	(roomsconnected room12_kitchen room10_home_office)
	(roomsconnected room13_living_room room10_home_office)
	(roomsconnected room14_living_room room15_lobby)
	(roomsconnected room14_living_room room16_staircase)
	(roomsconnected room15_lobby room14_living_room)
	(roomsconnected room16_staircase room14_living_room)
	(roomsconnected room16_staircase room6_corridor)
	(roomsconnected room16_staircase room8_dining_room)
	(roomsconnected room1_bathroom room10_home_office)
	(roomsconnected room1_bathroom room6_corridor)
	(roomsconnected room2_bathroom room3_bathroom)
	(roomsconnected room2_bathroom room5_closet)
	(roomsconnected room3_bathroom room11_home_office)
	(roomsconnected room3_bathroom room2_bathroom)
	(roomsconnected room3_bathroom room7_corridor)
	(roomsconnected room4_bedroom room7_corridor)
	(roomsconnected room5_closet room2_bathroom)
	(roomsconnected room6_corridor room16_staircase)
	(roomsconnected room6_corridor room1_bathroom)
	(roomsconnected room7_corridor room3_bathroom)
	(roomsconnected room7_corridor room4_bedroom)
	(roomsconnected room7_corridor room9_empty_room)
	(roomsconnected room8_dining_room room16_staircase)
	(roomsconnected room9_empty_room room10_home_office)
	(roomsconnected room9_empty_room room7_corridor)
  )
  (:goal (and
	(inreceptacle item52_vase_mediumitem receptacle46_sink)))
)
