
(define (problem frankforttaskographyv2medium1problem202) (:domain taskographyv2medium1scrub)
  (:objects
        item53_book_smallitem - item
	location_xneg16_ypos63_place12_room8_floora - location
	location_xneg27_ypos28_place10_room4_floora - location
	location_xneg27_ypos54_place1_room3_floorb - location
	location_xneg27_ypos95_place8_room5_floora - location
	location_xneg2_ypos38_place13_room13_floora - location
	location_xneg31_ypos76_place4_room7_floorb - location
	location_xneg33_ypos67_place0_room2_floora - location
	location_xneg5_ypos85_place7_room12_floorb - location
	location_xpos15_ypos88_place5_room11_floora - location
	location_xpos18_ypos105_place30_room11_floora - location
	location_xpos18_ypos25_place3_room10_floora - location
	location_xpos20_ypos60_place9_room6_floorb - location
	location_xpos23_ypos52_place6_room9_floora - location
	location_xpos23_ypos92_place30_room11_floora - location
	location_xpos27_ypos6_place52_room1_floora - location
	location_xpos31_yneg1_place2_room1_floora - location
	location_xpos9_yneg1_place11_room14_floora - location
	place0_door_room2_bathroom - place
	place10_door_room4_bedroom - place
	place11_door_room14_utility_room - place
	place12_door_room8_corridor - place
	place13_door_room13_staircase - place
	place1_door_room3_bathroom - place
	place2_door_room1_bathroom - place
	place30_receptacle16_couch - place
	place3_door_room10_kitchen - place
	place4_door_room7_closet - place
	place52_receptacle42_sink - place
	place5_door_room11_living_room - place
	place6_door_room9_dining_room - place
	place7_door_room12_living_room - place
	place8_door_room5_bedroom - place
	place9_door_room6_bedroom - place
	receptacle16_couch - receptacle
	receptacle42_sink - receptacle
	robot - agent
	room10_kitchen - room
	room11_living_room - room
	room12_living_room - room
	room13_staircase - room
	room14_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_bedroom - room
	room7_closet - room
	room8_corridor - room
	room9_dining_room - room
  )
  (:init 
	(atlocation robot location_xpos15_ypos88_place5_room11_floora)
	(inanyreceptacle item53_book_smallitem)
	(inplace robot place5_door_room11_living_room)
	(inreceptacle item53_book_smallitem receptacle16_couch)
	(inroom robot room11_living_room)
	(itematlocation item53_book_smallitem location_xpos23_ypos92_place30_room11_floora)
	(locationinplace location_xneg16_ypos63_place12_room8_floora place12_door_room8_corridor)
	(locationinplace location_xneg27_ypos28_place10_room4_floora place10_door_room4_bedroom)
	(locationinplace location_xneg27_ypos54_place1_room3_floorb place1_door_room3_bathroom)
	(locationinplace location_xneg27_ypos95_place8_room5_floora place8_door_room5_bedroom)
	(locationinplace location_xneg2_ypos38_place13_room13_floora place13_door_room13_staircase)
	(locationinplace location_xneg31_ypos76_place4_room7_floorb place4_door_room7_closet)
	(locationinplace location_xneg33_ypos67_place0_room2_floora place0_door_room2_bathroom)
	(locationinplace location_xneg5_ypos85_place7_room12_floorb place7_door_room12_living_room)
	(locationinplace location_xpos15_ypos88_place5_room11_floora place5_door_room11_living_room)
	(locationinplace location_xpos18_ypos105_place30_room11_floora place30_receptacle16_couch)
	(locationinplace location_xpos18_ypos25_place3_room10_floora place3_door_room10_kitchen)
	(locationinplace location_xpos20_ypos60_place9_room6_floorb place9_door_room6_bedroom)
	(locationinplace location_xpos23_ypos52_place6_room9_floora place6_door_room9_dining_room)
	(locationinplace location_xpos23_ypos92_place30_room11_floora place30_receptacle16_couch)
	(locationinplace location_xpos27_ypos6_place52_room1_floora place52_receptacle42_sink)
	(locationinplace location_xpos31_yneg1_place2_room1_floora place2_door_room1_bathroom)
	(locationinplace location_xpos9_yneg1_place11_room14_floora place11_door_room14_utility_room)
	(placeinroom place0_door_room2_bathroom room2_bathroom)
	(placeinroom place10_door_room4_bedroom room4_bedroom)
	(placeinroom place11_door_room14_utility_room room14_utility_room)
	(placeinroom place12_door_room8_corridor room8_corridor)
	(placeinroom place13_door_room13_staircase room13_staircase)
	(placeinroom place1_door_room3_bathroom room3_bathroom)
	(placeinroom place2_door_room1_bathroom room1_bathroom)
	(placeinroom place30_receptacle16_couch room11_living_room)
	(placeinroom place3_door_room10_kitchen room10_kitchen)
	(placeinroom place4_door_room7_closet room7_closet)
	(placeinroom place52_receptacle42_sink room1_bathroom)
	(placeinroom place5_door_room11_living_room room11_living_room)
	(placeinroom place6_door_room9_dining_room room9_dining_room)
	(placeinroom place7_door_room12_living_room room12_living_room)
	(placeinroom place8_door_room5_bedroom room5_bedroom)
	(placeinroom place9_door_room6_bedroom room6_bedroom)
	(placelocation location_xneg16_ypos63_place12_room8_floora place12_door_room8_corridor)
	(placelocation location_xneg27_ypos28_place10_room4_floora place10_door_room4_bedroom)
	(placelocation location_xneg27_ypos54_place1_room3_floorb place1_door_room3_bathroom)
	(placelocation location_xneg27_ypos95_place8_room5_floora place8_door_room5_bedroom)
	(placelocation location_xneg2_ypos38_place13_room13_floora place13_door_room13_staircase)
	(placelocation location_xneg31_ypos76_place4_room7_floorb place4_door_room7_closet)
	(placelocation location_xneg33_ypos67_place0_room2_floora place0_door_room2_bathroom)
	(placelocation location_xneg5_ypos85_place7_room12_floorb place7_door_room12_living_room)
	(placelocation location_xpos15_ypos88_place5_room11_floora place5_door_room11_living_room)
	(placelocation location_xpos18_ypos105_place30_room11_floora place30_receptacle16_couch)
	(placelocation location_xpos18_ypos25_place3_room10_floora place3_door_room10_kitchen)
	(placelocation location_xpos20_ypos60_place9_room6_floorb place9_door_room6_bedroom)
	(placelocation location_xpos23_ypos52_place6_room9_floora place6_door_room9_dining_room)
	(placelocation location_xpos27_ypos6_place52_room1_floora place52_receptacle42_sink)
	(placelocation location_xpos31_yneg1_place2_room1_floora place2_door_room1_bathroom)
	(placelocation location_xpos9_yneg1_place11_room14_floora place11_door_room14_utility_room)
	(receptacleatlocation receptacle16_couch location_xpos18_ypos105_place30_room11_floora)
	(receptacleatlocation receptacle42_sink location_xpos27_ypos6_place52_room1_floora)
	(roomplace place0_door_room2_bathroom room2_bathroom)
	(roomplace place10_door_room4_bedroom room4_bedroom)
	(roomplace place11_door_room14_utility_room room14_utility_room)
	(roomplace place12_door_room8_corridor room8_corridor)
	(roomplace place13_door_room13_staircase room13_staircase)
	(roomplace place1_door_room3_bathroom room3_bathroom)
	(roomplace place2_door_room1_bathroom room1_bathroom)
	(roomplace place3_door_room10_kitchen room10_kitchen)
	(roomplace place4_door_room7_closet room7_closet)
	(roomplace place5_door_room11_living_room room11_living_room)
	(roomplace place6_door_room9_dining_room room9_dining_room)
	(roomplace place7_door_room12_living_room room12_living_room)
	(roomplace place8_door_room5_bedroom room5_bedroom)
	(roomplace place9_door_room6_bedroom room6_bedroom)
	(roomsconnected room10_kitchen room13_staircase)
	(roomsconnected room10_kitchen room14_utility_room)
	(roomsconnected room10_kitchen room9_dining_room)
	(roomsconnected room11_living_room room9_dining_room)
	(roomsconnected room12_living_room room6_bedroom)
	(roomsconnected room12_living_room room7_closet)
	(roomsconnected room13_staircase room10_kitchen)
	(roomsconnected room13_staircase room4_bedroom)
	(roomsconnected room13_staircase room8_corridor)
	(roomsconnected room14_utility_room room10_kitchen)
	(roomsconnected room14_utility_room room1_bathroom)
	(roomsconnected room1_bathroom room14_utility_room)
	(roomsconnected room2_bathroom room5_bedroom)
	(roomsconnected room2_bathroom room8_corridor)
	(roomsconnected room3_bathroom room7_closet)
	(roomsconnected room4_bedroom room13_staircase)
	(roomsconnected room5_bedroom room2_bathroom)
	(roomsconnected room6_bedroom room12_living_room)
	(roomsconnected room6_bedroom room9_dining_room)
	(roomsconnected room7_closet room12_living_room)
	(roomsconnected room7_closet room3_bathroom)
	(roomsconnected room8_corridor room13_staircase)
	(roomsconnected room8_corridor room2_bathroom)
	(roomsconnected room9_dining_room room10_kitchen)
	(roomsconnected room9_dining_room room11_living_room)
	(roomsconnected room9_dining_room room6_bedroom)
  )
  (:goal (and
	(inreceptacle item53_book_smallitem receptacle42_sink)))
)
