
(define (problem springervilletaskographyv2medium1problem62) (:domain taskographyv2medium1scrub)
  (:objects
        item14_vase_mediumitem - item
	location_xneg12_yneg2_place43_room13_floora - location
	location_xneg17_ypos40_place1_room2_floorb - location
	location_xneg26_ypos41_place3_room8_floora - location
	location_xneg28_ypos6_place0_room9_floora - location
	location_xneg4_ypos5_place5_room13_floora - location
	location_xneg7_ypos6_place4_room4_floorb - location
	location_xpos11_ypos44_place6_room11_floora - location
	location_xpos18_ypos30_place10_room5_floora - location
	location_xpos1_ypos31_place2_room1_floora - location
	location_xpos22_ypos36_place12_room12_floora - location
	location_xpos29_ypos6_place9_room7_floora - location
	location_xpos32_ypos4_place7_room3_floorb - location
	location_xpos39_ypos66_place8_room10_floora - location
	location_xpos40_ypos2_place38_room3_floorb - location
	location_xpos49_yneg5_place38_room3_floorb - location
	location_xpos6_ypos31_place11_room6_floorb - location
	place0_door_room9_kitchen - place
	place10_door_room5_corridor - place
	place11_door_room6_corridor - place
	place12_door_room12_staircase - place
	place1_door_room2_bathroom - place
	place2_door_room1_bathroom - place
	place38_receptacle36_bed - place
	place3_door_room8_home_office - place
	place43_receptacle41_dining_table - place
	place4_door_room4_bedroom - place
	place5_door_room13_utility_room - place
	place6_door_room11_staircase - place
	place7_door_room3_bedroom - place
	place8_door_room10_living-room - place
	place9_door_room7_dining_room - place
	receptacle36_bed - receptacle
	receptacle41_dining_table - receptacle
	robot - agent
	room10_living-room - room
	room11_staircase - room
	room12_staircase - room
	room13_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bedroom - room
	room4_bedroom - room
	room5_corridor - room
	room6_corridor - room
	room7_dining_room - room
	room8_home_office - room
	room9_kitchen - room
  )
  (:init 
	(atlocation robot location_xneg4_ypos5_place5_room13_floora)
	(inanyreceptacle item14_vase_mediumitem)
	(inplace robot place5_door_room13_utility_room)
	(inreceptacle item14_vase_mediumitem receptacle36_bed)
	(inroom robot room13_utility_room)
	(itematlocation item14_vase_mediumitem location_xpos49_yneg5_place38_room3_floorb)
	(locationinplace location_xneg12_yneg2_place43_room13_floora place43_receptacle41_dining_table)
	(locationinplace location_xneg17_ypos40_place1_room2_floorb place1_door_room2_bathroom)
	(locationinplace location_xneg26_ypos41_place3_room8_floora place3_door_room8_home_office)
	(locationinplace location_xneg28_ypos6_place0_room9_floora place0_door_room9_kitchen)
	(locationinplace location_xneg4_ypos5_place5_room13_floora place5_door_room13_utility_room)
	(locationinplace location_xneg7_ypos6_place4_room4_floorb place4_door_room4_bedroom)
	(locationinplace location_xpos11_ypos44_place6_room11_floora place6_door_room11_staircase)
	(locationinplace location_xpos18_ypos30_place10_room5_floora place10_door_room5_corridor)
	(locationinplace location_xpos1_ypos31_place2_room1_floora place2_door_room1_bathroom)
	(locationinplace location_xpos22_ypos36_place12_room12_floora place12_door_room12_staircase)
	(locationinplace location_xpos29_ypos6_place9_room7_floora place9_door_room7_dining_room)
	(locationinplace location_xpos32_ypos4_place7_room3_floorb place7_door_room3_bedroom)
	(locationinplace location_xpos39_ypos66_place8_room10_floora place8_door_room10_living-room)
	(locationinplace location_xpos40_ypos2_place38_room3_floorb place38_receptacle36_bed)
	(locationinplace location_xpos49_yneg5_place38_room3_floorb place38_receptacle36_bed)
	(locationinplace location_xpos6_ypos31_place11_room6_floorb place11_door_room6_corridor)
	(placeinroom place0_door_room9_kitchen room9_kitchen)
	(placeinroom place10_door_room5_corridor room5_corridor)
	(placeinroom place11_door_room6_corridor room6_corridor)
	(placeinroom place12_door_room12_staircase room12_staircase)
	(placeinroom place1_door_room2_bathroom room2_bathroom)
	(placeinroom place2_door_room1_bathroom room1_bathroom)
	(placeinroom place38_receptacle36_bed room3_bedroom)
	(placeinroom place3_door_room8_home_office room8_home_office)
	(placeinroom place43_receptacle41_dining_table room13_utility_room)
	(placeinroom place4_door_room4_bedroom room4_bedroom)
	(placeinroom place5_door_room13_utility_room room13_utility_room)
	(placeinroom place6_door_room11_staircase room11_staircase)
	(placeinroom place7_door_room3_bedroom room3_bedroom)
	(placeinroom place8_door_room10_living-room room10_living-room)
	(placeinroom place9_door_room7_dining_room room7_dining_room)
	(placelocation location_xneg12_yneg2_place43_room13_floora place43_receptacle41_dining_table)
	(placelocation location_xneg17_ypos40_place1_room2_floorb place1_door_room2_bathroom)
	(placelocation location_xneg26_ypos41_place3_room8_floora place3_door_room8_home_office)
	(placelocation location_xneg28_ypos6_place0_room9_floora place0_door_room9_kitchen)
	(placelocation location_xneg4_ypos5_place5_room13_floora place5_door_room13_utility_room)
	(placelocation location_xneg7_ypos6_place4_room4_floorb place4_door_room4_bedroom)
	(placelocation location_xpos11_ypos44_place6_room11_floora place6_door_room11_staircase)
	(placelocation location_xpos18_ypos30_place10_room5_floora place10_door_room5_corridor)
	(placelocation location_xpos1_ypos31_place2_room1_floora place2_door_room1_bathroom)
	(placelocation location_xpos22_ypos36_place12_room12_floora place12_door_room12_staircase)
	(placelocation location_xpos29_ypos6_place9_room7_floora place9_door_room7_dining_room)
	(placelocation location_xpos32_ypos4_place7_room3_floorb place7_door_room3_bedroom)
	(placelocation location_xpos39_ypos66_place8_room10_floora place8_door_room10_living-room)
	(placelocation location_xpos40_ypos2_place38_room3_floorb place38_receptacle36_bed)
	(placelocation location_xpos6_ypos31_place11_room6_floorb place11_door_room6_corridor)
	(receptacleatlocation receptacle36_bed location_xpos40_ypos2_place38_room3_floorb)
	(receptacleatlocation receptacle41_dining_table location_xneg12_yneg2_place43_room13_floora)
	(roomplace place0_door_room9_kitchen room9_kitchen)
	(roomplace place10_door_room5_corridor room5_corridor)
	(roomplace place11_door_room6_corridor room6_corridor)
	(roomplace place12_door_room12_staircase room12_staircase)
	(roomplace place1_door_room2_bathroom room2_bathroom)
	(roomplace place2_door_room1_bathroom room1_bathroom)
	(roomplace place3_door_room8_home_office room8_home_office)
	(roomplace place4_door_room4_bedroom room4_bedroom)
	(roomplace place5_door_room13_utility_room room13_utility_room)
	(roomplace place6_door_room11_staircase room11_staircase)
	(roomplace place7_door_room3_bedroom room3_bedroom)
	(roomplace place8_door_room10_living-room room10_living-room)
	(roomplace place9_door_room7_dining_room room7_dining_room)
	(roomsconnected room10_living-room room11_staircase)
	(roomsconnected room11_staircase room10_living-room)
	(roomsconnected room11_staircase room12_staircase)
	(roomsconnected room11_staircase room6_corridor)
	(roomsconnected room12_staircase room11_staircase)
	(roomsconnected room12_staircase room5_corridor)
	(roomsconnected room13_utility_room room1_bathroom)
	(roomsconnected room13_utility_room room9_kitchen)
	(roomsconnected room1_bathroom room13_utility_room)
	(roomsconnected room1_bathroom room5_corridor)
	(roomsconnected room1_bathroom room8_home_office)
	(roomsconnected room2_bathroom room6_corridor)
	(roomsconnected room3_bedroom room6_corridor)
	(roomsconnected room4_bedroom room6_corridor)
	(roomsconnected room5_corridor room12_staircase)
	(roomsconnected room5_corridor room1_bathroom)
	(roomsconnected room5_corridor room7_dining_room)
	(roomsconnected room6_corridor room11_staircase)
	(roomsconnected room6_corridor room2_bathroom)
	(roomsconnected room6_corridor room3_bedroom)
	(roomsconnected room6_corridor room4_bedroom)
	(roomsconnected room7_dining_room room5_corridor)
	(roomsconnected room8_home_office room1_bathroom)
	(roomsconnected room9_kitchen room13_utility_room)
  )
  (:goal (and
	(inreceptacle item14_vase_mediumitem receptacle41_dining_table)))
)
