
(define (problem goodyeartaskographyv2medium1problem172) (:domain taskographyv2medium1scrub)
  (:objects
        item81_vase_mediumitem - item
	location_xneg24_yneg8_place16_room7_floorc - location
	location_xneg27_yneg36_place11_room3_floorc - location
	location_xneg28_ypos22_place10_room4_floorc - location
	location_xneg29_ypos6_place1_room16_floora - location
	location_xneg34_yneg13_place15_room6_floorb - location
	location_xneg34_yneg43_place9_room1_floorb - location
	location_xneg39_ypos23_place4_room11_floorb - location
	location_xneg43_yneg7_place6_room15_floorb - location
	location_xneg57_yneg37_place12_room17_floora - location
	location_xneg5_yneg25_place8_room12_floorb - location
	location_xneg60_yneg35_place3_room2_floorb - location
	location_xneg64_ypos7_place13_room14_floora - location
	location_xneg65_ypos32_place5_room9_floorb - location
	location_xneg6_yneg43_place14_room5_floorc - location
	location_xneg8_yneg37_place0_room10_floora - location
	location_xpos0_ypos23_place2_room8_floorb - location
	location_xpos13_yneg34_place43_room12_floorb - location
	location_xpos1_yneg32_place43_room12_floorb - location
	location_xpos4_ypos12_place7_room13_floorc - location
	location_xpos4_ypos16_place39_room8_floorb - location
	place0_door_room10_garage - place
	place10_door_room4_bedroom - place
	place11_door_room3_bedroom - place
	place12_door_room17_utility_room - place
	place13_door_room14_staircase - place
	place14_door_room5_closet - place
	place15_door_room6_corridor - place
	place16_door_room7_corridor - place
	place1_door_room16_storage - place
	place2_door_room8_dining_room - place
	place39_receptacle25_chair - place
	place3_door_room2_bedroom - place
	place43_receptacle29_couch - place
	place4_door_room11_kitchen - place
	place5_door_room9_dining_room - place
	place6_door_room15_staircase - place
	place7_door_room13_living_room - place
	place8_door_room12_living_room - place
	place9_door_room1_bathroom - place
	receptacle25_chair - receptacle
	receptacle29_couch - receptacle
	robot - agent
	room10_garage - room
	room11_kitchen - room
	room12_living_room - room
	room13_living_room - room
	room14_staircase - room
	room15_staircase - room
	room16_storage - room
	room17_utility_room - room
	room1_bathroom - room
	room2_bedroom - room
	room3_bedroom - room
	room4_bedroom - room
	room5_closet - room
	room6_corridor - room
	room7_corridor - room
	room8_dining_room - room
	room9_dining_room - room
  )
  (:init 
	(atlocation robot location_xneg29_ypos6_place1_room16_floora)
	(inanyreceptacle item81_vase_mediumitem)
	(inplace robot place1_door_room16_storage)
	(inreceptacle item81_vase_mediumitem receptacle29_couch)
	(inroom robot room16_storage)
	(itematlocation item81_vase_mediumitem location_xpos1_yneg32_place43_room12_floorb)
	(locationinplace location_xneg24_yneg8_place16_room7_floorc place16_door_room7_corridor)
	(locationinplace location_xneg27_yneg36_place11_room3_floorc place11_door_room3_bedroom)
	(locationinplace location_xneg28_ypos22_place10_room4_floorc place10_door_room4_bedroom)
	(locationinplace location_xneg29_ypos6_place1_room16_floora place1_door_room16_storage)
	(locationinplace location_xneg34_yneg13_place15_room6_floorb place15_door_room6_corridor)
	(locationinplace location_xneg34_yneg43_place9_room1_floorb place9_door_room1_bathroom)
	(locationinplace location_xneg39_ypos23_place4_room11_floorb place4_door_room11_kitchen)
	(locationinplace location_xneg43_yneg7_place6_room15_floorb place6_door_room15_staircase)
	(locationinplace location_xneg57_yneg37_place12_room17_floora place12_door_room17_utility_room)
	(locationinplace location_xneg5_yneg25_place8_room12_floorb place8_door_room12_living_room)
	(locationinplace location_xneg60_yneg35_place3_room2_floorb place3_door_room2_bedroom)
	(locationinplace location_xneg64_ypos7_place13_room14_floora place13_door_room14_staircase)
	(locationinplace location_xneg65_ypos32_place5_room9_floorb place5_door_room9_dining_room)
	(locationinplace location_xneg6_yneg43_place14_room5_floorc place14_door_room5_closet)
	(locationinplace location_xneg8_yneg37_place0_room10_floora place0_door_room10_garage)
	(locationinplace location_xpos0_ypos23_place2_room8_floorb place2_door_room8_dining_room)
	(locationinplace location_xpos13_yneg34_place43_room12_floorb place43_receptacle29_couch)
	(locationinplace location_xpos1_yneg32_place43_room12_floorb place43_receptacle29_couch)
	(locationinplace location_xpos4_ypos12_place7_room13_floorc place7_door_room13_living_room)
	(locationinplace location_xpos4_ypos16_place39_room8_floorb place39_receptacle25_chair)
	(placeinroom place0_door_room10_garage room10_garage)
	(placeinroom place10_door_room4_bedroom room4_bedroom)
	(placeinroom place11_door_room3_bedroom room3_bedroom)
	(placeinroom place12_door_room17_utility_room room17_utility_room)
	(placeinroom place13_door_room14_staircase room14_staircase)
	(placeinroom place14_door_room5_closet room5_closet)
	(placeinroom place15_door_room6_corridor room6_corridor)
	(placeinroom place16_door_room7_corridor room7_corridor)
	(placeinroom place1_door_room16_storage room16_storage)
	(placeinroom place2_door_room8_dining_room room8_dining_room)
	(placeinroom place39_receptacle25_chair room8_dining_room)
	(placeinroom place3_door_room2_bedroom room2_bedroom)
	(placeinroom place43_receptacle29_couch room12_living_room)
	(placeinroom place4_door_room11_kitchen room11_kitchen)
	(placeinroom place5_door_room9_dining_room room9_dining_room)
	(placeinroom place6_door_room15_staircase room15_staircase)
	(placeinroom place7_door_room13_living_room room13_living_room)
	(placeinroom place8_door_room12_living_room room12_living_room)
	(placeinroom place9_door_room1_bathroom room1_bathroom)
	(placelocation location_xneg24_yneg8_place16_room7_floorc place16_door_room7_corridor)
	(placelocation location_xneg27_yneg36_place11_room3_floorc place11_door_room3_bedroom)
	(placelocation location_xneg28_ypos22_place10_room4_floorc place10_door_room4_bedroom)
	(placelocation location_xneg29_ypos6_place1_room16_floora place1_door_room16_storage)
	(placelocation location_xneg34_yneg13_place15_room6_floorb place15_door_room6_corridor)
	(placelocation location_xneg34_yneg43_place9_room1_floorb place9_door_room1_bathroom)
	(placelocation location_xneg39_ypos23_place4_room11_floorb place4_door_room11_kitchen)
	(placelocation location_xneg43_yneg7_place6_room15_floorb place6_door_room15_staircase)
	(placelocation location_xneg57_yneg37_place12_room17_floora place12_door_room17_utility_room)
	(placelocation location_xneg5_yneg25_place8_room12_floorb place8_door_room12_living_room)
	(placelocation location_xneg60_yneg35_place3_room2_floorb place3_door_room2_bedroom)
	(placelocation location_xneg64_ypos7_place13_room14_floora place13_door_room14_staircase)
	(placelocation location_xneg65_ypos32_place5_room9_floorb place5_door_room9_dining_room)
	(placelocation location_xneg6_yneg43_place14_room5_floorc place14_door_room5_closet)
	(placelocation location_xneg8_yneg37_place0_room10_floora place0_door_room10_garage)
	(placelocation location_xpos0_ypos23_place2_room8_floorb place2_door_room8_dining_room)
	(placelocation location_xpos13_yneg34_place43_room12_floorb place43_receptacle29_couch)
	(placelocation location_xpos4_ypos12_place7_room13_floorc place7_door_room13_living_room)
	(placelocation location_xpos4_ypos16_place39_room8_floorb place39_receptacle25_chair)
	(receptacleatlocation receptacle25_chair location_xpos4_ypos16_place39_room8_floorb)
	(receptacleatlocation receptacle29_couch location_xpos13_yneg34_place43_room12_floorb)
	(roomplace place0_door_room10_garage room10_garage)
	(roomplace place10_door_room4_bedroom room4_bedroom)
	(roomplace place11_door_room3_bedroom room3_bedroom)
	(roomplace place12_door_room17_utility_room room17_utility_room)
	(roomplace place13_door_room14_staircase room14_staircase)
	(roomplace place14_door_room5_closet room5_closet)
	(roomplace place15_door_room6_corridor room6_corridor)
	(roomplace place16_door_room7_corridor room7_corridor)
	(roomplace place1_door_room16_storage room16_storage)
	(roomplace place2_door_room8_dining_room room8_dining_room)
	(roomplace place3_door_room2_bedroom room2_bedroom)
	(roomplace place4_door_room11_kitchen room11_kitchen)
	(roomplace place5_door_room9_dining_room room9_dining_room)
	(roomplace place6_door_room15_staircase room15_staircase)
	(roomplace place7_door_room13_living_room room13_living_room)
	(roomplace place8_door_room12_living_room room12_living_room)
	(roomplace place9_door_room1_bathroom room1_bathroom)
	(roomsconnected room10_garage room16_storage)
	(roomsconnected room11_kitchen room15_staircase)
	(roomsconnected room11_kitchen room8_dining_room)
	(roomsconnected room11_kitchen room9_dining_room)
	(roomsconnected room12_living_room room6_corridor)
	(roomsconnected room13_living_room room4_bedroom)
	(roomsconnected room14_staircase room16_storage)
	(roomsconnected room14_staircase room17_utility_room)
	(roomsconnected room15_staircase room11_kitchen)
	(roomsconnected room15_staircase room6_corridor)
	(roomsconnected room15_staircase room7_corridor)
	(roomsconnected room16_storage room10_garage)
	(roomsconnected room16_storage room14_staircase)
	(roomsconnected room17_utility_room room14_staircase)
	(roomsconnected room17_utility_room room2_bedroom)
	(roomsconnected room1_bathroom room2_bedroom)
	(roomsconnected room1_bathroom room6_corridor)
	(roomsconnected room2_bedroom room17_utility_room)
	(roomsconnected room2_bedroom room1_bathroom)
	(roomsconnected room3_bedroom room5_closet)
	(roomsconnected room3_bedroom room7_corridor)
	(roomsconnected room4_bedroom room13_living_room)
	(roomsconnected room4_bedroom room7_corridor)
	(roomsconnected room5_closet room3_bedroom)
	(roomsconnected room6_corridor room12_living_room)
	(roomsconnected room6_corridor room15_staircase)
	(roomsconnected room6_corridor room1_bathroom)
	(roomsconnected room7_corridor room15_staircase)
	(roomsconnected room7_corridor room3_bedroom)
	(roomsconnected room7_corridor room4_bedroom)
	(roomsconnected room8_dining_room room11_kitchen)
	(roomsconnected room9_dining_room room11_kitchen)
  )
  (:goal (and
	(inreceptacle item81_vase_mediumitem receptacle25_chair)))
)
