
(define (problem pameliataskographyv2medium1problem66) (:domain taskographyv2medium1scrub)
  (:objects
        item72_book_smallitem - item
	location_xneg17_yneg61_place2_room13_floora - location
	location_xneg1_yneg11_place47_room10_floorb - location
	location_xneg22_yneg22_place12_room8_floorb - location
	location_xneg29_yneg67_place11_room7_floorb - location
	location_xneg39_yneg40_place0_room6_floora - location
	location_xneg42_yneg43_place5_room11_floorb - location
	location_xneg49_yneg5_place1_room12_floorb - location
	location_xneg4_yneg46_place10_room4_floorb - location
	location_xneg52_yneg4_place9_room3_floora - location
	location_xneg53_ypos3_place33_room3_floora - location
	location_xneg5_ypos2_place8_room10_floorb - location
	location_xneg68_yneg42_place6_room9_floorb - location
	location_xneg8_yneg5_place7_room5_floora - location
	location_xpos1_yneg22_place3_room2_floorb - location
	location_xpos3_yneg39_place4_room1_floora - location
	place0_door_room6_corridor - place
	place10_door_room4_bedroom - place
	place11_door_room7_corridor - place
	place12_door_room8_corridor - place
	place1_door_room12_living_room - place
	place2_door_room13_staircase - place
	place33_receptacle42_bed - place
	place3_door_room2_bathroom - place
	place47_receptacle62_refrigerator - place
	place4_door_room1_bathroom - place
	place5_door_room11_kitchen - place
	place6_door_room9_dining_room - place
	place7_door_room5_childs_room - place
	place8_door_room10_home_office - place
	place9_door_room3_bedroom - place
	receptacle42_bed - receptacle
	receptacle62_refrigerator - receptacle
	robot - agent
	room10_home_office - room
	room11_kitchen - room
	room12_living_room - room
	room13_staircase - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bedroom - room
	room4_bedroom - room
	room5_childs_room - room
	room6_corridor - room
	room7_corridor - room
	room8_corridor - room
	room9_dining_room - room
  )
  (:init 
	(atlocation robot location_xneg39_yneg40_place0_room6_floora)
	(inanyreceptacle item72_book_smallitem)
	(inplace robot place0_door_room6_corridor)
	(inreceptacle item72_book_smallitem receptacle62_refrigerator)
	(inroom robot room6_corridor)
	(itematlocation item72_book_smallitem location_xneg1_yneg11_place47_room10_floorb)
	(locationinplace location_xneg17_yneg61_place2_room13_floora place2_door_room13_staircase)
	(locationinplace location_xneg1_yneg11_place47_room10_floorb place47_receptacle62_refrigerator)
	(locationinplace location_xneg22_yneg22_place12_room8_floorb place12_door_room8_corridor)
	(locationinplace location_xneg29_yneg67_place11_room7_floorb place11_door_room7_corridor)
	(locationinplace location_xneg39_yneg40_place0_room6_floora place0_door_room6_corridor)
	(locationinplace location_xneg42_yneg43_place5_room11_floorb place5_door_room11_kitchen)
	(locationinplace location_xneg49_yneg5_place1_room12_floorb place1_door_room12_living_room)
	(locationinplace location_xneg4_yneg46_place10_room4_floorb place10_door_room4_bedroom)
	(locationinplace location_xneg52_yneg4_place9_room3_floora place9_door_room3_bedroom)
	(locationinplace location_xneg53_ypos3_place33_room3_floora place33_receptacle42_bed)
	(locationinplace location_xneg5_ypos2_place8_room10_floorb place8_door_room10_home_office)
	(locationinplace location_xneg68_yneg42_place6_room9_floorb place6_door_room9_dining_room)
	(locationinplace location_xneg8_yneg5_place7_room5_floora place7_door_room5_childs_room)
	(locationinplace location_xpos1_yneg22_place3_room2_floorb place3_door_room2_bathroom)
	(locationinplace location_xpos3_yneg39_place4_room1_floora place4_door_room1_bathroom)
	(placeinroom place0_door_room6_corridor room6_corridor)
	(placeinroom place10_door_room4_bedroom room4_bedroom)
	(placeinroom place11_door_room7_corridor room7_corridor)
	(placeinroom place12_door_room8_corridor room8_corridor)
	(placeinroom place1_door_room12_living_room room12_living_room)
	(placeinroom place2_door_room13_staircase room13_staircase)
	(placeinroom place33_receptacle42_bed room3_bedroom)
	(placeinroom place3_door_room2_bathroom room2_bathroom)
	(placeinroom place47_receptacle62_refrigerator room10_home_office)
	(placeinroom place4_door_room1_bathroom room1_bathroom)
	(placeinroom place5_door_room11_kitchen room11_kitchen)
	(placeinroom place6_door_room9_dining_room room9_dining_room)
	(placeinroom place7_door_room5_childs_room room5_childs_room)
	(placeinroom place8_door_room10_home_office room10_home_office)
	(placeinroom place9_door_room3_bedroom room3_bedroom)
	(placelocation location_xneg17_yneg61_place2_room13_floora place2_door_room13_staircase)
	(placelocation location_xneg1_yneg11_place47_room10_floorb place47_receptacle62_refrigerator)
	(placelocation location_xneg22_yneg22_place12_room8_floorb place12_door_room8_corridor)
	(placelocation location_xneg29_yneg67_place11_room7_floorb place11_door_room7_corridor)
	(placelocation location_xneg39_yneg40_place0_room6_floora place0_door_room6_corridor)
	(placelocation location_xneg42_yneg43_place5_room11_floorb place5_door_room11_kitchen)
	(placelocation location_xneg49_yneg5_place1_room12_floorb place1_door_room12_living_room)
	(placelocation location_xneg4_yneg46_place10_room4_floorb place10_door_room4_bedroom)
	(placelocation location_xneg52_yneg4_place9_room3_floora place9_door_room3_bedroom)
	(placelocation location_xneg53_ypos3_place33_room3_floora place33_receptacle42_bed)
	(placelocation location_xneg5_ypos2_place8_room10_floorb place8_door_room10_home_office)
	(placelocation location_xneg68_yneg42_place6_room9_floorb place6_door_room9_dining_room)
	(placelocation location_xneg8_yneg5_place7_room5_floora place7_door_room5_childs_room)
	(placelocation location_xpos1_yneg22_place3_room2_floorb place3_door_room2_bathroom)
	(placelocation location_xpos3_yneg39_place4_room1_floora place4_door_room1_bathroom)
	(receptacleatlocation receptacle42_bed location_xneg53_ypos3_place33_room3_floora)
	(receptacleatlocation receptacle62_refrigerator location_xneg1_yneg11_place47_room10_floorb)
	(receptacleopeningtype receptacle62_refrigerator)
	(roomplace place0_door_room6_corridor room6_corridor)
	(roomplace place10_door_room4_bedroom room4_bedroom)
	(roomplace place11_door_room7_corridor room7_corridor)
	(roomplace place12_door_room8_corridor room8_corridor)
	(roomplace place1_door_room12_living_room room12_living_room)
	(roomplace place2_door_room13_staircase room13_staircase)
	(roomplace place3_door_room2_bathroom room2_bathroom)
	(roomplace place4_door_room1_bathroom room1_bathroom)
	(roomplace place5_door_room11_kitchen room11_kitchen)
	(roomplace place6_door_room9_dining_room room9_dining_room)
	(roomplace place7_door_room5_childs_room room5_childs_room)
	(roomplace place8_door_room10_home_office room10_home_office)
	(roomplace place9_door_room3_bedroom room3_bedroom)
	(roomsconnected room10_home_office room2_bathroom)
	(roomsconnected room11_kitchen room7_corridor)
	(roomsconnected room11_kitchen room8_corridor)
	(roomsconnected room11_kitchen room9_dining_room)
	(roomsconnected room12_living_room room8_corridor)
	(roomsconnected room13_staircase room1_bathroom)
	(roomsconnected room13_staircase room6_corridor)
	(roomsconnected room13_staircase room7_corridor)
	(roomsconnected room1_bathroom room13_staircase)
	(roomsconnected room1_bathroom room5_childs_room)
	(roomsconnected room2_bathroom room10_home_office)
	(roomsconnected room2_bathroom room4_bedroom)
	(roomsconnected room2_bathroom room8_corridor)
	(roomsconnected room3_bedroom room6_corridor)
	(roomsconnected room4_bedroom room2_bathroom)
	(roomsconnected room5_childs_room room1_bathroom)
	(roomsconnected room6_corridor room13_staircase)
	(roomsconnected room6_corridor room3_bedroom)
	(roomsconnected room7_corridor room11_kitchen)
	(roomsconnected room7_corridor room13_staircase)
	(roomsconnected room8_corridor room11_kitchen)
	(roomsconnected room8_corridor room12_living_room)
	(roomsconnected room8_corridor room2_bathroom)
	(roomsconnected room9_dining_room room11_kitchen)
  )
  (:goal (and
	(inreceptacle item72_book_smallitem receptacle42_bed)))
)
