
(define (problem KobukTaskographyv5Medium5Bagslots7Problem206) (:domain taskographyv5medium5bagslots7)
  (:objects
        apple - iclass
	backpack - iclass
	bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	bagslot6 - bagslot
	bagslot7 - bagslot
	banana - iclass
	baseballbat - iclass
	baseballglove - iclass
	bed - rclass
	bench - rclass
	bicycle - iclass
	boat - rclass
	book - iclass
	bottle - iclass
	bowl - iclass
	cake - iclass
	cellphone - iclass
	chair - rclass
	clock - iclass
	couch - rclass
	cup - iclass
	diningtable - rclass
	frisbee - iclass
	handbag - iclass
	item23_backpack_largeitem - item
	item27_potted_plant_largeitem - item
	item31_tv_largeitem - item
	item3_bottle_smallitem - item
	item4_bottle_smallitem - item
	item5_bottle_smallitem - item
	item6_bottle_smallitem - item
	item7_bottle_smallitem - item
	keyboard - iclass
	kite - iclass
	knife - iclass
	laptop - iclass
	location_Xneg12_Ypos30_place44_room11_floorA - location
	location_Xneg14_Yneg57_place2_room13_floorA - location
	location_Xneg15_Yneg26_place7_room20_floorA - location
	location_Xneg15_Ypos6_place12_room11_floorA - location
	location_Xneg16_Yneg23_place33_room20_floorA - location
	location_Xneg18_Ypos29_place46_room9_floorB - location
	location_Xneg19_Yneg75_place20_room16_floorB - location
	location_Xneg20_Yneg23_place15_room7_floorB - location
	location_Xneg22_Yneg38_place25_room13_floorA - location
	location_Xneg29_Ypos13_place8_room9_floorB - location
	location_Xneg29_Ypos14_place35_room9_floorB - location
	location_Xneg29_Ypos14_place47_room9_floorB - location
	location_Xneg35_Yneg18_place14_room6_floorA - location
	location_Xneg37_Yneg73_place45_room13_floorA - location
	location_Xneg39_Yneg53_place45_room13_floorA - location
	location_Xneg40_Yneg64_place18_room12_floorB - location
	location_Xneg41_Yneg18_place9_room18_floorA - location
	location_Xneg41_Yneg23_place38_room18_floorA - location
	location_Xneg41_Yneg59_place45_room13_floorA - location
	location_Xneg46_Yneg25_place31_room2_floorB - location
	location_Xneg47_Yneg17_place31_room2_floorB - location
	location_Xneg49_Yneg16_place31_room2_floorB - location
	location_Xneg4_Yneg51_place6_room16_floorB - location
	location_Xneg55_Yneg43_place16_room8_floorB - location
	location_Xneg58_Yneg17_place3_room1_floorA - location
	location_Xneg58_Yneg21_place4_room2_floorB - location
	location_Xneg58_Yneg32_place13_room5_floorA - location
	location_Xneg5_Yneg41_place25_room13_floorA - location
	location_Xneg64_Yneg10_place37_room2_floorB - location
	location_Xneg64_Yneg24_place29_room1_floorA - location
	location_Xneg65_Yneg10_place36_room1_floorA - location
	location_Xneg67_Yneg26_place29_room1_floorA - location
	location_Xneg74_Yneg12_place30_room14_floorA - location
	location_Xneg75_Yneg23_place21_room14_floorA - location
	location_Xneg76_Yneg58_place17_room10_floorA - location
	location_Xneg81_Yneg16_place42_room3_floorB - location
	location_Xneg81_Yneg64_place10_room4_floorB - location
	location_Xneg82_Yneg8_place43_room3_floorB - location
	location_Xneg84_Yneg22_place0_room14_floorA - location
	location_Xneg85_Yneg22_place11_room3_floorB - location
	location_Xneg88_Yneg64_place41_room4_floorB - location
	location_Xneg8_Ypos10_place28_room15_floorB - location
	location_Xneg95_Yneg17_place26_room14_floorA - location
	location_Xneg98_Yneg22_place26_room14_floorA - location
	location_Xpos0_Yneg74_place34_room13_floorA - location
	location_Xpos10_Yneg57_place40_room16_floorB - location
	location_Xpos12_Yneg27_place23_room19_floorA - location
	location_Xpos12_Yneg54_place24_room13_floorA - location
	location_Xpos14_Ypos20_place32_room15_floorB - location
	location_Xpos16_Yneg35_place27_room16_floorB - location
	location_Xpos1_Ypos29_place22_room15_floorB - location
	location_Xpos2_Yneg10_place19_room17_floorB - location
	location_Xpos2_Ypos18_place1_room15_floorB - location
	location_Xpos3_Yneg41_place39_room16_floorB - location
	location_Xpos5_Yneg29_place5_room19_floorA - location
	microwave - rclass
	motorcycle - iclass
	mouse - iclass
	orange - iclass
	oven - rclass
	place0_door_room14_kitchen - place
	place10_door_room4_bedroom - place
	place11_door_room3_bedroom - place
	place12_door_room11_empty_room - place
	place13_door_room5_corridor - place
	place14_door_room6_corridor - place
	place15_door_room7_corridor - place
	place16_door_room8_corridor - place
	place17_door_room10_empty_room - place
	place18_door_room12_empty_room - place
	place19_door_room17_lobby - place
	place1_door_room15_kitchen - place
	place20_item31_tv - place
	place21_receptacle1_oven - place
	place22_receptacle2_oven - place
	place23_receptacle8_refrigerator - place
	place24_receptacle9_refrigerator - place
	place25_receptacle10_refrigerator - place
	place26_receptacle11_refrigerator - place
	place27_receptacle12_refrigerator - place
	place28_receptacle13_refrigerator - place
	place29_receptacle14_sink - place
	place2_door_room13_garagge - place
	place30_receptacle15_sink - place
	place31_receptacle16_sink - place
	place32_receptacle17_sink - place
	place33_receptacle18_bench - place
	place34_receptacle19_bench - place
	place35_receptacle20_dining_table - place
	place36_receptacle21_toilet - place
	place37_receptacle22_toilet - place
	place38_receptacle24_couch - place
	place39_receptacle25_couch - place
	place3_door_room1_bathroom - place
	place40_receptacle26_couch - place
	place41_receptacle28_bed - place
	place42_receptacle29_bed - place
	place43_receptacle30_bed - place
	place44_receptacle32_chair - place
	place45_receptacle33_chair - place
	place46_receptacle34_chair - place
	place47_receptacle35_chair - place
	place4_door_room2_bathroom - place
	place5_door_room19_storage - place
	place6_door_room16_living_room - place
	place7_door_room20_storage - place
	place8_door_room9_dining_room - place
	place9_door_room18_staircase - place
	pottedplant - iclass
	receptacle10_refrigerator - receptacle
	receptacle11_refrigerator - receptacle
	receptacle12_refrigerator - receptacle
	receptacle13_refrigerator - receptacle
	receptacle14_sink - receptacle
	receptacle15_sink - receptacle
	receptacle16_sink - receptacle
	receptacle17_sink - receptacle
	receptacle18_bench - receptacle
	receptacle19_bench - receptacle
	receptacle1_oven - receptacle
	receptacle20_dining_table - receptacle
	receptacle21_toilet - receptacle
	receptacle22_toilet - receptacle
	receptacle24_couch - receptacle
	receptacle25_couch - receptacle
	receptacle26_couch - receptacle
	receptacle28_bed - receptacle
	receptacle29_bed - receptacle
	receptacle2_oven - receptacle
	receptacle30_bed - receptacle
	receptacle32_chair - receptacle
	receptacle33_chair - receptacle
	receptacle34_chair - receptacle
	receptacle35_chair - receptacle
	receptacle8_refrigerator - receptacle
	receptacle9_refrigerator - receptacle
	refrigerator - rclass
	remote - iclass
	robot - agent
	room10_empty_room - room
	room11_empty_room - room
	room12_empty_room - room
	room13_garagge - room
	room14_kitchen - room
	room15_kitchen - room
	room16_living_room - room
	room17_lobby - room
	room18_staircase - room
	room19_storage - room
	room1_bathroom - room
	room20_storage - room
	room2_bathroom - room
	room3_bedroom - room
	room4_bedroom - room
	room5_corridor - room
	room6_corridor - room
	room7_corridor - room
	room8_corridor - room
	room9_dining_room - room
	sink - rclass
	spoon - iclass
	sportsball - iclass
	suitcase - iclass
	surfboard - iclass
	teddybear - iclass
	tie - iclass
	toaster - rclass
	toilet - rclass
	toothbrush - iclass
	tv - iclass
	umbrella - iclass
	vase - iclass
	wineglass - iclass
  )
  (:init 
	(atlocation robot location_Xneg29_Ypos13_place8_room9_floorB)
	(classrelation backpack chair)
	(classrelation bottle chair)
	(classrelation bottle refrigerator)
	(classrelation bottle sink)
	(classrelation pottedplant sink)
	(inanyreceptacle item23_backpack_largeitem)
	(inanyreceptacle item27_potted_plant_largeitem)
	(inanyreceptacle item3_bottle_smallitem)
	(inanyreceptacle item4_bottle_smallitem)
	(inanyreceptacle item5_bottle_smallitem)
	(inanyreceptacle item6_bottle_smallitem)
	(inanyreceptacle item7_bottle_smallitem)
	(inplace robot place8_door_room9_dining_room)
	(inreceptacle item23_backpack_largeitem receptacle33_chair)
	(inreceptacle item27_potted_plant_largeitem receptacle16_sink)
	(inreceptacle item3_bottle_smallitem receptacle10_refrigerator)
	(inreceptacle item4_bottle_smallitem receptacle33_chair)
	(inreceptacle item5_bottle_smallitem receptacle14_sink)
	(inreceptacle item6_bottle_smallitem receptacle11_refrigerator)
	(inreceptacle item7_bottle_smallitem receptacle16_sink)
	(inroom robot room9_dining_room)
	(itematlocation item23_backpack_largeitem location_Xneg39_Yneg53_place45_room13_floorA)
	(itematlocation item27_potted_plant_largeitem location_Xneg47_Yneg17_place31_room2_floorB)
	(itematlocation item31_tv_largeitem location_Xneg19_Yneg75_place20_room16_floorB)
	(itematlocation item3_bottle_smallitem location_Xneg22_Yneg38_place25_room13_floorA)
	(itematlocation item4_bottle_smallitem location_Xneg37_Yneg73_place45_room13_floorA)
	(itematlocation item5_bottle_smallitem location_Xneg67_Yneg26_place29_room1_floorA)
	(itematlocation item6_bottle_smallitem location_Xneg98_Yneg22_place26_room14_floorA)
	(itematlocation item7_bottle_smallitem location_Xneg46_Yneg25_place31_room2_floorB)
	(itemclass item23_backpack_largeitem backpack)
	(itemclass item27_potted_plant_largeitem pottedplant)
	(itemclass item31_tv_largeitem tv)
	(itemclass item3_bottle_smallitem bottle)
	(itemclass item4_bottle_smallitem bottle)
	(itemclass item5_bottle_smallitem bottle)
	(itemclass item6_bottle_smallitem bottle)
	(itemclass item7_bottle_smallitem bottle)
	(largeitem item23_backpack_largeitem)
	(largeitem item27_potted_plant_largeitem)
	(largeitem item31_tv_largeitem)
	(locationinplace location_Xneg12_Ypos30_place44_room11_floorA place44_receptacle32_chair)
	(locationinplace location_Xneg14_Yneg57_place2_room13_floorA place2_door_room13_garagge)
	(locationinplace location_Xneg15_Yneg26_place7_room20_floorA place7_door_room20_storage)
	(locationinplace location_Xneg15_Ypos6_place12_room11_floorA place12_door_room11_empty_room)
	(locationinplace location_Xneg16_Yneg23_place33_room20_floorA place33_receptacle18_bench)
	(locationinplace location_Xneg18_Ypos29_place46_room9_floorB place46_receptacle34_chair)
	(locationinplace location_Xneg19_Yneg75_place20_room16_floorB place20_item31_tv)
	(locationinplace location_Xneg20_Yneg23_place15_room7_floorB place15_door_room7_corridor)
	(locationinplace location_Xneg22_Yneg38_place25_room13_floorA place25_receptacle10_refrigerator)
	(locationinplace location_Xneg29_Ypos13_place8_room9_floorB place8_door_room9_dining_room)
	(locationinplace location_Xneg29_Ypos14_place35_room9_floorB place35_receptacle20_dining_table)
	(locationinplace location_Xneg29_Ypos14_place47_room9_floorB place47_receptacle35_chair)
	(locationinplace location_Xneg35_Yneg18_place14_room6_floorA place14_door_room6_corridor)
	(locationinplace location_Xneg37_Yneg73_place45_room13_floorA place45_receptacle33_chair)
	(locationinplace location_Xneg39_Yneg53_place45_room13_floorA place45_receptacle33_chair)
	(locationinplace location_Xneg40_Yneg64_place18_room12_floorB place18_door_room12_empty_room)
	(locationinplace location_Xneg41_Yneg18_place9_room18_floorA place9_door_room18_staircase)
	(locationinplace location_Xneg41_Yneg23_place38_room18_floorA place38_receptacle24_couch)
	(locationinplace location_Xneg41_Yneg59_place45_room13_floorA place45_receptacle33_chair)
	(locationinplace location_Xneg46_Yneg25_place31_room2_floorB place31_receptacle16_sink)
	(locationinplace location_Xneg47_Yneg17_place31_room2_floorB place31_receptacle16_sink)
	(locationinplace location_Xneg49_Yneg16_place31_room2_floorB place31_receptacle16_sink)
	(locationinplace location_Xneg4_Yneg51_place6_room16_floorB place6_door_room16_living_room)
	(locationinplace location_Xneg55_Yneg43_place16_room8_floorB place16_door_room8_corridor)
	(locationinplace location_Xneg58_Yneg17_place3_room1_floorA place3_door_room1_bathroom)
	(locationinplace location_Xneg58_Yneg21_place4_room2_floorB place4_door_room2_bathroom)
	(locationinplace location_Xneg58_Yneg32_place13_room5_floorA place13_door_room5_corridor)
	(locationinplace location_Xneg5_Yneg41_place25_room13_floorA place25_receptacle10_refrigerator)
	(locationinplace location_Xneg64_Yneg10_place37_room2_floorB place37_receptacle22_toilet)
	(locationinplace location_Xneg64_Yneg24_place29_room1_floorA place29_receptacle14_sink)
	(locationinplace location_Xneg65_Yneg10_place36_room1_floorA place36_receptacle21_toilet)
	(locationinplace location_Xneg67_Yneg26_place29_room1_floorA place29_receptacle14_sink)
	(locationinplace location_Xneg74_Yneg12_place30_room14_floorA place30_receptacle15_sink)
	(locationinplace location_Xneg75_Yneg23_place21_room14_floorA place21_receptacle1_oven)
	(locationinplace location_Xneg76_Yneg58_place17_room10_floorA place17_door_room10_empty_room)
	(locationinplace location_Xneg81_Yneg16_place42_room3_floorB place42_receptacle29_bed)
	(locationinplace location_Xneg81_Yneg64_place10_room4_floorB place10_door_room4_bedroom)
	(locationinplace location_Xneg82_Yneg8_place43_room3_floorB place43_receptacle30_bed)
	(locationinplace location_Xneg84_Yneg22_place0_room14_floorA place0_door_room14_kitchen)
	(locationinplace location_Xneg85_Yneg22_place11_room3_floorB place11_door_room3_bedroom)
	(locationinplace location_Xneg88_Yneg64_place41_room4_floorB place41_receptacle28_bed)
	(locationinplace location_Xneg8_Ypos10_place28_room15_floorB place28_receptacle13_refrigerator)
	(locationinplace location_Xneg95_Yneg17_place26_room14_floorA place26_receptacle11_refrigerator)
	(locationinplace location_Xneg98_Yneg22_place26_room14_floorA place26_receptacle11_refrigerator)
	(locationinplace location_Xpos0_Yneg74_place34_room13_floorA place34_receptacle19_bench)
	(locationinplace location_Xpos10_Yneg57_place40_room16_floorB place40_receptacle26_couch)
	(locationinplace location_Xpos12_Yneg27_place23_room19_floorA place23_receptacle8_refrigerator)
	(locationinplace location_Xpos12_Yneg54_place24_room13_floorA place24_receptacle9_refrigerator)
	(locationinplace location_Xpos14_Ypos20_place32_room15_floorB place32_receptacle17_sink)
	(locationinplace location_Xpos16_Yneg35_place27_room16_floorB place27_receptacle12_refrigerator)
	(locationinplace location_Xpos1_Ypos29_place22_room15_floorB place22_receptacle2_oven)
	(locationinplace location_Xpos2_Yneg10_place19_room17_floorB place19_door_room17_lobby)
	(locationinplace location_Xpos2_Ypos18_place1_room15_floorB place1_door_room15_kitchen)
	(locationinplace location_Xpos3_Yneg41_place39_room16_floorB place39_receptacle25_couch)
	(locationinplace location_Xpos5_Yneg29_place5_room19_floorA place5_door_room19_storage)
	(placeinroom place0_door_room14_kitchen room14_kitchen)
	(placeinroom place10_door_room4_bedroom room4_bedroom)
	(placeinroom place11_door_room3_bedroom room3_bedroom)
	(placeinroom place12_door_room11_empty_room room11_empty_room)
	(placeinroom place13_door_room5_corridor room5_corridor)
	(placeinroom place14_door_room6_corridor room6_corridor)
	(placeinroom place15_door_room7_corridor room7_corridor)
	(placeinroom place16_door_room8_corridor room8_corridor)
	(placeinroom place17_door_room10_empty_room room10_empty_room)
	(placeinroom place18_door_room12_empty_room room12_empty_room)
	(placeinroom place19_door_room17_lobby room17_lobby)
	(placeinroom place1_door_room15_kitchen room15_kitchen)
	(placeinroom place20_item31_tv room16_living_room)
	(placeinroom place21_receptacle1_oven room14_kitchen)
	(placeinroom place22_receptacle2_oven room15_kitchen)
	(placeinroom place23_receptacle8_refrigerator room19_storage)
	(placeinroom place24_receptacle9_refrigerator room13_garagge)
	(placeinroom place25_receptacle10_refrigerator room13_garagge)
	(placeinroom place26_receptacle11_refrigerator room14_kitchen)
	(placeinroom place27_receptacle12_refrigerator room16_living_room)
	(placeinroom place28_receptacle13_refrigerator room15_kitchen)
	(placeinroom place29_receptacle14_sink room1_bathroom)
	(placeinroom place2_door_room13_garagge room13_garagge)
	(placeinroom place30_receptacle15_sink room14_kitchen)
	(placeinroom place31_receptacle16_sink room2_bathroom)
	(placeinroom place32_receptacle17_sink room15_kitchen)
	(placeinroom place33_receptacle18_bench room20_storage)
	(placeinroom place34_receptacle19_bench room13_garagge)
	(placeinroom place35_receptacle20_dining_table room9_dining_room)
	(placeinroom place36_receptacle21_toilet room1_bathroom)
	(placeinroom place37_receptacle22_toilet room2_bathroom)
	(placeinroom place38_receptacle24_couch room18_staircase)
	(placeinroom place39_receptacle25_couch room16_living_room)
	(placeinroom place3_door_room1_bathroom room1_bathroom)
	(placeinroom place40_receptacle26_couch room16_living_room)
	(placeinroom place41_receptacle28_bed room4_bedroom)
	(placeinroom place42_receptacle29_bed room3_bedroom)
	(placeinroom place43_receptacle30_bed room3_bedroom)
	(placeinroom place44_receptacle32_chair room11_empty_room)
	(placeinroom place45_receptacle33_chair room13_garagge)
	(placeinroom place46_receptacle34_chair room9_dining_room)
	(placeinroom place47_receptacle35_chair room9_dining_room)
	(placeinroom place4_door_room2_bathroom room2_bathroom)
	(placeinroom place5_door_room19_storage room19_storage)
	(placeinroom place6_door_room16_living_room room16_living_room)
	(placeinroom place7_door_room20_storage room20_storage)
	(placeinroom place8_door_room9_dining_room room9_dining_room)
	(placeinroom place9_door_room18_staircase room18_staircase)
	(placelocation location_Xneg12_Ypos30_place44_room11_floorA place44_receptacle32_chair)
	(placelocation location_Xneg14_Yneg57_place2_room13_floorA place2_door_room13_garagge)
	(placelocation location_Xneg15_Yneg26_place7_room20_floorA place7_door_room20_storage)
	(placelocation location_Xneg15_Ypos6_place12_room11_floorA place12_door_room11_empty_room)
	(placelocation location_Xneg16_Yneg23_place33_room20_floorA place33_receptacle18_bench)
	(placelocation location_Xneg18_Ypos29_place46_room9_floorB place46_receptacle34_chair)
	(placelocation location_Xneg19_Yneg75_place20_room16_floorB place20_item31_tv)
	(placelocation location_Xneg20_Yneg23_place15_room7_floorB place15_door_room7_corridor)
	(placelocation location_Xneg29_Ypos13_place8_room9_floorB place8_door_room9_dining_room)
	(placelocation location_Xneg29_Ypos14_place35_room9_floorB place35_receptacle20_dining_table)
	(placelocation location_Xneg29_Ypos14_place47_room9_floorB place47_receptacle35_chair)
	(placelocation location_Xneg35_Yneg18_place14_room6_floorA place14_door_room6_corridor)
	(placelocation location_Xneg40_Yneg64_place18_room12_floorB place18_door_room12_empty_room)
	(placelocation location_Xneg41_Yneg18_place9_room18_floorA place9_door_room18_staircase)
	(placelocation location_Xneg41_Yneg23_place38_room18_floorA place38_receptacle24_couch)
	(placelocation location_Xneg41_Yneg59_place45_room13_floorA place45_receptacle33_chair)
	(placelocation location_Xneg49_Yneg16_place31_room2_floorB place31_receptacle16_sink)
	(placelocation location_Xneg4_Yneg51_place6_room16_floorB place6_door_room16_living_room)
	(placelocation location_Xneg55_Yneg43_place16_room8_floorB place16_door_room8_corridor)
	(placelocation location_Xneg58_Yneg17_place3_room1_floorA place3_door_room1_bathroom)
	(placelocation location_Xneg58_Yneg21_place4_room2_floorB place4_door_room2_bathroom)
	(placelocation location_Xneg58_Yneg32_place13_room5_floorA place13_door_room5_corridor)
	(placelocation location_Xneg5_Yneg41_place25_room13_floorA place25_receptacle10_refrigerator)
	(placelocation location_Xneg64_Yneg10_place37_room2_floorB place37_receptacle22_toilet)
	(placelocation location_Xneg64_Yneg24_place29_room1_floorA place29_receptacle14_sink)
	(placelocation location_Xneg65_Yneg10_place36_room1_floorA place36_receptacle21_toilet)
	(placelocation location_Xneg74_Yneg12_place30_room14_floorA place30_receptacle15_sink)
	(placelocation location_Xneg75_Yneg23_place21_room14_floorA place21_receptacle1_oven)
	(placelocation location_Xneg76_Yneg58_place17_room10_floorA place17_door_room10_empty_room)
	(placelocation location_Xneg81_Yneg16_place42_room3_floorB place42_receptacle29_bed)
	(placelocation location_Xneg81_Yneg64_place10_room4_floorB place10_door_room4_bedroom)
	(placelocation location_Xneg82_Yneg8_place43_room3_floorB place43_receptacle30_bed)
	(placelocation location_Xneg84_Yneg22_place0_room14_floorA place0_door_room14_kitchen)
	(placelocation location_Xneg85_Yneg22_place11_room3_floorB place11_door_room3_bedroom)
	(placelocation location_Xneg88_Yneg64_place41_room4_floorB place41_receptacle28_bed)
	(placelocation location_Xneg8_Ypos10_place28_room15_floorB place28_receptacle13_refrigerator)
	(placelocation location_Xneg95_Yneg17_place26_room14_floorA place26_receptacle11_refrigerator)
	(placelocation location_Xpos0_Yneg74_place34_room13_floorA place34_receptacle19_bench)
	(placelocation location_Xpos10_Yneg57_place40_room16_floorB place40_receptacle26_couch)
	(placelocation location_Xpos12_Yneg27_place23_room19_floorA place23_receptacle8_refrigerator)
	(placelocation location_Xpos12_Yneg54_place24_room13_floorA place24_receptacle9_refrigerator)
	(placelocation location_Xpos14_Ypos20_place32_room15_floorB place32_receptacle17_sink)
	(placelocation location_Xpos16_Yneg35_place27_room16_floorB place27_receptacle12_refrigerator)
	(placelocation location_Xpos1_Ypos29_place22_room15_floorB place22_receptacle2_oven)
	(placelocation location_Xpos2_Yneg10_place19_room17_floorB place19_door_room17_lobby)
	(placelocation location_Xpos2_Ypos18_place1_room15_floorB place1_door_room15_kitchen)
	(placelocation location_Xpos3_Yneg41_place39_room16_floorB place39_receptacle25_couch)
	(placelocation location_Xpos5_Yneg29_place5_room19_floorA place5_door_room19_storage)
	(receptacleatlocation receptacle10_refrigerator location_Xneg5_Yneg41_place25_room13_floorA)
	(receptacleatlocation receptacle11_refrigerator location_Xneg95_Yneg17_place26_room14_floorA)
	(receptacleatlocation receptacle12_refrigerator location_Xpos16_Yneg35_place27_room16_floorB)
	(receptacleatlocation receptacle13_refrigerator location_Xneg8_Ypos10_place28_room15_floorB)
	(receptacleatlocation receptacle14_sink location_Xneg64_Yneg24_place29_room1_floorA)
	(receptacleatlocation receptacle15_sink location_Xneg74_Yneg12_place30_room14_floorA)
	(receptacleatlocation receptacle16_sink location_Xneg49_Yneg16_place31_room2_floorB)
	(receptacleatlocation receptacle17_sink location_Xpos14_Ypos20_place32_room15_floorB)
	(receptacleatlocation receptacle18_bench location_Xneg16_Yneg23_place33_room20_floorA)
	(receptacleatlocation receptacle19_bench location_Xpos0_Yneg74_place34_room13_floorA)
	(receptacleatlocation receptacle1_oven location_Xneg75_Yneg23_place21_room14_floorA)
	(receptacleatlocation receptacle20_dining_table location_Xneg29_Ypos14_place35_room9_floorB)
	(receptacleatlocation receptacle21_toilet location_Xneg65_Yneg10_place36_room1_floorA)
	(receptacleatlocation receptacle22_toilet location_Xneg64_Yneg10_place37_room2_floorB)
	(receptacleatlocation receptacle24_couch location_Xneg41_Yneg23_place38_room18_floorA)
	(receptacleatlocation receptacle25_couch location_Xpos3_Yneg41_place39_room16_floorB)
	(receptacleatlocation receptacle26_couch location_Xpos10_Yneg57_place40_room16_floorB)
	(receptacleatlocation receptacle28_bed location_Xneg88_Yneg64_place41_room4_floorB)
	(receptacleatlocation receptacle29_bed location_Xneg81_Yneg16_place42_room3_floorB)
	(receptacleatlocation receptacle2_oven location_Xpos1_Ypos29_place22_room15_floorB)
	(receptacleatlocation receptacle30_bed location_Xneg82_Yneg8_place43_room3_floorB)
	(receptacleatlocation receptacle32_chair location_Xneg12_Ypos30_place44_room11_floorA)
	(receptacleatlocation receptacle33_chair location_Xneg41_Yneg59_place45_room13_floorA)
	(receptacleatlocation receptacle34_chair location_Xneg18_Ypos29_place46_room9_floorB)
	(receptacleatlocation receptacle35_chair location_Xneg29_Ypos14_place47_room9_floorB)
	(receptacleatlocation receptacle8_refrigerator location_Xpos12_Yneg27_place23_room19_floorA)
	(receptacleatlocation receptacle9_refrigerator location_Xpos12_Yneg54_place24_room13_floorA)
	(receptacleclass receptacle10_refrigerator refrigerator)
	(receptacleclass receptacle11_refrigerator refrigerator)
	(receptacleclass receptacle12_refrigerator refrigerator)
	(receptacleclass receptacle13_refrigerator refrigerator)
	(receptacleclass receptacle14_sink sink)
	(receptacleclass receptacle15_sink sink)
	(receptacleclass receptacle16_sink sink)
	(receptacleclass receptacle17_sink sink)
	(receptacleclass receptacle18_bench bench)
	(receptacleclass receptacle19_bench bench)
	(receptacleclass receptacle1_oven oven)
	(receptacleclass receptacle20_dining_table diningtable)
	(receptacleclass receptacle21_toilet toilet)
	(receptacleclass receptacle22_toilet toilet)
	(receptacleclass receptacle24_couch couch)
	(receptacleclass receptacle25_couch couch)
	(receptacleclass receptacle26_couch couch)
	(receptacleclass receptacle28_bed bed)
	(receptacleclass receptacle29_bed bed)
	(receptacleclass receptacle2_oven oven)
	(receptacleclass receptacle30_bed bed)
	(receptacleclass receptacle32_chair chair)
	(receptacleclass receptacle33_chair chair)
	(receptacleclass receptacle34_chair chair)
	(receptacleclass receptacle35_chair chair)
	(receptacleclass receptacle8_refrigerator refrigerator)
	(receptacleclass receptacle9_refrigerator refrigerator)
	(receptacleopeningtype receptacle10_refrigerator)
	(receptacleopeningtype receptacle11_refrigerator)
	(receptacleopeningtype receptacle12_refrigerator)
	(receptacleopeningtype receptacle13_refrigerator)
	(receptacleopeningtype receptacle1_oven)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle8_refrigerator)
	(receptacleopeningtype receptacle9_refrigerator)
	(roomplace place0_door_room14_kitchen room14_kitchen)
	(roomplace place10_door_room4_bedroom room4_bedroom)
	(roomplace place11_door_room3_bedroom room3_bedroom)
	(roomplace place12_door_room11_empty_room room11_empty_room)
	(roomplace place13_door_room5_corridor room5_corridor)
	(roomplace place14_door_room6_corridor room6_corridor)
	(roomplace place15_door_room7_corridor room7_corridor)
	(roomplace place16_door_room8_corridor room8_corridor)
	(roomplace place17_door_room10_empty_room room10_empty_room)
	(roomplace place18_door_room12_empty_room room12_empty_room)
	(roomplace place19_door_room17_lobby room17_lobby)
	(roomplace place1_door_room15_kitchen room15_kitchen)
	(roomplace place2_door_room13_garagge room13_garagge)
	(roomplace place3_door_room1_bathroom room1_bathroom)
	(roomplace place4_door_room2_bathroom room2_bathroom)
	(roomplace place5_door_room19_storage room19_storage)
	(roomplace place6_door_room16_living_room room16_living_room)
	(roomplace place7_door_room20_storage room20_storage)
	(roomplace place8_door_room9_dining_room room9_dining_room)
	(roomplace place9_door_room18_staircase room18_staircase)
	(roomsconnected room10_empty_room room5_corridor)
	(roomsconnected room11_empty_room room6_corridor)
	(roomsconnected room12_empty_room room8_corridor)
	(roomsconnected room13_garagge room20_storage)
	(roomsconnected room14_kitchen room1_bathroom)
	(roomsconnected room15_kitchen room17_lobby)
	(roomsconnected room15_kitchen room9_dining_room)
	(roomsconnected room16_living_room room7_corridor)
	(roomsconnected room17_lobby room15_kitchen)
	(roomsconnected room17_lobby room7_corridor)
	(roomsconnected room18_staircase room1_bathroom)
	(roomsconnected room18_staircase room2_bathroom)
	(roomsconnected room18_staircase room6_corridor)
	(roomsconnected room19_storage room20_storage)
	(roomsconnected room1_bathroom room14_kitchen)
	(roomsconnected room1_bathroom room18_staircase)
	(roomsconnected room1_bathroom room5_corridor)
	(roomsconnected room20_storage room13_garagge)
	(roomsconnected room20_storage room19_storage)
	(roomsconnected room20_storage room6_corridor)
	(roomsconnected room2_bathroom room18_staircase)
	(roomsconnected room2_bathroom room3_bedroom)
	(roomsconnected room2_bathroom room7_corridor)
	(roomsconnected room2_bathroom room8_corridor)
	(roomsconnected room3_bedroom room2_bathroom)
	(roomsconnected room4_bedroom room8_corridor)
	(roomsconnected room5_corridor room10_empty_room)
	(roomsconnected room5_corridor room1_bathroom)
	(roomsconnected room6_corridor room11_empty_room)
	(roomsconnected room6_corridor room18_staircase)
	(roomsconnected room6_corridor room20_storage)
	(roomsconnected room7_corridor room16_living_room)
	(roomsconnected room7_corridor room17_lobby)
	(roomsconnected room7_corridor room2_bathroom)
	(roomsconnected room8_corridor room12_empty_room)
	(roomsconnected room8_corridor room2_bathroom)
	(roomsconnected room8_corridor room4_bedroom)
	(roomsconnected room9_dining_room room15_kitchen)
	(smallitem item3_bottle_smallitem)
	(smallitem item4_bottle_smallitem)
	(smallitem item5_bottle_smallitem)
	(smallitem item6_bottle_smallitem)
	(smallitem item7_bottle_smallitem)
  )
  (:goal (and
	(classrelation bottle couch)
	(classrelation bottle bed)
	(classrelation backpack refrigerator)
	(classrelation pottedplant refrigerator)
	(classrelation tv refrigerator)))
)
