
(define (problem coffeentaskographyv4tiny5problem32) (:domain taskographyv4tiny5scrub)
  (:objects
        apple - iclass
	backpack - iclass
	banana - iclass
	baseballbat - iclass
	baseballglove - iclass
	bed - rclass
	bench - rclass
	bicycle - iclass
	boat - rclass
	book - iclass
	bottle - iclass
	bowl - iclass
	cake - iclass
	cellphone - iclass
	chair - rclass
	clock - iclass
	couch - rclass
	cup - iclass
	diningtable - rclass
	frisbee - iclass
	handbag - iclass
	item10_wine_glass_smallitem - item
	item11_wine_glass_smallitem - item
	item12_wine_glass_smallitem - item
	item13_wine_glass_smallitem - item
	item14_wine_glass_smallitem - item
	item15_cup_smallitem - item
	item16_cup_smallitem - item
	item17_bowl_smallitem - item
	item18_bowl_smallitem - item
	item19_bowl_smallitem - item
	item1_backpack_largeitem - item
	item20_bowl_smallitem - item
	item21_bowl_smallitem - item
	item22_apple_smallitem - item
	item2_bottle_smallitem - item
	item38_potted_plant_largeitem - item
	item39_potted_plant_largeitem - item
	item3_bottle_smallitem - item
	item40_potted_plant_largeitem - item
	item41_potted_plant_largeitem - item
	item42_potted_plant_largeitem - item
	item43_potted_plant_largeitem - item
	item44_potted_plant_largeitem - item
	item45_potted_plant_largeitem - item
	item46_potted_plant_largeitem - item
	item47_potted_plant_largeitem - item
	item48_potted_plant_largeitem - item
	item49_potted_plant_largeitem - item
	item4_bottle_smallitem - item
	item50_potted_plant_largeitem - item
	item51_potted_plant_largeitem - item
	item52_potted_plant_largeitem - item
	item53_potted_plant_largeitem - item
	item54_potted_plant_largeitem - item
	item55_potted_plant_largeitem - item
	item56_potted_plant_largeitem - item
	item57_potted_plant_largeitem - item
	item58_potted_plant_largeitem - item
	item59_potted_plant_largeitem - item
	item5_bottle_smallitem - item
	item66_tv_largeitem - item
	item67_tv_largeitem - item
	item6_bottle_smallitem - item
	item78_book_smallitem - item
	item79_book_smallitem - item
	item7_bottle_smallitem - item
	item80_clock_mediumitem - item
	item81_vase_mediumitem - item
	item82_vase_mediumitem - item
	item83_vase_mediumitem - item
	item84_vase_mediumitem - item
	item85_vase_mediumitem - item
	item86_vase_mediumitem - item
	item8_bottle_smallitem - item
	item9_wine_glass_smallitem - item
	keyboard - iclass
	kite - iclass
	knife - iclass
	laptop - iclass
	location_xneg11_yneg10_place47_room14_floorc - location
	location_xneg11_ypos44_place42_room9_floorc - location
	location_xneg11_ypos46_place22_room19_floorb - location
	location_xneg13_yneg17_place48_room6_floord - location
	location_xneg13_ypos64_place45_room9_floorc - location
	location_xneg14_yneg6_place48_room6_floord - location
	location_xneg14_ypos3_place35_room13_floora - location
	location_xneg14_ypos61_place39_room10_floord - location
	location_xneg14_ypos69_place30_room10_floord - location
	location_xneg16_yneg19_place48_room6_floord - location
	location_xneg3_ypos27_place15_room15_floora - location
	location_xneg3_ypos27_place16_room16_floorb - location
	location_xneg3_ypos28_place17_room17_floorc - location
	location_xneg3_ypos28_place18_room18_floord - location
	location_xneg4_ypos60_place52_room5_floora - location
	location_xneg5_ypos4_place20_room14_floorc - location
	location_xneg5_ypos58_place42_room9_floorc - location
	location_xneg5_ypos63_place54_room9_floorc - location
	location_xneg5_ypos68_place43_room9_floorc - location
	location_xneg6_yneg15_place47_room14_floorc - location
	location_xneg6_ypos45_place19_room19_floorb - location
	location_xneg6_ypos50_place39_room10_floord - location
	location_xneg6_ypos63_place54_room9_floorc - location
	location_xneg9_ypos68_place44_room9_floorc - location
	location_xpos0_ypos12_place21_room6_floord - location
	location_xpos0_ypos64_place46_room9_floorc - location
	location_xpos10_ypos28_place9_room8_floord - location
	location_xpos10_ypos73_place40_room10_floord - location
	location_xpos13_yneg5_place8_room6_floord - location
	location_xpos13_ypos2_place7_room14_floorc - location
	location_xpos14_ypos5_place4_room13_floora - location
	location_xpos15_yneg11_place53_room6_floord - location
	location_xpos15_ypos56_place0_room19_floorb - location
	location_xpos16_ypos72_place59_room12_floorc - location
	location_xpos16_ypos73_place59_room12_floorc - location
	location_xpos17_ypos49_place36_room9_floorc - location
	location_xpos17_ypos50_place34_room9_floorc - location
	location_xpos17_ypos68_place59_room12_floorc - location
	location_xpos18_ypos69_place38_room5_floora - location
	location_xpos18_ypos69_place59_room12_floorc - location
	location_xpos18_ypos76_place59_room12_floorc - location
	location_xpos19_ypos27_place23_room8_floord - location
	location_xpos19_ypos69_place59_room12_floorc - location
	location_xpos19_ypos72_place59_room12_floorc - location
	location_xpos1_ypos60_place3_room9_floorc - location
	location_xpos21_ypos48_place37_room19_floorb - location
	location_xpos22_ypos71_place65_room1_floora - location
	location_xpos23_ypos17_place63_room3_floord - location
	location_xpos23_ypos70_place65_room1_floora - location
	location_xpos24_yneg3_place50_room13_floora - location
	location_xpos24_ypos23_place63_room3_floord - location
	location_xpos24_ypos66_place65_room1_floora - location
	location_xpos24_ypos68_place59_room12_floorc - location
	location_xpos25_ypos28_place41_room13_floora - location
	location_xpos26_ypos27_place32_room14_floorc - location
	location_xpos26_ypos51_place67_room12_floorc - location
	location_xpos27_ypos45_place60_room2_floorc - location
	location_xpos27_ypos77_place64_room12_floorc - location
	location_xpos28_yneg6_place51_room14_floorc - location
	location_xpos29_ypos41_place61_room11_floora - location
	location_xpos30_ypos24_place41_room13_floora - location
	location_xpos30_ypos36_place61_room11_floora - location
	location_xpos30_ypos40_place61_room11_floora - location
	location_xpos30_ypos43_place60_room2_floorc - location
	location_xpos30_ypos63_place2_room12_floorc - location
	location_xpos31_ypos33_place61_room11_floora - location
	location_xpos32_ypos16_place41_room13_floora - location
	location_xpos32_ypos32_place13_room3_floord - location
	location_xpos32_ypos38_place10_room2_floorc - location
	location_xpos32_ypos55_place12_room4_floord - location
	location_xpos33_ypos41_place61_room11_floora - location
	location_xpos33_ypos59_place11_room1_floora - location
	location_xpos35_yneg16_place28_room13_floora - location
	location_xpos36_yneg11_place26_room13_floora - location
	location_xpos36_yneg11_place50_room13_floora - location
	location_xpos36_ypos39_place1_room11_floora - location
	location_xpos36_ypos52_place58_room12_floorc - location
	location_xpos36_ypos72_place64_room12_floorc - location
	location_xpos37_yneg11_place27_room13_floora - location
	location_xpos37_ypos10_place41_room13_floora - location
	location_xpos38_yneg11_place50_room13_floora - location
	location_xpos38_ypos41_place57_room2_floorc - location
	location_xpos38_ypos58_place66_room19_floorb - location
	location_xpos39_yneg12_place25_room13_floora - location
	location_xpos39_ypos27_place31_room14_floorc - location
	location_xpos39_ypos55_place56_room4_floord - location
	location_xpos39_ypos67_place55_room1_floora - location
	location_xpos39_ypos69_place66_room19_floorb - location
	location_xpos40_ypos16_place33_room14_floorc - location
	location_xpos40_ypos23_place62_room3_floord - location
	location_xpos40_ypos2_place49_room6_floord - location
	location_xpos40_ypos75_place66_room19_floorb - location
	location_xpos40_ypos77_place66_room19_floorb - location
	location_xpos41_ypos75_place66_room19_floorb - location
	location_xpos41_ypos77_place64_room12_floorc - location
	location_xpos41_ypos77_place66_room19_floorb - location
	location_xpos41_ypos78_place66_room19_floorb - location
	location_xpos42_ypos72_place66_room19_floorb - location
	location_xpos4_ypos51_place5_room5_floora - location
	location_xpos8_ypos27_place14_room7_floorc - location
	location_xpos8_ypos60_place6_room10_floord - location
	location_xpos9_ypos68_place24_room19_floorb - location
	location_xpos9_ypos69_place29_room19_floorb - location
	microwave - rclass
	motorcycle - iclass
	mouse - iclass
	orange - iclass
	oven - rclass
	place0_door_room19_utility_room - place
	place10_door_room2_bathroom - place
	place11_door_room1_bathroom - place
	place12_door_room4_bathroom - place
	place13_door_room3_bathroom - place
	place14_door_room7_corridor - place
	place15_door_room15_staircase - place
	place16_door_room16_staircase - place
	place17_door_room17_staircase - place
	place18_door_room18_staircase - place
	place19_item1_backpack - place
	place1_door_room11_kitchen - place
	place20_item66_tv - place
	place21_item67_tv - place
	place22_item4_bottle - place
	place23_item38_potted_plant - place
	place24_item6_bottle - place
	place25_item40_potted_plant - place
	place26_item41_potted_plant - place
	place27_item42_potted_plant - place
	place28_item43_potted_plant - place
	place29_item15_cup - place
	place2_door_room12_kitchen - place
	place30_item79_book - place
	place31_item81_vase - place
	place32_item50_potted_plant - place
	place33_item82_vase - place
	place34_item83_vase - place
	place35_item53_potted_plant - place
	place36_item84_vase - place
	place37_receptacle23_chair - place
	place38_receptacle24_chair - place
	place39_receptacle25_chair - place
	place3_door_room9_dining_room - place
	place40_receptacle26_chair - place
	place41_receptacle27_chair - place
	place42_receptacle28_chair - place
	place43_receptacle29_chair - place
	place44_receptacle30_chair - place
	place45_receptacle31_chair - place
	place46_receptacle32_chair - place
	place47_receptacle33_chair - place
	place48_receptacle34_chair - place
	place49_receptacle35_chair - place
	place4_door_room13_living_room - place
	place50_receptacle36_couch - place
	place51_receptacle37_couch - place
	place52_receptacle60_bed - place
	place53_receptacle61_bed - place
	place54_receptacle62_dining_table - place
	place55_receptacle63_toilet - place
	place56_receptacle64_toilet - place
	place57_receptacle65_toilet - place
	place58_receptacle68_microwave - place
	place59_receptacle69_oven - place
	place5_door_room5_bedroom - place
	place60_receptacle70_sink - place
	place61_receptacle71_sink - place
	place62_receptacle72_sink - place
	place63_receptacle73_sink - place
	place64_receptacle74_sink - place
	place65_receptacle75_sink - place
	place66_receptacle76_sink - place
	place67_receptacle77_refrigerator - place
	place6_door_room10_home_office - place
	place7_door_room14_living_room - place
	place8_door_room6_bedroom - place
	place9_door_room8_corridor - place
	pottedplant - iclass
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle30_chair - receptacle
	receptacle31_chair - receptacle
	receptacle32_chair - receptacle
	receptacle33_chair - receptacle
	receptacle34_chair - receptacle
	receptacle35_chair - receptacle
	receptacle36_couch - receptacle
	receptacle37_couch - receptacle
	receptacle60_bed - receptacle
	receptacle61_bed - receptacle
	receptacle62_dining_table - receptacle
	receptacle63_toilet - receptacle
	receptacle64_toilet - receptacle
	receptacle65_toilet - receptacle
	receptacle68_microwave - receptacle
	receptacle69_oven - receptacle
	receptacle70_sink - receptacle
	receptacle71_sink - receptacle
	receptacle72_sink - receptacle
	receptacle73_sink - receptacle
	receptacle74_sink - receptacle
	receptacle75_sink - receptacle
	receptacle76_sink - receptacle
	receptacle77_refrigerator - receptacle
	refrigerator - rclass
	remote - iclass
	robot - agent
	room10_home_office - room
	room11_kitchen - room
	room12_kitchen - room
	room13_living_room - room
	room14_living_room - room
	room15_staircase - room
	room16_staircase - room
	room17_staircase - room
	room18_staircase - room
	room19_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bathroom - room
	room5_bedroom - room
	room6_bedroom - room
	room7_corridor - room
	room8_corridor - room
	room9_dining_room - room
	sink - rclass
	spoon - iclass
	sportsball - iclass
	suitcase - iclass
	surfboard - iclass
	teddybear - iclass
	tie - iclass
	toaster - rclass
	toilet - rclass
	toothbrush - iclass
	tv - iclass
	umbrella - iclass
	vase - iclass
	wineglass - iclass
  )
  (:init 
	(atlocation robot location_xneg3_ypos27_place16_room16_floorb)
	(classrelation apple sink)
	(classrelation book chair)
	(classrelation bottle sink)
	(classrelation bowl chair)
	(classrelation bowl oven)
	(classrelation clock couch)
	(classrelation cup sink)
	(classrelation pottedplant chair)
	(classrelation pottedplant couch)
	(classrelation pottedplant diningtable)
	(classrelation pottedplant sink)
	(classrelation vase sink)
	(classrelation wineglass chair)
	(classrelation wineglass oven)
	(inanyreceptacle item10_wine_glass_smallitem)
	(inanyreceptacle item11_wine_glass_smallitem)
	(inanyreceptacle item12_wine_glass_smallitem)
	(inanyreceptacle item13_wine_glass_smallitem)
	(inanyreceptacle item14_wine_glass_smallitem)
	(inanyreceptacle item16_cup_smallitem)
	(inanyreceptacle item17_bowl_smallitem)
	(inanyreceptacle item18_bowl_smallitem)
	(inanyreceptacle item19_bowl_smallitem)
	(inanyreceptacle item20_bowl_smallitem)
	(inanyreceptacle item21_bowl_smallitem)
	(inanyreceptacle item22_apple_smallitem)
	(inanyreceptacle item2_bottle_smallitem)
	(inanyreceptacle item39_potted_plant_largeitem)
	(inanyreceptacle item3_bottle_smallitem)
	(inanyreceptacle item44_potted_plant_largeitem)
	(inanyreceptacle item45_potted_plant_largeitem)
	(inanyreceptacle item46_potted_plant_largeitem)
	(inanyreceptacle item47_potted_plant_largeitem)
	(inanyreceptacle item48_potted_plant_largeitem)
	(inanyreceptacle item49_potted_plant_largeitem)
	(inanyreceptacle item51_potted_plant_largeitem)
	(inanyreceptacle item52_potted_plant_largeitem)
	(inanyreceptacle item54_potted_plant_largeitem)
	(inanyreceptacle item55_potted_plant_largeitem)
	(inanyreceptacle item56_potted_plant_largeitem)
	(inanyreceptacle item57_potted_plant_largeitem)
	(inanyreceptacle item58_potted_plant_largeitem)
	(inanyreceptacle item59_potted_plant_largeitem)
	(inanyreceptacle item5_bottle_smallitem)
	(inanyreceptacle item78_book_smallitem)
	(inanyreceptacle item7_bottle_smallitem)
	(inanyreceptacle item80_clock_mediumitem)
	(inanyreceptacle item85_vase_mediumitem)
	(inanyreceptacle item86_vase_mediumitem)
	(inanyreceptacle item8_bottle_smallitem)
	(inanyreceptacle item9_wine_glass_smallitem)
	(inplace robot place16_door_room16_staircase)
	(inreceptacle item10_wine_glass_smallitem receptacle69_oven)
	(inreceptacle item11_wine_glass_smallitem receptacle69_oven)
	(inreceptacle item12_wine_glass_smallitem receptacle69_oven)
	(inreceptacle item13_wine_glass_smallitem receptacle69_oven)
	(inreceptacle item14_wine_glass_smallitem receptacle28_chair)
	(inreceptacle item16_cup_smallitem receptacle76_sink)
	(inreceptacle item17_bowl_smallitem receptacle27_chair)
	(inreceptacle item18_bowl_smallitem receptacle69_oven)
	(inreceptacle item19_bowl_smallitem receptacle69_oven)
	(inreceptacle item20_bowl_smallitem receptacle69_oven)
	(inreceptacle item21_bowl_smallitem receptacle69_oven)
	(inreceptacle item22_apple_smallitem receptacle74_sink)
	(inreceptacle item2_bottle_smallitem receptacle71_sink)
	(inreceptacle item39_potted_plant_largeitem receptacle70_sink)
	(inreceptacle item3_bottle_smallitem receptacle71_sink)
	(inreceptacle item44_potted_plant_largeitem receptacle71_sink)
	(inreceptacle item45_potted_plant_largeitem receptacle27_chair)
	(inreceptacle item46_potted_plant_largeitem receptacle27_chair)
	(inreceptacle item47_potted_plant_largeitem receptacle62_dining_table)
	(inreceptacle item48_potted_plant_largeitem receptacle74_sink)
	(inreceptacle item49_potted_plant_largeitem receptacle33_chair)
	(inreceptacle item51_potted_plant_largeitem receptacle34_chair)
	(inreceptacle item52_potted_plant_largeitem receptacle34_chair)
	(inreceptacle item54_potted_plant_largeitem receptacle36_couch)
	(inreceptacle item55_potted_plant_largeitem receptacle75_sink)
	(inreceptacle item56_potted_plant_largeitem receptacle76_sink)
	(inreceptacle item57_potted_plant_largeitem receptacle76_sink)
	(inreceptacle item58_potted_plant_largeitem receptacle76_sink)
	(inreceptacle item59_potted_plant_largeitem receptacle76_sink)
	(inreceptacle item5_bottle_smallitem receptacle71_sink)
	(inreceptacle item78_book_smallitem receptacle25_chair)
	(inreceptacle item7_bottle_smallitem receptacle76_sink)
	(inreceptacle item80_clock_mediumitem receptacle36_couch)
	(inreceptacle item85_vase_mediumitem receptacle75_sink)
	(inreceptacle item86_vase_mediumitem receptacle73_sink)
	(inreceptacle item8_bottle_smallitem receptacle76_sink)
	(inreceptacle item9_wine_glass_smallitem receptacle69_oven)
	(inroom robot room16_staircase)
	(itematlocation item10_wine_glass_smallitem location_xpos16_ypos72_place59_room12_floorc)
	(itematlocation item11_wine_glass_smallitem location_xpos18_ypos76_place59_room12_floorc)
	(itematlocation item12_wine_glass_smallitem location_xpos17_ypos68_place59_room12_floorc)
	(itematlocation item13_wine_glass_smallitem location_xpos16_ypos73_place59_room12_floorc)
	(itematlocation item14_wine_glass_smallitem location_xneg11_ypos44_place42_room9_floorc)
	(itematlocation item15_cup_smallitem location_xpos9_ypos69_place29_room19_floorb)
	(itematlocation item16_cup_smallitem location_xpos38_ypos58_place66_room19_floorb)
	(itematlocation item17_bowl_smallitem location_xpos32_ypos16_place41_room13_floora)
	(itematlocation item18_bowl_smallitem location_xpos19_ypos69_place59_room12_floorc)
	(itematlocation item19_bowl_smallitem location_xpos18_ypos69_place59_room12_floorc)
	(itematlocation item1_backpack_largeitem location_xneg6_ypos45_place19_room19_floorb)
	(itematlocation item20_bowl_smallitem location_xpos19_ypos69_place59_room12_floorc)
	(itematlocation item21_bowl_smallitem location_xpos17_ypos68_place59_room12_floorc)
	(itematlocation item22_apple_smallitem location_xpos27_ypos77_place64_room12_floorc)
	(itematlocation item2_bottle_smallitem location_xpos30_ypos40_place61_room11_floora)
	(itematlocation item38_potted_plant_largeitem location_xpos19_ypos27_place23_room8_floord)
	(itematlocation item39_potted_plant_largeitem location_xpos27_ypos45_place60_room2_floorc)
	(itematlocation item3_bottle_smallitem location_xpos29_ypos41_place61_room11_floora)
	(itematlocation item40_potted_plant_largeitem location_xpos39_yneg12_place25_room13_floora)
	(itematlocation item41_potted_plant_largeitem location_xpos36_yneg11_place26_room13_floora)
	(itematlocation item42_potted_plant_largeitem location_xpos37_yneg11_place27_room13_floora)
	(itematlocation item43_potted_plant_largeitem location_xpos35_yneg16_place28_room13_floora)
	(itematlocation item44_potted_plant_largeitem location_xpos31_ypos33_place61_room11_floora)
	(itematlocation item45_potted_plant_largeitem location_xpos37_ypos10_place41_room13_floora)
	(itematlocation item46_potted_plant_largeitem location_xpos25_ypos28_place41_room13_floora)
	(itematlocation item47_potted_plant_largeitem location_xneg6_ypos63_place54_room9_floorc)
	(itematlocation item48_potted_plant_largeitem location_xpos41_ypos77_place64_room12_floorc)
	(itematlocation item49_potted_plant_largeitem location_xneg11_yneg10_place47_room14_floorc)
	(itematlocation item4_bottle_smallitem location_xneg11_ypos46_place22_room19_floorb)
	(itematlocation item50_potted_plant_largeitem location_xpos26_ypos27_place32_room14_floorc)
	(itematlocation item51_potted_plant_largeitem location_xneg13_yneg17_place48_room6_floord)
	(itematlocation item52_potted_plant_largeitem location_xneg16_yneg19_place48_room6_floord)
	(itematlocation item53_potted_plant_largeitem location_xneg14_ypos3_place35_room13_floora)
	(itematlocation item54_potted_plant_largeitem location_xpos38_yneg11_place50_room13_floora)
	(itematlocation item55_potted_plant_largeitem location_xpos22_ypos71_place65_room1_floora)
	(itematlocation item56_potted_plant_largeitem location_xpos40_ypos75_place66_room19_floorb)
	(itematlocation item57_potted_plant_largeitem location_xpos41_ypos78_place66_room19_floorb)
	(itematlocation item58_potted_plant_largeitem location_xpos41_ypos75_place66_room19_floorb)
	(itematlocation item59_potted_plant_largeitem location_xpos41_ypos77_place66_room19_floorb)
	(itematlocation item5_bottle_smallitem location_xpos30_ypos36_place61_room11_floora)
	(itematlocation item66_tv_largeitem location_xneg5_ypos4_place20_room14_floorc)
	(itematlocation item67_tv_largeitem location_xpos0_ypos12_place21_room6_floord)
	(itematlocation item6_bottle_smallitem location_xpos9_ypos68_place24_room19_floorb)
	(itematlocation item78_book_smallitem location_xneg14_ypos61_place39_room10_floord)
	(itematlocation item79_book_smallitem location_xneg14_ypos69_place30_room10_floord)
	(itematlocation item7_bottle_smallitem location_xpos42_ypos72_place66_room19_floorb)
	(itematlocation item80_clock_mediumitem location_xpos36_yneg11_place50_room13_floora)
	(itematlocation item81_vase_mediumitem location_xpos39_ypos27_place31_room14_floorc)
	(itematlocation item82_vase_mediumitem location_xpos40_ypos16_place33_room14_floorc)
	(itematlocation item83_vase_mediumitem location_xpos17_ypos50_place34_room9_floorc)
	(itematlocation item84_vase_mediumitem location_xpos17_ypos49_place36_room9_floorc)
	(itematlocation item85_vase_mediumitem location_xpos23_ypos70_place65_room1_floora)
	(itematlocation item86_vase_mediumitem location_xpos23_ypos17_place63_room3_floord)
	(itematlocation item8_bottle_smallitem location_xpos40_ypos77_place66_room19_floorb)
	(itematlocation item9_wine_glass_smallitem location_xpos19_ypos72_place59_room12_floorc)
	(itemclass item10_wine_glass_smallitem wineglass)
	(itemclass item11_wine_glass_smallitem wineglass)
	(itemclass item12_wine_glass_smallitem wineglass)
	(itemclass item13_wine_glass_smallitem wineglass)
	(itemclass item14_wine_glass_smallitem wineglass)
	(itemclass item15_cup_smallitem cup)
	(itemclass item16_cup_smallitem cup)
	(itemclass item17_bowl_smallitem bowl)
	(itemclass item18_bowl_smallitem bowl)
	(itemclass item19_bowl_smallitem bowl)
	(itemclass item1_backpack_largeitem backpack)
	(itemclass item20_bowl_smallitem bowl)
	(itemclass item21_bowl_smallitem bowl)
	(itemclass item22_apple_smallitem apple)
	(itemclass item2_bottle_smallitem bottle)
	(itemclass item38_potted_plant_largeitem pottedplant)
	(itemclass item39_potted_plant_largeitem pottedplant)
	(itemclass item3_bottle_smallitem bottle)
	(itemclass item40_potted_plant_largeitem pottedplant)
	(itemclass item41_potted_plant_largeitem pottedplant)
	(itemclass item42_potted_plant_largeitem pottedplant)
	(itemclass item43_potted_plant_largeitem pottedplant)
	(itemclass item44_potted_plant_largeitem pottedplant)
	(itemclass item45_potted_plant_largeitem pottedplant)
	(itemclass item46_potted_plant_largeitem pottedplant)
	(itemclass item47_potted_plant_largeitem pottedplant)
	(itemclass item48_potted_plant_largeitem pottedplant)
	(itemclass item49_potted_plant_largeitem pottedplant)
	(itemclass item4_bottle_smallitem bottle)
	(itemclass item50_potted_plant_largeitem pottedplant)
	(itemclass item51_potted_plant_largeitem pottedplant)
	(itemclass item52_potted_plant_largeitem pottedplant)
	(itemclass item53_potted_plant_largeitem pottedplant)
	(itemclass item54_potted_plant_largeitem pottedplant)
	(itemclass item55_potted_plant_largeitem pottedplant)
	(itemclass item56_potted_plant_largeitem pottedplant)
	(itemclass item57_potted_plant_largeitem pottedplant)
	(itemclass item58_potted_plant_largeitem pottedplant)
	(itemclass item59_potted_plant_largeitem pottedplant)
	(itemclass item5_bottle_smallitem bottle)
	(itemclass item66_tv_largeitem tv)
	(itemclass item67_tv_largeitem tv)
	(itemclass item6_bottle_smallitem bottle)
	(itemclass item78_book_smallitem book)
	(itemclass item79_book_smallitem book)
	(itemclass item7_bottle_smallitem bottle)
	(itemclass item80_clock_mediumitem clock)
	(itemclass item81_vase_mediumitem vase)
	(itemclass item82_vase_mediumitem vase)
	(itemclass item83_vase_mediumitem vase)
	(itemclass item84_vase_mediumitem vase)
	(itemclass item85_vase_mediumitem vase)
	(itemclass item86_vase_mediumitem vase)
	(itemclass item8_bottle_smallitem bottle)
	(itemclass item9_wine_glass_smallitem wineglass)
	(locationinplace location_xneg11_yneg10_place47_room14_floorc place47_receptacle33_chair)
	(locationinplace location_xneg11_ypos44_place42_room9_floorc place42_receptacle28_chair)
	(locationinplace location_xneg11_ypos46_place22_room19_floorb place22_item4_bottle)
	(locationinplace location_xneg13_yneg17_place48_room6_floord place48_receptacle34_chair)
	(locationinplace location_xneg13_ypos64_place45_room9_floorc place45_receptacle31_chair)
	(locationinplace location_xneg14_yneg6_place48_room6_floord place48_receptacle34_chair)
	(locationinplace location_xneg14_ypos3_place35_room13_floora place35_item53_potted_plant)
	(locationinplace location_xneg14_ypos61_place39_room10_floord place39_receptacle25_chair)
	(locationinplace location_xneg14_ypos69_place30_room10_floord place30_item79_book)
	(locationinplace location_xneg16_yneg19_place48_room6_floord place48_receptacle34_chair)
	(locationinplace location_xneg3_ypos27_place15_room15_floora place15_door_room15_staircase)
	(locationinplace location_xneg3_ypos27_place16_room16_floorb place16_door_room16_staircase)
	(locationinplace location_xneg3_ypos28_place17_room17_floorc place17_door_room17_staircase)
	(locationinplace location_xneg3_ypos28_place18_room18_floord place18_door_room18_staircase)
	(locationinplace location_xneg4_ypos60_place52_room5_floora place52_receptacle60_bed)
	(locationinplace location_xneg5_ypos4_place20_room14_floorc place20_item66_tv)
	(locationinplace location_xneg5_ypos58_place42_room9_floorc place42_receptacle28_chair)
	(locationinplace location_xneg5_ypos63_place54_room9_floorc place54_receptacle62_dining_table)
	(locationinplace location_xneg5_ypos68_place43_room9_floorc place43_receptacle29_chair)
	(locationinplace location_xneg6_yneg15_place47_room14_floorc place47_receptacle33_chair)
	(locationinplace location_xneg6_ypos45_place19_room19_floorb place19_item1_backpack)
	(locationinplace location_xneg6_ypos50_place39_room10_floord place39_receptacle25_chair)
	(locationinplace location_xneg6_ypos63_place54_room9_floorc place54_receptacle62_dining_table)
	(locationinplace location_xneg9_ypos68_place44_room9_floorc place44_receptacle30_chair)
	(locationinplace location_xpos0_ypos12_place21_room6_floord place21_item67_tv)
	(locationinplace location_xpos0_ypos64_place46_room9_floorc place46_receptacle32_chair)
	(locationinplace location_xpos10_ypos28_place9_room8_floord place9_door_room8_corridor)
	(locationinplace location_xpos10_ypos73_place40_room10_floord place40_receptacle26_chair)
	(locationinplace location_xpos13_yneg5_place8_room6_floord place8_door_room6_bedroom)
	(locationinplace location_xpos13_ypos2_place7_room14_floorc place7_door_room14_living_room)
	(locationinplace location_xpos14_ypos5_place4_room13_floora place4_door_room13_living_room)
	(locationinplace location_xpos15_yneg11_place53_room6_floord place53_receptacle61_bed)
	(locationinplace location_xpos15_ypos56_place0_room19_floorb place0_door_room19_utility_room)
	(locationinplace location_xpos16_ypos72_place59_room12_floorc place59_receptacle69_oven)
	(locationinplace location_xpos16_ypos73_place59_room12_floorc place59_receptacle69_oven)
	(locationinplace location_xpos17_ypos49_place36_room9_floorc place36_item84_vase)
	(locationinplace location_xpos17_ypos50_place34_room9_floorc place34_item83_vase)
	(locationinplace location_xpos17_ypos68_place59_room12_floorc place59_receptacle69_oven)
	(locationinplace location_xpos18_ypos69_place38_room5_floora place38_receptacle24_chair)
	(locationinplace location_xpos18_ypos69_place59_room12_floorc place59_receptacle69_oven)
	(locationinplace location_xpos18_ypos76_place59_room12_floorc place59_receptacle69_oven)
	(locationinplace location_xpos19_ypos27_place23_room8_floord place23_item38_potted_plant)
	(locationinplace location_xpos19_ypos69_place59_room12_floorc place59_receptacle69_oven)
	(locationinplace location_xpos19_ypos72_place59_room12_floorc place59_receptacle69_oven)
	(locationinplace location_xpos1_ypos60_place3_room9_floorc place3_door_room9_dining_room)
	(locationinplace location_xpos21_ypos48_place37_room19_floorb place37_receptacle23_chair)
	(locationinplace location_xpos22_ypos71_place65_room1_floora place65_receptacle75_sink)
	(locationinplace location_xpos23_ypos17_place63_room3_floord place63_receptacle73_sink)
	(locationinplace location_xpos23_ypos70_place65_room1_floora place65_receptacle75_sink)
	(locationinplace location_xpos24_yneg3_place50_room13_floora place50_receptacle36_couch)
	(locationinplace location_xpos24_ypos23_place63_room3_floord place63_receptacle73_sink)
	(locationinplace location_xpos24_ypos66_place65_room1_floora place65_receptacle75_sink)
	(locationinplace location_xpos24_ypos68_place59_room12_floorc place59_receptacle69_oven)
	(locationinplace location_xpos25_ypos28_place41_room13_floora place41_receptacle27_chair)
	(locationinplace location_xpos26_ypos27_place32_room14_floorc place32_item50_potted_plant)
	(locationinplace location_xpos26_ypos51_place67_room12_floorc place67_receptacle77_refrigerator)
	(locationinplace location_xpos27_ypos45_place60_room2_floorc place60_receptacle70_sink)
	(locationinplace location_xpos27_ypos77_place64_room12_floorc place64_receptacle74_sink)
	(locationinplace location_xpos28_yneg6_place51_room14_floorc place51_receptacle37_couch)
	(locationinplace location_xpos29_ypos41_place61_room11_floora place61_receptacle71_sink)
	(locationinplace location_xpos30_ypos24_place41_room13_floora place41_receptacle27_chair)
	(locationinplace location_xpos30_ypos36_place61_room11_floora place61_receptacle71_sink)
	(locationinplace location_xpos30_ypos40_place61_room11_floora place61_receptacle71_sink)
	(locationinplace location_xpos30_ypos43_place60_room2_floorc place60_receptacle70_sink)
	(locationinplace location_xpos30_ypos63_place2_room12_floorc place2_door_room12_kitchen)
	(locationinplace location_xpos31_ypos33_place61_room11_floora place61_receptacle71_sink)
	(locationinplace location_xpos32_ypos16_place41_room13_floora place41_receptacle27_chair)
	(locationinplace location_xpos32_ypos32_place13_room3_floord place13_door_room3_bathroom)
	(locationinplace location_xpos32_ypos38_place10_room2_floorc place10_door_room2_bathroom)
	(locationinplace location_xpos32_ypos55_place12_room4_floord place12_door_room4_bathroom)
	(locationinplace location_xpos33_ypos41_place61_room11_floora place61_receptacle71_sink)
	(locationinplace location_xpos33_ypos59_place11_room1_floora place11_door_room1_bathroom)
	(locationinplace location_xpos35_yneg16_place28_room13_floora place28_item43_potted_plant)
	(locationinplace location_xpos36_yneg11_place26_room13_floora place26_item41_potted_plant)
	(locationinplace location_xpos36_yneg11_place50_room13_floora place50_receptacle36_couch)
	(locationinplace location_xpos36_ypos39_place1_room11_floora place1_door_room11_kitchen)
	(locationinplace location_xpos36_ypos52_place58_room12_floorc place58_receptacle68_microwave)
	(locationinplace location_xpos36_ypos72_place64_room12_floorc place64_receptacle74_sink)
	(locationinplace location_xpos37_yneg11_place27_room13_floora place27_item42_potted_plant)
	(locationinplace location_xpos37_ypos10_place41_room13_floora place41_receptacle27_chair)
	(locationinplace location_xpos38_yneg11_place50_room13_floora place50_receptacle36_couch)
	(locationinplace location_xpos38_ypos41_place57_room2_floorc place57_receptacle65_toilet)
	(locationinplace location_xpos38_ypos58_place66_room19_floorb place66_receptacle76_sink)
	(locationinplace location_xpos39_yneg12_place25_room13_floora place25_item40_potted_plant)
	(locationinplace location_xpos39_ypos27_place31_room14_floorc place31_item81_vase)
	(locationinplace location_xpos39_ypos55_place56_room4_floord place56_receptacle64_toilet)
	(locationinplace location_xpos39_ypos67_place55_room1_floora place55_receptacle63_toilet)
	(locationinplace location_xpos39_ypos69_place66_room19_floorb place66_receptacle76_sink)
	(locationinplace location_xpos40_ypos16_place33_room14_floorc place33_item82_vase)
	(locationinplace location_xpos40_ypos23_place62_room3_floord place62_receptacle72_sink)
	(locationinplace location_xpos40_ypos2_place49_room6_floord place49_receptacle35_chair)
	(locationinplace location_xpos40_ypos75_place66_room19_floorb place66_receptacle76_sink)
	(locationinplace location_xpos40_ypos77_place66_room19_floorb place66_receptacle76_sink)
	(locationinplace location_xpos41_ypos75_place66_room19_floorb place66_receptacle76_sink)
	(locationinplace location_xpos41_ypos77_place64_room12_floorc place64_receptacle74_sink)
	(locationinplace location_xpos41_ypos77_place66_room19_floorb place66_receptacle76_sink)
	(locationinplace location_xpos41_ypos78_place66_room19_floorb place66_receptacle76_sink)
	(locationinplace location_xpos42_ypos72_place66_room19_floorb place66_receptacle76_sink)
	(locationinplace location_xpos4_ypos51_place5_room5_floora place5_door_room5_bedroom)
	(locationinplace location_xpos8_ypos27_place14_room7_floorc place14_door_room7_corridor)
	(locationinplace location_xpos8_ypos60_place6_room10_floord place6_door_room10_home_office)
	(locationinplace location_xpos9_ypos68_place24_room19_floorb place24_item6_bottle)
	(locationinplace location_xpos9_ypos69_place29_room19_floorb place29_item15_cup)
	(placeinroom place0_door_room19_utility_room room19_utility_room)
	(placeinroom place10_door_room2_bathroom room2_bathroom)
	(placeinroom place11_door_room1_bathroom room1_bathroom)
	(placeinroom place12_door_room4_bathroom room4_bathroom)
	(placeinroom place13_door_room3_bathroom room3_bathroom)
	(placeinroom place14_door_room7_corridor room7_corridor)
	(placeinroom place15_door_room15_staircase room15_staircase)
	(placeinroom place16_door_room16_staircase room16_staircase)
	(placeinroom place17_door_room17_staircase room17_staircase)
	(placeinroom place18_door_room18_staircase room18_staircase)
	(placeinroom place19_item1_backpack room19_utility_room)
	(placeinroom place1_door_room11_kitchen room11_kitchen)
	(placeinroom place20_item66_tv room14_living_room)
	(placeinroom place21_item67_tv room6_bedroom)
	(placeinroom place22_item4_bottle room19_utility_room)
	(placeinroom place23_item38_potted_plant room8_corridor)
	(placeinroom place24_item6_bottle room19_utility_room)
	(placeinroom place25_item40_potted_plant room13_living_room)
	(placeinroom place26_item41_potted_plant room13_living_room)
	(placeinroom place27_item42_potted_plant room13_living_room)
	(placeinroom place28_item43_potted_plant room13_living_room)
	(placeinroom place29_item15_cup room19_utility_room)
	(placeinroom place2_door_room12_kitchen room12_kitchen)
	(placeinroom place30_item79_book room10_home_office)
	(placeinroom place31_item81_vase room14_living_room)
	(placeinroom place32_item50_potted_plant room14_living_room)
	(placeinroom place33_item82_vase room14_living_room)
	(placeinroom place34_item83_vase room9_dining_room)
	(placeinroom place35_item53_potted_plant room13_living_room)
	(placeinroom place36_item84_vase room9_dining_room)
	(placeinroom place37_receptacle23_chair room19_utility_room)
	(placeinroom place38_receptacle24_chair room5_bedroom)
	(placeinroom place39_receptacle25_chair room10_home_office)
	(placeinroom place3_door_room9_dining_room room9_dining_room)
	(placeinroom place40_receptacle26_chair room10_home_office)
	(placeinroom place41_receptacle27_chair room13_living_room)
	(placeinroom place42_receptacle28_chair room9_dining_room)
	(placeinroom place43_receptacle29_chair room9_dining_room)
	(placeinroom place44_receptacle30_chair room9_dining_room)
	(placeinroom place45_receptacle31_chair room9_dining_room)
	(placeinroom place46_receptacle32_chair room9_dining_room)
	(placeinroom place47_receptacle33_chair room14_living_room)
	(placeinroom place48_receptacle34_chair room6_bedroom)
	(placeinroom place49_receptacle35_chair room6_bedroom)
	(placeinroom place4_door_room13_living_room room13_living_room)
	(placeinroom place50_receptacle36_couch room13_living_room)
	(placeinroom place51_receptacle37_couch room14_living_room)
	(placeinroom place52_receptacle60_bed room5_bedroom)
	(placeinroom place53_receptacle61_bed room6_bedroom)
	(placeinroom place54_receptacle62_dining_table room9_dining_room)
	(placeinroom place55_receptacle63_toilet room1_bathroom)
	(placeinroom place56_receptacle64_toilet room4_bathroom)
	(placeinroom place57_receptacle65_toilet room2_bathroom)
	(placeinroom place58_receptacle68_microwave room12_kitchen)
	(placeinroom place59_receptacle69_oven room12_kitchen)
	(placeinroom place5_door_room5_bedroom room5_bedroom)
	(placeinroom place60_receptacle70_sink room2_bathroom)
	(placeinroom place61_receptacle71_sink room11_kitchen)
	(placeinroom place62_receptacle72_sink room3_bathroom)
	(placeinroom place63_receptacle73_sink room3_bathroom)
	(placeinroom place64_receptacle74_sink room12_kitchen)
	(placeinroom place65_receptacle75_sink room1_bathroom)
	(placeinroom place66_receptacle76_sink room19_utility_room)
	(placeinroom place67_receptacle77_refrigerator room12_kitchen)
	(placeinroom place6_door_room10_home_office room10_home_office)
	(placeinroom place7_door_room14_living_room room14_living_room)
	(placeinroom place8_door_room6_bedroom room6_bedroom)
	(placeinroom place9_door_room8_corridor room8_corridor)
	(placelocation location_xneg11_ypos46_place22_room19_floorb place22_item4_bottle)
	(placelocation location_xneg13_ypos64_place45_room9_floorc place45_receptacle31_chair)
	(placelocation location_xneg14_yneg6_place48_room6_floord place48_receptacle34_chair)
	(placelocation location_xneg14_ypos3_place35_room13_floora place35_item53_potted_plant)
	(placelocation location_xneg14_ypos69_place30_room10_floord place30_item79_book)
	(placelocation location_xneg3_ypos27_place15_room15_floora place15_door_room15_staircase)
	(placelocation location_xneg3_ypos27_place16_room16_floorb place16_door_room16_staircase)
	(placelocation location_xneg3_ypos28_place17_room17_floorc place17_door_room17_staircase)
	(placelocation location_xneg3_ypos28_place18_room18_floord place18_door_room18_staircase)
	(placelocation location_xneg4_ypos60_place52_room5_floora place52_receptacle60_bed)
	(placelocation location_xneg5_ypos4_place20_room14_floorc place20_item66_tv)
	(placelocation location_xneg5_ypos58_place42_room9_floorc place42_receptacle28_chair)
	(placelocation location_xneg5_ypos63_place54_room9_floorc place54_receptacle62_dining_table)
	(placelocation location_xneg5_ypos68_place43_room9_floorc place43_receptacle29_chair)
	(placelocation location_xneg6_yneg15_place47_room14_floorc place47_receptacle33_chair)
	(placelocation location_xneg6_ypos45_place19_room19_floorb place19_item1_backpack)
	(placelocation location_xneg6_ypos50_place39_room10_floord place39_receptacle25_chair)
	(placelocation location_xneg9_ypos68_place44_room9_floorc place44_receptacle30_chair)
	(placelocation location_xpos0_ypos12_place21_room6_floord place21_item67_tv)
	(placelocation location_xpos0_ypos64_place46_room9_floorc place46_receptacle32_chair)
	(placelocation location_xpos10_ypos28_place9_room8_floord place9_door_room8_corridor)
	(placelocation location_xpos10_ypos73_place40_room10_floord place40_receptacle26_chair)
	(placelocation location_xpos13_yneg5_place8_room6_floord place8_door_room6_bedroom)
	(placelocation location_xpos13_ypos2_place7_room14_floorc place7_door_room14_living_room)
	(placelocation location_xpos14_ypos5_place4_room13_floora place4_door_room13_living_room)
	(placelocation location_xpos15_yneg11_place53_room6_floord place53_receptacle61_bed)
	(placelocation location_xpos15_ypos56_place0_room19_floorb place0_door_room19_utility_room)
	(placelocation location_xpos17_ypos49_place36_room9_floorc place36_item84_vase)
	(placelocation location_xpos17_ypos50_place34_room9_floorc place34_item83_vase)
	(placelocation location_xpos18_ypos69_place38_room5_floora place38_receptacle24_chair)
	(placelocation location_xpos19_ypos27_place23_room8_floord place23_item38_potted_plant)
	(placelocation location_xpos1_ypos60_place3_room9_floorc place3_door_room9_dining_room)
	(placelocation location_xpos21_ypos48_place37_room19_floorb place37_receptacle23_chair)
	(placelocation location_xpos24_yneg3_place50_room13_floora place50_receptacle36_couch)
	(placelocation location_xpos24_ypos23_place63_room3_floord place63_receptacle73_sink)
	(placelocation location_xpos24_ypos66_place65_room1_floora place65_receptacle75_sink)
	(placelocation location_xpos24_ypos68_place59_room12_floorc place59_receptacle69_oven)
	(placelocation location_xpos26_ypos27_place32_room14_floorc place32_item50_potted_plant)
	(placelocation location_xpos26_ypos51_place67_room12_floorc place67_receptacle77_refrigerator)
	(placelocation location_xpos28_yneg6_place51_room14_floorc place51_receptacle37_couch)
	(placelocation location_xpos30_ypos24_place41_room13_floora place41_receptacle27_chair)
	(placelocation location_xpos30_ypos43_place60_room2_floorc place60_receptacle70_sink)
	(placelocation location_xpos30_ypos63_place2_room12_floorc place2_door_room12_kitchen)
	(placelocation location_xpos32_ypos32_place13_room3_floord place13_door_room3_bathroom)
	(placelocation location_xpos32_ypos38_place10_room2_floorc place10_door_room2_bathroom)
	(placelocation location_xpos32_ypos55_place12_room4_floord place12_door_room4_bathroom)
	(placelocation location_xpos33_ypos41_place61_room11_floora place61_receptacle71_sink)
	(placelocation location_xpos33_ypos59_place11_room1_floora place11_door_room1_bathroom)
	(placelocation location_xpos35_yneg16_place28_room13_floora place28_item43_potted_plant)
	(placelocation location_xpos36_yneg11_place26_room13_floora place26_item41_potted_plant)
	(placelocation location_xpos36_ypos39_place1_room11_floora place1_door_room11_kitchen)
	(placelocation location_xpos36_ypos52_place58_room12_floorc place58_receptacle68_microwave)
	(placelocation location_xpos36_ypos72_place64_room12_floorc place64_receptacle74_sink)
	(placelocation location_xpos37_yneg11_place27_room13_floora place27_item42_potted_plant)
	(placelocation location_xpos38_ypos41_place57_room2_floorc place57_receptacle65_toilet)
	(placelocation location_xpos39_yneg12_place25_room13_floora place25_item40_potted_plant)
	(placelocation location_xpos39_ypos27_place31_room14_floorc place31_item81_vase)
	(placelocation location_xpos39_ypos55_place56_room4_floord place56_receptacle64_toilet)
	(placelocation location_xpos39_ypos67_place55_room1_floora place55_receptacle63_toilet)
	(placelocation location_xpos39_ypos69_place66_room19_floorb place66_receptacle76_sink)
	(placelocation location_xpos40_ypos16_place33_room14_floorc place33_item82_vase)
	(placelocation location_xpos40_ypos23_place62_room3_floord place62_receptacle72_sink)
	(placelocation location_xpos40_ypos2_place49_room6_floord place49_receptacle35_chair)
	(placelocation location_xpos4_ypos51_place5_room5_floora place5_door_room5_bedroom)
	(placelocation location_xpos8_ypos27_place14_room7_floorc place14_door_room7_corridor)
	(placelocation location_xpos8_ypos60_place6_room10_floord place6_door_room10_home_office)
	(placelocation location_xpos9_ypos68_place24_room19_floorb place24_item6_bottle)
	(placelocation location_xpos9_ypos69_place29_room19_floorb place29_item15_cup)
	(receptacleatlocation receptacle23_chair location_xpos21_ypos48_place37_room19_floorb)
	(receptacleatlocation receptacle24_chair location_xpos18_ypos69_place38_room5_floora)
	(receptacleatlocation receptacle25_chair location_xneg6_ypos50_place39_room10_floord)
	(receptacleatlocation receptacle26_chair location_xpos10_ypos73_place40_room10_floord)
	(receptacleatlocation receptacle27_chair location_xpos30_ypos24_place41_room13_floora)
	(receptacleatlocation receptacle28_chair location_xneg5_ypos58_place42_room9_floorc)
	(receptacleatlocation receptacle29_chair location_xneg5_ypos68_place43_room9_floorc)
	(receptacleatlocation receptacle30_chair location_xneg9_ypos68_place44_room9_floorc)
	(receptacleatlocation receptacle31_chair location_xneg13_ypos64_place45_room9_floorc)
	(receptacleatlocation receptacle32_chair location_xpos0_ypos64_place46_room9_floorc)
	(receptacleatlocation receptacle33_chair location_xneg6_yneg15_place47_room14_floorc)
	(receptacleatlocation receptacle34_chair location_xneg14_yneg6_place48_room6_floord)
	(receptacleatlocation receptacle35_chair location_xpos40_ypos2_place49_room6_floord)
	(receptacleatlocation receptacle36_couch location_xpos24_yneg3_place50_room13_floora)
	(receptacleatlocation receptacle37_couch location_xpos28_yneg6_place51_room14_floorc)
	(receptacleatlocation receptacle60_bed location_xneg4_ypos60_place52_room5_floora)
	(receptacleatlocation receptacle61_bed location_xpos15_yneg11_place53_room6_floord)
	(receptacleatlocation receptacle62_dining_table location_xneg5_ypos63_place54_room9_floorc)
	(receptacleatlocation receptacle63_toilet location_xpos39_ypos67_place55_room1_floora)
	(receptacleatlocation receptacle64_toilet location_xpos39_ypos55_place56_room4_floord)
	(receptacleatlocation receptacle65_toilet location_xpos38_ypos41_place57_room2_floorc)
	(receptacleatlocation receptacle68_microwave location_xpos36_ypos52_place58_room12_floorc)
	(receptacleatlocation receptacle69_oven location_xpos24_ypos68_place59_room12_floorc)
	(receptacleatlocation receptacle70_sink location_xpos30_ypos43_place60_room2_floorc)
	(receptacleatlocation receptacle71_sink location_xpos33_ypos41_place61_room11_floora)
	(receptacleatlocation receptacle72_sink location_xpos40_ypos23_place62_room3_floord)
	(receptacleatlocation receptacle73_sink location_xpos24_ypos23_place63_room3_floord)
	(receptacleatlocation receptacle74_sink location_xpos36_ypos72_place64_room12_floorc)
	(receptacleatlocation receptacle75_sink location_xpos24_ypos66_place65_room1_floora)
	(receptacleatlocation receptacle76_sink location_xpos39_ypos69_place66_room19_floorb)
	(receptacleatlocation receptacle77_refrigerator location_xpos26_ypos51_place67_room12_floorc)
	(receptacleclass receptacle23_chair chair)
	(receptacleclass receptacle24_chair chair)
	(receptacleclass receptacle25_chair chair)
	(receptacleclass receptacle26_chair chair)
	(receptacleclass receptacle27_chair chair)
	(receptacleclass receptacle28_chair chair)
	(receptacleclass receptacle29_chair chair)
	(receptacleclass receptacle30_chair chair)
	(receptacleclass receptacle31_chair chair)
	(receptacleclass receptacle32_chair chair)
	(receptacleclass receptacle33_chair chair)
	(receptacleclass receptacle34_chair chair)
	(receptacleclass receptacle35_chair chair)
	(receptacleclass receptacle36_couch couch)
	(receptacleclass receptacle37_couch couch)
	(receptacleclass receptacle60_bed bed)
	(receptacleclass receptacle61_bed bed)
	(receptacleclass receptacle62_dining_table diningtable)
	(receptacleclass receptacle63_toilet toilet)
	(receptacleclass receptacle64_toilet toilet)
	(receptacleclass receptacle65_toilet toilet)
	(receptacleclass receptacle68_microwave microwave)
	(receptacleclass receptacle69_oven oven)
	(receptacleclass receptacle70_sink sink)
	(receptacleclass receptacle71_sink sink)
	(receptacleclass receptacle72_sink sink)
	(receptacleclass receptacle73_sink sink)
	(receptacleclass receptacle74_sink sink)
	(receptacleclass receptacle75_sink sink)
	(receptacleclass receptacle76_sink sink)
	(receptacleclass receptacle77_refrigerator refrigerator)
	(receptacleopeningtype receptacle68_microwave)
	(receptacleopeningtype receptacle69_oven)
	(receptacleopeningtype receptacle77_refrigerator)
	(roomplace place0_door_room19_utility_room room19_utility_room)
	(roomplace place10_door_room2_bathroom room2_bathroom)
	(roomplace place11_door_room1_bathroom room1_bathroom)
	(roomplace place12_door_room4_bathroom room4_bathroom)
	(roomplace place13_door_room3_bathroom room3_bathroom)
	(roomplace place14_door_room7_corridor room7_corridor)
	(roomplace place15_door_room15_staircase room15_staircase)
	(roomplace place16_door_room16_staircase room16_staircase)
	(roomplace place17_door_room17_staircase room17_staircase)
	(roomplace place18_door_room18_staircase room18_staircase)
	(roomplace place1_door_room11_kitchen room11_kitchen)
	(roomplace place2_door_room12_kitchen room12_kitchen)
	(roomplace place3_door_room9_dining_room room9_dining_room)
	(roomplace place4_door_room13_living_room room13_living_room)
	(roomplace place5_door_room5_bedroom room5_bedroom)
	(roomplace place6_door_room10_home_office room10_home_office)
	(roomplace place7_door_room14_living_room room14_living_room)
	(roomplace place8_door_room6_bedroom room6_bedroom)
	(roomplace place9_door_room8_corridor room8_corridor)
	(roomsconnected room10_home_office room4_bathroom)
	(roomsconnected room11_kitchen room1_bathroom)
	(roomsconnected room12_kitchen room2_bathroom)
	(roomsconnected room12_kitchen room9_dining_room)
	(roomsconnected room13_living_room room15_staircase)
	(roomsconnected room14_living_room room7_corridor)
	(roomsconnected room15_staircase room13_living_room)
	(roomsconnected room15_staircase room16_staircase)
	(roomsconnected room15_staircase room5_bedroom)
	(roomsconnected room16_staircase room15_staircase)
	(roomsconnected room16_staircase room17_staircase)
	(roomsconnected room16_staircase room19_utility_room)
	(roomsconnected room17_staircase room16_staircase)
	(roomsconnected room17_staircase room7_corridor)
	(roomsconnected room18_staircase room8_corridor)
	(roomsconnected room19_utility_room room16_staircase)
	(roomsconnected room1_bathroom room11_kitchen)
	(roomsconnected room1_bathroom room5_bedroom)
	(roomsconnected room2_bathroom room12_kitchen)
	(roomsconnected room2_bathroom room3_bathroom)
	(roomsconnected room2_bathroom room7_corridor)
	(roomsconnected room3_bathroom room2_bathroom)
	(roomsconnected room3_bathroom room4_bathroom)
	(roomsconnected room3_bathroom room8_corridor)
	(roomsconnected room4_bathroom room10_home_office)
	(roomsconnected room4_bathroom room3_bathroom)
	(roomsconnected room5_bedroom room15_staircase)
	(roomsconnected room5_bedroom room1_bathroom)
	(roomsconnected room6_bedroom room8_corridor)
	(roomsconnected room7_corridor room14_living_room)
	(roomsconnected room7_corridor room17_staircase)
	(roomsconnected room7_corridor room2_bathroom)
	(roomsconnected room8_corridor room18_staircase)
	(roomsconnected room8_corridor room3_bathroom)
	(roomsconnected room8_corridor room6_bedroom)
	(roomsconnected room9_dining_room room12_kitchen)
  )
  (:goal (and
	(classrelation bottle diningtable)
	(classrelation vase chair)
	(classrelation tv chair)
	(classrelation pottedplant bed)
	(classrelation vase diningtable)))
)
