
(define (problem mifflinburgtaskographyv4tiny5problem7) (:domain taskographyv4tiny5scrub)
  (:objects
        apple - iclass
	backpack - iclass
	banana - iclass
	baseballbat - iclass
	baseballglove - iclass
	bed - rclass
	bench - rclass
	bicycle - iclass
	boat - rclass
	book - iclass
	bottle - iclass
	bowl - iclass
	cake - iclass
	cellphone - iclass
	chair - rclass
	clock - iclass
	couch - rclass
	cup - iclass
	diningtable - rclass
	frisbee - iclass
	handbag - iclass
	item28_potted_plant_largeitem - item
	item29_potted_plant_largeitem - item
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item9_vase_mediumitem - item
	keyboard - iclass
	kite - iclass
	knife - iclass
	laptop - iclass
	location_xneg11_yneg6_place47_room9_floora - location
	location_xneg11_ypos16_place34_room15_floorb - location
	location_xneg15_yneg12_place39_room9_floora - location
	location_xneg15_ypos32_place16_room16_floora - location
	location_xneg15_ypos43_place13_room8_floora - location
	location_xneg15_ypos57_place29_room2_floorb - location
	location_xneg15_ypos67_place17_room17_floora - location
	location_xneg16_ypos4_place8_room15_floorb - location
	location_xneg16_ypos55_place4_room2_floorb - location
	location_xneg17_ypos52_place26_room2_floorb - location
	location_xneg20_ypos17_place5_room6_floorc - location
	location_xneg24_ypos30_place36_room10_floorb - location
	location_xneg24_ypos37_place35_room10_floorb - location
	location_xneg24_ypos9_place11_room4_floora - location
	location_xneg25_ypos17_place44_room6_floorc - location
	location_xneg27_ypos33_place46_room10_floorb - location
	location_xneg28_ypos36_place7_room10_floorb - location
	location_xneg30_ypos30_place32_room10_floorb - location
	location_xneg30_ypos39_place33_room10_floorb - location
	location_xneg30_ypos65_place9_room5_floorb - location
	location_xneg30_ypos78_place37_room5_floorb - location
	location_xneg32_yneg2_place45_room4_floora - location
	location_xneg32_ypos21_place15_room12_floora - location
	location_xneg33_ypos61_place14_room11_floora - location
	location_xneg36_ypos2_place42_room15_floorb - location
	location_xneg3_ypos18_place30_room1_floora - location
	location_xneg41_ypos74_place43_room5_floorb - location
	location_xneg4_yneg1_place10_room9_floora - location
	location_xneg5_ypos12_place41_room15_floorb - location
	location_xneg6_yneg12_place19_room6_floorc - location
	location_xneg6_yneg7_place38_room9_floora - location
	location_xneg7_ypos36_place40_room6_floorc - location
	location_xneg7_ypos43_place28_room6_floorc - location
	location_xneg9_ypos16_place41_room15_floorb - location
	location_xpos0_ypos25_place20_room14_floorb - location
	location_xpos0_ypos26_place21_room14_floorb - location
	location_xpos10_yneg1_place3_room13_floora - location
	location_xpos10_ypos3_place18_room18_floorb - location
	location_xpos11_ypos28_place24_room19_floora - location
	location_xpos11_ypos55_place27_room14_floorb - location
	location_xpos11_ypos9_place25_room13_floora - location
	location_xpos13_ypos28_place31_room3_floorc - location
	location_xpos13_ypos37_place22_room14_floorb - location
	location_xpos13_ypos66_place27_room14_floorb - location
	location_xpos14_ypos36_place23_room3_floorc - location
	location_xpos16_ypos67_place27_room14_floorb - location
	location_xpos3_ypos45_place0_room14_floorb - location
	location_xpos4_ypos17_place6_room1_floora - location
	location_xpos6_ypos35_place2_room19_floora - location
	location_xpos7_yneg1_place12_room7_floorc - location
	location_xpos7_ypos36_place1_room3_floorc - location
	microwave - rclass
	motorcycle - iclass
	mouse - iclass
	orange - iclass
	oven - rclass
	place0_door_room14_kitchen - place
	place10_door_room9_dining_room - place
	place11_door_room4_bedroom - place
	place12_door_room7_closet - place
	place13_door_room8_corridor - place
	place14_door_room11_empty_room - place
	place15_door_room12_home_office - place
	place16_door_room16_lobby - place
	place17_door_room17_staircase - place
	place18_door_room18_staircase - place
	place19_item9_vase - place
	place1_door_room3_bathroom - place
	place20_receptacle1_microwave - place
	place21_receptacle2_oven - place
	place22_receptacle3_sink - place
	place23_receptacle4_sink - place
	place24_receptacle5_sink - place
	place25_receptacle6_sink - place
	place26_receptacle7_sink - place
	place27_receptacle8_refrigerator - place
	place28_receptacle10_bench - place
	place29_receptacle11_toilet - place
	place2_door_room19_utility_room - place
	place30_receptacle12_toilet - place
	place31_receptacle13_toilet - place
	place32_receptacle14_chair - place
	place33_receptacle15_chair - place
	place34_receptacle16_chair - place
	place35_receptacle17_chair - place
	place36_receptacle18_chair - place
	place37_receptacle19_chair - place
	place38_receptacle23_chair - place
	place39_receptacle24_chair - place
	place3_door_room13_kitchen - place
	place40_receptacle25_chair - place
	place41_receptacle26_couch - place
	place42_receptacle27_couch - place
	place43_receptacle33_bed - place
	place44_receptacle34_bed - place
	place45_receptacle35_bed - place
	place46_receptacle36_dining_table - place
	place47_receptacle37_dining_table - place
	place4_door_room2_bathroom - place
	place5_door_room6_bedroom - place
	place6_door_room1_bathroom - place
	place7_door_room10_dining_room - place
	place8_door_room15_living_room - place
	place9_door_room5_bedroom - place
	pottedplant - iclass
	receptacle10_bench - receptacle
	receptacle11_toilet - receptacle
	receptacle12_toilet - receptacle
	receptacle13_toilet - receptacle
	receptacle14_chair - receptacle
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle1_microwave - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_couch - receptacle
	receptacle27_couch - receptacle
	receptacle2_oven - receptacle
	receptacle33_bed - receptacle
	receptacle34_bed - receptacle
	receptacle35_bed - receptacle
	receptacle36_dining_table - receptacle
	receptacle37_dining_table - receptacle
	receptacle3_sink - receptacle
	receptacle4_sink - receptacle
	receptacle5_sink - receptacle
	receptacle6_sink - receptacle
	receptacle7_sink - receptacle
	receptacle8_refrigerator - receptacle
	refrigerator - rclass
	remote - iclass
	robot - agent
	room10_dining_room - room
	room11_empty_room - room
	room12_home_office - room
	room13_kitchen - room
	room14_kitchen - room
	room15_living_room - room
	room16_lobby - room
	room17_staircase - room
	room18_staircase - room
	room19_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_bedroom - room
	room7_closet - room
	room8_corridor - room
	room9_dining_room - room
	sink - rclass
	spoon - iclass
	sportsball - iclass
	suitcase - iclass
	surfboard - iclass
	teddybear - iclass
	tie - iclass
	toaster - rclass
	toilet - rclass
	toothbrush - iclass
	tv - iclass
	umbrella - iclass
	vase - iclass
	wineglass - iclass
  )
  (:init 
	(atlocation robot location_xneg33_ypos61_place14_room11_floora)
	(classrelation pottedplant couch)
	(classrelation pottedplant diningtable)
	(classrelation pottedplant refrigerator)
	(inanyreceptacle item28_potted_plant_largeitem)
	(inanyreceptacle item29_potted_plant_largeitem)
	(inanyreceptacle item30_potted_plant_largeitem)
	(inanyreceptacle item31_potted_plant_largeitem)
	(inanyreceptacle item32_potted_plant_largeitem)
	(inplace robot place14_door_room11_empty_room)
	(inreceptacle item28_potted_plant_largeitem receptacle26_couch)
	(inreceptacle item29_potted_plant_largeitem receptacle37_dining_table)
	(inreceptacle item30_potted_plant_largeitem receptacle8_refrigerator)
	(inreceptacle item31_potted_plant_largeitem receptacle8_refrigerator)
	(inreceptacle item32_potted_plant_largeitem receptacle8_refrigerator)
	(inroom robot room11_empty_room)
	(itematlocation item28_potted_plant_largeitem location_xneg5_ypos12_place41_room15_floorb)
	(itematlocation item29_potted_plant_largeitem location_xneg11_yneg6_place47_room9_floora)
	(itematlocation item30_potted_plant_largeitem location_xpos13_ypos66_place27_room14_floorb)
	(itematlocation item31_potted_plant_largeitem location_xpos16_ypos67_place27_room14_floorb)
	(itematlocation item32_potted_plant_largeitem location_xpos13_ypos66_place27_room14_floorb)
	(itematlocation item9_vase_mediumitem location_xneg6_yneg12_place19_room6_floorc)
	(itemclass item28_potted_plant_largeitem pottedplant)
	(itemclass item29_potted_plant_largeitem pottedplant)
	(itemclass item30_potted_plant_largeitem pottedplant)
	(itemclass item31_potted_plant_largeitem pottedplant)
	(itemclass item32_potted_plant_largeitem pottedplant)
	(itemclass item9_vase_mediumitem vase)
	(locationinplace location_xneg11_yneg6_place47_room9_floora place47_receptacle37_dining_table)
	(locationinplace location_xneg11_ypos16_place34_room15_floorb place34_receptacle16_chair)
	(locationinplace location_xneg15_yneg12_place39_room9_floora place39_receptacle24_chair)
	(locationinplace location_xneg15_ypos32_place16_room16_floora place16_door_room16_lobby)
	(locationinplace location_xneg15_ypos43_place13_room8_floora place13_door_room8_corridor)
	(locationinplace location_xneg15_ypos57_place29_room2_floorb place29_receptacle11_toilet)
	(locationinplace location_xneg15_ypos67_place17_room17_floora place17_door_room17_staircase)
	(locationinplace location_xneg16_ypos4_place8_room15_floorb place8_door_room15_living_room)
	(locationinplace location_xneg16_ypos55_place4_room2_floorb place4_door_room2_bathroom)
	(locationinplace location_xneg17_ypos52_place26_room2_floorb place26_receptacle7_sink)
	(locationinplace location_xneg20_ypos17_place5_room6_floorc place5_door_room6_bedroom)
	(locationinplace location_xneg24_ypos30_place36_room10_floorb place36_receptacle18_chair)
	(locationinplace location_xneg24_ypos37_place35_room10_floorb place35_receptacle17_chair)
	(locationinplace location_xneg24_ypos9_place11_room4_floora place11_door_room4_bedroom)
	(locationinplace location_xneg25_ypos17_place44_room6_floorc place44_receptacle34_bed)
	(locationinplace location_xneg27_ypos33_place46_room10_floorb place46_receptacle36_dining_table)
	(locationinplace location_xneg28_ypos36_place7_room10_floorb place7_door_room10_dining_room)
	(locationinplace location_xneg30_ypos30_place32_room10_floorb place32_receptacle14_chair)
	(locationinplace location_xneg30_ypos39_place33_room10_floorb place33_receptacle15_chair)
	(locationinplace location_xneg30_ypos65_place9_room5_floorb place9_door_room5_bedroom)
	(locationinplace location_xneg30_ypos78_place37_room5_floorb place37_receptacle19_chair)
	(locationinplace location_xneg32_yneg2_place45_room4_floora place45_receptacle35_bed)
	(locationinplace location_xneg32_ypos21_place15_room12_floora place15_door_room12_home_office)
	(locationinplace location_xneg33_ypos61_place14_room11_floora place14_door_room11_empty_room)
	(locationinplace location_xneg36_ypos2_place42_room15_floorb place42_receptacle27_couch)
	(locationinplace location_xneg3_ypos18_place30_room1_floora place30_receptacle12_toilet)
	(locationinplace location_xneg41_ypos74_place43_room5_floorb place43_receptacle33_bed)
	(locationinplace location_xneg4_yneg1_place10_room9_floora place10_door_room9_dining_room)
	(locationinplace location_xneg5_ypos12_place41_room15_floorb place41_receptacle26_couch)
	(locationinplace location_xneg6_yneg12_place19_room6_floorc place19_item9_vase)
	(locationinplace location_xneg6_yneg7_place38_room9_floora place38_receptacle23_chair)
	(locationinplace location_xneg7_ypos36_place40_room6_floorc place40_receptacle25_chair)
	(locationinplace location_xneg7_ypos43_place28_room6_floorc place28_receptacle10_bench)
	(locationinplace location_xneg9_ypos16_place41_room15_floorb place41_receptacle26_couch)
	(locationinplace location_xpos0_ypos25_place20_room14_floorb place20_receptacle1_microwave)
	(locationinplace location_xpos0_ypos26_place21_room14_floorb place21_receptacle2_oven)
	(locationinplace location_xpos10_yneg1_place3_room13_floora place3_door_room13_kitchen)
	(locationinplace location_xpos10_ypos3_place18_room18_floorb place18_door_room18_staircase)
	(locationinplace location_xpos11_ypos28_place24_room19_floora place24_receptacle5_sink)
	(locationinplace location_xpos11_ypos55_place27_room14_floorb place27_receptacle8_refrigerator)
	(locationinplace location_xpos11_ypos9_place25_room13_floora place25_receptacle6_sink)
	(locationinplace location_xpos13_ypos28_place31_room3_floorc place31_receptacle13_toilet)
	(locationinplace location_xpos13_ypos37_place22_room14_floorb place22_receptacle3_sink)
	(locationinplace location_xpos13_ypos66_place27_room14_floorb place27_receptacle8_refrigerator)
	(locationinplace location_xpos14_ypos36_place23_room3_floorc place23_receptacle4_sink)
	(locationinplace location_xpos16_ypos67_place27_room14_floorb place27_receptacle8_refrigerator)
	(locationinplace location_xpos3_ypos45_place0_room14_floorb place0_door_room14_kitchen)
	(locationinplace location_xpos4_ypos17_place6_room1_floora place6_door_room1_bathroom)
	(locationinplace location_xpos6_ypos35_place2_room19_floora place2_door_room19_utility_room)
	(locationinplace location_xpos7_yneg1_place12_room7_floorc place12_door_room7_closet)
	(locationinplace location_xpos7_ypos36_place1_room3_floorc place1_door_room3_bathroom)
	(placeinroom place0_door_room14_kitchen room14_kitchen)
	(placeinroom place10_door_room9_dining_room room9_dining_room)
	(placeinroom place11_door_room4_bedroom room4_bedroom)
	(placeinroom place12_door_room7_closet room7_closet)
	(placeinroom place13_door_room8_corridor room8_corridor)
	(placeinroom place14_door_room11_empty_room room11_empty_room)
	(placeinroom place15_door_room12_home_office room12_home_office)
	(placeinroom place16_door_room16_lobby room16_lobby)
	(placeinroom place17_door_room17_staircase room17_staircase)
	(placeinroom place18_door_room18_staircase room18_staircase)
	(placeinroom place19_item9_vase room6_bedroom)
	(placeinroom place1_door_room3_bathroom room3_bathroom)
	(placeinroom place20_receptacle1_microwave room14_kitchen)
	(placeinroom place21_receptacle2_oven room14_kitchen)
	(placeinroom place22_receptacle3_sink room14_kitchen)
	(placeinroom place23_receptacle4_sink room3_bathroom)
	(placeinroom place24_receptacle5_sink room19_utility_room)
	(placeinroom place25_receptacle6_sink room13_kitchen)
	(placeinroom place26_receptacle7_sink room2_bathroom)
	(placeinroom place27_receptacle8_refrigerator room14_kitchen)
	(placeinroom place28_receptacle10_bench room6_bedroom)
	(placeinroom place29_receptacle11_toilet room2_bathroom)
	(placeinroom place2_door_room19_utility_room room19_utility_room)
	(placeinroom place30_receptacle12_toilet room1_bathroom)
	(placeinroom place31_receptacle13_toilet room3_bathroom)
	(placeinroom place32_receptacle14_chair room10_dining_room)
	(placeinroom place33_receptacle15_chair room10_dining_room)
	(placeinroom place34_receptacle16_chair room15_living_room)
	(placeinroom place35_receptacle17_chair room10_dining_room)
	(placeinroom place36_receptacle18_chair room10_dining_room)
	(placeinroom place37_receptacle19_chair room5_bedroom)
	(placeinroom place38_receptacle23_chair room9_dining_room)
	(placeinroom place39_receptacle24_chair room9_dining_room)
	(placeinroom place3_door_room13_kitchen room13_kitchen)
	(placeinroom place40_receptacle25_chair room6_bedroom)
	(placeinroom place41_receptacle26_couch room15_living_room)
	(placeinroom place42_receptacle27_couch room15_living_room)
	(placeinroom place43_receptacle33_bed room5_bedroom)
	(placeinroom place44_receptacle34_bed room6_bedroom)
	(placeinroom place45_receptacle35_bed room4_bedroom)
	(placeinroom place46_receptacle36_dining_table room10_dining_room)
	(placeinroom place47_receptacle37_dining_table room9_dining_room)
	(placeinroom place4_door_room2_bathroom room2_bathroom)
	(placeinroom place5_door_room6_bedroom room6_bedroom)
	(placeinroom place6_door_room1_bathroom room1_bathroom)
	(placeinroom place7_door_room10_dining_room room10_dining_room)
	(placeinroom place8_door_room15_living_room room15_living_room)
	(placeinroom place9_door_room5_bedroom room5_bedroom)
	(placelocation location_xneg11_yneg6_place47_room9_floora place47_receptacle37_dining_table)
	(placelocation location_xneg11_ypos16_place34_room15_floorb place34_receptacle16_chair)
	(placelocation location_xneg15_yneg12_place39_room9_floora place39_receptacle24_chair)
	(placelocation location_xneg15_ypos32_place16_room16_floora place16_door_room16_lobby)
	(placelocation location_xneg15_ypos43_place13_room8_floora place13_door_room8_corridor)
	(placelocation location_xneg15_ypos57_place29_room2_floorb place29_receptacle11_toilet)
	(placelocation location_xneg15_ypos67_place17_room17_floora place17_door_room17_staircase)
	(placelocation location_xneg16_ypos4_place8_room15_floorb place8_door_room15_living_room)
	(placelocation location_xneg16_ypos55_place4_room2_floorb place4_door_room2_bathroom)
	(placelocation location_xneg17_ypos52_place26_room2_floorb place26_receptacle7_sink)
	(placelocation location_xneg20_ypos17_place5_room6_floorc place5_door_room6_bedroom)
	(placelocation location_xneg24_ypos30_place36_room10_floorb place36_receptacle18_chair)
	(placelocation location_xneg24_ypos37_place35_room10_floorb place35_receptacle17_chair)
	(placelocation location_xneg24_ypos9_place11_room4_floora place11_door_room4_bedroom)
	(placelocation location_xneg25_ypos17_place44_room6_floorc place44_receptacle34_bed)
	(placelocation location_xneg27_ypos33_place46_room10_floorb place46_receptacle36_dining_table)
	(placelocation location_xneg28_ypos36_place7_room10_floorb place7_door_room10_dining_room)
	(placelocation location_xneg30_ypos30_place32_room10_floorb place32_receptacle14_chair)
	(placelocation location_xneg30_ypos39_place33_room10_floorb place33_receptacle15_chair)
	(placelocation location_xneg30_ypos65_place9_room5_floorb place9_door_room5_bedroom)
	(placelocation location_xneg30_ypos78_place37_room5_floorb place37_receptacle19_chair)
	(placelocation location_xneg32_yneg2_place45_room4_floora place45_receptacle35_bed)
	(placelocation location_xneg32_ypos21_place15_room12_floora place15_door_room12_home_office)
	(placelocation location_xneg33_ypos61_place14_room11_floora place14_door_room11_empty_room)
	(placelocation location_xneg36_ypos2_place42_room15_floorb place42_receptacle27_couch)
	(placelocation location_xneg3_ypos18_place30_room1_floora place30_receptacle12_toilet)
	(placelocation location_xneg41_ypos74_place43_room5_floorb place43_receptacle33_bed)
	(placelocation location_xneg4_yneg1_place10_room9_floora place10_door_room9_dining_room)
	(placelocation location_xneg6_yneg12_place19_room6_floorc place19_item9_vase)
	(placelocation location_xneg6_yneg7_place38_room9_floora place38_receptacle23_chair)
	(placelocation location_xneg7_ypos36_place40_room6_floorc place40_receptacle25_chair)
	(placelocation location_xneg7_ypos43_place28_room6_floorc place28_receptacle10_bench)
	(placelocation location_xneg9_ypos16_place41_room15_floorb place41_receptacle26_couch)
	(placelocation location_xpos0_ypos25_place20_room14_floorb place20_receptacle1_microwave)
	(placelocation location_xpos0_ypos26_place21_room14_floorb place21_receptacle2_oven)
	(placelocation location_xpos10_yneg1_place3_room13_floora place3_door_room13_kitchen)
	(placelocation location_xpos10_ypos3_place18_room18_floorb place18_door_room18_staircase)
	(placelocation location_xpos11_ypos28_place24_room19_floora place24_receptacle5_sink)
	(placelocation location_xpos11_ypos55_place27_room14_floorb place27_receptacle8_refrigerator)
	(placelocation location_xpos11_ypos9_place25_room13_floora place25_receptacle6_sink)
	(placelocation location_xpos13_ypos28_place31_room3_floorc place31_receptacle13_toilet)
	(placelocation location_xpos13_ypos37_place22_room14_floorb place22_receptacle3_sink)
	(placelocation location_xpos14_ypos36_place23_room3_floorc place23_receptacle4_sink)
	(placelocation location_xpos3_ypos45_place0_room14_floorb place0_door_room14_kitchen)
	(placelocation location_xpos4_ypos17_place6_room1_floora place6_door_room1_bathroom)
	(placelocation location_xpos6_ypos35_place2_room19_floora place2_door_room19_utility_room)
	(placelocation location_xpos7_yneg1_place12_room7_floorc place12_door_room7_closet)
	(placelocation location_xpos7_ypos36_place1_room3_floorc place1_door_room3_bathroom)
	(receptacleatlocation receptacle10_bench location_xneg7_ypos43_place28_room6_floorc)
	(receptacleatlocation receptacle11_toilet location_xneg15_ypos57_place29_room2_floorb)
	(receptacleatlocation receptacle12_toilet location_xneg3_ypos18_place30_room1_floora)
	(receptacleatlocation receptacle13_toilet location_xpos13_ypos28_place31_room3_floorc)
	(receptacleatlocation receptacle14_chair location_xneg30_ypos30_place32_room10_floorb)
	(receptacleatlocation receptacle15_chair location_xneg30_ypos39_place33_room10_floorb)
	(receptacleatlocation receptacle16_chair location_xneg11_ypos16_place34_room15_floorb)
	(receptacleatlocation receptacle17_chair location_xneg24_ypos37_place35_room10_floorb)
	(receptacleatlocation receptacle18_chair location_xneg24_ypos30_place36_room10_floorb)
	(receptacleatlocation receptacle19_chair location_xneg30_ypos78_place37_room5_floorb)
	(receptacleatlocation receptacle1_microwave location_xpos0_ypos25_place20_room14_floorb)
	(receptacleatlocation receptacle23_chair location_xneg6_yneg7_place38_room9_floora)
	(receptacleatlocation receptacle24_chair location_xneg15_yneg12_place39_room9_floora)
	(receptacleatlocation receptacle25_chair location_xneg7_ypos36_place40_room6_floorc)
	(receptacleatlocation receptacle26_couch location_xneg9_ypos16_place41_room15_floorb)
	(receptacleatlocation receptacle27_couch location_xneg36_ypos2_place42_room15_floorb)
	(receptacleatlocation receptacle2_oven location_xpos0_ypos26_place21_room14_floorb)
	(receptacleatlocation receptacle33_bed location_xneg41_ypos74_place43_room5_floorb)
	(receptacleatlocation receptacle34_bed location_xneg25_ypos17_place44_room6_floorc)
	(receptacleatlocation receptacle35_bed location_xneg32_yneg2_place45_room4_floora)
	(receptacleatlocation receptacle36_dining_table location_xneg27_ypos33_place46_room10_floorb)
	(receptacleatlocation receptacle37_dining_table location_xneg11_yneg6_place47_room9_floora)
	(receptacleatlocation receptacle3_sink location_xpos13_ypos37_place22_room14_floorb)
	(receptacleatlocation receptacle4_sink location_xpos14_ypos36_place23_room3_floorc)
	(receptacleatlocation receptacle5_sink location_xpos11_ypos28_place24_room19_floora)
	(receptacleatlocation receptacle6_sink location_xpos11_ypos9_place25_room13_floora)
	(receptacleatlocation receptacle7_sink location_xneg17_ypos52_place26_room2_floorb)
	(receptacleatlocation receptacle8_refrigerator location_xpos11_ypos55_place27_room14_floorb)
	(receptacleclass receptacle10_bench bench)
	(receptacleclass receptacle11_toilet toilet)
	(receptacleclass receptacle12_toilet toilet)
	(receptacleclass receptacle13_toilet toilet)
	(receptacleclass receptacle14_chair chair)
	(receptacleclass receptacle15_chair chair)
	(receptacleclass receptacle16_chair chair)
	(receptacleclass receptacle17_chair chair)
	(receptacleclass receptacle18_chair chair)
	(receptacleclass receptacle19_chair chair)
	(receptacleclass receptacle1_microwave microwave)
	(receptacleclass receptacle23_chair chair)
	(receptacleclass receptacle24_chair chair)
	(receptacleclass receptacle25_chair chair)
	(receptacleclass receptacle26_couch couch)
	(receptacleclass receptacle27_couch couch)
	(receptacleclass receptacle2_oven oven)
	(receptacleclass receptacle33_bed bed)
	(receptacleclass receptacle34_bed bed)
	(receptacleclass receptacle35_bed bed)
	(receptacleclass receptacle36_dining_table diningtable)
	(receptacleclass receptacle37_dining_table diningtable)
	(receptacleclass receptacle3_sink sink)
	(receptacleclass receptacle4_sink sink)
	(receptacleclass receptacle5_sink sink)
	(receptacleclass receptacle6_sink sink)
	(receptacleclass receptacle7_sink sink)
	(receptacleclass receptacle8_refrigerator refrigerator)
	(receptacleopeningtype receptacle1_microwave)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle8_refrigerator)
	(roomplace place0_door_room14_kitchen room14_kitchen)
	(roomplace place10_door_room9_dining_room room9_dining_room)
	(roomplace place11_door_room4_bedroom room4_bedroom)
	(roomplace place12_door_room7_closet room7_closet)
	(roomplace place13_door_room8_corridor room8_corridor)
	(roomplace place14_door_room11_empty_room room11_empty_room)
	(roomplace place15_door_room12_home_office room12_home_office)
	(roomplace place16_door_room16_lobby room16_lobby)
	(roomplace place17_door_room17_staircase room17_staircase)
	(roomplace place18_door_room18_staircase room18_staircase)
	(roomplace place1_door_room3_bathroom room3_bathroom)
	(roomplace place2_door_room19_utility_room room19_utility_room)
	(roomplace place3_door_room13_kitchen room13_kitchen)
	(roomplace place4_door_room2_bathroom room2_bathroom)
	(roomplace place5_door_room6_bedroom room6_bedroom)
	(roomplace place6_door_room1_bathroom room1_bathroom)
	(roomplace place7_door_room10_dining_room room10_dining_room)
	(roomplace place8_door_room15_living_room room15_living_room)
	(roomplace place9_door_room5_bedroom room5_bedroom)
	(roomsconnected room10_dining_room room15_living_room)
	(roomsconnected room10_dining_room room2_bathroom)
	(roomsconnected room11_empty_room room17_staircase)
	(roomsconnected room11_empty_room room8_corridor)
	(roomsconnected room12_home_office room16_lobby)
	(roomsconnected room12_home_office room4_bedroom)
	(roomsconnected room13_kitchen room1_bathroom)
	(roomsconnected room13_kitchen room9_dining_room)
	(roomsconnected room14_kitchen room2_bathroom)
	(roomsconnected room15_living_room room10_dining_room)
	(roomsconnected room15_living_room room18_staircase)
	(roomsconnected room16_lobby room12_home_office)
	(roomsconnected room16_lobby room19_utility_room)
	(roomsconnected room16_lobby room8_corridor)
	(roomsconnected room17_staircase room11_empty_room)
	(roomsconnected room17_staircase room2_bathroom)
	(roomsconnected room18_staircase room15_living_room)
	(roomsconnected room18_staircase room7_closet)
	(roomsconnected room19_utility_room room16_lobby)
	(roomsconnected room19_utility_room room1_bathroom)
	(roomsconnected room1_bathroom room13_kitchen)
	(roomsconnected room1_bathroom room19_utility_room)
	(roomsconnected room2_bathroom room10_dining_room)
	(roomsconnected room2_bathroom room14_kitchen)
	(roomsconnected room2_bathroom room17_staircase)
	(roomsconnected room2_bathroom room5_bedroom)
	(roomsconnected room3_bathroom room6_bedroom)
	(roomsconnected room4_bedroom room12_home_office)
	(roomsconnected room5_bedroom room2_bathroom)
	(roomsconnected room6_bedroom room3_bathroom)
	(roomsconnected room6_bedroom room7_closet)
	(roomsconnected room7_closet room18_staircase)
	(roomsconnected room7_closet room6_bedroom)
	(roomsconnected room8_corridor room11_empty_room)
	(roomsconnected room8_corridor room16_lobby)
	(roomsconnected room9_dining_room room13_kitchen)
  )
  (:goal (and
	(classrelation vase toilet)
	(classrelation pottedplant bed)
	(classrelation vase chair)
	(classrelation vase sink)
	(classrelation pottedplant bench)))
)
