
(define (problem noxapatertaskographyv4tiny5problem25) (:domain taskographyv4tiny5scrub)
  (:objects
        apple - iclass
	backpack - iclass
	banana - iclass
	baseballbat - iclass
	baseballglove - iclass
	bed - rclass
	bench - rclass
	bicycle - iclass
	boat - rclass
	book - iclass
	bottle - iclass
	bowl - iclass
	cake - iclass
	cellphone - iclass
	chair - rclass
	clock - iclass
	couch - rclass
	cup - iclass
	diningtable - rclass
	frisbee - iclass
	handbag - iclass
	item29_potted_plant_largeitem - item
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item6_book_smallitem - item
	item7_book_smallitem - item
	item8_bottle_smallitem - item
	keyboard - iclass
	kite - iclass
	knife - iclass
	laptop - iclass
	location_xneg12_ypos2_place5_room2_floora - location
	location_xneg19_yneg14_place3_room9_floorb - location
	location_xneg19_yneg15_place35_room9_floorb - location
	location_xneg19_ypos17_place24_room9_floorb - location
	location_xneg24_ypos3_place36_room2_floora - location
	location_xneg30_yneg4_place35_room9_floorb - location
	location_xneg32_yneg18_place35_room9_floorb - location
	location_xneg4_ypos6_place23_room9_floorb - location
	location_xneg5_ypos7_place24_room9_floorb - location
	location_xneg6_ypos5_place22_room9_floorb - location
	location_xpos10_ypos18_place12_room8_floorb - location
	location_xpos11_yneg30_place32_room5_floora - location
	location_xpos12_yneg28_place27_room5_floora - location
	location_xpos13_yneg33_place34_room5_floora - location
	location_xpos15_yneg34_place4_room5_floora - location
	location_xpos16_yneg37_place28_room5_floora - location
	location_xpos16_yneg3_place11_room8_floorb - location
	location_xpos17_yneg34_place37_room5_floora - location
	location_xpos17_yneg39_place30_room5_floora - location
	location_xpos19_yneg32_place25_room5_floora - location
	location_xpos19_yneg36_place33_room5_floora - location
	location_xpos1_yneg44_place29_room5_floora - location
	location_xpos20_yneg39_place31_room5_floora - location
	location_xpos23_ypos26_place17_room8_floorb - location
	location_xpos23_ypos9_place0_room8_floorb - location
	location_xpos24_ypos21_place18_room8_floorb - location
	location_xpos28_ypos25_place38_room8_floorb - location
	location_xpos28_ypos27_place38_room8_floorb - location
	location_xpos28_ypos4_place6_room3_floora - location
	location_xpos29_ypos30_place21_room8_floorb - location
	location_xpos30_yneg2_place15_room8_floorb - location
	location_xpos31_yneg46_place31_room5_floora - location
	location_xpos32_yneg47_place31_room5_floora - location
	location_xpos32_ypos22_place20_room8_floorb - location
	location_xpos33_ypos26_place19_room8_floorb - location
	location_xpos34_yneg13_place7_room4_floorb - location
	location_xpos3_yneg44_place26_room5_floora - location
	location_xpos46_yneg32_place8_room6_floora - location
	location_xpos54_yneg34_place9_room7_floorb - location
	location_xpos57_ypos3_place2_room11_floora - location
	location_xpos59_yneg10_place13_room1_floorb - location
	location_xpos60_yneg3_place1_room1_floorb - location
	location_xpos60_ypos12_place10_room10_floora - location
	location_xpos61_yneg10_place14_room11_floora - location
	location_xpos61_yneg9_place13_room1_floorb - location
	location_xpos68_yneg7_place16_room1_floorb - location
	microwave - rclass
	motorcycle - iclass
	mouse - iclass
	orange - iclass
	oven - rclass
	place0_door_room8_kitchen - place
	place10_door_room10_staircase - place
	place11_receptacle1_oven - place
	place12_receptacle2_sink - place
	place13_receptacle3_sink - place
	place14_receptacle4_sink - place
	place15_receptacle5_refrigerator - place
	place16_receptacle9_toilet - place
	place17_receptacle10_chair - place
	place18_receptacle11_chair - place
	place19_receptacle12_chair - place
	place1_door_room1_bathroom - place
	place20_receptacle13_chair - place
	place21_receptacle14_chair - place
	place22_receptacle15_chair - place
	place23_receptacle16_chair - place
	place24_receptacle17_chair - place
	place25_receptacle18_chair - place
	place26_receptacle19_chair - place
	place27_receptacle20_chair - place
	place28_receptacle21_chair - place
	place29_receptacle22_chair - place
	place2_door_room11_utility_room - place
	place30_receptacle23_chair - place
	place31_receptacle24_chair - place
	place32_receptacle25_chair - place
	place33_receptacle26_chair - place
	place34_receptacle27_chair - place
	place35_receptacle28_couch - place
	place36_receptacle33_bed - place
	place37_receptacle34_dining_table - place
	place38_receptacle35_dining_table - place
	place3_door_room9_living_room - place
	place4_door_room5_dining_room - place
	place5_door_room2_bedroom - place
	place6_door_room3_corridor - place
	place7_door_room4_corridor - place
	place8_door_room6_empty_room - place
	place9_door_room7_empty_room - place
	pottedplant - iclass
	receptacle10_chair - receptacle
	receptacle11_chair - receptacle
	receptacle12_chair - receptacle
	receptacle13_chair - receptacle
	receptacle14_chair - receptacle
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle1_oven - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_couch - receptacle
	receptacle2_sink - receptacle
	receptacle33_bed - receptacle
	receptacle34_dining_table - receptacle
	receptacle35_dining_table - receptacle
	receptacle3_sink - receptacle
	receptacle4_sink - receptacle
	receptacle5_refrigerator - receptacle
	receptacle9_toilet - receptacle
	refrigerator - rclass
	remote - iclass
	robot - agent
	room10_staircase - room
	room11_utility_room - room
	room1_bathroom - room
	room2_bedroom - room
	room3_corridor - room
	room4_corridor - room
	room5_dining_room - room
	room6_empty_room - room
	room7_empty_room - room
	room8_kitchen - room
	room9_living_room - room
	sink - rclass
	spoon - iclass
	sportsball - iclass
	suitcase - iclass
	surfboard - iclass
	teddybear - iclass
	tie - iclass
	toaster - rclass
	toilet - rclass
	toothbrush - iclass
	tv - iclass
	umbrella - iclass
	vase - iclass
	wineglass - iclass
  )
  (:init 
	(atlocation robot location_xneg19_yneg14_place3_room9_floorb)
	(classrelation book couch)
	(classrelation bottle sink)
	(classrelation pottedplant chair)
	(classrelation pottedplant diningtable)
	(inanyreceptacle item29_potted_plant_largeitem)
	(inanyreceptacle item30_potted_plant_largeitem)
	(inanyreceptacle item31_potted_plant_largeitem)
	(inanyreceptacle item32_potted_plant_largeitem)
	(inanyreceptacle item6_book_smallitem)
	(inanyreceptacle item7_book_smallitem)
	(inanyreceptacle item8_bottle_smallitem)
	(inplace robot place3_door_room9_living_room)
	(inreceptacle item29_potted_plant_largeitem receptacle35_dining_table)
	(inreceptacle item30_potted_plant_largeitem receptacle17_chair)
	(inreceptacle item31_potted_plant_largeitem receptacle24_chair)
	(inreceptacle item32_potted_plant_largeitem receptacle24_chair)
	(inreceptacle item6_book_smallitem receptacle28_couch)
	(inreceptacle item7_book_smallitem receptacle28_couch)
	(inreceptacle item8_bottle_smallitem receptacle3_sink)
	(inroom robot room9_living_room)
	(itematlocation item29_potted_plant_largeitem location_xpos28_ypos27_place38_room8_floorb)
	(itematlocation item30_potted_plant_largeitem location_xneg19_ypos17_place24_room9_floorb)
	(itematlocation item31_potted_plant_largeitem location_xpos31_yneg46_place31_room5_floora)
	(itematlocation item32_potted_plant_largeitem location_xpos32_yneg47_place31_room5_floora)
	(itematlocation item6_book_smallitem location_xneg19_yneg15_place35_room9_floorb)
	(itematlocation item7_book_smallitem location_xneg30_yneg4_place35_room9_floorb)
	(itematlocation item8_bottle_smallitem location_xpos59_yneg10_place13_room1_floorb)
	(itemclass item29_potted_plant_largeitem pottedplant)
	(itemclass item30_potted_plant_largeitem pottedplant)
	(itemclass item31_potted_plant_largeitem pottedplant)
	(itemclass item32_potted_plant_largeitem pottedplant)
	(itemclass item6_book_smallitem book)
	(itemclass item7_book_smallitem book)
	(itemclass item8_bottle_smallitem bottle)
	(locationinplace location_xneg12_ypos2_place5_room2_floora place5_door_room2_bedroom)
	(locationinplace location_xneg19_yneg14_place3_room9_floorb place3_door_room9_living_room)
	(locationinplace location_xneg19_yneg15_place35_room9_floorb place35_receptacle28_couch)
	(locationinplace location_xneg19_ypos17_place24_room9_floorb place24_receptacle17_chair)
	(locationinplace location_xneg24_ypos3_place36_room2_floora place36_receptacle33_bed)
	(locationinplace location_xneg30_yneg4_place35_room9_floorb place35_receptacle28_couch)
	(locationinplace location_xneg32_yneg18_place35_room9_floorb place35_receptacle28_couch)
	(locationinplace location_xneg4_ypos6_place23_room9_floorb place23_receptacle16_chair)
	(locationinplace location_xneg5_ypos7_place24_room9_floorb place24_receptacle17_chair)
	(locationinplace location_xneg6_ypos5_place22_room9_floorb place22_receptacle15_chair)
	(locationinplace location_xpos10_ypos18_place12_room8_floorb place12_receptacle2_sink)
	(locationinplace location_xpos11_yneg30_place32_room5_floora place32_receptacle25_chair)
	(locationinplace location_xpos12_yneg28_place27_room5_floora place27_receptacle20_chair)
	(locationinplace location_xpos13_yneg33_place34_room5_floora place34_receptacle27_chair)
	(locationinplace location_xpos15_yneg34_place4_room5_floora place4_door_room5_dining_room)
	(locationinplace location_xpos16_yneg37_place28_room5_floora place28_receptacle21_chair)
	(locationinplace location_xpos16_yneg3_place11_room8_floorb place11_receptacle1_oven)
	(locationinplace location_xpos17_yneg34_place37_room5_floora place37_receptacle34_dining_table)
	(locationinplace location_xpos17_yneg39_place30_room5_floora place30_receptacle23_chair)
	(locationinplace location_xpos19_yneg32_place25_room5_floora place25_receptacle18_chair)
	(locationinplace location_xpos19_yneg36_place33_room5_floora place33_receptacle26_chair)
	(locationinplace location_xpos1_yneg44_place29_room5_floora place29_receptacle22_chair)
	(locationinplace location_xpos20_yneg39_place31_room5_floora place31_receptacle24_chair)
	(locationinplace location_xpos23_ypos26_place17_room8_floorb place17_receptacle10_chair)
	(locationinplace location_xpos23_ypos9_place0_room8_floorb place0_door_room8_kitchen)
	(locationinplace location_xpos24_ypos21_place18_room8_floorb place18_receptacle11_chair)
	(locationinplace location_xpos28_ypos25_place38_room8_floorb place38_receptacle35_dining_table)
	(locationinplace location_xpos28_ypos27_place38_room8_floorb place38_receptacle35_dining_table)
	(locationinplace location_xpos28_ypos4_place6_room3_floora place6_door_room3_corridor)
	(locationinplace location_xpos29_ypos30_place21_room8_floorb place21_receptacle14_chair)
	(locationinplace location_xpos30_yneg2_place15_room8_floorb place15_receptacle5_refrigerator)
	(locationinplace location_xpos31_yneg46_place31_room5_floora place31_receptacle24_chair)
	(locationinplace location_xpos32_yneg47_place31_room5_floora place31_receptacle24_chair)
	(locationinplace location_xpos32_ypos22_place20_room8_floorb place20_receptacle13_chair)
	(locationinplace location_xpos33_ypos26_place19_room8_floorb place19_receptacle12_chair)
	(locationinplace location_xpos34_yneg13_place7_room4_floorb place7_door_room4_corridor)
	(locationinplace location_xpos3_yneg44_place26_room5_floora place26_receptacle19_chair)
	(locationinplace location_xpos46_yneg32_place8_room6_floora place8_door_room6_empty_room)
	(locationinplace location_xpos54_yneg34_place9_room7_floorb place9_door_room7_empty_room)
	(locationinplace location_xpos57_ypos3_place2_room11_floora place2_door_room11_utility_room)
	(locationinplace location_xpos59_yneg10_place13_room1_floorb place13_receptacle3_sink)
	(locationinplace location_xpos60_yneg3_place1_room1_floorb place1_door_room1_bathroom)
	(locationinplace location_xpos60_ypos12_place10_room10_floora place10_door_room10_staircase)
	(locationinplace location_xpos61_yneg10_place14_room11_floora place14_receptacle4_sink)
	(locationinplace location_xpos61_yneg9_place13_room1_floorb place13_receptacle3_sink)
	(locationinplace location_xpos68_yneg7_place16_room1_floorb place16_receptacle9_toilet)
	(placeinroom place0_door_room8_kitchen room8_kitchen)
	(placeinroom place10_door_room10_staircase room10_staircase)
	(placeinroom place11_receptacle1_oven room8_kitchen)
	(placeinroom place12_receptacle2_sink room8_kitchen)
	(placeinroom place13_receptacle3_sink room1_bathroom)
	(placeinroom place14_receptacle4_sink room11_utility_room)
	(placeinroom place15_receptacle5_refrigerator room8_kitchen)
	(placeinroom place16_receptacle9_toilet room1_bathroom)
	(placeinroom place17_receptacle10_chair room8_kitchen)
	(placeinroom place18_receptacle11_chair room8_kitchen)
	(placeinroom place19_receptacle12_chair room8_kitchen)
	(placeinroom place1_door_room1_bathroom room1_bathroom)
	(placeinroom place20_receptacle13_chair room8_kitchen)
	(placeinroom place21_receptacle14_chair room8_kitchen)
	(placeinroom place22_receptacle15_chair room9_living_room)
	(placeinroom place23_receptacle16_chair room9_living_room)
	(placeinroom place24_receptacle17_chair room9_living_room)
	(placeinroom place25_receptacle18_chair room5_dining_room)
	(placeinroom place26_receptacle19_chair room5_dining_room)
	(placeinroom place27_receptacle20_chair room5_dining_room)
	(placeinroom place28_receptacle21_chair room5_dining_room)
	(placeinroom place29_receptacle22_chair room5_dining_room)
	(placeinroom place2_door_room11_utility_room room11_utility_room)
	(placeinroom place30_receptacle23_chair room5_dining_room)
	(placeinroom place31_receptacle24_chair room5_dining_room)
	(placeinroom place32_receptacle25_chair room5_dining_room)
	(placeinroom place33_receptacle26_chair room5_dining_room)
	(placeinroom place34_receptacle27_chair room5_dining_room)
	(placeinroom place35_receptacle28_couch room9_living_room)
	(placeinroom place36_receptacle33_bed room2_bedroom)
	(placeinroom place37_receptacle34_dining_table room5_dining_room)
	(placeinroom place38_receptacle35_dining_table room8_kitchen)
	(placeinroom place3_door_room9_living_room room9_living_room)
	(placeinroom place4_door_room5_dining_room room5_dining_room)
	(placeinroom place5_door_room2_bedroom room2_bedroom)
	(placeinroom place6_door_room3_corridor room3_corridor)
	(placeinroom place7_door_room4_corridor room4_corridor)
	(placeinroom place8_door_room6_empty_room room6_empty_room)
	(placeinroom place9_door_room7_empty_room room7_empty_room)
	(placelocation location_xneg12_ypos2_place5_room2_floora place5_door_room2_bedroom)
	(placelocation location_xneg19_yneg14_place3_room9_floorb place3_door_room9_living_room)
	(placelocation location_xneg24_ypos3_place36_room2_floora place36_receptacle33_bed)
	(placelocation location_xneg32_yneg18_place35_room9_floorb place35_receptacle28_couch)
	(placelocation location_xneg4_ypos6_place23_room9_floorb place23_receptacle16_chair)
	(placelocation location_xneg5_ypos7_place24_room9_floorb place24_receptacle17_chair)
	(placelocation location_xneg6_ypos5_place22_room9_floorb place22_receptacle15_chair)
	(placelocation location_xpos10_ypos18_place12_room8_floorb place12_receptacle2_sink)
	(placelocation location_xpos11_yneg30_place32_room5_floora place32_receptacle25_chair)
	(placelocation location_xpos12_yneg28_place27_room5_floora place27_receptacle20_chair)
	(placelocation location_xpos13_yneg33_place34_room5_floora place34_receptacle27_chair)
	(placelocation location_xpos15_yneg34_place4_room5_floora place4_door_room5_dining_room)
	(placelocation location_xpos16_yneg37_place28_room5_floora place28_receptacle21_chair)
	(placelocation location_xpos16_yneg3_place11_room8_floorb place11_receptacle1_oven)
	(placelocation location_xpos17_yneg34_place37_room5_floora place37_receptacle34_dining_table)
	(placelocation location_xpos17_yneg39_place30_room5_floora place30_receptacle23_chair)
	(placelocation location_xpos19_yneg32_place25_room5_floora place25_receptacle18_chair)
	(placelocation location_xpos19_yneg36_place33_room5_floora place33_receptacle26_chair)
	(placelocation location_xpos1_yneg44_place29_room5_floora place29_receptacle22_chair)
	(placelocation location_xpos20_yneg39_place31_room5_floora place31_receptacle24_chair)
	(placelocation location_xpos23_ypos26_place17_room8_floorb place17_receptacle10_chair)
	(placelocation location_xpos23_ypos9_place0_room8_floorb place0_door_room8_kitchen)
	(placelocation location_xpos24_ypos21_place18_room8_floorb place18_receptacle11_chair)
	(placelocation location_xpos28_ypos25_place38_room8_floorb place38_receptacle35_dining_table)
	(placelocation location_xpos28_ypos4_place6_room3_floora place6_door_room3_corridor)
	(placelocation location_xpos29_ypos30_place21_room8_floorb place21_receptacle14_chair)
	(placelocation location_xpos30_yneg2_place15_room8_floorb place15_receptacle5_refrigerator)
	(placelocation location_xpos32_ypos22_place20_room8_floorb place20_receptacle13_chair)
	(placelocation location_xpos33_ypos26_place19_room8_floorb place19_receptacle12_chair)
	(placelocation location_xpos34_yneg13_place7_room4_floorb place7_door_room4_corridor)
	(placelocation location_xpos3_yneg44_place26_room5_floora place26_receptacle19_chair)
	(placelocation location_xpos46_yneg32_place8_room6_floora place8_door_room6_empty_room)
	(placelocation location_xpos54_yneg34_place9_room7_floorb place9_door_room7_empty_room)
	(placelocation location_xpos57_ypos3_place2_room11_floora place2_door_room11_utility_room)
	(placelocation location_xpos60_yneg3_place1_room1_floorb place1_door_room1_bathroom)
	(placelocation location_xpos60_ypos12_place10_room10_floora place10_door_room10_staircase)
	(placelocation location_xpos61_yneg10_place14_room11_floora place14_receptacle4_sink)
	(placelocation location_xpos61_yneg9_place13_room1_floorb place13_receptacle3_sink)
	(placelocation location_xpos68_yneg7_place16_room1_floorb place16_receptacle9_toilet)
	(receptacleatlocation receptacle10_chair location_xpos23_ypos26_place17_room8_floorb)
	(receptacleatlocation receptacle11_chair location_xpos24_ypos21_place18_room8_floorb)
	(receptacleatlocation receptacle12_chair location_xpos33_ypos26_place19_room8_floorb)
	(receptacleatlocation receptacle13_chair location_xpos32_ypos22_place20_room8_floorb)
	(receptacleatlocation receptacle14_chair location_xpos29_ypos30_place21_room8_floorb)
	(receptacleatlocation receptacle15_chair location_xneg6_ypos5_place22_room9_floorb)
	(receptacleatlocation receptacle16_chair location_xneg4_ypos6_place23_room9_floorb)
	(receptacleatlocation receptacle17_chair location_xneg5_ypos7_place24_room9_floorb)
	(receptacleatlocation receptacle18_chair location_xpos19_yneg32_place25_room5_floora)
	(receptacleatlocation receptacle19_chair location_xpos3_yneg44_place26_room5_floora)
	(receptacleatlocation receptacle1_oven location_xpos16_yneg3_place11_room8_floorb)
	(receptacleatlocation receptacle20_chair location_xpos12_yneg28_place27_room5_floora)
	(receptacleatlocation receptacle21_chair location_xpos16_yneg37_place28_room5_floora)
	(receptacleatlocation receptacle22_chair location_xpos1_yneg44_place29_room5_floora)
	(receptacleatlocation receptacle23_chair location_xpos17_yneg39_place30_room5_floora)
	(receptacleatlocation receptacle24_chair location_xpos20_yneg39_place31_room5_floora)
	(receptacleatlocation receptacle25_chair location_xpos11_yneg30_place32_room5_floora)
	(receptacleatlocation receptacle26_chair location_xpos19_yneg36_place33_room5_floora)
	(receptacleatlocation receptacle27_chair location_xpos13_yneg33_place34_room5_floora)
	(receptacleatlocation receptacle28_couch location_xneg32_yneg18_place35_room9_floorb)
	(receptacleatlocation receptacle2_sink location_xpos10_ypos18_place12_room8_floorb)
	(receptacleatlocation receptacle33_bed location_xneg24_ypos3_place36_room2_floora)
	(receptacleatlocation receptacle34_dining_table location_xpos17_yneg34_place37_room5_floora)
	(receptacleatlocation receptacle35_dining_table location_xpos28_ypos25_place38_room8_floorb)
	(receptacleatlocation receptacle3_sink location_xpos61_yneg9_place13_room1_floorb)
	(receptacleatlocation receptacle4_sink location_xpos61_yneg10_place14_room11_floora)
	(receptacleatlocation receptacle5_refrigerator location_xpos30_yneg2_place15_room8_floorb)
	(receptacleatlocation receptacle9_toilet location_xpos68_yneg7_place16_room1_floorb)
	(receptacleclass receptacle10_chair chair)
	(receptacleclass receptacle11_chair chair)
	(receptacleclass receptacle12_chair chair)
	(receptacleclass receptacle13_chair chair)
	(receptacleclass receptacle14_chair chair)
	(receptacleclass receptacle15_chair chair)
	(receptacleclass receptacle16_chair chair)
	(receptacleclass receptacle17_chair chair)
	(receptacleclass receptacle18_chair chair)
	(receptacleclass receptacle19_chair chair)
	(receptacleclass receptacle1_oven oven)
	(receptacleclass receptacle20_chair chair)
	(receptacleclass receptacle21_chair chair)
	(receptacleclass receptacle22_chair chair)
	(receptacleclass receptacle23_chair chair)
	(receptacleclass receptacle24_chair chair)
	(receptacleclass receptacle25_chair chair)
	(receptacleclass receptacle26_chair chair)
	(receptacleclass receptacle27_chair chair)
	(receptacleclass receptacle28_couch couch)
	(receptacleclass receptacle2_sink sink)
	(receptacleclass receptacle33_bed bed)
	(receptacleclass receptacle34_dining_table diningtable)
	(receptacleclass receptacle35_dining_table diningtable)
	(receptacleclass receptacle3_sink sink)
	(receptacleclass receptacle4_sink sink)
	(receptacleclass receptacle5_refrigerator refrigerator)
	(receptacleclass receptacle9_toilet toilet)
	(receptacleopeningtype receptacle1_oven)
	(receptacleopeningtype receptacle5_refrigerator)
	(roomplace place0_door_room8_kitchen room8_kitchen)
	(roomplace place10_door_room10_staircase room10_staircase)
	(roomplace place1_door_room1_bathroom room1_bathroom)
	(roomplace place2_door_room11_utility_room room11_utility_room)
	(roomplace place3_door_room9_living_room room9_living_room)
	(roomplace place4_door_room5_dining_room room5_dining_room)
	(roomplace place5_door_room2_bedroom room2_bedroom)
	(roomplace place6_door_room3_corridor room3_corridor)
	(roomplace place7_door_room4_corridor room4_corridor)
	(roomplace place8_door_room6_empty_room room6_empty_room)
	(roomplace place9_door_room7_empty_room room7_empty_room)
	(roomsconnected room10_staircase room11_utility_room)
	(roomsconnected room10_staircase room1_bathroom)
	(roomsconnected room11_utility_room room10_staircase)
	(roomsconnected room11_utility_room room3_corridor)
	(roomsconnected room11_utility_room room6_empty_room)
	(roomsconnected room1_bathroom room10_staircase)
	(roomsconnected room1_bathroom room4_corridor)
	(roomsconnected room2_bedroom room3_corridor)
	(roomsconnected room3_corridor room11_utility_room)
	(roomsconnected room3_corridor room2_bedroom)
	(roomsconnected room4_corridor room1_bathroom)
	(roomsconnected room4_corridor room7_empty_room)
	(roomsconnected room4_corridor room8_kitchen)
	(roomsconnected room5_dining_room room6_empty_room)
	(roomsconnected room6_empty_room room11_utility_room)
	(roomsconnected room6_empty_room room5_dining_room)
	(roomsconnected room7_empty_room room4_corridor)
	(roomsconnected room8_kitchen room4_corridor)
	(roomsconnected room8_kitchen room9_living_room)
	(roomsconnected room9_living_room room8_kitchen)
  )
  (:goal (and
	(classrelation pottedplant toilet)
	(classrelation pottedplant oven)
	(classrelation bottle chair)
	(classrelation pottedplant bed)
	(classrelation pottedplant sink)))
)
