
(define (problem micanopytaskographyv5medium5bagslots5problem86) (:domain taskographyv5medium5bagslots5scrub)
  (:objects
        bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	bed - rclass
	book - iclass
	bottle - iclass
	bowl - iclass
	cake - iclass
	chair - rclass
	clock - iclass
	couch - rclass
	cup - iclass
	diningtable - rclass
	item10_bottle_smallitem - item
	item12_cup_smallitem - item
	item13_cup_smallitem - item
	item14_spoon_smallitem - item
	item15_spoon_smallitem - item
	item16_bowl_smallitem - item
	item17_bowl_smallitem - item
	item18_bowl_smallitem - item
	item19_bowl_smallitem - item
	item20_bowl_smallitem - item
	item21_bowl_smallitem - item
	item22_cake_mediumitem - item
	item23_cake_mediumitem - item
	item3_sports_ball_largeitem - item
	item47_potted_plant_largeitem - item
	item48_potted_plant_largeitem - item
	item49_potted_plant_largeitem - item
	item4_sports_ball_largeitem - item
	item5_bottle_smallitem - item
	item65_tv_largeitem - item
	item66_tv_largeitem - item
	item67_tv_largeitem - item
	item68_tv_largeitem - item
	item69_tv_largeitem - item
	item6_bottle_smallitem - item
	item70_tv_largeitem - item
	item7_bottle_smallitem - item
	item83_book_smallitem - item
	item84_book_smallitem - item
	item85_book_smallitem - item
	item86_book_smallitem - item
	item87_book_smallitem - item
	item88_book_smallitem - item
	item89_book_smallitem - item
	item8_bottle_smallitem - item
	item90_book_smallitem - item
	item91_clock_mediumitem - item
	item92_clock_mediumitem - item
	item93_vase_mediumitem - item
	item94_vase_mediumitem - item
	item95_vase_mediumitem - item
	item96_vase_mediumitem - item
	item97_vase_mediumitem - item
	item98_vase_mediumitem - item
	item9_bottle_smallitem - item
	location_xneg10_yneg2_place57_room20_floorb - location
	location_xneg11_ypos2_place25_room4_floora - location
	location_xneg13_ypos29_place85_room21_floorb - location
	location_xneg13_ypos44_place34_room9_floora - location
	location_xneg14_ypos41_place59_room7_floorc - location
	location_xneg14_ypos46_place59_room7_floorc - location
	location_xneg14_ypos54_place59_room7_floorc - location
	location_xneg16_ypos34_place85_room21_floorb - location
	location_xneg19_ypos54_place82_room10_floora - location
	location_xneg20_ypos62_place18_room10_floora - location
	location_xneg25_ypos44_place2_room24_floora - location
	location_xneg30_ypos52_place31_room24_floora - location
	location_xneg30_ypos54_place30_room24_floora - location
	location_xneg31_ypos52_place29_room24_floora - location
	location_xneg4_ypos44_place9_room21_floorb - location
	location_xneg5_yneg14_place57_room20_floorb - location
	location_xneg6_yneg32_place49_room20_floorb - location
	location_xneg9_yneg11_place67_room5_floorc - location
	location_xpos11_ypos60_place24_room23_floorb - location
	location_xpos12_ypos51_place65_room7_floorc - location
	location_xpos14_ypos31_place77_room1_floora - location
	location_xpos15_ypos9_place60_room4_floora - location
	location_xpos22_ypos34_place17_room1_floora - location
	location_xpos23_ypos36_place65_room7_floorc - location
	location_xpos23_ypos49_place21_room12_floorb - location
	location_xpos26_ypos40_place83_room1_floora - location
	location_xpos27_ypos23_place40_room20_floorb - location
	location_xpos29_yneg24_place32_room8_floorc - location
	location_xpos29_yneg30_place39_room20_floorb - location
	location_xpos29_yneg32_place14_room8_floorc - location
	location_xpos29_yneg5_place22_room13_floorc - location
	location_xpos30_ypos29_place71_room1_floora - location
	location_xpos30_ypos59_place20_room11_floora - location
	location_xpos31_ypos38_place84_room1_floora - location
	location_xpos32_yneg40_place33_room8_floorc - location
	location_xpos35_ypos27_place23_room14_floorc - location
	location_xpos37_yneg32_place48_room15_floorb - location
	location_xpos37_ypos37_place27_room25_floora - location
	location_xpos37_ypos38_place28_room25_floora - location
	location_xpos37_ypos38_place55_room25_floora - location
	location_xpos37_ypos63_place58_room16_floorb - location
	location_xpos38_yneg28_place47_room15_floorb - location
	location_xpos38_yneg31_place47_room15_floorb - location
	location_xpos38_yneg35_place48_room15_floorb - location
	location_xpos38_ypos37_place86_room19_floorb - location
	location_xpos38_ypos38_place86_room19_floorb - location
	location_xpos39_ypos38_place86_room19_floorb - location
	location_xpos3_ypos37_place13_room7_floorc - location
	location_xpos41_yneg39_place74_room2_floorc - location
	location_xpos41_ypos62_place55_room25_floora - location
	location_xpos42_ypos48_place52_room6_floorc - location
	location_xpos42_ypos64_place55_room25_floora - location
	location_xpos43_ypos31_place86_room19_floorb - location
	location_xpos43_ypos48_place63_room6_floorc - location
	location_xpos47_yneg9_place35_room17_floora - location
	location_xpos47_yneg9_place36_room17_floora - location
	location_xpos48_yneg1_place1_room17_floora - location
	location_xpos48_ypos1_place79_room2_floorc - location
	location_xpos49_ypos2_place79_room2_floorc - location
	location_xpos49_ypos62_place58_room16_floorb - location
	location_xpos50_yneg20_place70_room15_floorb - location
	location_xpos50_ypos60_place50_room16_floorb - location
	location_xpos50_ypos60_place68_room16_floorb - location
	location_xpos51_yneg22_place47_room15_floorb - location
	location_xpos51_ypos48_place55_room25_floora - location
	location_xpos52_ypos46_place7_room25_floora - location
	location_xpos52_ypos65_place53_room6_floorc - location
	location_xpos53_yneg15_place3_room15_floorb - location
	location_xpos53_yneg19_place4_room2_floorc - location
	location_xpos53_yneg39_place62_room15_floorb - location
	location_xpos53_yneg8_place42_room15_floorb - location
	location_xpos53_ypos2_place41_room15_floorb - location
	location_xpos53_ypos48_place8_room6_floorc - location
	location_xpos54_yneg12_place69_room15_floorb - location
	location_xpos54_yneg27_place48_room15_floorb - location
	location_xpos54_ypos34_place5_room19_floorb - location
	location_xpos54_ypos62_place11_room16_floorb - location
	location_xpos55_yneg17_place45_room15_floorb - location
	location_xpos56_ypos17_place0_room18_floora - location
	location_xpos56_ypos2_place43_room15_floorb - location
	location_xpos56_ypos47_place54_room25_floora - location
	location_xpos56_ypos68_place53_room6_floorc - location
	location_xpos57_yneg20_place46_room15_floorb - location
	location_xpos57_ypos2_place79_room2_floorc - location
	location_xpos57_ypos31_place64_room6_floorc - location
	location_xpos58_yneg10_place37_room17_floora - location
	location_xpos58_ypos7_place80_room3_floorc - location
	location_xpos59_yneg12_place37_room17_floora - location
	location_xpos59_yneg5_place44_room15_floorb - location
	location_xpos59_ypos15_place6_room3_floorc - location
	location_xpos59_ypos1_place72_room2_floorc - location
	location_xpos5_yneg29_place66_room5_floorc - location
	location_xpos60_ypos1_place72_room2_floorc - location
	location_xpos60_ypos29_place64_room6_floorc - location
	location_xpos62_ypos6_place73_room3_floorc - location
	location_xpos63_ypos0_place37_room17_floora - location
	location_xpos64_yneg19_place81_room2_floorc - location
	location_xpos65_yneg8_place37_room17_floora - location
	location_xpos65_ypos62_place53_room6_floorc - location
	location_xpos67_yneg1_place72_room2_floorc - location
	location_xpos67_ypos30_place51_room6_floorc - location
	location_xpos67_ypos8_place73_room3_floorc - location
	location_xpos68_ypos2_place37_room17_floora - location
	location_xpos68_ypos2_place72_room2_floorc - location
	location_xpos68_ypos33_place78_room19_floorb - location
	location_xpos68_ypos46_place76_room19_floorb - location
	location_xpos69_yneg34_place48_room15_floorb - location
	location_xpos69_ypos46_place75_room19_floorb - location
	location_xpos6_yneg18_place16_room5_floorc - location
	location_xpos70_yneg34_place48_room15_floorb - location
	location_xpos70_ypos53_place75_room19_floorb - location
	location_xpos7_ypos54_place38_room21_floorb - location
	location_xpos7_ypos62_place56_room22_floora - location
	location_xpos8_ypos4_place15_room4_floora - location
	location_xpos9_yneg14_place61_room20_floorb - location
	location_xpos9_yneg5_place10_room20_floorb - location
	location_xpos9_ypos39_place19_room9_floora - location
	location_xpos9_ypos63_place12_room22_floora - location
	microwave - rclass
	oven - rclass
	place0_door_room18_kitchen - place
	place10_door_room20_living_room - place
	place11_door_room16_dining_room - place
	place12_door_room22_staircase - place
	place13_door_room7_childs_room - place
	place14_door_room8_closet - place
	place15_door_room4_bedroom - place
	place16_door_room5_bedroom - place
	place17_door_room1_bathroom - place
	place18_door_room10_corridor - place
	place19_door_room9_corridor - place
	place1_door_room17_home_office - place
	place20_door_room11_corridor - place
	place21_door_room12_corridor - place
	place22_door_room13_corridor - place
	place23_door_room14_corridor - place
	place24_door_room23_staircase - place
	place25_item65_tv - place
	place27_item66_tv - place
	place28_item68_tv - place
	place29_item5_bottle - place
	place2_door_room24_storage - place
	place30_item6_bottle - place
	place31_item7_bottle - place
	place32_item70_tv - place
	place33_item49_potted_plant - place
	place34_item83_book - place
	place35_item84_book - place
	place36_item85_book - place
	place37_receptacle24_chair - place
	place38_receptacle25_chair - place
	place39_receptacle26_chair - place
	place3_door_room15_dining_room - place
	place40_receptacle27_chair - place
	place41_receptacle28_chair - place
	place42_receptacle29_chair - place
	place43_receptacle30_chair - place
	place44_receptacle31_chair - place
	place45_receptacle32_chair - place
	place46_receptacle33_chair - place
	place47_receptacle34_chair - place
	place48_receptacle35_chair - place
	place49_receptacle36_chair - place
	place4_door_room2_bathroom - place
	place50_receptacle37_chair - place
	place51_receptacle38_chair - place
	place52_receptacle39_chair - place
	place53_receptacle40_chair - place
	place54_receptacle41_couch - place
	place55_receptacle42_couch - place
	place56_receptacle43_couch - place
	place57_receptacle44_couch - place
	place58_receptacle45_couch - place
	place59_receptacle46_couch - place
	place5_door_room19_kitchen - place
	place60_receptacle50_bed - place
	place61_receptacle51_bed - place
	place62_receptacle52_bed - place
	place63_receptacle53_bed - place
	place64_receptacle54_bed - place
	place65_receptacle55_bed - place
	place66_receptacle56_bed - place
	place67_receptacle57_bed - place
	place68_receptacle58_dining_table - place
	place69_receptacle59_dining_table - place
	place6_door_room3_bathroom - place
	place70_receptacle60_dining_table - place
	place71_receptacle61_toilet - place
	place72_receptacle62_toilet - place
	place73_receptacle63_toilet - place
	place74_receptacle64_toilet - place
	place75_receptacle71_microwave - place
	place76_receptacle72_oven - place
	place77_receptacle73_sink - place
	place78_receptacle74_sink - place
	place79_receptacle75_sink - place
	place7_door_room25_television_room - place
	place80_receptacle76_sink - place
	place81_receptacle77_sink - place
	place82_receptacle78_refrigerator - place
	place83_receptacle79_refrigerator - place
	place84_receptacle80_refrigerator - place
	place85_receptacle81_refrigerator - place
	place86_receptacle82_refrigerator - place
	place8_door_room6_childs_room - place
	place9_door_room21_lobby - place
	pottedplant - iclass
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle30_chair - receptacle
	receptacle31_chair - receptacle
	receptacle32_chair - receptacle
	receptacle33_chair - receptacle
	receptacle34_chair - receptacle
	receptacle35_chair - receptacle
	receptacle36_chair - receptacle
	receptacle37_chair - receptacle
	receptacle38_chair - receptacle
	receptacle39_chair - receptacle
	receptacle40_chair - receptacle
	receptacle41_couch - receptacle
	receptacle42_couch - receptacle
	receptacle43_couch - receptacle
	receptacle44_couch - receptacle
	receptacle45_couch - receptacle
	receptacle46_couch - receptacle
	receptacle50_bed - receptacle
	receptacle51_bed - receptacle
	receptacle52_bed - receptacle
	receptacle53_bed - receptacle
	receptacle54_bed - receptacle
	receptacle55_bed - receptacle
	receptacle56_bed - receptacle
	receptacle57_bed - receptacle
	receptacle58_dining_table - receptacle
	receptacle59_dining_table - receptacle
	receptacle60_dining_table - receptacle
	receptacle61_toilet - receptacle
	receptacle62_toilet - receptacle
	receptacle63_toilet - receptacle
	receptacle64_toilet - receptacle
	receptacle71_microwave - receptacle
	receptacle72_oven - receptacle
	receptacle73_sink - receptacle
	receptacle74_sink - receptacle
	receptacle75_sink - receptacle
	receptacle76_sink - receptacle
	receptacle77_sink - receptacle
	receptacle78_refrigerator - receptacle
	receptacle79_refrigerator - receptacle
	receptacle80_refrigerator - receptacle
	receptacle81_refrigerator - receptacle
	receptacle82_refrigerator - receptacle
	refrigerator - rclass
	robot - agent
	room10_corridor - room
	room11_corridor - room
	room12_corridor - room
	room13_corridor - room
	room14_corridor - room
	room15_dining_room - room
	room16_dining_room - room
	room17_home_office - room
	room18_kitchen - room
	room19_kitchen - room
	room1_bathroom - room
	room20_living_room - room
	room21_lobby - room
	room22_staircase - room
	room23_staircase - room
	room24_storage - room
	room25_television_room - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_childs_room - room
	room7_childs_room - room
	room8_closet - room
	room9_corridor - room
	sink - rclass
	spoon - iclass
	sportsball - iclass
	toilet - rclass
	tv - iclass
	vase - iclass
  )
  (:init 
	(atlocation robot location_xpos9_ypos39_place19_room9_floora)
	(classrelation book bed)
	(classrelation book chair)
	(classrelation book couch)
	(classrelation book refrigerator)
	(classrelation bottle chair)
	(classrelation bottle sink)
	(classrelation bowl chair)
	(classrelation bowl couch)
	(classrelation bowl refrigerator)
	(classrelation cake chair)
	(classrelation clock couch)
	(classrelation clock sink)
	(classrelation cup chair)
	(classrelation cup toilet)
	(classrelation pottedplant chair)
	(classrelation pottedplant diningtable)
	(classrelation spoon microwave)
	(classrelation spoon toilet)
	(classrelation sportsball chair)
	(classrelation tv chair)
	(classrelation tv couch)
	(classrelation vase bed)
	(classrelation vase couch)
	(classrelation vase diningtable)
	(classrelation vase refrigerator)
	(classrelation vase toilet)
	(inanyreceptacle item10_bottle_smallitem)
	(inanyreceptacle item12_cup_smallitem)
	(inanyreceptacle item13_cup_smallitem)
	(inanyreceptacle item14_spoon_smallitem)
	(inanyreceptacle item15_spoon_smallitem)
	(inanyreceptacle item16_bowl_smallitem)
	(inanyreceptacle item17_bowl_smallitem)
	(inanyreceptacle item18_bowl_smallitem)
	(inanyreceptacle item19_bowl_smallitem)
	(inanyreceptacle item20_bowl_smallitem)
	(inanyreceptacle item21_bowl_smallitem)
	(inanyreceptacle item22_cake_mediumitem)
	(inanyreceptacle item23_cake_mediumitem)
	(inanyreceptacle item3_sports_ball_largeitem)
	(inanyreceptacle item47_potted_plant_largeitem)
	(inanyreceptacle item48_potted_plant_largeitem)
	(inanyreceptacle item4_sports_ball_largeitem)
	(inanyreceptacle item67_tv_largeitem)
	(inanyreceptacle item69_tv_largeitem)
	(inanyreceptacle item86_book_smallitem)
	(inanyreceptacle item87_book_smallitem)
	(inanyreceptacle item88_book_smallitem)
	(inanyreceptacle item89_book_smallitem)
	(inanyreceptacle item8_bottle_smallitem)
	(inanyreceptacle item90_book_smallitem)
	(inanyreceptacle item91_clock_mediumitem)
	(inanyreceptacle item92_clock_mediumitem)
	(inanyreceptacle item93_vase_mediumitem)
	(inanyreceptacle item94_vase_mediumitem)
	(inanyreceptacle item95_vase_mediumitem)
	(inanyreceptacle item96_vase_mediumitem)
	(inanyreceptacle item97_vase_mediumitem)
	(inanyreceptacle item98_vase_mediumitem)
	(inanyreceptacle item9_bottle_smallitem)
	(inplace robot place19_door_room9_corridor)
	(inreceptacle item10_bottle_smallitem receptacle75_sink)
	(inreceptacle item12_cup_smallitem receptacle34_chair)
	(inreceptacle item13_cup_smallitem receptacle62_toilet)
	(inreceptacle item14_spoon_smallitem receptacle71_microwave)
	(inreceptacle item15_spoon_smallitem receptacle63_toilet)
	(inreceptacle item16_bowl_smallitem receptacle42_couch)
	(inreceptacle item17_bowl_smallitem receptacle42_couch)
	(inreceptacle item18_bowl_smallitem receptacle35_chair)
	(inreceptacle item19_bowl_smallitem receptacle34_chair)
	(inreceptacle item20_bowl_smallitem receptacle82_refrigerator)
	(inreceptacle item21_bowl_smallitem receptacle82_refrigerator)
	(inreceptacle item22_cake_mediumitem receptacle40_chair)
	(inreceptacle item23_cake_mediumitem receptacle40_chair)
	(inreceptacle item3_sports_ball_largeitem receptacle24_chair)
	(inreceptacle item47_potted_plant_largeitem receptacle59_dining_table)
	(inreceptacle item48_potted_plant_largeitem receptacle35_chair)
	(inreceptacle item4_sports_ball_largeitem receptacle24_chair)
	(inreceptacle item67_tv_largeitem receptacle42_couch)
	(inreceptacle item69_tv_largeitem receptacle24_chair)
	(inreceptacle item86_book_smallitem receptacle24_chair)
	(inreceptacle item87_book_smallitem receptacle82_refrigerator)
	(inreceptacle item88_book_smallitem receptacle54_bed)
	(inreceptacle item89_book_smallitem receptacle46_couch)
	(inreceptacle item8_bottle_smallitem receptacle35_chair)
	(inreceptacle item90_book_smallitem receptacle46_couch)
	(inreceptacle item91_clock_mediumitem receptacle45_couch)
	(inreceptacle item92_clock_mediumitem receptacle75_sink)
	(inreceptacle item93_vase_mediumitem receptacle81_refrigerator)
	(inreceptacle item94_vase_mediumitem receptacle44_couch)
	(inreceptacle item95_vase_mediumitem receptacle59_dining_table)
	(inreceptacle item96_vase_mediumitem receptacle55_bed)
	(inreceptacle item97_vase_mediumitem receptacle62_toilet)
	(inreceptacle item98_vase_mediumitem receptacle62_toilet)
	(inreceptacle item9_bottle_smallitem receptacle35_chair)
	(inroom robot room9_corridor)
	(itematlocation item10_bottle_smallitem location_xpos49_ypos2_place79_room2_floorc)
	(itematlocation item12_cup_smallitem location_xpos38_yneg28_place47_room15_floorb)
	(itematlocation item13_cup_smallitem location_xpos59_ypos1_place72_room2_floorc)
	(itematlocation item14_spoon_smallitem location_xpos70_ypos53_place75_room19_floorb)
	(itematlocation item15_spoon_smallitem location_xpos62_ypos6_place73_room3_floorc)
	(itematlocation item16_bowl_smallitem location_xpos42_ypos64_place55_room25_floora)
	(itematlocation item17_bowl_smallitem location_xpos41_ypos62_place55_room25_floora)
	(itematlocation item18_bowl_smallitem location_xpos69_yneg34_place48_room15_floorb)
	(itematlocation item19_bowl_smallitem location_xpos38_yneg31_place47_room15_floorb)
	(itematlocation item20_bowl_smallitem location_xpos39_ypos38_place86_room19_floorb)
	(itematlocation item21_bowl_smallitem location_xpos38_ypos37_place86_room19_floorb)
	(itematlocation item22_cake_mediumitem location_xpos52_ypos65_place53_room6_floorc)
	(itematlocation item23_cake_mediumitem location_xpos56_ypos68_place53_room6_floorc)
	(itematlocation item3_sports_ball_largeitem location_xpos59_yneg12_place37_room17_floora)
	(itematlocation item47_potted_plant_largeitem location_xpos54_yneg12_place69_room15_floorb)
	(itematlocation item48_potted_plant_largeitem location_xpos70_yneg34_place48_room15_floorb)
	(itematlocation item49_potted_plant_largeitem location_xpos32_yneg40_place33_room8_floorc)
	(itematlocation item4_sports_ball_largeitem location_xpos58_yneg10_place37_room17_floora)
	(itematlocation item5_bottle_smallitem location_xneg31_ypos52_place29_room24_floora)
	(itematlocation item65_tv_largeitem location_xneg11_ypos2_place25_room4_floora)
	(itematlocation item66_tv_largeitem location_xpos37_ypos37_place27_room25_floora)
	(itematlocation item67_tv_largeitem location_xpos37_ypos38_place55_room25_floora)
	(itematlocation item68_tv_largeitem location_xpos37_ypos38_place28_room25_floora)
	(itematlocation item69_tv_largeitem location_xpos68_ypos2_place37_room17_floora)
	(itematlocation item6_bottle_smallitem location_xneg30_ypos54_place30_room24_floora)
	(itematlocation item70_tv_largeitem location_xpos29_yneg24_place32_room8_floorc)
	(itematlocation item7_bottle_smallitem location_xneg30_ypos52_place31_room24_floora)
	(itematlocation item83_book_smallitem location_xneg13_ypos44_place34_room9_floora)
	(itematlocation item84_book_smallitem location_xpos47_yneg9_place35_room17_floora)
	(itematlocation item85_book_smallitem location_xpos47_yneg9_place36_room17_floora)
	(itematlocation item86_book_smallitem location_xpos65_yneg8_place37_room17_floora)
	(itematlocation item87_book_smallitem location_xpos38_ypos38_place86_room19_floorb)
	(itematlocation item88_book_smallitem location_xpos57_ypos31_place64_room6_floorc)
	(itematlocation item89_book_smallitem location_xneg14_ypos46_place59_room7_floorc)
	(itematlocation item8_bottle_smallitem location_xpos38_yneg35_place48_room15_floorb)
	(itematlocation item90_book_smallitem location_xneg14_ypos41_place59_room7_floorc)
	(itematlocation item91_clock_mediumitem location_xpos37_ypos63_place58_room16_floorb)
	(itematlocation item92_clock_mediumitem location_xpos57_ypos2_place79_room2_floorc)
	(itematlocation item93_vase_mediumitem location_xneg16_ypos34_place85_room21_floorb)
	(itematlocation item94_vase_mediumitem location_xneg10_yneg2_place57_room20_floorb)
	(itematlocation item95_vase_mediumitem location_xpos54_yneg12_place69_room15_floorb)
	(itematlocation item96_vase_mediumitem location_xpos23_ypos36_place65_room7_floorc)
	(itematlocation item97_vase_mediumitem location_xpos60_ypos1_place72_room2_floorc)
	(itematlocation item98_vase_mediumitem location_xpos68_ypos2_place72_room2_floorc)
	(itematlocation item9_bottle_smallitem location_xpos37_yneg32_place48_room15_floorb)
	(itemclass item10_bottle_smallitem bottle)
	(itemclass item12_cup_smallitem cup)
	(itemclass item13_cup_smallitem cup)
	(itemclass item14_spoon_smallitem spoon)
	(itemclass item15_spoon_smallitem spoon)
	(itemclass item16_bowl_smallitem bowl)
	(itemclass item17_bowl_smallitem bowl)
	(itemclass item18_bowl_smallitem bowl)
	(itemclass item19_bowl_smallitem bowl)
	(itemclass item20_bowl_smallitem bowl)
	(itemclass item21_bowl_smallitem bowl)
	(itemclass item22_cake_mediumitem cake)
	(itemclass item23_cake_mediumitem cake)
	(itemclass item3_sports_ball_largeitem sportsball)
	(itemclass item47_potted_plant_largeitem pottedplant)
	(itemclass item48_potted_plant_largeitem pottedplant)
	(itemclass item49_potted_plant_largeitem pottedplant)
	(itemclass item4_sports_ball_largeitem sportsball)
	(itemclass item5_bottle_smallitem bottle)
	(itemclass item65_tv_largeitem tv)
	(itemclass item66_tv_largeitem tv)
	(itemclass item67_tv_largeitem tv)
	(itemclass item68_tv_largeitem tv)
	(itemclass item69_tv_largeitem tv)
	(itemclass item6_bottle_smallitem bottle)
	(itemclass item70_tv_largeitem tv)
	(itemclass item7_bottle_smallitem bottle)
	(itemclass item83_book_smallitem book)
	(itemclass item84_book_smallitem book)
	(itemclass item85_book_smallitem book)
	(itemclass item86_book_smallitem book)
	(itemclass item87_book_smallitem book)
	(itemclass item88_book_smallitem book)
	(itemclass item89_book_smallitem book)
	(itemclass item8_bottle_smallitem bottle)
	(itemclass item90_book_smallitem book)
	(itemclass item91_clock_mediumitem clock)
	(itemclass item92_clock_mediumitem clock)
	(itemclass item93_vase_mediumitem vase)
	(itemclass item94_vase_mediumitem vase)
	(itemclass item95_vase_mediumitem vase)
	(itemclass item96_vase_mediumitem vase)
	(itemclass item97_vase_mediumitem vase)
	(itemclass item98_vase_mediumitem vase)
	(itemclass item9_bottle_smallitem bottle)
	(largeitem item3_sports_ball_largeitem)
	(largeitem item47_potted_plant_largeitem)
	(largeitem item48_potted_plant_largeitem)
	(largeitem item49_potted_plant_largeitem)
	(largeitem item4_sports_ball_largeitem)
	(largeitem item65_tv_largeitem)
	(largeitem item66_tv_largeitem)
	(largeitem item67_tv_largeitem)
	(largeitem item68_tv_largeitem)
	(largeitem item69_tv_largeitem)
	(largeitem item70_tv_largeitem)
	(locationinplace location_xneg10_yneg2_place57_room20_floorb place57_receptacle44_couch)
	(locationinplace location_xneg11_ypos2_place25_room4_floora place25_item65_tv)
	(locationinplace location_xneg13_ypos29_place85_room21_floorb place85_receptacle81_refrigerator)
	(locationinplace location_xneg13_ypos44_place34_room9_floora place34_item83_book)
	(locationinplace location_xneg14_ypos41_place59_room7_floorc place59_receptacle46_couch)
	(locationinplace location_xneg14_ypos46_place59_room7_floorc place59_receptacle46_couch)
	(locationinplace location_xneg14_ypos54_place59_room7_floorc place59_receptacle46_couch)
	(locationinplace location_xneg16_ypos34_place85_room21_floorb place85_receptacle81_refrigerator)
	(locationinplace location_xneg19_ypos54_place82_room10_floora place82_receptacle78_refrigerator)
	(locationinplace location_xneg20_ypos62_place18_room10_floora place18_door_room10_corridor)
	(locationinplace location_xneg25_ypos44_place2_room24_floora place2_door_room24_storage)
	(locationinplace location_xneg30_ypos52_place31_room24_floora place31_item7_bottle)
	(locationinplace location_xneg30_ypos54_place30_room24_floora place30_item6_bottle)
	(locationinplace location_xneg31_ypos52_place29_room24_floora place29_item5_bottle)
	(locationinplace location_xneg4_ypos44_place9_room21_floorb place9_door_room21_lobby)
	(locationinplace location_xneg5_yneg14_place57_room20_floorb place57_receptacle44_couch)
	(locationinplace location_xneg6_yneg32_place49_room20_floorb place49_receptacle36_chair)
	(locationinplace location_xneg9_yneg11_place67_room5_floorc place67_receptacle57_bed)
	(locationinplace location_xpos11_ypos60_place24_room23_floorb place24_door_room23_staircase)
	(locationinplace location_xpos12_ypos51_place65_room7_floorc place65_receptacle55_bed)
	(locationinplace location_xpos14_ypos31_place77_room1_floora place77_receptacle73_sink)
	(locationinplace location_xpos15_ypos9_place60_room4_floora place60_receptacle50_bed)
	(locationinplace location_xpos22_ypos34_place17_room1_floora place17_door_room1_bathroom)
	(locationinplace location_xpos23_ypos36_place65_room7_floorc place65_receptacle55_bed)
	(locationinplace location_xpos23_ypos49_place21_room12_floorb place21_door_room12_corridor)
	(locationinplace location_xpos26_ypos40_place83_room1_floora place83_receptacle79_refrigerator)
	(locationinplace location_xpos27_ypos23_place40_room20_floorb place40_receptacle27_chair)
	(locationinplace location_xpos29_yneg24_place32_room8_floorc place32_item70_tv)
	(locationinplace location_xpos29_yneg30_place39_room20_floorb place39_receptacle26_chair)
	(locationinplace location_xpos29_yneg32_place14_room8_floorc place14_door_room8_closet)
	(locationinplace location_xpos29_yneg5_place22_room13_floorc place22_door_room13_corridor)
	(locationinplace location_xpos30_ypos29_place71_room1_floora place71_receptacle61_toilet)
	(locationinplace location_xpos30_ypos59_place20_room11_floora place20_door_room11_corridor)
	(locationinplace location_xpos31_ypos38_place84_room1_floora place84_receptacle80_refrigerator)
	(locationinplace location_xpos32_yneg40_place33_room8_floorc place33_item49_potted_plant)
	(locationinplace location_xpos35_ypos27_place23_room14_floorc place23_door_room14_corridor)
	(locationinplace location_xpos37_yneg32_place48_room15_floorb place48_receptacle35_chair)
	(locationinplace location_xpos37_ypos37_place27_room25_floora place27_item66_tv)
	(locationinplace location_xpos37_ypos38_place28_room25_floora place28_item68_tv)
	(locationinplace location_xpos37_ypos38_place55_room25_floora place55_receptacle42_couch)
	(locationinplace location_xpos37_ypos63_place58_room16_floorb place58_receptacle45_couch)
	(locationinplace location_xpos38_yneg28_place47_room15_floorb place47_receptacle34_chair)
	(locationinplace location_xpos38_yneg31_place47_room15_floorb place47_receptacle34_chair)
	(locationinplace location_xpos38_yneg35_place48_room15_floorb place48_receptacle35_chair)
	(locationinplace location_xpos38_ypos37_place86_room19_floorb place86_receptacle82_refrigerator)
	(locationinplace location_xpos38_ypos38_place86_room19_floorb place86_receptacle82_refrigerator)
	(locationinplace location_xpos39_ypos38_place86_room19_floorb place86_receptacle82_refrigerator)
	(locationinplace location_xpos3_ypos37_place13_room7_floorc place13_door_room7_childs_room)
	(locationinplace location_xpos41_yneg39_place74_room2_floorc place74_receptacle64_toilet)
	(locationinplace location_xpos41_ypos62_place55_room25_floora place55_receptacle42_couch)
	(locationinplace location_xpos42_ypos48_place52_room6_floorc place52_receptacle39_chair)
	(locationinplace location_xpos42_ypos64_place55_room25_floora place55_receptacle42_couch)
	(locationinplace location_xpos43_ypos31_place86_room19_floorb place86_receptacle82_refrigerator)
	(locationinplace location_xpos43_ypos48_place63_room6_floorc place63_receptacle53_bed)
	(locationinplace location_xpos47_yneg9_place35_room17_floora place35_item84_book)
	(locationinplace location_xpos47_yneg9_place36_room17_floora place36_item85_book)
	(locationinplace location_xpos48_yneg1_place1_room17_floora place1_door_room17_home_office)
	(locationinplace location_xpos48_ypos1_place79_room2_floorc place79_receptacle75_sink)
	(locationinplace location_xpos49_ypos2_place79_room2_floorc place79_receptacle75_sink)
	(locationinplace location_xpos49_ypos62_place58_room16_floorb place58_receptacle45_couch)
	(locationinplace location_xpos50_yneg20_place70_room15_floorb place70_receptacle60_dining_table)
	(locationinplace location_xpos50_ypos60_place50_room16_floorb place50_receptacle37_chair)
	(locationinplace location_xpos50_ypos60_place68_room16_floorb place68_receptacle58_dining_table)
	(locationinplace location_xpos51_yneg22_place47_room15_floorb place47_receptacle34_chair)
	(locationinplace location_xpos51_ypos48_place55_room25_floora place55_receptacle42_couch)
	(locationinplace location_xpos52_ypos46_place7_room25_floora place7_door_room25_television_room)
	(locationinplace location_xpos52_ypos65_place53_room6_floorc place53_receptacle40_chair)
	(locationinplace location_xpos53_yneg15_place3_room15_floorb place3_door_room15_dining_room)
	(locationinplace location_xpos53_yneg19_place4_room2_floorc place4_door_room2_bathroom)
	(locationinplace location_xpos53_yneg39_place62_room15_floorb place62_receptacle52_bed)
	(locationinplace location_xpos53_yneg8_place42_room15_floorb place42_receptacle29_chair)
	(locationinplace location_xpos53_ypos2_place41_room15_floorb place41_receptacle28_chair)
	(locationinplace location_xpos53_ypos48_place8_room6_floorc place8_door_room6_childs_room)
	(locationinplace location_xpos54_yneg12_place69_room15_floorb place69_receptacle59_dining_table)
	(locationinplace location_xpos54_yneg27_place48_room15_floorb place48_receptacle35_chair)
	(locationinplace location_xpos54_ypos34_place5_room19_floorb place5_door_room19_kitchen)
	(locationinplace location_xpos54_ypos62_place11_room16_floorb place11_door_room16_dining_room)
	(locationinplace location_xpos55_yneg17_place45_room15_floorb place45_receptacle32_chair)
	(locationinplace location_xpos56_ypos17_place0_room18_floora place0_door_room18_kitchen)
	(locationinplace location_xpos56_ypos2_place43_room15_floorb place43_receptacle30_chair)
	(locationinplace location_xpos56_ypos47_place54_room25_floora place54_receptacle41_couch)
	(locationinplace location_xpos56_ypos68_place53_room6_floorc place53_receptacle40_chair)
	(locationinplace location_xpos57_yneg20_place46_room15_floorb place46_receptacle33_chair)
	(locationinplace location_xpos57_ypos2_place79_room2_floorc place79_receptacle75_sink)
	(locationinplace location_xpos57_ypos31_place64_room6_floorc place64_receptacle54_bed)
	(locationinplace location_xpos58_yneg10_place37_room17_floora place37_receptacle24_chair)
	(locationinplace location_xpos58_ypos7_place80_room3_floorc place80_receptacle76_sink)
	(locationinplace location_xpos59_yneg12_place37_room17_floora place37_receptacle24_chair)
	(locationinplace location_xpos59_yneg5_place44_room15_floorb place44_receptacle31_chair)
	(locationinplace location_xpos59_ypos15_place6_room3_floorc place6_door_room3_bathroom)
	(locationinplace location_xpos59_ypos1_place72_room2_floorc place72_receptacle62_toilet)
	(locationinplace location_xpos5_yneg29_place66_room5_floorc place66_receptacle56_bed)
	(locationinplace location_xpos60_ypos1_place72_room2_floorc place72_receptacle62_toilet)
	(locationinplace location_xpos60_ypos29_place64_room6_floorc place64_receptacle54_bed)
	(locationinplace location_xpos62_ypos6_place73_room3_floorc place73_receptacle63_toilet)
	(locationinplace location_xpos63_ypos0_place37_room17_floora place37_receptacle24_chair)
	(locationinplace location_xpos64_yneg19_place81_room2_floorc place81_receptacle77_sink)
	(locationinplace location_xpos65_yneg8_place37_room17_floora place37_receptacle24_chair)
	(locationinplace location_xpos65_ypos62_place53_room6_floorc place53_receptacle40_chair)
	(locationinplace location_xpos67_yneg1_place72_room2_floorc place72_receptacle62_toilet)
	(locationinplace location_xpos67_ypos30_place51_room6_floorc place51_receptacle38_chair)
	(locationinplace location_xpos67_ypos8_place73_room3_floorc place73_receptacle63_toilet)
	(locationinplace location_xpos68_ypos2_place37_room17_floora place37_receptacle24_chair)
	(locationinplace location_xpos68_ypos2_place72_room2_floorc place72_receptacle62_toilet)
	(locationinplace location_xpos68_ypos33_place78_room19_floorb place78_receptacle74_sink)
	(locationinplace location_xpos68_ypos46_place76_room19_floorb place76_receptacle72_oven)
	(locationinplace location_xpos69_yneg34_place48_room15_floorb place48_receptacle35_chair)
	(locationinplace location_xpos69_ypos46_place75_room19_floorb place75_receptacle71_microwave)
	(locationinplace location_xpos6_yneg18_place16_room5_floorc place16_door_room5_bedroom)
	(locationinplace location_xpos70_yneg34_place48_room15_floorb place48_receptacle35_chair)
	(locationinplace location_xpos70_ypos53_place75_room19_floorb place75_receptacle71_microwave)
	(locationinplace location_xpos7_ypos54_place38_room21_floorb place38_receptacle25_chair)
	(locationinplace location_xpos7_ypos62_place56_room22_floora place56_receptacle43_couch)
	(locationinplace location_xpos8_ypos4_place15_room4_floora place15_door_room4_bedroom)
	(locationinplace location_xpos9_yneg14_place61_room20_floorb place61_receptacle51_bed)
	(locationinplace location_xpos9_yneg5_place10_room20_floorb place10_door_room20_living_room)
	(locationinplace location_xpos9_ypos39_place19_room9_floora place19_door_room9_corridor)
	(locationinplace location_xpos9_ypos63_place12_room22_floora place12_door_room22_staircase)
	(mediumitem item22_cake_mediumitem)
	(mediumitem item23_cake_mediumitem)
	(mediumitem item91_clock_mediumitem)
	(mediumitem item92_clock_mediumitem)
	(mediumitem item93_vase_mediumitem)
	(mediumitem item94_vase_mediumitem)
	(mediumitem item95_vase_mediumitem)
	(mediumitem item96_vase_mediumitem)
	(mediumitem item97_vase_mediumitem)
	(mediumitem item98_vase_mediumitem)
	(placeinroom place0_door_room18_kitchen room18_kitchen)
	(placeinroom place10_door_room20_living_room room20_living_room)
	(placeinroom place11_door_room16_dining_room room16_dining_room)
	(placeinroom place12_door_room22_staircase room22_staircase)
	(placeinroom place13_door_room7_childs_room room7_childs_room)
	(placeinroom place14_door_room8_closet room8_closet)
	(placeinroom place15_door_room4_bedroom room4_bedroom)
	(placeinroom place16_door_room5_bedroom room5_bedroom)
	(placeinroom place17_door_room1_bathroom room1_bathroom)
	(placeinroom place18_door_room10_corridor room10_corridor)
	(placeinroom place19_door_room9_corridor room9_corridor)
	(placeinroom place1_door_room17_home_office room17_home_office)
	(placeinroom place20_door_room11_corridor room11_corridor)
	(placeinroom place21_door_room12_corridor room12_corridor)
	(placeinroom place22_door_room13_corridor room13_corridor)
	(placeinroom place23_door_room14_corridor room14_corridor)
	(placeinroom place24_door_room23_staircase room23_staircase)
	(placeinroom place25_item65_tv room4_bedroom)
	(placeinroom place27_item66_tv room25_television_room)
	(placeinroom place28_item68_tv room25_television_room)
	(placeinroom place29_item5_bottle room24_storage)
	(placeinroom place2_door_room24_storage room24_storage)
	(placeinroom place30_item6_bottle room24_storage)
	(placeinroom place31_item7_bottle room24_storage)
	(placeinroom place32_item70_tv room8_closet)
	(placeinroom place33_item49_potted_plant room8_closet)
	(placeinroom place34_item83_book room9_corridor)
	(placeinroom place35_item84_book room17_home_office)
	(placeinroom place36_item85_book room17_home_office)
	(placeinroom place37_receptacle24_chair room17_home_office)
	(placeinroom place38_receptacle25_chair room21_lobby)
	(placeinroom place39_receptacle26_chair room20_living_room)
	(placeinroom place3_door_room15_dining_room room15_dining_room)
	(placeinroom place40_receptacle27_chair room20_living_room)
	(placeinroom place41_receptacle28_chair room15_dining_room)
	(placeinroom place42_receptacle29_chair room15_dining_room)
	(placeinroom place43_receptacle30_chair room15_dining_room)
	(placeinroom place44_receptacle31_chair room15_dining_room)
	(placeinroom place45_receptacle32_chair room15_dining_room)
	(placeinroom place46_receptacle33_chair room15_dining_room)
	(placeinroom place47_receptacle34_chair room15_dining_room)
	(placeinroom place48_receptacle35_chair room15_dining_room)
	(placeinroom place49_receptacle36_chair room20_living_room)
	(placeinroom place4_door_room2_bathroom room2_bathroom)
	(placeinroom place50_receptacle37_chair room16_dining_room)
	(placeinroom place51_receptacle38_chair room6_childs_room)
	(placeinroom place52_receptacle39_chair room6_childs_room)
	(placeinroom place53_receptacle40_chair room6_childs_room)
	(placeinroom place54_receptacle41_couch room25_television_room)
	(placeinroom place55_receptacle42_couch room25_television_room)
	(placeinroom place56_receptacle43_couch room22_staircase)
	(placeinroom place57_receptacle44_couch room20_living_room)
	(placeinroom place58_receptacle45_couch room16_dining_room)
	(placeinroom place59_receptacle46_couch room7_childs_room)
	(placeinroom place5_door_room19_kitchen room19_kitchen)
	(placeinroom place60_receptacle50_bed room4_bedroom)
	(placeinroom place61_receptacle51_bed room20_living_room)
	(placeinroom place62_receptacle52_bed room15_dining_room)
	(placeinroom place63_receptacle53_bed room6_childs_room)
	(placeinroom place64_receptacle54_bed room6_childs_room)
	(placeinroom place65_receptacle55_bed room7_childs_room)
	(placeinroom place66_receptacle56_bed room5_bedroom)
	(placeinroom place67_receptacle57_bed room5_bedroom)
	(placeinroom place68_receptacle58_dining_table room16_dining_room)
	(placeinroom place69_receptacle59_dining_table room15_dining_room)
	(placeinroom place6_door_room3_bathroom room3_bathroom)
	(placeinroom place70_receptacle60_dining_table room15_dining_room)
	(placeinroom place71_receptacle61_toilet room1_bathroom)
	(placeinroom place72_receptacle62_toilet room2_bathroom)
	(placeinroom place73_receptacle63_toilet room3_bathroom)
	(placeinroom place74_receptacle64_toilet room2_bathroom)
	(placeinroom place75_receptacle71_microwave room19_kitchen)
	(placeinroom place76_receptacle72_oven room19_kitchen)
	(placeinroom place77_receptacle73_sink room1_bathroom)
	(placeinroom place78_receptacle74_sink room19_kitchen)
	(placeinroom place79_receptacle75_sink room2_bathroom)
	(placeinroom place7_door_room25_television_room room25_television_room)
	(placeinroom place80_receptacle76_sink room3_bathroom)
	(placeinroom place81_receptacle77_sink room2_bathroom)
	(placeinroom place82_receptacle78_refrigerator room10_corridor)
	(placeinroom place83_receptacle79_refrigerator room1_bathroom)
	(placeinroom place84_receptacle80_refrigerator room1_bathroom)
	(placeinroom place85_receptacle81_refrigerator room21_lobby)
	(placeinroom place86_receptacle82_refrigerator room19_kitchen)
	(placeinroom place8_door_room6_childs_room room6_childs_room)
	(placeinroom place9_door_room21_lobby room21_lobby)
	(placelocation location_xneg11_ypos2_place25_room4_floora place25_item65_tv)
	(placelocation location_xneg13_ypos29_place85_room21_floorb place85_receptacle81_refrigerator)
	(placelocation location_xneg13_ypos44_place34_room9_floora place34_item83_book)
	(placelocation location_xneg14_ypos54_place59_room7_floorc place59_receptacle46_couch)
	(placelocation location_xneg19_ypos54_place82_room10_floora place82_receptacle78_refrigerator)
	(placelocation location_xneg20_ypos62_place18_room10_floora place18_door_room10_corridor)
	(placelocation location_xneg25_ypos44_place2_room24_floora place2_door_room24_storage)
	(placelocation location_xneg30_ypos52_place31_room24_floora place31_item7_bottle)
	(placelocation location_xneg30_ypos54_place30_room24_floora place30_item6_bottle)
	(placelocation location_xneg31_ypos52_place29_room24_floora place29_item5_bottle)
	(placelocation location_xneg4_ypos44_place9_room21_floorb place9_door_room21_lobby)
	(placelocation location_xneg5_yneg14_place57_room20_floorb place57_receptacle44_couch)
	(placelocation location_xneg6_yneg32_place49_room20_floorb place49_receptacle36_chair)
	(placelocation location_xneg9_yneg11_place67_room5_floorc place67_receptacle57_bed)
	(placelocation location_xpos11_ypos60_place24_room23_floorb place24_door_room23_staircase)
	(placelocation location_xpos12_ypos51_place65_room7_floorc place65_receptacle55_bed)
	(placelocation location_xpos14_ypos31_place77_room1_floora place77_receptacle73_sink)
	(placelocation location_xpos15_ypos9_place60_room4_floora place60_receptacle50_bed)
	(placelocation location_xpos22_ypos34_place17_room1_floora place17_door_room1_bathroom)
	(placelocation location_xpos23_ypos49_place21_room12_floorb place21_door_room12_corridor)
	(placelocation location_xpos26_ypos40_place83_room1_floora place83_receptacle79_refrigerator)
	(placelocation location_xpos27_ypos23_place40_room20_floorb place40_receptacle27_chair)
	(placelocation location_xpos29_yneg24_place32_room8_floorc place32_item70_tv)
	(placelocation location_xpos29_yneg30_place39_room20_floorb place39_receptacle26_chair)
	(placelocation location_xpos29_yneg32_place14_room8_floorc place14_door_room8_closet)
	(placelocation location_xpos29_yneg5_place22_room13_floorc place22_door_room13_corridor)
	(placelocation location_xpos30_ypos29_place71_room1_floora place71_receptacle61_toilet)
	(placelocation location_xpos30_ypos59_place20_room11_floora place20_door_room11_corridor)
	(placelocation location_xpos31_ypos38_place84_room1_floora place84_receptacle80_refrigerator)
	(placelocation location_xpos32_yneg40_place33_room8_floorc place33_item49_potted_plant)
	(placelocation location_xpos35_ypos27_place23_room14_floorc place23_door_room14_corridor)
	(placelocation location_xpos37_ypos37_place27_room25_floora place27_item66_tv)
	(placelocation location_xpos37_ypos38_place28_room25_floora place28_item68_tv)
	(placelocation location_xpos3_ypos37_place13_room7_floorc place13_door_room7_childs_room)
	(placelocation location_xpos41_yneg39_place74_room2_floorc place74_receptacle64_toilet)
	(placelocation location_xpos42_ypos48_place52_room6_floorc place52_receptacle39_chair)
	(placelocation location_xpos43_ypos31_place86_room19_floorb place86_receptacle82_refrigerator)
	(placelocation location_xpos43_ypos48_place63_room6_floorc place63_receptacle53_bed)
	(placelocation location_xpos47_yneg9_place35_room17_floora place35_item84_book)
	(placelocation location_xpos47_yneg9_place36_room17_floora place36_item85_book)
	(placelocation location_xpos48_yneg1_place1_room17_floora place1_door_room17_home_office)
	(placelocation location_xpos48_ypos1_place79_room2_floorc place79_receptacle75_sink)
	(placelocation location_xpos49_ypos62_place58_room16_floorb place58_receptacle45_couch)
	(placelocation location_xpos50_yneg20_place70_room15_floorb place70_receptacle60_dining_table)
	(placelocation location_xpos50_ypos60_place50_room16_floorb place50_receptacle37_chair)
	(placelocation location_xpos50_ypos60_place68_room16_floorb place68_receptacle58_dining_table)
	(placelocation location_xpos51_yneg22_place47_room15_floorb place47_receptacle34_chair)
	(placelocation location_xpos51_ypos48_place55_room25_floora place55_receptacle42_couch)
	(placelocation location_xpos52_ypos46_place7_room25_floora place7_door_room25_television_room)
	(placelocation location_xpos53_yneg15_place3_room15_floorb place3_door_room15_dining_room)
	(placelocation location_xpos53_yneg19_place4_room2_floorc place4_door_room2_bathroom)
	(placelocation location_xpos53_yneg39_place62_room15_floorb place62_receptacle52_bed)
	(placelocation location_xpos53_yneg8_place42_room15_floorb place42_receptacle29_chair)
	(placelocation location_xpos53_ypos2_place41_room15_floorb place41_receptacle28_chair)
	(placelocation location_xpos53_ypos48_place8_room6_floorc place8_door_room6_childs_room)
	(placelocation location_xpos54_yneg12_place69_room15_floorb place69_receptacle59_dining_table)
	(placelocation location_xpos54_yneg27_place48_room15_floorb place48_receptacle35_chair)
	(placelocation location_xpos54_ypos34_place5_room19_floorb place5_door_room19_kitchen)
	(placelocation location_xpos54_ypos62_place11_room16_floorb place11_door_room16_dining_room)
	(placelocation location_xpos55_yneg17_place45_room15_floorb place45_receptacle32_chair)
	(placelocation location_xpos56_ypos17_place0_room18_floora place0_door_room18_kitchen)
	(placelocation location_xpos56_ypos2_place43_room15_floorb place43_receptacle30_chair)
	(placelocation location_xpos56_ypos47_place54_room25_floora place54_receptacle41_couch)
	(placelocation location_xpos57_yneg20_place46_room15_floorb place46_receptacle33_chair)
	(placelocation location_xpos58_ypos7_place80_room3_floorc place80_receptacle76_sink)
	(placelocation location_xpos59_yneg5_place44_room15_floorb place44_receptacle31_chair)
	(placelocation location_xpos59_ypos15_place6_room3_floorc place6_door_room3_bathroom)
	(placelocation location_xpos5_yneg29_place66_room5_floorc place66_receptacle56_bed)
	(placelocation location_xpos60_ypos29_place64_room6_floorc place64_receptacle54_bed)
	(placelocation location_xpos63_ypos0_place37_room17_floora place37_receptacle24_chair)
	(placelocation location_xpos64_yneg19_place81_room2_floorc place81_receptacle77_sink)
	(placelocation location_xpos65_ypos62_place53_room6_floorc place53_receptacle40_chair)
	(placelocation location_xpos67_yneg1_place72_room2_floorc place72_receptacle62_toilet)
	(placelocation location_xpos67_ypos30_place51_room6_floorc place51_receptacle38_chair)
	(placelocation location_xpos67_ypos8_place73_room3_floorc place73_receptacle63_toilet)
	(placelocation location_xpos68_ypos33_place78_room19_floorb place78_receptacle74_sink)
	(placelocation location_xpos68_ypos46_place76_room19_floorb place76_receptacle72_oven)
	(placelocation location_xpos69_ypos46_place75_room19_floorb place75_receptacle71_microwave)
	(placelocation location_xpos6_yneg18_place16_room5_floorc place16_door_room5_bedroom)
	(placelocation location_xpos7_ypos54_place38_room21_floorb place38_receptacle25_chair)
	(placelocation location_xpos7_ypos62_place56_room22_floora place56_receptacle43_couch)
	(placelocation location_xpos8_ypos4_place15_room4_floora place15_door_room4_bedroom)
	(placelocation location_xpos9_yneg14_place61_room20_floorb place61_receptacle51_bed)
	(placelocation location_xpos9_yneg5_place10_room20_floorb place10_door_room20_living_room)
	(placelocation location_xpos9_ypos39_place19_room9_floora place19_door_room9_corridor)
	(placelocation location_xpos9_ypos63_place12_room22_floora place12_door_room22_staircase)
	(receptacleatlocation receptacle24_chair location_xpos63_ypos0_place37_room17_floora)
	(receptacleatlocation receptacle25_chair location_xpos7_ypos54_place38_room21_floorb)
	(receptacleatlocation receptacle26_chair location_xpos29_yneg30_place39_room20_floorb)
	(receptacleatlocation receptacle27_chair location_xpos27_ypos23_place40_room20_floorb)
	(receptacleatlocation receptacle28_chair location_xpos53_ypos2_place41_room15_floorb)
	(receptacleatlocation receptacle29_chair location_xpos53_yneg8_place42_room15_floorb)
	(receptacleatlocation receptacle30_chair location_xpos56_ypos2_place43_room15_floorb)
	(receptacleatlocation receptacle31_chair location_xpos59_yneg5_place44_room15_floorb)
	(receptacleatlocation receptacle32_chair location_xpos55_yneg17_place45_room15_floorb)
	(receptacleatlocation receptacle33_chair location_xpos57_yneg20_place46_room15_floorb)
	(receptacleatlocation receptacle34_chair location_xpos51_yneg22_place47_room15_floorb)
	(receptacleatlocation receptacle35_chair location_xpos54_yneg27_place48_room15_floorb)
	(receptacleatlocation receptacle36_chair location_xneg6_yneg32_place49_room20_floorb)
	(receptacleatlocation receptacle37_chair location_xpos50_ypos60_place50_room16_floorb)
	(receptacleatlocation receptacle38_chair location_xpos67_ypos30_place51_room6_floorc)
	(receptacleatlocation receptacle39_chair location_xpos42_ypos48_place52_room6_floorc)
	(receptacleatlocation receptacle40_chair location_xpos65_ypos62_place53_room6_floorc)
	(receptacleatlocation receptacle41_couch location_xpos56_ypos47_place54_room25_floora)
	(receptacleatlocation receptacle42_couch location_xpos51_ypos48_place55_room25_floora)
	(receptacleatlocation receptacle43_couch location_xpos7_ypos62_place56_room22_floora)
	(receptacleatlocation receptacle44_couch location_xneg5_yneg14_place57_room20_floorb)
	(receptacleatlocation receptacle45_couch location_xpos49_ypos62_place58_room16_floorb)
	(receptacleatlocation receptacle46_couch location_xneg14_ypos54_place59_room7_floorc)
	(receptacleatlocation receptacle50_bed location_xpos15_ypos9_place60_room4_floora)
	(receptacleatlocation receptacle51_bed location_xpos9_yneg14_place61_room20_floorb)
	(receptacleatlocation receptacle52_bed location_xpos53_yneg39_place62_room15_floorb)
	(receptacleatlocation receptacle53_bed location_xpos43_ypos48_place63_room6_floorc)
	(receptacleatlocation receptacle54_bed location_xpos60_ypos29_place64_room6_floorc)
	(receptacleatlocation receptacle55_bed location_xpos12_ypos51_place65_room7_floorc)
	(receptacleatlocation receptacle56_bed location_xpos5_yneg29_place66_room5_floorc)
	(receptacleatlocation receptacle57_bed location_xneg9_yneg11_place67_room5_floorc)
	(receptacleatlocation receptacle58_dining_table location_xpos50_ypos60_place68_room16_floorb)
	(receptacleatlocation receptacle59_dining_table location_xpos54_yneg12_place69_room15_floorb)
	(receptacleatlocation receptacle60_dining_table location_xpos50_yneg20_place70_room15_floorb)
	(receptacleatlocation receptacle61_toilet location_xpos30_ypos29_place71_room1_floora)
	(receptacleatlocation receptacle62_toilet location_xpos67_yneg1_place72_room2_floorc)
	(receptacleatlocation receptacle63_toilet location_xpos67_ypos8_place73_room3_floorc)
	(receptacleatlocation receptacle64_toilet location_xpos41_yneg39_place74_room2_floorc)
	(receptacleatlocation receptacle71_microwave location_xpos69_ypos46_place75_room19_floorb)
	(receptacleatlocation receptacle72_oven location_xpos68_ypos46_place76_room19_floorb)
	(receptacleatlocation receptacle73_sink location_xpos14_ypos31_place77_room1_floora)
	(receptacleatlocation receptacle74_sink location_xpos68_ypos33_place78_room19_floorb)
	(receptacleatlocation receptacle75_sink location_xpos48_ypos1_place79_room2_floorc)
	(receptacleatlocation receptacle76_sink location_xpos58_ypos7_place80_room3_floorc)
	(receptacleatlocation receptacle77_sink location_xpos64_yneg19_place81_room2_floorc)
	(receptacleatlocation receptacle78_refrigerator location_xneg19_ypos54_place82_room10_floora)
	(receptacleatlocation receptacle79_refrigerator location_xpos26_ypos40_place83_room1_floora)
	(receptacleatlocation receptacle80_refrigerator location_xpos31_ypos38_place84_room1_floora)
	(receptacleatlocation receptacle81_refrigerator location_xneg13_ypos29_place85_room21_floorb)
	(receptacleatlocation receptacle82_refrigerator location_xpos43_ypos31_place86_room19_floorb)
	(receptacleclass receptacle24_chair chair)
	(receptacleclass receptacle25_chair chair)
	(receptacleclass receptacle26_chair chair)
	(receptacleclass receptacle27_chair chair)
	(receptacleclass receptacle28_chair chair)
	(receptacleclass receptacle29_chair chair)
	(receptacleclass receptacle30_chair chair)
	(receptacleclass receptacle31_chair chair)
	(receptacleclass receptacle32_chair chair)
	(receptacleclass receptacle33_chair chair)
	(receptacleclass receptacle34_chair chair)
	(receptacleclass receptacle35_chair chair)
	(receptacleclass receptacle36_chair chair)
	(receptacleclass receptacle37_chair chair)
	(receptacleclass receptacle38_chair chair)
	(receptacleclass receptacle39_chair chair)
	(receptacleclass receptacle40_chair chair)
	(receptacleclass receptacle41_couch couch)
	(receptacleclass receptacle42_couch couch)
	(receptacleclass receptacle43_couch couch)
	(receptacleclass receptacle44_couch couch)
	(receptacleclass receptacle45_couch couch)
	(receptacleclass receptacle46_couch couch)
	(receptacleclass receptacle50_bed bed)
	(receptacleclass receptacle51_bed bed)
	(receptacleclass receptacle52_bed bed)
	(receptacleclass receptacle53_bed bed)
	(receptacleclass receptacle54_bed bed)
	(receptacleclass receptacle55_bed bed)
	(receptacleclass receptacle56_bed bed)
	(receptacleclass receptacle57_bed bed)
	(receptacleclass receptacle58_dining_table diningtable)
	(receptacleclass receptacle59_dining_table diningtable)
	(receptacleclass receptacle60_dining_table diningtable)
	(receptacleclass receptacle61_toilet toilet)
	(receptacleclass receptacle62_toilet toilet)
	(receptacleclass receptacle63_toilet toilet)
	(receptacleclass receptacle64_toilet toilet)
	(receptacleclass receptacle71_microwave microwave)
	(receptacleclass receptacle72_oven oven)
	(receptacleclass receptacle73_sink sink)
	(receptacleclass receptacle74_sink sink)
	(receptacleclass receptacle75_sink sink)
	(receptacleclass receptacle76_sink sink)
	(receptacleclass receptacle77_sink sink)
	(receptacleclass receptacle78_refrigerator refrigerator)
	(receptacleclass receptacle79_refrigerator refrigerator)
	(receptacleclass receptacle80_refrigerator refrigerator)
	(receptacleclass receptacle81_refrigerator refrigerator)
	(receptacleclass receptacle82_refrigerator refrigerator)
	(receptacleopeningtype receptacle71_microwave)
	(receptacleopeningtype receptacle72_oven)
	(receptacleopeningtype receptacle78_refrigerator)
	(receptacleopeningtype receptacle79_refrigerator)
	(receptacleopeningtype receptacle80_refrigerator)
	(receptacleopeningtype receptacle81_refrigerator)
	(receptacleopeningtype receptacle82_refrigerator)
	(roomplace place0_door_room18_kitchen room18_kitchen)
	(roomplace place10_door_room20_living_room room20_living_room)
	(roomplace place11_door_room16_dining_room room16_dining_room)
	(roomplace place12_door_room22_staircase room22_staircase)
	(roomplace place13_door_room7_childs_room room7_childs_room)
	(roomplace place14_door_room8_closet room8_closet)
	(roomplace place15_door_room4_bedroom room4_bedroom)
	(roomplace place16_door_room5_bedroom room5_bedroom)
	(roomplace place17_door_room1_bathroom room1_bathroom)
	(roomplace place18_door_room10_corridor room10_corridor)
	(roomplace place19_door_room9_corridor room9_corridor)
	(roomplace place1_door_room17_home_office room17_home_office)
	(roomplace place20_door_room11_corridor room11_corridor)
	(roomplace place21_door_room12_corridor room12_corridor)
	(roomplace place22_door_room13_corridor room13_corridor)
	(roomplace place23_door_room14_corridor room14_corridor)
	(roomplace place24_door_room23_staircase room23_staircase)
	(roomplace place2_door_room24_storage room24_storage)
	(roomplace place3_door_room15_dining_room room15_dining_room)
	(roomplace place4_door_room2_bathroom room2_bathroom)
	(roomplace place5_door_room19_kitchen room19_kitchen)
	(roomplace place6_door_room3_bathroom room3_bathroom)
	(roomplace place7_door_room25_television_room room25_television_room)
	(roomplace place8_door_room6_childs_room room6_childs_room)
	(roomplace place9_door_room21_lobby room21_lobby)
	(roomsconnected room10_corridor room22_staircase)
	(roomsconnected room10_corridor room24_storage)
	(roomsconnected room11_corridor room12_corridor)
	(roomsconnected room11_corridor room22_staircase)
	(roomsconnected room12_corridor room11_corridor)
	(roomsconnected room12_corridor room16_dining_room)
	(roomsconnected room12_corridor room23_staircase)
	(roomsconnected room13_corridor room14_corridor)
	(roomsconnected room13_corridor room5_bedroom)
	(roomsconnected room14_corridor room13_corridor)
	(roomsconnected room14_corridor room3_bathroom)
	(roomsconnected room14_corridor room6_childs_room)
	(roomsconnected room14_corridor room7_childs_room)
	(roomsconnected room15_dining_room room19_kitchen)
	(roomsconnected room15_dining_room room20_living_room)
	(roomsconnected room16_dining_room room12_corridor)
	(roomsconnected room16_dining_room room19_kitchen)
	(roomsconnected room17_home_office room18_kitchen)
	(roomsconnected room18_kitchen room17_home_office)
	(roomsconnected room18_kitchen room25_television_room)
	(roomsconnected room19_kitchen room15_dining_room)
	(roomsconnected room19_kitchen room16_dining_room)
	(roomsconnected room1_bathroom room25_television_room)
	(roomsconnected room1_bathroom room4_bedroom)
	(roomsconnected room1_bathroom room9_corridor)
	(roomsconnected room20_living_room room15_dining_room)
	(roomsconnected room21_lobby room23_staircase)
	(roomsconnected room22_staircase room10_corridor)
	(roomsconnected room22_staircase room11_corridor)
	(roomsconnected room22_staircase room9_corridor)
	(roomsconnected room23_staircase room12_corridor)
	(roomsconnected room23_staircase room21_lobby)
	(roomsconnected room23_staircase room7_childs_room)
	(roomsconnected room24_storage room10_corridor)
	(roomsconnected room25_television_room room18_kitchen)
	(roomsconnected room25_television_room room1_bathroom)
	(roomsconnected room2_bathroom room8_closet)
	(roomsconnected room3_bathroom room14_corridor)
	(roomsconnected room4_bedroom room1_bathroom)
	(roomsconnected room5_bedroom room13_corridor)
	(roomsconnected room5_bedroom room8_closet)
	(roomsconnected room6_childs_room room14_corridor)
	(roomsconnected room7_childs_room room14_corridor)
	(roomsconnected room7_childs_room room23_staircase)
	(roomsconnected room8_closet room2_bathroom)
	(roomsconnected room8_closet room5_bedroom)
	(roomsconnected room9_corridor room1_bathroom)
	(roomsconnected room9_corridor room22_staircase)
	(smallitem item10_bottle_smallitem)
	(smallitem item12_cup_smallitem)
	(smallitem item13_cup_smallitem)
	(smallitem item14_spoon_smallitem)
	(smallitem item15_spoon_smallitem)
	(smallitem item16_bowl_smallitem)
	(smallitem item17_bowl_smallitem)
	(smallitem item18_bowl_smallitem)
	(smallitem item19_bowl_smallitem)
	(smallitem item20_bowl_smallitem)
	(smallitem item21_bowl_smallitem)
	(smallitem item5_bottle_smallitem)
	(smallitem item6_bottle_smallitem)
	(smallitem item7_bottle_smallitem)
	(smallitem item83_book_smallitem)
	(smallitem item84_book_smallitem)
	(smallitem item85_book_smallitem)
	(smallitem item86_book_smallitem)
	(smallitem item87_book_smallitem)
	(smallitem item88_book_smallitem)
	(smallitem item89_book_smallitem)
	(smallitem item8_bottle_smallitem)
	(smallitem item90_book_smallitem)
	(smallitem item9_bottle_smallitem)
  )
  (:goal (and
	(classrelation vase chair)
	(classrelation spoon sink)
	(classrelation cake couch)
	(classrelation cake refrigerator)
	(classrelation tv oven)))
)
