
(define (problem sugarvilletaskographyv5medium5bagslots5problem88) (:domain taskographyv5medium5bagslots5scrub)
  (:objects
        bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	bed - rclass
	bench - rclass
	book - iclass
	bottle - iclass
	cake - iclass
	clock - iclass
	couch - rclass
	cup - iclass
	diningtable - rclass
	item10_suitcase_largeitem - item
	item11_sports_ball_largeitem - item
	item12_bottle_smallitem - item
	item13_bottle_smallitem - item
	item14_bottle_smallitem - item
	item15_cup_smallitem - item
	item16_cup_smallitem - item
	item17_knife_smallitem - item
	item18_cake_mediumitem - item
	item35_potted_plant_largeitem - item
	item36_potted_plant_largeitem - item
	item37_potted_plant_largeitem - item
	item38_potted_plant_largeitem - item
	item39_potted_plant_largeitem - item
	item3_umbrella_largeitem - item
	item40_potted_plant_largeitem - item
	item41_potted_plant_largeitem - item
	item42_potted_plant_largeitem - item
	item43_potted_plant_largeitem - item
	item44_potted_plant_largeitem - item
	item45_potted_plant_largeitem - item
	item46_potted_plant_largeitem - item
	item47_potted_plant_largeitem - item
	item4_umbrella_largeitem - item
	item59_tv_largeitem - item
	item5_umbrella_largeitem - item
	item60_tv_largeitem - item
	item6_umbrella_largeitem - item
	item74_book_smallitem - item
	item75_book_smallitem - item
	item76_book_smallitem - item
	item77_book_smallitem - item
	item78_book_smallitem - item
	item79_book_smallitem - item
	item7_umbrella_largeitem - item
	item80_book_smallitem - item
	item81_clock_mediumitem - item
	item82_clock_mediumitem - item
	item83_clock_mediumitem - item
	item84_vase_mediumitem - item
	item85_vase_mediumitem - item
	item86_vase_mediumitem - item
	item87_vase_mediumitem - item
	knife - iclass
	location_xneg11_ypos11_place11_room5_floora - location
	location_xneg12_ypos53_place15_room14_floora - location
	location_xneg15_yneg15_place53_room6_floorb - location
	location_xneg15_ypos121_place69_room1_floora - location
	location_xneg15_ypos131_place68_room1_floora - location
	location_xneg17_ypos125_place69_room1_floora - location
	location_xneg18_ypos0_place52_room5_floora - location
	location_xneg18_ypos82_place16_room16_floora - location
	location_xneg20_ypos18_place55_room6_floorb - location
	location_xneg23_ypos133_place28_room8_floora - location
	location_xneg24_yneg6_place53_room6_floorb - location
	location_xneg24_ypos17_place55_room6_floorb - location
	location_xneg30_ypos2_place3_room6_floorb - location
	location_xneg31_ypos126_place1_room8_floora - location
	location_xneg33_ypos54_place14_room9_floora - location
	location_xneg35_ypos45_place9_room10_floorb - location
	location_xneg36_ypos22_place30_room10_floorb - location
	location_xneg38_ypos51_place25_room9_floora - location
	location_xneg38_ypos51_place26_room9_floora - location
	location_xneg39_ypos114_place17_room8_floora - location
	location_xneg39_ypos115_place18_room8_floora - location
	location_xneg3_ypos115_place8_room1_floora - location
	location_xneg3_ypos85_place71_room2_floora - location
	location_xneg40_yneg5_place64_room12_floora - location
	location_xneg40_ypos4_place72_room12_floora - location
	location_xneg42_ypos116_place19_room8_floora - location
	location_xneg43_ypos96_place27_room13_floora - location
	location_xneg54_ypos4_place72_room12_floora - location
	location_xneg54_ypos5_place72_room12_floora - location
	location_xneg54_ypos6_place72_room12_floora - location
	location_xneg57_ypos114_place13_room4_floora - location
	location_xneg62_yneg15_place63_room12_floora - location
	location_xneg62_ypos69_place2_room17_floorb - location
	location_xneg64_ypos30_place56_room11_floora - location
	location_xneg66_yneg14_place63_room12_floora - location
	location_xneg66_yneg5_place4_room12_floora - location
	location_xneg67_yneg39_place34_room15_floora - location
	location_xneg67_ypos30_place56_room11_floora - location
	location_xneg68_ypos72_place7_room13_floora - location
	location_xneg68_ypos91_place29_room13_floora - location
	location_xneg68_ypos91_place36_room13_floora - location
	location_xneg69_ypos29_place10_room11_floora - location
	location_xneg69_ypos29_place56_room11_floora - location
	location_xneg69_ypos4_place66_room12_floora - location
	location_xneg69_ypos59_place48_room13_floora - location
	location_xneg69_ypos80_place50_room17_floorb - location
	location_xneg69_ypos95_place50_room17_floorb - location
	location_xneg70_yneg40_place33_room15_floora - location
	location_xneg70_ypos30_place56_room11_floora - location
	location_xneg70_ypos72_place48_room13_floora - location
	location_xneg71_yneg14_place44_room7_floorb - location
	location_xneg71_ypos131_place51_room4_floora - location
	location_xneg72_ypos67_place49_room17_floorb - location
	location_xneg73_ypos30_place56_room11_floora - location
	location_xneg74_yneg39_place33_room15_floora - location
	location_xneg74_ypos3_place12_room7_floorb - location
	location_xneg76_yneg13_place44_room7_floorb - location
	location_xneg76_ypos82_place36_room13_floora - location
	location_xneg77_yneg15_place63_room12_floora - location
	location_xneg77_ypos44_place70_room17_floorb - location
	location_xneg78_ypos23_place73_room3_floorb - location
	location_xneg79_yneg40_place33_room15_floora - location
	location_xneg79_ypos34_place6_room3_floorb - location
	location_xneg80_yneg30_place0_room15_floora - location
	location_xneg80_ypos95_place47_room13_floora - location
	location_xneg81_ypos10_place66_room12_floora - location
	location_xneg82_yneg13_place58_room7_floorb - location
	location_xneg82_ypos79_place36_room13_floora - location
	location_xneg83_ypos60_place48_room13_floora - location
	location_xneg83_ypos67_place49_room17_floorb - location
	location_xneg84_ypos16_place54_room7_floorb - location
	location_xneg84_ypos81_place47_room13_floora - location
	location_xneg85_ypos138_place57_room4_floora - location
	location_xneg85_ypos95_place47_room13_floora - location
	location_xneg86_ypos138_place57_room4_floora - location
	location_xneg87_ypos140_place57_room4_floora - location
	location_xneg88_ypos27_place73_room3_floorb - location
	location_xneg89_ypos142_place57_room4_floora - location
	location_xneg92_ypos102_place20_room4_floora - location
	location_xneg92_ypos99_place21_room4_floora - location
	location_xneg93_ypos94_place47_room13_floora - location
	location_xneg94_ypos96_place31_room13_floora - location
	location_xneg96_ypos104_place24_room4_floora - location
	location_xpos0_ypos86_place71_room2_floora - location
	location_xpos1_ypos77_place5_room2_floora - location
	location_xpos8_ypos115_place67_room1_floora - location
	oven - rclass
	place0_door_room15_lobby - place
	place10_door_room11_dining_room - place
	place11_door_room5_bedroom - place
	place12_door_room7_childs_room - place
	place13_door_room4_bedroom - place
	place14_door_room9_corridor - place
	place15_door_room14_lobby - place
	place16_door_room16_staircase - place
	place17_item3_umbrella - place
	place18_item4_umbrella - place
	place19_item5_umbrella - place
	place1_door_room8_closet - place
	place20_item37_potted_plant - place
	place21_item38_potted_plant - place
	place24_item39_potted_plant - place
	place25_item42_potted_plant - place
	place26_item43_potted_plant - place
	place27_item15_cup - place
	place28_item79_book - place
	place29_item81_clock - place
	place2_door_room17_television_room - place
	place30_item82_clock - place
	place31_item85_vase - place
	place33_receptacle1_bench - place
	place34_receptacle2_bench - place
	place36_receptacle20_chair - place
	place3_door_room6_bedroom - place
	place44_receptacle28_chair - place
	place47_receptacle31_couch - place
	place48_receptacle32_couch - place
	place49_receptacle33_couch - place
	place4_door_room12_kitchen - place
	place50_receptacle34_couch - place
	place51_receptacle48_bed - place
	place52_receptacle49_bed - place
	place53_receptacle50_bed - place
	place54_receptacle51_bed - place
	place55_receptacle52_dining_table - place
	place56_receptacle53_dining_table - place
	place57_receptacle54_dining_table - place
	place58_receptacle55_dining_table - place
	place5_door_room2_bathroom - place
	place63_receptacle63_oven - place
	place64_receptacle64_oven - place
	place66_receptacle66_sink - place
	place67_receptacle67_sink - place
	place68_receptacle68_sink - place
	place69_receptacle69_sink - place
	place6_door_room3_bathroom - place
	place70_receptacle70_sink - place
	place71_receptacle71_sink - place
	place72_receptacle72_refrigerator - place
	place73_receptacle73_refrigerator - place
	place7_door_room13_living_room - place
	place8_door_room1_bathroom - place
	place9_door_room10_corridor - place
	pottedplant - iclass
	receptacle1_bench - receptacle
	receptacle20_chair - receptacle
	receptacle28_chair - receptacle
	receptacle2_bench - receptacle
	receptacle31_couch - receptacle
	receptacle32_couch - receptacle
	receptacle33_couch - receptacle
	receptacle34_couch - receptacle
	receptacle48_bed - receptacle
	receptacle49_bed - receptacle
	receptacle50_bed - receptacle
	receptacle51_bed - receptacle
	receptacle52_dining_table - receptacle
	receptacle53_dining_table - receptacle
	receptacle54_dining_table - receptacle
	receptacle55_dining_table - receptacle
	receptacle63_oven - receptacle
	receptacle64_oven - receptacle
	receptacle66_sink - receptacle
	receptacle67_sink - receptacle
	receptacle68_sink - receptacle
	receptacle69_sink - receptacle
	receptacle70_sink - receptacle
	receptacle71_sink - receptacle
	receptacle72_refrigerator - receptacle
	receptacle73_refrigerator - receptacle
	robot - agent
	room10_corridor - room
	room11_dining_room - room
	room12_kitchen - room
	room13_living_room - room
	room14_lobby - room
	room15_lobby - room
	room16_staircase - room
	room17_television_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_bedroom - room
	room7_childs_room - room
	room8_closet - room
	room9_corridor - room
	sink - rclass
	sportsball - iclass
	suitcase - iclass
	tv - iclass
	umbrella - iclass
	vase - iclass
  )
  (:init 
	(atlocation robot location_xpos1_ypos77_place5_room2_floora)
	(classrelation book couch)
	(classrelation bottle oven)
	(classrelation bottle sink)
	(classrelation cake couch)
	(classrelation clock bed)
	(classrelation cup sink)
	(classrelation knife oven)
	(classrelation pottedplant couch)
	(classrelation pottedplant diningtable)
	(classrelation sportsball diningtable)
	(classrelation suitcase couch)
	(classrelation tv couch)
	(classrelation umbrella bench)
	(classrelation vase diningtable)
	(classrelation vase sink)
	(inanyreceptacle item10_suitcase_largeitem)
	(inanyreceptacle item11_sports_ball_largeitem)
	(inanyreceptacle item12_bottle_smallitem)
	(inanyreceptacle item13_bottle_smallitem)
	(inanyreceptacle item14_bottle_smallitem)
	(inanyreceptacle item16_cup_smallitem)
	(inanyreceptacle item17_knife_smallitem)
	(inanyreceptacle item18_cake_mediumitem)
	(inanyreceptacle item35_potted_plant_largeitem)
	(inanyreceptacle item36_potted_plant_largeitem)
	(inanyreceptacle item40_potted_plant_largeitem)
	(inanyreceptacle item41_potted_plant_largeitem)
	(inanyreceptacle item44_potted_plant_largeitem)
	(inanyreceptacle item45_potted_plant_largeitem)
	(inanyreceptacle item46_potted_plant_largeitem)
	(inanyreceptacle item47_potted_plant_largeitem)
	(inanyreceptacle item59_tv_largeitem)
	(inanyreceptacle item60_tv_largeitem)
	(inanyreceptacle item6_umbrella_largeitem)
	(inanyreceptacle item74_book_smallitem)
	(inanyreceptacle item75_book_smallitem)
	(inanyreceptacle item76_book_smallitem)
	(inanyreceptacle item77_book_smallitem)
	(inanyreceptacle item78_book_smallitem)
	(inanyreceptacle item7_umbrella_largeitem)
	(inanyreceptacle item80_book_smallitem)
	(inanyreceptacle item83_clock_mediumitem)
	(inanyreceptacle item84_vase_mediumitem)
	(inanyreceptacle item86_vase_mediumitem)
	(inanyreceptacle item87_vase_mediumitem)
	(inplace robot place5_door_room2_bathroom)
	(inreceptacle item10_suitcase_largeitem receptacle33_couch)
	(inreceptacle item11_sports_ball_largeitem receptacle52_dining_table)
	(inreceptacle item12_bottle_smallitem receptacle63_oven)
	(inreceptacle item13_bottle_smallitem receptacle71_sink)
	(inreceptacle item14_bottle_smallitem receptacle73_refrigerator)
	(inreceptacle item16_cup_smallitem receptacle69_sink)
	(inreceptacle item17_knife_smallitem receptacle63_oven)
	(inreceptacle item18_cake_mediumitem receptacle31_couch)
	(inreceptacle item35_potted_plant_largeitem receptacle54_dining_table)
	(inreceptacle item36_potted_plant_largeitem receptacle54_dining_table)
	(inreceptacle item40_potted_plant_largeitem receptacle31_couch)
	(inreceptacle item41_potted_plant_largeitem receptacle32_couch)
	(inreceptacle item44_potted_plant_largeitem receptacle53_dining_table)
	(inreceptacle item45_potted_plant_largeitem receptacle53_dining_table)
	(inreceptacle item46_potted_plant_largeitem receptacle53_dining_table)
	(inreceptacle item47_potted_plant_largeitem receptacle53_dining_table)
	(inreceptacle item59_tv_largeitem receptacle20_chair)
	(inreceptacle item60_tv_largeitem receptacle34_couch)
	(inreceptacle item6_umbrella_largeitem receptacle1_bench)
	(inreceptacle item74_book_smallitem receptacle32_couch)
	(inreceptacle item75_book_smallitem receptacle72_refrigerator)
	(inreceptacle item76_book_smallitem receptacle72_refrigerator)
	(inreceptacle item77_book_smallitem receptacle72_refrigerator)
	(inreceptacle item78_book_smallitem receptacle28_chair)
	(inreceptacle item7_umbrella_largeitem receptacle1_bench)
	(inreceptacle item80_book_smallitem receptacle31_couch)
	(inreceptacle item83_clock_mediumitem receptacle50_bed)
	(inreceptacle item84_vase_mediumitem receptacle66_sink)
	(inreceptacle item86_vase_mediumitem receptacle54_dining_table)
	(inreceptacle item87_vase_mediumitem receptacle20_chair)
	(inroom robot room2_bathroom)
	(itematlocation item10_suitcase_largeitem location_xneg83_ypos67_place49_room17_floorb)
	(itematlocation item11_sports_ball_largeitem location_xneg20_ypos18_place55_room6_floorb)
	(itematlocation item12_bottle_smallitem location_xneg77_yneg15_place63_room12_floora)
	(itematlocation item13_bottle_smallitem location_xpos0_ypos86_place71_room2_floora)
	(itematlocation item14_bottle_smallitem location_xneg78_ypos23_place73_room3_floorb)
	(itematlocation item15_cup_smallitem location_xneg43_ypos96_place27_room13_floora)
	(itematlocation item16_cup_smallitem location_xneg17_ypos125_place69_room1_floora)
	(itematlocation item17_knife_smallitem location_xneg62_yneg15_place63_room12_floora)
	(itematlocation item18_cake_mediumitem location_xneg80_ypos95_place47_room13_floora)
	(itematlocation item35_potted_plant_largeitem location_xneg87_ypos140_place57_room4_floora)
	(itematlocation item36_potted_plant_largeitem location_xneg85_ypos138_place57_room4_floora)
	(itematlocation item37_potted_plant_largeitem location_xneg92_ypos102_place20_room4_floora)
	(itematlocation item38_potted_plant_largeitem location_xneg92_ypos99_place21_room4_floora)
	(itematlocation item39_potted_plant_largeitem location_xneg96_ypos104_place24_room4_floora)
	(itematlocation item3_umbrella_largeitem location_xneg39_ypos114_place17_room8_floora)
	(itematlocation item40_potted_plant_largeitem location_xneg85_ypos95_place47_room13_floora)
	(itematlocation item41_potted_plant_largeitem location_xneg70_ypos72_place48_room13_floora)
	(itematlocation item42_potted_plant_largeitem location_xneg38_ypos51_place25_room9_floora)
	(itematlocation item43_potted_plant_largeitem location_xneg38_ypos51_place26_room9_floora)
	(itematlocation item44_potted_plant_largeitem location_xneg70_ypos30_place56_room11_floora)
	(itematlocation item45_potted_plant_largeitem location_xneg64_ypos30_place56_room11_floora)
	(itematlocation item46_potted_plant_largeitem location_xneg67_ypos30_place56_room11_floora)
	(itematlocation item47_potted_plant_largeitem location_xneg73_ypos30_place56_room11_floora)
	(itematlocation item4_umbrella_largeitem location_xneg39_ypos115_place18_room8_floora)
	(itematlocation item59_tv_largeitem location_xneg68_ypos91_place36_room13_floora)
	(itematlocation item5_umbrella_largeitem location_xneg42_ypos116_place19_room8_floora)
	(itematlocation item60_tv_largeitem location_xneg69_ypos95_place50_room17_floorb)
	(itematlocation item6_umbrella_largeitem location_xneg70_yneg40_place33_room15_floora)
	(itematlocation item74_book_smallitem location_xneg83_ypos60_place48_room13_floora)
	(itematlocation item75_book_smallitem location_xneg54_ypos5_place72_room12_floora)
	(itematlocation item76_book_smallitem location_xneg54_ypos4_place72_room12_floora)
	(itematlocation item77_book_smallitem location_xneg54_ypos6_place72_room12_floora)
	(itematlocation item78_book_smallitem location_xneg71_yneg14_place44_room7_floorb)
	(itematlocation item79_book_smallitem location_xneg23_ypos133_place28_room8_floora)
	(itematlocation item7_umbrella_largeitem location_xneg79_yneg40_place33_room15_floora)
	(itematlocation item80_book_smallitem location_xneg93_ypos94_place47_room13_floora)
	(itematlocation item81_clock_mediumitem location_xneg68_ypos91_place29_room13_floora)
	(itematlocation item82_clock_mediumitem location_xneg36_ypos22_place30_room10_floorb)
	(itematlocation item83_clock_mediumitem location_xneg15_yneg15_place53_room6_floorb)
	(itematlocation item84_vase_mediumitem location_xneg81_ypos10_place66_room12_floora)
	(itematlocation item85_vase_mediumitem location_xneg94_ypos96_place31_room13_floora)
	(itematlocation item86_vase_mediumitem location_xneg89_ypos142_place57_room4_floora)
	(itematlocation item87_vase_mediumitem location_xneg76_ypos82_place36_room13_floora)
	(itemclass item10_suitcase_largeitem suitcase)
	(itemclass item11_sports_ball_largeitem sportsball)
	(itemclass item12_bottle_smallitem bottle)
	(itemclass item13_bottle_smallitem bottle)
	(itemclass item14_bottle_smallitem bottle)
	(itemclass item15_cup_smallitem cup)
	(itemclass item16_cup_smallitem cup)
	(itemclass item17_knife_smallitem knife)
	(itemclass item18_cake_mediumitem cake)
	(itemclass item35_potted_plant_largeitem pottedplant)
	(itemclass item36_potted_plant_largeitem pottedplant)
	(itemclass item37_potted_plant_largeitem pottedplant)
	(itemclass item38_potted_plant_largeitem pottedplant)
	(itemclass item39_potted_plant_largeitem pottedplant)
	(itemclass item3_umbrella_largeitem umbrella)
	(itemclass item40_potted_plant_largeitem pottedplant)
	(itemclass item41_potted_plant_largeitem pottedplant)
	(itemclass item42_potted_plant_largeitem pottedplant)
	(itemclass item43_potted_plant_largeitem pottedplant)
	(itemclass item44_potted_plant_largeitem pottedplant)
	(itemclass item45_potted_plant_largeitem pottedplant)
	(itemclass item46_potted_plant_largeitem pottedplant)
	(itemclass item47_potted_plant_largeitem pottedplant)
	(itemclass item4_umbrella_largeitem umbrella)
	(itemclass item59_tv_largeitem tv)
	(itemclass item5_umbrella_largeitem umbrella)
	(itemclass item60_tv_largeitem tv)
	(itemclass item6_umbrella_largeitem umbrella)
	(itemclass item74_book_smallitem book)
	(itemclass item75_book_smallitem book)
	(itemclass item76_book_smallitem book)
	(itemclass item77_book_smallitem book)
	(itemclass item78_book_smallitem book)
	(itemclass item79_book_smallitem book)
	(itemclass item7_umbrella_largeitem umbrella)
	(itemclass item80_book_smallitem book)
	(itemclass item81_clock_mediumitem clock)
	(itemclass item82_clock_mediumitem clock)
	(itemclass item83_clock_mediumitem clock)
	(itemclass item84_vase_mediumitem vase)
	(itemclass item85_vase_mediumitem vase)
	(itemclass item86_vase_mediumitem vase)
	(itemclass item87_vase_mediumitem vase)
	(largeitem item10_suitcase_largeitem)
	(largeitem item11_sports_ball_largeitem)
	(largeitem item35_potted_plant_largeitem)
	(largeitem item36_potted_plant_largeitem)
	(largeitem item37_potted_plant_largeitem)
	(largeitem item38_potted_plant_largeitem)
	(largeitem item39_potted_plant_largeitem)
	(largeitem item3_umbrella_largeitem)
	(largeitem item40_potted_plant_largeitem)
	(largeitem item41_potted_plant_largeitem)
	(largeitem item42_potted_plant_largeitem)
	(largeitem item43_potted_plant_largeitem)
	(largeitem item44_potted_plant_largeitem)
	(largeitem item45_potted_plant_largeitem)
	(largeitem item46_potted_plant_largeitem)
	(largeitem item47_potted_plant_largeitem)
	(largeitem item4_umbrella_largeitem)
	(largeitem item59_tv_largeitem)
	(largeitem item5_umbrella_largeitem)
	(largeitem item60_tv_largeitem)
	(largeitem item6_umbrella_largeitem)
	(largeitem item7_umbrella_largeitem)
	(locationinplace location_xneg11_ypos11_place11_room5_floora place11_door_room5_bedroom)
	(locationinplace location_xneg12_ypos53_place15_room14_floora place15_door_room14_lobby)
	(locationinplace location_xneg15_yneg15_place53_room6_floorb place53_receptacle50_bed)
	(locationinplace location_xneg15_ypos121_place69_room1_floora place69_receptacle69_sink)
	(locationinplace location_xneg15_ypos131_place68_room1_floora place68_receptacle68_sink)
	(locationinplace location_xneg17_ypos125_place69_room1_floora place69_receptacle69_sink)
	(locationinplace location_xneg18_ypos0_place52_room5_floora place52_receptacle49_bed)
	(locationinplace location_xneg18_ypos82_place16_room16_floora place16_door_room16_staircase)
	(locationinplace location_xneg20_ypos18_place55_room6_floorb place55_receptacle52_dining_table)
	(locationinplace location_xneg23_ypos133_place28_room8_floora place28_item79_book)
	(locationinplace location_xneg24_yneg6_place53_room6_floorb place53_receptacle50_bed)
	(locationinplace location_xneg24_ypos17_place55_room6_floorb place55_receptacle52_dining_table)
	(locationinplace location_xneg30_ypos2_place3_room6_floorb place3_door_room6_bedroom)
	(locationinplace location_xneg31_ypos126_place1_room8_floora place1_door_room8_closet)
	(locationinplace location_xneg33_ypos54_place14_room9_floora place14_door_room9_corridor)
	(locationinplace location_xneg35_ypos45_place9_room10_floorb place9_door_room10_corridor)
	(locationinplace location_xneg36_ypos22_place30_room10_floorb place30_item82_clock)
	(locationinplace location_xneg38_ypos51_place25_room9_floora place25_item42_potted_plant)
	(locationinplace location_xneg38_ypos51_place26_room9_floora place26_item43_potted_plant)
	(locationinplace location_xneg39_ypos114_place17_room8_floora place17_item3_umbrella)
	(locationinplace location_xneg39_ypos115_place18_room8_floora place18_item4_umbrella)
	(locationinplace location_xneg3_ypos115_place8_room1_floora place8_door_room1_bathroom)
	(locationinplace location_xneg3_ypos85_place71_room2_floora place71_receptacle71_sink)
	(locationinplace location_xneg40_yneg5_place64_room12_floora place64_receptacle64_oven)
	(locationinplace location_xneg40_ypos4_place72_room12_floora place72_receptacle72_refrigerator)
	(locationinplace location_xneg42_ypos116_place19_room8_floora place19_item5_umbrella)
	(locationinplace location_xneg43_ypos96_place27_room13_floora place27_item15_cup)
	(locationinplace location_xneg54_ypos4_place72_room12_floora place72_receptacle72_refrigerator)
	(locationinplace location_xneg54_ypos5_place72_room12_floora place72_receptacle72_refrigerator)
	(locationinplace location_xneg54_ypos6_place72_room12_floora place72_receptacle72_refrigerator)
	(locationinplace location_xneg57_ypos114_place13_room4_floora place13_door_room4_bedroom)
	(locationinplace location_xneg62_yneg15_place63_room12_floora place63_receptacle63_oven)
	(locationinplace location_xneg62_ypos69_place2_room17_floorb place2_door_room17_television_room)
	(locationinplace location_xneg64_ypos30_place56_room11_floora place56_receptacle53_dining_table)
	(locationinplace location_xneg66_yneg14_place63_room12_floora place63_receptacle63_oven)
	(locationinplace location_xneg66_yneg5_place4_room12_floora place4_door_room12_kitchen)
	(locationinplace location_xneg67_yneg39_place34_room15_floora place34_receptacle2_bench)
	(locationinplace location_xneg67_ypos30_place56_room11_floora place56_receptacle53_dining_table)
	(locationinplace location_xneg68_ypos72_place7_room13_floora place7_door_room13_living_room)
	(locationinplace location_xneg68_ypos91_place29_room13_floora place29_item81_clock)
	(locationinplace location_xneg68_ypos91_place36_room13_floora place36_receptacle20_chair)
	(locationinplace location_xneg69_ypos29_place10_room11_floora place10_door_room11_dining_room)
	(locationinplace location_xneg69_ypos29_place56_room11_floora place56_receptacle53_dining_table)
	(locationinplace location_xneg69_ypos4_place66_room12_floora place66_receptacle66_sink)
	(locationinplace location_xneg69_ypos59_place48_room13_floora place48_receptacle32_couch)
	(locationinplace location_xneg69_ypos80_place50_room17_floorb place50_receptacle34_couch)
	(locationinplace location_xneg69_ypos95_place50_room17_floorb place50_receptacle34_couch)
	(locationinplace location_xneg70_yneg40_place33_room15_floora place33_receptacle1_bench)
	(locationinplace location_xneg70_ypos30_place56_room11_floora place56_receptacle53_dining_table)
	(locationinplace location_xneg70_ypos72_place48_room13_floora place48_receptacle32_couch)
	(locationinplace location_xneg71_yneg14_place44_room7_floorb place44_receptacle28_chair)
	(locationinplace location_xneg71_ypos131_place51_room4_floora place51_receptacle48_bed)
	(locationinplace location_xneg72_ypos67_place49_room17_floorb place49_receptacle33_couch)
	(locationinplace location_xneg73_ypos30_place56_room11_floora place56_receptacle53_dining_table)
	(locationinplace location_xneg74_yneg39_place33_room15_floora place33_receptacle1_bench)
	(locationinplace location_xneg74_ypos3_place12_room7_floorb place12_door_room7_childs_room)
	(locationinplace location_xneg76_yneg13_place44_room7_floorb place44_receptacle28_chair)
	(locationinplace location_xneg76_ypos82_place36_room13_floora place36_receptacle20_chair)
	(locationinplace location_xneg77_yneg15_place63_room12_floora place63_receptacle63_oven)
	(locationinplace location_xneg77_ypos44_place70_room17_floorb place70_receptacle70_sink)
	(locationinplace location_xneg78_ypos23_place73_room3_floorb place73_receptacle73_refrigerator)
	(locationinplace location_xneg79_yneg40_place33_room15_floora place33_receptacle1_bench)
	(locationinplace location_xneg79_ypos34_place6_room3_floorb place6_door_room3_bathroom)
	(locationinplace location_xneg80_yneg30_place0_room15_floora place0_door_room15_lobby)
	(locationinplace location_xneg80_ypos95_place47_room13_floora place47_receptacle31_couch)
	(locationinplace location_xneg81_ypos10_place66_room12_floora place66_receptacle66_sink)
	(locationinplace location_xneg82_yneg13_place58_room7_floorb place58_receptacle55_dining_table)
	(locationinplace location_xneg82_ypos79_place36_room13_floora place36_receptacle20_chair)
	(locationinplace location_xneg83_ypos60_place48_room13_floora place48_receptacle32_couch)
	(locationinplace location_xneg83_ypos67_place49_room17_floorb place49_receptacle33_couch)
	(locationinplace location_xneg84_ypos16_place54_room7_floorb place54_receptacle51_bed)
	(locationinplace location_xneg84_ypos81_place47_room13_floora place47_receptacle31_couch)
	(locationinplace location_xneg85_ypos138_place57_room4_floora place57_receptacle54_dining_table)
	(locationinplace location_xneg85_ypos95_place47_room13_floora place47_receptacle31_couch)
	(locationinplace location_xneg86_ypos138_place57_room4_floora place57_receptacle54_dining_table)
	(locationinplace location_xneg87_ypos140_place57_room4_floora place57_receptacle54_dining_table)
	(locationinplace location_xneg88_ypos27_place73_room3_floorb place73_receptacle73_refrigerator)
	(locationinplace location_xneg89_ypos142_place57_room4_floora place57_receptacle54_dining_table)
	(locationinplace location_xneg92_ypos102_place20_room4_floora place20_item37_potted_plant)
	(locationinplace location_xneg92_ypos99_place21_room4_floora place21_item38_potted_plant)
	(locationinplace location_xneg93_ypos94_place47_room13_floora place47_receptacle31_couch)
	(locationinplace location_xneg94_ypos96_place31_room13_floora place31_item85_vase)
	(locationinplace location_xneg96_ypos104_place24_room4_floora place24_item39_potted_plant)
	(locationinplace location_xpos0_ypos86_place71_room2_floora place71_receptacle71_sink)
	(locationinplace location_xpos1_ypos77_place5_room2_floora place5_door_room2_bathroom)
	(locationinplace location_xpos8_ypos115_place67_room1_floora place67_receptacle67_sink)
	(mediumitem item18_cake_mediumitem)
	(mediumitem item81_clock_mediumitem)
	(mediumitem item82_clock_mediumitem)
	(mediumitem item83_clock_mediumitem)
	(mediumitem item84_vase_mediumitem)
	(mediumitem item85_vase_mediumitem)
	(mediumitem item86_vase_mediumitem)
	(mediumitem item87_vase_mediumitem)
	(placeinroom place0_door_room15_lobby room15_lobby)
	(placeinroom place10_door_room11_dining_room room11_dining_room)
	(placeinroom place11_door_room5_bedroom room5_bedroom)
	(placeinroom place12_door_room7_childs_room room7_childs_room)
	(placeinroom place13_door_room4_bedroom room4_bedroom)
	(placeinroom place14_door_room9_corridor room9_corridor)
	(placeinroom place15_door_room14_lobby room14_lobby)
	(placeinroom place16_door_room16_staircase room16_staircase)
	(placeinroom place17_item3_umbrella room8_closet)
	(placeinroom place18_item4_umbrella room8_closet)
	(placeinroom place19_item5_umbrella room8_closet)
	(placeinroom place1_door_room8_closet room8_closet)
	(placeinroom place20_item37_potted_plant room4_bedroom)
	(placeinroom place21_item38_potted_plant room4_bedroom)
	(placeinroom place24_item39_potted_plant room4_bedroom)
	(placeinroom place25_item42_potted_plant room9_corridor)
	(placeinroom place26_item43_potted_plant room9_corridor)
	(placeinroom place27_item15_cup room13_living_room)
	(placeinroom place28_item79_book room8_closet)
	(placeinroom place29_item81_clock room13_living_room)
	(placeinroom place2_door_room17_television_room room17_television_room)
	(placeinroom place30_item82_clock room10_corridor)
	(placeinroom place31_item85_vase room13_living_room)
	(placeinroom place33_receptacle1_bench room15_lobby)
	(placeinroom place34_receptacle2_bench room15_lobby)
	(placeinroom place36_receptacle20_chair room13_living_room)
	(placeinroom place3_door_room6_bedroom room6_bedroom)
	(placeinroom place44_receptacle28_chair room7_childs_room)
	(placeinroom place47_receptacle31_couch room13_living_room)
	(placeinroom place48_receptacle32_couch room13_living_room)
	(placeinroom place49_receptacle33_couch room17_television_room)
	(placeinroom place4_door_room12_kitchen room12_kitchen)
	(placeinroom place50_receptacle34_couch room17_television_room)
	(placeinroom place51_receptacle48_bed room4_bedroom)
	(placeinroom place52_receptacle49_bed room5_bedroom)
	(placeinroom place53_receptacle50_bed room6_bedroom)
	(placeinroom place54_receptacle51_bed room7_childs_room)
	(placeinroom place55_receptacle52_dining_table room6_bedroom)
	(placeinroom place56_receptacle53_dining_table room11_dining_room)
	(placeinroom place57_receptacle54_dining_table room4_bedroom)
	(placeinroom place58_receptacle55_dining_table room7_childs_room)
	(placeinroom place5_door_room2_bathroom room2_bathroom)
	(placeinroom place63_receptacle63_oven room12_kitchen)
	(placeinroom place64_receptacle64_oven room12_kitchen)
	(placeinroom place66_receptacle66_sink room12_kitchen)
	(placeinroom place67_receptacle67_sink room1_bathroom)
	(placeinroom place68_receptacle68_sink room1_bathroom)
	(placeinroom place69_receptacle69_sink room1_bathroom)
	(placeinroom place6_door_room3_bathroom room3_bathroom)
	(placeinroom place70_receptacle70_sink room17_television_room)
	(placeinroom place71_receptacle71_sink room2_bathroom)
	(placeinroom place72_receptacle72_refrigerator room12_kitchen)
	(placeinroom place73_receptacle73_refrigerator room3_bathroom)
	(placeinroom place7_door_room13_living_room room13_living_room)
	(placeinroom place8_door_room1_bathroom room1_bathroom)
	(placeinroom place9_door_room10_corridor room10_corridor)
	(placelocation location_xneg11_ypos11_place11_room5_floora place11_door_room5_bedroom)
	(placelocation location_xneg12_ypos53_place15_room14_floora place15_door_room14_lobby)
	(placelocation location_xneg15_ypos121_place69_room1_floora place69_receptacle69_sink)
	(placelocation location_xneg15_ypos131_place68_room1_floora place68_receptacle68_sink)
	(placelocation location_xneg18_ypos0_place52_room5_floora place52_receptacle49_bed)
	(placelocation location_xneg18_ypos82_place16_room16_floora place16_door_room16_staircase)
	(placelocation location_xneg23_ypos133_place28_room8_floora place28_item79_book)
	(placelocation location_xneg24_yneg6_place53_room6_floorb place53_receptacle50_bed)
	(placelocation location_xneg24_ypos17_place55_room6_floorb place55_receptacle52_dining_table)
	(placelocation location_xneg30_ypos2_place3_room6_floorb place3_door_room6_bedroom)
	(placelocation location_xneg31_ypos126_place1_room8_floora place1_door_room8_closet)
	(placelocation location_xneg33_ypos54_place14_room9_floora place14_door_room9_corridor)
	(placelocation location_xneg35_ypos45_place9_room10_floorb place9_door_room10_corridor)
	(placelocation location_xneg36_ypos22_place30_room10_floorb place30_item82_clock)
	(placelocation location_xneg38_ypos51_place25_room9_floora place25_item42_potted_plant)
	(placelocation location_xneg38_ypos51_place26_room9_floora place26_item43_potted_plant)
	(placelocation location_xneg39_ypos114_place17_room8_floora place17_item3_umbrella)
	(placelocation location_xneg39_ypos115_place18_room8_floora place18_item4_umbrella)
	(placelocation location_xneg3_ypos115_place8_room1_floora place8_door_room1_bathroom)
	(placelocation location_xneg3_ypos85_place71_room2_floora place71_receptacle71_sink)
	(placelocation location_xneg40_yneg5_place64_room12_floora place64_receptacle64_oven)
	(placelocation location_xneg40_ypos4_place72_room12_floora place72_receptacle72_refrigerator)
	(placelocation location_xneg42_ypos116_place19_room8_floora place19_item5_umbrella)
	(placelocation location_xneg43_ypos96_place27_room13_floora place27_item15_cup)
	(placelocation location_xneg57_ypos114_place13_room4_floora place13_door_room4_bedroom)
	(placelocation location_xneg62_ypos69_place2_room17_floorb place2_door_room17_television_room)
	(placelocation location_xneg66_yneg14_place63_room12_floora place63_receptacle63_oven)
	(placelocation location_xneg66_yneg5_place4_room12_floora place4_door_room12_kitchen)
	(placelocation location_xneg67_yneg39_place34_room15_floora place34_receptacle2_bench)
	(placelocation location_xneg68_ypos72_place7_room13_floora place7_door_room13_living_room)
	(placelocation location_xneg68_ypos91_place29_room13_floora place29_item81_clock)
	(placelocation location_xneg69_ypos29_place10_room11_floora place10_door_room11_dining_room)
	(placelocation location_xneg69_ypos29_place56_room11_floora place56_receptacle53_dining_table)
	(placelocation location_xneg69_ypos4_place66_room12_floora place66_receptacle66_sink)
	(placelocation location_xneg69_ypos59_place48_room13_floora place48_receptacle32_couch)
	(placelocation location_xneg69_ypos80_place50_room17_floorb place50_receptacle34_couch)
	(placelocation location_xneg71_ypos131_place51_room4_floora place51_receptacle48_bed)
	(placelocation location_xneg72_ypos67_place49_room17_floorb place49_receptacle33_couch)
	(placelocation location_xneg74_yneg39_place33_room15_floora place33_receptacle1_bench)
	(placelocation location_xneg74_ypos3_place12_room7_floorb place12_door_room7_childs_room)
	(placelocation location_xneg76_yneg13_place44_room7_floorb place44_receptacle28_chair)
	(placelocation location_xneg77_ypos44_place70_room17_floorb place70_receptacle70_sink)
	(placelocation location_xneg79_ypos34_place6_room3_floorb place6_door_room3_bathroom)
	(placelocation location_xneg80_yneg30_place0_room15_floora place0_door_room15_lobby)
	(placelocation location_xneg82_yneg13_place58_room7_floorb place58_receptacle55_dining_table)
	(placelocation location_xneg82_ypos79_place36_room13_floora place36_receptacle20_chair)
	(placelocation location_xneg84_ypos16_place54_room7_floorb place54_receptacle51_bed)
	(placelocation location_xneg84_ypos81_place47_room13_floora place47_receptacle31_couch)
	(placelocation location_xneg86_ypos138_place57_room4_floora place57_receptacle54_dining_table)
	(placelocation location_xneg88_ypos27_place73_room3_floorb place73_receptacle73_refrigerator)
	(placelocation location_xneg92_ypos102_place20_room4_floora place20_item37_potted_plant)
	(placelocation location_xneg92_ypos99_place21_room4_floora place21_item38_potted_plant)
	(placelocation location_xneg94_ypos96_place31_room13_floora place31_item85_vase)
	(placelocation location_xneg96_ypos104_place24_room4_floora place24_item39_potted_plant)
	(placelocation location_xpos1_ypos77_place5_room2_floora place5_door_room2_bathroom)
	(placelocation location_xpos8_ypos115_place67_room1_floora place67_receptacle67_sink)
	(receptacleatlocation receptacle1_bench location_xneg74_yneg39_place33_room15_floora)
	(receptacleatlocation receptacle20_chair location_xneg82_ypos79_place36_room13_floora)
	(receptacleatlocation receptacle28_chair location_xneg76_yneg13_place44_room7_floorb)
	(receptacleatlocation receptacle2_bench location_xneg67_yneg39_place34_room15_floora)
	(receptacleatlocation receptacle31_couch location_xneg84_ypos81_place47_room13_floora)
	(receptacleatlocation receptacle32_couch location_xneg69_ypos59_place48_room13_floora)
	(receptacleatlocation receptacle33_couch location_xneg72_ypos67_place49_room17_floorb)
	(receptacleatlocation receptacle34_couch location_xneg69_ypos80_place50_room17_floorb)
	(receptacleatlocation receptacle48_bed location_xneg71_ypos131_place51_room4_floora)
	(receptacleatlocation receptacle49_bed location_xneg18_ypos0_place52_room5_floora)
	(receptacleatlocation receptacle50_bed location_xneg24_yneg6_place53_room6_floorb)
	(receptacleatlocation receptacle51_bed location_xneg84_ypos16_place54_room7_floorb)
	(receptacleatlocation receptacle52_dining_table location_xneg24_ypos17_place55_room6_floorb)
	(receptacleatlocation receptacle53_dining_table location_xneg69_ypos29_place56_room11_floora)
	(receptacleatlocation receptacle54_dining_table location_xneg86_ypos138_place57_room4_floora)
	(receptacleatlocation receptacle55_dining_table location_xneg82_yneg13_place58_room7_floorb)
	(receptacleatlocation receptacle63_oven location_xneg66_yneg14_place63_room12_floora)
	(receptacleatlocation receptacle64_oven location_xneg40_yneg5_place64_room12_floora)
	(receptacleatlocation receptacle66_sink location_xneg69_ypos4_place66_room12_floora)
	(receptacleatlocation receptacle67_sink location_xpos8_ypos115_place67_room1_floora)
	(receptacleatlocation receptacle68_sink location_xneg15_ypos131_place68_room1_floora)
	(receptacleatlocation receptacle69_sink location_xneg15_ypos121_place69_room1_floora)
	(receptacleatlocation receptacle70_sink location_xneg77_ypos44_place70_room17_floorb)
	(receptacleatlocation receptacle71_sink location_xneg3_ypos85_place71_room2_floora)
	(receptacleatlocation receptacle72_refrigerator location_xneg40_ypos4_place72_room12_floora)
	(receptacleatlocation receptacle73_refrigerator location_xneg88_ypos27_place73_room3_floorb)
	(receptacleclass receptacle1_bench bench)
	(receptacleclass receptacle2_bench bench)
	(receptacleclass receptacle31_couch couch)
	(receptacleclass receptacle32_couch couch)
	(receptacleclass receptacle33_couch couch)
	(receptacleclass receptacle34_couch couch)
	(receptacleclass receptacle48_bed bed)
	(receptacleclass receptacle49_bed bed)
	(receptacleclass receptacle50_bed bed)
	(receptacleclass receptacle51_bed bed)
	(receptacleclass receptacle52_dining_table diningtable)
	(receptacleclass receptacle53_dining_table diningtable)
	(receptacleclass receptacle54_dining_table diningtable)
	(receptacleclass receptacle55_dining_table diningtable)
	(receptacleclass receptacle63_oven oven)
	(receptacleclass receptacle64_oven oven)
	(receptacleclass receptacle66_sink sink)
	(receptacleclass receptacle67_sink sink)
	(receptacleclass receptacle68_sink sink)
	(receptacleclass receptacle69_sink sink)
	(receptacleclass receptacle70_sink sink)
	(receptacleclass receptacle71_sink sink)
	(receptacleopeningtype receptacle63_oven)
	(receptacleopeningtype receptacle64_oven)
	(receptacleopeningtype receptacle72_refrigerator)
	(receptacleopeningtype receptacle73_refrigerator)
	(roomplace place0_door_room15_lobby room15_lobby)
	(roomplace place10_door_room11_dining_room room11_dining_room)
	(roomplace place11_door_room5_bedroom room5_bedroom)
	(roomplace place12_door_room7_childs_room room7_childs_room)
	(roomplace place13_door_room4_bedroom room4_bedroom)
	(roomplace place14_door_room9_corridor room9_corridor)
	(roomplace place15_door_room14_lobby room14_lobby)
	(roomplace place16_door_room16_staircase room16_staircase)
	(roomplace place1_door_room8_closet room8_closet)
	(roomplace place2_door_room17_television_room room17_television_room)
	(roomplace place3_door_room6_bedroom room6_bedroom)
	(roomplace place4_door_room12_kitchen room12_kitchen)
	(roomplace place5_door_room2_bathroom room2_bathroom)
	(roomplace place6_door_room3_bathroom room3_bathroom)
	(roomplace place7_door_room13_living_room room13_living_room)
	(roomplace place8_door_room1_bathroom room1_bathroom)
	(roomplace place9_door_room10_corridor room10_corridor)
	(roomsconnected room10_corridor room17_television_room)
	(roomsconnected room10_corridor room6_bedroom)
	(roomsconnected room11_dining_room room12_kitchen)
	(roomsconnected room11_dining_room room13_living_room)
	(roomsconnected room12_kitchen room11_dining_room)
	(roomsconnected room12_kitchen room15_lobby)
	(roomsconnected room13_living_room room11_dining_room)
	(roomsconnected room13_living_room room17_television_room)
	(roomsconnected room13_living_room room9_corridor)
	(roomsconnected room14_lobby room2_bathroom)
	(roomsconnected room14_lobby room5_bedroom)
	(roomsconnected room14_lobby room9_corridor)
	(roomsconnected room15_lobby room12_kitchen)
	(roomsconnected room16_staircase room2_bathroom)
	(roomsconnected room17_television_room room10_corridor)
	(roomsconnected room17_television_room room13_living_room)
	(roomsconnected room17_television_room room3_bathroom)
	(roomsconnected room1_bathroom room2_bathroom)
	(roomsconnected room1_bathroom room8_closet)
	(roomsconnected room2_bathroom room14_lobby)
	(roomsconnected room2_bathroom room16_staircase)
	(roomsconnected room2_bathroom room1_bathroom)
	(roomsconnected room3_bathroom room17_television_room)
	(roomsconnected room3_bathroom room7_childs_room)
	(roomsconnected room4_bedroom room8_closet)
	(roomsconnected room5_bedroom room14_lobby)
	(roomsconnected room6_bedroom room10_corridor)
	(roomsconnected room7_childs_room room3_bathroom)
	(roomsconnected room8_closet room1_bathroom)
	(roomsconnected room8_closet room4_bedroom)
	(roomsconnected room9_corridor room13_living_room)
	(roomsconnected room9_corridor room14_lobby)
	(smallitem item12_bottle_smallitem)
	(smallitem item13_bottle_smallitem)
	(smallitem item14_bottle_smallitem)
	(smallitem item15_cup_smallitem)
	(smallitem item16_cup_smallitem)
	(smallitem item17_knife_smallitem)
	(smallitem item74_book_smallitem)
	(smallitem item75_book_smallitem)
	(smallitem item76_book_smallitem)
	(smallitem item77_book_smallitem)
	(smallitem item78_book_smallitem)
	(smallitem item79_book_smallitem)
	(smallitem item80_book_smallitem)
  )
  (:goal (and
	(classrelation cake diningtable)
	(classrelation clock diningtable)
	(classrelation pottedplant sink)
	(classrelation umbrella couch)
	(classrelation pottedplant oven)))
)
