
(define (problem heltontaskographyv5medium5bagslots5problem169) (:domain taskographyv5medium5bagslots5scrub)
  (:objects
        bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	book - iclass
	bottle - iclass
	bowl - iclass
	chair - rclass
	clock - iclass
	couch - rclass
	cup - iclass
	diningtable - rclass
	item10_knife_smallitem - item
	item11_knife_smallitem - item
	item12_bowl_smallitem - item
	item13_bowl_smallitem - item
	item28_potted_plant_largeitem - item
	item29_potted_plant_largeitem - item
	item2_bottle_smallitem - item
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item33_potted_plant_largeitem - item
	item34_potted_plant_largeitem - item
	item35_potted_plant_largeitem - item
	item36_potted_plant_largeitem - item
	item37_potted_plant_largeitem - item
	item38_potted_plant_largeitem - item
	item39_potted_plant_largeitem - item
	item3_bottle_smallitem - item
	item40_potted_plant_largeitem - item
	item48_tv_largeitem - item
	item49_tv_largeitem - item
	item4_bottle_smallitem - item
	item50_tv_largeitem - item
	item51_remote_smallitem - item
	item52_remote_smallitem - item
	item5_bottle_smallitem - item
	item67_book_smallitem - item
	item68_clock_mediumitem - item
	item69_clock_mediumitem - item
	item6_wine_glass_smallitem - item
	item70_clock_mediumitem - item
	item71_vase_mediumitem - item
	item72_vase_mediumitem - item
	item7_cup_smallitem - item
	item8_cup_smallitem - item
	item9_cup_smallitem - item
	knife - iclass
	location_xneg10_yneg21_place36_room10_floora - location
	location_xneg10_yneg22_place41_room2_floorb - location
	location_xneg10_yneg24_place36_room10_floora - location
	location_xneg10_ypos67_place30_room7_floora - location
	location_xneg10_ypos69_place29_room7_floora - location
	location_xneg12_ypos63_place27_room7_floora - location
	location_xneg13_ypos61_place28_room7_floora - location
	location_xneg13_ypos64_place4_room7_floora - location
	location_xneg14_ypos44_place54_room8_floora - location
	location_xneg14_ypos48_place54_room8_floora - location
	location_xneg15_yneg28_place36_room10_floora - location
	location_xneg15_ypos33_place45_room8_floora - location
	location_xneg16_ypos33_place44_room8_floora - location
	location_xneg17_ypos37_place44_room8_floora - location
	location_xneg17_ypos39_place54_room8_floora - location
	location_xneg18_ypos30_place37_room4_floorb - location
	location_xneg18_ypos33_place16_room12_floora - location
	location_xneg18_ypos39_place14_room12_floora - location
	location_xneg18_ypos45_place20_room12_floora - location
	location_xneg24_ypos52_place56_room7_floora - location
	location_xneg26_ypos52_place56_room7_floora - location
	location_xneg27_yneg17_place51_room3_floorb - location
	location_xneg28_yneg22_place51_room3_floorb - location
	location_xneg28_yneg24_place51_room3_floorb - location
	location_xneg28_yneg28_place42_room3_floorb - location
	location_xneg29_ypos37_place0_room12_floora - location
	location_xneg29_ypos54_place56_room7_floora - location
	location_xneg2_ypos70_place26_room7_floora - location
	location_xneg30_yneg20_place51_room3_floorb - location
	location_xneg31_yneg28_place42_room3_floorb - location
	location_xneg31_ypos53_place56_room7_floora - location
	location_xneg33_yneg27_place2_room3_floorb - location
	location_xneg34_ypos52_place55_room7_floora - location
	location_xneg37_ypos5_place12_room6_floorb - location
	location_xneg38_yneg13_place10_room1_floora - location
	location_xneg38_yneg30_place11_room14_floora - location
	location_xneg38_yneg35_place57_room14_floora - location
	location_xneg39_ypos18_place13_room11_floora - location
	location_xneg3_ypos32_place3_room8_floora - location
	location_xneg41_yneg35_place47_room14_floora - location
	location_xneg42_yneg16_place43_room1_floora - location
	location_xneg43_yneg8_place53_room1_floora - location
	location_xneg4_ypos19_place37_room4_floorb - location
	location_xneg50_yneg38_place34_room13_floorb - location
	location_xneg56_ypos76_place22_room9_floora - location
	location_xneg61_yneg9_place19_room13_floorb - location
	location_xneg62_ypos54_place6_room9_floora - location
	location_xneg63_yneg34_place34_room13_floorb - location
	location_xneg63_ypos15_place5_room5_floorb - location
	location_xneg63_ypos76_place23_room9_floora - location
	location_xneg65_yneg20_place7_room13_floorb - location
	location_xneg67_ypos76_place21_room9_floora - location
	location_xneg6_ypos65_place40_room7_floora - location
	location_xneg6_ypos66_place40_room7_floora - location
	location_xneg73_ypos26_place24_room5_floorb - location
	location_xneg79_yneg38_place35_room13_floorb - location
	location_xneg80_ypos55_place31_room9_floora - location
	location_xneg81_ypos69_place32_room9_floora - location
	location_xneg84_ypos66_place33_room9_floora - location
	location_xneg85_ypos67_place33_room9_floora - location
	location_xneg87_ypos69_place33_room9_floora - location
	location_xneg8_yneg10_place18_room4_floorb - location
	location_xneg8_yneg7_place8_room10_floora - location
	location_xneg8_ypos11_place9_room4_floorb - location
	location_xneg9_yneg25_place36_room10_floora - location
	location_xneg9_yneg35_place41_room2_floorb - location
	location_xpos0_yneg25_place1_room2_floorb - location
	location_xpos0_ypos64_place25_room7_floora - location
	location_xpos10_ypos30_place52_room8_floora - location
	location_xpos11_yneg17_place49_room2_floorb - location
	location_xpos11_yneg21_place46_room10_floora - location
	location_xpos11_ypos27_place52_room8_floora - location
	location_xpos11_ypos48_place52_room8_floora - location
	location_xpos12_ypos32_place52_room8_floora - location
	location_xpos5_yneg32_place50_room2_floorb - location
	location_xpos5_yneg33_place46_room10_floora - location
	location_xpos6_yneg33_place46_room10_floora - location
	location_xpos9_yneg14_place49_room2_floorb - location
	location_xpos9_yneg22_place48_room2_floorb - location
	location_xpos9_ypos29_place52_room8_floora - location
	oven - rclass
	place0_door_room12_staircase - place
	place10_door_room1_bathroom - place
	place11_door_room14_utility_room - place
	place12_door_room6_corridor - place
	place13_door_room11_lobby - place
	place14_item32_potted_plant - place
	place16_item33_potted_plant - place
	place18_item48_tv - place
	place19_item49_tv - place
	place1_door_room2_bathroom - place
	place20_item28_potted_plant - place
	place21_item29_potted_plant - place
	place22_item30_potted_plant - place
	place23_item31_potted_plant - place
	place24_receptacle15_chair - place
	place25_receptacle16_chair - place
	place26_receptacle17_chair - place
	place27_receptacle18_chair - place
	place28_receptacle19_chair - place
	place29_receptacle20_chair - place
	place2_door_room3_bathroom - place
	place30_receptacle21_chair - place
	place31_receptacle22_chair - place
	place32_receptacle23_chair - place
	place33_receptacle24_chair - place
	place34_receptacle25_couch - place
	place35_receptacle26_couch - place
	place36_receptacle27_couch - place
	place37_receptacle41_bed - place
	place3_door_room8_kitchen - place
	place40_receptacle44_dining_table - place
	place41_receptacle45_toilet - place
	place42_receptacle46_toilet - place
	place43_receptacle47_toilet - place
	place44_receptacle53_microwave - place
	place45_receptacle54_oven - place
	place46_receptacle55_oven - place
	place47_receptacle56_oven - place
	place48_receptacle57_sink - place
	place49_receptacle58_sink - place
	place4_door_room7_dining_room - place
	place50_receptacle59_sink - place
	place51_receptacle60_sink - place
	place52_receptacle61_sink - place
	place53_receptacle62_sink - place
	place54_receptacle63_refrigerator - place
	place55_receptacle64_refrigerator - place
	place56_receptacle65_refrigerator - place
	place57_receptacle66_refrigerator - place
	place5_door_room5_bedroom - place
	place6_door_room9_living_room - place
	place7_door_room13_television_room - place
	place8_door_room10_living_room - place
	place9_door_room4_bedroom - place
	pottedplant - iclass
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_couch - receptacle
	receptacle26_couch - receptacle
	receptacle27_couch - receptacle
	receptacle41_bed - receptacle
	receptacle44_dining_table - receptacle
	receptacle45_toilet - receptacle
	receptacle46_toilet - receptacle
	receptacle47_toilet - receptacle
	receptacle53_microwave - receptacle
	receptacle54_oven - receptacle
	receptacle55_oven - receptacle
	receptacle56_oven - receptacle
	receptacle57_sink - receptacle
	receptacle58_sink - receptacle
	receptacle59_sink - receptacle
	receptacle60_sink - receptacle
	receptacle61_sink - receptacle
	receptacle62_sink - receptacle
	receptacle63_refrigerator - receptacle
	receptacle64_refrigerator - receptacle
	receptacle65_refrigerator - receptacle
	receptacle66_refrigerator - receptacle
	refrigerator - rclass
	remote - iclass
	robot - agent
	room10_living_room - room
	room11_lobby - room
	room12_staircase - room
	room13_television_room - room
	room14_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_corridor - room
	room7_dining_room - room
	room8_kitchen - room
	room9_living_room - room
	sink - rclass
	toilet - rclass
	tv - iclass
	vase - iclass
	wineglass - iclass
  )
  (:init 
	(atlocation robot location_xneg62_ypos54_place6_room9_floora)
	(classrelation book couch)
	(classrelation bottle refrigerator)
	(classrelation bottle sink)
	(classrelation bottle toilet)
	(classrelation bowl sink)
	(classrelation bowl toilet)
	(classrelation clock couch)
	(classrelation clock oven)
	(classrelation cup refrigerator)
	(classrelation cup sink)
	(classrelation knife sink)
	(classrelation pottedplant chair)
	(classrelation pottedplant diningtable)
	(classrelation pottedplant refrigerator)
	(classrelation pottedplant sink)
	(classrelation remote couch)
	(classrelation tv oven)
	(classrelation vase sink)
	(classrelation wineglass refrigerator)
	(inanyreceptacle item10_knife_smallitem)
	(inanyreceptacle item11_knife_smallitem)
	(inanyreceptacle item12_bowl_smallitem)
	(inanyreceptacle item13_bowl_smallitem)
	(inanyreceptacle item2_bottle_smallitem)
	(inanyreceptacle item34_potted_plant_largeitem)
	(inanyreceptacle item35_potted_plant_largeitem)
	(inanyreceptacle item36_potted_plant_largeitem)
	(inanyreceptacle item37_potted_plant_largeitem)
	(inanyreceptacle item38_potted_plant_largeitem)
	(inanyreceptacle item39_potted_plant_largeitem)
	(inanyreceptacle item3_bottle_smallitem)
	(inanyreceptacle item40_potted_plant_largeitem)
	(inanyreceptacle item4_bottle_smallitem)
	(inanyreceptacle item50_tv_largeitem)
	(inanyreceptacle item51_remote_smallitem)
	(inanyreceptacle item52_remote_smallitem)
	(inanyreceptacle item5_bottle_smallitem)
	(inanyreceptacle item67_book_smallitem)
	(inanyreceptacle item68_clock_mediumitem)
	(inanyreceptacle item69_clock_mediumitem)
	(inanyreceptacle item6_wine_glass_smallitem)
	(inanyreceptacle item70_clock_mediumitem)
	(inanyreceptacle item71_vase_mediumitem)
	(inanyreceptacle item72_vase_mediumitem)
	(inanyreceptacle item7_cup_smallitem)
	(inanyreceptacle item8_cup_smallitem)
	(inanyreceptacle item9_cup_smallitem)
	(inplace robot place6_door_room9_living_room)
	(inreceptacle item10_knife_smallitem receptacle61_sink)
	(inreceptacle item11_knife_smallitem receptacle53_microwave)
	(inreceptacle item12_bowl_smallitem receptacle58_sink)
	(inreceptacle item13_bowl_smallitem receptacle46_toilet)
	(inreceptacle item2_bottle_smallitem receptacle45_toilet)
	(inreceptacle item34_potted_plant_largeitem receptacle61_sink)
	(inreceptacle item35_potted_plant_largeitem receptacle61_sink)
	(inreceptacle item36_potted_plant_largeitem receptacle61_sink)
	(inreceptacle item37_potted_plant_largeitem receptacle44_dining_table)
	(inreceptacle item38_potted_plant_largeitem receptacle24_chair)
	(inreceptacle item39_potted_plant_largeitem receptacle24_chair)
	(inreceptacle item3_bottle_smallitem receptacle60_sink)
	(inreceptacle item40_potted_plant_largeitem receptacle63_refrigerator)
	(inreceptacle item4_bottle_smallitem receptacle63_refrigerator)
	(inreceptacle item50_tv_largeitem receptacle55_oven)
	(inreceptacle item51_remote_smallitem receptacle27_couch)
	(inreceptacle item52_remote_smallitem receptacle27_couch)
	(inreceptacle item5_bottle_smallitem receptacle53_microwave)
	(inreceptacle item67_book_smallitem receptacle27_couch)
	(inreceptacle item68_clock_mediumitem receptacle41_bed)
	(inreceptacle item69_clock_mediumitem receptacle25_couch)
	(inreceptacle item6_wine_glass_smallitem receptacle65_refrigerator)
	(inreceptacle item70_clock_mediumitem receptacle55_oven)
	(inreceptacle item71_vase_mediumitem receptacle60_sink)
	(inreceptacle item72_vase_mediumitem receptacle61_sink)
	(inreceptacle item7_cup_smallitem receptacle60_sink)
	(inreceptacle item8_cup_smallitem receptacle65_refrigerator)
	(inreceptacle item9_cup_smallitem receptacle65_refrigerator)
	(inroom robot room9_living_room)
	(itematlocation item10_knife_smallitem location_xpos11_ypos48_place52_room8_floora)
	(itematlocation item11_knife_smallitem location_xneg17_ypos37_place44_room8_floora)
	(itematlocation item12_bowl_smallitem location_xpos11_yneg17_place49_room2_floorb)
	(itematlocation item13_bowl_smallitem location_xneg28_yneg28_place42_room3_floorb)
	(itematlocation item28_potted_plant_largeitem location_xneg18_ypos45_place20_room12_floora)
	(itematlocation item29_potted_plant_largeitem location_xneg67_ypos76_place21_room9_floora)
	(itematlocation item2_bottle_smallitem location_xneg10_yneg22_place41_room2_floorb)
	(itematlocation item30_potted_plant_largeitem location_xneg56_ypos76_place22_room9_floora)
	(itematlocation item31_potted_plant_largeitem location_xneg63_ypos76_place23_room9_floora)
	(itematlocation item32_potted_plant_largeitem location_xneg18_ypos39_place14_room12_floora)
	(itematlocation item33_potted_plant_largeitem location_xneg18_ypos33_place16_room12_floora)
	(itematlocation item34_potted_plant_largeitem location_xpos10_ypos30_place52_room8_floora)
	(itematlocation item35_potted_plant_largeitem location_xpos12_ypos32_place52_room8_floora)
	(itematlocation item36_potted_plant_largeitem location_xpos11_ypos27_place52_room8_floora)
	(itematlocation item37_potted_plant_largeitem location_xneg6_ypos65_place40_room7_floora)
	(itematlocation item38_potted_plant_largeitem location_xneg87_ypos69_place33_room9_floora)
	(itematlocation item39_potted_plant_largeitem location_xneg84_ypos66_place33_room9_floora)
	(itematlocation item3_bottle_smallitem location_xneg27_yneg17_place51_room3_floorb)
	(itematlocation item40_potted_plant_largeitem location_xneg14_ypos48_place54_room8_floora)
	(itematlocation item48_tv_largeitem location_xneg8_yneg10_place18_room4_floorb)
	(itematlocation item49_tv_largeitem location_xneg61_yneg9_place19_room13_floorb)
	(itematlocation item4_bottle_smallitem location_xneg17_ypos39_place54_room8_floora)
	(itematlocation item50_tv_largeitem location_xpos6_yneg33_place46_room10_floora)
	(itematlocation item51_remote_smallitem location_xneg10_yneg24_place36_room10_floora)
	(itematlocation item52_remote_smallitem location_xneg9_yneg25_place36_room10_floora)
	(itematlocation item5_bottle_smallitem location_xneg17_ypos37_place44_room8_floora)
	(itematlocation item67_book_smallitem location_xneg10_yneg21_place36_room10_floora)
	(itematlocation item68_clock_mediumitem location_xneg18_ypos30_place37_room4_floorb)
	(itematlocation item69_clock_mediumitem location_xneg50_yneg38_place34_room13_floorb)
	(itematlocation item6_wine_glass_smallitem location_xneg24_ypos52_place56_room7_floora)
	(itematlocation item70_clock_mediumitem location_xpos11_yneg21_place46_room10_floora)
	(itematlocation item71_vase_mediumitem location_xneg28_yneg24_place51_room3_floorb)
	(itematlocation item72_vase_mediumitem location_xpos12_ypos32_place52_room8_floora)
	(itematlocation item7_cup_smallitem location_xneg28_yneg22_place51_room3_floorb)
	(itematlocation item8_cup_smallitem location_xneg26_ypos52_place56_room7_floora)
	(itematlocation item9_cup_smallitem location_xneg31_ypos53_place56_room7_floora)
	(itemclass item10_knife_smallitem knife)
	(itemclass item11_knife_smallitem knife)
	(itemclass item12_bowl_smallitem bowl)
	(itemclass item13_bowl_smallitem bowl)
	(itemclass item28_potted_plant_largeitem pottedplant)
	(itemclass item29_potted_plant_largeitem pottedplant)
	(itemclass item2_bottle_smallitem bottle)
	(itemclass item30_potted_plant_largeitem pottedplant)
	(itemclass item31_potted_plant_largeitem pottedplant)
	(itemclass item32_potted_plant_largeitem pottedplant)
	(itemclass item33_potted_plant_largeitem pottedplant)
	(itemclass item34_potted_plant_largeitem pottedplant)
	(itemclass item35_potted_plant_largeitem pottedplant)
	(itemclass item36_potted_plant_largeitem pottedplant)
	(itemclass item37_potted_plant_largeitem pottedplant)
	(itemclass item38_potted_plant_largeitem pottedplant)
	(itemclass item39_potted_plant_largeitem pottedplant)
	(itemclass item3_bottle_smallitem bottle)
	(itemclass item40_potted_plant_largeitem pottedplant)
	(itemclass item48_tv_largeitem tv)
	(itemclass item49_tv_largeitem tv)
	(itemclass item4_bottle_smallitem bottle)
	(itemclass item50_tv_largeitem tv)
	(itemclass item51_remote_smallitem remote)
	(itemclass item52_remote_smallitem remote)
	(itemclass item5_bottle_smallitem bottle)
	(itemclass item67_book_smallitem book)
	(itemclass item68_clock_mediumitem clock)
	(itemclass item69_clock_mediumitem clock)
	(itemclass item6_wine_glass_smallitem wineglass)
	(itemclass item70_clock_mediumitem clock)
	(itemclass item71_vase_mediumitem vase)
	(itemclass item72_vase_mediumitem vase)
	(itemclass item7_cup_smallitem cup)
	(itemclass item8_cup_smallitem cup)
	(itemclass item9_cup_smallitem cup)
	(largeitem item28_potted_plant_largeitem)
	(largeitem item29_potted_plant_largeitem)
	(largeitem item30_potted_plant_largeitem)
	(largeitem item31_potted_plant_largeitem)
	(largeitem item32_potted_plant_largeitem)
	(largeitem item33_potted_plant_largeitem)
	(largeitem item34_potted_plant_largeitem)
	(largeitem item35_potted_plant_largeitem)
	(largeitem item36_potted_plant_largeitem)
	(largeitem item37_potted_plant_largeitem)
	(largeitem item38_potted_plant_largeitem)
	(largeitem item39_potted_plant_largeitem)
	(largeitem item40_potted_plant_largeitem)
	(largeitem item48_tv_largeitem)
	(largeitem item49_tv_largeitem)
	(largeitem item50_tv_largeitem)
	(locationinplace location_xneg10_yneg21_place36_room10_floora place36_receptacle27_couch)
	(locationinplace location_xneg10_yneg22_place41_room2_floorb place41_receptacle45_toilet)
	(locationinplace location_xneg10_yneg24_place36_room10_floora place36_receptacle27_couch)
	(locationinplace location_xneg10_ypos67_place30_room7_floora place30_receptacle21_chair)
	(locationinplace location_xneg10_ypos69_place29_room7_floora place29_receptacle20_chair)
	(locationinplace location_xneg12_ypos63_place27_room7_floora place27_receptacle18_chair)
	(locationinplace location_xneg13_ypos61_place28_room7_floora place28_receptacle19_chair)
	(locationinplace location_xneg13_ypos64_place4_room7_floora place4_door_room7_dining_room)
	(locationinplace location_xneg14_ypos44_place54_room8_floora place54_receptacle63_refrigerator)
	(locationinplace location_xneg14_ypos48_place54_room8_floora place54_receptacle63_refrigerator)
	(locationinplace location_xneg15_yneg28_place36_room10_floora place36_receptacle27_couch)
	(locationinplace location_xneg15_ypos33_place45_room8_floora place45_receptacle54_oven)
	(locationinplace location_xneg16_ypos33_place44_room8_floora place44_receptacle53_microwave)
	(locationinplace location_xneg17_ypos37_place44_room8_floora place44_receptacle53_microwave)
	(locationinplace location_xneg17_ypos39_place54_room8_floora place54_receptacle63_refrigerator)
	(locationinplace location_xneg18_ypos30_place37_room4_floorb place37_receptacle41_bed)
	(locationinplace location_xneg18_ypos33_place16_room12_floora place16_item33_potted_plant)
	(locationinplace location_xneg18_ypos39_place14_room12_floora place14_item32_potted_plant)
	(locationinplace location_xneg18_ypos45_place20_room12_floora place20_item28_potted_plant)
	(locationinplace location_xneg24_ypos52_place56_room7_floora place56_receptacle65_refrigerator)
	(locationinplace location_xneg26_ypos52_place56_room7_floora place56_receptacle65_refrigerator)
	(locationinplace location_xneg27_yneg17_place51_room3_floorb place51_receptacle60_sink)
	(locationinplace location_xneg28_yneg22_place51_room3_floorb place51_receptacle60_sink)
	(locationinplace location_xneg28_yneg24_place51_room3_floorb place51_receptacle60_sink)
	(locationinplace location_xneg28_yneg28_place42_room3_floorb place42_receptacle46_toilet)
	(locationinplace location_xneg29_ypos37_place0_room12_floora place0_door_room12_staircase)
	(locationinplace location_xneg29_ypos54_place56_room7_floora place56_receptacle65_refrigerator)
	(locationinplace location_xneg2_ypos70_place26_room7_floora place26_receptacle17_chair)
	(locationinplace location_xneg30_yneg20_place51_room3_floorb place51_receptacle60_sink)
	(locationinplace location_xneg31_yneg28_place42_room3_floorb place42_receptacle46_toilet)
	(locationinplace location_xneg31_ypos53_place56_room7_floora place56_receptacle65_refrigerator)
	(locationinplace location_xneg33_yneg27_place2_room3_floorb place2_door_room3_bathroom)
	(locationinplace location_xneg34_ypos52_place55_room7_floora place55_receptacle64_refrigerator)
	(locationinplace location_xneg37_ypos5_place12_room6_floorb place12_door_room6_corridor)
	(locationinplace location_xneg38_yneg13_place10_room1_floora place10_door_room1_bathroom)
	(locationinplace location_xneg38_yneg30_place11_room14_floora place11_door_room14_utility_room)
	(locationinplace location_xneg38_yneg35_place57_room14_floora place57_receptacle66_refrigerator)
	(locationinplace location_xneg39_ypos18_place13_room11_floora place13_door_room11_lobby)
	(locationinplace location_xneg3_ypos32_place3_room8_floora place3_door_room8_kitchen)
	(locationinplace location_xneg41_yneg35_place47_room14_floora place47_receptacle56_oven)
	(locationinplace location_xneg42_yneg16_place43_room1_floora place43_receptacle47_toilet)
	(locationinplace location_xneg43_yneg8_place53_room1_floora place53_receptacle62_sink)
	(locationinplace location_xneg4_ypos19_place37_room4_floorb place37_receptacle41_bed)
	(locationinplace location_xneg50_yneg38_place34_room13_floorb place34_receptacle25_couch)
	(locationinplace location_xneg56_ypos76_place22_room9_floora place22_item30_potted_plant)
	(locationinplace location_xneg61_yneg9_place19_room13_floorb place19_item49_tv)
	(locationinplace location_xneg62_ypos54_place6_room9_floora place6_door_room9_living_room)
	(locationinplace location_xneg63_yneg34_place34_room13_floorb place34_receptacle25_couch)
	(locationinplace location_xneg63_ypos15_place5_room5_floorb place5_door_room5_bedroom)
	(locationinplace location_xneg63_ypos76_place23_room9_floora place23_item31_potted_plant)
	(locationinplace location_xneg65_yneg20_place7_room13_floorb place7_door_room13_television_room)
	(locationinplace location_xneg67_ypos76_place21_room9_floora place21_item29_potted_plant)
	(locationinplace location_xneg6_ypos65_place40_room7_floora place40_receptacle44_dining_table)
	(locationinplace location_xneg6_ypos66_place40_room7_floora place40_receptacle44_dining_table)
	(locationinplace location_xneg73_ypos26_place24_room5_floorb place24_receptacle15_chair)
	(locationinplace location_xneg79_yneg38_place35_room13_floorb place35_receptacle26_couch)
	(locationinplace location_xneg80_ypos55_place31_room9_floora place31_receptacle22_chair)
	(locationinplace location_xneg81_ypos69_place32_room9_floora place32_receptacle23_chair)
	(locationinplace location_xneg84_ypos66_place33_room9_floora place33_receptacle24_chair)
	(locationinplace location_xneg85_ypos67_place33_room9_floora place33_receptacle24_chair)
	(locationinplace location_xneg87_ypos69_place33_room9_floora place33_receptacle24_chair)
	(locationinplace location_xneg8_yneg10_place18_room4_floorb place18_item48_tv)
	(locationinplace location_xneg8_yneg7_place8_room10_floora place8_door_room10_living_room)
	(locationinplace location_xneg8_ypos11_place9_room4_floorb place9_door_room4_bedroom)
	(locationinplace location_xneg9_yneg25_place36_room10_floora place36_receptacle27_couch)
	(locationinplace location_xneg9_yneg35_place41_room2_floorb place41_receptacle45_toilet)
	(locationinplace location_xpos0_yneg25_place1_room2_floorb place1_door_room2_bathroom)
	(locationinplace location_xpos0_ypos64_place25_room7_floora place25_receptacle16_chair)
	(locationinplace location_xpos10_ypos30_place52_room8_floora place52_receptacle61_sink)
	(locationinplace location_xpos11_yneg17_place49_room2_floorb place49_receptacle58_sink)
	(locationinplace location_xpos11_yneg21_place46_room10_floora place46_receptacle55_oven)
	(locationinplace location_xpos11_ypos27_place52_room8_floora place52_receptacle61_sink)
	(locationinplace location_xpos11_ypos48_place52_room8_floora place52_receptacle61_sink)
	(locationinplace location_xpos12_ypos32_place52_room8_floora place52_receptacle61_sink)
	(locationinplace location_xpos5_yneg32_place50_room2_floorb place50_receptacle59_sink)
	(locationinplace location_xpos5_yneg33_place46_room10_floora place46_receptacle55_oven)
	(locationinplace location_xpos6_yneg33_place46_room10_floora place46_receptacle55_oven)
	(locationinplace location_xpos9_yneg14_place49_room2_floorb place49_receptacle58_sink)
	(locationinplace location_xpos9_yneg22_place48_room2_floorb place48_receptacle57_sink)
	(locationinplace location_xpos9_ypos29_place52_room8_floora place52_receptacle61_sink)
	(mediumitem item68_clock_mediumitem)
	(mediumitem item69_clock_mediumitem)
	(mediumitem item70_clock_mediumitem)
	(mediumitem item71_vase_mediumitem)
	(mediumitem item72_vase_mediumitem)
	(placeinroom place0_door_room12_staircase room12_staircase)
	(placeinroom place10_door_room1_bathroom room1_bathroom)
	(placeinroom place11_door_room14_utility_room room14_utility_room)
	(placeinroom place12_door_room6_corridor room6_corridor)
	(placeinroom place13_door_room11_lobby room11_lobby)
	(placeinroom place14_item32_potted_plant room12_staircase)
	(placeinroom place16_item33_potted_plant room12_staircase)
	(placeinroom place18_item48_tv room4_bedroom)
	(placeinroom place19_item49_tv room13_television_room)
	(placeinroom place1_door_room2_bathroom room2_bathroom)
	(placeinroom place20_item28_potted_plant room12_staircase)
	(placeinroom place21_item29_potted_plant room9_living_room)
	(placeinroom place22_item30_potted_plant room9_living_room)
	(placeinroom place23_item31_potted_plant room9_living_room)
	(placeinroom place24_receptacle15_chair room5_bedroom)
	(placeinroom place25_receptacle16_chair room7_dining_room)
	(placeinroom place26_receptacle17_chair room7_dining_room)
	(placeinroom place27_receptacle18_chair room7_dining_room)
	(placeinroom place28_receptacle19_chair room7_dining_room)
	(placeinroom place29_receptacle20_chair room7_dining_room)
	(placeinroom place2_door_room3_bathroom room3_bathroom)
	(placeinroom place30_receptacle21_chair room7_dining_room)
	(placeinroom place31_receptacle22_chair room9_living_room)
	(placeinroom place32_receptacle23_chair room9_living_room)
	(placeinroom place33_receptacle24_chair room9_living_room)
	(placeinroom place34_receptacle25_couch room13_television_room)
	(placeinroom place35_receptacle26_couch room13_television_room)
	(placeinroom place36_receptacle27_couch room10_living_room)
	(placeinroom place37_receptacle41_bed room4_bedroom)
	(placeinroom place3_door_room8_kitchen room8_kitchen)
	(placeinroom place40_receptacle44_dining_table room7_dining_room)
	(placeinroom place41_receptacle45_toilet room2_bathroom)
	(placeinroom place42_receptacle46_toilet room3_bathroom)
	(placeinroom place43_receptacle47_toilet room1_bathroom)
	(placeinroom place44_receptacle53_microwave room8_kitchen)
	(placeinroom place45_receptacle54_oven room8_kitchen)
	(placeinroom place46_receptacle55_oven room10_living_room)
	(placeinroom place47_receptacle56_oven room14_utility_room)
	(placeinroom place48_receptacle57_sink room2_bathroom)
	(placeinroom place49_receptacle58_sink room2_bathroom)
	(placeinroom place4_door_room7_dining_room room7_dining_room)
	(placeinroom place50_receptacle59_sink room2_bathroom)
	(placeinroom place51_receptacle60_sink room3_bathroom)
	(placeinroom place52_receptacle61_sink room8_kitchen)
	(placeinroom place53_receptacle62_sink room1_bathroom)
	(placeinroom place54_receptacle63_refrigerator room8_kitchen)
	(placeinroom place55_receptacle64_refrigerator room7_dining_room)
	(placeinroom place56_receptacle65_refrigerator room7_dining_room)
	(placeinroom place57_receptacle66_refrigerator room14_utility_room)
	(placeinroom place5_door_room5_bedroom room5_bedroom)
	(placeinroom place6_door_room9_living_room room9_living_room)
	(placeinroom place7_door_room13_television_room room13_television_room)
	(placeinroom place8_door_room10_living_room room10_living_room)
	(placeinroom place9_door_room4_bedroom room4_bedroom)
	(placelocation location_xneg10_ypos67_place30_room7_floora place30_receptacle21_chair)
	(placelocation location_xneg10_ypos69_place29_room7_floora place29_receptacle20_chair)
	(placelocation location_xneg12_ypos63_place27_room7_floora place27_receptacle18_chair)
	(placelocation location_xneg13_ypos61_place28_room7_floora place28_receptacle19_chair)
	(placelocation location_xneg13_ypos64_place4_room7_floora place4_door_room7_dining_room)
	(placelocation location_xneg14_ypos44_place54_room8_floora place54_receptacle63_refrigerator)
	(placelocation location_xneg15_yneg28_place36_room10_floora place36_receptacle27_couch)
	(placelocation location_xneg15_ypos33_place45_room8_floora place45_receptacle54_oven)
	(placelocation location_xneg16_ypos33_place44_room8_floora place44_receptacle53_microwave)
	(placelocation location_xneg18_ypos33_place16_room12_floora place16_item33_potted_plant)
	(placelocation location_xneg18_ypos39_place14_room12_floora place14_item32_potted_plant)
	(placelocation location_xneg18_ypos45_place20_room12_floora place20_item28_potted_plant)
	(placelocation location_xneg29_ypos37_place0_room12_floora place0_door_room12_staircase)
	(placelocation location_xneg29_ypos54_place56_room7_floora place56_receptacle65_refrigerator)
	(placelocation location_xneg2_ypos70_place26_room7_floora place26_receptacle17_chair)
	(placelocation location_xneg30_yneg20_place51_room3_floorb place51_receptacle60_sink)
	(placelocation location_xneg31_yneg28_place42_room3_floorb place42_receptacle46_toilet)
	(placelocation location_xneg33_yneg27_place2_room3_floorb place2_door_room3_bathroom)
	(placelocation location_xneg34_ypos52_place55_room7_floora place55_receptacle64_refrigerator)
	(placelocation location_xneg37_ypos5_place12_room6_floorb place12_door_room6_corridor)
	(placelocation location_xneg38_yneg13_place10_room1_floora place10_door_room1_bathroom)
	(placelocation location_xneg38_yneg30_place11_room14_floora place11_door_room14_utility_room)
	(placelocation location_xneg38_yneg35_place57_room14_floora place57_receptacle66_refrigerator)
	(placelocation location_xneg39_ypos18_place13_room11_floora place13_door_room11_lobby)
	(placelocation location_xneg3_ypos32_place3_room8_floora place3_door_room8_kitchen)
	(placelocation location_xneg41_yneg35_place47_room14_floora place47_receptacle56_oven)
	(placelocation location_xneg42_yneg16_place43_room1_floora place43_receptacle47_toilet)
	(placelocation location_xneg43_yneg8_place53_room1_floora place53_receptacle62_sink)
	(placelocation location_xneg4_ypos19_place37_room4_floorb place37_receptacle41_bed)
	(placelocation location_xneg56_ypos76_place22_room9_floora place22_item30_potted_plant)
	(placelocation location_xneg61_yneg9_place19_room13_floorb place19_item49_tv)
	(placelocation location_xneg62_ypos54_place6_room9_floora place6_door_room9_living_room)
	(placelocation location_xneg63_yneg34_place34_room13_floorb place34_receptacle25_couch)
	(placelocation location_xneg63_ypos15_place5_room5_floorb place5_door_room5_bedroom)
	(placelocation location_xneg63_ypos76_place23_room9_floora place23_item31_potted_plant)
	(placelocation location_xneg65_yneg20_place7_room13_floorb place7_door_room13_television_room)
	(placelocation location_xneg67_ypos76_place21_room9_floora place21_item29_potted_plant)
	(placelocation location_xneg6_ypos66_place40_room7_floora place40_receptacle44_dining_table)
	(placelocation location_xneg73_ypos26_place24_room5_floorb place24_receptacle15_chair)
	(placelocation location_xneg79_yneg38_place35_room13_floorb place35_receptacle26_couch)
	(placelocation location_xneg80_ypos55_place31_room9_floora place31_receptacle22_chair)
	(placelocation location_xneg81_ypos69_place32_room9_floora place32_receptacle23_chair)
	(placelocation location_xneg85_ypos67_place33_room9_floora place33_receptacle24_chair)
	(placelocation location_xneg8_yneg10_place18_room4_floorb place18_item48_tv)
	(placelocation location_xneg8_yneg7_place8_room10_floora place8_door_room10_living_room)
	(placelocation location_xneg8_ypos11_place9_room4_floorb place9_door_room4_bedroom)
	(placelocation location_xneg9_yneg35_place41_room2_floorb place41_receptacle45_toilet)
	(placelocation location_xpos0_yneg25_place1_room2_floorb place1_door_room2_bathroom)
	(placelocation location_xpos0_ypos64_place25_room7_floora place25_receptacle16_chair)
	(placelocation location_xpos5_yneg32_place50_room2_floorb place50_receptacle59_sink)
	(placelocation location_xpos5_yneg33_place46_room10_floora place46_receptacle55_oven)
	(placelocation location_xpos9_yneg14_place49_room2_floorb place49_receptacle58_sink)
	(placelocation location_xpos9_yneg22_place48_room2_floorb place48_receptacle57_sink)
	(placelocation location_xpos9_ypos29_place52_room8_floora place52_receptacle61_sink)
	(receptacleatlocation receptacle15_chair location_xneg73_ypos26_place24_room5_floorb)
	(receptacleatlocation receptacle16_chair location_xpos0_ypos64_place25_room7_floora)
	(receptacleatlocation receptacle17_chair location_xneg2_ypos70_place26_room7_floora)
	(receptacleatlocation receptacle18_chair location_xneg12_ypos63_place27_room7_floora)
	(receptacleatlocation receptacle19_chair location_xneg13_ypos61_place28_room7_floora)
	(receptacleatlocation receptacle20_chair location_xneg10_ypos69_place29_room7_floora)
	(receptacleatlocation receptacle21_chair location_xneg10_ypos67_place30_room7_floora)
	(receptacleatlocation receptacle22_chair location_xneg80_ypos55_place31_room9_floora)
	(receptacleatlocation receptacle23_chair location_xneg81_ypos69_place32_room9_floora)
	(receptacleatlocation receptacle24_chair location_xneg85_ypos67_place33_room9_floora)
	(receptacleatlocation receptacle25_couch location_xneg63_yneg34_place34_room13_floorb)
	(receptacleatlocation receptacle26_couch location_xneg79_yneg38_place35_room13_floorb)
	(receptacleatlocation receptacle27_couch location_xneg15_yneg28_place36_room10_floora)
	(receptacleatlocation receptacle41_bed location_xneg4_ypos19_place37_room4_floorb)
	(receptacleatlocation receptacle44_dining_table location_xneg6_ypos66_place40_room7_floora)
	(receptacleatlocation receptacle45_toilet location_xneg9_yneg35_place41_room2_floorb)
	(receptacleatlocation receptacle46_toilet location_xneg31_yneg28_place42_room3_floorb)
	(receptacleatlocation receptacle47_toilet location_xneg42_yneg16_place43_room1_floora)
	(receptacleatlocation receptacle53_microwave location_xneg16_ypos33_place44_room8_floora)
	(receptacleatlocation receptacle54_oven location_xneg15_ypos33_place45_room8_floora)
	(receptacleatlocation receptacle55_oven location_xpos5_yneg33_place46_room10_floora)
	(receptacleatlocation receptacle56_oven location_xneg41_yneg35_place47_room14_floora)
	(receptacleatlocation receptacle57_sink location_xpos9_yneg22_place48_room2_floorb)
	(receptacleatlocation receptacle58_sink location_xpos9_yneg14_place49_room2_floorb)
	(receptacleatlocation receptacle59_sink location_xpos5_yneg32_place50_room2_floorb)
	(receptacleatlocation receptacle60_sink location_xneg30_yneg20_place51_room3_floorb)
	(receptacleatlocation receptacle61_sink location_xpos9_ypos29_place52_room8_floora)
	(receptacleatlocation receptacle62_sink location_xneg43_yneg8_place53_room1_floora)
	(receptacleatlocation receptacle63_refrigerator location_xneg14_ypos44_place54_room8_floora)
	(receptacleatlocation receptacle64_refrigerator location_xneg34_ypos52_place55_room7_floora)
	(receptacleatlocation receptacle65_refrigerator location_xneg29_ypos54_place56_room7_floora)
	(receptacleatlocation receptacle66_refrigerator location_xneg38_yneg35_place57_room14_floora)
	(receptacleclass receptacle15_chair chair)
	(receptacleclass receptacle16_chair chair)
	(receptacleclass receptacle17_chair chair)
	(receptacleclass receptacle18_chair chair)
	(receptacleclass receptacle19_chair chair)
	(receptacleclass receptacle20_chair chair)
	(receptacleclass receptacle21_chair chair)
	(receptacleclass receptacle22_chair chair)
	(receptacleclass receptacle23_chair chair)
	(receptacleclass receptacle24_chair chair)
	(receptacleclass receptacle25_couch couch)
	(receptacleclass receptacle26_couch couch)
	(receptacleclass receptacle27_couch couch)
	(receptacleclass receptacle44_dining_table diningtable)
	(receptacleclass receptacle45_toilet toilet)
	(receptacleclass receptacle46_toilet toilet)
	(receptacleclass receptacle47_toilet toilet)
	(receptacleclass receptacle54_oven oven)
	(receptacleclass receptacle55_oven oven)
	(receptacleclass receptacle56_oven oven)
	(receptacleclass receptacle57_sink sink)
	(receptacleclass receptacle58_sink sink)
	(receptacleclass receptacle59_sink sink)
	(receptacleclass receptacle60_sink sink)
	(receptacleclass receptacle61_sink sink)
	(receptacleclass receptacle62_sink sink)
	(receptacleclass receptacle63_refrigerator refrigerator)
	(receptacleclass receptacle64_refrigerator refrigerator)
	(receptacleclass receptacle65_refrigerator refrigerator)
	(receptacleclass receptacle66_refrigerator refrigerator)
	(receptacleopeningtype receptacle53_microwave)
	(receptacleopeningtype receptacle54_oven)
	(receptacleopeningtype receptacle55_oven)
	(receptacleopeningtype receptacle56_oven)
	(receptacleopeningtype receptacle63_refrigerator)
	(receptacleopeningtype receptacle64_refrigerator)
	(receptacleopeningtype receptacle65_refrigerator)
	(receptacleopeningtype receptacle66_refrigerator)
	(roomplace place0_door_room12_staircase room12_staircase)
	(roomplace place10_door_room1_bathroom room1_bathroom)
	(roomplace place11_door_room14_utility_room room14_utility_room)
	(roomplace place12_door_room6_corridor room6_corridor)
	(roomplace place13_door_room11_lobby room11_lobby)
	(roomplace place1_door_room2_bathroom room2_bathroom)
	(roomplace place2_door_room3_bathroom room3_bathroom)
	(roomplace place3_door_room8_kitchen room8_kitchen)
	(roomplace place4_door_room7_dining_room room7_dining_room)
	(roomplace place5_door_room5_bedroom room5_bedroom)
	(roomplace place6_door_room9_living_room room9_living_room)
	(roomplace place7_door_room13_television_room room13_television_room)
	(roomplace place8_door_room10_living_room room10_living_room)
	(roomplace place9_door_room4_bedroom room4_bedroom)
	(roomsconnected room10_living_room room1_bathroom)
	(roomsconnected room11_lobby room12_staircase)
	(roomsconnected room11_lobby room1_bathroom)
	(roomsconnected room12_staircase room11_lobby)
	(roomsconnected room12_staircase room7_dining_room)
	(roomsconnected room12_staircase room8_kitchen)
	(roomsconnected room12_staircase room9_living_room)
	(roomsconnected room13_television_room room3_bathroom)
	(roomsconnected room14_utility_room room1_bathroom)
	(roomsconnected room14_utility_room room3_bathroom)
	(roomsconnected room1_bathroom room10_living_room)
	(roomsconnected room1_bathroom room11_lobby)
	(roomsconnected room1_bathroom room14_utility_room)
	(roomsconnected room2_bathroom room3_bathroom)
	(roomsconnected room3_bathroom room13_television_room)
	(roomsconnected room3_bathroom room14_utility_room)
	(roomsconnected room3_bathroom room2_bathroom)
	(roomsconnected room3_bathroom room6_corridor)
	(roomsconnected room4_bedroom room6_corridor)
	(roomsconnected room5_bedroom room6_corridor)
	(roomsconnected room6_corridor room3_bathroom)
	(roomsconnected room6_corridor room4_bedroom)
	(roomsconnected room6_corridor room5_bedroom)
	(roomsconnected room7_dining_room room12_staircase)
	(roomsconnected room8_kitchen room12_staircase)
	(roomsconnected room9_living_room room12_staircase)
	(smallitem item10_knife_smallitem)
	(smallitem item11_knife_smallitem)
	(smallitem item12_bowl_smallitem)
	(smallitem item13_bowl_smallitem)
	(smallitem item2_bottle_smallitem)
	(smallitem item3_bottle_smallitem)
	(smallitem item4_bottle_smallitem)
	(smallitem item51_remote_smallitem)
	(smallitem item52_remote_smallitem)
	(smallitem item5_bottle_smallitem)
	(smallitem item67_book_smallitem)
	(smallitem item6_wine_glass_smallitem)
	(smallitem item7_cup_smallitem)
	(smallitem item8_cup_smallitem)
	(smallitem item9_cup_smallitem)
  )
  (:goal (and
	(classrelation tv toilet)
	(classrelation vase chair)
	(classrelation pottedplant couch)
	(classrelation tv refrigerator)
	(classrelation remote sink)))
)
