
(define (problem wandotaskographyv5medium5bagslots5problem50) (:domain taskographyv5medium5bagslots5scrub)
  (:objects
        bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	bottle - iclass
	chair - rclass
	couch - rclass
	item10_vase_mediumitem - item
	item11_vase_mediumitem - item
	item12_vase_mediumitem - item
	item13_vase_mediumitem - item
	item14_tie_smallitem - item
	item15_tie_smallitem - item
	item16_tie_smallitem - item
	item17_tie_smallitem - item
	item1_remote_smallitem - item
	item27_potted_plant_largeitem - item
	item28_potted_plant_largeitem - item
	item33_tv_largeitem - item
	item34_tv_largeitem - item
	item35_tv_largeitem - item
	item8_bottle_smallitem - item
	item9_bottle_smallitem - item
	location_xneg10_yneg38_place23_room1_floora - location
	location_xneg10_yneg39_place23_room1_floora - location
	location_xneg10_yneg48_place26_room1_floora - location
	location_xneg14_yneg25_place8_room6_floora - location
	location_xneg14_yneg47_place14_room3_floora - location
	location_xneg17_ypos0_place32_room2_floora - location
	location_xneg18_ypos0_place31_room2_floora - location
	location_xneg19_yneg6_place28_room2_floora - location
	location_xneg19_ypos8_place29_room2_floora - location
	location_xneg19_ypos8_place30_room2_floora - location
	location_xneg32_yneg46_place4_room3_floora - location
	location_xneg34_yneg3_place3_room2_floora - location
	location_xneg37_yneg18_place25_room2_floora - location
	location_xneg41_yneg28_place16_room5_floora - location
	location_xneg43_yneg28_place15_room5_floora - location
	location_xneg45_yneg18_place7_room4_floora - location
	location_xneg45_yneg27_place5_room5_floora - location
	location_xneg46_yneg28_place17_room5_floora - location
	location_xneg48_yneg27_place18_room5_floora - location
	location_xneg4_yneg45_place2_room1_floora - location
	location_xneg7_yneg49_place26_room1_floora - location
	location_xneg8_yneg35_place23_room1_floora - location
	location_xpos11_ypos2_place1_room8_floora - location
	location_xpos14_ypos9_place22_room8_floora - location
	location_xpos16_yneg15_place11_room9_floora - location
	location_xpos19_yneg15_place10_room9_floora - location
	location_xpos19_yneg17_place9_room9_floora - location
	location_xpos21_yneg9_place24_room8_floora - location
	location_xpos28_yneg37_place0_room9_floora - location
	location_xpos33_yneg53_place34_room9_floora - location
	location_xpos36_yneg46_place34_room9_floora - location
	location_xpos36_ypos2_place27_room7_floora - location
	location_xpos40_yneg1_place6_room7_floora - location
	location_xpos40_ypos2_place27_room7_floora - location
	location_xpos45_ypos8_place33_room7_floora - location
	location_xpos5_yneg44_place12_room9_floora - location
	location_xpos5_yneg44_place13_room9_floora - location
	location_xpos7_yneg35_place19_room9_floora - location
	place0_door_room9_living_room - place
	place10_item34_tv - place
	place11_item35_tv - place
	place12_item10_vase - place
	place13_item11_vase - place
	place14_item12_vase - place
	place15_item14_tie - place
	place16_item15_tie - place
	place17_item16_tie - place
	place18_item17_tie - place
	place19_item28_potted_plant - place
	place1_door_room8_kitchen - place
	place22_receptacle3_sink - place
	place23_receptacle4_sink - place
	place24_receptacle5_refrigerator - place
	place25_receptacle6_refrigerator - place
	place26_receptacle18_toilet - place
	place27_receptacle19_chair - place
	place28_receptacle20_chair - place
	place29_receptacle21_chair - place
	place2_door_room1_bathroom - place
	place30_receptacle22_chair - place
	place31_receptacle23_chair - place
	place32_receptacle24_chair - place
	place33_receptacle25_chair - place
	place34_receptacle26_couch - place
	place3_door_room2_bedroom - place
	place4_door_room3_bedroom - place
	place5_door_room5_closet - place
	place6_door_room7_dining_room - place
	place7_door_room4_closet - place
	place8_door_room6_corridor - place
	place9_item33_tv - place
	pottedplant - iclass
	receptacle18_toilet - receptacle
	receptacle19_chair - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_couch - receptacle
	receptacle3_sink - receptacle
	receptacle4_sink - receptacle
	receptacle5_refrigerator - receptacle
	receptacle6_refrigerator - receptacle
	refrigerator - rclass
	remote - iclass
	robot - agent
	room1_bathroom - room
	room2_bedroom - room
	room3_bedroom - room
	room4_closet - room
	room5_closet - room
	room6_corridor - room
	room7_dining_room - room
	room8_kitchen - room
	room9_living_room - room
	sink - rclass
	tie - iclass
	toilet - rclass
	tv - iclass
	vase - iclass
  )
  (:init 
	(atlocation robot location_xpos11_ypos2_place1_room8_floora)
	(classrelation bottle sink)
	(classrelation pottedplant chair)
	(classrelation remote couch)
	(classrelation vase toilet)
	(inanyreceptacle item13_vase_mediumitem)
	(inanyreceptacle item1_remote_smallitem)
	(inanyreceptacle item27_potted_plant_largeitem)
	(inanyreceptacle item8_bottle_smallitem)
	(inanyreceptacle item9_bottle_smallitem)
	(inplace robot place1_door_room8_kitchen)
	(inreceptacle item13_vase_mediumitem receptacle18_toilet)
	(inreceptacle item1_remote_smallitem receptacle26_couch)
	(inreceptacle item27_potted_plant_largeitem receptacle19_chair)
	(inreceptacle item8_bottle_smallitem receptacle4_sink)
	(inreceptacle item9_bottle_smallitem receptacle4_sink)
	(inroom robot room8_kitchen)
	(itematlocation item10_vase_mediumitem location_xpos5_yneg44_place12_room9_floora)
	(itematlocation item11_vase_mediumitem location_xpos5_yneg44_place13_room9_floora)
	(itematlocation item12_vase_mediumitem location_xneg14_yneg47_place14_room3_floora)
	(itematlocation item13_vase_mediumitem location_xneg10_yneg48_place26_room1_floora)
	(itematlocation item14_tie_smallitem location_xneg43_yneg28_place15_room5_floora)
	(itematlocation item15_tie_smallitem location_xneg41_yneg28_place16_room5_floora)
	(itematlocation item16_tie_smallitem location_xneg46_yneg28_place17_room5_floora)
	(itematlocation item17_tie_smallitem location_xneg48_yneg27_place18_room5_floora)
	(itematlocation item1_remote_smallitem location_xpos36_yneg46_place34_room9_floora)
	(itematlocation item27_potted_plant_largeitem location_xpos40_ypos2_place27_room7_floora)
	(itematlocation item28_potted_plant_largeitem location_xpos7_yneg35_place19_room9_floora)
	(itematlocation item33_tv_largeitem location_xpos19_yneg17_place9_room9_floora)
	(itematlocation item34_tv_largeitem location_xpos19_yneg15_place10_room9_floora)
	(itematlocation item35_tv_largeitem location_xpos16_yneg15_place11_room9_floora)
	(itematlocation item8_bottle_smallitem location_xneg10_yneg39_place23_room1_floora)
	(itematlocation item9_bottle_smallitem location_xneg10_yneg38_place23_room1_floora)
	(itemclass item10_vase_mediumitem vase)
	(itemclass item11_vase_mediumitem vase)
	(itemclass item12_vase_mediumitem vase)
	(itemclass item13_vase_mediumitem vase)
	(itemclass item14_tie_smallitem tie)
	(itemclass item15_tie_smallitem tie)
	(itemclass item16_tie_smallitem tie)
	(itemclass item17_tie_smallitem tie)
	(itemclass item1_remote_smallitem remote)
	(itemclass item27_potted_plant_largeitem pottedplant)
	(itemclass item28_potted_plant_largeitem pottedplant)
	(itemclass item33_tv_largeitem tv)
	(itemclass item34_tv_largeitem tv)
	(itemclass item35_tv_largeitem tv)
	(itemclass item8_bottle_smallitem bottle)
	(itemclass item9_bottle_smallitem bottle)
	(largeitem item27_potted_plant_largeitem)
	(largeitem item28_potted_plant_largeitem)
	(largeitem item33_tv_largeitem)
	(largeitem item34_tv_largeitem)
	(largeitem item35_tv_largeitem)
	(locationinplace location_xneg10_yneg38_place23_room1_floora place23_receptacle4_sink)
	(locationinplace location_xneg10_yneg39_place23_room1_floora place23_receptacle4_sink)
	(locationinplace location_xneg10_yneg48_place26_room1_floora place26_receptacle18_toilet)
	(locationinplace location_xneg14_yneg25_place8_room6_floora place8_door_room6_corridor)
	(locationinplace location_xneg14_yneg47_place14_room3_floora place14_item12_vase)
	(locationinplace location_xneg17_ypos0_place32_room2_floora place32_receptacle24_chair)
	(locationinplace location_xneg18_ypos0_place31_room2_floora place31_receptacle23_chair)
	(locationinplace location_xneg19_yneg6_place28_room2_floora place28_receptacle20_chair)
	(locationinplace location_xneg19_ypos8_place29_room2_floora place29_receptacle21_chair)
	(locationinplace location_xneg19_ypos8_place30_room2_floora place30_receptacle22_chair)
	(locationinplace location_xneg32_yneg46_place4_room3_floora place4_door_room3_bedroom)
	(locationinplace location_xneg34_yneg3_place3_room2_floora place3_door_room2_bedroom)
	(locationinplace location_xneg37_yneg18_place25_room2_floora place25_receptacle6_refrigerator)
	(locationinplace location_xneg41_yneg28_place16_room5_floora place16_item15_tie)
	(locationinplace location_xneg43_yneg28_place15_room5_floora place15_item14_tie)
	(locationinplace location_xneg45_yneg18_place7_room4_floora place7_door_room4_closet)
	(locationinplace location_xneg45_yneg27_place5_room5_floora place5_door_room5_closet)
	(locationinplace location_xneg46_yneg28_place17_room5_floora place17_item16_tie)
	(locationinplace location_xneg48_yneg27_place18_room5_floora place18_item17_tie)
	(locationinplace location_xneg4_yneg45_place2_room1_floora place2_door_room1_bathroom)
	(locationinplace location_xneg7_yneg49_place26_room1_floora place26_receptacle18_toilet)
	(locationinplace location_xneg8_yneg35_place23_room1_floora place23_receptacle4_sink)
	(locationinplace location_xpos11_ypos2_place1_room8_floora place1_door_room8_kitchen)
	(locationinplace location_xpos14_ypos9_place22_room8_floora place22_receptacle3_sink)
	(locationinplace location_xpos16_yneg15_place11_room9_floora place11_item35_tv)
	(locationinplace location_xpos19_yneg15_place10_room9_floora place10_item34_tv)
	(locationinplace location_xpos19_yneg17_place9_room9_floora place9_item33_tv)
	(locationinplace location_xpos21_yneg9_place24_room8_floora place24_receptacle5_refrigerator)
	(locationinplace location_xpos28_yneg37_place0_room9_floora place0_door_room9_living_room)
	(locationinplace location_xpos33_yneg53_place34_room9_floora place34_receptacle26_couch)
	(locationinplace location_xpos36_yneg46_place34_room9_floora place34_receptacle26_couch)
	(locationinplace location_xpos36_ypos2_place27_room7_floora place27_receptacle19_chair)
	(locationinplace location_xpos40_yneg1_place6_room7_floora place6_door_room7_dining_room)
	(locationinplace location_xpos40_ypos2_place27_room7_floora place27_receptacle19_chair)
	(locationinplace location_xpos45_ypos8_place33_room7_floora place33_receptacle25_chair)
	(locationinplace location_xpos5_yneg44_place12_room9_floora place12_item10_vase)
	(locationinplace location_xpos5_yneg44_place13_room9_floora place13_item11_vase)
	(locationinplace location_xpos7_yneg35_place19_room9_floora place19_item28_potted_plant)
	(mediumitem item10_vase_mediumitem)
	(mediumitem item11_vase_mediumitem)
	(mediumitem item12_vase_mediumitem)
	(mediumitem item13_vase_mediumitem)
	(placeinroom place0_door_room9_living_room room9_living_room)
	(placeinroom place10_item34_tv room9_living_room)
	(placeinroom place11_item35_tv room9_living_room)
	(placeinroom place12_item10_vase room9_living_room)
	(placeinroom place13_item11_vase room9_living_room)
	(placeinroom place14_item12_vase room3_bedroom)
	(placeinroom place15_item14_tie room5_closet)
	(placeinroom place16_item15_tie room5_closet)
	(placeinroom place17_item16_tie room5_closet)
	(placeinroom place18_item17_tie room5_closet)
	(placeinroom place19_item28_potted_plant room9_living_room)
	(placeinroom place1_door_room8_kitchen room8_kitchen)
	(placeinroom place22_receptacle3_sink room8_kitchen)
	(placeinroom place23_receptacle4_sink room1_bathroom)
	(placeinroom place24_receptacle5_refrigerator room8_kitchen)
	(placeinroom place25_receptacle6_refrigerator room2_bedroom)
	(placeinroom place26_receptacle18_toilet room1_bathroom)
	(placeinroom place27_receptacle19_chair room7_dining_room)
	(placeinroom place28_receptacle20_chair room2_bedroom)
	(placeinroom place29_receptacle21_chair room2_bedroom)
	(placeinroom place2_door_room1_bathroom room1_bathroom)
	(placeinroom place30_receptacle22_chair room2_bedroom)
	(placeinroom place31_receptacle23_chair room2_bedroom)
	(placeinroom place32_receptacle24_chair room2_bedroom)
	(placeinroom place33_receptacle25_chair room7_dining_room)
	(placeinroom place34_receptacle26_couch room9_living_room)
	(placeinroom place3_door_room2_bedroom room2_bedroom)
	(placeinroom place4_door_room3_bedroom room3_bedroom)
	(placeinroom place5_door_room5_closet room5_closet)
	(placeinroom place6_door_room7_dining_room room7_dining_room)
	(placeinroom place7_door_room4_closet room4_closet)
	(placeinroom place8_door_room6_corridor room6_corridor)
	(placeinroom place9_item33_tv room9_living_room)
	(placelocation location_xneg14_yneg25_place8_room6_floora place8_door_room6_corridor)
	(placelocation location_xneg14_yneg47_place14_room3_floora place14_item12_vase)
	(placelocation location_xneg17_ypos0_place32_room2_floora place32_receptacle24_chair)
	(placelocation location_xneg18_ypos0_place31_room2_floora place31_receptacle23_chair)
	(placelocation location_xneg19_yneg6_place28_room2_floora place28_receptacle20_chair)
	(placelocation location_xneg19_ypos8_place29_room2_floora place29_receptacle21_chair)
	(placelocation location_xneg19_ypos8_place30_room2_floora place30_receptacle22_chair)
	(placelocation location_xneg32_yneg46_place4_room3_floora place4_door_room3_bedroom)
	(placelocation location_xneg34_yneg3_place3_room2_floora place3_door_room2_bedroom)
	(placelocation location_xneg37_yneg18_place25_room2_floora place25_receptacle6_refrigerator)
	(placelocation location_xneg41_yneg28_place16_room5_floora place16_item15_tie)
	(placelocation location_xneg43_yneg28_place15_room5_floora place15_item14_tie)
	(placelocation location_xneg45_yneg18_place7_room4_floora place7_door_room4_closet)
	(placelocation location_xneg45_yneg27_place5_room5_floora place5_door_room5_closet)
	(placelocation location_xneg46_yneg28_place17_room5_floora place17_item16_tie)
	(placelocation location_xneg48_yneg27_place18_room5_floora place18_item17_tie)
	(placelocation location_xneg4_yneg45_place2_room1_floora place2_door_room1_bathroom)
	(placelocation location_xneg7_yneg49_place26_room1_floora place26_receptacle18_toilet)
	(placelocation location_xneg8_yneg35_place23_room1_floora place23_receptacle4_sink)
	(placelocation location_xpos11_ypos2_place1_room8_floora place1_door_room8_kitchen)
	(placelocation location_xpos14_ypos9_place22_room8_floora place22_receptacle3_sink)
	(placelocation location_xpos16_yneg15_place11_room9_floora place11_item35_tv)
	(placelocation location_xpos19_yneg15_place10_room9_floora place10_item34_tv)
	(placelocation location_xpos19_yneg17_place9_room9_floora place9_item33_tv)
	(placelocation location_xpos21_yneg9_place24_room8_floora place24_receptacle5_refrigerator)
	(placelocation location_xpos28_yneg37_place0_room9_floora place0_door_room9_living_room)
	(placelocation location_xpos33_yneg53_place34_room9_floora place34_receptacle26_couch)
	(placelocation location_xpos36_ypos2_place27_room7_floora place27_receptacle19_chair)
	(placelocation location_xpos40_yneg1_place6_room7_floora place6_door_room7_dining_room)
	(placelocation location_xpos45_ypos8_place33_room7_floora place33_receptacle25_chair)
	(placelocation location_xpos5_yneg44_place12_room9_floora place12_item10_vase)
	(placelocation location_xpos5_yneg44_place13_room9_floora place13_item11_vase)
	(placelocation location_xpos7_yneg35_place19_room9_floora place19_item28_potted_plant)
	(receptacleatlocation receptacle18_toilet location_xneg7_yneg49_place26_room1_floora)
	(receptacleatlocation receptacle19_chair location_xpos36_ypos2_place27_room7_floora)
	(receptacleatlocation receptacle20_chair location_xneg19_yneg6_place28_room2_floora)
	(receptacleatlocation receptacle21_chair location_xneg19_ypos8_place29_room2_floora)
	(receptacleatlocation receptacle22_chair location_xneg19_ypos8_place30_room2_floora)
	(receptacleatlocation receptacle23_chair location_xneg18_ypos0_place31_room2_floora)
	(receptacleatlocation receptacle24_chair location_xneg17_ypos0_place32_room2_floora)
	(receptacleatlocation receptacle25_chair location_xpos45_ypos8_place33_room7_floora)
	(receptacleatlocation receptacle26_couch location_xpos33_yneg53_place34_room9_floora)
	(receptacleatlocation receptacle3_sink location_xpos14_ypos9_place22_room8_floora)
	(receptacleatlocation receptacle4_sink location_xneg8_yneg35_place23_room1_floora)
	(receptacleatlocation receptacle5_refrigerator location_xpos21_yneg9_place24_room8_floora)
	(receptacleatlocation receptacle6_refrigerator location_xneg37_yneg18_place25_room2_floora)
	(receptacleclass receptacle18_toilet toilet)
	(receptacleclass receptacle19_chair chair)
	(receptacleclass receptacle20_chair chair)
	(receptacleclass receptacle21_chair chair)
	(receptacleclass receptacle22_chair chair)
	(receptacleclass receptacle23_chair chair)
	(receptacleclass receptacle24_chair chair)
	(receptacleclass receptacle25_chair chair)
	(receptacleclass receptacle26_couch couch)
	(receptacleclass receptacle3_sink sink)
	(receptacleclass receptacle4_sink sink)
	(receptacleclass receptacle5_refrigerator refrigerator)
	(receptacleclass receptacle6_refrigerator refrigerator)
	(receptacleopeningtype receptacle5_refrigerator)
	(receptacleopeningtype receptacle6_refrigerator)
	(roomplace place0_door_room9_living_room room9_living_room)
	(roomplace place1_door_room8_kitchen room8_kitchen)
	(roomplace place2_door_room1_bathroom room1_bathroom)
	(roomplace place3_door_room2_bedroom room2_bedroom)
	(roomplace place4_door_room3_bedroom room3_bedroom)
	(roomplace place5_door_room5_closet room5_closet)
	(roomplace place6_door_room7_dining_room room7_dining_room)
	(roomplace place7_door_room4_closet room4_closet)
	(roomplace place8_door_room6_corridor room6_corridor)
	(roomsconnected room1_bathroom room6_corridor)
	(roomsconnected room1_bathroom room9_living_room)
	(roomsconnected room2_bedroom room4_closet)
	(roomsconnected room3_bedroom room5_closet)
	(roomsconnected room3_bedroom room6_corridor)
	(roomsconnected room4_closet room2_bedroom)
	(roomsconnected room4_closet room5_closet)
	(roomsconnected room5_closet room3_bedroom)
	(roomsconnected room5_closet room4_closet)
	(roomsconnected room6_corridor room1_bathroom)
	(roomsconnected room6_corridor room3_bedroom)
	(roomsconnected room6_corridor room8_kitchen)
	(roomsconnected room7_dining_room room8_kitchen)
	(roomsconnected room8_kitchen room6_corridor)
	(roomsconnected room8_kitchen room7_dining_room)
	(roomsconnected room9_living_room room1_bathroom)
	(smallitem item14_tie_smallitem)
	(smallitem item15_tie_smallitem)
	(smallitem item16_tie_smallitem)
	(smallitem item17_tie_smallitem)
	(smallitem item1_remote_smallitem)
	(smallitem item8_bottle_smallitem)
	(smallitem item9_bottle_smallitem)
  )
  (:goal (and
	(classrelation vase sink)
	(classrelation remote chair)
	(classrelation tv chair)
	(classrelation tie chair)
	(classrelation tie refrigerator)))
)
