
(define (problem maidataskographyv5medium5bagslots5problem40) (:domain taskographyv5medium5bagslots5scrub)
  (:objects
        bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	bed - rclass
	chair - rclass
	couch - rclass
	item16_tv_largeitem - item
	item1_keyboard_largeitem - item
	keyboard - iclass
	location_xneg13_yneg15_place7_room4_floora - location
	location_xneg13_yneg9_place8_room2_floora - location
	location_xneg13_ypos22_place11_room2_floora - location
	location_xneg13_ypos4_place13_room2_floora - location
	location_xneg14_yneg22_place6_room4_floora - location
	location_xneg14_yneg27_place6_room4_floora - location
	location_xneg15_ypos24_place12_room2_floora - location
	location_xneg7_yneg23_place0_room4_floora - location
	location_xneg7_ypos5_place15_room2_floora - location
	location_xneg8_ypos12_place14_room2_floora - location
	location_xpos16_ypos11_place16_room2_floora - location
	location_xpos17_yneg28_place1_room1_floora - location
	location_xpos18_yneg12_place3_room3_floora - location
	location_xpos21_ypos20_place17_room2_floora - location
	location_xpos25_yneg23_place5_room1_floora - location
	location_xpos3_ypos27_place11_room2_floora - location
	location_xpos5_ypos10_place2_room2_floora - location
	place0_door_room4_kitchen - place
	place11_receptacle9_chair - place
	place12_receptacle10_chair - place
	place13_receptacle11_couch - place
	place14_receptacle12_couch - place
	place15_receptacle13_couch - place
	place16_receptacle14_bed - place
	place17_receptacle15_bed - place
	place1_door_room1_bathroom - place
	place2_door_room2_bedroom - place
	place3_door_room3_closet - place
	place5_receptacle3_sink - place
	place6_receptacle4_sink - place
	place7_receptacle5_refrigerator - place
	place8_receptacle6_refrigerator - place
	receptacle10_chair - receptacle
	receptacle11_couch - receptacle
	receptacle12_couch - receptacle
	receptacle13_couch - receptacle
	receptacle14_bed - receptacle
	receptacle15_bed - receptacle
	receptacle3_sink - receptacle
	receptacle4_sink - receptacle
	receptacle5_refrigerator - receptacle
	receptacle6_refrigerator - receptacle
	receptacle9_chair - receptacle
	refrigerator - rclass
	robot - agent
	room1_bathroom - room
	room2_bedroom - room
	room3_closet - room
	room4_kitchen - room
	sink - rclass
	tv - iclass
  )
  (:init 
	(atlocation robot location_xneg7_yneg23_place0_room4_floora)
	(classrelation keyboard sink)
	(classrelation tv chair)
	(inanyreceptacle item16_tv_largeitem)
	(inanyreceptacle item1_keyboard_largeitem)
	(inplace robot place0_door_room4_kitchen)
	(inreceptacle item16_tv_largeitem receptacle9_chair)
	(inreceptacle item1_keyboard_largeitem receptacle4_sink)
	(inroom robot room4_kitchen)
	(itematlocation item16_tv_largeitem location_xpos3_ypos27_place11_room2_floora)
	(itematlocation item1_keyboard_largeitem location_xneg14_yneg22_place6_room4_floora)
	(itemclass item16_tv_largeitem tv)
	(itemclass item1_keyboard_largeitem keyboard)
	(largeitem item16_tv_largeitem)
	(largeitem item1_keyboard_largeitem)
	(locationinplace location_xneg13_yneg15_place7_room4_floora place7_receptacle5_refrigerator)
	(locationinplace location_xneg13_yneg9_place8_room2_floora place8_receptacle6_refrigerator)
	(locationinplace location_xneg13_ypos22_place11_room2_floora place11_receptacle9_chair)
	(locationinplace location_xneg13_ypos4_place13_room2_floora place13_receptacle11_couch)
	(locationinplace location_xneg14_yneg22_place6_room4_floora place6_receptacle4_sink)
	(locationinplace location_xneg14_yneg27_place6_room4_floora place6_receptacle4_sink)
	(locationinplace location_xneg15_ypos24_place12_room2_floora place12_receptacle10_chair)
	(locationinplace location_xneg7_yneg23_place0_room4_floora place0_door_room4_kitchen)
	(locationinplace location_xneg7_ypos5_place15_room2_floora place15_receptacle13_couch)
	(locationinplace location_xneg8_ypos12_place14_room2_floora place14_receptacle12_couch)
	(locationinplace location_xpos16_ypos11_place16_room2_floora place16_receptacle14_bed)
	(locationinplace location_xpos17_yneg28_place1_room1_floora place1_door_room1_bathroom)
	(locationinplace location_xpos18_yneg12_place3_room3_floora place3_door_room3_closet)
	(locationinplace location_xpos21_ypos20_place17_room2_floora place17_receptacle15_bed)
	(locationinplace location_xpos25_yneg23_place5_room1_floora place5_receptacle3_sink)
	(locationinplace location_xpos3_ypos27_place11_room2_floora place11_receptacle9_chair)
	(locationinplace location_xpos5_ypos10_place2_room2_floora place2_door_room2_bedroom)
	(placeinroom place0_door_room4_kitchen room4_kitchen)
	(placeinroom place11_receptacle9_chair room2_bedroom)
	(placeinroom place12_receptacle10_chair room2_bedroom)
	(placeinroom place13_receptacle11_couch room2_bedroom)
	(placeinroom place14_receptacle12_couch room2_bedroom)
	(placeinroom place15_receptacle13_couch room2_bedroom)
	(placeinroom place16_receptacle14_bed room2_bedroom)
	(placeinroom place17_receptacle15_bed room2_bedroom)
	(placeinroom place1_door_room1_bathroom room1_bathroom)
	(placeinroom place2_door_room2_bedroom room2_bedroom)
	(placeinroom place3_door_room3_closet room3_closet)
	(placeinroom place5_receptacle3_sink room1_bathroom)
	(placeinroom place6_receptacle4_sink room4_kitchen)
	(placeinroom place7_receptacle5_refrigerator room4_kitchen)
	(placeinroom place8_receptacle6_refrigerator room2_bedroom)
	(placelocation location_xneg13_yneg15_place7_room4_floora place7_receptacle5_refrigerator)
	(placelocation location_xneg13_yneg9_place8_room2_floora place8_receptacle6_refrigerator)
	(placelocation location_xneg13_ypos22_place11_room2_floora place11_receptacle9_chair)
	(placelocation location_xneg13_ypos4_place13_room2_floora place13_receptacle11_couch)
	(placelocation location_xneg14_yneg27_place6_room4_floora place6_receptacle4_sink)
	(placelocation location_xneg15_ypos24_place12_room2_floora place12_receptacle10_chair)
	(placelocation location_xneg7_yneg23_place0_room4_floora place0_door_room4_kitchen)
	(placelocation location_xneg7_ypos5_place15_room2_floora place15_receptacle13_couch)
	(placelocation location_xneg8_ypos12_place14_room2_floora place14_receptacle12_couch)
	(placelocation location_xpos16_ypos11_place16_room2_floora place16_receptacle14_bed)
	(placelocation location_xpos17_yneg28_place1_room1_floora place1_door_room1_bathroom)
	(placelocation location_xpos18_yneg12_place3_room3_floora place3_door_room3_closet)
	(placelocation location_xpos21_ypos20_place17_room2_floora place17_receptacle15_bed)
	(placelocation location_xpos25_yneg23_place5_room1_floora place5_receptacle3_sink)
	(placelocation location_xpos5_ypos10_place2_room2_floora place2_door_room2_bedroom)
	(receptacleatlocation receptacle10_chair location_xneg15_ypos24_place12_room2_floora)
	(receptacleatlocation receptacle11_couch location_xneg13_ypos4_place13_room2_floora)
	(receptacleatlocation receptacle12_couch location_xneg8_ypos12_place14_room2_floora)
	(receptacleatlocation receptacle13_couch location_xneg7_ypos5_place15_room2_floora)
	(receptacleatlocation receptacle14_bed location_xpos16_ypos11_place16_room2_floora)
	(receptacleatlocation receptacle15_bed location_xpos21_ypos20_place17_room2_floora)
	(receptacleatlocation receptacle3_sink location_xpos25_yneg23_place5_room1_floora)
	(receptacleatlocation receptacle4_sink location_xneg14_yneg27_place6_room4_floora)
	(receptacleatlocation receptacle5_refrigerator location_xneg13_yneg15_place7_room4_floora)
	(receptacleatlocation receptacle6_refrigerator location_xneg13_yneg9_place8_room2_floora)
	(receptacleatlocation receptacle9_chair location_xneg13_ypos22_place11_room2_floora)
	(receptacleclass receptacle10_chair chair)
	(receptacleclass receptacle11_couch couch)
	(receptacleclass receptacle12_couch couch)
	(receptacleclass receptacle13_couch couch)
	(receptacleclass receptacle14_bed bed)
	(receptacleclass receptacle15_bed bed)
	(receptacleclass receptacle3_sink sink)
	(receptacleclass receptacle4_sink sink)
	(receptacleclass receptacle5_refrigerator refrigerator)
	(receptacleclass receptacle6_refrigerator refrigerator)
	(receptacleclass receptacle9_chair chair)
	(receptacleopeningtype receptacle5_refrigerator)
	(receptacleopeningtype receptacle6_refrigerator)
	(roomplace place0_door_room4_kitchen room4_kitchen)
	(roomplace place1_door_room1_bathroom room1_bathroom)
	(roomplace place2_door_room2_bedroom room2_bedroom)
	(roomplace place3_door_room3_closet room3_closet)
	(roomsconnected room1_bathroom room3_closet)
	(roomsconnected room1_bathroom room4_kitchen)
	(roomsconnected room2_bedroom room3_closet)
	(roomsconnected room3_closet room1_bathroom)
	(roomsconnected room3_closet room2_bedroom)
	(roomsconnected room4_kitchen room1_bathroom)
  )
  (:goal (and
	(classrelation keyboard bed)
	(classrelation keyboard refrigerator)
	(classrelation tv bed)
	(classrelation keyboard couch)
	(classrelation tv refrigerator)))
)
