
(define (problem sandstaskographyv5medium5bagslots5problem178) (:domain taskographyv5medium5bagslots5scrub)
  (:objects
        bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	bottle - iclass
	couch - rclass
	cup - iclass
	frisbee - iclass
	item15_cup_smallitem - item
	item16_bottle_smallitem - item
	item17_bottle_smallitem - item
	item18_bottle_smallitem - item
	item19_frisbee_mediumitem - item
	item25_potted_plant_largeitem - item
	item26_potted_plant_largeitem - item
	item27_potted_plant_largeitem - item
	location_xneg1_yneg20_place2_room8_floorb - location
	location_xneg1_yneg24_place7_room5_floora - location
	location_xpos12_yneg9_place24_room5_floora - location
	location_xpos16_ypos14_place6_room7_floorb - location
	location_xpos23_ypos1_place8_room6_floora - location
	location_xpos2_yneg7_place11_room6_floora - location
	location_xpos32_yneg29_place9_room10_floora - location
	location_xpos35_ypos12_place15_room9_floora - location
	location_xpos36_yneg21_place10_room4_floorb - location
	location_xpos36_ypos26_place22_room9_floora - location
	location_xpos37_ypos3_place21_room7_floorb - location
	location_xpos38_yneg36_place30_room10_floora - location
	location_xpos40_yneg36_place23_room1_floora - location
	location_xpos42_ypos15_place28_room11_floorb - location
	location_xpos43_ypos19_place0_room9_floora - location
	location_xpos44_ypos12_place16_room11_floorb - location
	location_xpos47_yneg31_place4_room1_floora - location
	location_xpos47_yneg3_place5_room2_floorb - location
	location_xpos47_ypos15_place1_room11_floorb - location
	location_xpos47_ypos25_place3_room3_floorb - location
	location_xpos47_ypos6_place20_room2_floorb - location
	location_xpos49_ypos10_place14_room9_floora - location
	location_xpos50_ypos14_place29_room11_floorb - location
	location_xpos51_yneg24_place18_room1_floora - location
	location_xpos51_yneg36_place26_room1_floora - location
	location_xpos51_yneg5_place27_room2_floorb - location
	location_xpos52_yneg10_place19_room2_floorb - location
	location_xpos52_yneg28_place18_room1_floora - location
	location_xpos52_ypos17_place17_room9_floora - location
	location_xpos53_yneg12_place19_room2_floorb - location
	location_xpos53_yneg25_place18_room1_floora - location
	location_xpos53_yneg8_place19_room2_floorb - location
	location_xpos53_ypos9_place14_room9_floora - location
	location_xpos54_yneg3_place27_room2_floorb - location
	location_xpos5_yneg39_place25_room5_floora - location
	oven - rclass
	place0_door_room9_kitchen - place
	place10_door_room4_corridor - place
	place11_item19_frisbee - place
	place14_receptacle1_oven - place
	place15_receptacle2_oven - place
	place16_receptacle3_oven - place
	place17_receptacle6_sink - place
	place18_receptacle7_sink - place
	place19_receptacle8_sink - place
	place1_door_room11_utility_room - place
	place20_receptacle9_sink - place
	place21_receptacle10_sink - place
	place22_receptacle11_refrigerator - place
	place23_receptacle12_refrigerator - place
	place24_receptacle13_refrigerator - place
	place25_receptacle14_refrigerator - place
	place26_receptacle20_toilet - place
	place27_receptacle21_toilet - place
	place28_receptacle22_toilet - place
	place29_receptacle23_toilet - place
	place2_door_room8_empty_room - place
	place30_receptacle24_couch - place
	place3_door_room3_closet - place
	place4_door_room1_bathroom - place
	place5_door_room2_bathroom - place
	place6_door_room7_empty_room - place
	place7_door_room5_empty_room - place
	place8_door_room6_empty_room - place
	place9_door_room10_staircase - place
	pottedplant - iclass
	receptacle10_sink - receptacle
	receptacle11_refrigerator - receptacle
	receptacle12_refrigerator - receptacle
	receptacle13_refrigerator - receptacle
	receptacle14_refrigerator - receptacle
	receptacle1_oven - receptacle
	receptacle20_toilet - receptacle
	receptacle21_toilet - receptacle
	receptacle22_toilet - receptacle
	receptacle23_toilet - receptacle
	receptacle24_couch - receptacle
	receptacle2_oven - receptacle
	receptacle3_oven - receptacle
	receptacle6_sink - receptacle
	receptacle7_sink - receptacle
	receptacle8_sink - receptacle
	receptacle9_sink - receptacle
	refrigerator - rclass
	robot - agent
	room10_staircase - room
	room11_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_closet - room
	room4_corridor - room
	room5_empty_room - room
	room6_empty_room - room
	room7_empty_room - room
	room8_empty_room - room
	room9_kitchen - room
	sink - rclass
	toilet - rclass
  )
  (:init 
	(atlocation robot location_xpos32_yneg29_place9_room10_floora)
	(classrelation bottle sink)
	(classrelation bottle toilet)
	(classrelation cup sink)
	(classrelation pottedplant oven)
	(classrelation pottedplant sink)
	(inanyreceptacle item15_cup_smallitem)
	(inanyreceptacle item16_bottle_smallitem)
	(inanyreceptacle item17_bottle_smallitem)
	(inanyreceptacle item18_bottle_smallitem)
	(inanyreceptacle item25_potted_plant_largeitem)
	(inanyreceptacle item26_potted_plant_largeitem)
	(inanyreceptacle item27_potted_plant_largeitem)
	(inplace robot place9_door_room10_staircase)
	(inreceptacle item15_cup_smallitem receptacle8_sink)
	(inreceptacle item16_bottle_smallitem receptacle7_sink)
	(inreceptacle item17_bottle_smallitem receptacle8_sink)
	(inreceptacle item18_bottle_smallitem receptacle21_toilet)
	(inreceptacle item25_potted_plant_largeitem receptacle1_oven)
	(inreceptacle item26_potted_plant_largeitem receptacle7_sink)
	(inreceptacle item27_potted_plant_largeitem receptacle8_sink)
	(inroom robot room10_staircase)
	(itematlocation item15_cup_smallitem location_xpos53_yneg8_place19_room2_floorb)
	(itematlocation item16_bottle_smallitem location_xpos53_yneg25_place18_room1_floora)
	(itematlocation item17_bottle_smallitem location_xpos53_yneg8_place19_room2_floorb)
	(itematlocation item18_bottle_smallitem location_xpos54_yneg3_place27_room2_floorb)
	(itematlocation item19_frisbee_mediumitem location_xpos2_yneg7_place11_room6_floora)
	(itematlocation item25_potted_plant_largeitem location_xpos53_ypos9_place14_room9_floora)
	(itematlocation item26_potted_plant_largeitem location_xpos51_yneg24_place18_room1_floora)
	(itematlocation item27_potted_plant_largeitem location_xpos53_yneg12_place19_room2_floorb)
	(itemclass item15_cup_smallitem cup)
	(itemclass item16_bottle_smallitem bottle)
	(itemclass item17_bottle_smallitem bottle)
	(itemclass item18_bottle_smallitem bottle)
	(itemclass item19_frisbee_mediumitem frisbee)
	(itemclass item25_potted_plant_largeitem pottedplant)
	(itemclass item26_potted_plant_largeitem pottedplant)
	(itemclass item27_potted_plant_largeitem pottedplant)
	(largeitem item25_potted_plant_largeitem)
	(largeitem item26_potted_plant_largeitem)
	(largeitem item27_potted_plant_largeitem)
	(locationinplace location_xneg1_yneg20_place2_room8_floorb place2_door_room8_empty_room)
	(locationinplace location_xneg1_yneg24_place7_room5_floora place7_door_room5_empty_room)
	(locationinplace location_xpos12_yneg9_place24_room5_floora place24_receptacle13_refrigerator)
	(locationinplace location_xpos16_ypos14_place6_room7_floorb place6_door_room7_empty_room)
	(locationinplace location_xpos23_ypos1_place8_room6_floora place8_door_room6_empty_room)
	(locationinplace location_xpos2_yneg7_place11_room6_floora place11_item19_frisbee)
	(locationinplace location_xpos32_yneg29_place9_room10_floora place9_door_room10_staircase)
	(locationinplace location_xpos35_ypos12_place15_room9_floora place15_receptacle2_oven)
	(locationinplace location_xpos36_yneg21_place10_room4_floorb place10_door_room4_corridor)
	(locationinplace location_xpos36_ypos26_place22_room9_floora place22_receptacle11_refrigerator)
	(locationinplace location_xpos37_ypos3_place21_room7_floorb place21_receptacle10_sink)
	(locationinplace location_xpos38_yneg36_place30_room10_floora place30_receptacle24_couch)
	(locationinplace location_xpos40_yneg36_place23_room1_floora place23_receptacle12_refrigerator)
	(locationinplace location_xpos42_ypos15_place28_room11_floorb place28_receptacle22_toilet)
	(locationinplace location_xpos43_ypos19_place0_room9_floora place0_door_room9_kitchen)
	(locationinplace location_xpos44_ypos12_place16_room11_floorb place16_receptacle3_oven)
	(locationinplace location_xpos47_yneg31_place4_room1_floora place4_door_room1_bathroom)
	(locationinplace location_xpos47_yneg3_place5_room2_floorb place5_door_room2_bathroom)
	(locationinplace location_xpos47_ypos15_place1_room11_floorb place1_door_room11_utility_room)
	(locationinplace location_xpos47_ypos25_place3_room3_floorb place3_door_room3_closet)
	(locationinplace location_xpos47_ypos6_place20_room2_floorb place20_receptacle9_sink)
	(locationinplace location_xpos49_ypos10_place14_room9_floora place14_receptacle1_oven)
	(locationinplace location_xpos50_ypos14_place29_room11_floorb place29_receptacle23_toilet)
	(locationinplace location_xpos51_yneg24_place18_room1_floora place18_receptacle7_sink)
	(locationinplace location_xpos51_yneg36_place26_room1_floora place26_receptacle20_toilet)
	(locationinplace location_xpos51_yneg5_place27_room2_floorb place27_receptacle21_toilet)
	(locationinplace location_xpos52_yneg10_place19_room2_floorb place19_receptacle8_sink)
	(locationinplace location_xpos52_yneg28_place18_room1_floora place18_receptacle7_sink)
	(locationinplace location_xpos52_ypos17_place17_room9_floora place17_receptacle6_sink)
	(locationinplace location_xpos53_yneg12_place19_room2_floorb place19_receptacle8_sink)
	(locationinplace location_xpos53_yneg25_place18_room1_floora place18_receptacle7_sink)
	(locationinplace location_xpos53_yneg8_place19_room2_floorb place19_receptacle8_sink)
	(locationinplace location_xpos53_ypos9_place14_room9_floora place14_receptacle1_oven)
	(locationinplace location_xpos54_yneg3_place27_room2_floorb place27_receptacle21_toilet)
	(locationinplace location_xpos5_yneg39_place25_room5_floora place25_receptacle14_refrigerator)
	(mediumitem item19_frisbee_mediumitem)
	(placeinroom place0_door_room9_kitchen room9_kitchen)
	(placeinroom place10_door_room4_corridor room4_corridor)
	(placeinroom place11_item19_frisbee room6_empty_room)
	(placeinroom place14_receptacle1_oven room9_kitchen)
	(placeinroom place15_receptacle2_oven room9_kitchen)
	(placeinroom place16_receptacle3_oven room11_utility_room)
	(placeinroom place17_receptacle6_sink room9_kitchen)
	(placeinroom place18_receptacle7_sink room1_bathroom)
	(placeinroom place19_receptacle8_sink room2_bathroom)
	(placeinroom place1_door_room11_utility_room room11_utility_room)
	(placeinroom place20_receptacle9_sink room2_bathroom)
	(placeinroom place21_receptacle10_sink room7_empty_room)
	(placeinroom place22_receptacle11_refrigerator room9_kitchen)
	(placeinroom place23_receptacle12_refrigerator room1_bathroom)
	(placeinroom place24_receptacle13_refrigerator room5_empty_room)
	(placeinroom place25_receptacle14_refrigerator room5_empty_room)
	(placeinroom place26_receptacle20_toilet room1_bathroom)
	(placeinroom place27_receptacle21_toilet room2_bathroom)
	(placeinroom place28_receptacle22_toilet room11_utility_room)
	(placeinroom place29_receptacle23_toilet room11_utility_room)
	(placeinroom place2_door_room8_empty_room room8_empty_room)
	(placeinroom place30_receptacle24_couch room10_staircase)
	(placeinroom place3_door_room3_closet room3_closet)
	(placeinroom place4_door_room1_bathroom room1_bathroom)
	(placeinroom place5_door_room2_bathroom room2_bathroom)
	(placeinroom place6_door_room7_empty_room room7_empty_room)
	(placeinroom place7_door_room5_empty_room room5_empty_room)
	(placeinroom place8_door_room6_empty_room room6_empty_room)
	(placeinroom place9_door_room10_staircase room10_staircase)
	(placelocation location_xneg1_yneg20_place2_room8_floorb place2_door_room8_empty_room)
	(placelocation location_xneg1_yneg24_place7_room5_floora place7_door_room5_empty_room)
	(placelocation location_xpos12_yneg9_place24_room5_floora place24_receptacle13_refrigerator)
	(placelocation location_xpos16_ypos14_place6_room7_floorb place6_door_room7_empty_room)
	(placelocation location_xpos23_ypos1_place8_room6_floora place8_door_room6_empty_room)
	(placelocation location_xpos2_yneg7_place11_room6_floora place11_item19_frisbee)
	(placelocation location_xpos32_yneg29_place9_room10_floora place9_door_room10_staircase)
	(placelocation location_xpos35_ypos12_place15_room9_floora place15_receptacle2_oven)
	(placelocation location_xpos36_yneg21_place10_room4_floorb place10_door_room4_corridor)
	(placelocation location_xpos36_ypos26_place22_room9_floora place22_receptacle11_refrigerator)
	(placelocation location_xpos37_ypos3_place21_room7_floorb place21_receptacle10_sink)
	(placelocation location_xpos38_yneg36_place30_room10_floora place30_receptacle24_couch)
	(placelocation location_xpos40_yneg36_place23_room1_floora place23_receptacle12_refrigerator)
	(placelocation location_xpos42_ypos15_place28_room11_floorb place28_receptacle22_toilet)
	(placelocation location_xpos43_ypos19_place0_room9_floora place0_door_room9_kitchen)
	(placelocation location_xpos44_ypos12_place16_room11_floorb place16_receptacle3_oven)
	(placelocation location_xpos47_yneg31_place4_room1_floora place4_door_room1_bathroom)
	(placelocation location_xpos47_yneg3_place5_room2_floorb place5_door_room2_bathroom)
	(placelocation location_xpos47_ypos15_place1_room11_floorb place1_door_room11_utility_room)
	(placelocation location_xpos47_ypos25_place3_room3_floorb place3_door_room3_closet)
	(placelocation location_xpos47_ypos6_place20_room2_floorb place20_receptacle9_sink)
	(placelocation location_xpos49_ypos10_place14_room9_floora place14_receptacle1_oven)
	(placelocation location_xpos50_ypos14_place29_room11_floorb place29_receptacle23_toilet)
	(placelocation location_xpos51_yneg36_place26_room1_floora place26_receptacle20_toilet)
	(placelocation location_xpos51_yneg5_place27_room2_floorb place27_receptacle21_toilet)
	(placelocation location_xpos52_yneg10_place19_room2_floorb place19_receptacle8_sink)
	(placelocation location_xpos52_yneg28_place18_room1_floora place18_receptacle7_sink)
	(placelocation location_xpos52_ypos17_place17_room9_floora place17_receptacle6_sink)
	(placelocation location_xpos5_yneg39_place25_room5_floora place25_receptacle14_refrigerator)
	(receptacleatlocation receptacle10_sink location_xpos37_ypos3_place21_room7_floorb)
	(receptacleatlocation receptacle11_refrigerator location_xpos36_ypos26_place22_room9_floora)
	(receptacleatlocation receptacle12_refrigerator location_xpos40_yneg36_place23_room1_floora)
	(receptacleatlocation receptacle13_refrigerator location_xpos12_yneg9_place24_room5_floora)
	(receptacleatlocation receptacle14_refrigerator location_xpos5_yneg39_place25_room5_floora)
	(receptacleatlocation receptacle1_oven location_xpos49_ypos10_place14_room9_floora)
	(receptacleatlocation receptacle20_toilet location_xpos51_yneg36_place26_room1_floora)
	(receptacleatlocation receptacle21_toilet location_xpos51_yneg5_place27_room2_floorb)
	(receptacleatlocation receptacle22_toilet location_xpos42_ypos15_place28_room11_floorb)
	(receptacleatlocation receptacle23_toilet location_xpos50_ypos14_place29_room11_floorb)
	(receptacleatlocation receptacle24_couch location_xpos38_yneg36_place30_room10_floora)
	(receptacleatlocation receptacle2_oven location_xpos35_ypos12_place15_room9_floora)
	(receptacleatlocation receptacle3_oven location_xpos44_ypos12_place16_room11_floorb)
	(receptacleatlocation receptacle6_sink location_xpos52_ypos17_place17_room9_floora)
	(receptacleatlocation receptacle7_sink location_xpos52_yneg28_place18_room1_floora)
	(receptacleatlocation receptacle8_sink location_xpos52_yneg10_place19_room2_floorb)
	(receptacleatlocation receptacle9_sink location_xpos47_ypos6_place20_room2_floorb)
	(receptacleclass receptacle10_sink sink)
	(receptacleclass receptacle11_refrigerator refrigerator)
	(receptacleclass receptacle12_refrigerator refrigerator)
	(receptacleclass receptacle13_refrigerator refrigerator)
	(receptacleclass receptacle14_refrigerator refrigerator)
	(receptacleclass receptacle1_oven oven)
	(receptacleclass receptacle20_toilet toilet)
	(receptacleclass receptacle21_toilet toilet)
	(receptacleclass receptacle22_toilet toilet)
	(receptacleclass receptacle23_toilet toilet)
	(receptacleclass receptacle24_couch couch)
	(receptacleclass receptacle2_oven oven)
	(receptacleclass receptacle3_oven oven)
	(receptacleclass receptacle6_sink sink)
	(receptacleclass receptacle7_sink sink)
	(receptacleclass receptacle8_sink sink)
	(receptacleclass receptacle9_sink sink)
	(receptacleopeningtype receptacle11_refrigerator)
	(receptacleopeningtype receptacle12_refrigerator)
	(receptacleopeningtype receptacle13_refrigerator)
	(receptacleopeningtype receptacle14_refrigerator)
	(receptacleopeningtype receptacle1_oven)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle3_oven)
	(roomplace place0_door_room9_kitchen room9_kitchen)
	(roomplace place10_door_room4_corridor room4_corridor)
	(roomplace place1_door_room11_utility_room room11_utility_room)
	(roomplace place2_door_room8_empty_room room8_empty_room)
	(roomplace place3_door_room3_closet room3_closet)
	(roomplace place4_door_room1_bathroom room1_bathroom)
	(roomplace place5_door_room2_bathroom room2_bathroom)
	(roomplace place6_door_room7_empty_room room7_empty_room)
	(roomplace place7_door_room5_empty_room room5_empty_room)
	(roomplace place8_door_room6_empty_room room6_empty_room)
	(roomplace place9_door_room10_staircase room10_staircase)
	(roomsconnected room10_staircase room1_bathroom)
	(roomsconnected room10_staircase room4_corridor)
	(roomsconnected room10_staircase room6_empty_room)
	(roomsconnected room11_utility_room room2_bathroom)
	(roomsconnected room11_utility_room room3_closet)
	(roomsconnected room11_utility_room room7_empty_room)
	(roomsconnected room1_bathroom room10_staircase)
	(roomsconnected room2_bathroom room11_utility_room)
	(roomsconnected room2_bathroom room4_corridor)
	(roomsconnected room3_closet room11_utility_room)
	(roomsconnected room4_corridor room10_staircase)
	(roomsconnected room4_corridor room2_bathroom)
	(roomsconnected room4_corridor room8_empty_room)
	(roomsconnected room5_empty_room room6_empty_room)
	(roomsconnected room6_empty_room room10_staircase)
	(roomsconnected room6_empty_room room5_empty_room)
	(roomsconnected room6_empty_room room9_kitchen)
	(roomsconnected room7_empty_room room11_utility_room)
	(roomsconnected room8_empty_room room4_corridor)
	(roomsconnected room9_kitchen room6_empty_room)
	(smallitem item15_cup_smallitem)
	(smallitem item16_bottle_smallitem)
	(smallitem item17_bottle_smallitem)
	(smallitem item18_bottle_smallitem)
  )
  (:goal (and
	(classrelation pottedplant couch)
	(classrelation frisbee oven)
	(classrelation frisbee toilet)
	(classrelation cup refrigerator)
	(classrelation bottle oven)))
)
