
(define (problem rockporttaskographyv3medium10bagslots5problem191) (:domain taskographyv3medium10bagslots5scrub)
  (:objects
        bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	item15_vase_mediumitem - item
	item16_vase_mediumitem - item
	item17_vase_mediumitem - item
	item20_book_smallitem - item
	item21_bowl_smallitem - item
	item22_bowl_smallitem - item
	item23_bowl_smallitem - item
	item44_potted_plant_largeitem - item
	item48_potted_plant_largeitem - item
	item50_potted_plant_largeitem - item
	location_xneg13_yneg3_place8_room2_floorb - location
	location_xneg13_ypos7_place4_room9_floora - location
	location_xneg14_yneg8_place34_room9_floora - location
	location_xneg14_ypos40_place6_room10_floorb - location
	location_xneg22_ypos61_place32_room10_floorb - location
	location_xneg26_ypos22_place27_room10_floorb - location
	location_xneg2_yneg9_place34_room9_floora - location
	location_xneg3_ypos27_place33_room10_floorb - location
	location_xpos11_ypos21_place9_room3_floorb - location
	location_xpos15_ypos52_place5_room4_floorb - location
	location_xpos15_ypos60_place24_room4_floorb - location
	location_xpos16_ypos58_place38_room4_floorb - location
	location_xpos16_ypos59_place38_room4_floorb - location
	location_xpos16_ypos64_place25_room4_floorb - location
	location_xpos17_ypos59_place23_room4_floorb - location
	location_xpos1_ypos39_place33_room10_floorb - location
	location_xpos25_ypos6_place0_room12_floora - location
	location_xpos29_yneg4_place7_room7_floorb - location
	location_xpos30_ypos21_place3_room1_floorb - location
	location_xpos31_yneg8_place40_room7_floorb - location
	location_xpos32_yneg3_place29_room7_floorb - location
	location_xpos33_yneg5_place40_room7_floorb - location
	location_xpos33_ypos36_place11_room11_floora - location
	location_xpos36_yneg5_place31_room7_floorb - location
	location_xpos37_ypos61_place16_room8_floorb - location
	location_xpos37_ypos64_place16_room8_floorb - location
	location_xpos39_ypos15_place20_room1_floorb - location
	location_xpos39_ypos49_place2_room6_floora - location
	location_xpos40_ypos48_place1_room8_floorb - location
	location_xpos41_ypos45_place15_room8_floorb - location
	location_xpos42_ypos13_place20_room1_floorb - location
	location_xpos45_ypos43_place15_room8_floorb - location
	location_xpos46_ypos43_place15_room8_floorb - location
	location_xpos4_ypos48_place10_room5_floora - location
	location_xpos53_ypos59_place19_room8_floorb - location
	location_xpos56_ypos54_place19_room8_floorb - location
	place0_door_room12_utility_room - place
	place10_door_room5_empty_room - place
	place11_door_room11_staircase - place
	place15_receptacle4_oven - place
	place16_receptacle5_oven - place
	place19_receptacle10_sink - place
	place1_door_room8_kitchen - place
	place20_receptacle11_sink - place
	place23_receptacle27_chair - place
	place24_receptacle28_chair - place
	place25_receptacle29_chair - place
	place27_receptacle31_chair - place
	place29_receptacle33_chair - place
	place2_door_room6_empty_room - place
	place31_receptacle35_chair - place
	place32_receptacle36_couch - place
	place33_receptacle37_couch - place
	place34_receptacle51_bed - place
	place38_receptacle55_dining_table - place
	place3_door_room1_bathroom - place
	place40_receptacle57_dining_table - place
	place4_door_room9_living_room - place
	place5_door_room4_dining_room - place
	place6_door_room10_living_room - place
	place7_door_room7_home_office - place
	place8_door_room2_bedroom - place
	place9_door_room3_corridor - place
	receptacle10_sink - receptacle
	receptacle11_sink - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle31_chair - receptacle
	receptacle33_chair - receptacle
	receptacle35_chair - receptacle
	receptacle36_couch - receptacle
	receptacle37_couch - receptacle
	receptacle4_oven - receptacle
	receptacle51_bed - receptacle
	receptacle55_dining_table - receptacle
	receptacle57_dining_table - receptacle
	receptacle5_oven - receptacle
	robot - agent
	room10_living_room - room
	room11_staircase - room
	room12_utility_room - room
	room1_bathroom - room
	room2_bedroom - room
	room3_corridor - room
	room4_dining_room - room
	room5_empty_room - room
	room6_empty_room - room
	room7_home_office - room
	room8_kitchen - room
	room9_living_room - room
  )
  (:init 
	(atlocation robot location_xpos15_ypos52_place5_room4_floorb)
	(inanyreceptacle item15_vase_mediumitem)
	(inanyreceptacle item16_vase_mediumitem)
	(inanyreceptacle item17_vase_mediumitem)
	(inanyreceptacle item20_book_smallitem)
	(inanyreceptacle item21_bowl_smallitem)
	(inanyreceptacle item22_bowl_smallitem)
	(inanyreceptacle item23_bowl_smallitem)
	(inanyreceptacle item44_potted_plant_largeitem)
	(inanyreceptacle item48_potted_plant_largeitem)
	(inanyreceptacle item50_potted_plant_largeitem)
	(inplace robot place5_door_room4_dining_room)
	(inreceptacle item15_vase_mediumitem receptacle51_bed)
	(inreceptacle item16_vase_mediumitem receptacle51_bed)
	(inreceptacle item17_vase_mediumitem receptacle55_dining_table)
	(inreceptacle item20_book_smallitem receptacle37_couch)
	(inreceptacle item21_bowl_smallitem receptacle4_oven)
	(inreceptacle item22_bowl_smallitem receptacle10_sink)
	(inreceptacle item23_bowl_smallitem receptacle4_oven)
	(inreceptacle item44_potted_plant_largeitem receptacle5_oven)
	(inreceptacle item48_potted_plant_largeitem receptacle57_dining_table)
	(inreceptacle item50_potted_plant_largeitem receptacle11_sink)
	(inroom robot room4_dining_room)
	(itematlocation item15_vase_mediumitem location_xneg2_yneg9_place34_room9_floora)
	(itematlocation item16_vase_mediumitem location_xneg2_yneg9_place34_room9_floora)
	(itematlocation item17_vase_mediumitem location_xpos16_ypos59_place38_room4_floorb)
	(itematlocation item20_book_smallitem location_xpos1_ypos39_place33_room10_floorb)
	(itematlocation item21_bowl_smallitem location_xpos45_ypos43_place15_room8_floorb)
	(itematlocation item22_bowl_smallitem location_xpos56_ypos54_place19_room8_floorb)
	(itematlocation item23_bowl_smallitem location_xpos46_ypos43_place15_room8_floorb)
	(itematlocation item44_potted_plant_largeitem location_xpos37_ypos64_place16_room8_floorb)
	(itematlocation item48_potted_plant_largeitem location_xpos31_yneg8_place40_room7_floorb)
	(itematlocation item50_potted_plant_largeitem location_xpos42_ypos13_place20_room1_floorb)
	(largeitem item44_potted_plant_largeitem)
	(largeitem item48_potted_plant_largeitem)
	(largeitem item50_potted_plant_largeitem)
	(locationinplace location_xneg13_yneg3_place8_room2_floorb place8_door_room2_bedroom)
	(locationinplace location_xneg13_ypos7_place4_room9_floora place4_door_room9_living_room)
	(locationinplace location_xneg14_yneg8_place34_room9_floora place34_receptacle51_bed)
	(locationinplace location_xneg14_ypos40_place6_room10_floorb place6_door_room10_living_room)
	(locationinplace location_xneg22_ypos61_place32_room10_floorb place32_receptacle36_couch)
	(locationinplace location_xneg26_ypos22_place27_room10_floorb place27_receptacle31_chair)
	(locationinplace location_xneg2_yneg9_place34_room9_floora place34_receptacle51_bed)
	(locationinplace location_xneg3_ypos27_place33_room10_floorb place33_receptacle37_couch)
	(locationinplace location_xpos11_ypos21_place9_room3_floorb place9_door_room3_corridor)
	(locationinplace location_xpos15_ypos52_place5_room4_floorb place5_door_room4_dining_room)
	(locationinplace location_xpos15_ypos60_place24_room4_floorb place24_receptacle28_chair)
	(locationinplace location_xpos16_ypos58_place38_room4_floorb place38_receptacle55_dining_table)
	(locationinplace location_xpos16_ypos59_place38_room4_floorb place38_receptacle55_dining_table)
	(locationinplace location_xpos16_ypos64_place25_room4_floorb place25_receptacle29_chair)
	(locationinplace location_xpos17_ypos59_place23_room4_floorb place23_receptacle27_chair)
	(locationinplace location_xpos1_ypos39_place33_room10_floorb place33_receptacle37_couch)
	(locationinplace location_xpos25_ypos6_place0_room12_floora place0_door_room12_utility_room)
	(locationinplace location_xpos29_yneg4_place7_room7_floorb place7_door_room7_home_office)
	(locationinplace location_xpos30_ypos21_place3_room1_floorb place3_door_room1_bathroom)
	(locationinplace location_xpos31_yneg8_place40_room7_floorb place40_receptacle57_dining_table)
	(locationinplace location_xpos32_yneg3_place29_room7_floorb place29_receptacle33_chair)
	(locationinplace location_xpos33_yneg5_place40_room7_floorb place40_receptacle57_dining_table)
	(locationinplace location_xpos33_ypos36_place11_room11_floora place11_door_room11_staircase)
	(locationinplace location_xpos36_yneg5_place31_room7_floorb place31_receptacle35_chair)
	(locationinplace location_xpos37_ypos61_place16_room8_floorb place16_receptacle5_oven)
	(locationinplace location_xpos37_ypos64_place16_room8_floorb place16_receptacle5_oven)
	(locationinplace location_xpos39_ypos15_place20_room1_floorb place20_receptacle11_sink)
	(locationinplace location_xpos39_ypos49_place2_room6_floora place2_door_room6_empty_room)
	(locationinplace location_xpos40_ypos48_place1_room8_floorb place1_door_room8_kitchen)
	(locationinplace location_xpos41_ypos45_place15_room8_floorb place15_receptacle4_oven)
	(locationinplace location_xpos42_ypos13_place20_room1_floorb place20_receptacle11_sink)
	(locationinplace location_xpos45_ypos43_place15_room8_floorb place15_receptacle4_oven)
	(locationinplace location_xpos46_ypos43_place15_room8_floorb place15_receptacle4_oven)
	(locationinplace location_xpos4_ypos48_place10_room5_floora place10_door_room5_empty_room)
	(locationinplace location_xpos53_ypos59_place19_room8_floorb place19_receptacle10_sink)
	(locationinplace location_xpos56_ypos54_place19_room8_floorb place19_receptacle10_sink)
	(mediumitem item15_vase_mediumitem)
	(mediumitem item16_vase_mediumitem)
	(mediumitem item17_vase_mediumitem)
	(placeinroom place0_door_room12_utility_room room12_utility_room)
	(placeinroom place10_door_room5_empty_room room5_empty_room)
	(placeinroom place11_door_room11_staircase room11_staircase)
	(placeinroom place15_receptacle4_oven room8_kitchen)
	(placeinroom place16_receptacle5_oven room8_kitchen)
	(placeinroom place19_receptacle10_sink room8_kitchen)
	(placeinroom place1_door_room8_kitchen room8_kitchen)
	(placeinroom place20_receptacle11_sink room1_bathroom)
	(placeinroom place23_receptacle27_chair room4_dining_room)
	(placeinroom place24_receptacle28_chair room4_dining_room)
	(placeinroom place25_receptacle29_chair room4_dining_room)
	(placeinroom place27_receptacle31_chair room10_living_room)
	(placeinroom place29_receptacle33_chair room7_home_office)
	(placeinroom place2_door_room6_empty_room room6_empty_room)
	(placeinroom place31_receptacle35_chair room7_home_office)
	(placeinroom place32_receptacle36_couch room10_living_room)
	(placeinroom place33_receptacle37_couch room10_living_room)
	(placeinroom place34_receptacle51_bed room9_living_room)
	(placeinroom place38_receptacle55_dining_table room4_dining_room)
	(placeinroom place3_door_room1_bathroom room1_bathroom)
	(placeinroom place40_receptacle57_dining_table room7_home_office)
	(placeinroom place4_door_room9_living_room room9_living_room)
	(placeinroom place5_door_room4_dining_room room4_dining_room)
	(placeinroom place6_door_room10_living_room room10_living_room)
	(placeinroom place7_door_room7_home_office room7_home_office)
	(placeinroom place8_door_room2_bedroom room2_bedroom)
	(placeinroom place9_door_room3_corridor room3_corridor)
	(placelocation location_xneg13_yneg3_place8_room2_floorb place8_door_room2_bedroom)
	(placelocation location_xneg13_ypos7_place4_room9_floora place4_door_room9_living_room)
	(placelocation location_xneg14_yneg8_place34_room9_floora place34_receptacle51_bed)
	(placelocation location_xneg14_ypos40_place6_room10_floorb place6_door_room10_living_room)
	(placelocation location_xneg22_ypos61_place32_room10_floorb place32_receptacle36_couch)
	(placelocation location_xneg26_ypos22_place27_room10_floorb place27_receptacle31_chair)
	(placelocation location_xneg3_ypos27_place33_room10_floorb place33_receptacle37_couch)
	(placelocation location_xpos11_ypos21_place9_room3_floorb place9_door_room3_corridor)
	(placelocation location_xpos15_ypos52_place5_room4_floorb place5_door_room4_dining_room)
	(placelocation location_xpos15_ypos60_place24_room4_floorb place24_receptacle28_chair)
	(placelocation location_xpos16_ypos58_place38_room4_floorb place38_receptacle55_dining_table)
	(placelocation location_xpos16_ypos64_place25_room4_floorb place25_receptacle29_chair)
	(placelocation location_xpos17_ypos59_place23_room4_floorb place23_receptacle27_chair)
	(placelocation location_xpos25_ypos6_place0_room12_floora place0_door_room12_utility_room)
	(placelocation location_xpos29_yneg4_place7_room7_floorb place7_door_room7_home_office)
	(placelocation location_xpos30_ypos21_place3_room1_floorb place3_door_room1_bathroom)
	(placelocation location_xpos32_yneg3_place29_room7_floorb place29_receptacle33_chair)
	(placelocation location_xpos33_yneg5_place40_room7_floorb place40_receptacle57_dining_table)
	(placelocation location_xpos33_ypos36_place11_room11_floora place11_door_room11_staircase)
	(placelocation location_xpos36_yneg5_place31_room7_floorb place31_receptacle35_chair)
	(placelocation location_xpos37_ypos61_place16_room8_floorb place16_receptacle5_oven)
	(placelocation location_xpos39_ypos15_place20_room1_floorb place20_receptacle11_sink)
	(placelocation location_xpos39_ypos49_place2_room6_floora place2_door_room6_empty_room)
	(placelocation location_xpos40_ypos48_place1_room8_floorb place1_door_room8_kitchen)
	(placelocation location_xpos41_ypos45_place15_room8_floorb place15_receptacle4_oven)
	(placelocation location_xpos4_ypos48_place10_room5_floora place10_door_room5_empty_room)
	(placelocation location_xpos53_ypos59_place19_room8_floorb place19_receptacle10_sink)
	(receptacleatlocation receptacle10_sink location_xpos53_ypos59_place19_room8_floorb)
	(receptacleatlocation receptacle11_sink location_xpos39_ypos15_place20_room1_floorb)
	(receptacleatlocation receptacle27_chair location_xpos17_ypos59_place23_room4_floorb)
	(receptacleatlocation receptacle28_chair location_xpos15_ypos60_place24_room4_floorb)
	(receptacleatlocation receptacle29_chair location_xpos16_ypos64_place25_room4_floorb)
	(receptacleatlocation receptacle31_chair location_xneg26_ypos22_place27_room10_floorb)
	(receptacleatlocation receptacle33_chair location_xpos32_yneg3_place29_room7_floorb)
	(receptacleatlocation receptacle35_chair location_xpos36_yneg5_place31_room7_floorb)
	(receptacleatlocation receptacle36_couch location_xneg22_ypos61_place32_room10_floorb)
	(receptacleatlocation receptacle37_couch location_xneg3_ypos27_place33_room10_floorb)
	(receptacleatlocation receptacle4_oven location_xpos41_ypos45_place15_room8_floorb)
	(receptacleatlocation receptacle51_bed location_xneg14_yneg8_place34_room9_floora)
	(receptacleatlocation receptacle55_dining_table location_xpos16_ypos58_place38_room4_floorb)
	(receptacleatlocation receptacle57_dining_table location_xpos33_yneg5_place40_room7_floorb)
	(receptacleatlocation receptacle5_oven location_xpos37_ypos61_place16_room8_floorb)
	(receptacleopeningtype receptacle4_oven)
	(receptacleopeningtype receptacle5_oven)
	(roomplace place0_door_room12_utility_room room12_utility_room)
	(roomplace place10_door_room5_empty_room room5_empty_room)
	(roomplace place11_door_room11_staircase room11_staircase)
	(roomplace place1_door_room8_kitchen room8_kitchen)
	(roomplace place2_door_room6_empty_room room6_empty_room)
	(roomplace place3_door_room1_bathroom room1_bathroom)
	(roomplace place4_door_room9_living_room room9_living_room)
	(roomplace place5_door_room4_dining_room room4_dining_room)
	(roomplace place6_door_room10_living_room room10_living_room)
	(roomplace place7_door_room7_home_office room7_home_office)
	(roomplace place8_door_room2_bedroom room2_bedroom)
	(roomplace place9_door_room3_corridor room3_corridor)
	(roomsconnected room10_living_room room3_corridor)
	(roomsconnected room11_staircase room12_utility_room)
	(roomsconnected room11_staircase room5_empty_room)
	(roomsconnected room11_staircase room6_empty_room)
	(roomsconnected room11_staircase room8_kitchen)
	(roomsconnected room12_utility_room room11_staircase)
	(roomsconnected room12_utility_room room9_living_room)
	(roomsconnected room1_bathroom room3_corridor)
	(roomsconnected room1_bathroom room7_home_office)
	(roomsconnected room1_bathroom room8_kitchen)
	(roomsconnected room2_bedroom room3_corridor)
	(roomsconnected room3_corridor room10_living_room)
	(roomsconnected room3_corridor room1_bathroom)
	(roomsconnected room3_corridor room2_bedroom)
	(roomsconnected room4_dining_room room8_kitchen)
	(roomsconnected room5_empty_room room11_staircase)
	(roomsconnected room6_empty_room room11_staircase)
	(roomsconnected room7_home_office room1_bathroom)
	(roomsconnected room8_kitchen room11_staircase)
	(roomsconnected room8_kitchen room1_bathroom)
	(roomsconnected room8_kitchen room4_dining_room)
	(roomsconnected room9_living_room room12_utility_room)
	(smallitem item20_book_smallitem)
	(smallitem item21_bowl_smallitem)
	(smallitem item22_bowl_smallitem)
	(smallitem item23_bowl_smallitem)
  )
  (:goal (and
	(inreceptacle item44_potted_plant_largeitem receptacle29_chair)
	(inreceptacle item15_vase_mediumitem receptacle57_dining_table)
	(inreceptacle item48_potted_plant_largeitem receptacle27_chair)
	(inreceptacle item16_vase_mediumitem receptacle35_chair)
	(inreceptacle item50_potted_plant_largeitem receptacle28_chair)
	(inreceptacle item21_bowl_smallitem receptacle33_chair)
	(inreceptacle item17_vase_mediumitem receptacle57_dining_table)
	(inreceptacle item23_bowl_smallitem receptacle36_couch)
	(inreceptacle item20_book_smallitem receptacle29_chair)
	(inreceptacle item22_bowl_smallitem receptacle31_chair)))
)
