
(define (problem anaheimtaskographyv2medium2problem74) (:domain taskographyv2medium2scrub)
  (:objects
        item46_laptop_mediumitem - item
	item5_bottle_smallitem - item
	location_xneg12_ypos3_place6_room13_floorb - location
	location_xneg21_ypos23_place4_room14_floorb - location
	location_xneg25_ypos9_place8_room6_floorc - location
	location_xneg50_ypos11_place5_room15_floorb - location
	location_xpos10_yneg7_place55_room8_floorb - location
	location_xpos1_yneg2_place14_room11_floorb - location
	location_xpos22_yneg8_place11_room7_floorb - location
	location_xpos22_ypos26_place0_room1_floora - location
	location_xpos23_yneg6_place9_room18_floora - location
	location_xpos23_ypos24_place1_room2_floorb - location
	location_xpos23_ypos8_place12_room9_floora - location
	location_xpos24_ypos10_place2_room3_floorc - location
	location_xpos27_ypos24_place43_room3_floorc - location
	location_xpos28_ypos19_place47_room1_floora - location
	location_xpos30_ypos20_place47_room1_floora - location
	location_xpos3_yneg7_place10_room8_floorb - location
	location_xpos3_ypos22_place17_room17_floorb - location
	location_xpos3_ypos24_place16_room16_floora - location
	location_xpos4_ypos2_place13_room10_floora - location
	location_xpos4_ypos5_place15_room12_floorc - location
	location_xpos51_ypos15_place7_room5_floorb - location
	location_xpos51_ypos16_place3_room4_floora - location
	location_xpos57_ypos7_place38_room4_floora - location
	location_xpos58_ypos5_place38_room4_floora - location
	place0_door_room1_bathroom - place
	place10_door_room8_closet - place
	place11_door_room7_closet - place
	place12_door_room9_corridor - place
	place13_door_room10_corridor - place
	place14_door_room11_corridor - place
	place15_door_room12_corridor - place
	place16_door_room16_staircase - place
	place17_door_room17_staircase - place
	place1_door_room2_bathroom - place
	place2_door_room3_bathroom - place
	place38_receptacle40_dining_table - place
	place3_door_room4_bedroom - place
	place43_receptacle45_toilet - place
	place47_receptacle50_sink - place
	place4_door_room14_kitchen - place
	place55_receptacle58_refrigerator - place
	place5_door_room15_living_room - place
	place6_door_room13_dining_room - place
	place7_door_room5_bedroom - place
	place8_door_room6_bedroom - place
	place9_door_room18_utility_room - place
	receptacle40_dining_table - receptacle
	receptacle45_toilet - receptacle
	receptacle50_sink - receptacle
	receptacle58_refrigerator - receptacle
	robot - agent
	room10_corridor - room
	room11_corridor - room
	room12_corridor - room
	room13_dining_room - room
	room14_kitchen - room
	room15_living_room - room
	room16_staircase - room
	room17_staircase - room
	room18_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_bedroom - room
	room7_closet - room
	room8_closet - room
	room9_corridor - room
  )
  (:init 
	(atlocation robot location_xpos22_yneg8_place11_room7_floorb)
	(inanyreceptacle item46_laptop_mediumitem)
	(inanyreceptacle item5_bottle_smallitem)
	(inplace robot place11_door_room7_closet)
	(inreceptacle item46_laptop_mediumitem receptacle40_dining_table)
	(inreceptacle item5_bottle_smallitem receptacle50_sink)
	(inroom robot room7_closet)
	(itematlocation item46_laptop_mediumitem location_xpos57_ypos7_place38_room4_floora)
	(itematlocation item5_bottle_smallitem location_xpos30_ypos20_place47_room1_floora)
	(locationinplace location_xneg12_ypos3_place6_room13_floorb place6_door_room13_dining_room)
	(locationinplace location_xneg21_ypos23_place4_room14_floorb place4_door_room14_kitchen)
	(locationinplace location_xneg25_ypos9_place8_room6_floorc place8_door_room6_bedroom)
	(locationinplace location_xneg50_ypos11_place5_room15_floorb place5_door_room15_living_room)
	(locationinplace location_xpos10_yneg7_place55_room8_floorb place55_receptacle58_refrigerator)
	(locationinplace location_xpos1_yneg2_place14_room11_floorb place14_door_room11_corridor)
	(locationinplace location_xpos22_yneg8_place11_room7_floorb place11_door_room7_closet)
	(locationinplace location_xpos22_ypos26_place0_room1_floora place0_door_room1_bathroom)
	(locationinplace location_xpos23_yneg6_place9_room18_floora place9_door_room18_utility_room)
	(locationinplace location_xpos23_ypos24_place1_room2_floorb place1_door_room2_bathroom)
	(locationinplace location_xpos23_ypos8_place12_room9_floora place12_door_room9_corridor)
	(locationinplace location_xpos24_ypos10_place2_room3_floorc place2_door_room3_bathroom)
	(locationinplace location_xpos27_ypos24_place43_room3_floorc place43_receptacle45_toilet)
	(locationinplace location_xpos28_ypos19_place47_room1_floora place47_receptacle50_sink)
	(locationinplace location_xpos30_ypos20_place47_room1_floora place47_receptacle50_sink)
	(locationinplace location_xpos3_yneg7_place10_room8_floorb place10_door_room8_closet)
	(locationinplace location_xpos3_ypos22_place17_room17_floorb place17_door_room17_staircase)
	(locationinplace location_xpos3_ypos24_place16_room16_floora place16_door_room16_staircase)
	(locationinplace location_xpos4_ypos2_place13_room10_floora place13_door_room10_corridor)
	(locationinplace location_xpos4_ypos5_place15_room12_floorc place15_door_room12_corridor)
	(locationinplace location_xpos51_ypos15_place7_room5_floorb place7_door_room5_bedroom)
	(locationinplace location_xpos51_ypos16_place3_room4_floora place3_door_room4_bedroom)
	(locationinplace location_xpos57_ypos7_place38_room4_floora place38_receptacle40_dining_table)
	(locationinplace location_xpos58_ypos5_place38_room4_floora place38_receptacle40_dining_table)
	(placeinroom place0_door_room1_bathroom room1_bathroom)
	(placeinroom place10_door_room8_closet room8_closet)
	(placeinroom place11_door_room7_closet room7_closet)
	(placeinroom place12_door_room9_corridor room9_corridor)
	(placeinroom place13_door_room10_corridor room10_corridor)
	(placeinroom place14_door_room11_corridor room11_corridor)
	(placeinroom place15_door_room12_corridor room12_corridor)
	(placeinroom place16_door_room16_staircase room16_staircase)
	(placeinroom place17_door_room17_staircase room17_staircase)
	(placeinroom place1_door_room2_bathroom room2_bathroom)
	(placeinroom place2_door_room3_bathroom room3_bathroom)
	(placeinroom place38_receptacle40_dining_table room4_bedroom)
	(placeinroom place3_door_room4_bedroom room4_bedroom)
	(placeinroom place43_receptacle45_toilet room3_bathroom)
	(placeinroom place47_receptacle50_sink room1_bathroom)
	(placeinroom place4_door_room14_kitchen room14_kitchen)
	(placeinroom place55_receptacle58_refrigerator room8_closet)
	(placeinroom place5_door_room15_living_room room15_living_room)
	(placeinroom place6_door_room13_dining_room room13_dining_room)
	(placeinroom place7_door_room5_bedroom room5_bedroom)
	(placeinroom place8_door_room6_bedroom room6_bedroom)
	(placeinroom place9_door_room18_utility_room room18_utility_room)
	(placelocation location_xneg12_ypos3_place6_room13_floorb place6_door_room13_dining_room)
	(placelocation location_xneg21_ypos23_place4_room14_floorb place4_door_room14_kitchen)
	(placelocation location_xneg25_ypos9_place8_room6_floorc place8_door_room6_bedroom)
	(placelocation location_xneg50_ypos11_place5_room15_floorb place5_door_room15_living_room)
	(placelocation location_xpos10_yneg7_place55_room8_floorb place55_receptacle58_refrigerator)
	(placelocation location_xpos1_yneg2_place14_room11_floorb place14_door_room11_corridor)
	(placelocation location_xpos22_yneg8_place11_room7_floorb place11_door_room7_closet)
	(placelocation location_xpos22_ypos26_place0_room1_floora place0_door_room1_bathroom)
	(placelocation location_xpos23_yneg6_place9_room18_floora place9_door_room18_utility_room)
	(placelocation location_xpos23_ypos24_place1_room2_floorb place1_door_room2_bathroom)
	(placelocation location_xpos23_ypos8_place12_room9_floora place12_door_room9_corridor)
	(placelocation location_xpos24_ypos10_place2_room3_floorc place2_door_room3_bathroom)
	(placelocation location_xpos27_ypos24_place43_room3_floorc place43_receptacle45_toilet)
	(placelocation location_xpos28_ypos19_place47_room1_floora place47_receptacle50_sink)
	(placelocation location_xpos3_yneg7_place10_room8_floorb place10_door_room8_closet)
	(placelocation location_xpos3_ypos22_place17_room17_floorb place17_door_room17_staircase)
	(placelocation location_xpos3_ypos24_place16_room16_floora place16_door_room16_staircase)
	(placelocation location_xpos4_ypos2_place13_room10_floora place13_door_room10_corridor)
	(placelocation location_xpos4_ypos5_place15_room12_floorc place15_door_room12_corridor)
	(placelocation location_xpos51_ypos15_place7_room5_floorb place7_door_room5_bedroom)
	(placelocation location_xpos51_ypos16_place3_room4_floora place3_door_room4_bedroom)
	(placelocation location_xpos58_ypos5_place38_room4_floora place38_receptacle40_dining_table)
	(receptacleatlocation receptacle40_dining_table location_xpos58_ypos5_place38_room4_floora)
	(receptacleatlocation receptacle45_toilet location_xpos27_ypos24_place43_room3_floorc)
	(receptacleatlocation receptacle50_sink location_xpos28_ypos19_place47_room1_floora)
	(receptacleatlocation receptacle58_refrigerator location_xpos10_yneg7_place55_room8_floorb)
	(receptacleopeningtype receptacle58_refrigerator)
	(roomplace place0_door_room1_bathroom room1_bathroom)
	(roomplace place10_door_room8_closet room8_closet)
	(roomplace place11_door_room7_closet room7_closet)
	(roomplace place12_door_room9_corridor room9_corridor)
	(roomplace place13_door_room10_corridor room10_corridor)
	(roomplace place14_door_room11_corridor room11_corridor)
	(roomplace place15_door_room12_corridor room12_corridor)
	(roomplace place16_door_room16_staircase room16_staircase)
	(roomplace place17_door_room17_staircase room17_staircase)
	(roomplace place1_door_room2_bathroom room2_bathroom)
	(roomplace place2_door_room3_bathroom room3_bathroom)
	(roomplace place3_door_room4_bedroom room4_bedroom)
	(roomplace place4_door_room14_kitchen room14_kitchen)
	(roomplace place5_door_room15_living_room room15_living_room)
	(roomplace place6_door_room13_dining_room room13_dining_room)
	(roomplace place7_door_room5_bedroom room5_bedroom)
	(roomplace place8_door_room6_bedroom room6_bedroom)
	(roomplace place9_door_room18_utility_room room18_utility_room)
	(roomsconnected room10_corridor room18_utility_room)
	(roomsconnected room11_corridor room13_dining_room)
	(roomsconnected room11_corridor room17_staircase)
	(roomsconnected room11_corridor room7_closet)
	(roomsconnected room11_corridor room8_closet)
	(roomsconnected room12_corridor room3_bathroom)
	(roomsconnected room12_corridor room6_bedroom)
	(roomsconnected room12_corridor room8_closet)
	(roomsconnected room13_dining_room room11_corridor)
	(roomsconnected room13_dining_room room14_kitchen)
	(roomsconnected room14_kitchen room13_dining_room)
	(roomsconnected room14_kitchen room15_living_room)
	(roomsconnected room15_living_room room14_kitchen)
	(roomsconnected room16_staircase room1_bathroom)
	(roomsconnected room16_staircase room2_bathroom)
	(roomsconnected room17_staircase room11_corridor)
	(roomsconnected room17_staircase room2_bathroom)
	(roomsconnected room18_utility_room room10_corridor)
	(roomsconnected room18_utility_room room9_corridor)
	(roomsconnected room1_bathroom room16_staircase)
	(roomsconnected room1_bathroom room9_corridor)
	(roomsconnected room2_bathroom room16_staircase)
	(roomsconnected room2_bathroom room17_staircase)
	(roomsconnected room2_bathroom room5_bedroom)
	(roomsconnected room3_bathroom room12_corridor)
	(roomsconnected room4_bedroom room9_corridor)
	(roomsconnected room5_bedroom room2_bathroom)
	(roomsconnected room6_bedroom room12_corridor)
	(roomsconnected room7_closet room11_corridor)
	(roomsconnected room8_closet room11_corridor)
	(roomsconnected room8_closet room12_corridor)
	(roomsconnected room9_corridor room18_utility_room)
	(roomsconnected room9_corridor room1_bathroom)
	(roomsconnected room9_corridor room4_bedroom)
  )
  (:goal (and
	(inreceptacle item5_bottle_smallitem receptacle45_toilet)
	(inreceptacle item46_laptop_mediumitem receptacle58_refrigerator)))
)
