
(define (problem rockporttaskographyv2medium2problem190) (:domain taskographyv2medium2scrub)
  (:objects
        item13_bottle_smallitem - item
	item19_vase_mediumitem - item
	location_xneg13_yneg3_place8_room2_floorb - location
	location_xneg13_ypos7_place4_room9_floora - location
	location_xneg14_ypos40_place6_room10_floorb - location
	location_xpos11_ypos21_place9_room3_floorb - location
	location_xpos15_ypos52_place5_room4_floorb - location
	location_xpos16_ypos58_place38_room4_floorb - location
	location_xpos25_ypos6_place0_room12_floora - location
	location_xpos29_yneg4_place7_room7_floorb - location
	location_xpos30_ypos21_place3_room1_floorb - location
	location_xpos33_ypos36_place11_room11_floora - location
	location_xpos36_ypos42_place15_room8_floorb - location
	location_xpos39_ypos15_place20_room1_floorb - location
	location_xpos39_ypos49_place2_room6_floora - location
	location_xpos40_ypos13_place20_room1_floorb - location
	location_xpos40_ypos48_place1_room8_floorb - location
	location_xpos41_ypos45_place15_room8_floorb - location
	location_xpos4_ypos48_place10_room5_floora - location
	place0_door_room12_utility_room - place
	place10_door_room5_empty_room - place
	place11_door_room11_staircase - place
	place15_receptacle4_oven - place
	place1_door_room8_kitchen - place
	place20_receptacle11_sink - place
	place2_door_room6_empty_room - place
	place38_receptacle55_dining_table - place
	place3_door_room1_bathroom - place
	place4_door_room9_living_room - place
	place5_door_room4_dining_room - place
	place6_door_room10_living_room - place
	place7_door_room7_home_office - place
	place8_door_room2_bedroom - place
	place9_door_room3_corridor - place
	receptacle11_sink - receptacle
	receptacle4_oven - receptacle
	receptacle55_dining_table - receptacle
	robot - agent
	room10_living_room - room
	room11_staircase - room
	room12_utility_room - room
	room1_bathroom - room
	room2_bedroom - room
	room3_corridor - room
	room4_dining_room - room
	room5_empty_room - room
	room6_empty_room - room
	room7_home_office - room
	room8_kitchen - room
	room9_living_room - room
  )
  (:init 
	(atlocation robot location_xneg14_ypos40_place6_room10_floorb)
	(inanyreceptacle item13_bottle_smallitem)
	(inanyreceptacle item19_vase_mediumitem)
	(inplace robot place6_door_room10_living_room)
	(inreceptacle item13_bottle_smallitem receptacle4_oven)
	(inreceptacle item19_vase_mediumitem receptacle11_sink)
	(inroom robot room10_living_room)
	(itematlocation item13_bottle_smallitem location_xpos36_ypos42_place15_room8_floorb)
	(itematlocation item19_vase_mediumitem location_xpos40_ypos13_place20_room1_floorb)
	(locationinplace location_xneg13_yneg3_place8_room2_floorb place8_door_room2_bedroom)
	(locationinplace location_xneg13_ypos7_place4_room9_floora place4_door_room9_living_room)
	(locationinplace location_xneg14_ypos40_place6_room10_floorb place6_door_room10_living_room)
	(locationinplace location_xpos11_ypos21_place9_room3_floorb place9_door_room3_corridor)
	(locationinplace location_xpos15_ypos52_place5_room4_floorb place5_door_room4_dining_room)
	(locationinplace location_xpos16_ypos58_place38_room4_floorb place38_receptacle55_dining_table)
	(locationinplace location_xpos25_ypos6_place0_room12_floora place0_door_room12_utility_room)
	(locationinplace location_xpos29_yneg4_place7_room7_floorb place7_door_room7_home_office)
	(locationinplace location_xpos30_ypos21_place3_room1_floorb place3_door_room1_bathroom)
	(locationinplace location_xpos33_ypos36_place11_room11_floora place11_door_room11_staircase)
	(locationinplace location_xpos36_ypos42_place15_room8_floorb place15_receptacle4_oven)
	(locationinplace location_xpos39_ypos15_place20_room1_floorb place20_receptacle11_sink)
	(locationinplace location_xpos39_ypos49_place2_room6_floora place2_door_room6_empty_room)
	(locationinplace location_xpos40_ypos13_place20_room1_floorb place20_receptacle11_sink)
	(locationinplace location_xpos40_ypos48_place1_room8_floorb place1_door_room8_kitchen)
	(locationinplace location_xpos41_ypos45_place15_room8_floorb place15_receptacle4_oven)
	(locationinplace location_xpos4_ypos48_place10_room5_floora place10_door_room5_empty_room)
	(placeinroom place0_door_room12_utility_room room12_utility_room)
	(placeinroom place10_door_room5_empty_room room5_empty_room)
	(placeinroom place11_door_room11_staircase room11_staircase)
	(placeinroom place15_receptacle4_oven room8_kitchen)
	(placeinroom place1_door_room8_kitchen room8_kitchen)
	(placeinroom place20_receptacle11_sink room1_bathroom)
	(placeinroom place2_door_room6_empty_room room6_empty_room)
	(placeinroom place38_receptacle55_dining_table room4_dining_room)
	(placeinroom place3_door_room1_bathroom room1_bathroom)
	(placeinroom place4_door_room9_living_room room9_living_room)
	(placeinroom place5_door_room4_dining_room room4_dining_room)
	(placeinroom place6_door_room10_living_room room10_living_room)
	(placeinroom place7_door_room7_home_office room7_home_office)
	(placeinroom place8_door_room2_bedroom room2_bedroom)
	(placeinroom place9_door_room3_corridor room3_corridor)
	(placelocation location_xneg13_yneg3_place8_room2_floorb place8_door_room2_bedroom)
	(placelocation location_xneg13_ypos7_place4_room9_floora place4_door_room9_living_room)
	(placelocation location_xneg14_ypos40_place6_room10_floorb place6_door_room10_living_room)
	(placelocation location_xpos11_ypos21_place9_room3_floorb place9_door_room3_corridor)
	(placelocation location_xpos15_ypos52_place5_room4_floorb place5_door_room4_dining_room)
	(placelocation location_xpos16_ypos58_place38_room4_floorb place38_receptacle55_dining_table)
	(placelocation location_xpos25_ypos6_place0_room12_floora place0_door_room12_utility_room)
	(placelocation location_xpos29_yneg4_place7_room7_floorb place7_door_room7_home_office)
	(placelocation location_xpos30_ypos21_place3_room1_floorb place3_door_room1_bathroom)
	(placelocation location_xpos33_ypos36_place11_room11_floora place11_door_room11_staircase)
	(placelocation location_xpos39_ypos15_place20_room1_floorb place20_receptacle11_sink)
	(placelocation location_xpos39_ypos49_place2_room6_floora place2_door_room6_empty_room)
	(placelocation location_xpos40_ypos48_place1_room8_floorb place1_door_room8_kitchen)
	(placelocation location_xpos41_ypos45_place15_room8_floorb place15_receptacle4_oven)
	(placelocation location_xpos4_ypos48_place10_room5_floora place10_door_room5_empty_room)
	(receptacleatlocation receptacle11_sink location_xpos39_ypos15_place20_room1_floorb)
	(receptacleatlocation receptacle4_oven location_xpos41_ypos45_place15_room8_floorb)
	(receptacleatlocation receptacle55_dining_table location_xpos16_ypos58_place38_room4_floorb)
	(receptacleopeningtype receptacle4_oven)
	(roomplace place0_door_room12_utility_room room12_utility_room)
	(roomplace place10_door_room5_empty_room room5_empty_room)
	(roomplace place11_door_room11_staircase room11_staircase)
	(roomplace place1_door_room8_kitchen room8_kitchen)
	(roomplace place2_door_room6_empty_room room6_empty_room)
	(roomplace place3_door_room1_bathroom room1_bathroom)
	(roomplace place4_door_room9_living_room room9_living_room)
	(roomplace place5_door_room4_dining_room room4_dining_room)
	(roomplace place6_door_room10_living_room room10_living_room)
	(roomplace place7_door_room7_home_office room7_home_office)
	(roomplace place8_door_room2_bedroom room2_bedroom)
	(roomplace place9_door_room3_corridor room3_corridor)
	(roomsconnected room10_living_room room3_corridor)
	(roomsconnected room11_staircase room12_utility_room)
	(roomsconnected room11_staircase room5_empty_room)
	(roomsconnected room11_staircase room6_empty_room)
	(roomsconnected room11_staircase room8_kitchen)
	(roomsconnected room12_utility_room room11_staircase)
	(roomsconnected room12_utility_room room9_living_room)
	(roomsconnected room1_bathroom room3_corridor)
	(roomsconnected room1_bathroom room7_home_office)
	(roomsconnected room1_bathroom room8_kitchen)
	(roomsconnected room2_bedroom room3_corridor)
	(roomsconnected room3_corridor room10_living_room)
	(roomsconnected room3_corridor room1_bathroom)
	(roomsconnected room3_corridor room2_bedroom)
	(roomsconnected room4_dining_room room8_kitchen)
	(roomsconnected room5_empty_room room11_staircase)
	(roomsconnected room6_empty_room room11_staircase)
	(roomsconnected room7_home_office room1_bathroom)
	(roomsconnected room8_kitchen room11_staircase)
	(roomsconnected room8_kitchen room1_bathroom)
	(roomsconnected room8_kitchen room4_dining_room)
	(roomsconnected room9_living_room room12_utility_room)
  )
  (:goal (and
	(inreceptacle item13_bottle_smallitem receptacle55_dining_table)
	(inreceptacle item19_vase_mediumitem receptacle4_oven)))
)
