
(define (problem heltontaskographyv2medium2problem166) (:domain taskographyv2medium2scrub)
  (:objects
        item33_potted_plant_largeitem - item
	item70_clock_mediumitem - item
	location_xneg13_ypos64_place4_room7_floora - location
	location_xneg18_ypos33_place16_room12_floora - location
	location_xneg29_ypos37_place0_room12_floora - location
	location_xneg33_yneg27_place2_room3_floorb - location
	location_xneg37_ypos5_place12_room6_floorb - location
	location_xneg38_yneg13_place10_room1_floora - location
	location_xneg38_yneg30_place11_room14_floora - location
	location_xneg39_ypos18_place13_room11_floora - location
	location_xneg3_ypos32_place3_room8_floora - location
	location_xneg41_yneg35_place47_room14_floora - location
	location_xneg62_ypos54_place6_room9_floora - location
	location_xneg63_ypos15_place5_room5_floorb - location
	location_xneg65_yneg20_place7_room13_floorb - location
	location_xneg73_ypos26_place24_room5_floorb - location
	location_xneg8_yneg7_place8_room10_floora - location
	location_xneg8_ypos11_place9_room4_floorb - location
	location_xpos0_yneg25_place1_room2_floorb - location
	location_xpos11_yneg21_place46_room10_floora - location
	location_xpos5_yneg33_place46_room10_floora - location
	place0_door_room12_staircase - place
	place10_door_room1_bathroom - place
	place11_door_room14_utility_room - place
	place12_door_room6_corridor - place
	place13_door_room11_lobby - place
	place16_item33_potted_plant - place
	place1_door_room2_bathroom - place
	place24_receptacle15_chair - place
	place2_door_room3_bathroom - place
	place3_door_room8_kitchen - place
	place46_receptacle55_oven - place
	place47_receptacle56_oven - place
	place4_door_room7_dining_room - place
	place5_door_room5_bedroom - place
	place6_door_room9_living_room - place
	place7_door_room13_television_room - place
	place8_door_room10_living_room - place
	place9_door_room4_bedroom - place
	receptacle15_chair - receptacle
	receptacle55_oven - receptacle
	receptacle56_oven - receptacle
	robot - agent
	room10_living_room - room
	room11_lobby - room
	room12_staircase - room
	room13_television_room - room
	room14_utility_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_corridor - room
	room7_dining_room - room
	room8_kitchen - room
	room9_living_room - room
  )
  (:init 
	(atlocation robot location_xneg65_yneg20_place7_room13_floorb)
	(inanyreceptacle item70_clock_mediumitem)
	(inplace robot place7_door_room13_television_room)
	(inreceptacle item70_clock_mediumitem receptacle55_oven)
	(inroom robot room13_television_room)
	(itematlocation item33_potted_plant_largeitem location_xneg18_ypos33_place16_room12_floora)
	(itematlocation item70_clock_mediumitem location_xpos11_yneg21_place46_room10_floora)
	(locationinplace location_xneg13_ypos64_place4_room7_floora place4_door_room7_dining_room)
	(locationinplace location_xneg18_ypos33_place16_room12_floora place16_item33_potted_plant)
	(locationinplace location_xneg29_ypos37_place0_room12_floora place0_door_room12_staircase)
	(locationinplace location_xneg33_yneg27_place2_room3_floorb place2_door_room3_bathroom)
	(locationinplace location_xneg37_ypos5_place12_room6_floorb place12_door_room6_corridor)
	(locationinplace location_xneg38_yneg13_place10_room1_floora place10_door_room1_bathroom)
	(locationinplace location_xneg38_yneg30_place11_room14_floora place11_door_room14_utility_room)
	(locationinplace location_xneg39_ypos18_place13_room11_floora place13_door_room11_lobby)
	(locationinplace location_xneg3_ypos32_place3_room8_floora place3_door_room8_kitchen)
	(locationinplace location_xneg41_yneg35_place47_room14_floora place47_receptacle56_oven)
	(locationinplace location_xneg62_ypos54_place6_room9_floora place6_door_room9_living_room)
	(locationinplace location_xneg63_ypos15_place5_room5_floorb place5_door_room5_bedroom)
	(locationinplace location_xneg65_yneg20_place7_room13_floorb place7_door_room13_television_room)
	(locationinplace location_xneg73_ypos26_place24_room5_floorb place24_receptacle15_chair)
	(locationinplace location_xneg8_yneg7_place8_room10_floora place8_door_room10_living_room)
	(locationinplace location_xneg8_ypos11_place9_room4_floorb place9_door_room4_bedroom)
	(locationinplace location_xpos0_yneg25_place1_room2_floorb place1_door_room2_bathroom)
	(locationinplace location_xpos11_yneg21_place46_room10_floora place46_receptacle55_oven)
	(locationinplace location_xpos5_yneg33_place46_room10_floora place46_receptacle55_oven)
	(placeinroom place0_door_room12_staircase room12_staircase)
	(placeinroom place10_door_room1_bathroom room1_bathroom)
	(placeinroom place11_door_room14_utility_room room14_utility_room)
	(placeinroom place12_door_room6_corridor room6_corridor)
	(placeinroom place13_door_room11_lobby room11_lobby)
	(placeinroom place16_item33_potted_plant room12_staircase)
	(placeinroom place1_door_room2_bathroom room2_bathroom)
	(placeinroom place24_receptacle15_chair room5_bedroom)
	(placeinroom place2_door_room3_bathroom room3_bathroom)
	(placeinroom place3_door_room8_kitchen room8_kitchen)
	(placeinroom place46_receptacle55_oven room10_living_room)
	(placeinroom place47_receptacle56_oven room14_utility_room)
	(placeinroom place4_door_room7_dining_room room7_dining_room)
	(placeinroom place5_door_room5_bedroom room5_bedroom)
	(placeinroom place6_door_room9_living_room room9_living_room)
	(placeinroom place7_door_room13_television_room room13_television_room)
	(placeinroom place8_door_room10_living_room room10_living_room)
	(placeinroom place9_door_room4_bedroom room4_bedroom)
	(placelocation location_xneg13_ypos64_place4_room7_floora place4_door_room7_dining_room)
	(placelocation location_xneg18_ypos33_place16_room12_floora place16_item33_potted_plant)
	(placelocation location_xneg29_ypos37_place0_room12_floora place0_door_room12_staircase)
	(placelocation location_xneg33_yneg27_place2_room3_floorb place2_door_room3_bathroom)
	(placelocation location_xneg37_ypos5_place12_room6_floorb place12_door_room6_corridor)
	(placelocation location_xneg38_yneg13_place10_room1_floora place10_door_room1_bathroom)
	(placelocation location_xneg38_yneg30_place11_room14_floora place11_door_room14_utility_room)
	(placelocation location_xneg39_ypos18_place13_room11_floora place13_door_room11_lobby)
	(placelocation location_xneg3_ypos32_place3_room8_floora place3_door_room8_kitchen)
	(placelocation location_xneg41_yneg35_place47_room14_floora place47_receptacle56_oven)
	(placelocation location_xneg62_ypos54_place6_room9_floora place6_door_room9_living_room)
	(placelocation location_xneg63_ypos15_place5_room5_floorb place5_door_room5_bedroom)
	(placelocation location_xneg65_yneg20_place7_room13_floorb place7_door_room13_television_room)
	(placelocation location_xneg73_ypos26_place24_room5_floorb place24_receptacle15_chair)
	(placelocation location_xneg8_yneg7_place8_room10_floora place8_door_room10_living_room)
	(placelocation location_xneg8_ypos11_place9_room4_floorb place9_door_room4_bedroom)
	(placelocation location_xpos0_yneg25_place1_room2_floorb place1_door_room2_bathroom)
	(placelocation location_xpos5_yneg33_place46_room10_floora place46_receptacle55_oven)
	(receptacleatlocation receptacle15_chair location_xneg73_ypos26_place24_room5_floorb)
	(receptacleatlocation receptacle55_oven location_xpos5_yneg33_place46_room10_floora)
	(receptacleatlocation receptacle56_oven location_xneg41_yneg35_place47_room14_floora)
	(receptacleopeningtype receptacle55_oven)
	(receptacleopeningtype receptacle56_oven)
	(roomplace place0_door_room12_staircase room12_staircase)
	(roomplace place10_door_room1_bathroom room1_bathroom)
	(roomplace place11_door_room14_utility_room room14_utility_room)
	(roomplace place12_door_room6_corridor room6_corridor)
	(roomplace place13_door_room11_lobby room11_lobby)
	(roomplace place1_door_room2_bathroom room2_bathroom)
	(roomplace place2_door_room3_bathroom room3_bathroom)
	(roomplace place3_door_room8_kitchen room8_kitchen)
	(roomplace place4_door_room7_dining_room room7_dining_room)
	(roomplace place5_door_room5_bedroom room5_bedroom)
	(roomplace place6_door_room9_living_room room9_living_room)
	(roomplace place7_door_room13_television_room room13_television_room)
	(roomplace place8_door_room10_living_room room10_living_room)
	(roomplace place9_door_room4_bedroom room4_bedroom)
	(roomsconnected room10_living_room room1_bathroom)
	(roomsconnected room11_lobby room12_staircase)
	(roomsconnected room11_lobby room1_bathroom)
	(roomsconnected room12_staircase room11_lobby)
	(roomsconnected room12_staircase room7_dining_room)
	(roomsconnected room12_staircase room8_kitchen)
	(roomsconnected room12_staircase room9_living_room)
	(roomsconnected room13_television_room room3_bathroom)
	(roomsconnected room14_utility_room room1_bathroom)
	(roomsconnected room14_utility_room room3_bathroom)
	(roomsconnected room1_bathroom room10_living_room)
	(roomsconnected room1_bathroom room11_lobby)
	(roomsconnected room1_bathroom room14_utility_room)
	(roomsconnected room2_bathroom room3_bathroom)
	(roomsconnected room3_bathroom room13_television_room)
	(roomsconnected room3_bathroom room14_utility_room)
	(roomsconnected room3_bathroom room2_bathroom)
	(roomsconnected room3_bathroom room6_corridor)
	(roomsconnected room4_bedroom room6_corridor)
	(roomsconnected room5_bedroom room6_corridor)
	(roomsconnected room6_corridor room3_bathroom)
	(roomsconnected room6_corridor room4_bedroom)
	(roomsconnected room6_corridor room5_bedroom)
	(roomsconnected room7_dining_room room12_staircase)
	(roomsconnected room8_kitchen room12_staircase)
	(roomsconnected room9_living_room room12_staircase)
  )
  (:goal (and
	(inreceptacle item33_potted_plant_largeitem receptacle56_oven)
	(inreceptacle item70_clock_mediumitem receptacle15_chair)))
)
