
(define (problem maugansvilletaskographyv2medium2problem101) (:domain taskographyv2medium2scrub)
  (:objects
        item10_umbrella_largeitem - item
	item46_tv_largeitem - item
	location_xneg10_ypos73_place12_room6_floorb - location
	location_xneg14_yneg45_place16_room17_floora - location
	location_xneg1_yneg39_place7_room22_floorb - location
	location_xneg1_ypos17_place9_room21_floorb - location
	location_xneg27_ypos9_place19_room9_floora - location
	location_xneg30_ypos55_place0_room19_floora - location
	location_xneg33_yneg35_place23_room14_floorb - location
	location_xneg33_ypos21_place18_room13_floorb - location
	location_xneg34_ypos78_place13_room3_floorb - location
	location_xneg39_ypos29_place14_room4_floorb - location
	location_xneg39_ypos51_place22_room12_floorb - location
	location_xneg41_yneg12_place11_room23_floora - location
	location_xneg43_yneg3_place24_room18_floora - location
	location_xneg52_yneg25_place20_room10_floora - location
	location_xneg52_ypos52_place21_room11_floorb - location
	location_xneg53_yneg56_place1_room24_floora - location
	location_xneg54_yneg62_place56_room7_floorb - location
	location_xneg59_yneg23_place5_room2_floorb - location
	location_xneg61_yneg51_place3_room7_floorb - location
	location_xneg62_ypos42_place2_room8_floorb - location
	location_xneg62_ypos4_place6_room25_floora - location
	location_xneg63_ypos4_place10_room20_floorb - location
	location_xneg63_ypos72_place4_room5_floorb - location
	location_xneg67_yneg24_place15_room1_floora - location
	location_xneg76_yneg51_place25_room7_floorb - location
	location_xneg7_ypos43_place8_room15_floorb - location
	location_xneg8_ypos1_place17_room16_floora - location
	location_xpos5_ypos76_place57_room6_floorb - location
	location_xpos5_ypos86_place57_room6_floorb - location
	location_xpos8_ypos25_place46_room21_floorb - location
	place0_door_room19_garage - place
	place10_door_room20_home_office - place
	place11_door_room23_staircase - place
	place12_door_room6_bedroom - place
	place13_door_room3_bathroom - place
	place14_door_room4_bathroom - place
	place15_door_room1_bathroom - place
	place16_door_room17_empty_room - place
	place17_door_room16_empty_room - place
	place18_door_room13_corridor - place
	place19_door_room9_closet - place
	place1_door_room24_storage - place
	place20_door_room10_corridor - place
	place21_door_room11_corridor - place
	place22_door_room12_corridor - place
	place23_door_room14_corridor - place
	place24_door_room18_empty_room - place
	place25_item10_umbrella - place
	place2_door_room8_childs_room - place
	place3_door_room7_bedroom - place
	place46_receptacle24_chair - place
	place4_door_room5_bedroom - place
	place56_receptacle34_bed - place
	place57_receptacle35_bed - place
	place5_door_room2_bathroom - place
	place6_door_room25_utility_room - place
	place7_door_room22_living_room - place
	place8_door_room15_dining_room - place
	place9_door_room21_kitchen - place
	receptacle24_chair - receptacle
	receptacle34_bed - receptacle
	receptacle35_bed - receptacle
	robot - agent
	room10_corridor - room
	room11_corridor - room
	room12_corridor - room
	room13_corridor - room
	room14_corridor - room
	room15_dining_room - room
	room16_empty_room - room
	room17_empty_room - room
	room18_empty_room - room
	room19_garage - room
	room1_bathroom - room
	room20_home_office - room
	room21_kitchen - room
	room22_living_room - room
	room23_staircase - room
	room24_storage - room
	room25_utility_room - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bathroom - room
	room5_bedroom - room
	room6_bedroom - room
	room7_bedroom - room
	room8_childs_room - room
	room9_closet - room
  )
  (:init 
	(atlocation robot location_xneg27_ypos9_place19_room9_floora)
	(inanyreceptacle item46_tv_largeitem)
	(inplace robot place19_door_room9_closet)
	(inreceptacle item46_tv_largeitem receptacle35_bed)
	(inroom robot room9_closet)
	(itematlocation item10_umbrella_largeitem location_xneg76_yneg51_place25_room7_floorb)
	(itematlocation item46_tv_largeitem location_xpos5_ypos86_place57_room6_floorb)
	(locationinplace location_xneg10_ypos73_place12_room6_floorb place12_door_room6_bedroom)
	(locationinplace location_xneg14_yneg45_place16_room17_floora place16_door_room17_empty_room)
	(locationinplace location_xneg1_yneg39_place7_room22_floorb place7_door_room22_living_room)
	(locationinplace location_xneg1_ypos17_place9_room21_floorb place9_door_room21_kitchen)
	(locationinplace location_xneg27_ypos9_place19_room9_floora place19_door_room9_closet)
	(locationinplace location_xneg30_ypos55_place0_room19_floora place0_door_room19_garage)
	(locationinplace location_xneg33_yneg35_place23_room14_floorb place23_door_room14_corridor)
	(locationinplace location_xneg33_ypos21_place18_room13_floorb place18_door_room13_corridor)
	(locationinplace location_xneg34_ypos78_place13_room3_floorb place13_door_room3_bathroom)
	(locationinplace location_xneg39_ypos29_place14_room4_floorb place14_door_room4_bathroom)
	(locationinplace location_xneg39_ypos51_place22_room12_floorb place22_door_room12_corridor)
	(locationinplace location_xneg41_yneg12_place11_room23_floora place11_door_room23_staircase)
	(locationinplace location_xneg43_yneg3_place24_room18_floora place24_door_room18_empty_room)
	(locationinplace location_xneg52_yneg25_place20_room10_floora place20_door_room10_corridor)
	(locationinplace location_xneg52_ypos52_place21_room11_floorb place21_door_room11_corridor)
	(locationinplace location_xneg53_yneg56_place1_room24_floora place1_door_room24_storage)
	(locationinplace location_xneg54_yneg62_place56_room7_floorb place56_receptacle34_bed)
	(locationinplace location_xneg59_yneg23_place5_room2_floorb place5_door_room2_bathroom)
	(locationinplace location_xneg61_yneg51_place3_room7_floorb place3_door_room7_bedroom)
	(locationinplace location_xneg62_ypos42_place2_room8_floorb place2_door_room8_childs_room)
	(locationinplace location_xneg62_ypos4_place6_room25_floora place6_door_room25_utility_room)
	(locationinplace location_xneg63_ypos4_place10_room20_floorb place10_door_room20_home_office)
	(locationinplace location_xneg63_ypos72_place4_room5_floorb place4_door_room5_bedroom)
	(locationinplace location_xneg67_yneg24_place15_room1_floora place15_door_room1_bathroom)
	(locationinplace location_xneg76_yneg51_place25_room7_floorb place25_item10_umbrella)
	(locationinplace location_xneg7_ypos43_place8_room15_floorb place8_door_room15_dining_room)
	(locationinplace location_xneg8_ypos1_place17_room16_floora place17_door_room16_empty_room)
	(locationinplace location_xpos5_ypos76_place57_room6_floorb place57_receptacle35_bed)
	(locationinplace location_xpos5_ypos86_place57_room6_floorb place57_receptacle35_bed)
	(locationinplace location_xpos8_ypos25_place46_room21_floorb place46_receptacle24_chair)
	(placeinroom place0_door_room19_garage room19_garage)
	(placeinroom place10_door_room20_home_office room20_home_office)
	(placeinroom place11_door_room23_staircase room23_staircase)
	(placeinroom place12_door_room6_bedroom room6_bedroom)
	(placeinroom place13_door_room3_bathroom room3_bathroom)
	(placeinroom place14_door_room4_bathroom room4_bathroom)
	(placeinroom place15_door_room1_bathroom room1_bathroom)
	(placeinroom place16_door_room17_empty_room room17_empty_room)
	(placeinroom place17_door_room16_empty_room room16_empty_room)
	(placeinroom place18_door_room13_corridor room13_corridor)
	(placeinroom place19_door_room9_closet room9_closet)
	(placeinroom place1_door_room24_storage room24_storage)
	(placeinroom place20_door_room10_corridor room10_corridor)
	(placeinroom place21_door_room11_corridor room11_corridor)
	(placeinroom place22_door_room12_corridor room12_corridor)
	(placeinroom place23_door_room14_corridor room14_corridor)
	(placeinroom place24_door_room18_empty_room room18_empty_room)
	(placeinroom place25_item10_umbrella room7_bedroom)
	(placeinroom place2_door_room8_childs_room room8_childs_room)
	(placeinroom place3_door_room7_bedroom room7_bedroom)
	(placeinroom place46_receptacle24_chair room21_kitchen)
	(placeinroom place4_door_room5_bedroom room5_bedroom)
	(placeinroom place56_receptacle34_bed room7_bedroom)
	(placeinroom place57_receptacle35_bed room6_bedroom)
	(placeinroom place5_door_room2_bathroom room2_bathroom)
	(placeinroom place6_door_room25_utility_room room25_utility_room)
	(placeinroom place7_door_room22_living_room room22_living_room)
	(placeinroom place8_door_room15_dining_room room15_dining_room)
	(placeinroom place9_door_room21_kitchen room21_kitchen)
	(placelocation location_xneg10_ypos73_place12_room6_floorb place12_door_room6_bedroom)
	(placelocation location_xneg14_yneg45_place16_room17_floora place16_door_room17_empty_room)
	(placelocation location_xneg1_yneg39_place7_room22_floorb place7_door_room22_living_room)
	(placelocation location_xneg1_ypos17_place9_room21_floorb place9_door_room21_kitchen)
	(placelocation location_xneg27_ypos9_place19_room9_floora place19_door_room9_closet)
	(placelocation location_xneg30_ypos55_place0_room19_floora place0_door_room19_garage)
	(placelocation location_xneg33_yneg35_place23_room14_floorb place23_door_room14_corridor)
	(placelocation location_xneg33_ypos21_place18_room13_floorb place18_door_room13_corridor)
	(placelocation location_xneg34_ypos78_place13_room3_floorb place13_door_room3_bathroom)
	(placelocation location_xneg39_ypos29_place14_room4_floorb place14_door_room4_bathroom)
	(placelocation location_xneg39_ypos51_place22_room12_floorb place22_door_room12_corridor)
	(placelocation location_xneg41_yneg12_place11_room23_floora place11_door_room23_staircase)
	(placelocation location_xneg43_yneg3_place24_room18_floora place24_door_room18_empty_room)
	(placelocation location_xneg52_yneg25_place20_room10_floora place20_door_room10_corridor)
	(placelocation location_xneg52_ypos52_place21_room11_floorb place21_door_room11_corridor)
	(placelocation location_xneg53_yneg56_place1_room24_floora place1_door_room24_storage)
	(placelocation location_xneg54_yneg62_place56_room7_floorb place56_receptacle34_bed)
	(placelocation location_xneg59_yneg23_place5_room2_floorb place5_door_room2_bathroom)
	(placelocation location_xneg61_yneg51_place3_room7_floorb place3_door_room7_bedroom)
	(placelocation location_xneg62_ypos42_place2_room8_floorb place2_door_room8_childs_room)
	(placelocation location_xneg62_ypos4_place6_room25_floora place6_door_room25_utility_room)
	(placelocation location_xneg63_ypos4_place10_room20_floorb place10_door_room20_home_office)
	(placelocation location_xneg63_ypos72_place4_room5_floorb place4_door_room5_bedroom)
	(placelocation location_xneg67_yneg24_place15_room1_floora place15_door_room1_bathroom)
	(placelocation location_xneg76_yneg51_place25_room7_floorb place25_item10_umbrella)
	(placelocation location_xneg7_ypos43_place8_room15_floorb place8_door_room15_dining_room)
	(placelocation location_xneg8_ypos1_place17_room16_floora place17_door_room16_empty_room)
	(placelocation location_xpos5_ypos76_place57_room6_floorb place57_receptacle35_bed)
	(placelocation location_xpos8_ypos25_place46_room21_floorb place46_receptacle24_chair)
	(receptacleatlocation receptacle24_chair location_xpos8_ypos25_place46_room21_floorb)
	(receptacleatlocation receptacle34_bed location_xneg54_yneg62_place56_room7_floorb)
	(receptacleatlocation receptacle35_bed location_xpos5_ypos76_place57_room6_floorb)
	(roomplace place0_door_room19_garage room19_garage)
	(roomplace place10_door_room20_home_office room20_home_office)
	(roomplace place11_door_room23_staircase room23_staircase)
	(roomplace place12_door_room6_bedroom room6_bedroom)
	(roomplace place13_door_room3_bathroom room3_bathroom)
	(roomplace place14_door_room4_bathroom room4_bathroom)
	(roomplace place15_door_room1_bathroom room1_bathroom)
	(roomplace place16_door_room17_empty_room room17_empty_room)
	(roomplace place17_door_room16_empty_room room16_empty_room)
	(roomplace place18_door_room13_corridor room13_corridor)
	(roomplace place19_door_room9_closet room9_closet)
	(roomplace place1_door_room24_storage room24_storage)
	(roomplace place20_door_room10_corridor room10_corridor)
	(roomplace place21_door_room11_corridor room11_corridor)
	(roomplace place22_door_room12_corridor room12_corridor)
	(roomplace place23_door_room14_corridor room14_corridor)
	(roomplace place24_door_room18_empty_room room18_empty_room)
	(roomplace place2_door_room8_childs_room room8_childs_room)
	(roomplace place3_door_room7_bedroom room7_bedroom)
	(roomplace place4_door_room5_bedroom room5_bedroom)
	(roomplace place5_door_room2_bathroom room2_bathroom)
	(roomplace place6_door_room25_utility_room room25_utility_room)
	(roomplace place7_door_room22_living_room room22_living_room)
	(roomplace place8_door_room15_dining_room room15_dining_room)
	(roomplace place9_door_room21_kitchen room21_kitchen)
	(roomsconnected room10_corridor room1_bathroom)
	(roomsconnected room10_corridor room23_staircase)
	(roomsconnected room10_corridor room24_storage)
	(roomsconnected room11_corridor room12_corridor)
	(roomsconnected room11_corridor room5_bedroom)
	(roomsconnected room11_corridor room8_childs_room)
	(roomsconnected room12_corridor room11_corridor)
	(roomsconnected room12_corridor room3_bathroom)
	(roomsconnected room12_corridor room4_bathroom)
	(roomsconnected room13_corridor room20_home_office)
	(roomsconnected room13_corridor room4_bathroom)
	(roomsconnected room14_corridor room22_living_room)
	(roomsconnected room14_corridor room2_bathroom)
	(roomsconnected room15_dining_room room21_kitchen)
	(roomsconnected room15_dining_room room6_bedroom)
	(roomsconnected room16_empty_room room9_closet)
	(roomsconnected room17_empty_room room24_storage)
	(roomsconnected room18_empty_room room23_staircase)
	(roomsconnected room18_empty_room room25_utility_room)
	(roomsconnected room18_empty_room room9_closet)
	(roomsconnected room19_garage room9_closet)
	(roomsconnected room1_bathroom room10_corridor)
	(roomsconnected room20_home_office room13_corridor)
	(roomsconnected room20_home_office room2_bathroom)
	(roomsconnected room21_kitchen room15_dining_room)
	(roomsconnected room22_living_room room14_corridor)
	(roomsconnected room23_staircase room10_corridor)
	(roomsconnected room23_staircase room18_empty_room)
	(roomsconnected room23_staircase room2_bathroom)
	(roomsconnected room24_storage room10_corridor)
	(roomsconnected room24_storage room17_empty_room)
	(roomsconnected room25_utility_room room18_empty_room)
	(roomsconnected room2_bathroom room14_corridor)
	(roomsconnected room2_bathroom room20_home_office)
	(roomsconnected room2_bathroom room23_staircase)
	(roomsconnected room2_bathroom room7_bedroom)
	(roomsconnected room3_bathroom room12_corridor)
	(roomsconnected room3_bathroom room6_bedroom)
	(roomsconnected room4_bathroom room12_corridor)
	(roomsconnected room4_bathroom room13_corridor)
	(roomsconnected room5_bedroom room11_corridor)
	(roomsconnected room6_bedroom room15_dining_room)
	(roomsconnected room6_bedroom room3_bathroom)
	(roomsconnected room7_bedroom room2_bathroom)
	(roomsconnected room8_childs_room room11_corridor)
	(roomsconnected room9_closet room16_empty_room)
	(roomsconnected room9_closet room18_empty_room)
	(roomsconnected room9_closet room19_garage)
  )
  (:goal (and
	(inreceptacle item10_umbrella_largeitem receptacle24_chair)
	(inreceptacle item46_tv_largeitem receptacle34_bed)))
)
