
(define (problem annonataskographyv2medium2problem83) (:domain taskographyv2medium2scrub)
  (:objects
        item20_vase_mediumitem - item
	item23_vase_mediumitem - item
	location_xneg11_yneg10_place37_room13_floora - location
	location_xneg12_ypos60_place14_room7_floora - location
	location_xneg14_yneg1_place37_room13_floora - location
	location_xneg19_ypos67_place9_room15_floora - location
	location_xneg1_ypos79_place3_room16_floora - location
	location_xneg25_ypos12_place60_room10_floorb - location
	location_xneg30_ypos91_place0_room4_floorb - location
	location_xneg31_ypos19_place11_room10_floorb - location
	location_xneg31_ypos54_place1_room12_floorb - location
	location_xneg31_ypos61_place5_room6_floora - location
	location_xneg35_ypos91_place54_room4_floorb - location
	location_xneg37_ypos25_place10_room9_floora - location
	location_xneg8_ypos17_place7_room13_floora - location
	location_xpos19_ypos5_place8_room14_floorb - location
	location_xpos1_ypos55_place15_room8_floorb - location
	location_xpos1_ypos96_place4_room2_floorb - location
	location_xpos22_yneg15_place47_room14_floorb - location
	location_xpos26_ypos45_place12_room3_floorb - location
	location_xpos29_yneg12_place47_room14_floorb - location
	location_xpos30_ypos91_place13_room5_floorb - location
	location_xpos31_ypos19_place6_room11_floora - location
	location_xpos40_ypos96_place2_room1_floora - location
	place0_door_room4_bedroom - place
	place10_door_room9_dining_room - place
	place11_door_room10_dining_room - place
	place12_door_room3_bedroom - place
	place13_door_room5_bedroom - place
	place14_door_room7_corridor - place
	place15_door_room8_corridor - place
	place1_door_room12_kitchen - place
	place2_door_room1_bathroom - place
	place37_receptacle32_chair - place
	place3_door_room16_storage - place
	place47_receptacle42_chair - place
	place4_door_room2_bathroom - place
	place54_receptacle53_bed - place
	place5_door_room6_closet - place
	place60_receptacle59_dining_table - place
	place6_door_room11_garage - place
	place7_door_room13_living_room - place
	place8_door_room14_living_room - place
	place9_door_room15_staircase - place
	receptacle32_chair - receptacle
	receptacle42_chair - receptacle
	receptacle53_bed - receptacle
	receptacle59_dining_table - receptacle
	robot - agent
	room10_dining_room - room
	room11_garage - room
	room12_kitchen - room
	room13_living_room - room
	room14_living_room - room
	room15_staircase - room
	room16_storage - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bedroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_closet - room
	room7_corridor - room
	room8_corridor - room
	room9_dining_room - room
  )
  (:init 
	(atlocation robot location_xpos26_ypos45_place12_room3_floorb)
	(inanyreceptacle item20_vase_mediumitem)
	(inanyreceptacle item23_vase_mediumitem)
	(inplace robot place12_door_room3_bedroom)
	(inreceptacle item20_vase_mediumitem receptacle32_chair)
	(inreceptacle item23_vase_mediumitem receptacle42_chair)
	(inroom robot room3_bedroom)
	(itematlocation item20_vase_mediumitem location_xneg14_yneg1_place37_room13_floora)
	(itematlocation item23_vase_mediumitem location_xpos22_yneg15_place47_room14_floorb)
	(locationinplace location_xneg11_yneg10_place37_room13_floora place37_receptacle32_chair)
	(locationinplace location_xneg12_ypos60_place14_room7_floora place14_door_room7_corridor)
	(locationinplace location_xneg14_yneg1_place37_room13_floora place37_receptacle32_chair)
	(locationinplace location_xneg19_ypos67_place9_room15_floora place9_door_room15_staircase)
	(locationinplace location_xneg1_ypos79_place3_room16_floora place3_door_room16_storage)
	(locationinplace location_xneg25_ypos12_place60_room10_floorb place60_receptacle59_dining_table)
	(locationinplace location_xneg30_ypos91_place0_room4_floorb place0_door_room4_bedroom)
	(locationinplace location_xneg31_ypos19_place11_room10_floorb place11_door_room10_dining_room)
	(locationinplace location_xneg31_ypos54_place1_room12_floorb place1_door_room12_kitchen)
	(locationinplace location_xneg31_ypos61_place5_room6_floora place5_door_room6_closet)
	(locationinplace location_xneg35_ypos91_place54_room4_floorb place54_receptacle53_bed)
	(locationinplace location_xneg37_ypos25_place10_room9_floora place10_door_room9_dining_room)
	(locationinplace location_xneg8_ypos17_place7_room13_floora place7_door_room13_living_room)
	(locationinplace location_xpos19_ypos5_place8_room14_floorb place8_door_room14_living_room)
	(locationinplace location_xpos1_ypos55_place15_room8_floorb place15_door_room8_corridor)
	(locationinplace location_xpos1_ypos96_place4_room2_floorb place4_door_room2_bathroom)
	(locationinplace location_xpos22_yneg15_place47_room14_floorb place47_receptacle42_chair)
	(locationinplace location_xpos26_ypos45_place12_room3_floorb place12_door_room3_bedroom)
	(locationinplace location_xpos29_yneg12_place47_room14_floorb place47_receptacle42_chair)
	(locationinplace location_xpos30_ypos91_place13_room5_floorb place13_door_room5_bedroom)
	(locationinplace location_xpos31_ypos19_place6_room11_floora place6_door_room11_garage)
	(locationinplace location_xpos40_ypos96_place2_room1_floora place2_door_room1_bathroom)
	(placeinroom place0_door_room4_bedroom room4_bedroom)
	(placeinroom place10_door_room9_dining_room room9_dining_room)
	(placeinroom place11_door_room10_dining_room room10_dining_room)
	(placeinroom place12_door_room3_bedroom room3_bedroom)
	(placeinroom place13_door_room5_bedroom room5_bedroom)
	(placeinroom place14_door_room7_corridor room7_corridor)
	(placeinroom place15_door_room8_corridor room8_corridor)
	(placeinroom place1_door_room12_kitchen room12_kitchen)
	(placeinroom place2_door_room1_bathroom room1_bathroom)
	(placeinroom place37_receptacle32_chair room13_living_room)
	(placeinroom place3_door_room16_storage room16_storage)
	(placeinroom place47_receptacle42_chair room14_living_room)
	(placeinroom place4_door_room2_bathroom room2_bathroom)
	(placeinroom place54_receptacle53_bed room4_bedroom)
	(placeinroom place5_door_room6_closet room6_closet)
	(placeinroom place60_receptacle59_dining_table room10_dining_room)
	(placeinroom place6_door_room11_garage room11_garage)
	(placeinroom place7_door_room13_living_room room13_living_room)
	(placeinroom place8_door_room14_living_room room14_living_room)
	(placeinroom place9_door_room15_staircase room15_staircase)
	(placelocation location_xneg11_yneg10_place37_room13_floora place37_receptacle32_chair)
	(placelocation location_xneg12_ypos60_place14_room7_floora place14_door_room7_corridor)
	(placelocation location_xneg19_ypos67_place9_room15_floora place9_door_room15_staircase)
	(placelocation location_xneg1_ypos79_place3_room16_floora place3_door_room16_storage)
	(placelocation location_xneg25_ypos12_place60_room10_floorb place60_receptacle59_dining_table)
	(placelocation location_xneg30_ypos91_place0_room4_floorb place0_door_room4_bedroom)
	(placelocation location_xneg31_ypos19_place11_room10_floorb place11_door_room10_dining_room)
	(placelocation location_xneg31_ypos54_place1_room12_floorb place1_door_room12_kitchen)
	(placelocation location_xneg31_ypos61_place5_room6_floora place5_door_room6_closet)
	(placelocation location_xneg35_ypos91_place54_room4_floorb place54_receptacle53_bed)
	(placelocation location_xneg37_ypos25_place10_room9_floora place10_door_room9_dining_room)
	(placelocation location_xneg8_ypos17_place7_room13_floora place7_door_room13_living_room)
	(placelocation location_xpos19_ypos5_place8_room14_floorb place8_door_room14_living_room)
	(placelocation location_xpos1_ypos55_place15_room8_floorb place15_door_room8_corridor)
	(placelocation location_xpos1_ypos96_place4_room2_floorb place4_door_room2_bathroom)
	(placelocation location_xpos26_ypos45_place12_room3_floorb place12_door_room3_bedroom)
	(placelocation location_xpos29_yneg12_place47_room14_floorb place47_receptacle42_chair)
	(placelocation location_xpos30_ypos91_place13_room5_floorb place13_door_room5_bedroom)
	(placelocation location_xpos31_ypos19_place6_room11_floora place6_door_room11_garage)
	(placelocation location_xpos40_ypos96_place2_room1_floora place2_door_room1_bathroom)
	(receptacleatlocation receptacle32_chair location_xneg11_yneg10_place37_room13_floora)
	(receptacleatlocation receptacle42_chair location_xpos29_yneg12_place47_room14_floorb)
	(receptacleatlocation receptacle53_bed location_xneg35_ypos91_place54_room4_floorb)
	(receptacleatlocation receptacle59_dining_table location_xneg25_ypos12_place60_room10_floorb)
	(roomplace place0_door_room4_bedroom room4_bedroom)
	(roomplace place10_door_room9_dining_room room9_dining_room)
	(roomplace place11_door_room10_dining_room room10_dining_room)
	(roomplace place12_door_room3_bedroom room3_bedroom)
	(roomplace place13_door_room5_bedroom room5_bedroom)
	(roomplace place14_door_room7_corridor room7_corridor)
	(roomplace place15_door_room8_corridor room8_corridor)
	(roomplace place1_door_room12_kitchen room12_kitchen)
	(roomplace place2_door_room1_bathroom room1_bathroom)
	(roomplace place3_door_room16_storage room16_storage)
	(roomplace place4_door_room2_bathroom room2_bathroom)
	(roomplace place5_door_room6_closet room6_closet)
	(roomplace place6_door_room11_garage room11_garage)
	(roomplace place7_door_room13_living_room room13_living_room)
	(roomplace place8_door_room14_living_room room14_living_room)
	(roomplace place9_door_room15_staircase room15_staircase)
	(roomsconnected room10_dining_room room12_kitchen)
	(roomsconnected room11_garage room13_living_room)
	(roomsconnected room12_kitchen room10_dining_room)
	(roomsconnected room12_kitchen room15_staircase)
	(roomsconnected room12_kitchen room4_bedroom)
	(roomsconnected room12_kitchen room8_corridor)
	(roomsconnected room13_living_room room11_garage)
	(roomsconnected room13_living_room room9_dining_room)
	(roomsconnected room14_living_room room3_bedroom)
	(roomsconnected room15_staircase room12_kitchen)
	(roomsconnected room15_staircase room7_corridor)
	(roomsconnected room16_storage room1_bathroom)
	(roomsconnected room16_storage room7_corridor)
	(roomsconnected room1_bathroom room16_storage)
	(roomsconnected room2_bathroom room4_bedroom)
	(roomsconnected room2_bathroom room5_bedroom)
	(roomsconnected room3_bedroom room14_living_room)
	(roomsconnected room3_bedroom room8_corridor)
	(roomsconnected room4_bedroom room12_kitchen)
	(roomsconnected room4_bedroom room2_bathroom)
	(roomsconnected room5_bedroom room2_bathroom)
	(roomsconnected room6_closet room7_corridor)
	(roomsconnected room6_closet room9_dining_room)
	(roomsconnected room7_corridor room15_staircase)
	(roomsconnected room7_corridor room16_storage)
	(roomsconnected room7_corridor room6_closet)
	(roomsconnected room8_corridor room12_kitchen)
	(roomsconnected room8_corridor room3_bedroom)
	(roomsconnected room9_dining_room room13_living_room)
	(roomsconnected room9_dining_room room6_closet)
  )
  (:goal (and
	(inreceptacle item23_vase_mediumitem receptacle53_bed)
	(inreceptacle item20_vase_mediumitem receptacle59_dining_table)))
)
