
(define (problem gravellytaskographyv2medium2problem155) (:domain taskographyv2medium2scrub)
  (:objects
        item128_vase_mediumitem - item
	item129_vase_mediumitem - item
	location_xneg11_ypos67_place119_room6_floorb - location
	location_xneg1_ypos29_place23_room2_floora - location
	location_xneg28_ypos46_place3_room12_floorb - location
	location_xneg3_ypos1_place29_room28_floora - location
	location_xneg5_yneg28_place19_room19_floorb - location
	location_xpos10_yneg30_place4_room26_floora - location
	location_xpos10_yneg4_place12_room17_floorb - location
	location_xpos11_ypos24_place21_room29_floora - location
	location_xpos18_ypos7_place26_room14_floora - location
	location_xpos1_ypos55_place6_room6_floorb - location
	location_xpos23_ypos47_place16_room20_floorb - location
	location_xpos30_ypos65_place1_room5_floorb - location
	location_xpos31_ypos42_place11_room13_floora - location
	location_xpos32_yneg53_place22_room4_floorb - location
	location_xpos39_yneg67_place9_room24_floora - location
	location_xpos42_ypos1_place17_room18_floorb - location
	location_xpos43_yneg31_place27_room16_floorb - location
	location_xpos43_ypos61_place8_room1_floora - location
	location_xpos4_yneg55_place20_room9_floorb - location
	location_xpos53_yneg51_place5_room15_floorb - location
	location_xpos54_yneg70_place7_room3_floorb - location
	location_xpos5_ypos42_place28_room27_floora - location
	location_xpos5_ypos61_place25_room30_floora - location
	location_xpos61_yneg53_place24_room23_floora - location
	location_xpos62_ypos3_place10_room25_floora - location
	location_xpos63_yneg74_place112_room23_floora - location
	location_xpos63_ypos33_place13_room11_floorb - location
	location_xpos69_ypos54_place18_room7_floora - location
	location_xpos71_yneg25_place2_room10_floorb - location
	location_xpos76_ypos39_place30_room7_floora - location
	location_xpos85_yneg60_place15_room8_floorb - location
	location_xpos89_yneg53_place0_room21_floora - location
	location_xpos9_yneg24_place31_room17_floorb - location
	location_xpos9_yneg65_place14_room22_floora - location
	place0_door_room21_dining_room - place
	place10_door_room25_living_room - place
	place112_receptacle91_oven - place
	place119_receptacle98_sink - place
	place11_door_room13_corridor - place
	place12_door_room17_corridor - place
	place13_door_room11_bedroom - place
	place14_door_room22_dining_room - place
	place15_door_room8_bedroom - place
	place16_door_room20_corridor - place
	place17_door_room18_corridor - place
	place18_door_room7_bedroom - place
	place19_door_room19_corridor - place
	place1_door_room5_bathroom - place
	place20_door_room9_bedroom - place
	place21_door_room29_staircase - place
	place22_door_room4_bathroom - place
	place23_door_room2_bathroom - place
	place24_door_room23_kitchen - place
	place25_door_room30_utility_room - place
	place26_door_room14_corridor - place
	place27_door_room16_corridor - place
	place28_door_room27_lobby - place
	place29_door_room28_lobby - place
	place2_door_room10_bedroom - place
	place30_item128_vase - place
	place31_item129_vase - place
	place3_door_room12_closet - place
	place4_door_room26_living_room - place
	place5_door_room15_corridor - place
	place6_door_room6_bathroom - place
	place7_door_room3_bathroom - place
	place8_door_room1_bathroom - place
	place9_door_room24_kitchen - place
	receptacle91_oven - receptacle
	receptacle98_sink - receptacle
	robot - agent
	room10_bedroom - room
	room11_bedroom - room
	room12_closet - room
	room13_corridor - room
	room14_corridor - room
	room15_corridor - room
	room16_corridor - room
	room17_corridor - room
	room18_corridor - room
	room19_corridor - room
	room1_bathroom - room
	room20_corridor - room
	room21_dining_room - room
	room22_dining_room - room
	room23_kitchen - room
	room24_kitchen - room
	room25_living_room - room
	room26_living_room - room
	room27_lobby - room
	room28_lobby - room
	room29_staircase - room
	room2_bathroom - room
	room30_utility_room - room
	room3_bathroom - room
	room4_bathroom - room
	room5_bathroom - room
	room6_bathroom - room
	room7_bedroom - room
	room8_bedroom - room
	room9_bedroom - room
  )
  (:init 
	(atlocation robot location_xpos42_ypos1_place17_room18_floorb)
	(inplace robot place17_door_room18_corridor)
	(inroom robot room18_corridor)
	(itematlocation item128_vase_mediumitem location_xpos76_ypos39_place30_room7_floora)
	(itematlocation item129_vase_mediumitem location_xpos9_yneg24_place31_room17_floorb)
	(locationinplace location_xneg11_ypos67_place119_room6_floorb place119_receptacle98_sink)
	(locationinplace location_xneg1_ypos29_place23_room2_floora place23_door_room2_bathroom)
	(locationinplace location_xneg28_ypos46_place3_room12_floorb place3_door_room12_closet)
	(locationinplace location_xneg3_ypos1_place29_room28_floora place29_door_room28_lobby)
	(locationinplace location_xneg5_yneg28_place19_room19_floorb place19_door_room19_corridor)
	(locationinplace location_xpos10_yneg30_place4_room26_floora place4_door_room26_living_room)
	(locationinplace location_xpos10_yneg4_place12_room17_floorb place12_door_room17_corridor)
	(locationinplace location_xpos11_ypos24_place21_room29_floora place21_door_room29_staircase)
	(locationinplace location_xpos18_ypos7_place26_room14_floora place26_door_room14_corridor)
	(locationinplace location_xpos1_ypos55_place6_room6_floorb place6_door_room6_bathroom)
	(locationinplace location_xpos23_ypos47_place16_room20_floorb place16_door_room20_corridor)
	(locationinplace location_xpos30_ypos65_place1_room5_floorb place1_door_room5_bathroom)
	(locationinplace location_xpos31_ypos42_place11_room13_floora place11_door_room13_corridor)
	(locationinplace location_xpos32_yneg53_place22_room4_floorb place22_door_room4_bathroom)
	(locationinplace location_xpos39_yneg67_place9_room24_floora place9_door_room24_kitchen)
	(locationinplace location_xpos42_ypos1_place17_room18_floorb place17_door_room18_corridor)
	(locationinplace location_xpos43_yneg31_place27_room16_floorb place27_door_room16_corridor)
	(locationinplace location_xpos43_ypos61_place8_room1_floora place8_door_room1_bathroom)
	(locationinplace location_xpos4_yneg55_place20_room9_floorb place20_door_room9_bedroom)
	(locationinplace location_xpos53_yneg51_place5_room15_floorb place5_door_room15_corridor)
	(locationinplace location_xpos54_yneg70_place7_room3_floorb place7_door_room3_bathroom)
	(locationinplace location_xpos5_ypos42_place28_room27_floora place28_door_room27_lobby)
	(locationinplace location_xpos5_ypos61_place25_room30_floora place25_door_room30_utility_room)
	(locationinplace location_xpos61_yneg53_place24_room23_floora place24_door_room23_kitchen)
	(locationinplace location_xpos62_ypos3_place10_room25_floora place10_door_room25_living_room)
	(locationinplace location_xpos63_yneg74_place112_room23_floora place112_receptacle91_oven)
	(locationinplace location_xpos63_ypos33_place13_room11_floorb place13_door_room11_bedroom)
	(locationinplace location_xpos69_ypos54_place18_room7_floora place18_door_room7_bedroom)
	(locationinplace location_xpos71_yneg25_place2_room10_floorb place2_door_room10_bedroom)
	(locationinplace location_xpos76_ypos39_place30_room7_floora place30_item128_vase)
	(locationinplace location_xpos85_yneg60_place15_room8_floorb place15_door_room8_bedroom)
	(locationinplace location_xpos89_yneg53_place0_room21_floora place0_door_room21_dining_room)
	(locationinplace location_xpos9_yneg24_place31_room17_floorb place31_item129_vase)
	(locationinplace location_xpos9_yneg65_place14_room22_floora place14_door_room22_dining_room)
	(placeinroom place0_door_room21_dining_room room21_dining_room)
	(placeinroom place10_door_room25_living_room room25_living_room)
	(placeinroom place112_receptacle91_oven room23_kitchen)
	(placeinroom place119_receptacle98_sink room6_bathroom)
	(placeinroom place11_door_room13_corridor room13_corridor)
	(placeinroom place12_door_room17_corridor room17_corridor)
	(placeinroom place13_door_room11_bedroom room11_bedroom)
	(placeinroom place14_door_room22_dining_room room22_dining_room)
	(placeinroom place15_door_room8_bedroom room8_bedroom)
	(placeinroom place16_door_room20_corridor room20_corridor)
	(placeinroom place17_door_room18_corridor room18_corridor)
	(placeinroom place18_door_room7_bedroom room7_bedroom)
	(placeinroom place19_door_room19_corridor room19_corridor)
	(placeinroom place1_door_room5_bathroom room5_bathroom)
	(placeinroom place20_door_room9_bedroom room9_bedroom)
	(placeinroom place21_door_room29_staircase room29_staircase)
	(placeinroom place22_door_room4_bathroom room4_bathroom)
	(placeinroom place23_door_room2_bathroom room2_bathroom)
	(placeinroom place24_door_room23_kitchen room23_kitchen)
	(placeinroom place25_door_room30_utility_room room30_utility_room)
	(placeinroom place26_door_room14_corridor room14_corridor)
	(placeinroom place27_door_room16_corridor room16_corridor)
	(placeinroom place28_door_room27_lobby room27_lobby)
	(placeinroom place29_door_room28_lobby room28_lobby)
	(placeinroom place2_door_room10_bedroom room10_bedroom)
	(placeinroom place30_item128_vase room7_bedroom)
	(placeinroom place31_item129_vase room17_corridor)
	(placeinroom place3_door_room12_closet room12_closet)
	(placeinroom place4_door_room26_living_room room26_living_room)
	(placeinroom place5_door_room15_corridor room15_corridor)
	(placeinroom place6_door_room6_bathroom room6_bathroom)
	(placeinroom place7_door_room3_bathroom room3_bathroom)
	(placeinroom place8_door_room1_bathroom room1_bathroom)
	(placeinroom place9_door_room24_kitchen room24_kitchen)
	(placelocation location_xneg11_ypos67_place119_room6_floorb place119_receptacle98_sink)
	(placelocation location_xneg1_ypos29_place23_room2_floora place23_door_room2_bathroom)
	(placelocation location_xneg28_ypos46_place3_room12_floorb place3_door_room12_closet)
	(placelocation location_xneg3_ypos1_place29_room28_floora place29_door_room28_lobby)
	(placelocation location_xneg5_yneg28_place19_room19_floorb place19_door_room19_corridor)
	(placelocation location_xpos10_yneg30_place4_room26_floora place4_door_room26_living_room)
	(placelocation location_xpos10_yneg4_place12_room17_floorb place12_door_room17_corridor)
	(placelocation location_xpos11_ypos24_place21_room29_floora place21_door_room29_staircase)
	(placelocation location_xpos18_ypos7_place26_room14_floora place26_door_room14_corridor)
	(placelocation location_xpos1_ypos55_place6_room6_floorb place6_door_room6_bathroom)
	(placelocation location_xpos23_ypos47_place16_room20_floorb place16_door_room20_corridor)
	(placelocation location_xpos30_ypos65_place1_room5_floorb place1_door_room5_bathroom)
	(placelocation location_xpos31_ypos42_place11_room13_floora place11_door_room13_corridor)
	(placelocation location_xpos32_yneg53_place22_room4_floorb place22_door_room4_bathroom)
	(placelocation location_xpos39_yneg67_place9_room24_floora place9_door_room24_kitchen)
	(placelocation location_xpos42_ypos1_place17_room18_floorb place17_door_room18_corridor)
	(placelocation location_xpos43_yneg31_place27_room16_floorb place27_door_room16_corridor)
	(placelocation location_xpos43_ypos61_place8_room1_floora place8_door_room1_bathroom)
	(placelocation location_xpos4_yneg55_place20_room9_floorb place20_door_room9_bedroom)
	(placelocation location_xpos53_yneg51_place5_room15_floorb place5_door_room15_corridor)
	(placelocation location_xpos54_yneg70_place7_room3_floorb place7_door_room3_bathroom)
	(placelocation location_xpos5_ypos42_place28_room27_floora place28_door_room27_lobby)
	(placelocation location_xpos5_ypos61_place25_room30_floora place25_door_room30_utility_room)
	(placelocation location_xpos61_yneg53_place24_room23_floora place24_door_room23_kitchen)
	(placelocation location_xpos62_ypos3_place10_room25_floora place10_door_room25_living_room)
	(placelocation location_xpos63_yneg74_place112_room23_floora place112_receptacle91_oven)
	(placelocation location_xpos63_ypos33_place13_room11_floorb place13_door_room11_bedroom)
	(placelocation location_xpos69_ypos54_place18_room7_floora place18_door_room7_bedroom)
	(placelocation location_xpos71_yneg25_place2_room10_floorb place2_door_room10_bedroom)
	(placelocation location_xpos76_ypos39_place30_room7_floora place30_item128_vase)
	(placelocation location_xpos85_yneg60_place15_room8_floorb place15_door_room8_bedroom)
	(placelocation location_xpos89_yneg53_place0_room21_floora place0_door_room21_dining_room)
	(placelocation location_xpos9_yneg24_place31_room17_floorb place31_item129_vase)
	(placelocation location_xpos9_yneg65_place14_room22_floora place14_door_room22_dining_room)
	(receptacleatlocation receptacle91_oven location_xpos63_yneg74_place112_room23_floora)
	(receptacleatlocation receptacle98_sink location_xneg11_ypos67_place119_room6_floorb)
	(receptacleopeningtype receptacle91_oven)
	(roomplace place0_door_room21_dining_room room21_dining_room)
	(roomplace place10_door_room25_living_room room25_living_room)
	(roomplace place11_door_room13_corridor room13_corridor)
	(roomplace place12_door_room17_corridor room17_corridor)
	(roomplace place13_door_room11_bedroom room11_bedroom)
	(roomplace place14_door_room22_dining_room room22_dining_room)
	(roomplace place15_door_room8_bedroom room8_bedroom)
	(roomplace place16_door_room20_corridor room20_corridor)
	(roomplace place17_door_room18_corridor room18_corridor)
	(roomplace place18_door_room7_bedroom room7_bedroom)
	(roomplace place19_door_room19_corridor room19_corridor)
	(roomplace place1_door_room5_bathroom room5_bathroom)
	(roomplace place20_door_room9_bedroom room9_bedroom)
	(roomplace place21_door_room29_staircase room29_staircase)
	(roomplace place22_door_room4_bathroom room4_bathroom)
	(roomplace place23_door_room2_bathroom room2_bathroom)
	(roomplace place24_door_room23_kitchen room23_kitchen)
	(roomplace place25_door_room30_utility_room room30_utility_room)
	(roomplace place26_door_room14_corridor room14_corridor)
	(roomplace place27_door_room16_corridor room16_corridor)
	(roomplace place28_door_room27_lobby room27_lobby)
	(roomplace place29_door_room28_lobby room28_lobby)
	(roomplace place2_door_room10_bedroom room10_bedroom)
	(roomplace place3_door_room12_closet room12_closet)
	(roomplace place4_door_room26_living_room room26_living_room)
	(roomplace place5_door_room15_corridor room15_corridor)
	(roomplace place6_door_room6_bathroom room6_bathroom)
	(roomplace place7_door_room3_bathroom room3_bathroom)
	(roomplace place8_door_room1_bathroom room1_bathroom)
	(roomplace place9_door_room24_kitchen room24_kitchen)
	(roomsconnected room10_bedroom room16_corridor)
	(roomsconnected room11_bedroom room18_corridor)
	(roomsconnected room11_bedroom room20_corridor)
	(roomsconnected room12_closet room6_bathroom)
	(roomsconnected room13_corridor room1_bathroom)
	(roomsconnected room13_corridor room27_lobby)
	(roomsconnected room14_corridor room17_corridor)
	(roomsconnected room14_corridor room25_living_room)
	(roomsconnected room14_corridor room28_lobby)
	(roomsconnected room14_corridor room29_staircase)
	(roomsconnected room15_corridor room16_corridor)
	(roomsconnected room15_corridor room3_bathroom)
	(roomsconnected room15_corridor room4_bathroom)
	(roomsconnected room16_corridor room10_bedroom)
	(roomsconnected room16_corridor room15_corridor)
	(roomsconnected room16_corridor room18_corridor)
	(roomsconnected room17_corridor room14_corridor)
	(roomsconnected room17_corridor room19_corridor)
	(roomsconnected room18_corridor room11_bedroom)
	(roomsconnected room18_corridor room16_corridor)
	(roomsconnected room19_corridor room17_corridor)
	(roomsconnected room19_corridor room9_bedroom)
	(roomsconnected room1_bathroom room13_corridor)
	(roomsconnected room1_bathroom room7_bedroom)
	(roomsconnected room20_corridor room11_bedroom)
	(roomsconnected room20_corridor room5_bathroom)
	(roomsconnected room20_corridor room6_bathroom)
	(roomsconnected room21_dining_room room23_kitchen)
	(roomsconnected room22_dining_room room24_kitchen)
	(roomsconnected room22_dining_room room26_living_room)
	(roomsconnected room23_kitchen room21_dining_room)
	(roomsconnected room23_kitchen room24_kitchen)
	(roomsconnected room24_kitchen room22_dining_room)
	(roomsconnected room24_kitchen room23_kitchen)
	(roomsconnected room25_living_room room14_corridor)
	(roomsconnected room26_living_room room22_dining_room)
	(roomsconnected room26_living_room room28_lobby)
	(roomsconnected room27_lobby room13_corridor)
	(roomsconnected room27_lobby room2_bathroom)
	(roomsconnected room27_lobby room30_utility_room)
	(roomsconnected room28_lobby room14_corridor)
	(roomsconnected room28_lobby room26_living_room)
	(roomsconnected room29_staircase room14_corridor)
	(roomsconnected room29_staircase room2_bathroom)
	(roomsconnected room2_bathroom room27_lobby)
	(roomsconnected room2_bathroom room29_staircase)
	(roomsconnected room30_utility_room room27_lobby)
	(roomsconnected room3_bathroom room15_corridor)
	(roomsconnected room3_bathroom room8_bedroom)
	(roomsconnected room4_bathroom room15_corridor)
	(roomsconnected room4_bathroom room9_bedroom)
	(roomsconnected room5_bathroom room20_corridor)
	(roomsconnected room6_bathroom room12_closet)
	(roomsconnected room6_bathroom room20_corridor)
	(roomsconnected room7_bedroom room1_bathroom)
	(roomsconnected room8_bedroom room3_bathroom)
	(roomsconnected room9_bedroom room19_corridor)
	(roomsconnected room9_bedroom room4_bathroom)
  )
  (:goal (and
	(inreceptacle item128_vase_mediumitem receptacle98_sink)
	(inreceptacle item129_vase_mediumitem receptacle91_oven)))
)
