
(define (problem swormvilletaskographyv2medium2problem181) (:domain taskographyv2medium2scrub)
  (:objects
        item10_bottle_smallitem - item
	item33_potted_plant_largeitem - item
	location_xneg3_ypos64_place2_room9_floora - location
	location_xpos11_yneg13_place3_room8_floora - location
	location_xpos11_ypos12_place6_room6_floora - location
	location_xpos12_ypos36_place0_room7_floora - location
	location_xpos14_ypos49_place17_room7_floora - location
	location_xpos18_ypos59_place5_room5_floora - location
	location_xpos33_ypos43_place15_room1_floora - location
	location_xpos36_ypos24_place8_room4_floora - location
	location_xpos39_ypos43_place15_room1_floora - location
	location_xpos47_yneg2_place4_room2_floora - location
	location_xpos47_ypos38_place1_room1_floora - location
	location_xpos53_ypos21_place7_room3_floora - location
	location_xpos60_yneg12_place34_room2_floora - location
	location_xpos61_yneg10_place34_room2_floora - location
	location_xpos6_ypos14_place26_room6_floora - location
	place0_door_room7_kitchen - place
	place15_receptacle4_sink - place
	place17_receptacle6_refrigerator - place
	place1_door_room1_bathroom - place
	place26_receptacle20_chair - place
	place2_door_room9_utility_room - place
	place34_receptacle35_bed - place
	place3_door_room8_living_room - place
	place4_door_room2_bedroom - place
	place5_door_room5_corridor - place
	place6_door_room6_dining_room - place
	place7_door_room3_closet - place
	place8_door_room4_coriidor - place
	receptacle20_chair - receptacle
	receptacle35_bed - receptacle
	receptacle4_sink - receptacle
	receptacle6_refrigerator - receptacle
	robot - agent
	room1_bathroom - room
	room2_bedroom - room
	room3_closet - room
	room4_coriidor - room
	room5_corridor - room
	room6_dining_room - room
	room7_kitchen - room
	room8_living_room - room
	room9_utility_room - room
  )
  (:init 
	(atlocation robot location_xpos11_yneg13_place3_room8_floora)
	(inanyreceptacle item10_bottle_smallitem)
	(inanyreceptacle item33_potted_plant_largeitem)
	(inplace robot place3_door_room8_living_room)
	(inreceptacle item10_bottle_smallitem receptacle35_bed)
	(inreceptacle item33_potted_plant_largeitem receptacle4_sink)
	(inroom robot room8_living_room)
	(itematlocation item10_bottle_smallitem location_xpos61_yneg10_place34_room2_floora)
	(itematlocation item33_potted_plant_largeitem location_xpos33_ypos43_place15_room1_floora)
	(locationinplace location_xneg3_ypos64_place2_room9_floora place2_door_room9_utility_room)
	(locationinplace location_xpos11_yneg13_place3_room8_floora place3_door_room8_living_room)
	(locationinplace location_xpos11_ypos12_place6_room6_floora place6_door_room6_dining_room)
	(locationinplace location_xpos12_ypos36_place0_room7_floora place0_door_room7_kitchen)
	(locationinplace location_xpos14_ypos49_place17_room7_floora place17_receptacle6_refrigerator)
	(locationinplace location_xpos18_ypos59_place5_room5_floora place5_door_room5_corridor)
	(locationinplace location_xpos33_ypos43_place15_room1_floora place15_receptacle4_sink)
	(locationinplace location_xpos36_ypos24_place8_room4_floora place8_door_room4_coriidor)
	(locationinplace location_xpos39_ypos43_place15_room1_floora place15_receptacle4_sink)
	(locationinplace location_xpos47_yneg2_place4_room2_floora place4_door_room2_bedroom)
	(locationinplace location_xpos47_ypos38_place1_room1_floora place1_door_room1_bathroom)
	(locationinplace location_xpos53_ypos21_place7_room3_floora place7_door_room3_closet)
	(locationinplace location_xpos60_yneg12_place34_room2_floora place34_receptacle35_bed)
	(locationinplace location_xpos61_yneg10_place34_room2_floora place34_receptacle35_bed)
	(locationinplace location_xpos6_ypos14_place26_room6_floora place26_receptacle20_chair)
	(placeinroom place0_door_room7_kitchen room7_kitchen)
	(placeinroom place15_receptacle4_sink room1_bathroom)
	(placeinroom place17_receptacle6_refrigerator room7_kitchen)
	(placeinroom place1_door_room1_bathroom room1_bathroom)
	(placeinroom place26_receptacle20_chair room6_dining_room)
	(placeinroom place2_door_room9_utility_room room9_utility_room)
	(placeinroom place34_receptacle35_bed room2_bedroom)
	(placeinroom place3_door_room8_living_room room8_living_room)
	(placeinroom place4_door_room2_bedroom room2_bedroom)
	(placeinroom place5_door_room5_corridor room5_corridor)
	(placeinroom place6_door_room6_dining_room room6_dining_room)
	(placeinroom place7_door_room3_closet room3_closet)
	(placeinroom place8_door_room4_coriidor room4_coriidor)
	(placelocation location_xneg3_ypos64_place2_room9_floora place2_door_room9_utility_room)
	(placelocation location_xpos11_yneg13_place3_room8_floora place3_door_room8_living_room)
	(placelocation location_xpos11_ypos12_place6_room6_floora place6_door_room6_dining_room)
	(placelocation location_xpos12_ypos36_place0_room7_floora place0_door_room7_kitchen)
	(placelocation location_xpos14_ypos49_place17_room7_floora place17_receptacle6_refrigerator)
	(placelocation location_xpos18_ypos59_place5_room5_floora place5_door_room5_corridor)
	(placelocation location_xpos36_ypos24_place8_room4_floora place8_door_room4_coriidor)
	(placelocation location_xpos39_ypos43_place15_room1_floora place15_receptacle4_sink)
	(placelocation location_xpos47_yneg2_place4_room2_floora place4_door_room2_bedroom)
	(placelocation location_xpos47_ypos38_place1_room1_floora place1_door_room1_bathroom)
	(placelocation location_xpos53_ypos21_place7_room3_floora place7_door_room3_closet)
	(placelocation location_xpos60_yneg12_place34_room2_floora place34_receptacle35_bed)
	(placelocation location_xpos6_ypos14_place26_room6_floora place26_receptacle20_chair)
	(receptacleatlocation receptacle20_chair location_xpos6_ypos14_place26_room6_floora)
	(receptacleatlocation receptacle35_bed location_xpos60_yneg12_place34_room2_floora)
	(receptacleatlocation receptacle4_sink location_xpos39_ypos43_place15_room1_floora)
	(receptacleatlocation receptacle6_refrigerator location_xpos14_ypos49_place17_room7_floora)
	(receptacleopeningtype receptacle6_refrigerator)
	(roomplace place0_door_room7_kitchen room7_kitchen)
	(roomplace place1_door_room1_bathroom room1_bathroom)
	(roomplace place2_door_room9_utility_room room9_utility_room)
	(roomplace place3_door_room8_living_room room8_living_room)
	(roomplace place4_door_room2_bedroom room2_bedroom)
	(roomplace place5_door_room5_corridor room5_corridor)
	(roomplace place6_door_room6_dining_room room6_dining_room)
	(roomplace place7_door_room3_closet room3_closet)
	(roomplace place8_door_room4_coriidor room4_coriidor)
	(roomsconnected room1_bathroom room4_coriidor)
	(roomsconnected room2_bedroom room3_closet)
	(roomsconnected room3_closet room2_bedroom)
	(roomsconnected room3_closet room4_coriidor)
	(roomsconnected room4_coriidor room1_bathroom)
	(roomsconnected room4_coriidor room3_closet)
	(roomsconnected room4_coriidor room7_kitchen)
	(roomsconnected room5_corridor room7_kitchen)
	(roomsconnected room5_corridor room9_utility_room)
	(roomsconnected room6_dining_room room7_kitchen)
	(roomsconnected room6_dining_room room8_living_room)
	(roomsconnected room7_kitchen room4_coriidor)
	(roomsconnected room7_kitchen room5_corridor)
	(roomsconnected room7_kitchen room6_dining_room)
	(roomsconnected room8_living_room room6_dining_room)
	(roomsconnected room9_utility_room room5_corridor)
  )
  (:goal (and
	(inreceptacle item10_bottle_smallitem receptacle6_refrigerator)
	(inreceptacle item33_potted_plant_largeitem receptacle20_chair)))
)
