
(define (problem clairtontaskographyv2medium2problem77) (:domain taskographyv2medium2scrub)
  (:objects
        item24_potted_plant_largeitem - item
	item28_potted_plant_largeitem - item
	location_xneg10_ypos11_place5_room4_floora - location
	location_xneg11_yneg29_place2_room3_floora - location
	location_xneg27_yneg65_place3_room8_floora - location
	location_xneg40_ypos12_place0_room2_floora - location
	location_xneg42_yneg29_place6_room1_floora - location
	location_xneg48_yneg15_place8_room5_floora - location
	location_xneg77_yneg17_place1_room7_floora - location
	location_xneg77_yneg46_place4_room6_floora - location
	location_xneg82_ypos13_place7_room9_floora - location
	location_xpos11_ypos4_place42_room4_floora - location
	location_xpos3_yneg24_place37_room3_floora - location
	location_xpos4_yneg81_place18_room8_floora - location
	location_xpos9_yneg60_place22_room8_floora - location
	place0_door_room2_bathroom - place
	place18_item24_potted_plant - place
	place1_door_room7_kitchen - place
	place22_item28_potted_plant - place
	place2_door_room3_bedroom - place
	place37_receptacle31_bed - place
	place3_door_room8_living_room - place
	place42_receptacle36_dining_table - place
	place4_door_room6_dining_room - place
	place5_door_room4_bedroom - place
	place6_door_room1_bathroom - place
	place7_door_room9_utility_room - place
	place8_door_room5_corridor - place
	receptacle31_bed - receptacle
	receptacle36_dining_table - receptacle
	robot - agent
	room1_bathroom - room
	room2_bathroom - room
	room3_bedroom - room
	room4_bedroom - room
	room5_corridor - room
	room6_dining_room - room
	room7_kitchen - room
	room8_living_room - room
	room9_utility_room - room
  )
  (:init 
	(atlocation robot location_xneg42_yneg29_place6_room1_floora)
	(inplace robot place6_door_room1_bathroom)
	(inroom robot room1_bathroom)
	(itematlocation item24_potted_plant_largeitem location_xpos4_yneg81_place18_room8_floora)
	(itematlocation item28_potted_plant_largeitem location_xpos9_yneg60_place22_room8_floora)
	(locationinplace location_xneg10_ypos11_place5_room4_floora place5_door_room4_bedroom)
	(locationinplace location_xneg11_yneg29_place2_room3_floora place2_door_room3_bedroom)
	(locationinplace location_xneg27_yneg65_place3_room8_floora place3_door_room8_living_room)
	(locationinplace location_xneg40_ypos12_place0_room2_floora place0_door_room2_bathroom)
	(locationinplace location_xneg42_yneg29_place6_room1_floora place6_door_room1_bathroom)
	(locationinplace location_xneg48_yneg15_place8_room5_floora place8_door_room5_corridor)
	(locationinplace location_xneg77_yneg17_place1_room7_floora place1_door_room7_kitchen)
	(locationinplace location_xneg77_yneg46_place4_room6_floora place4_door_room6_dining_room)
	(locationinplace location_xneg82_ypos13_place7_room9_floora place7_door_room9_utility_room)
	(locationinplace location_xpos11_ypos4_place42_room4_floora place42_receptacle36_dining_table)
	(locationinplace location_xpos3_yneg24_place37_room3_floora place37_receptacle31_bed)
	(locationinplace location_xpos4_yneg81_place18_room8_floora place18_item24_potted_plant)
	(locationinplace location_xpos9_yneg60_place22_room8_floora place22_item28_potted_plant)
	(placeinroom place0_door_room2_bathroom room2_bathroom)
	(placeinroom place18_item24_potted_plant room8_living_room)
	(placeinroom place1_door_room7_kitchen room7_kitchen)
	(placeinroom place22_item28_potted_plant room8_living_room)
	(placeinroom place2_door_room3_bedroom room3_bedroom)
	(placeinroom place37_receptacle31_bed room3_bedroom)
	(placeinroom place3_door_room8_living_room room8_living_room)
	(placeinroom place42_receptacle36_dining_table room4_bedroom)
	(placeinroom place4_door_room6_dining_room room6_dining_room)
	(placeinroom place5_door_room4_bedroom room4_bedroom)
	(placeinroom place6_door_room1_bathroom room1_bathroom)
	(placeinroom place7_door_room9_utility_room room9_utility_room)
	(placeinroom place8_door_room5_corridor room5_corridor)
	(placelocation location_xneg10_ypos11_place5_room4_floora place5_door_room4_bedroom)
	(placelocation location_xneg11_yneg29_place2_room3_floora place2_door_room3_bedroom)
	(placelocation location_xneg27_yneg65_place3_room8_floora place3_door_room8_living_room)
	(placelocation location_xneg40_ypos12_place0_room2_floora place0_door_room2_bathroom)
	(placelocation location_xneg42_yneg29_place6_room1_floora place6_door_room1_bathroom)
	(placelocation location_xneg48_yneg15_place8_room5_floora place8_door_room5_corridor)
	(placelocation location_xneg77_yneg17_place1_room7_floora place1_door_room7_kitchen)
	(placelocation location_xneg77_yneg46_place4_room6_floora place4_door_room6_dining_room)
	(placelocation location_xneg82_ypos13_place7_room9_floora place7_door_room9_utility_room)
	(placelocation location_xpos11_ypos4_place42_room4_floora place42_receptacle36_dining_table)
	(placelocation location_xpos3_yneg24_place37_room3_floora place37_receptacle31_bed)
	(placelocation location_xpos4_yneg81_place18_room8_floora place18_item24_potted_plant)
	(placelocation location_xpos9_yneg60_place22_room8_floora place22_item28_potted_plant)
	(receptacleatlocation receptacle31_bed location_xpos3_yneg24_place37_room3_floora)
	(receptacleatlocation receptacle36_dining_table location_xpos11_ypos4_place42_room4_floora)
	(roomplace place0_door_room2_bathroom room2_bathroom)
	(roomplace place1_door_room7_kitchen room7_kitchen)
	(roomplace place2_door_room3_bedroom room3_bedroom)
	(roomplace place3_door_room8_living_room room8_living_room)
	(roomplace place4_door_room6_dining_room room6_dining_room)
	(roomplace place5_door_room4_bedroom room4_bedroom)
	(roomplace place6_door_room1_bathroom room1_bathroom)
	(roomplace place7_door_room9_utility_room room9_utility_room)
	(roomplace place8_door_room5_corridor room5_corridor)
	(roomsconnected room1_bathroom room3_bedroom)
	(roomsconnected room1_bathroom room5_corridor)
	(roomsconnected room1_bathroom room8_living_room)
	(roomsconnected room2_bathroom room4_bedroom)
	(roomsconnected room2_bathroom room5_corridor)
	(roomsconnected room3_bedroom room1_bathroom)
	(roomsconnected room4_bedroom room2_bathroom)
	(roomsconnected room5_corridor room1_bathroom)
	(roomsconnected room5_corridor room2_bathroom)
	(roomsconnected room5_corridor room7_kitchen)
	(roomsconnected room6_dining_room room7_kitchen)
	(roomsconnected room7_kitchen room5_corridor)
	(roomsconnected room7_kitchen room6_dining_room)
	(roomsconnected room7_kitchen room9_utility_room)
	(roomsconnected room8_living_room room1_bathroom)
	(roomsconnected room9_utility_room room7_kitchen)
  )
  (:goal (and
	(inreceptacle item24_potted_plant_largeitem receptacle31_bed)
	(inreceptacle item28_potted_plant_largeitem receptacle36_dining_table)))
)
