
(define (problem andovertaskographyv2medium2problem205) (:domain taskographyv2medium2scrub)
  (:objects
        item26_potted_plant_largeitem - item
	item54_tv_largeitem - item
	location_xneg13_yneg22_place3_room15_floora - location
	location_xneg13_yneg70_place7_room9_floora - location
	location_xneg17_yneg42_place16_room12_floorc - location
	location_xneg17_ypos0_place0_room8_floorc - location
	location_xneg18_yneg81_place19_room19_floorb - location
	location_xneg29_yneg112_place6_room16_floorb - location
	location_xneg29_yneg156_place2_room13_floorb - location
	location_xneg2_yneg68_place13_room3_floorc - location
	location_xneg35_yneg136_place32_room16_floorb - location
	location_xneg38_yneg5_place11_room6_floorc - location
	location_xneg39_yneg54_place5_room5_floorc - location
	location_xneg44_ypos5_place59_room6_floorc - location
	location_xneg8_yneg80_place18_room18_floora - location
	location_xpos10_yneg44_place14_room7_floorc - location
	location_xpos13_yneg69_place8_room20_floora - location
	location_xpos18_yneg106_place15_room10_floorb - location
	location_xpos18_ypos1_place52_room15_floora - location
	location_xpos19_yneg68_place9_room2_floorc - location
	location_xpos23_yneg10_place52_room15_floora - location
	location_xpos30_yneg150_place4_room14_floorb - location
	location_xpos32_yneg92_place1_room11_floorb - location
	location_xpos47_yneg113_place17_room17_floorb - location
	location_xpos49_yneg94_place12_room1_floorb - location
	location_xpos6_yneg25_place51_room15_floora - location
	location_xpos8_yneg13_place10_room4_floorc - location
	place0_door_room8_closet - place
	place10_door_room4_bedroom - place
	place11_door_room6_childs_room - place
	place12_door_room1_bathroom - place
	place13_door_room3_bathroom - place
	place14_door_room7_closet - place
	place15_door_room10_corridor - place
	place16_door_room12_corridor - place
	place17_door_room17_lobby - place
	place18_door_room18_staircase - place
	place19_door_room19_staircase - place
	place1_door_room11_corridor - place
	place2_door_room13_dining_room - place
	place32_item54_tv - place
	place3_door_room15_living_room - place
	place4_door_room14_kitchen - place
	place51_receptacle20_couch - place
	place52_receptacle21_couch - place
	place59_receptacle45_bed - place
	place5_door_room5_bedroom - place
	place6_door_room16_living_room - place
	place7_door_room9_corridor - place
	place8_door_room20_utility_room - place
	place9_door_room2_bathroom - place
	receptacle20_couch - receptacle
	receptacle21_couch - receptacle
	receptacle45_bed - receptacle
	robot - agent
	room10_corridor - room
	room11_corridor - room
	room12_corridor - room
	room13_dining_room - room
	room14_kitchen - room
	room15_living_room - room
	room16_living_room - room
	room17_lobby - room
	room18_staircase - room
	room19_staircase - room
	room1_bathroom - room
	room20_utility_room - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_childs_room - room
	room7_closet - room
	room8_closet - room
	room9_corridor - room
  )
  (:init 
	(atlocation robot location_xneg29_yneg156_place2_room13_floorb)
	(inanyreceptacle item26_potted_plant_largeitem)
	(inplace robot place2_door_room13_dining_room)
	(inreceptacle item26_potted_plant_largeitem receptacle21_couch)
	(inroom robot room13_dining_room)
	(itematlocation item26_potted_plant_largeitem location_xpos23_yneg10_place52_room15_floora)
	(itematlocation item54_tv_largeitem location_xneg35_yneg136_place32_room16_floorb)
	(locationinplace location_xneg13_yneg22_place3_room15_floora place3_door_room15_living_room)
	(locationinplace location_xneg13_yneg70_place7_room9_floora place7_door_room9_corridor)
	(locationinplace location_xneg17_yneg42_place16_room12_floorc place16_door_room12_corridor)
	(locationinplace location_xneg17_ypos0_place0_room8_floorc place0_door_room8_closet)
	(locationinplace location_xneg18_yneg81_place19_room19_floorb place19_door_room19_staircase)
	(locationinplace location_xneg29_yneg112_place6_room16_floorb place6_door_room16_living_room)
	(locationinplace location_xneg29_yneg156_place2_room13_floorb place2_door_room13_dining_room)
	(locationinplace location_xneg2_yneg68_place13_room3_floorc place13_door_room3_bathroom)
	(locationinplace location_xneg35_yneg136_place32_room16_floorb place32_item54_tv)
	(locationinplace location_xneg38_yneg5_place11_room6_floorc place11_door_room6_childs_room)
	(locationinplace location_xneg39_yneg54_place5_room5_floorc place5_door_room5_bedroom)
	(locationinplace location_xneg44_ypos5_place59_room6_floorc place59_receptacle45_bed)
	(locationinplace location_xneg8_yneg80_place18_room18_floora place18_door_room18_staircase)
	(locationinplace location_xpos10_yneg44_place14_room7_floorc place14_door_room7_closet)
	(locationinplace location_xpos13_yneg69_place8_room20_floora place8_door_room20_utility_room)
	(locationinplace location_xpos18_yneg106_place15_room10_floorb place15_door_room10_corridor)
	(locationinplace location_xpos18_ypos1_place52_room15_floora place52_receptacle21_couch)
	(locationinplace location_xpos19_yneg68_place9_room2_floorc place9_door_room2_bathroom)
	(locationinplace location_xpos23_yneg10_place52_room15_floora place52_receptacle21_couch)
	(locationinplace location_xpos30_yneg150_place4_room14_floorb place4_door_room14_kitchen)
	(locationinplace location_xpos32_yneg92_place1_room11_floorb place1_door_room11_corridor)
	(locationinplace location_xpos47_yneg113_place17_room17_floorb place17_door_room17_lobby)
	(locationinplace location_xpos49_yneg94_place12_room1_floorb place12_door_room1_bathroom)
	(locationinplace location_xpos6_yneg25_place51_room15_floora place51_receptacle20_couch)
	(locationinplace location_xpos8_yneg13_place10_room4_floorc place10_door_room4_bedroom)
	(placeinroom place0_door_room8_closet room8_closet)
	(placeinroom place10_door_room4_bedroom room4_bedroom)
	(placeinroom place11_door_room6_childs_room room6_childs_room)
	(placeinroom place12_door_room1_bathroom room1_bathroom)
	(placeinroom place13_door_room3_bathroom room3_bathroom)
	(placeinroom place14_door_room7_closet room7_closet)
	(placeinroom place15_door_room10_corridor room10_corridor)
	(placeinroom place16_door_room12_corridor room12_corridor)
	(placeinroom place17_door_room17_lobby room17_lobby)
	(placeinroom place18_door_room18_staircase room18_staircase)
	(placeinroom place19_door_room19_staircase room19_staircase)
	(placeinroom place1_door_room11_corridor room11_corridor)
	(placeinroom place2_door_room13_dining_room room13_dining_room)
	(placeinroom place32_item54_tv room16_living_room)
	(placeinroom place3_door_room15_living_room room15_living_room)
	(placeinroom place4_door_room14_kitchen room14_kitchen)
	(placeinroom place51_receptacle20_couch room15_living_room)
	(placeinroom place52_receptacle21_couch room15_living_room)
	(placeinroom place59_receptacle45_bed room6_childs_room)
	(placeinroom place5_door_room5_bedroom room5_bedroom)
	(placeinroom place6_door_room16_living_room room16_living_room)
	(placeinroom place7_door_room9_corridor room9_corridor)
	(placeinroom place8_door_room20_utility_room room20_utility_room)
	(placeinroom place9_door_room2_bathroom room2_bathroom)
	(placelocation location_xneg13_yneg22_place3_room15_floora place3_door_room15_living_room)
	(placelocation location_xneg13_yneg70_place7_room9_floora place7_door_room9_corridor)
	(placelocation location_xneg17_yneg42_place16_room12_floorc place16_door_room12_corridor)
	(placelocation location_xneg17_ypos0_place0_room8_floorc place0_door_room8_closet)
	(placelocation location_xneg18_yneg81_place19_room19_floorb place19_door_room19_staircase)
	(placelocation location_xneg29_yneg112_place6_room16_floorb place6_door_room16_living_room)
	(placelocation location_xneg29_yneg156_place2_room13_floorb place2_door_room13_dining_room)
	(placelocation location_xneg2_yneg68_place13_room3_floorc place13_door_room3_bathroom)
	(placelocation location_xneg35_yneg136_place32_room16_floorb place32_item54_tv)
	(placelocation location_xneg38_yneg5_place11_room6_floorc place11_door_room6_childs_room)
	(placelocation location_xneg39_yneg54_place5_room5_floorc place5_door_room5_bedroom)
	(placelocation location_xneg44_ypos5_place59_room6_floorc place59_receptacle45_bed)
	(placelocation location_xneg8_yneg80_place18_room18_floora place18_door_room18_staircase)
	(placelocation location_xpos10_yneg44_place14_room7_floorc place14_door_room7_closet)
	(placelocation location_xpos13_yneg69_place8_room20_floora place8_door_room20_utility_room)
	(placelocation location_xpos18_yneg106_place15_room10_floorb place15_door_room10_corridor)
	(placelocation location_xpos18_ypos1_place52_room15_floora place52_receptacle21_couch)
	(placelocation location_xpos19_yneg68_place9_room2_floorc place9_door_room2_bathroom)
	(placelocation location_xpos30_yneg150_place4_room14_floorb place4_door_room14_kitchen)
	(placelocation location_xpos32_yneg92_place1_room11_floorb place1_door_room11_corridor)
	(placelocation location_xpos47_yneg113_place17_room17_floorb place17_door_room17_lobby)
	(placelocation location_xpos49_yneg94_place12_room1_floorb place12_door_room1_bathroom)
	(placelocation location_xpos6_yneg25_place51_room15_floora place51_receptacle20_couch)
	(placelocation location_xpos8_yneg13_place10_room4_floorc place10_door_room4_bedroom)
	(receptacleatlocation receptacle20_couch location_xpos6_yneg25_place51_room15_floora)
	(receptacleatlocation receptacle21_couch location_xpos18_ypos1_place52_room15_floora)
	(receptacleatlocation receptacle45_bed location_xneg44_ypos5_place59_room6_floorc)
	(roomplace place0_door_room8_closet room8_closet)
	(roomplace place10_door_room4_bedroom room4_bedroom)
	(roomplace place11_door_room6_childs_room room6_childs_room)
	(roomplace place12_door_room1_bathroom room1_bathroom)
	(roomplace place13_door_room3_bathroom room3_bathroom)
	(roomplace place14_door_room7_closet room7_closet)
	(roomplace place15_door_room10_corridor room10_corridor)
	(roomplace place16_door_room12_corridor room12_corridor)
	(roomplace place17_door_room17_lobby room17_lobby)
	(roomplace place18_door_room18_staircase room18_staircase)
	(roomplace place19_door_room19_staircase room19_staircase)
	(roomplace place1_door_room11_corridor room11_corridor)
	(roomplace place2_door_room13_dining_room room13_dining_room)
	(roomplace place3_door_room15_living_room room15_living_room)
	(roomplace place4_door_room14_kitchen room14_kitchen)
	(roomplace place5_door_room5_bedroom room5_bedroom)
	(roomplace place6_door_room16_living_room room16_living_room)
	(roomplace place7_door_room9_corridor room9_corridor)
	(roomplace place8_door_room20_utility_room room20_utility_room)
	(roomplace place9_door_room2_bathroom room2_bathroom)
	(roomsconnected room10_corridor room11_corridor)
	(roomsconnected room10_corridor room19_staircase)
	(roomsconnected room11_corridor room10_corridor)
	(roomsconnected room11_corridor room1_bathroom)
	(roomsconnected room12_corridor room5_bedroom)
	(roomsconnected room12_corridor room7_closet)
	(roomsconnected room13_dining_room room16_living_room)
	(roomsconnected room14_kitchen room17_lobby)
	(roomsconnected room15_living_room room9_corridor)
	(roomsconnected room16_living_room room13_dining_room)
	(roomsconnected room16_living_room room19_staircase)
	(roomsconnected room17_lobby room14_kitchen)
	(roomsconnected room17_lobby room1_bathroom)
	(roomsconnected room18_staircase room19_staircase)
	(roomsconnected room18_staircase room20_utility_room)
	(roomsconnected room18_staircase room3_bathroom)
	(roomsconnected room18_staircase room9_corridor)
	(roomsconnected room19_staircase room10_corridor)
	(roomsconnected room19_staircase room16_living_room)
	(roomsconnected room19_staircase room18_staircase)
	(roomsconnected room1_bathroom room11_corridor)
	(roomsconnected room1_bathroom room17_lobby)
	(roomsconnected room20_utility_room room18_staircase)
	(roomsconnected room2_bathroom room3_bathroom)
	(roomsconnected room2_bathroom room7_closet)
	(roomsconnected room3_bathroom room18_staircase)
	(roomsconnected room3_bathroom room2_bathroom)
	(roomsconnected room4_bedroom room7_closet)
	(roomsconnected room4_bedroom room8_closet)
	(roomsconnected room5_bedroom room12_corridor)
	(roomsconnected room6_childs_room room8_closet)
	(roomsconnected room7_closet room12_corridor)
	(roomsconnected room7_closet room2_bathroom)
	(roomsconnected room7_closet room4_bedroom)
	(roomsconnected room8_closet room4_bedroom)
	(roomsconnected room8_closet room6_childs_room)
	(roomsconnected room9_corridor room15_living_room)
	(roomsconnected room9_corridor room18_staircase)
  )
  (:goal (and
	(inreceptacle item26_potted_plant_largeitem receptacle45_bed)
	(inreceptacle item54_tv_largeitem receptacle20_couch)))
)
