
(define (problem highspiretaskographyv2medium2problem57) (:domain taskographyv2medium2scrub)
  (:objects
        item29_tv_largeitem - item
	item45_clock_mediumitem - item
	location_xneg14_ypos19_place12_room16_floorb - location
	location_xneg19_yneg30_place37_room6_floorc - location
	location_xneg20_ypos20_place15_room15_floora - location
	location_xneg22_ypos9_place2_room7_floora - location
	location_xneg26_ypos12_place13_room8_floorb - location
	location_xneg31_yneg14_place37_room6_floorc - location
	location_xneg31_yneg7_place6_room6_floorc - location
	location_xneg42_yneg31_place21_room13_floorb - location
	location_xneg43_yneg16_place7_room13_floorb - location
	location_xneg48_ypos15_place4_room14_floora - location
	location_xneg5_yneg14_place10_room4_floorc - location
	location_xneg8_yneg17_place5_room10_floorb - location
	location_xpos15_yneg7_place0_room5_floora - location
	location_xpos17_ypos18_place8_room2_floorb - location
	location_xpos18_yneg14_place1_room11_floorc - location
	location_xpos19_ypos14_place40_room2_floorb - location
	location_xpos20_yneg11_place3_room12_floorb - location
	location_xpos22_ypos19_place9_room1_floora - location
	location_xpos27_ypos14_place11_room3_floorc - location
	location_xpos30_ypos19_place50_room1_floora - location
	location_xpos5_ypos9_place14_room9_floorc - location
	place0_door_room5_bedroom - place
	place10_door_room4_bathroom - place
	place11_door_room3_bathroom - place
	place12_door_room16_staircase - place
	place13_door_room8_corridor - place
	place14_door_room9_corridor - place
	place15_door_room15_staircase - place
	place1_door_room11_home_office - place
	place21_item29_tv - place
	place2_door_room7_corridor - place
	place37_receptacle21_bed - place
	place3_door_room12_kitchen - place
	place40_receptacle24_toilet - place
	place4_door_room14_lobby - place
	place50_receptacle39_sink - place
	place5_door_room10_dining_room - place
	place6_door_room6_bedroom - place
	place7_door_room13_living_room - place
	place8_door_room2_bathroom - place
	place9_door_room1_bathroom - place
	receptacle21_bed - receptacle
	receptacle24_toilet - receptacle
	receptacle39_sink - receptacle
	robot - agent
	room10_dining_room - room
	room11_home_office - room
	room12_kitchen - room
	room13_living_room - room
	room14_lobby - room
	room15_staircase - room
	room16_staircase - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bathroom - room
	room5_bedroom - room
	room6_bedroom - room
	room7_corridor - room
	room8_corridor - room
	room9_corridor - room
  )
  (:init 
	(atlocation robot location_xneg26_ypos12_place13_room8_floorb)
	(inanyreceptacle item45_clock_mediumitem)
	(inplace robot place13_door_room8_corridor)
	(inreceptacle item45_clock_mediumitem receptacle21_bed)
	(inroom robot room8_corridor)
	(itematlocation item29_tv_largeitem location_xneg42_yneg31_place21_room13_floorb)
	(itematlocation item45_clock_mediumitem location_xneg19_yneg30_place37_room6_floorc)
	(locationinplace location_xneg14_ypos19_place12_room16_floorb place12_door_room16_staircase)
	(locationinplace location_xneg19_yneg30_place37_room6_floorc place37_receptacle21_bed)
	(locationinplace location_xneg20_ypos20_place15_room15_floora place15_door_room15_staircase)
	(locationinplace location_xneg22_ypos9_place2_room7_floora place2_door_room7_corridor)
	(locationinplace location_xneg26_ypos12_place13_room8_floorb place13_door_room8_corridor)
	(locationinplace location_xneg31_yneg14_place37_room6_floorc place37_receptacle21_bed)
	(locationinplace location_xneg31_yneg7_place6_room6_floorc place6_door_room6_bedroom)
	(locationinplace location_xneg42_yneg31_place21_room13_floorb place21_item29_tv)
	(locationinplace location_xneg43_yneg16_place7_room13_floorb place7_door_room13_living_room)
	(locationinplace location_xneg48_ypos15_place4_room14_floora place4_door_room14_lobby)
	(locationinplace location_xneg5_yneg14_place10_room4_floorc place10_door_room4_bathroom)
	(locationinplace location_xneg8_yneg17_place5_room10_floorb place5_door_room10_dining_room)
	(locationinplace location_xpos15_yneg7_place0_room5_floora place0_door_room5_bedroom)
	(locationinplace location_xpos17_ypos18_place8_room2_floorb place8_door_room2_bathroom)
	(locationinplace location_xpos18_yneg14_place1_room11_floorc place1_door_room11_home_office)
	(locationinplace location_xpos19_ypos14_place40_room2_floorb place40_receptacle24_toilet)
	(locationinplace location_xpos20_yneg11_place3_room12_floorb place3_door_room12_kitchen)
	(locationinplace location_xpos22_ypos19_place9_room1_floora place9_door_room1_bathroom)
	(locationinplace location_xpos27_ypos14_place11_room3_floorc place11_door_room3_bathroom)
	(locationinplace location_xpos30_ypos19_place50_room1_floora place50_receptacle39_sink)
	(locationinplace location_xpos5_ypos9_place14_room9_floorc place14_door_room9_corridor)
	(placeinroom place0_door_room5_bedroom room5_bedroom)
	(placeinroom place10_door_room4_bathroom room4_bathroom)
	(placeinroom place11_door_room3_bathroom room3_bathroom)
	(placeinroom place12_door_room16_staircase room16_staircase)
	(placeinroom place13_door_room8_corridor room8_corridor)
	(placeinroom place14_door_room9_corridor room9_corridor)
	(placeinroom place15_door_room15_staircase room15_staircase)
	(placeinroom place1_door_room11_home_office room11_home_office)
	(placeinroom place21_item29_tv room13_living_room)
	(placeinroom place2_door_room7_corridor room7_corridor)
	(placeinroom place37_receptacle21_bed room6_bedroom)
	(placeinroom place3_door_room12_kitchen room12_kitchen)
	(placeinroom place40_receptacle24_toilet room2_bathroom)
	(placeinroom place4_door_room14_lobby room14_lobby)
	(placeinroom place50_receptacle39_sink room1_bathroom)
	(placeinroom place5_door_room10_dining_room room10_dining_room)
	(placeinroom place6_door_room6_bedroom room6_bedroom)
	(placeinroom place7_door_room13_living_room room13_living_room)
	(placeinroom place8_door_room2_bathroom room2_bathroom)
	(placeinroom place9_door_room1_bathroom room1_bathroom)
	(placelocation location_xneg14_ypos19_place12_room16_floorb place12_door_room16_staircase)
	(placelocation location_xneg20_ypos20_place15_room15_floora place15_door_room15_staircase)
	(placelocation location_xneg22_ypos9_place2_room7_floora place2_door_room7_corridor)
	(placelocation location_xneg26_ypos12_place13_room8_floorb place13_door_room8_corridor)
	(placelocation location_xneg31_yneg14_place37_room6_floorc place37_receptacle21_bed)
	(placelocation location_xneg31_yneg7_place6_room6_floorc place6_door_room6_bedroom)
	(placelocation location_xneg42_yneg31_place21_room13_floorb place21_item29_tv)
	(placelocation location_xneg43_yneg16_place7_room13_floorb place7_door_room13_living_room)
	(placelocation location_xneg48_ypos15_place4_room14_floora place4_door_room14_lobby)
	(placelocation location_xneg5_yneg14_place10_room4_floorc place10_door_room4_bathroom)
	(placelocation location_xneg8_yneg17_place5_room10_floorb place5_door_room10_dining_room)
	(placelocation location_xpos15_yneg7_place0_room5_floora place0_door_room5_bedroom)
	(placelocation location_xpos17_ypos18_place8_room2_floorb place8_door_room2_bathroom)
	(placelocation location_xpos18_yneg14_place1_room11_floorc place1_door_room11_home_office)
	(placelocation location_xpos19_ypos14_place40_room2_floorb place40_receptacle24_toilet)
	(placelocation location_xpos20_yneg11_place3_room12_floorb place3_door_room12_kitchen)
	(placelocation location_xpos22_ypos19_place9_room1_floora place9_door_room1_bathroom)
	(placelocation location_xpos27_ypos14_place11_room3_floorc place11_door_room3_bathroom)
	(placelocation location_xpos30_ypos19_place50_room1_floora place50_receptacle39_sink)
	(placelocation location_xpos5_ypos9_place14_room9_floorc place14_door_room9_corridor)
	(receptacleatlocation receptacle21_bed location_xneg31_yneg14_place37_room6_floorc)
	(receptacleatlocation receptacle24_toilet location_xpos19_ypos14_place40_room2_floorb)
	(receptacleatlocation receptacle39_sink location_xpos30_ypos19_place50_room1_floora)
	(roomplace place0_door_room5_bedroom room5_bedroom)
	(roomplace place10_door_room4_bathroom room4_bathroom)
	(roomplace place11_door_room3_bathroom room3_bathroom)
	(roomplace place12_door_room16_staircase room16_staircase)
	(roomplace place13_door_room8_corridor room8_corridor)
	(roomplace place14_door_room9_corridor room9_corridor)
	(roomplace place15_door_room15_staircase room15_staircase)
	(roomplace place1_door_room11_home_office room11_home_office)
	(roomplace place2_door_room7_corridor room7_corridor)
	(roomplace place3_door_room12_kitchen room12_kitchen)
	(roomplace place4_door_room14_lobby room14_lobby)
	(roomplace place5_door_room10_dining_room room10_dining_room)
	(roomplace place6_door_room6_bedroom room6_bedroom)
	(roomplace place7_door_room13_living_room room13_living_room)
	(roomplace place8_door_room2_bathroom room2_bathroom)
	(roomplace place9_door_room1_bathroom room1_bathroom)
	(roomsconnected room10_dining_room room12_kitchen)
	(roomsconnected room10_dining_room room8_corridor)
	(roomsconnected room11_home_office room4_bathroom)
	(roomsconnected room12_kitchen room10_dining_room)
	(roomsconnected room12_kitchen room2_bathroom)
	(roomsconnected room13_living_room room8_corridor)
	(roomsconnected room14_lobby room7_corridor)
	(roomsconnected room15_staircase room7_corridor)
	(roomsconnected room15_staircase room8_corridor)
	(roomsconnected room16_staircase room8_corridor)
	(roomsconnected room16_staircase room9_corridor)
	(roomsconnected room1_bathroom room5_bedroom)
	(roomsconnected room2_bathroom room12_kitchen)
	(roomsconnected room3_bathroom room9_corridor)
	(roomsconnected room4_bathroom room11_home_office)
	(roomsconnected room4_bathroom room6_bedroom)
	(roomsconnected room4_bathroom room9_corridor)
	(roomsconnected room5_bedroom room1_bathroom)
	(roomsconnected room5_bedroom room7_corridor)
	(roomsconnected room6_bedroom room4_bathroom)
	(roomsconnected room7_corridor room14_lobby)
	(roomsconnected room7_corridor room15_staircase)
	(roomsconnected room7_corridor room5_bedroom)
	(roomsconnected room8_corridor room10_dining_room)
	(roomsconnected room8_corridor room13_living_room)
	(roomsconnected room8_corridor room15_staircase)
	(roomsconnected room8_corridor room16_staircase)
	(roomsconnected room9_corridor room16_staircase)
	(roomsconnected room9_corridor room3_bathroom)
	(roomsconnected room9_corridor room4_bathroom)
  )
  (:goal (and
	(inreceptacle item45_clock_mediumitem receptacle39_sink)
	(inreceptacle item29_tv_largeitem receptacle24_toilet)))
)
