
(define (problem NoxapaterTaskographyv4Tiny5Problem25) (:domain taskographyv4tiny5)
  (:objects
        apple - iclass
	backpack - iclass
	banana - iclass
	baseballbat - iclass
	baseballglove - iclass
	bed - rclass
	bench - rclass
	bicycle - iclass
	boat - rclass
	book - iclass
	bottle - iclass
	bowl - iclass
	cake - iclass
	cellphone - iclass
	chair - rclass
	clock - iclass
	couch - rclass
	cup - iclass
	diningtable - rclass
	frisbee - iclass
	handbag - iclass
	item29_potted_plant_largeitem - item
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item6_book_smallitem - item
	item7_book_smallitem - item
	item8_bottle_smallitem - item
	keyboard - iclass
	kite - iclass
	knife - iclass
	laptop - iclass
	location_Xneg12_Ypos2_place5_room2_floorA - location
	location_Xneg19_Yneg14_place3_room9_floorB - location
	location_Xneg19_Yneg15_place35_room9_floorB - location
	location_Xneg19_Ypos17_place24_room9_floorB - location
	location_Xneg24_Ypos3_place36_room2_floorA - location
	location_Xneg30_Yneg4_place35_room9_floorB - location
	location_Xneg32_Yneg18_place35_room9_floorB - location
	location_Xneg4_Ypos6_place23_room9_floorB - location
	location_Xneg5_Ypos7_place24_room9_floorB - location
	location_Xneg6_Ypos5_place22_room9_floorB - location
	location_Xpos10_Ypos18_place12_room8_floorB - location
	location_Xpos11_Yneg30_place32_room5_floorA - location
	location_Xpos12_Yneg28_place27_room5_floorA - location
	location_Xpos13_Yneg33_place34_room5_floorA - location
	location_Xpos15_Yneg34_place4_room5_floorA - location
	location_Xpos16_Yneg37_place28_room5_floorA - location
	location_Xpos16_Yneg3_place11_room8_floorB - location
	location_Xpos17_Yneg34_place37_room5_floorA - location
	location_Xpos17_Yneg39_place30_room5_floorA - location
	location_Xpos19_Yneg32_place25_room5_floorA - location
	location_Xpos19_Yneg36_place33_room5_floorA - location
	location_Xpos1_Yneg44_place29_room5_floorA - location
	location_Xpos20_Yneg39_place31_room5_floorA - location
	location_Xpos23_Ypos26_place17_room8_floorB - location
	location_Xpos23_Ypos9_place0_room8_floorB - location
	location_Xpos24_Ypos21_place18_room8_floorB - location
	location_Xpos28_Ypos25_place38_room8_floorB - location
	location_Xpos28_Ypos27_place38_room8_floorB - location
	location_Xpos28_Ypos4_place6_room3_floorA - location
	location_Xpos29_Ypos30_place21_room8_floorB - location
	location_Xpos30_Yneg2_place15_room8_floorB - location
	location_Xpos31_Yneg46_place31_room5_floorA - location
	location_Xpos32_Yneg47_place31_room5_floorA - location
	location_Xpos32_Ypos22_place20_room8_floorB - location
	location_Xpos33_Ypos26_place19_room8_floorB - location
	location_Xpos34_Yneg13_place7_room4_floorB - location
	location_Xpos3_Yneg44_place26_room5_floorA - location
	location_Xpos46_Yneg32_place8_room6_floorA - location
	location_Xpos54_Yneg34_place9_room7_floorB - location
	location_Xpos57_Ypos3_place2_room11_floorA - location
	location_Xpos59_Yneg10_place13_room1_floorB - location
	location_Xpos60_Yneg3_place1_room1_floorB - location
	location_Xpos60_Ypos12_place10_room10_floorA - location
	location_Xpos61_Yneg10_place14_room11_floorA - location
	location_Xpos61_Yneg9_place13_room1_floorB - location
	location_Xpos68_Yneg7_place16_room1_floorB - location
	microwave - rclass
	motorcycle - iclass
	mouse - iclass
	orange - iclass
	oven - rclass
	place0_door_room8_kitchen - place
	place10_door_room10_staircase - place
	place11_receptacle1_oven - place
	place12_receptacle2_sink - place
	place13_receptacle3_sink - place
	place14_receptacle4_sink - place
	place15_receptacle5_refrigerator - place
	place16_receptacle9_toilet - place
	place17_receptacle10_chair - place
	place18_receptacle11_chair - place
	place19_receptacle12_chair - place
	place1_door_room1_bathroom - place
	place20_receptacle13_chair - place
	place21_receptacle14_chair - place
	place22_receptacle15_chair - place
	place23_receptacle16_chair - place
	place24_receptacle17_chair - place
	place25_receptacle18_chair - place
	place26_receptacle19_chair - place
	place27_receptacle20_chair - place
	place28_receptacle21_chair - place
	place29_receptacle22_chair - place
	place2_door_room11_utility_room - place
	place30_receptacle23_chair - place
	place31_receptacle24_chair - place
	place32_receptacle25_chair - place
	place33_receptacle26_chair - place
	place34_receptacle27_chair - place
	place35_receptacle28_couch - place
	place36_receptacle33_bed - place
	place37_receptacle34_dining_table - place
	place38_receptacle35_dining_table - place
	place3_door_room9_living_room - place
	place4_door_room5_dining_room - place
	place5_door_room2_bedroom - place
	place6_door_room3_corridor - place
	place7_door_room4_corridor - place
	place8_door_room6_empty_room - place
	place9_door_room7_empty_room - place
	pottedplant - iclass
	receptacle10_chair - receptacle
	receptacle11_chair - receptacle
	receptacle12_chair - receptacle
	receptacle13_chair - receptacle
	receptacle14_chair - receptacle
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle1_oven - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_couch - receptacle
	receptacle2_sink - receptacle
	receptacle33_bed - receptacle
	receptacle34_dining_table - receptacle
	receptacle35_dining_table - receptacle
	receptacle3_sink - receptacle
	receptacle4_sink - receptacle
	receptacle5_refrigerator - receptacle
	receptacle9_toilet - receptacle
	refrigerator - rclass
	remote - iclass
	robot - agent
	room10_staircase - room
	room11_utility_room - room
	room1_bathroom - room
	room2_bedroom - room
	room3_corridor - room
	room4_corridor - room
	room5_dining_room - room
	room6_empty_room - room
	room7_empty_room - room
	room8_kitchen - room
	room9_living_room - room
	sink - rclass
	spoon - iclass
	sportsball - iclass
	suitcase - iclass
	surfboard - iclass
	teddybear - iclass
	tie - iclass
	toaster - rclass
	toilet - rclass
	toothbrush - iclass
	tv - iclass
	umbrella - iclass
	vase - iclass
	wineglass - iclass
  )
  (:init 
	(atlocation robot location_Xpos57_Ypos3_place2_room11_floorA)
	(classrelation book couch)
	(classrelation bottle sink)
	(classrelation pottedplant chair)
	(classrelation pottedplant diningtable)
	(inanyreceptacle item29_potted_plant_largeitem)
	(inanyreceptacle item30_potted_plant_largeitem)
	(inanyreceptacle item31_potted_plant_largeitem)
	(inanyreceptacle item32_potted_plant_largeitem)
	(inanyreceptacle item6_book_smallitem)
	(inanyreceptacle item7_book_smallitem)
	(inanyreceptacle item8_bottle_smallitem)
	(inplace robot place2_door_room11_utility_room)
	(inreceptacle item29_potted_plant_largeitem receptacle35_dining_table)
	(inreceptacle item30_potted_plant_largeitem receptacle17_chair)
	(inreceptacle item31_potted_plant_largeitem receptacle24_chair)
	(inreceptacle item32_potted_plant_largeitem receptacle24_chair)
	(inreceptacle item6_book_smallitem receptacle28_couch)
	(inreceptacle item7_book_smallitem receptacle28_couch)
	(inreceptacle item8_bottle_smallitem receptacle3_sink)
	(inroom robot room11_utility_room)
	(itematlocation item29_potted_plant_largeitem location_Xpos28_Ypos27_place38_room8_floorB)
	(itematlocation item30_potted_plant_largeitem location_Xneg19_Ypos17_place24_room9_floorB)
	(itematlocation item31_potted_plant_largeitem location_Xpos31_Yneg46_place31_room5_floorA)
	(itematlocation item32_potted_plant_largeitem location_Xpos32_Yneg47_place31_room5_floorA)
	(itematlocation item6_book_smallitem location_Xneg19_Yneg15_place35_room9_floorB)
	(itematlocation item7_book_smallitem location_Xneg30_Yneg4_place35_room9_floorB)
	(itematlocation item8_bottle_smallitem location_Xpos59_Yneg10_place13_room1_floorB)
	(itemclass item29_potted_plant_largeitem pottedplant)
	(itemclass item30_potted_plant_largeitem pottedplant)
	(itemclass item31_potted_plant_largeitem pottedplant)
	(itemclass item32_potted_plant_largeitem pottedplant)
	(itemclass item6_book_smallitem book)
	(itemclass item7_book_smallitem book)
	(itemclass item8_bottle_smallitem bottle)
	(locationinplace location_Xneg12_Ypos2_place5_room2_floorA place5_door_room2_bedroom)
	(locationinplace location_Xneg19_Yneg14_place3_room9_floorB place3_door_room9_living_room)
	(locationinplace location_Xneg19_Yneg15_place35_room9_floorB place35_receptacle28_couch)
	(locationinplace location_Xneg19_Ypos17_place24_room9_floorB place24_receptacle17_chair)
	(locationinplace location_Xneg24_Ypos3_place36_room2_floorA place36_receptacle33_bed)
	(locationinplace location_Xneg30_Yneg4_place35_room9_floorB place35_receptacle28_couch)
	(locationinplace location_Xneg32_Yneg18_place35_room9_floorB place35_receptacle28_couch)
	(locationinplace location_Xneg4_Ypos6_place23_room9_floorB place23_receptacle16_chair)
	(locationinplace location_Xneg5_Ypos7_place24_room9_floorB place24_receptacle17_chair)
	(locationinplace location_Xneg6_Ypos5_place22_room9_floorB place22_receptacle15_chair)
	(locationinplace location_Xpos10_Ypos18_place12_room8_floorB place12_receptacle2_sink)
	(locationinplace location_Xpos11_Yneg30_place32_room5_floorA place32_receptacle25_chair)
	(locationinplace location_Xpos12_Yneg28_place27_room5_floorA place27_receptacle20_chair)
	(locationinplace location_Xpos13_Yneg33_place34_room5_floorA place34_receptacle27_chair)
	(locationinplace location_Xpos15_Yneg34_place4_room5_floorA place4_door_room5_dining_room)
	(locationinplace location_Xpos16_Yneg37_place28_room5_floorA place28_receptacle21_chair)
	(locationinplace location_Xpos16_Yneg3_place11_room8_floorB place11_receptacle1_oven)
	(locationinplace location_Xpos17_Yneg34_place37_room5_floorA place37_receptacle34_dining_table)
	(locationinplace location_Xpos17_Yneg39_place30_room5_floorA place30_receptacle23_chair)
	(locationinplace location_Xpos19_Yneg32_place25_room5_floorA place25_receptacle18_chair)
	(locationinplace location_Xpos19_Yneg36_place33_room5_floorA place33_receptacle26_chair)
	(locationinplace location_Xpos1_Yneg44_place29_room5_floorA place29_receptacle22_chair)
	(locationinplace location_Xpos20_Yneg39_place31_room5_floorA place31_receptacle24_chair)
	(locationinplace location_Xpos23_Ypos26_place17_room8_floorB place17_receptacle10_chair)
	(locationinplace location_Xpos23_Ypos9_place0_room8_floorB place0_door_room8_kitchen)
	(locationinplace location_Xpos24_Ypos21_place18_room8_floorB place18_receptacle11_chair)
	(locationinplace location_Xpos28_Ypos25_place38_room8_floorB place38_receptacle35_dining_table)
	(locationinplace location_Xpos28_Ypos27_place38_room8_floorB place38_receptacle35_dining_table)
	(locationinplace location_Xpos28_Ypos4_place6_room3_floorA place6_door_room3_corridor)
	(locationinplace location_Xpos29_Ypos30_place21_room8_floorB place21_receptacle14_chair)
	(locationinplace location_Xpos30_Yneg2_place15_room8_floorB place15_receptacle5_refrigerator)
	(locationinplace location_Xpos31_Yneg46_place31_room5_floorA place31_receptacle24_chair)
	(locationinplace location_Xpos32_Yneg47_place31_room5_floorA place31_receptacle24_chair)
	(locationinplace location_Xpos32_Ypos22_place20_room8_floorB place20_receptacle13_chair)
	(locationinplace location_Xpos33_Ypos26_place19_room8_floorB place19_receptacle12_chair)
	(locationinplace location_Xpos34_Yneg13_place7_room4_floorB place7_door_room4_corridor)
	(locationinplace location_Xpos3_Yneg44_place26_room5_floorA place26_receptacle19_chair)
	(locationinplace location_Xpos46_Yneg32_place8_room6_floorA place8_door_room6_empty_room)
	(locationinplace location_Xpos54_Yneg34_place9_room7_floorB place9_door_room7_empty_room)
	(locationinplace location_Xpos57_Ypos3_place2_room11_floorA place2_door_room11_utility_room)
	(locationinplace location_Xpos59_Yneg10_place13_room1_floorB place13_receptacle3_sink)
	(locationinplace location_Xpos60_Yneg3_place1_room1_floorB place1_door_room1_bathroom)
	(locationinplace location_Xpos60_Ypos12_place10_room10_floorA place10_door_room10_staircase)
	(locationinplace location_Xpos61_Yneg10_place14_room11_floorA place14_receptacle4_sink)
	(locationinplace location_Xpos61_Yneg9_place13_room1_floorB place13_receptacle3_sink)
	(locationinplace location_Xpos68_Yneg7_place16_room1_floorB place16_receptacle9_toilet)
	(placeinroom place0_door_room8_kitchen room8_kitchen)
	(placeinroom place10_door_room10_staircase room10_staircase)
	(placeinroom place11_receptacle1_oven room8_kitchen)
	(placeinroom place12_receptacle2_sink room8_kitchen)
	(placeinroom place13_receptacle3_sink room1_bathroom)
	(placeinroom place14_receptacle4_sink room11_utility_room)
	(placeinroom place15_receptacle5_refrigerator room8_kitchen)
	(placeinroom place16_receptacle9_toilet room1_bathroom)
	(placeinroom place17_receptacle10_chair room8_kitchen)
	(placeinroom place18_receptacle11_chair room8_kitchen)
	(placeinroom place19_receptacle12_chair room8_kitchen)
	(placeinroom place1_door_room1_bathroom room1_bathroom)
	(placeinroom place20_receptacle13_chair room8_kitchen)
	(placeinroom place21_receptacle14_chair room8_kitchen)
	(placeinroom place22_receptacle15_chair room9_living_room)
	(placeinroom place23_receptacle16_chair room9_living_room)
	(placeinroom place24_receptacle17_chair room9_living_room)
	(placeinroom place25_receptacle18_chair room5_dining_room)
	(placeinroom place26_receptacle19_chair room5_dining_room)
	(placeinroom place27_receptacle20_chair room5_dining_room)
	(placeinroom place28_receptacle21_chair room5_dining_room)
	(placeinroom place29_receptacle22_chair room5_dining_room)
	(placeinroom place2_door_room11_utility_room room11_utility_room)
	(placeinroom place30_receptacle23_chair room5_dining_room)
	(placeinroom place31_receptacle24_chair room5_dining_room)
	(placeinroom place32_receptacle25_chair room5_dining_room)
	(placeinroom place33_receptacle26_chair room5_dining_room)
	(placeinroom place34_receptacle27_chair room5_dining_room)
	(placeinroom place35_receptacle28_couch room9_living_room)
	(placeinroom place36_receptacle33_bed room2_bedroom)
	(placeinroom place37_receptacle34_dining_table room5_dining_room)
	(placeinroom place38_receptacle35_dining_table room8_kitchen)
	(placeinroom place3_door_room9_living_room room9_living_room)
	(placeinroom place4_door_room5_dining_room room5_dining_room)
	(placeinroom place5_door_room2_bedroom room2_bedroom)
	(placeinroom place6_door_room3_corridor room3_corridor)
	(placeinroom place7_door_room4_corridor room4_corridor)
	(placeinroom place8_door_room6_empty_room room6_empty_room)
	(placeinroom place9_door_room7_empty_room room7_empty_room)
	(placelocation location_Xneg12_Ypos2_place5_room2_floorA place5_door_room2_bedroom)
	(placelocation location_Xneg19_Yneg14_place3_room9_floorB place3_door_room9_living_room)
	(placelocation location_Xneg24_Ypos3_place36_room2_floorA place36_receptacle33_bed)
	(placelocation location_Xneg32_Yneg18_place35_room9_floorB place35_receptacle28_couch)
	(placelocation location_Xneg4_Ypos6_place23_room9_floorB place23_receptacle16_chair)
	(placelocation location_Xneg5_Ypos7_place24_room9_floorB place24_receptacle17_chair)
	(placelocation location_Xneg6_Ypos5_place22_room9_floorB place22_receptacle15_chair)
	(placelocation location_Xpos10_Ypos18_place12_room8_floorB place12_receptacle2_sink)
	(placelocation location_Xpos11_Yneg30_place32_room5_floorA place32_receptacle25_chair)
	(placelocation location_Xpos12_Yneg28_place27_room5_floorA place27_receptacle20_chair)
	(placelocation location_Xpos13_Yneg33_place34_room5_floorA place34_receptacle27_chair)
	(placelocation location_Xpos15_Yneg34_place4_room5_floorA place4_door_room5_dining_room)
	(placelocation location_Xpos16_Yneg37_place28_room5_floorA place28_receptacle21_chair)
	(placelocation location_Xpos16_Yneg3_place11_room8_floorB place11_receptacle1_oven)
	(placelocation location_Xpos17_Yneg34_place37_room5_floorA place37_receptacle34_dining_table)
	(placelocation location_Xpos17_Yneg39_place30_room5_floorA place30_receptacle23_chair)
	(placelocation location_Xpos19_Yneg32_place25_room5_floorA place25_receptacle18_chair)
	(placelocation location_Xpos19_Yneg36_place33_room5_floorA place33_receptacle26_chair)
	(placelocation location_Xpos1_Yneg44_place29_room5_floorA place29_receptacle22_chair)
	(placelocation location_Xpos20_Yneg39_place31_room5_floorA place31_receptacle24_chair)
	(placelocation location_Xpos23_Ypos26_place17_room8_floorB place17_receptacle10_chair)
	(placelocation location_Xpos23_Ypos9_place0_room8_floorB place0_door_room8_kitchen)
	(placelocation location_Xpos24_Ypos21_place18_room8_floorB place18_receptacle11_chair)
	(placelocation location_Xpos28_Ypos25_place38_room8_floorB place38_receptacle35_dining_table)
	(placelocation location_Xpos28_Ypos4_place6_room3_floorA place6_door_room3_corridor)
	(placelocation location_Xpos29_Ypos30_place21_room8_floorB place21_receptacle14_chair)
	(placelocation location_Xpos30_Yneg2_place15_room8_floorB place15_receptacle5_refrigerator)
	(placelocation location_Xpos32_Ypos22_place20_room8_floorB place20_receptacle13_chair)
	(placelocation location_Xpos33_Ypos26_place19_room8_floorB place19_receptacle12_chair)
	(placelocation location_Xpos34_Yneg13_place7_room4_floorB place7_door_room4_corridor)
	(placelocation location_Xpos3_Yneg44_place26_room5_floorA place26_receptacle19_chair)
	(placelocation location_Xpos46_Yneg32_place8_room6_floorA place8_door_room6_empty_room)
	(placelocation location_Xpos54_Yneg34_place9_room7_floorB place9_door_room7_empty_room)
	(placelocation location_Xpos57_Ypos3_place2_room11_floorA place2_door_room11_utility_room)
	(placelocation location_Xpos60_Yneg3_place1_room1_floorB place1_door_room1_bathroom)
	(placelocation location_Xpos60_Ypos12_place10_room10_floorA place10_door_room10_staircase)
	(placelocation location_Xpos61_Yneg10_place14_room11_floorA place14_receptacle4_sink)
	(placelocation location_Xpos61_Yneg9_place13_room1_floorB place13_receptacle3_sink)
	(placelocation location_Xpos68_Yneg7_place16_room1_floorB place16_receptacle9_toilet)
	(receptacleatlocation receptacle10_chair location_Xpos23_Ypos26_place17_room8_floorB)
	(receptacleatlocation receptacle11_chair location_Xpos24_Ypos21_place18_room8_floorB)
	(receptacleatlocation receptacle12_chair location_Xpos33_Ypos26_place19_room8_floorB)
	(receptacleatlocation receptacle13_chair location_Xpos32_Ypos22_place20_room8_floorB)
	(receptacleatlocation receptacle14_chair location_Xpos29_Ypos30_place21_room8_floorB)
	(receptacleatlocation receptacle15_chair location_Xneg6_Ypos5_place22_room9_floorB)
	(receptacleatlocation receptacle16_chair location_Xneg4_Ypos6_place23_room9_floorB)
	(receptacleatlocation receptacle17_chair location_Xneg5_Ypos7_place24_room9_floorB)
	(receptacleatlocation receptacle18_chair location_Xpos19_Yneg32_place25_room5_floorA)
	(receptacleatlocation receptacle19_chair location_Xpos3_Yneg44_place26_room5_floorA)
	(receptacleatlocation receptacle1_oven location_Xpos16_Yneg3_place11_room8_floorB)
	(receptacleatlocation receptacle20_chair location_Xpos12_Yneg28_place27_room5_floorA)
	(receptacleatlocation receptacle21_chair location_Xpos16_Yneg37_place28_room5_floorA)
	(receptacleatlocation receptacle22_chair location_Xpos1_Yneg44_place29_room5_floorA)
	(receptacleatlocation receptacle23_chair location_Xpos17_Yneg39_place30_room5_floorA)
	(receptacleatlocation receptacle24_chair location_Xpos20_Yneg39_place31_room5_floorA)
	(receptacleatlocation receptacle25_chair location_Xpos11_Yneg30_place32_room5_floorA)
	(receptacleatlocation receptacle26_chair location_Xpos19_Yneg36_place33_room5_floorA)
	(receptacleatlocation receptacle27_chair location_Xpos13_Yneg33_place34_room5_floorA)
	(receptacleatlocation receptacle28_couch location_Xneg32_Yneg18_place35_room9_floorB)
	(receptacleatlocation receptacle2_sink location_Xpos10_Ypos18_place12_room8_floorB)
	(receptacleatlocation receptacle33_bed location_Xneg24_Ypos3_place36_room2_floorA)
	(receptacleatlocation receptacle34_dining_table location_Xpos17_Yneg34_place37_room5_floorA)
	(receptacleatlocation receptacle35_dining_table location_Xpos28_Ypos25_place38_room8_floorB)
	(receptacleatlocation receptacle3_sink location_Xpos61_Yneg9_place13_room1_floorB)
	(receptacleatlocation receptacle4_sink location_Xpos61_Yneg10_place14_room11_floorA)
	(receptacleatlocation receptacle5_refrigerator location_Xpos30_Yneg2_place15_room8_floorB)
	(receptacleatlocation receptacle9_toilet location_Xpos68_Yneg7_place16_room1_floorB)
	(receptacleclass receptacle10_chair chair)
	(receptacleclass receptacle11_chair chair)
	(receptacleclass receptacle12_chair chair)
	(receptacleclass receptacle13_chair chair)
	(receptacleclass receptacle14_chair chair)
	(receptacleclass receptacle15_chair chair)
	(receptacleclass receptacle16_chair chair)
	(receptacleclass receptacle17_chair chair)
	(receptacleclass receptacle18_chair chair)
	(receptacleclass receptacle19_chair chair)
	(receptacleclass receptacle1_oven oven)
	(receptacleclass receptacle20_chair chair)
	(receptacleclass receptacle21_chair chair)
	(receptacleclass receptacle22_chair chair)
	(receptacleclass receptacle23_chair chair)
	(receptacleclass receptacle24_chair chair)
	(receptacleclass receptacle25_chair chair)
	(receptacleclass receptacle26_chair chair)
	(receptacleclass receptacle27_chair chair)
	(receptacleclass receptacle28_couch couch)
	(receptacleclass receptacle2_sink sink)
	(receptacleclass receptacle33_bed bed)
	(receptacleclass receptacle34_dining_table diningtable)
	(receptacleclass receptacle35_dining_table diningtable)
	(receptacleclass receptacle3_sink sink)
	(receptacleclass receptacle4_sink sink)
	(receptacleclass receptacle5_refrigerator refrigerator)
	(receptacleclass receptacle9_toilet toilet)
	(receptacleopeningtype receptacle1_oven)
	(receptacleopeningtype receptacle5_refrigerator)
	(roomplace place0_door_room8_kitchen room8_kitchen)
	(roomplace place10_door_room10_staircase room10_staircase)
	(roomplace place1_door_room1_bathroom room1_bathroom)
	(roomplace place2_door_room11_utility_room room11_utility_room)
	(roomplace place3_door_room9_living_room room9_living_room)
	(roomplace place4_door_room5_dining_room room5_dining_room)
	(roomplace place5_door_room2_bedroom room2_bedroom)
	(roomplace place6_door_room3_corridor room3_corridor)
	(roomplace place7_door_room4_corridor room4_corridor)
	(roomplace place8_door_room6_empty_room room6_empty_room)
	(roomplace place9_door_room7_empty_room room7_empty_room)
	(roomsconnected room10_staircase room11_utility_room)
	(roomsconnected room10_staircase room1_bathroom)
	(roomsconnected room11_utility_room room10_staircase)
	(roomsconnected room11_utility_room room3_corridor)
	(roomsconnected room11_utility_room room6_empty_room)
	(roomsconnected room1_bathroom room10_staircase)
	(roomsconnected room1_bathroom room4_corridor)
	(roomsconnected room2_bedroom room3_corridor)
	(roomsconnected room3_corridor room11_utility_room)
	(roomsconnected room3_corridor room2_bedroom)
	(roomsconnected room4_corridor room1_bathroom)
	(roomsconnected room4_corridor room7_empty_room)
	(roomsconnected room4_corridor room8_kitchen)
	(roomsconnected room5_dining_room room6_empty_room)
	(roomsconnected room6_empty_room room11_utility_room)
	(roomsconnected room6_empty_room room5_dining_room)
	(roomsconnected room7_empty_room room4_corridor)
	(roomsconnected room8_kitchen room4_corridor)
	(roomsconnected room8_kitchen room9_living_room)
	(roomsconnected room9_living_room room8_kitchen)
  )
  (:goal (and
	(classrelation book chair)
	(classrelation bottle chair)
	(classrelation pottedplant sink)
	(classrelation book sink)
	(classrelation pottedplant oven)))
)
