
(define (problem ShelbianaTaskographyv4Medium5Problem184) (:domain taskographyv4medium5)
  (:objects
        apple - iclass
	backpack - iclass
	banana - iclass
	baseballbat - iclass
	baseballglove - iclass
	bed - rclass
	bench - rclass
	bicycle - iclass
	boat - rclass
	book - iclass
	bottle - iclass
	bowl - iclass
	cake - iclass
	cellphone - iclass
	chair - rclass
	clock - iclass
	couch - rclass
	cup - iclass
	diningtable - rclass
	frisbee - iclass
	handbag - iclass
	item14_clock_mediumitem - item
	item15_clock_mediumitem - item
	item1_kite_largeitem - item
	item2_kite_largeitem - item
	item3_kite_largeitem - item
	keyboard - iclass
	kite - iclass
	knife - iclass
	laptop - iclass
	location_Xneg12_Yneg1_place20_room11_floorA - location
	location_Xneg13_Ypos48_place10_room6_floorA - location
	location_Xneg19_Ypos17_place18_room11_floorA - location
	location_Xneg19_Ypos9_place2_room11_floorA - location
	location_Xneg27_Ypos7_place16_room11_floorA - location
	location_Xneg28_Ypos7_place15_room11_floorA - location
	location_Xneg39_Ypos20_place8_room4_floorA - location
	location_Xneg47_Ypos50_place5_room7_floorA - location
	location_Xneg49_Ypos28_place19_room1_floorA - location
	location_Xneg54_Ypos12_place22_room1_floorA - location
	location_Xneg54_Ypos17_place4_room1_floorA - location
	location_Xneg57_Ypos36_place21_room7_floorA - location
	location_Xneg58_Ypos16_place25_room1_floorA - location
	location_Xneg59_Ypos24_place19_room1_floorA - location
	location_Xpos14_Yneg5_place27_room3_floorA - location
	location_Xpos17_Ypos11_place9_room5_floorA - location
	location_Xpos17_Ypos36_place26_room2_floorA - location
	location_Xpos18_Ypos29_place3_room2_floorA - location
	location_Xpos18_Ypos61_place7_room10_floorA - location
	location_Xpos20_Ypos2_place6_room3_floorA - location
	location_Xpos27_Ypos24_place17_room2_floorA - location
	location_Xpos31_Yneg3_place23_room3_floorA - location
	location_Xpos45_Ypos28_place24_room8_floorA - location
	location_Xpos48_Ypos52_place0_room9_floorA - location
	location_Xpos50_Ypos75_place12_room9_floorA - location
	location_Xpos51_Ypos13_place1_room8_floorA - location
	location_Xpos60_Yneg6_place13_room8_floorA - location
	location_Xpos66_Ypos58_place11_room9_floorA - location
	location_Xpos9_Ypos61_place14_room10_floorA - location
	microwave - rclass
	motorcycle - iclass
	mouse - iclass
	orange - iclass
	oven - rclass
	place0_door_room9_empty_room - place
	place10_door_room6_empty_room - place
	place11_item1_kite - place
	place12_item2_kite - place
	place13_item3_kite - place
	place14_item14_clock - place
	place15_receptacle4_microwave - place
	place16_receptacle5_oven - place
	place17_receptacle6_sink - place
	place18_receptacle7_sink - place
	place19_receptacle8_sink - place
	place1_door_room8_empty_room - place
	place20_receptacle9_refrigerator - place
	place21_receptacle10_refrigerator - place
	place22_receptacle11_refrigerator - place
	place23_receptacle12_refrigerator - place
	place24_receptacle13_refrigerator - place
	place25_receptacle16_toilet - place
	place26_receptacle17_toilet - place
	place27_receptacle18_chair - place
	place2_door_room11_kitchen - place
	place3_door_room2_bathroom - place
	place4_door_room1_bathroom - place
	place5_door_room7_empty_room - place
	place6_door_room3_closet - place
	place7_door_room10_empty_room - place
	place8_door_room4_corridor - place
	place9_door_room5_corridor - place
	pottedplant - iclass
	receptacle10_refrigerator - receptacle
	receptacle11_refrigerator - receptacle
	receptacle12_refrigerator - receptacle
	receptacle13_refrigerator - receptacle
	receptacle16_toilet - receptacle
	receptacle17_toilet - receptacle
	receptacle18_chair - receptacle
	receptacle4_microwave - receptacle
	receptacle5_oven - receptacle
	receptacle6_sink - receptacle
	receptacle7_sink - receptacle
	receptacle8_sink - receptacle
	receptacle9_refrigerator - receptacle
	refrigerator - rclass
	remote - iclass
	robot - agent
	room10_empty_room - room
	room11_kitchen - room
	room1_bathroom - room
	room2_bathroom - room
	room3_closet - room
	room4_corridor - room
	room5_corridor - room
	room6_empty_room - room
	room7_empty_room - room
	room8_empty_room - room
	room9_empty_room - room
	sink - rclass
	spoon - iclass
	sportsball - iclass
	suitcase - iclass
	surfboard - iclass
	teddybear - iclass
	tie - iclass
	toaster - rclass
	toilet - rclass
	toothbrush - iclass
	tv - iclass
	umbrella - iclass
	vase - iclass
	wineglass - iclass
  )
  (:init 
	(atlocation robot location_Xneg54_Ypos17_place4_room1_floorA)
	(classrelation clock sink)
	(inanyreceptacle item15_clock_mediumitem)
	(inplace robot place4_door_room1_bathroom)
	(inreceptacle item15_clock_mediumitem receptacle8_sink)
	(inroom robot room1_bathroom)
	(itematlocation item14_clock_mediumitem location_Xpos9_Ypos61_place14_room10_floorA)
	(itematlocation item15_clock_mediumitem location_Xneg49_Ypos28_place19_room1_floorA)
	(itematlocation item1_kite_largeitem location_Xpos66_Ypos58_place11_room9_floorA)
	(itematlocation item2_kite_largeitem location_Xpos50_Ypos75_place12_room9_floorA)
	(itematlocation item3_kite_largeitem location_Xpos60_Yneg6_place13_room8_floorA)
	(itemclass item14_clock_mediumitem clock)
	(itemclass item15_clock_mediumitem clock)
	(itemclass item1_kite_largeitem kite)
	(itemclass item2_kite_largeitem kite)
	(itemclass item3_kite_largeitem kite)
	(locationinplace location_Xneg12_Yneg1_place20_room11_floorA place20_receptacle9_refrigerator)
	(locationinplace location_Xneg13_Ypos48_place10_room6_floorA place10_door_room6_empty_room)
	(locationinplace location_Xneg19_Ypos17_place18_room11_floorA place18_receptacle7_sink)
	(locationinplace location_Xneg19_Ypos9_place2_room11_floorA place2_door_room11_kitchen)
	(locationinplace location_Xneg27_Ypos7_place16_room11_floorA place16_receptacle5_oven)
	(locationinplace location_Xneg28_Ypos7_place15_room11_floorA place15_receptacle4_microwave)
	(locationinplace location_Xneg39_Ypos20_place8_room4_floorA place8_door_room4_corridor)
	(locationinplace location_Xneg47_Ypos50_place5_room7_floorA place5_door_room7_empty_room)
	(locationinplace location_Xneg49_Ypos28_place19_room1_floorA place19_receptacle8_sink)
	(locationinplace location_Xneg54_Ypos12_place22_room1_floorA place22_receptacle11_refrigerator)
	(locationinplace location_Xneg54_Ypos17_place4_room1_floorA place4_door_room1_bathroom)
	(locationinplace location_Xneg57_Ypos36_place21_room7_floorA place21_receptacle10_refrigerator)
	(locationinplace location_Xneg58_Ypos16_place25_room1_floorA place25_receptacle16_toilet)
	(locationinplace location_Xneg59_Ypos24_place19_room1_floorA place19_receptacle8_sink)
	(locationinplace location_Xpos14_Yneg5_place27_room3_floorA place27_receptacle18_chair)
	(locationinplace location_Xpos17_Ypos11_place9_room5_floorA place9_door_room5_corridor)
	(locationinplace location_Xpos17_Ypos36_place26_room2_floorA place26_receptacle17_toilet)
	(locationinplace location_Xpos18_Ypos29_place3_room2_floorA place3_door_room2_bathroom)
	(locationinplace location_Xpos18_Ypos61_place7_room10_floorA place7_door_room10_empty_room)
	(locationinplace location_Xpos20_Ypos2_place6_room3_floorA place6_door_room3_closet)
	(locationinplace location_Xpos27_Ypos24_place17_room2_floorA place17_receptacle6_sink)
	(locationinplace location_Xpos31_Yneg3_place23_room3_floorA place23_receptacle12_refrigerator)
	(locationinplace location_Xpos45_Ypos28_place24_room8_floorA place24_receptacle13_refrigerator)
	(locationinplace location_Xpos48_Ypos52_place0_room9_floorA place0_door_room9_empty_room)
	(locationinplace location_Xpos50_Ypos75_place12_room9_floorA place12_item2_kite)
	(locationinplace location_Xpos51_Ypos13_place1_room8_floorA place1_door_room8_empty_room)
	(locationinplace location_Xpos60_Yneg6_place13_room8_floorA place13_item3_kite)
	(locationinplace location_Xpos66_Ypos58_place11_room9_floorA place11_item1_kite)
	(locationinplace location_Xpos9_Ypos61_place14_room10_floorA place14_item14_clock)
	(placeinroom place0_door_room9_empty_room room9_empty_room)
	(placeinroom place10_door_room6_empty_room room6_empty_room)
	(placeinroom place11_item1_kite room9_empty_room)
	(placeinroom place12_item2_kite room9_empty_room)
	(placeinroom place13_item3_kite room8_empty_room)
	(placeinroom place14_item14_clock room10_empty_room)
	(placeinroom place15_receptacle4_microwave room11_kitchen)
	(placeinroom place16_receptacle5_oven room11_kitchen)
	(placeinroom place17_receptacle6_sink room2_bathroom)
	(placeinroom place18_receptacle7_sink room11_kitchen)
	(placeinroom place19_receptacle8_sink room1_bathroom)
	(placeinroom place1_door_room8_empty_room room8_empty_room)
	(placeinroom place20_receptacle9_refrigerator room11_kitchen)
	(placeinroom place21_receptacle10_refrigerator room7_empty_room)
	(placeinroom place22_receptacle11_refrigerator room1_bathroom)
	(placeinroom place23_receptacle12_refrigerator room3_closet)
	(placeinroom place24_receptacle13_refrigerator room8_empty_room)
	(placeinroom place25_receptacle16_toilet room1_bathroom)
	(placeinroom place26_receptacle17_toilet room2_bathroom)
	(placeinroom place27_receptacle18_chair room3_closet)
	(placeinroom place2_door_room11_kitchen room11_kitchen)
	(placeinroom place3_door_room2_bathroom room2_bathroom)
	(placeinroom place4_door_room1_bathroom room1_bathroom)
	(placeinroom place5_door_room7_empty_room room7_empty_room)
	(placeinroom place6_door_room3_closet room3_closet)
	(placeinroom place7_door_room10_empty_room room10_empty_room)
	(placeinroom place8_door_room4_corridor room4_corridor)
	(placeinroom place9_door_room5_corridor room5_corridor)
	(placelocation location_Xneg12_Yneg1_place20_room11_floorA place20_receptacle9_refrigerator)
	(placelocation location_Xneg13_Ypos48_place10_room6_floorA place10_door_room6_empty_room)
	(placelocation location_Xneg19_Ypos17_place18_room11_floorA place18_receptacle7_sink)
	(placelocation location_Xneg19_Ypos9_place2_room11_floorA place2_door_room11_kitchen)
	(placelocation location_Xneg27_Ypos7_place16_room11_floorA place16_receptacle5_oven)
	(placelocation location_Xneg28_Ypos7_place15_room11_floorA place15_receptacle4_microwave)
	(placelocation location_Xneg39_Ypos20_place8_room4_floorA place8_door_room4_corridor)
	(placelocation location_Xneg47_Ypos50_place5_room7_floorA place5_door_room7_empty_room)
	(placelocation location_Xneg54_Ypos12_place22_room1_floorA place22_receptacle11_refrigerator)
	(placelocation location_Xneg54_Ypos17_place4_room1_floorA place4_door_room1_bathroom)
	(placelocation location_Xneg57_Ypos36_place21_room7_floorA place21_receptacle10_refrigerator)
	(placelocation location_Xneg58_Ypos16_place25_room1_floorA place25_receptacle16_toilet)
	(placelocation location_Xneg59_Ypos24_place19_room1_floorA place19_receptacle8_sink)
	(placelocation location_Xpos14_Yneg5_place27_room3_floorA place27_receptacle18_chair)
	(placelocation location_Xpos17_Ypos11_place9_room5_floorA place9_door_room5_corridor)
	(placelocation location_Xpos17_Ypos36_place26_room2_floorA place26_receptacle17_toilet)
	(placelocation location_Xpos18_Ypos29_place3_room2_floorA place3_door_room2_bathroom)
	(placelocation location_Xpos18_Ypos61_place7_room10_floorA place7_door_room10_empty_room)
	(placelocation location_Xpos20_Ypos2_place6_room3_floorA place6_door_room3_closet)
	(placelocation location_Xpos27_Ypos24_place17_room2_floorA place17_receptacle6_sink)
	(placelocation location_Xpos31_Yneg3_place23_room3_floorA place23_receptacle12_refrigerator)
	(placelocation location_Xpos45_Ypos28_place24_room8_floorA place24_receptacle13_refrigerator)
	(placelocation location_Xpos48_Ypos52_place0_room9_floorA place0_door_room9_empty_room)
	(placelocation location_Xpos50_Ypos75_place12_room9_floorA place12_item2_kite)
	(placelocation location_Xpos51_Ypos13_place1_room8_floorA place1_door_room8_empty_room)
	(placelocation location_Xpos60_Yneg6_place13_room8_floorA place13_item3_kite)
	(placelocation location_Xpos66_Ypos58_place11_room9_floorA place11_item1_kite)
	(placelocation location_Xpos9_Ypos61_place14_room10_floorA place14_item14_clock)
	(receptacleatlocation receptacle10_refrigerator location_Xneg57_Ypos36_place21_room7_floorA)
	(receptacleatlocation receptacle11_refrigerator location_Xneg54_Ypos12_place22_room1_floorA)
	(receptacleatlocation receptacle12_refrigerator location_Xpos31_Yneg3_place23_room3_floorA)
	(receptacleatlocation receptacle13_refrigerator location_Xpos45_Ypos28_place24_room8_floorA)
	(receptacleatlocation receptacle16_toilet location_Xneg58_Ypos16_place25_room1_floorA)
	(receptacleatlocation receptacle17_toilet location_Xpos17_Ypos36_place26_room2_floorA)
	(receptacleatlocation receptacle18_chair location_Xpos14_Yneg5_place27_room3_floorA)
	(receptacleatlocation receptacle4_microwave location_Xneg28_Ypos7_place15_room11_floorA)
	(receptacleatlocation receptacle5_oven location_Xneg27_Ypos7_place16_room11_floorA)
	(receptacleatlocation receptacle6_sink location_Xpos27_Ypos24_place17_room2_floorA)
	(receptacleatlocation receptacle7_sink location_Xneg19_Ypos17_place18_room11_floorA)
	(receptacleatlocation receptacle8_sink location_Xneg59_Ypos24_place19_room1_floorA)
	(receptacleatlocation receptacle9_refrigerator location_Xneg12_Yneg1_place20_room11_floorA)
	(receptacleclass receptacle10_refrigerator refrigerator)
	(receptacleclass receptacle11_refrigerator refrigerator)
	(receptacleclass receptacle12_refrigerator refrigerator)
	(receptacleclass receptacle13_refrigerator refrigerator)
	(receptacleclass receptacle16_toilet toilet)
	(receptacleclass receptacle17_toilet toilet)
	(receptacleclass receptacle18_chair chair)
	(receptacleclass receptacle4_microwave microwave)
	(receptacleclass receptacle5_oven oven)
	(receptacleclass receptacle6_sink sink)
	(receptacleclass receptacle7_sink sink)
	(receptacleclass receptacle8_sink sink)
	(receptacleclass receptacle9_refrigerator refrigerator)
	(receptacleopeningtype receptacle10_refrigerator)
	(receptacleopeningtype receptacle11_refrigerator)
	(receptacleopeningtype receptacle12_refrigerator)
	(receptacleopeningtype receptacle13_refrigerator)
	(receptacleopeningtype receptacle4_microwave)
	(receptacleopeningtype receptacle5_oven)
	(receptacleopeningtype receptacle9_refrigerator)
	(roomplace place0_door_room9_empty_room room9_empty_room)
	(roomplace place10_door_room6_empty_room room6_empty_room)
	(roomplace place1_door_room8_empty_room room8_empty_room)
	(roomplace place2_door_room11_kitchen room11_kitchen)
	(roomplace place3_door_room2_bathroom room2_bathroom)
	(roomplace place4_door_room1_bathroom room1_bathroom)
	(roomplace place5_door_room7_empty_room room7_empty_room)
	(roomplace place6_door_room3_closet room3_closet)
	(roomplace place7_door_room10_empty_room room10_empty_room)
	(roomplace place8_door_room4_corridor room4_corridor)
	(roomplace place9_door_room5_corridor room5_corridor)
	(roomsconnected room10_empty_room room2_bathroom)
	(roomsconnected room10_empty_room room6_empty_room)
	(roomsconnected room10_empty_room room9_empty_room)
	(roomsconnected room11_kitchen room4_corridor)
	(roomsconnected room1_bathroom room4_corridor)
	(roomsconnected room2_bathroom room10_empty_room)
	(roomsconnected room2_bathroom room5_corridor)
	(roomsconnected room3_closet room5_corridor)
	(roomsconnected room3_closet room8_empty_room)
	(roomsconnected room4_corridor room11_kitchen)
	(roomsconnected room4_corridor room1_bathroom)
	(roomsconnected room4_corridor room7_empty_room)
	(roomsconnected room5_corridor room2_bathroom)
	(roomsconnected room5_corridor room3_closet)
	(roomsconnected room6_empty_room room10_empty_room)
	(roomsconnected room6_empty_room room7_empty_room)
	(roomsconnected room7_empty_room room4_corridor)
	(roomsconnected room7_empty_room room6_empty_room)
	(roomsconnected room8_empty_room room3_closet)
	(roomsconnected room9_empty_room room10_empty_room)
  )
  (:goal (and
	(classrelation kite chair)
	(classrelation kite refrigerator)
	(classrelation clock refrigerator)
	(classrelation clock toilet)
	(classrelation kite toilet)))
)
