
(define (problem ParoleTaskographyv4Medium5Problem181) (:domain taskographyv4medium5)
  (:objects
        apple - iclass
	backpack - iclass
	banana - iclass
	baseballbat - iclass
	baseballglove - iclass
	bed - rclass
	bench - rclass
	bicycle - iclass
	boat - rclass
	book - iclass
	bottle - iclass
	bowl - iclass
	cake - iclass
	cellphone - iclass
	chair - rclass
	clock - iclass
	couch - rclass
	cup - iclass
	diningtable - rclass
	frisbee - iclass
	handbag - iclass
	item15_potted_plant_largeitem - item
	item7_vase_mediumitem - item
	item8_vase_mediumitem - item
	keyboard - iclass
	kite - iclass
	knife - iclass
	laptop - iclass
	location_Xneg10_Yneg23_place19_room5_floorA - location
	location_Xneg12_Yneg19_place23_room5_floorA - location
	location_Xneg22_Yneg7_place6_room4_floorA - location
	location_Xneg36_Yneg22_place13_room1_floorA - location
	location_Xneg39_Yneg17_place1_room1_floorA - location
	location_Xneg43_Ypos17_place22_room2_floorA - location
	location_Xneg44_Ypos11_place4_room2_floorA - location
	location_Xneg47_Yneg11_place12_room1_floorA - location
	location_Xneg47_Yneg22_place16_room1_floorA - location
	location_Xneg6_Yneg16_place24_room5_floorA - location
	location_Xneg8_Yneg16_place18_room5_floorA - location
	location_Xneg8_Yneg17_place3_room5_floorA - location
	location_Xneg8_Ypos10_place5_room3_floorA - location
	location_Xpos14_Yneg21_place20_room7_floorA - location
	location_Xpos14_Ypos37_place11_room6_floorA - location
	location_Xpos15_Ypos28_place0_room6_floorA - location
	location_Xpos17_Yneg6_place2_room7_floorA - location
	location_Xpos21_Ypos18_place14_room6_floorA - location
	location_Xpos29_Yneg7_place21_room7_floorA - location
	location_Xpos29_Ypos18_place15_room6_floorA - location
	location_Xpos30_Ypos37_place10_room6_floorA - location
	location_Xpos30_Ypos8_place17_room7_floorA - location
	location_Xpos5_Ypos11_place9_room7_floorA - location
	location_Xpos5_Ypos12_place8_room7_floorA - location
	location_Xpos9_Ypos12_place7_room7_floorA - location
	microwave - rclass
	motorcycle - iclass
	mouse - iclass
	orange - iclass
	oven - rclass
	place0_door_room6_kitchen - place
	place10_receptacle1_oven - place
	place11_receptacle2_sink - place
	place12_receptacle3_sink - place
	place13_receptacle4_sink - place
	place14_receptacle5_refrigerator - place
	place15_receptacle6_refrigerator - place
	place16_receptacle9_toilet - place
	place17_receptacle10_chair - place
	place18_receptacle11_chair - place
	place19_receptacle12_chair - place
	place1_door_room1_bathroom - place
	place20_receptacle13_couch - place
	place21_receptacle14_couch - place
	place22_receptacle16_bed - place
	place23_receptacle17_dining_table - place
	place24_receptacle18_dining_table - place
	place2_door_room7_living_room - place
	place3_door_room5_dining_room - place
	place4_door_room2_bedroom - place
	place5_door_room3_corridor - place
	place6_door_room4_corridor - place
	place7_item8_vase - place
	place8_item7_vase - place
	place9_item15_potted_plant - place
	pottedplant - iclass
	receptacle10_chair - receptacle
	receptacle11_chair - receptacle
	receptacle12_chair - receptacle
	receptacle13_couch - receptacle
	receptacle14_couch - receptacle
	receptacle16_bed - receptacle
	receptacle17_dining_table - receptacle
	receptacle18_dining_table - receptacle
	receptacle1_oven - receptacle
	receptacle2_sink - receptacle
	receptacle3_sink - receptacle
	receptacle4_sink - receptacle
	receptacle5_refrigerator - receptacle
	receptacle6_refrigerator - receptacle
	receptacle9_toilet - receptacle
	refrigerator - rclass
	remote - iclass
	robot - agent
	room1_bathroom - room
	room2_bedroom - room
	room3_corridor - room
	room4_corridor - room
	room5_dining_room - room
	room6_kitchen - room
	room7_living_room - room
	sink - rclass
	spoon - iclass
	sportsball - iclass
	suitcase - iclass
	surfboard - iclass
	teddybear - iclass
	tie - iclass
	toaster - rclass
	toilet - rclass
	toothbrush - iclass
	tv - iclass
	umbrella - iclass
	vase - iclass
	wineglass - iclass
  )
  (:init 
	(atlocation robot location_Xpos15_Ypos28_place0_room6_floorA)
	(inplace robot place0_door_room6_kitchen)
	(inroom robot room6_kitchen)
	(itematlocation item15_potted_plant_largeitem location_Xpos5_Ypos11_place9_room7_floorA)
	(itematlocation item7_vase_mediumitem location_Xpos5_Ypos12_place8_room7_floorA)
	(itematlocation item8_vase_mediumitem location_Xpos9_Ypos12_place7_room7_floorA)
	(itemclass item15_potted_plant_largeitem pottedplant)
	(itemclass item7_vase_mediumitem vase)
	(itemclass item8_vase_mediumitem vase)
	(locationinplace location_Xneg10_Yneg23_place19_room5_floorA place19_receptacle12_chair)
	(locationinplace location_Xneg12_Yneg19_place23_room5_floorA place23_receptacle17_dining_table)
	(locationinplace location_Xneg22_Yneg7_place6_room4_floorA place6_door_room4_corridor)
	(locationinplace location_Xneg36_Yneg22_place13_room1_floorA place13_receptacle4_sink)
	(locationinplace location_Xneg39_Yneg17_place1_room1_floorA place1_door_room1_bathroom)
	(locationinplace location_Xneg43_Ypos17_place22_room2_floorA place22_receptacle16_bed)
	(locationinplace location_Xneg44_Ypos11_place4_room2_floorA place4_door_room2_bedroom)
	(locationinplace location_Xneg47_Yneg11_place12_room1_floorA place12_receptacle3_sink)
	(locationinplace location_Xneg47_Yneg22_place16_room1_floorA place16_receptacle9_toilet)
	(locationinplace location_Xneg6_Yneg16_place24_room5_floorA place24_receptacle18_dining_table)
	(locationinplace location_Xneg8_Yneg16_place18_room5_floorA place18_receptacle11_chair)
	(locationinplace location_Xneg8_Yneg17_place3_room5_floorA place3_door_room5_dining_room)
	(locationinplace location_Xneg8_Ypos10_place5_room3_floorA place5_door_room3_corridor)
	(locationinplace location_Xpos14_Yneg21_place20_room7_floorA place20_receptacle13_couch)
	(locationinplace location_Xpos14_Ypos37_place11_room6_floorA place11_receptacle2_sink)
	(locationinplace location_Xpos15_Ypos28_place0_room6_floorA place0_door_room6_kitchen)
	(locationinplace location_Xpos17_Yneg6_place2_room7_floorA place2_door_room7_living_room)
	(locationinplace location_Xpos21_Ypos18_place14_room6_floorA place14_receptacle5_refrigerator)
	(locationinplace location_Xpos29_Yneg7_place21_room7_floorA place21_receptacle14_couch)
	(locationinplace location_Xpos29_Ypos18_place15_room6_floorA place15_receptacle6_refrigerator)
	(locationinplace location_Xpos30_Ypos37_place10_room6_floorA place10_receptacle1_oven)
	(locationinplace location_Xpos30_Ypos8_place17_room7_floorA place17_receptacle10_chair)
	(locationinplace location_Xpos5_Ypos11_place9_room7_floorA place9_item15_potted_plant)
	(locationinplace location_Xpos5_Ypos12_place8_room7_floorA place8_item7_vase)
	(locationinplace location_Xpos9_Ypos12_place7_room7_floorA place7_item8_vase)
	(placeinroom place0_door_room6_kitchen room6_kitchen)
	(placeinroom place10_receptacle1_oven room6_kitchen)
	(placeinroom place11_receptacle2_sink room6_kitchen)
	(placeinroom place12_receptacle3_sink room1_bathroom)
	(placeinroom place13_receptacle4_sink room1_bathroom)
	(placeinroom place14_receptacle5_refrigerator room6_kitchen)
	(placeinroom place15_receptacle6_refrigerator room6_kitchen)
	(placeinroom place16_receptacle9_toilet room1_bathroom)
	(placeinroom place17_receptacle10_chair room7_living_room)
	(placeinroom place18_receptacle11_chair room5_dining_room)
	(placeinroom place19_receptacle12_chair room5_dining_room)
	(placeinroom place1_door_room1_bathroom room1_bathroom)
	(placeinroom place20_receptacle13_couch room7_living_room)
	(placeinroom place21_receptacle14_couch room7_living_room)
	(placeinroom place22_receptacle16_bed room2_bedroom)
	(placeinroom place23_receptacle17_dining_table room5_dining_room)
	(placeinroom place24_receptacle18_dining_table room5_dining_room)
	(placeinroom place2_door_room7_living_room room7_living_room)
	(placeinroom place3_door_room5_dining_room room5_dining_room)
	(placeinroom place4_door_room2_bedroom room2_bedroom)
	(placeinroom place5_door_room3_corridor room3_corridor)
	(placeinroom place6_door_room4_corridor room4_corridor)
	(placeinroom place7_item8_vase room7_living_room)
	(placeinroom place8_item7_vase room7_living_room)
	(placeinroom place9_item15_potted_plant room7_living_room)
	(placelocation location_Xneg10_Yneg23_place19_room5_floorA place19_receptacle12_chair)
	(placelocation location_Xneg12_Yneg19_place23_room5_floorA place23_receptacle17_dining_table)
	(placelocation location_Xneg22_Yneg7_place6_room4_floorA place6_door_room4_corridor)
	(placelocation location_Xneg36_Yneg22_place13_room1_floorA place13_receptacle4_sink)
	(placelocation location_Xneg39_Yneg17_place1_room1_floorA place1_door_room1_bathroom)
	(placelocation location_Xneg43_Ypos17_place22_room2_floorA place22_receptacle16_bed)
	(placelocation location_Xneg44_Ypos11_place4_room2_floorA place4_door_room2_bedroom)
	(placelocation location_Xneg47_Yneg11_place12_room1_floorA place12_receptacle3_sink)
	(placelocation location_Xneg47_Yneg22_place16_room1_floorA place16_receptacle9_toilet)
	(placelocation location_Xneg6_Yneg16_place24_room5_floorA place24_receptacle18_dining_table)
	(placelocation location_Xneg8_Yneg16_place18_room5_floorA place18_receptacle11_chair)
	(placelocation location_Xneg8_Yneg17_place3_room5_floorA place3_door_room5_dining_room)
	(placelocation location_Xneg8_Ypos10_place5_room3_floorA place5_door_room3_corridor)
	(placelocation location_Xpos14_Yneg21_place20_room7_floorA place20_receptacle13_couch)
	(placelocation location_Xpos14_Ypos37_place11_room6_floorA place11_receptacle2_sink)
	(placelocation location_Xpos15_Ypos28_place0_room6_floorA place0_door_room6_kitchen)
	(placelocation location_Xpos17_Yneg6_place2_room7_floorA place2_door_room7_living_room)
	(placelocation location_Xpos21_Ypos18_place14_room6_floorA place14_receptacle5_refrigerator)
	(placelocation location_Xpos29_Yneg7_place21_room7_floorA place21_receptacle14_couch)
	(placelocation location_Xpos29_Ypos18_place15_room6_floorA place15_receptacle6_refrigerator)
	(placelocation location_Xpos30_Ypos37_place10_room6_floorA place10_receptacle1_oven)
	(placelocation location_Xpos30_Ypos8_place17_room7_floorA place17_receptacle10_chair)
	(placelocation location_Xpos5_Ypos11_place9_room7_floorA place9_item15_potted_plant)
	(placelocation location_Xpos5_Ypos12_place8_room7_floorA place8_item7_vase)
	(placelocation location_Xpos9_Ypos12_place7_room7_floorA place7_item8_vase)
	(receptacleatlocation receptacle10_chair location_Xpos30_Ypos8_place17_room7_floorA)
	(receptacleatlocation receptacle11_chair location_Xneg8_Yneg16_place18_room5_floorA)
	(receptacleatlocation receptacle12_chair location_Xneg10_Yneg23_place19_room5_floorA)
	(receptacleatlocation receptacle13_couch location_Xpos14_Yneg21_place20_room7_floorA)
	(receptacleatlocation receptacle14_couch location_Xpos29_Yneg7_place21_room7_floorA)
	(receptacleatlocation receptacle16_bed location_Xneg43_Ypos17_place22_room2_floorA)
	(receptacleatlocation receptacle17_dining_table location_Xneg12_Yneg19_place23_room5_floorA)
	(receptacleatlocation receptacle18_dining_table location_Xneg6_Yneg16_place24_room5_floorA)
	(receptacleatlocation receptacle1_oven location_Xpos30_Ypos37_place10_room6_floorA)
	(receptacleatlocation receptacle2_sink location_Xpos14_Ypos37_place11_room6_floorA)
	(receptacleatlocation receptacle3_sink location_Xneg47_Yneg11_place12_room1_floorA)
	(receptacleatlocation receptacle4_sink location_Xneg36_Yneg22_place13_room1_floorA)
	(receptacleatlocation receptacle5_refrigerator location_Xpos21_Ypos18_place14_room6_floorA)
	(receptacleatlocation receptacle6_refrigerator location_Xpos29_Ypos18_place15_room6_floorA)
	(receptacleatlocation receptacle9_toilet location_Xneg47_Yneg22_place16_room1_floorA)
	(receptacleclass receptacle10_chair chair)
	(receptacleclass receptacle11_chair chair)
	(receptacleclass receptacle12_chair chair)
	(receptacleclass receptacle13_couch couch)
	(receptacleclass receptacle14_couch couch)
	(receptacleclass receptacle16_bed bed)
	(receptacleclass receptacle17_dining_table diningtable)
	(receptacleclass receptacle18_dining_table diningtable)
	(receptacleclass receptacle1_oven oven)
	(receptacleclass receptacle2_sink sink)
	(receptacleclass receptacle3_sink sink)
	(receptacleclass receptacle4_sink sink)
	(receptacleclass receptacle5_refrigerator refrigerator)
	(receptacleclass receptacle6_refrigerator refrigerator)
	(receptacleclass receptacle9_toilet toilet)
	(receptacleopeningtype receptacle1_oven)
	(receptacleopeningtype receptacle5_refrigerator)
	(receptacleopeningtype receptacle6_refrigerator)
	(roomplace place0_door_room6_kitchen room6_kitchen)
	(roomplace place1_door_room1_bathroom room1_bathroom)
	(roomplace place2_door_room7_living_room room7_living_room)
	(roomplace place3_door_room5_dining_room room5_dining_room)
	(roomplace place4_door_room2_bedroom room2_bedroom)
	(roomplace place5_door_room3_corridor room3_corridor)
	(roomplace place6_door_room4_corridor room4_corridor)
	(roomsconnected room1_bathroom room4_corridor)
	(roomsconnected room2_bedroom room4_corridor)
	(roomsconnected room3_corridor room4_corridor)
	(roomsconnected room3_corridor room6_kitchen)
	(roomsconnected room4_corridor room1_bathroom)
	(roomsconnected room4_corridor room2_bedroom)
	(roomsconnected room4_corridor room3_corridor)
	(roomsconnected room4_corridor room5_dining_room)
	(roomsconnected room5_dining_room room4_corridor)
	(roomsconnected room5_dining_room room7_living_room)
	(roomsconnected room6_kitchen room3_corridor)
	(roomsconnected room7_living_room room5_dining_room)
  )
  (:goal (and
	(classrelation vase refrigerator)
	(classrelation vase sink)
	(classrelation vase chair)
	(classrelation pottedplant sink)
	(classrelation vase couch)))
)
