
(define (problem shelbyvilletaskographyv2tiny2problem40) (:domain taskographyv2tiny2scrub)
  (:objects
        item22_bowl_smallitem - item
	item89_vase_mediumitem - item
	location_xneg10_ypos79_place3_room10_floorc - location
	location_xneg16_yneg14_place5_room20_floorb - location
	location_xneg21_ypos8_place9_room22_floora - location
	location_xneg23_ypos90_place1_room21_floorb - location
	location_xneg24_ypos60_place11_room19_floorb - location
	location_xneg24_ypos75_place15_room25_floora - location
	location_xneg25_ypos25_place77_room6_floorc - location
	location_xneg27_ypos27_place10_room16_floorb - location
	location_xneg29_yneg37_place74_room6_floorc - location
	location_xneg31_yneg17_place16_room6_floorc - location
	location_xneg33_ypos81_place17_room3_floorc - location
	location_xneg4_yneg10_place19_room7_floorc - location
	location_xneg4_yneg29_place18_room2_floorc - location
	location_xpos12_ypos83_place8_room11_floorc - location
	location_xpos14_yneg4_place20_room12_floora - location
	location_xpos21_yneg32_place51_room18_floorb - location
	location_xpos23_ypos17_place7_room1_floora - location
	location_xpos40_ypos79_place12_room4_floorc - location
	location_xpos42_yneg26_place13_room18_floorb - location
	location_xpos43_yneg1_place21_room14_floorb - location
	location_xpos43_ypos23_place14_room17_floorb - location
	location_xpos44_yneg17_place0_room5_floorc - location
	location_xpos51_ypos44_place4_room9_floorc - location
	location_xpos53_ypos19_place2_room8_floorc - location
	location_xpos5_ypos30_place22_room15_floorc - location
	location_xpos6_yneg25_place23_room23_floora - location
	location_xpos7_ypos30_place41_room22_floora - location
	location_xpos9_yneg23_place24_room24_floorb - location
	location_xpos9_ypos30_place6_room13_floorb - location
	place0_door_room5_bedroom - place
	place10_door_room16_dining_room - place
	place11_door_room19_kitchen - place
	place12_door_room4_bedroom - place
	place13_door_room18_home_office - place
	place14_door_room17_dining_room - place
	place15_door_room25_television_room - place
	place16_door_room6_childs_room - place
	place17_door_room3_bathroom - place
	place18_door_room2_bathroom - place
	place19_door_room7_closet - place
	place1_door_room21_lobby - place
	place20_door_room12_corridor - place
	place21_door_room14_corridor - place
	place22_door_room15_corridor - place
	place23_door_room23_staircase - place
	place24_door_room24_staircase - place
	place2_door_room8_closet - place
	place3_door_room10_closet - place
	place41_item22_bowl - place
	place4_door_room9_closet - place
	place51_item89_vase - place
	place5_door_room20_living_room - place
	place6_door_room13_corridor - place
	place74_receptacle45_couch - place
	place77_receptacle59_bed - place
	place7_door_room1_bathroom - place
	place8_door_room11_closet - place
	place9_door_room22_playroom - place
	receptacle45_couch - receptacle
	receptacle59_bed - receptacle
	robot - agent
	room10_closet - room
	room11_closet - room
	room12_corridor - room
	room13_corridor - room
	room14_corridor - room
	room15_corridor - room
	room16_dining_room - room
	room17_dining_room - room
	room18_home_office - room
	room19_kitchen - room
	room1_bathroom - room
	room20_living_room - room
	room21_lobby - room
	room22_playroom - room
	room23_staircase - room
	room24_staircase - room
	room25_television_room - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_childs_room - room
	room7_closet - room
	room8_closet - room
	room9_closet - room
  )
  (:init 
	(atlocation robot location_xpos12_ypos83_place8_room11_floorc)
	(inplace robot place8_door_room11_closet)
	(inroom robot room11_closet)
	(itematlocation item22_bowl_smallitem location_xpos7_ypos30_place41_room22_floora)
	(itematlocation item89_vase_mediumitem location_xpos21_yneg32_place51_room18_floorb)
	(locationinplace location_xneg10_ypos79_place3_room10_floorc place3_door_room10_closet)
	(locationinplace location_xneg16_yneg14_place5_room20_floorb place5_door_room20_living_room)
	(locationinplace location_xneg21_ypos8_place9_room22_floora place9_door_room22_playroom)
	(locationinplace location_xneg23_ypos90_place1_room21_floorb place1_door_room21_lobby)
	(locationinplace location_xneg24_ypos60_place11_room19_floorb place11_door_room19_kitchen)
	(locationinplace location_xneg24_ypos75_place15_room25_floora place15_door_room25_television_room)
	(locationinplace location_xneg25_ypos25_place77_room6_floorc place77_receptacle59_bed)
	(locationinplace location_xneg27_ypos27_place10_room16_floorb place10_door_room16_dining_room)
	(locationinplace location_xneg29_yneg37_place74_room6_floorc place74_receptacle45_couch)
	(locationinplace location_xneg31_yneg17_place16_room6_floorc place16_door_room6_childs_room)
	(locationinplace location_xneg33_ypos81_place17_room3_floorc place17_door_room3_bathroom)
	(locationinplace location_xneg4_yneg10_place19_room7_floorc place19_door_room7_closet)
	(locationinplace location_xneg4_yneg29_place18_room2_floorc place18_door_room2_bathroom)
	(locationinplace location_xpos12_ypos83_place8_room11_floorc place8_door_room11_closet)
	(locationinplace location_xpos14_yneg4_place20_room12_floora place20_door_room12_corridor)
	(locationinplace location_xpos21_yneg32_place51_room18_floorb place51_item89_vase)
	(locationinplace location_xpos23_ypos17_place7_room1_floora place7_door_room1_bathroom)
	(locationinplace location_xpos40_ypos79_place12_room4_floorc place12_door_room4_bedroom)
	(locationinplace location_xpos42_yneg26_place13_room18_floorb place13_door_room18_home_office)
	(locationinplace location_xpos43_yneg1_place21_room14_floorb place21_door_room14_corridor)
	(locationinplace location_xpos43_ypos23_place14_room17_floorb place14_door_room17_dining_room)
	(locationinplace location_xpos44_yneg17_place0_room5_floorc place0_door_room5_bedroom)
	(locationinplace location_xpos51_ypos44_place4_room9_floorc place4_door_room9_closet)
	(locationinplace location_xpos53_ypos19_place2_room8_floorc place2_door_room8_closet)
	(locationinplace location_xpos5_ypos30_place22_room15_floorc place22_door_room15_corridor)
	(locationinplace location_xpos6_yneg25_place23_room23_floora place23_door_room23_staircase)
	(locationinplace location_xpos7_ypos30_place41_room22_floora place41_item22_bowl)
	(locationinplace location_xpos9_yneg23_place24_room24_floorb place24_door_room24_staircase)
	(locationinplace location_xpos9_ypos30_place6_room13_floorb place6_door_room13_corridor)
	(placeinroom place0_door_room5_bedroom room5_bedroom)
	(placeinroom place10_door_room16_dining_room room16_dining_room)
	(placeinroom place11_door_room19_kitchen room19_kitchen)
	(placeinroom place12_door_room4_bedroom room4_bedroom)
	(placeinroom place13_door_room18_home_office room18_home_office)
	(placeinroom place14_door_room17_dining_room room17_dining_room)
	(placeinroom place15_door_room25_television_room room25_television_room)
	(placeinroom place16_door_room6_childs_room room6_childs_room)
	(placeinroom place17_door_room3_bathroom room3_bathroom)
	(placeinroom place18_door_room2_bathroom room2_bathroom)
	(placeinroom place19_door_room7_closet room7_closet)
	(placeinroom place1_door_room21_lobby room21_lobby)
	(placeinroom place20_door_room12_corridor room12_corridor)
	(placeinroom place21_door_room14_corridor room14_corridor)
	(placeinroom place22_door_room15_corridor room15_corridor)
	(placeinroom place23_door_room23_staircase room23_staircase)
	(placeinroom place24_door_room24_staircase room24_staircase)
	(placeinroom place2_door_room8_closet room8_closet)
	(placeinroom place3_door_room10_closet room10_closet)
	(placeinroom place41_item22_bowl room22_playroom)
	(placeinroom place4_door_room9_closet room9_closet)
	(placeinroom place51_item89_vase room18_home_office)
	(placeinroom place5_door_room20_living_room room20_living_room)
	(placeinroom place6_door_room13_corridor room13_corridor)
	(placeinroom place74_receptacle45_couch room6_childs_room)
	(placeinroom place77_receptacle59_bed room6_childs_room)
	(placeinroom place7_door_room1_bathroom room1_bathroom)
	(placeinroom place8_door_room11_closet room11_closet)
	(placeinroom place9_door_room22_playroom room22_playroom)
	(placelocation location_xneg10_ypos79_place3_room10_floorc place3_door_room10_closet)
	(placelocation location_xneg16_yneg14_place5_room20_floorb place5_door_room20_living_room)
	(placelocation location_xneg21_ypos8_place9_room22_floora place9_door_room22_playroom)
	(placelocation location_xneg23_ypos90_place1_room21_floorb place1_door_room21_lobby)
	(placelocation location_xneg24_ypos60_place11_room19_floorb place11_door_room19_kitchen)
	(placelocation location_xneg24_ypos75_place15_room25_floora place15_door_room25_television_room)
	(placelocation location_xneg25_ypos25_place77_room6_floorc place77_receptacle59_bed)
	(placelocation location_xneg27_ypos27_place10_room16_floorb place10_door_room16_dining_room)
	(placelocation location_xneg29_yneg37_place74_room6_floorc place74_receptacle45_couch)
	(placelocation location_xneg31_yneg17_place16_room6_floorc place16_door_room6_childs_room)
	(placelocation location_xneg33_ypos81_place17_room3_floorc place17_door_room3_bathroom)
	(placelocation location_xneg4_yneg10_place19_room7_floorc place19_door_room7_closet)
	(placelocation location_xneg4_yneg29_place18_room2_floorc place18_door_room2_bathroom)
	(placelocation location_xpos12_ypos83_place8_room11_floorc place8_door_room11_closet)
	(placelocation location_xpos14_yneg4_place20_room12_floora place20_door_room12_corridor)
	(placelocation location_xpos21_yneg32_place51_room18_floorb place51_item89_vase)
	(placelocation location_xpos23_ypos17_place7_room1_floora place7_door_room1_bathroom)
	(placelocation location_xpos40_ypos79_place12_room4_floorc place12_door_room4_bedroom)
	(placelocation location_xpos42_yneg26_place13_room18_floorb place13_door_room18_home_office)
	(placelocation location_xpos43_yneg1_place21_room14_floorb place21_door_room14_corridor)
	(placelocation location_xpos43_ypos23_place14_room17_floorb place14_door_room17_dining_room)
	(placelocation location_xpos44_yneg17_place0_room5_floorc place0_door_room5_bedroom)
	(placelocation location_xpos51_ypos44_place4_room9_floorc place4_door_room9_closet)
	(placelocation location_xpos53_ypos19_place2_room8_floorc place2_door_room8_closet)
	(placelocation location_xpos5_ypos30_place22_room15_floorc place22_door_room15_corridor)
	(placelocation location_xpos6_yneg25_place23_room23_floora place23_door_room23_staircase)
	(placelocation location_xpos7_ypos30_place41_room22_floora place41_item22_bowl)
	(placelocation location_xpos9_yneg23_place24_room24_floorb place24_door_room24_staircase)
	(placelocation location_xpos9_ypos30_place6_room13_floorb place6_door_room13_corridor)
	(receptacleatlocation receptacle45_couch location_xneg29_yneg37_place74_room6_floorc)
	(receptacleatlocation receptacle59_bed location_xneg25_ypos25_place77_room6_floorc)
	(roomplace place0_door_room5_bedroom room5_bedroom)
	(roomplace place10_door_room16_dining_room room16_dining_room)
	(roomplace place11_door_room19_kitchen room19_kitchen)
	(roomplace place12_door_room4_bedroom room4_bedroom)
	(roomplace place13_door_room18_home_office room18_home_office)
	(roomplace place14_door_room17_dining_room room17_dining_room)
	(roomplace place15_door_room25_television_room room25_television_room)
	(roomplace place16_door_room6_childs_room room6_childs_room)
	(roomplace place17_door_room3_bathroom room3_bathroom)
	(roomplace place18_door_room2_bathroom room2_bathroom)
	(roomplace place19_door_room7_closet room7_closet)
	(roomplace place1_door_room21_lobby room21_lobby)
	(roomplace place20_door_room12_corridor room12_corridor)
	(roomplace place21_door_room14_corridor room14_corridor)
	(roomplace place22_door_room15_corridor room15_corridor)
	(roomplace place23_door_room23_staircase room23_staircase)
	(roomplace place24_door_room24_staircase room24_staircase)
	(roomplace place2_door_room8_closet room8_closet)
	(roomplace place3_door_room10_closet room10_closet)
	(roomplace place4_door_room9_closet room9_closet)
	(roomplace place5_door_room20_living_room room20_living_room)
	(roomplace place6_door_room13_corridor room13_corridor)
	(roomplace place7_door_room1_bathroom room1_bathroom)
	(roomplace place8_door_room11_closet room11_closet)
	(roomplace place9_door_room22_playroom room22_playroom)
	(roomsconnected room10_closet room11_closet)
	(roomsconnected room10_closet room3_bathroom)
	(roomsconnected room11_closet room10_closet)
	(roomsconnected room11_closet room4_bedroom)
	(roomsconnected room12_corridor room1_bathroom)
	(roomsconnected room12_corridor room22_playroom)
	(roomsconnected room12_corridor room23_staircase)
	(roomsconnected room13_corridor room16_dining_room)
	(roomsconnected room13_corridor room17_dining_room)
	(roomsconnected room14_corridor room17_dining_room)
	(roomsconnected room14_corridor room18_home_office)
	(roomsconnected room15_corridor room7_closet)
	(roomsconnected room15_corridor room9_closet)
	(roomsconnected room16_dining_room room13_corridor)
	(roomsconnected room16_dining_room room19_kitchen)
	(roomsconnected room17_dining_room room13_corridor)
	(roomsconnected room17_dining_room room14_corridor)
	(roomsconnected room18_home_office room14_corridor)
	(roomsconnected room18_home_office room24_staircase)
	(roomsconnected room19_kitchen room16_dining_room)
	(roomsconnected room19_kitchen room21_lobby)
	(roomsconnected room1_bathroom room12_corridor)
	(roomsconnected room20_living_room room23_staircase)
	(roomsconnected room20_living_room room24_staircase)
	(roomsconnected room21_lobby room19_kitchen)
	(roomsconnected room22_playroom room12_corridor)
	(roomsconnected room22_playroom room25_television_room)
	(roomsconnected room23_staircase room12_corridor)
	(roomsconnected room23_staircase room20_living_room)
	(roomsconnected room24_staircase room18_home_office)
	(roomsconnected room24_staircase room20_living_room)
	(roomsconnected room24_staircase room2_bathroom)
	(roomsconnected room25_television_room room22_playroom)
	(roomsconnected room2_bathroom room24_staircase)
	(roomsconnected room2_bathroom room7_closet)
	(roomsconnected room3_bathroom room10_closet)
	(roomsconnected room4_bedroom room11_closet)
	(roomsconnected room4_bedroom room9_closet)
	(roomsconnected room5_bedroom room8_closet)
	(roomsconnected room6_childs_room room7_closet)
	(roomsconnected room7_closet room15_corridor)
	(roomsconnected room7_closet room2_bathroom)
	(roomsconnected room7_closet room6_childs_room)
	(roomsconnected room8_closet room5_bedroom)
	(roomsconnected room8_closet room9_closet)
	(roomsconnected room9_closet room15_corridor)
	(roomsconnected room9_closet room4_bedroom)
	(roomsconnected room9_closet room8_closet)
  )
  (:goal (and
	(inreceptacle item89_vase_mediumitem receptacle45_couch)
	(inreceptacle item22_bowl_smallitem receptacle59_bed)))
)
