
(define (problem newcombtaskographyv4medium5problem6) (:domain taskographyv4medium5scrub)
  (:objects
        apple - iclass
	backpack - iclass
	banana - iclass
	baseballbat - iclass
	baseballglove - iclass
	bed - rclass
	bench - rclass
	bicycle - iclass
	boat - rclass
	book - iclass
	bottle - iclass
	bowl - iclass
	cake - iclass
	cellphone - iclass
	chair - rclass
	clock - iclass
	couch - rclass
	cup - iclass
	diningtable - rclass
	frisbee - iclass
	handbag - iclass
	item10_cup_smallitem - item
	item11_clock_mediumitem - item
	item12_vase_mediumitem - item
	item13_vase_mediumitem - item
	item14_vase_mediumitem - item
	item15_vase_mediumitem - item
	item16_bowl_smallitem - item
	item17_bowl_smallitem - item
	item18_banana_smallitem - item
	item19_banana_smallitem - item
	item20_apple_smallitem - item
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item33_potted_plant_largeitem - item
	item8_cup_smallitem - item
	item9_cup_smallitem - item
	keyboard - iclass
	kite - iclass
	knife - iclass
	laptop - iclass
	location_xneg12_ypos57_place23_room1_floora - location
	location_xneg13_ypos26_place13_room2_floora - location
	location_xneg14_ypos23_place13_room2_floora - location
	location_xneg19_yneg29_place12_room8_floora - location
	location_xneg20_ypos26_place1_room2_floora - location
	location_xneg21_yneg28_place12_room8_floora - location
	location_xneg22_yneg11_place16_room8_floora - location
	location_xneg22_yneg22_place12_room8_floora - location
	location_xneg2_yneg10_place7_room3_floora - location
	location_xneg2_ypos45_place2_room1_floora - location
	location_xneg31_ypos5_place5_room6_floora - location
	location_xneg32_yneg17_place0_room8_floora - location
	location_xneg33_ypos6_place10_room6_floora - location
	location_xneg34_ypos33_place8_room5_floora - location
	location_xneg36_yneg26_place11_room8_floora - location
	location_xneg3_ypos25_place9_room10_floora - location
	location_xneg42_yneg16_place14_room8_floora - location
	location_xneg42_yneg28_place11_room8_floora - location
	location_xneg42_yneg9_place14_room8_floora - location
	location_xneg44_yneg26_place11_room8_floora - location
	location_xneg44_yneg28_place11_room8_floora - location
	location_xneg47_yneg28_place22_room7_floora - location
	location_xneg49_yneg22_place22_room7_floora - location
	location_xneg51_yneg23_place25_room7_floora - location
	location_xneg53_ypos24_place6_room4_floora - location
	location_xneg54_yneg29_place20_room7_floora - location
	location_xneg56_yneg17_place4_room7_floora - location
	location_xneg56_yneg23_place20_room7_floora - location
	location_xneg57_yneg28_place21_room7_floora - location
	location_xneg57_yneg29_place20_room7_floora - location
	location_xneg61_yneg29_place20_room7_floora - location
	location_xneg61_ypos28_place18_room4_floora - location
	location_xneg62_yneg23_place26_room7_floora - location
	location_xneg6_yneg18_place19_room3_floora - location
	location_xneg71_ypos2_place24_room9_floora - location
	location_xneg82_yneg24_place29_room9_floora - location
	location_xneg82_yneg6_place30_room9_floora - location
	location_xneg83_yneg11_place3_room9_floora - location
	location_xneg83_yneg22_place27_room9_floora - location
	location_xneg85_yneg26_place28_room9_floora - location
	location_xneg94_yneg7_place30_room9_floora - location
	location_xneg9_ypos37_place17_room1_floora - location
	location_xpos5_ypos54_place23_room1_floora - location
	location_xpos6_ypos39_place15_room1_floora - location
	location_xpos8_ypos42_place15_room1_floora - location
	microwave - rclass
	motorcycle - iclass
	mouse - iclass
	orange - iclass
	oven - rclass
	place0_door_room8_kitchen - place
	place10_item20_apple - place
	place11_receptacle1_microwave - place
	place12_receptacle2_oven - place
	place13_receptacle3_sink - place
	place14_receptacle4_sink - place
	place15_receptacle5_sink - place
	place16_receptacle6_refrigerator - place
	place17_receptacle7_refrigerator - place
	place18_receptacle34_bed - place
	place19_receptacle35_bed - place
	place1_door_room2_bathroom - place
	place20_receptacle36_dining_table - place
	place21_receptacle37_dining_table - place
	place22_receptacle38_dining_table - place
	place23_receptacle21_toilet - place
	place24_receptacle22_chair - place
	place25_receptacle23_chair - place
	place26_receptacle24_chair - place
	place27_receptacle25_chair - place
	place28_receptacle26_chair - place
	place29_receptacle27_chair - place
	place2_door_room1_bathroom - place
	place30_receptacle29_couch - place
	place3_door_room9_living_room - place
	place4_door_room7_dining_room - place
	place5_door_room6_corridor - place
	place6_door_room4_bedroom - place
	place7_door_room3_bedroom - place
	place8_door_room5_closet - place
	place9_door_room10_lobby - place
	pottedplant - iclass
	receptacle1_microwave - receptacle
	receptacle21_toilet - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle29_couch - receptacle
	receptacle2_oven - receptacle
	receptacle34_bed - receptacle
	receptacle35_bed - receptacle
	receptacle36_dining_table - receptacle
	receptacle37_dining_table - receptacle
	receptacle38_dining_table - receptacle
	receptacle3_sink - receptacle
	receptacle4_sink - receptacle
	receptacle5_sink - receptacle
	receptacle6_refrigerator - receptacle
	receptacle7_refrigerator - receptacle
	refrigerator - rclass
	remote - iclass
	robot - agent
	room10_lobby - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bedroom - room
	room4_bedroom - room
	room5_closet - room
	room6_corridor - room
	room7_dining_room - room
	room8_kitchen - room
	room9_living_room - room
	sink - rclass
	spoon - iclass
	sportsball - iclass
	suitcase - iclass
	surfboard - iclass
	teddybear - iclass
	tie - iclass
	toaster - rclass
	toilet - rclass
	toothbrush - iclass
	tv - iclass
	umbrella - iclass
	vase - iclass
	wineglass - iclass
  )
  (:init 
	(atlocation robot location_xneg3_ypos25_place9_room10_floora)
	(classrelation banana diningtable)
	(classrelation bowl couch)
	(classrelation bowl sink)
	(classrelation clock toilet)
	(classrelation cup oven)
	(classrelation pottedplant diningtable)
	(classrelation pottedplant sink)
	(classrelation vase microwave)
	(classrelation vase sink)
	(inanyreceptacle item10_cup_smallitem)
	(inanyreceptacle item11_clock_mediumitem)
	(inanyreceptacle item12_vase_mediumitem)
	(inanyreceptacle item13_vase_mediumitem)
	(inanyreceptacle item14_vase_mediumitem)
	(inanyreceptacle item15_vase_mediumitem)
	(inanyreceptacle item16_bowl_smallitem)
	(inanyreceptacle item17_bowl_smallitem)
	(inanyreceptacle item18_banana_smallitem)
	(inanyreceptacle item19_banana_smallitem)
	(inanyreceptacle item30_potted_plant_largeitem)
	(inanyreceptacle item31_potted_plant_largeitem)
	(inanyreceptacle item32_potted_plant_largeitem)
	(inanyreceptacle item33_potted_plant_largeitem)
	(inanyreceptacle item8_cup_smallitem)
	(inanyreceptacle item9_cup_smallitem)
	(inplace robot place9_door_room10_lobby)
	(inreceptacle item10_cup_smallitem receptacle2_oven)
	(inreceptacle item11_clock_mediumitem receptacle21_toilet)
	(inreceptacle item12_vase_mediumitem receptacle1_microwave)
	(inreceptacle item13_vase_mediumitem receptacle1_microwave)
	(inreceptacle item14_vase_mediumitem receptacle1_microwave)
	(inreceptacle item15_vase_mediumitem receptacle5_sink)
	(inreceptacle item16_bowl_smallitem receptacle29_couch)
	(inreceptacle item17_bowl_smallitem receptacle4_sink)
	(inreceptacle item18_banana_smallitem receptacle36_dining_table)
	(inreceptacle item19_banana_smallitem receptacle38_dining_table)
	(inreceptacle item30_potted_plant_largeitem receptacle3_sink)
	(inreceptacle item31_potted_plant_largeitem receptacle36_dining_table)
	(inreceptacle item32_potted_plant_largeitem receptacle36_dining_table)
	(inreceptacle item33_potted_plant_largeitem receptacle36_dining_table)
	(inreceptacle item8_cup_smallitem receptacle2_oven)
	(inreceptacle item9_cup_smallitem receptacle2_oven)
	(inroom robot room10_lobby)
	(itematlocation item10_cup_smallitem location_xneg19_yneg29_place12_room8_floora)
	(itematlocation item11_clock_mediumitem location_xneg12_ypos57_place23_room1_floora)
	(itematlocation item12_vase_mediumitem location_xneg44_yneg26_place11_room8_floora)
	(itematlocation item13_vase_mediumitem location_xneg42_yneg28_place11_room8_floora)
	(itematlocation item14_vase_mediumitem location_xneg44_yneg28_place11_room8_floora)
	(itematlocation item15_vase_mediumitem location_xpos8_ypos42_place15_room1_floora)
	(itematlocation item16_bowl_smallitem location_xneg82_yneg6_place30_room9_floora)
	(itematlocation item17_bowl_smallitem location_xneg42_yneg9_place14_room8_floora)
	(itematlocation item18_banana_smallitem location_xneg56_yneg23_place20_room7_floora)
	(itematlocation item19_banana_smallitem location_xneg47_yneg28_place22_room7_floora)
	(itematlocation item20_apple_smallitem location_xneg33_ypos6_place10_room6_floora)
	(itematlocation item30_potted_plant_largeitem location_xneg13_ypos26_place13_room2_floora)
	(itematlocation item31_potted_plant_largeitem location_xneg61_yneg29_place20_room7_floora)
	(itematlocation item32_potted_plant_largeitem location_xneg57_yneg29_place20_room7_floora)
	(itematlocation item33_potted_plant_largeitem location_xneg54_yneg29_place20_room7_floora)
	(itematlocation item8_cup_smallitem location_xneg21_yneg28_place12_room8_floora)
	(itematlocation item9_cup_smallitem location_xneg19_yneg29_place12_room8_floora)
	(itemclass item10_cup_smallitem cup)
	(itemclass item11_clock_mediumitem clock)
	(itemclass item12_vase_mediumitem vase)
	(itemclass item13_vase_mediumitem vase)
	(itemclass item14_vase_mediumitem vase)
	(itemclass item15_vase_mediumitem vase)
	(itemclass item16_bowl_smallitem bowl)
	(itemclass item17_bowl_smallitem bowl)
	(itemclass item18_banana_smallitem banana)
	(itemclass item19_banana_smallitem banana)
	(itemclass item20_apple_smallitem apple)
	(itemclass item30_potted_plant_largeitem pottedplant)
	(itemclass item31_potted_plant_largeitem pottedplant)
	(itemclass item32_potted_plant_largeitem pottedplant)
	(itemclass item33_potted_plant_largeitem pottedplant)
	(itemclass item8_cup_smallitem cup)
	(itemclass item9_cup_smallitem cup)
	(locationinplace location_xneg12_ypos57_place23_room1_floora place23_receptacle21_toilet)
	(locationinplace location_xneg13_ypos26_place13_room2_floora place13_receptacle3_sink)
	(locationinplace location_xneg14_ypos23_place13_room2_floora place13_receptacle3_sink)
	(locationinplace location_xneg19_yneg29_place12_room8_floora place12_receptacle2_oven)
	(locationinplace location_xneg20_ypos26_place1_room2_floora place1_door_room2_bathroom)
	(locationinplace location_xneg21_yneg28_place12_room8_floora place12_receptacle2_oven)
	(locationinplace location_xneg22_yneg11_place16_room8_floora place16_receptacle6_refrigerator)
	(locationinplace location_xneg22_yneg22_place12_room8_floora place12_receptacle2_oven)
	(locationinplace location_xneg2_yneg10_place7_room3_floora place7_door_room3_bedroom)
	(locationinplace location_xneg2_ypos45_place2_room1_floora place2_door_room1_bathroom)
	(locationinplace location_xneg31_ypos5_place5_room6_floora place5_door_room6_corridor)
	(locationinplace location_xneg32_yneg17_place0_room8_floora place0_door_room8_kitchen)
	(locationinplace location_xneg33_ypos6_place10_room6_floora place10_item20_apple)
	(locationinplace location_xneg34_ypos33_place8_room5_floora place8_door_room5_closet)
	(locationinplace location_xneg36_yneg26_place11_room8_floora place11_receptacle1_microwave)
	(locationinplace location_xneg3_ypos25_place9_room10_floora place9_door_room10_lobby)
	(locationinplace location_xneg42_yneg16_place14_room8_floora place14_receptacle4_sink)
	(locationinplace location_xneg42_yneg28_place11_room8_floora place11_receptacle1_microwave)
	(locationinplace location_xneg42_yneg9_place14_room8_floora place14_receptacle4_sink)
	(locationinplace location_xneg44_yneg26_place11_room8_floora place11_receptacle1_microwave)
	(locationinplace location_xneg44_yneg28_place11_room8_floora place11_receptacle1_microwave)
	(locationinplace location_xneg47_yneg28_place22_room7_floora place22_receptacle38_dining_table)
	(locationinplace location_xneg49_yneg22_place22_room7_floora place22_receptacle38_dining_table)
	(locationinplace location_xneg51_yneg23_place25_room7_floora place25_receptacle23_chair)
	(locationinplace location_xneg53_ypos24_place6_room4_floora place6_door_room4_bedroom)
	(locationinplace location_xneg54_yneg29_place20_room7_floora place20_receptacle36_dining_table)
	(locationinplace location_xneg56_yneg17_place4_room7_floora place4_door_room7_dining_room)
	(locationinplace location_xneg56_yneg23_place20_room7_floora place20_receptacle36_dining_table)
	(locationinplace location_xneg57_yneg28_place21_room7_floora place21_receptacle37_dining_table)
	(locationinplace location_xneg57_yneg29_place20_room7_floora place20_receptacle36_dining_table)
	(locationinplace location_xneg61_yneg29_place20_room7_floora place20_receptacle36_dining_table)
	(locationinplace location_xneg61_ypos28_place18_room4_floora place18_receptacle34_bed)
	(locationinplace location_xneg62_yneg23_place26_room7_floora place26_receptacle24_chair)
	(locationinplace location_xneg6_yneg18_place19_room3_floora place19_receptacle35_bed)
	(locationinplace location_xneg71_ypos2_place24_room9_floora place24_receptacle22_chair)
	(locationinplace location_xneg82_yneg24_place29_room9_floora place29_receptacle27_chair)
	(locationinplace location_xneg82_yneg6_place30_room9_floora place30_receptacle29_couch)
	(locationinplace location_xneg83_yneg11_place3_room9_floora place3_door_room9_living_room)
	(locationinplace location_xneg83_yneg22_place27_room9_floora place27_receptacle25_chair)
	(locationinplace location_xneg85_yneg26_place28_room9_floora place28_receptacle26_chair)
	(locationinplace location_xneg94_yneg7_place30_room9_floora place30_receptacle29_couch)
	(locationinplace location_xneg9_ypos37_place17_room1_floora place17_receptacle7_refrigerator)
	(locationinplace location_xpos5_ypos54_place23_room1_floora place23_receptacle21_toilet)
	(locationinplace location_xpos6_ypos39_place15_room1_floora place15_receptacle5_sink)
	(locationinplace location_xpos8_ypos42_place15_room1_floora place15_receptacle5_sink)
	(placeinroom place0_door_room8_kitchen room8_kitchen)
	(placeinroom place10_item20_apple room6_corridor)
	(placeinroom place11_receptacle1_microwave room8_kitchen)
	(placeinroom place12_receptacle2_oven room8_kitchen)
	(placeinroom place13_receptacle3_sink room2_bathroom)
	(placeinroom place14_receptacle4_sink room8_kitchen)
	(placeinroom place15_receptacle5_sink room1_bathroom)
	(placeinroom place16_receptacle6_refrigerator room8_kitchen)
	(placeinroom place17_receptacle7_refrigerator room1_bathroom)
	(placeinroom place18_receptacle34_bed room4_bedroom)
	(placeinroom place19_receptacle35_bed room3_bedroom)
	(placeinroom place1_door_room2_bathroom room2_bathroom)
	(placeinroom place20_receptacle36_dining_table room7_dining_room)
	(placeinroom place21_receptacle37_dining_table room7_dining_room)
	(placeinroom place22_receptacle38_dining_table room7_dining_room)
	(placeinroom place23_receptacle21_toilet room1_bathroom)
	(placeinroom place24_receptacle22_chair room9_living_room)
	(placeinroom place25_receptacle23_chair room7_dining_room)
	(placeinroom place26_receptacle24_chair room7_dining_room)
	(placeinroom place27_receptacle25_chair room9_living_room)
	(placeinroom place28_receptacle26_chair room9_living_room)
	(placeinroom place29_receptacle27_chair room9_living_room)
	(placeinroom place2_door_room1_bathroom room1_bathroom)
	(placeinroom place30_receptacle29_couch room9_living_room)
	(placeinroom place3_door_room9_living_room room9_living_room)
	(placeinroom place4_door_room7_dining_room room7_dining_room)
	(placeinroom place5_door_room6_corridor room6_corridor)
	(placeinroom place6_door_room4_bedroom room4_bedroom)
	(placeinroom place7_door_room3_bedroom room3_bedroom)
	(placeinroom place8_door_room5_closet room5_closet)
	(placeinroom place9_door_room10_lobby room10_lobby)
	(placelocation location_xneg14_ypos23_place13_room2_floora place13_receptacle3_sink)
	(placelocation location_xneg20_ypos26_place1_room2_floora place1_door_room2_bathroom)
	(placelocation location_xneg22_yneg11_place16_room8_floora place16_receptacle6_refrigerator)
	(placelocation location_xneg22_yneg22_place12_room8_floora place12_receptacle2_oven)
	(placelocation location_xneg2_yneg10_place7_room3_floora place7_door_room3_bedroom)
	(placelocation location_xneg2_ypos45_place2_room1_floora place2_door_room1_bathroom)
	(placelocation location_xneg31_ypos5_place5_room6_floora place5_door_room6_corridor)
	(placelocation location_xneg32_yneg17_place0_room8_floora place0_door_room8_kitchen)
	(placelocation location_xneg33_ypos6_place10_room6_floora place10_item20_apple)
	(placelocation location_xneg34_ypos33_place8_room5_floora place8_door_room5_closet)
	(placelocation location_xneg36_yneg26_place11_room8_floora place11_receptacle1_microwave)
	(placelocation location_xneg3_ypos25_place9_room10_floora place9_door_room10_lobby)
	(placelocation location_xneg42_yneg16_place14_room8_floora place14_receptacle4_sink)
	(placelocation location_xneg49_yneg22_place22_room7_floora place22_receptacle38_dining_table)
	(placelocation location_xneg51_yneg23_place25_room7_floora place25_receptacle23_chair)
	(placelocation location_xneg53_ypos24_place6_room4_floora place6_door_room4_bedroom)
	(placelocation location_xneg56_yneg17_place4_room7_floora place4_door_room7_dining_room)
	(placelocation location_xneg56_yneg23_place20_room7_floora place20_receptacle36_dining_table)
	(placelocation location_xneg57_yneg28_place21_room7_floora place21_receptacle37_dining_table)
	(placelocation location_xneg61_ypos28_place18_room4_floora place18_receptacle34_bed)
	(placelocation location_xneg62_yneg23_place26_room7_floora place26_receptacle24_chair)
	(placelocation location_xneg6_yneg18_place19_room3_floora place19_receptacle35_bed)
	(placelocation location_xneg71_ypos2_place24_room9_floora place24_receptacle22_chair)
	(placelocation location_xneg82_yneg24_place29_room9_floora place29_receptacle27_chair)
	(placelocation location_xneg83_yneg11_place3_room9_floora place3_door_room9_living_room)
	(placelocation location_xneg83_yneg22_place27_room9_floora place27_receptacle25_chair)
	(placelocation location_xneg85_yneg26_place28_room9_floora place28_receptacle26_chair)
	(placelocation location_xneg94_yneg7_place30_room9_floora place30_receptacle29_couch)
	(placelocation location_xneg9_ypos37_place17_room1_floora place17_receptacle7_refrigerator)
	(placelocation location_xpos5_ypos54_place23_room1_floora place23_receptacle21_toilet)
	(placelocation location_xpos6_ypos39_place15_room1_floora place15_receptacle5_sink)
	(receptacleatlocation receptacle1_microwave location_xneg36_yneg26_place11_room8_floora)
	(receptacleatlocation receptacle21_toilet location_xpos5_ypos54_place23_room1_floora)
	(receptacleatlocation receptacle22_chair location_xneg71_ypos2_place24_room9_floora)
	(receptacleatlocation receptacle23_chair location_xneg51_yneg23_place25_room7_floora)
	(receptacleatlocation receptacle24_chair location_xneg62_yneg23_place26_room7_floora)
	(receptacleatlocation receptacle25_chair location_xneg83_yneg22_place27_room9_floora)
	(receptacleatlocation receptacle26_chair location_xneg85_yneg26_place28_room9_floora)
	(receptacleatlocation receptacle27_chair location_xneg82_yneg24_place29_room9_floora)
	(receptacleatlocation receptacle29_couch location_xneg94_yneg7_place30_room9_floora)
	(receptacleatlocation receptacle2_oven location_xneg22_yneg22_place12_room8_floora)
	(receptacleatlocation receptacle34_bed location_xneg61_ypos28_place18_room4_floora)
	(receptacleatlocation receptacle35_bed location_xneg6_yneg18_place19_room3_floora)
	(receptacleatlocation receptacle36_dining_table location_xneg56_yneg23_place20_room7_floora)
	(receptacleatlocation receptacle37_dining_table location_xneg57_yneg28_place21_room7_floora)
	(receptacleatlocation receptacle38_dining_table location_xneg49_yneg22_place22_room7_floora)
	(receptacleatlocation receptacle3_sink location_xneg14_ypos23_place13_room2_floora)
	(receptacleatlocation receptacle4_sink location_xneg42_yneg16_place14_room8_floora)
	(receptacleatlocation receptacle5_sink location_xpos6_ypos39_place15_room1_floora)
	(receptacleatlocation receptacle6_refrigerator location_xneg22_yneg11_place16_room8_floora)
	(receptacleatlocation receptacle7_refrigerator location_xneg9_ypos37_place17_room1_floora)
	(receptacleclass receptacle1_microwave microwave)
	(receptacleclass receptacle21_toilet toilet)
	(receptacleclass receptacle22_chair chair)
	(receptacleclass receptacle23_chair chair)
	(receptacleclass receptacle24_chair chair)
	(receptacleclass receptacle25_chair chair)
	(receptacleclass receptacle26_chair chair)
	(receptacleclass receptacle27_chair chair)
	(receptacleclass receptacle29_couch couch)
	(receptacleclass receptacle2_oven oven)
	(receptacleclass receptacle34_bed bed)
	(receptacleclass receptacle35_bed bed)
	(receptacleclass receptacle36_dining_table diningtable)
	(receptacleclass receptacle37_dining_table diningtable)
	(receptacleclass receptacle38_dining_table diningtable)
	(receptacleclass receptacle3_sink sink)
	(receptacleclass receptacle4_sink sink)
	(receptacleclass receptacle5_sink sink)
	(receptacleclass receptacle6_refrigerator refrigerator)
	(receptacleclass receptacle7_refrigerator refrigerator)
	(receptacleopeningtype receptacle1_microwave)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle6_refrigerator)
	(receptacleopeningtype receptacle7_refrigerator)
	(roomplace place0_door_room8_kitchen room8_kitchen)
	(roomplace place1_door_room2_bathroom room2_bathroom)
	(roomplace place2_door_room1_bathroom room1_bathroom)
	(roomplace place3_door_room9_living_room room9_living_room)
	(roomplace place4_door_room7_dining_room room7_dining_room)
	(roomplace place5_door_room6_corridor room6_corridor)
	(roomplace place6_door_room4_bedroom room4_bedroom)
	(roomplace place7_door_room3_bedroom room3_bedroom)
	(roomplace place8_door_room5_closet room5_closet)
	(roomplace place9_door_room10_lobby room10_lobby)
	(roomsconnected room10_lobby room1_bathroom)
	(roomsconnected room10_lobby room2_bathroom)
	(roomsconnected room1_bathroom room10_lobby)
	(roomsconnected room2_bathroom room10_lobby)
	(roomsconnected room2_bathroom room5_closet)
	(roomsconnected room2_bathroom room6_corridor)
	(roomsconnected room3_bedroom room8_kitchen)
	(roomsconnected room4_bedroom room5_closet)
	(roomsconnected room5_closet room2_bathroom)
	(roomsconnected room5_closet room4_bedroom)
	(roomsconnected room6_corridor room2_bathroom)
	(roomsconnected room6_corridor room8_kitchen)
	(roomsconnected room7_dining_room room8_kitchen)
	(roomsconnected room7_dining_room room9_living_room)
	(roomsconnected room8_kitchen room3_bedroom)
	(roomsconnected room8_kitchen room6_corridor)
	(roomsconnected room8_kitchen room7_dining_room)
	(roomsconnected room9_living_room room7_dining_room)
  )
  (:goal (and
	(classrelation vase chair)
	(classrelation cup refrigerator)
	(classrelation cup chair)
	(classrelation clock sink)
	(classrelation vase toilet)))
)
