
(define (problem hildebrantaskographyv4medium5problem37) (:domain taskographyv4medium5scrub)
  (:objects
        apple - iclass
	backpack - iclass
	banana - iclass
	baseballbat - iclass
	baseballglove - iclass
	bed - rclass
	bench - rclass
	bicycle - iclass
	boat - rclass
	book - iclass
	bottle - iclass
	bowl - iclass
	cake - iclass
	cellphone - iclass
	chair - rclass
	clock - iclass
	couch - rclass
	cup - iclass
	diningtable - rclass
	frisbee - iclass
	handbag - iclass
	item12_book_smallitem - item
	item13_book_smallitem - item
	item14_book_smallitem - item
	item15_vase_mediumitem - item
	item16_vase_mediumitem - item
	item17_vase_mediumitem - item
	item18_vase_mediumitem - item
	item19_cup_smallitem - item
	item20_cup_smallitem - item
	item21_bowl_smallitem - item
	item22_bowl_smallitem - item
	item3_bottle_smallitem - item
	item41_potted_plant_largeitem - item
	item42_potted_plant_largeitem - item
	item43_potted_plant_largeitem - item
	item4_bottle_smallitem - item
	keyboard - iclass
	kite - iclass
	knife - iclass
	laptop - iclass
	location_xneg10_yneg33_place41_room4_floora - location
	location_xneg11_yneg10_place12_room8_floora - location
	location_xneg12_yneg10_place8_room8_floora - location
	location_xneg12_yneg70_place44_room3_floora - location
	location_xneg12_ypos10_place5_room8_floora - location
	location_xneg15_yneg30_place7_room4_floora - location
	location_xneg15_yneg63_place4_room3_floora - location
	location_xneg15_ypos11_place39_room8_floora - location
	location_xneg15_ypos24_place39_room8_floora - location
	location_xneg15_ypos31_place40_room8_floora - location
	location_xneg16_ypos10_place39_room8_floora - location
	location_xneg34_yneg28_place13_room5_floora - location
	location_xneg34_yneg88_place24_room2_floora - location
	location_xneg35_yneg28_place9_room5_floora - location
	location_xneg35_ypos16_place29_room6_floora - location
	location_xneg37_yneg88_place25_room2_floora - location
	location_xneg38_ypos19_place32_room6_floora - location
	location_xneg39_yneg3_place28_room7_floora - location
	location_xneg39_ypos15_place45_room6_floora - location
	location_xneg3_yneg10_place10_room8_floora - location
	location_xneg40_ypos11_place31_room6_floora - location
	location_xneg40_ypos11_place6_room6_floora - location
	location_xneg41_yneg62_place22_room2_floora - location
	location_xneg41_yneg64_place22_room2_floora - location
	location_xneg41_ypos22_place26_room6_floora - location
	location_xneg42_yneg7_place28_room7_floora - location
	location_xneg43_ypos13_place27_room6_floora - location
	location_xneg43_ypos19_place46_room6_floora - location
	location_xneg44_ypos2_place30_room7_floora - location
	location_xneg46_ypos16_place34_room6_floora - location
	location_xneg48_yneg2_place19_room7_floora - location
	location_xneg49_ypos8_place33_room7_floora - location
	location_xneg51_yneg74_place3_room2_floora - location
	location_xneg51_ypos11_place35_room7_floora - location
	location_xneg53_yneg4_place0_room7_floora - location
	location_xneg55_yneg36_place2_room5_floora - location
	location_xneg5_yneg48_place38_room3_floora - location
	location_xneg60_ypos2_place14_room7_floora - location
	location_xneg61_yneg16_place16_room7_floora - location
	location_xneg62_yneg27_place43_room5_floora - location
	location_xneg63_yneg4_place14_room7_floora - location
	location_xneg63_yneg4_place15_room7_floora - location
	location_xneg67_yneg23_place21_room1_floora - location
	location_xneg73_yneg21_place21_room1_floora - location
	location_xneg74_yneg13_place16_room7_floora - location
	location_xneg79_yneg68_place18_room5_floora - location
	location_xneg80_yneg33_place1_room1_floora - location
	location_xneg83_yneg25_place23_room1_floora - location
	location_xneg89_yneg41_place20_room1_floora - location
	location_xneg90_yneg48_place17_room1_floora - location
	location_xneg91_yneg36_place20_room1_floora - location
	location_xpos0_yneg12_place11_room8_floora - location
	location_xpos0_yneg46_place38_room3_floora - location
	location_xpos1_yneg50_place38_room3_floora - location
	location_xpos2_ypos12_place37_room8_floora - location
	location_xpos4_yneg45_place42_room4_floora - location
	location_xpos5_ypos10_place36_room8_floora - location
	microwave - rclass
	motorcycle - iclass
	mouse - iclass
	orange - iclass
	oven - rclass
	place0_door_room7_kitchen - place
	place10_item15_vase - place
	place11_item16_vase - place
	place12_item17_vase - place
	place13_item19_cup - place
	place14_receptacle1_microwave - place
	place15_receptacle2_oven - place
	place16_receptacle5_refrigerator - place
	place17_receptacle6_refrigerator - place
	place18_receptacle7_refrigerator - place
	place19_receptacle8_sink - place
	place1_door_room1_bathroom - place
	place20_receptacle9_sink - place
	place21_receptacle10_sink - place
	place22_receptacle11_sink - place
	place23_receptacle23_toilet - place
	place24_receptacle24_toilet - place
	place25_receptacle25_toilet - place
	place26_receptacle26_chair - place
	place27_receptacle27_chair - place
	place28_receptacle28_chair - place
	place29_receptacle29_chair - place
	place2_door_room5_corridor - place
	place30_receptacle30_chair - place
	place31_receptacle31_chair - place
	place32_receptacle32_chair - place
	place33_receptacle33_chair - place
	place34_receptacle34_chair - place
	place35_receptacle35_chair - place
	place36_receptacle36_chair - place
	place37_receptacle37_chair - place
	place38_receptacle38_chair - place
	place39_receptacle39_couch - place
	place3_door_room2_bathroom - place
	place40_receptacle40_couch - place
	place41_receptacle44_bed - place
	place42_receptacle45_bed - place
	place43_receptacle46_bed - place
	place44_receptacle47_bed - place
	place45_receptacle48_dining_table - place
	place46_receptacle49_dining_table - place
	place4_door_room3_bedroom - place
	place5_door_room8_living_room - place
	place6_door_room6_dining_room - place
	place7_door_room4_bedroom - place
	place8_item41_potted_plant - place
	place9_item12_book - place
	pottedplant - iclass
	receptacle10_sink - receptacle
	receptacle11_sink - receptacle
	receptacle1_microwave - receptacle
	receptacle23_toilet - receptacle
	receptacle24_toilet - receptacle
	receptacle25_toilet - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_chair - receptacle
	receptacle2_oven - receptacle
	receptacle30_chair - receptacle
	receptacle31_chair - receptacle
	receptacle32_chair - receptacle
	receptacle33_chair - receptacle
	receptacle34_chair - receptacle
	receptacle35_chair - receptacle
	receptacle36_chair - receptacle
	receptacle37_chair - receptacle
	receptacle38_chair - receptacle
	receptacle39_couch - receptacle
	receptacle40_couch - receptacle
	receptacle44_bed - receptacle
	receptacle45_bed - receptacle
	receptacle46_bed - receptacle
	receptacle47_bed - receptacle
	receptacle48_dining_table - receptacle
	receptacle49_dining_table - receptacle
	receptacle5_refrigerator - receptacle
	receptacle6_refrigerator - receptacle
	receptacle7_refrigerator - receptacle
	receptacle8_sink - receptacle
	receptacle9_sink - receptacle
	refrigerator - rclass
	remote - iclass
	robot - agent
	room1_bathroom - room
	room2_bathroom - room
	room3_bedroom - room
	room4_bedroom - room
	room5_corridor - room
	room6_dining_room - room
	room7_kitchen - room
	room8_living_room - room
	sink - rclass
	spoon - iclass
	sportsball - iclass
	suitcase - iclass
	surfboard - iclass
	teddybear - iclass
	tie - iclass
	toaster - rclass
	toilet - rclass
	toothbrush - iclass
	tv - iclass
	umbrella - iclass
	vase - iclass
	wineglass - iclass
  )
  (:init 
	(atlocation robot location_xneg53_yneg4_place0_room7_floora)
	(classrelation book chair)
	(classrelation bottle microwave)
	(classrelation bottle sink)
	(classrelation bowl chair)
	(classrelation bowl sink)
	(classrelation cup refrigerator)
	(classrelation pottedplant couch)
	(classrelation pottedplant sink)
	(classrelation vase couch)
	(inanyreceptacle item13_book_smallitem)
	(inanyreceptacle item14_book_smallitem)
	(inanyreceptacle item18_vase_mediumitem)
	(inanyreceptacle item20_cup_smallitem)
	(inanyreceptacle item21_bowl_smallitem)
	(inanyreceptacle item22_bowl_smallitem)
	(inanyreceptacle item3_bottle_smallitem)
	(inanyreceptacle item42_potted_plant_largeitem)
	(inanyreceptacle item43_potted_plant_largeitem)
	(inanyreceptacle item4_bottle_smallitem)
	(inplace robot place0_door_room7_kitchen)
	(inreceptacle item13_book_smallitem receptacle38_chair)
	(inreceptacle item14_book_smallitem receptacle38_chair)
	(inreceptacle item18_vase_mediumitem receptacle39_couch)
	(inreceptacle item20_cup_smallitem receptacle5_refrigerator)
	(inreceptacle item21_bowl_smallitem receptacle28_chair)
	(inreceptacle item22_bowl_smallitem receptacle9_sink)
	(inreceptacle item3_bottle_smallitem receptacle1_microwave)
	(inreceptacle item42_potted_plant_largeitem receptacle39_couch)
	(inreceptacle item43_potted_plant_largeitem receptacle11_sink)
	(inreceptacle item4_bottle_smallitem receptacle10_sink)
	(inroom robot room7_kitchen)
	(itematlocation item12_book_smallitem location_xneg35_yneg28_place9_room5_floora)
	(itematlocation item13_book_smallitem location_xneg5_yneg48_place38_room3_floora)
	(itematlocation item14_book_smallitem location_xpos0_yneg46_place38_room3_floora)
	(itematlocation item15_vase_mediumitem location_xneg3_yneg10_place10_room8_floora)
	(itematlocation item16_vase_mediumitem location_xpos0_yneg12_place11_room8_floora)
	(itematlocation item17_vase_mediumitem location_xneg11_yneg10_place12_room8_floora)
	(itematlocation item18_vase_mediumitem location_xneg16_ypos10_place39_room8_floora)
	(itematlocation item19_cup_smallitem location_xneg34_yneg28_place13_room5_floora)
	(itematlocation item20_cup_smallitem location_xneg74_yneg13_place16_room7_floora)
	(itematlocation item21_bowl_smallitem location_xneg42_yneg7_place28_room7_floora)
	(itematlocation item22_bowl_smallitem location_xneg91_yneg36_place20_room1_floora)
	(itematlocation item3_bottle_smallitem location_xneg60_ypos2_place14_room7_floora)
	(itematlocation item41_potted_plant_largeitem location_xneg12_yneg10_place8_room8_floora)
	(itematlocation item42_potted_plant_largeitem location_xneg15_ypos11_place39_room8_floora)
	(itematlocation item43_potted_plant_largeitem location_xneg41_yneg62_place22_room2_floora)
	(itematlocation item4_bottle_smallitem location_xneg67_yneg23_place21_room1_floora)
	(itemclass item12_book_smallitem book)
	(itemclass item13_book_smallitem book)
	(itemclass item14_book_smallitem book)
	(itemclass item15_vase_mediumitem vase)
	(itemclass item16_vase_mediumitem vase)
	(itemclass item17_vase_mediumitem vase)
	(itemclass item18_vase_mediumitem vase)
	(itemclass item19_cup_smallitem cup)
	(itemclass item20_cup_smallitem cup)
	(itemclass item21_bowl_smallitem bowl)
	(itemclass item22_bowl_smallitem bowl)
	(itemclass item3_bottle_smallitem bottle)
	(itemclass item41_potted_plant_largeitem pottedplant)
	(itemclass item42_potted_plant_largeitem pottedplant)
	(itemclass item43_potted_plant_largeitem pottedplant)
	(itemclass item4_bottle_smallitem bottle)
	(locationinplace location_xneg10_yneg33_place41_room4_floora place41_receptacle44_bed)
	(locationinplace location_xneg11_yneg10_place12_room8_floora place12_item17_vase)
	(locationinplace location_xneg12_yneg10_place8_room8_floora place8_item41_potted_plant)
	(locationinplace location_xneg12_yneg70_place44_room3_floora place44_receptacle47_bed)
	(locationinplace location_xneg12_ypos10_place5_room8_floora place5_door_room8_living_room)
	(locationinplace location_xneg15_yneg30_place7_room4_floora place7_door_room4_bedroom)
	(locationinplace location_xneg15_yneg63_place4_room3_floora place4_door_room3_bedroom)
	(locationinplace location_xneg15_ypos11_place39_room8_floora place39_receptacle39_couch)
	(locationinplace location_xneg15_ypos24_place39_room8_floora place39_receptacle39_couch)
	(locationinplace location_xneg15_ypos31_place40_room8_floora place40_receptacle40_couch)
	(locationinplace location_xneg16_ypos10_place39_room8_floora place39_receptacle39_couch)
	(locationinplace location_xneg34_yneg28_place13_room5_floora place13_item19_cup)
	(locationinplace location_xneg34_yneg88_place24_room2_floora place24_receptacle24_toilet)
	(locationinplace location_xneg35_yneg28_place9_room5_floora place9_item12_book)
	(locationinplace location_xneg35_ypos16_place29_room6_floora place29_receptacle29_chair)
	(locationinplace location_xneg37_yneg88_place25_room2_floora place25_receptacle25_toilet)
	(locationinplace location_xneg38_ypos19_place32_room6_floora place32_receptacle32_chair)
	(locationinplace location_xneg39_yneg3_place28_room7_floora place28_receptacle28_chair)
	(locationinplace location_xneg39_ypos15_place45_room6_floora place45_receptacle48_dining_table)
	(locationinplace location_xneg3_yneg10_place10_room8_floora place10_item15_vase)
	(locationinplace location_xneg40_ypos11_place31_room6_floora place31_receptacle31_chair)
	(locationinplace location_xneg40_ypos11_place6_room6_floora place6_door_room6_dining_room)
	(locationinplace location_xneg41_yneg62_place22_room2_floora place22_receptacle11_sink)
	(locationinplace location_xneg41_yneg64_place22_room2_floora place22_receptacle11_sink)
	(locationinplace location_xneg41_ypos22_place26_room6_floora place26_receptacle26_chair)
	(locationinplace location_xneg42_yneg7_place28_room7_floora place28_receptacle28_chair)
	(locationinplace location_xneg43_ypos13_place27_room6_floora place27_receptacle27_chair)
	(locationinplace location_xneg43_ypos19_place46_room6_floora place46_receptacle49_dining_table)
	(locationinplace location_xneg44_ypos2_place30_room7_floora place30_receptacle30_chair)
	(locationinplace location_xneg46_ypos16_place34_room6_floora place34_receptacle34_chair)
	(locationinplace location_xneg48_yneg2_place19_room7_floora place19_receptacle8_sink)
	(locationinplace location_xneg49_ypos8_place33_room7_floora place33_receptacle33_chair)
	(locationinplace location_xneg51_yneg74_place3_room2_floora place3_door_room2_bathroom)
	(locationinplace location_xneg51_ypos11_place35_room7_floora place35_receptacle35_chair)
	(locationinplace location_xneg53_yneg4_place0_room7_floora place0_door_room7_kitchen)
	(locationinplace location_xneg55_yneg36_place2_room5_floora place2_door_room5_corridor)
	(locationinplace location_xneg5_yneg48_place38_room3_floora place38_receptacle38_chair)
	(locationinplace location_xneg60_ypos2_place14_room7_floora place14_receptacle1_microwave)
	(locationinplace location_xneg61_yneg16_place16_room7_floora place16_receptacle5_refrigerator)
	(locationinplace location_xneg62_yneg27_place43_room5_floora place43_receptacle46_bed)
	(locationinplace location_xneg63_yneg4_place14_room7_floora place14_receptacle1_microwave)
	(locationinplace location_xneg63_yneg4_place15_room7_floora place15_receptacle2_oven)
	(locationinplace location_xneg67_yneg23_place21_room1_floora place21_receptacle10_sink)
	(locationinplace location_xneg73_yneg21_place21_room1_floora place21_receptacle10_sink)
	(locationinplace location_xneg74_yneg13_place16_room7_floora place16_receptacle5_refrigerator)
	(locationinplace location_xneg79_yneg68_place18_room5_floora place18_receptacle7_refrigerator)
	(locationinplace location_xneg80_yneg33_place1_room1_floora place1_door_room1_bathroom)
	(locationinplace location_xneg83_yneg25_place23_room1_floora place23_receptacle23_toilet)
	(locationinplace location_xneg89_yneg41_place20_room1_floora place20_receptacle9_sink)
	(locationinplace location_xneg90_yneg48_place17_room1_floora place17_receptacle6_refrigerator)
	(locationinplace location_xneg91_yneg36_place20_room1_floora place20_receptacle9_sink)
	(locationinplace location_xpos0_yneg12_place11_room8_floora place11_item16_vase)
	(locationinplace location_xpos0_yneg46_place38_room3_floora place38_receptacle38_chair)
	(locationinplace location_xpos1_yneg50_place38_room3_floora place38_receptacle38_chair)
	(locationinplace location_xpos2_ypos12_place37_room8_floora place37_receptacle37_chair)
	(locationinplace location_xpos4_yneg45_place42_room4_floora place42_receptacle45_bed)
	(locationinplace location_xpos5_ypos10_place36_room8_floora place36_receptacle36_chair)
	(placeinroom place0_door_room7_kitchen room7_kitchen)
	(placeinroom place10_item15_vase room8_living_room)
	(placeinroom place11_item16_vase room8_living_room)
	(placeinroom place12_item17_vase room8_living_room)
	(placeinroom place13_item19_cup room5_corridor)
	(placeinroom place14_receptacle1_microwave room7_kitchen)
	(placeinroom place15_receptacle2_oven room7_kitchen)
	(placeinroom place16_receptacle5_refrigerator room7_kitchen)
	(placeinroom place17_receptacle6_refrigerator room1_bathroom)
	(placeinroom place18_receptacle7_refrigerator room5_corridor)
	(placeinroom place19_receptacle8_sink room7_kitchen)
	(placeinroom place1_door_room1_bathroom room1_bathroom)
	(placeinroom place20_receptacle9_sink room1_bathroom)
	(placeinroom place21_receptacle10_sink room1_bathroom)
	(placeinroom place22_receptacle11_sink room2_bathroom)
	(placeinroom place23_receptacle23_toilet room1_bathroom)
	(placeinroom place24_receptacle24_toilet room2_bathroom)
	(placeinroom place25_receptacle25_toilet room2_bathroom)
	(placeinroom place26_receptacle26_chair room6_dining_room)
	(placeinroom place27_receptacle27_chair room6_dining_room)
	(placeinroom place28_receptacle28_chair room7_kitchen)
	(placeinroom place29_receptacle29_chair room6_dining_room)
	(placeinroom place2_door_room5_corridor room5_corridor)
	(placeinroom place30_receptacle30_chair room7_kitchen)
	(placeinroom place31_receptacle31_chair room6_dining_room)
	(placeinroom place32_receptacle32_chair room6_dining_room)
	(placeinroom place33_receptacle33_chair room7_kitchen)
	(placeinroom place34_receptacle34_chair room6_dining_room)
	(placeinroom place35_receptacle35_chair room7_kitchen)
	(placeinroom place36_receptacle36_chair room8_living_room)
	(placeinroom place37_receptacle37_chair room8_living_room)
	(placeinroom place38_receptacle38_chair room3_bedroom)
	(placeinroom place39_receptacle39_couch room8_living_room)
	(placeinroom place3_door_room2_bathroom room2_bathroom)
	(placeinroom place40_receptacle40_couch room8_living_room)
	(placeinroom place41_receptacle44_bed room4_bedroom)
	(placeinroom place42_receptacle45_bed room4_bedroom)
	(placeinroom place43_receptacle46_bed room5_corridor)
	(placeinroom place44_receptacle47_bed room3_bedroom)
	(placeinroom place45_receptacle48_dining_table room6_dining_room)
	(placeinroom place46_receptacle49_dining_table room6_dining_room)
	(placeinroom place4_door_room3_bedroom room3_bedroom)
	(placeinroom place5_door_room8_living_room room8_living_room)
	(placeinroom place6_door_room6_dining_room room6_dining_room)
	(placeinroom place7_door_room4_bedroom room4_bedroom)
	(placeinroom place8_item41_potted_plant room8_living_room)
	(placeinroom place9_item12_book room5_corridor)
	(placelocation location_xneg10_yneg33_place41_room4_floora place41_receptacle44_bed)
	(placelocation location_xneg11_yneg10_place12_room8_floora place12_item17_vase)
	(placelocation location_xneg12_yneg10_place8_room8_floora place8_item41_potted_plant)
	(placelocation location_xneg12_yneg70_place44_room3_floora place44_receptacle47_bed)
	(placelocation location_xneg12_ypos10_place5_room8_floora place5_door_room8_living_room)
	(placelocation location_xneg15_yneg30_place7_room4_floora place7_door_room4_bedroom)
	(placelocation location_xneg15_yneg63_place4_room3_floora place4_door_room3_bedroom)
	(placelocation location_xneg15_ypos24_place39_room8_floora place39_receptacle39_couch)
	(placelocation location_xneg15_ypos31_place40_room8_floora place40_receptacle40_couch)
	(placelocation location_xneg34_yneg28_place13_room5_floora place13_item19_cup)
	(placelocation location_xneg34_yneg88_place24_room2_floora place24_receptacle24_toilet)
	(placelocation location_xneg35_yneg28_place9_room5_floora place9_item12_book)
	(placelocation location_xneg35_ypos16_place29_room6_floora place29_receptacle29_chair)
	(placelocation location_xneg37_yneg88_place25_room2_floora place25_receptacle25_toilet)
	(placelocation location_xneg38_ypos19_place32_room6_floora place32_receptacle32_chair)
	(placelocation location_xneg39_yneg3_place28_room7_floora place28_receptacle28_chair)
	(placelocation location_xneg39_ypos15_place45_room6_floora place45_receptacle48_dining_table)
	(placelocation location_xneg3_yneg10_place10_room8_floora place10_item15_vase)
	(placelocation location_xneg40_ypos11_place31_room6_floora place31_receptacle31_chair)
	(placelocation location_xneg40_ypos11_place6_room6_floora place6_door_room6_dining_room)
	(placelocation location_xneg41_yneg64_place22_room2_floora place22_receptacle11_sink)
	(placelocation location_xneg41_ypos22_place26_room6_floora place26_receptacle26_chair)
	(placelocation location_xneg43_ypos13_place27_room6_floora place27_receptacle27_chair)
	(placelocation location_xneg43_ypos19_place46_room6_floora place46_receptacle49_dining_table)
	(placelocation location_xneg44_ypos2_place30_room7_floora place30_receptacle30_chair)
	(placelocation location_xneg46_ypos16_place34_room6_floora place34_receptacle34_chair)
	(placelocation location_xneg48_yneg2_place19_room7_floora place19_receptacle8_sink)
	(placelocation location_xneg49_ypos8_place33_room7_floora place33_receptacle33_chair)
	(placelocation location_xneg51_yneg74_place3_room2_floora place3_door_room2_bathroom)
	(placelocation location_xneg51_ypos11_place35_room7_floora place35_receptacle35_chair)
	(placelocation location_xneg53_yneg4_place0_room7_floora place0_door_room7_kitchen)
	(placelocation location_xneg55_yneg36_place2_room5_floora place2_door_room5_corridor)
	(placelocation location_xneg61_yneg16_place16_room7_floora place16_receptacle5_refrigerator)
	(placelocation location_xneg62_yneg27_place43_room5_floora place43_receptacle46_bed)
	(placelocation location_xneg63_yneg4_place14_room7_floora place14_receptacle1_microwave)
	(placelocation location_xneg63_yneg4_place15_room7_floora place15_receptacle2_oven)
	(placelocation location_xneg73_yneg21_place21_room1_floora place21_receptacle10_sink)
	(placelocation location_xneg79_yneg68_place18_room5_floora place18_receptacle7_refrigerator)
	(placelocation location_xneg80_yneg33_place1_room1_floora place1_door_room1_bathroom)
	(placelocation location_xneg83_yneg25_place23_room1_floora place23_receptacle23_toilet)
	(placelocation location_xneg89_yneg41_place20_room1_floora place20_receptacle9_sink)
	(placelocation location_xneg90_yneg48_place17_room1_floora place17_receptacle6_refrigerator)
	(placelocation location_xpos0_yneg12_place11_room8_floora place11_item16_vase)
	(placelocation location_xpos1_yneg50_place38_room3_floora place38_receptacle38_chair)
	(placelocation location_xpos2_ypos12_place37_room8_floora place37_receptacle37_chair)
	(placelocation location_xpos4_yneg45_place42_room4_floora place42_receptacle45_bed)
	(placelocation location_xpos5_ypos10_place36_room8_floora place36_receptacle36_chair)
	(receptacleatlocation receptacle10_sink location_xneg73_yneg21_place21_room1_floora)
	(receptacleatlocation receptacle11_sink location_xneg41_yneg64_place22_room2_floora)
	(receptacleatlocation receptacle1_microwave location_xneg63_yneg4_place14_room7_floora)
	(receptacleatlocation receptacle23_toilet location_xneg83_yneg25_place23_room1_floora)
	(receptacleatlocation receptacle24_toilet location_xneg34_yneg88_place24_room2_floora)
	(receptacleatlocation receptacle25_toilet location_xneg37_yneg88_place25_room2_floora)
	(receptacleatlocation receptacle26_chair location_xneg41_ypos22_place26_room6_floora)
	(receptacleatlocation receptacle27_chair location_xneg43_ypos13_place27_room6_floora)
	(receptacleatlocation receptacle28_chair location_xneg39_yneg3_place28_room7_floora)
	(receptacleatlocation receptacle29_chair location_xneg35_ypos16_place29_room6_floora)
	(receptacleatlocation receptacle2_oven location_xneg63_yneg4_place15_room7_floora)
	(receptacleatlocation receptacle30_chair location_xneg44_ypos2_place30_room7_floora)
	(receptacleatlocation receptacle31_chair location_xneg40_ypos11_place31_room6_floora)
	(receptacleatlocation receptacle32_chair location_xneg38_ypos19_place32_room6_floora)
	(receptacleatlocation receptacle33_chair location_xneg49_ypos8_place33_room7_floora)
	(receptacleatlocation receptacle34_chair location_xneg46_ypos16_place34_room6_floora)
	(receptacleatlocation receptacle35_chair location_xneg51_ypos11_place35_room7_floora)
	(receptacleatlocation receptacle36_chair location_xpos5_ypos10_place36_room8_floora)
	(receptacleatlocation receptacle37_chair location_xpos2_ypos12_place37_room8_floora)
	(receptacleatlocation receptacle38_chair location_xpos1_yneg50_place38_room3_floora)
	(receptacleatlocation receptacle39_couch location_xneg15_ypos24_place39_room8_floora)
	(receptacleatlocation receptacle40_couch location_xneg15_ypos31_place40_room8_floora)
	(receptacleatlocation receptacle44_bed location_xneg10_yneg33_place41_room4_floora)
	(receptacleatlocation receptacle45_bed location_xpos4_yneg45_place42_room4_floora)
	(receptacleatlocation receptacle46_bed location_xneg62_yneg27_place43_room5_floora)
	(receptacleatlocation receptacle47_bed location_xneg12_yneg70_place44_room3_floora)
	(receptacleatlocation receptacle48_dining_table location_xneg39_ypos15_place45_room6_floora)
	(receptacleatlocation receptacle49_dining_table location_xneg43_ypos19_place46_room6_floora)
	(receptacleatlocation receptacle5_refrigerator location_xneg61_yneg16_place16_room7_floora)
	(receptacleatlocation receptacle6_refrigerator location_xneg90_yneg48_place17_room1_floora)
	(receptacleatlocation receptacle7_refrigerator location_xneg79_yneg68_place18_room5_floora)
	(receptacleatlocation receptacle8_sink location_xneg48_yneg2_place19_room7_floora)
	(receptacleatlocation receptacle9_sink location_xneg89_yneg41_place20_room1_floora)
	(receptacleclass receptacle10_sink sink)
	(receptacleclass receptacle11_sink sink)
	(receptacleclass receptacle1_microwave microwave)
	(receptacleclass receptacle23_toilet toilet)
	(receptacleclass receptacle24_toilet toilet)
	(receptacleclass receptacle25_toilet toilet)
	(receptacleclass receptacle26_chair chair)
	(receptacleclass receptacle27_chair chair)
	(receptacleclass receptacle28_chair chair)
	(receptacleclass receptacle29_chair chair)
	(receptacleclass receptacle2_oven oven)
	(receptacleclass receptacle30_chair chair)
	(receptacleclass receptacle31_chair chair)
	(receptacleclass receptacle32_chair chair)
	(receptacleclass receptacle33_chair chair)
	(receptacleclass receptacle34_chair chair)
	(receptacleclass receptacle35_chair chair)
	(receptacleclass receptacle36_chair chair)
	(receptacleclass receptacle37_chair chair)
	(receptacleclass receptacle38_chair chair)
	(receptacleclass receptacle39_couch couch)
	(receptacleclass receptacle40_couch couch)
	(receptacleclass receptacle44_bed bed)
	(receptacleclass receptacle45_bed bed)
	(receptacleclass receptacle46_bed bed)
	(receptacleclass receptacle47_bed bed)
	(receptacleclass receptacle48_dining_table diningtable)
	(receptacleclass receptacle49_dining_table diningtable)
	(receptacleclass receptacle5_refrigerator refrigerator)
	(receptacleclass receptacle6_refrigerator refrigerator)
	(receptacleclass receptacle7_refrigerator refrigerator)
	(receptacleclass receptacle8_sink sink)
	(receptacleclass receptacle9_sink sink)
	(receptacleopeningtype receptacle1_microwave)
	(receptacleopeningtype receptacle2_oven)
	(receptacleopeningtype receptacle5_refrigerator)
	(receptacleopeningtype receptacle6_refrigerator)
	(receptacleopeningtype receptacle7_refrigerator)
	(roomplace place0_door_room7_kitchen room7_kitchen)
	(roomplace place1_door_room1_bathroom room1_bathroom)
	(roomplace place2_door_room5_corridor room5_corridor)
	(roomplace place3_door_room2_bathroom room2_bathroom)
	(roomplace place4_door_room3_bedroom room3_bedroom)
	(roomplace place5_door_room8_living_room room8_living_room)
	(roomplace place6_door_room6_dining_room room6_dining_room)
	(roomplace place7_door_room4_bedroom room4_bedroom)
	(roomsconnected room1_bathroom room5_corridor)
	(roomsconnected room2_bathroom room3_bedroom)
	(roomsconnected room2_bathroom room5_corridor)
	(roomsconnected room3_bedroom room2_bathroom)
	(roomsconnected room3_bedroom room4_bedroom)
	(roomsconnected room4_bedroom room3_bedroom)
	(roomsconnected room5_corridor room1_bathroom)
	(roomsconnected room5_corridor room2_bathroom)
	(roomsconnected room5_corridor room7_kitchen)
	(roomsconnected room6_dining_room room7_kitchen)
	(roomsconnected room6_dining_room room8_living_room)
	(roomsconnected room7_kitchen room5_corridor)
	(roomsconnected room7_kitchen room6_dining_room)
	(roomsconnected room8_living_room room6_dining_room)
  )
  (:goal (and
	(classrelation cup chair)
	(classrelation bottle toilet)
	(classrelation book couch)
	(classrelation pottedplant chair)
	(classrelation bowl bed)))
)
