
(define (problem timberontaskographyv4medium5problem135) (:domain taskographyv4medium5scrub)
  (:objects
        bed - rclass
	bench - rclass
	book - iclass
	bottle - iclass
	couch - rclass
	cup - iclass
	diningtable - rclass
	item10_bottle_smallitem - item
	item11_bottle_smallitem - item
	item12_bottle_smallitem - item
	item13_bottle_smallitem - item
	item14_cup_smallitem - item
	item15_cup_smallitem - item
	item16_cup_smallitem - item
	item67_book_smallitem - item
	item68_book_smallitem - item
	item69_book_smallitem - item
	item6_bottle_smallitem - item
	item70_book_smallitem - item
	item71_book_smallitem - item
	item72_book_smallitem - item
	item73_book_smallitem - item
	item74_book_smallitem - item
	item75_book_smallitem - item
	item76_book_smallitem - item
	item77_vase_mediumitem - item
	item78_vase_mediumitem - item
	item79_vase_mediumitem - item
	item7_bottle_smallitem - item
	item80_vase_mediumitem - item
	item8_bottle_smallitem - item
	item9_bottle_smallitem - item
	location_xneg11_ypos43_place25_room2_floorc - location
	location_xneg12_ypos41_place23_room2_floorc - location
	location_xneg16_yneg39_place47_room4_floorc - location
	location_xneg16_yneg51_place47_room4_floorc - location
	location_xneg17_yneg51_place47_room4_floorc - location
	location_xneg19_yneg30_place47_room4_floorc - location
	location_xneg5_yneg71_place22_room4_floorc - location
	location_xneg7_ypos0_place56_room1_floora - location
	location_xneg8_ypos21_place54_room2_floorc - location
	location_xneg9_ypos12_place53_room3_floorc - location
	location_xneg9_ypos13_place60_room11_floorb - location
	location_xpos0_yneg2_place64_room1_floora - location
	location_xpos11_yneg55_place48_room4_floorc - location
	location_xpos11_ypos41_place63_room2_floorc - location
	location_xpos12_ypos20_place62_room2_floorc - location
	location_xpos15_yneg17_place12_room8_floorc - location
	location_xpos15_ypos42_place63_room2_floorc - location
	location_xpos19_yneg50_place44_room16_floora - location
	location_xpos1_yneg50_place5_room4_floorc - location
	location_xpos1_ypos1_place4_room1_floora - location
	location_xpos23_yneg46_place57_room12_floorb - location
	location_xpos23_yneg51_place0_room12_floorb - location
	location_xpos24_yneg48_place6_room16_floora - location
	location_xpos25_yneg1_place9_room7_floora - location
	location_xpos26_yneg50_place57_room12_floorb - location
	location_xpos2_yneg4_place64_room1_floora - location
	location_xpos2_ypos30_place3_room2_floorc - location
	location_xpos32_yneg15_place26_room8_floorc - location
	location_xpos33_yneg13_place27_room8_floorc - location
	location_xpos33_yneg52_place45_room16_floora - location
	location_xpos36_yneg49_place57_room12_floorb - location
	location_xpos36_ypos12_place52_room9_floorb - location
	location_xpos37_yneg8_place20_room6_floorc - location
	location_xpos37_ypos13_place52_room9_floorb - location
	location_xpos38_yneg19_place14_room13_floorb - location
	location_xpos38_ypos10_place8_room9_floorb - location
	location_xpos38_ypos13_place11_room5_floorc - location
	location_xpos39_ypos18_place50_room5_floorc - location
	location_xpos3_yneg18_place15_room14_floora - location
	location_xpos3_ypos5_place13_room3_floorc - location
	location_xpos41_yneg41_place10_room10_floorc - location
	location_xpos47_yneg18_place1_room6_floorc - location
	location_xpos4_ypos17_place7_room11_floorb - location
	location_xpos53_yneg31_place30_room12_floorb - location
	location_xpos54_yneg29_place30_room12_floorb - location
	location_xpos55_yneg47_place30_room12_floorb - location
	location_xpos55_yneg8_place24_room6_floorc - location
	location_xpos56_yneg30_place30_room12_floorb - location
	location_xpos5_yneg18_place2_room15_floorb - location
	location_xpos5_yneg68_place46_room12_floorb - location
	location_xpos6_yneg23_place49_room8_floorc - location
	location_xpos6_yneg50_place46_room12_floorb - location
	location_xpos7_yneg43_place46_room12_floorb - location
	location_xpos7_ypos13_place61_room3_floorc - location
	location_xpos8_ypos20_place51_room11_floorb - location
	location_xpos9_yneg32_place55_room4_floorc - location
	location_xpos9_ypos13_place51_room11_floorb - location
	location_xpos9_ypos18_place62_room2_floorc - location
	place0_door_room12_living_room - place
	place10_door_room10_home_office - place
	place11_door_room5_bedroom - place
	place12_door_room8_corridor - place
	place13_door_room3_bathroom - place
	place14_door_room13_lobby - place
	place15_door_room14_staircase - place
	place1_door_room6_closet - place
	place20_item6_bottle - place
	place22_item70_book - place
	place23_item9_bottle - place
	place24_item73_book - place
	place25_item13_bottle - place
	place26_item79_vase - place
	place27_item80_vase - place
	place2_door_room15_staircase - place
	place30_receptacle1_bench - place
	place3_door_room2_bathroom - place
	place44_receptacle31_couch - place
	place45_receptacle32_couch - place
	place46_receptacle33_couch - place
	place47_receptacle34_couch - place
	place48_receptacle39_bed - place
	place49_receptacle40_bed - place
	place4_door_room1_bathroom - place
	place50_receptacle41_bed - place
	place51_receptacle42_dining_table - place
	place52_receptacle43_dining_table - place
	place53_receptacle44_toilet - place
	place54_receptacle45_toilet - place
	place55_receptacle46_toilet - place
	place56_receptacle47_toilet - place
	place57_receptacle48_toilet - place
	place5_door_room4_bedroom - place
	place60_receptacle61_sink - place
	place61_receptacle62_sink - place
	place62_receptacle63_sink - place
	place63_receptacle64_sink - place
	place64_receptacle65_sink - place
	place6_door_room16_television_room - place
	place7_door_room11_kitchen - place
	place8_door_room9_dining_room - place
	place9_door_room7_corridor - place
	receptacle1_bench - receptacle
	receptacle31_couch - receptacle
	receptacle32_couch - receptacle
	receptacle33_couch - receptacle
	receptacle34_couch - receptacle
	receptacle39_bed - receptacle
	receptacle40_bed - receptacle
	receptacle41_bed - receptacle
	receptacle42_dining_table - receptacle
	receptacle43_dining_table - receptacle
	receptacle44_toilet - receptacle
	receptacle45_toilet - receptacle
	receptacle46_toilet - receptacle
	receptacle47_toilet - receptacle
	receptacle48_toilet - receptacle
	receptacle61_sink - receptacle
	receptacle62_sink - receptacle
	receptacle63_sink - receptacle
	receptacle64_sink - receptacle
	receptacle65_sink - receptacle
	robot - agent
	room10_home_office - room
	room11_kitchen - room
	room12_living_room - room
	room13_lobby - room
	room14_staircase - room
	room15_staircase - room
	room16_television_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_closet - room
	room7_corridor - room
	room8_corridor - room
	room9_dining_room - room
	sink - rclass
	toilet - rclass
	vase - iclass
  )
  (:init 
	(atlocation robot location_xpos47_yneg18_place1_room6_floorc)
	(classrelation book couch)
	(classrelation book diningtable)
	(classrelation book toilet)
	(classrelation bottle bench)
	(classrelation bottle sink)
	(classrelation cup couch)
	(classrelation cup toilet)
	(classrelation vase bench)
	(classrelation vase diningtable)
	(inanyreceptacle item10_bottle_smallitem)
	(inanyreceptacle item11_bottle_smallitem)
	(inanyreceptacle item12_bottle_smallitem)
	(inanyreceptacle item14_cup_smallitem)
	(inanyreceptacle item15_cup_smallitem)
	(inanyreceptacle item16_cup_smallitem)
	(inanyreceptacle item67_book_smallitem)
	(inanyreceptacle item68_book_smallitem)
	(inanyreceptacle item69_book_smallitem)
	(inanyreceptacle item71_book_smallitem)
	(inanyreceptacle item72_book_smallitem)
	(inanyreceptacle item74_book_smallitem)
	(inanyreceptacle item75_book_smallitem)
	(inanyreceptacle item76_book_smallitem)
	(inanyreceptacle item77_vase_mediumitem)
	(inanyreceptacle item78_vase_mediumitem)
	(inanyreceptacle item7_bottle_smallitem)
	(inanyreceptacle item8_bottle_smallitem)
	(inplace robot place1_door_room6_closet)
	(inreceptacle item10_bottle_smallitem receptacle65_sink)
	(inreceptacle item11_bottle_smallitem receptacle1_bench)
	(inreceptacle item12_bottle_smallitem receptacle1_bench)
	(inreceptacle item14_cup_smallitem receptacle48_toilet)
	(inreceptacle item15_cup_smallitem receptacle34_couch)
	(inreceptacle item16_cup_smallitem receptacle33_couch)
	(inreceptacle item67_book_smallitem receptacle42_dining_table)
	(inreceptacle item68_book_smallitem receptacle42_dining_table)
	(inreceptacle item69_book_smallitem receptacle42_dining_table)
	(inreceptacle item71_book_smallitem receptacle48_toilet)
	(inreceptacle item72_book_smallitem receptacle33_couch)
	(inreceptacle item74_book_smallitem receptacle34_couch)
	(inreceptacle item75_book_smallitem receptacle34_couch)
	(inreceptacle item76_book_smallitem receptacle34_couch)
	(inreceptacle item77_vase_mediumitem receptacle43_dining_table)
	(inreceptacle item78_vase_mediumitem receptacle1_bench)
	(inreceptacle item7_bottle_smallitem receptacle63_sink)
	(inreceptacle item8_bottle_smallitem receptacle64_sink)
	(inroom robot room6_closet)
	(itematlocation item10_bottle_smallitem location_xpos2_yneg4_place64_room1_floora)
	(itematlocation item11_bottle_smallitem location_xpos53_yneg31_place30_room12_floorb)
	(itematlocation item12_bottle_smallitem location_xpos54_yneg29_place30_room12_floorb)
	(itematlocation item13_bottle_smallitem location_xneg11_ypos43_place25_room2_floorc)
	(itematlocation item14_cup_smallitem location_xpos26_yneg50_place57_room12_floorb)
	(itematlocation item15_cup_smallitem location_xneg19_yneg30_place47_room4_floorc)
	(itematlocation item16_cup_smallitem location_xpos5_yneg68_place46_room12_floorb)
	(itematlocation item67_book_smallitem location_xpos8_ypos20_place51_room11_floorb)
	(itematlocation item68_book_smallitem location_xpos8_ypos20_place51_room11_floorb)
	(itematlocation item69_book_smallitem location_xpos8_ypos20_place51_room11_floorb)
	(itematlocation item6_bottle_smallitem location_xpos37_yneg8_place20_room6_floorc)
	(itematlocation item70_book_smallitem location_xneg5_yneg71_place22_room4_floorc)
	(itematlocation item71_book_smallitem location_xpos23_yneg46_place57_room12_floorb)
	(itematlocation item72_book_smallitem location_xpos7_yneg43_place46_room12_floorb)
	(itematlocation item73_book_smallitem location_xpos55_yneg8_place24_room6_floorc)
	(itematlocation item74_book_smallitem location_xneg17_yneg51_place47_room4_floorc)
	(itematlocation item75_book_smallitem location_xneg16_yneg51_place47_room4_floorc)
	(itematlocation item76_book_smallitem location_xneg16_yneg51_place47_room4_floorc)
	(itematlocation item77_vase_mediumitem location_xpos36_ypos12_place52_room9_floorb)
	(itematlocation item78_vase_mediumitem location_xpos56_yneg30_place30_room12_floorb)
	(itematlocation item79_vase_mediumitem location_xpos32_yneg15_place26_room8_floorc)
	(itematlocation item7_bottle_smallitem location_xpos9_ypos18_place62_room2_floorc)
	(itematlocation item80_vase_mediumitem location_xpos33_yneg13_place27_room8_floorc)
	(itematlocation item8_bottle_smallitem location_xpos15_ypos42_place63_room2_floorc)
	(itematlocation item9_bottle_smallitem location_xneg12_ypos41_place23_room2_floorc)
	(itemclass item10_bottle_smallitem bottle)
	(itemclass item11_bottle_smallitem bottle)
	(itemclass item12_bottle_smallitem bottle)
	(itemclass item13_bottle_smallitem bottle)
	(itemclass item14_cup_smallitem cup)
	(itemclass item15_cup_smallitem cup)
	(itemclass item16_cup_smallitem cup)
	(itemclass item67_book_smallitem book)
	(itemclass item68_book_smallitem book)
	(itemclass item69_book_smallitem book)
	(itemclass item6_bottle_smallitem bottle)
	(itemclass item70_book_smallitem book)
	(itemclass item71_book_smallitem book)
	(itemclass item72_book_smallitem book)
	(itemclass item73_book_smallitem book)
	(itemclass item74_book_smallitem book)
	(itemclass item75_book_smallitem book)
	(itemclass item76_book_smallitem book)
	(itemclass item77_vase_mediumitem vase)
	(itemclass item78_vase_mediumitem vase)
	(itemclass item79_vase_mediumitem vase)
	(itemclass item7_bottle_smallitem bottle)
	(itemclass item80_vase_mediumitem vase)
	(itemclass item8_bottle_smallitem bottle)
	(itemclass item9_bottle_smallitem bottle)
	(locationinplace location_xneg11_ypos43_place25_room2_floorc place25_item13_bottle)
	(locationinplace location_xneg12_ypos41_place23_room2_floorc place23_item9_bottle)
	(locationinplace location_xneg16_yneg39_place47_room4_floorc place47_receptacle34_couch)
	(locationinplace location_xneg16_yneg51_place47_room4_floorc place47_receptacle34_couch)
	(locationinplace location_xneg17_yneg51_place47_room4_floorc place47_receptacle34_couch)
	(locationinplace location_xneg19_yneg30_place47_room4_floorc place47_receptacle34_couch)
	(locationinplace location_xneg5_yneg71_place22_room4_floorc place22_item70_book)
	(locationinplace location_xneg7_ypos0_place56_room1_floora place56_receptacle47_toilet)
	(locationinplace location_xneg8_ypos21_place54_room2_floorc place54_receptacle45_toilet)
	(locationinplace location_xneg9_ypos12_place53_room3_floorc place53_receptacle44_toilet)
	(locationinplace location_xneg9_ypos13_place60_room11_floorb place60_receptacle61_sink)
	(locationinplace location_xpos0_yneg2_place64_room1_floora place64_receptacle65_sink)
	(locationinplace location_xpos11_yneg55_place48_room4_floorc place48_receptacle39_bed)
	(locationinplace location_xpos11_ypos41_place63_room2_floorc place63_receptacle64_sink)
	(locationinplace location_xpos12_ypos20_place62_room2_floorc place62_receptacle63_sink)
	(locationinplace location_xpos15_yneg17_place12_room8_floorc place12_door_room8_corridor)
	(locationinplace location_xpos15_ypos42_place63_room2_floorc place63_receptacle64_sink)
	(locationinplace location_xpos19_yneg50_place44_room16_floora place44_receptacle31_couch)
	(locationinplace location_xpos1_yneg50_place5_room4_floorc place5_door_room4_bedroom)
	(locationinplace location_xpos1_ypos1_place4_room1_floora place4_door_room1_bathroom)
	(locationinplace location_xpos23_yneg46_place57_room12_floorb place57_receptacle48_toilet)
	(locationinplace location_xpos23_yneg51_place0_room12_floorb place0_door_room12_living_room)
	(locationinplace location_xpos24_yneg48_place6_room16_floora place6_door_room16_television_room)
	(locationinplace location_xpos25_yneg1_place9_room7_floora place9_door_room7_corridor)
	(locationinplace location_xpos26_yneg50_place57_room12_floorb place57_receptacle48_toilet)
	(locationinplace location_xpos2_yneg4_place64_room1_floora place64_receptacle65_sink)
	(locationinplace location_xpos2_ypos30_place3_room2_floorc place3_door_room2_bathroom)
	(locationinplace location_xpos32_yneg15_place26_room8_floorc place26_item79_vase)
	(locationinplace location_xpos33_yneg13_place27_room8_floorc place27_item80_vase)
	(locationinplace location_xpos33_yneg52_place45_room16_floora place45_receptacle32_couch)
	(locationinplace location_xpos36_yneg49_place57_room12_floorb place57_receptacle48_toilet)
	(locationinplace location_xpos36_ypos12_place52_room9_floorb place52_receptacle43_dining_table)
	(locationinplace location_xpos37_yneg8_place20_room6_floorc place20_item6_bottle)
	(locationinplace location_xpos37_ypos13_place52_room9_floorb place52_receptacle43_dining_table)
	(locationinplace location_xpos38_yneg19_place14_room13_floorb place14_door_room13_lobby)
	(locationinplace location_xpos38_ypos10_place8_room9_floorb place8_door_room9_dining_room)
	(locationinplace location_xpos38_ypos13_place11_room5_floorc place11_door_room5_bedroom)
	(locationinplace location_xpos39_ypos18_place50_room5_floorc place50_receptacle41_bed)
	(locationinplace location_xpos3_yneg18_place15_room14_floora place15_door_room14_staircase)
	(locationinplace location_xpos3_ypos5_place13_room3_floorc place13_door_room3_bathroom)
	(locationinplace location_xpos41_yneg41_place10_room10_floorc place10_door_room10_home_office)
	(locationinplace location_xpos47_yneg18_place1_room6_floorc place1_door_room6_closet)
	(locationinplace location_xpos4_ypos17_place7_room11_floorb place7_door_room11_kitchen)
	(locationinplace location_xpos53_yneg31_place30_room12_floorb place30_receptacle1_bench)
	(locationinplace location_xpos54_yneg29_place30_room12_floorb place30_receptacle1_bench)
	(locationinplace location_xpos55_yneg47_place30_room12_floorb place30_receptacle1_bench)
	(locationinplace location_xpos55_yneg8_place24_room6_floorc place24_item73_book)
	(locationinplace location_xpos56_yneg30_place30_room12_floorb place30_receptacle1_bench)
	(locationinplace location_xpos5_yneg18_place2_room15_floorb place2_door_room15_staircase)
	(locationinplace location_xpos5_yneg68_place46_room12_floorb place46_receptacle33_couch)
	(locationinplace location_xpos6_yneg23_place49_room8_floorc place49_receptacle40_bed)
	(locationinplace location_xpos6_yneg50_place46_room12_floorb place46_receptacle33_couch)
	(locationinplace location_xpos7_yneg43_place46_room12_floorb place46_receptacle33_couch)
	(locationinplace location_xpos7_ypos13_place61_room3_floorc place61_receptacle62_sink)
	(locationinplace location_xpos8_ypos20_place51_room11_floorb place51_receptacle42_dining_table)
	(locationinplace location_xpos9_yneg32_place55_room4_floorc place55_receptacle46_toilet)
	(locationinplace location_xpos9_ypos13_place51_room11_floorb place51_receptacle42_dining_table)
	(locationinplace location_xpos9_ypos18_place62_room2_floorc place62_receptacle63_sink)
	(placeinroom place0_door_room12_living_room room12_living_room)
	(placeinroom place10_door_room10_home_office room10_home_office)
	(placeinroom place11_door_room5_bedroom room5_bedroom)
	(placeinroom place12_door_room8_corridor room8_corridor)
	(placeinroom place13_door_room3_bathroom room3_bathroom)
	(placeinroom place14_door_room13_lobby room13_lobby)
	(placeinroom place15_door_room14_staircase room14_staircase)
	(placeinroom place1_door_room6_closet room6_closet)
	(placeinroom place20_item6_bottle room6_closet)
	(placeinroom place22_item70_book room4_bedroom)
	(placeinroom place23_item9_bottle room2_bathroom)
	(placeinroom place24_item73_book room6_closet)
	(placeinroom place25_item13_bottle room2_bathroom)
	(placeinroom place26_item79_vase room8_corridor)
	(placeinroom place27_item80_vase room8_corridor)
	(placeinroom place2_door_room15_staircase room15_staircase)
	(placeinroom place30_receptacle1_bench room12_living_room)
	(placeinroom place3_door_room2_bathroom room2_bathroom)
	(placeinroom place44_receptacle31_couch room16_television_room)
	(placeinroom place45_receptacle32_couch room16_television_room)
	(placeinroom place46_receptacle33_couch room12_living_room)
	(placeinroom place47_receptacle34_couch room4_bedroom)
	(placeinroom place48_receptacle39_bed room4_bedroom)
	(placeinroom place49_receptacle40_bed room8_corridor)
	(placeinroom place4_door_room1_bathroom room1_bathroom)
	(placeinroom place50_receptacle41_bed room5_bedroom)
	(placeinroom place51_receptacle42_dining_table room11_kitchen)
	(placeinroom place52_receptacle43_dining_table room9_dining_room)
	(placeinroom place53_receptacle44_toilet room3_bathroom)
	(placeinroom place54_receptacle45_toilet room2_bathroom)
	(placeinroom place55_receptacle46_toilet room4_bedroom)
	(placeinroom place56_receptacle47_toilet room1_bathroom)
	(placeinroom place57_receptacle48_toilet room12_living_room)
	(placeinroom place5_door_room4_bedroom room4_bedroom)
	(placeinroom place60_receptacle61_sink room11_kitchen)
	(placeinroom place61_receptacle62_sink room3_bathroom)
	(placeinroom place62_receptacle63_sink room2_bathroom)
	(placeinroom place63_receptacle64_sink room2_bathroom)
	(placeinroom place64_receptacle65_sink room1_bathroom)
	(placeinroom place6_door_room16_television_room room16_television_room)
	(placeinroom place7_door_room11_kitchen room11_kitchen)
	(placeinroom place8_door_room9_dining_room room9_dining_room)
	(placeinroom place9_door_room7_corridor room7_corridor)
	(placelocation location_xneg11_ypos43_place25_room2_floorc place25_item13_bottle)
	(placelocation location_xneg12_ypos41_place23_room2_floorc place23_item9_bottle)
	(placelocation location_xneg16_yneg39_place47_room4_floorc place47_receptacle34_couch)
	(placelocation location_xneg5_yneg71_place22_room4_floorc place22_item70_book)
	(placelocation location_xneg7_ypos0_place56_room1_floora place56_receptacle47_toilet)
	(placelocation location_xneg8_ypos21_place54_room2_floorc place54_receptacle45_toilet)
	(placelocation location_xneg9_ypos12_place53_room3_floorc place53_receptacle44_toilet)
	(placelocation location_xneg9_ypos13_place60_room11_floorb place60_receptacle61_sink)
	(placelocation location_xpos0_yneg2_place64_room1_floora place64_receptacle65_sink)
	(placelocation location_xpos11_yneg55_place48_room4_floorc place48_receptacle39_bed)
	(placelocation location_xpos11_ypos41_place63_room2_floorc place63_receptacle64_sink)
	(placelocation location_xpos12_ypos20_place62_room2_floorc place62_receptacle63_sink)
	(placelocation location_xpos15_yneg17_place12_room8_floorc place12_door_room8_corridor)
	(placelocation location_xpos19_yneg50_place44_room16_floora place44_receptacle31_couch)
	(placelocation location_xpos1_yneg50_place5_room4_floorc place5_door_room4_bedroom)
	(placelocation location_xpos1_ypos1_place4_room1_floora place4_door_room1_bathroom)
	(placelocation location_xpos23_yneg51_place0_room12_floorb place0_door_room12_living_room)
	(placelocation location_xpos24_yneg48_place6_room16_floora place6_door_room16_television_room)
	(placelocation location_xpos25_yneg1_place9_room7_floora place9_door_room7_corridor)
	(placelocation location_xpos2_ypos30_place3_room2_floorc place3_door_room2_bathroom)
	(placelocation location_xpos32_yneg15_place26_room8_floorc place26_item79_vase)
	(placelocation location_xpos33_yneg13_place27_room8_floorc place27_item80_vase)
	(placelocation location_xpos33_yneg52_place45_room16_floora place45_receptacle32_couch)
	(placelocation location_xpos36_yneg49_place57_room12_floorb place57_receptacle48_toilet)
	(placelocation location_xpos37_yneg8_place20_room6_floorc place20_item6_bottle)
	(placelocation location_xpos37_ypos13_place52_room9_floorb place52_receptacle43_dining_table)
	(placelocation location_xpos38_yneg19_place14_room13_floorb place14_door_room13_lobby)
	(placelocation location_xpos38_ypos10_place8_room9_floorb place8_door_room9_dining_room)
	(placelocation location_xpos38_ypos13_place11_room5_floorc place11_door_room5_bedroom)
	(placelocation location_xpos39_ypos18_place50_room5_floorc place50_receptacle41_bed)
	(placelocation location_xpos3_yneg18_place15_room14_floora place15_door_room14_staircase)
	(placelocation location_xpos3_ypos5_place13_room3_floorc place13_door_room3_bathroom)
	(placelocation location_xpos41_yneg41_place10_room10_floorc place10_door_room10_home_office)
	(placelocation location_xpos47_yneg18_place1_room6_floorc place1_door_room6_closet)
	(placelocation location_xpos4_ypos17_place7_room11_floorb place7_door_room11_kitchen)
	(placelocation location_xpos55_yneg47_place30_room12_floorb place30_receptacle1_bench)
	(placelocation location_xpos55_yneg8_place24_room6_floorc place24_item73_book)
	(placelocation location_xpos5_yneg18_place2_room15_floorb place2_door_room15_staircase)
	(placelocation location_xpos6_yneg23_place49_room8_floorc place49_receptacle40_bed)
	(placelocation location_xpos6_yneg50_place46_room12_floorb place46_receptacle33_couch)
	(placelocation location_xpos7_ypos13_place61_room3_floorc place61_receptacle62_sink)
	(placelocation location_xpos9_yneg32_place55_room4_floorc place55_receptacle46_toilet)
	(placelocation location_xpos9_ypos13_place51_room11_floorb place51_receptacle42_dining_table)
	(receptacleatlocation receptacle1_bench location_xpos55_yneg47_place30_room12_floorb)
	(receptacleatlocation receptacle31_couch location_xpos19_yneg50_place44_room16_floora)
	(receptacleatlocation receptacle32_couch location_xpos33_yneg52_place45_room16_floora)
	(receptacleatlocation receptacle33_couch location_xpos6_yneg50_place46_room12_floorb)
	(receptacleatlocation receptacle34_couch location_xneg16_yneg39_place47_room4_floorc)
	(receptacleatlocation receptacle39_bed location_xpos11_yneg55_place48_room4_floorc)
	(receptacleatlocation receptacle40_bed location_xpos6_yneg23_place49_room8_floorc)
	(receptacleatlocation receptacle41_bed location_xpos39_ypos18_place50_room5_floorc)
	(receptacleatlocation receptacle42_dining_table location_xpos9_ypos13_place51_room11_floorb)
	(receptacleatlocation receptacle43_dining_table location_xpos37_ypos13_place52_room9_floorb)
	(receptacleatlocation receptacle44_toilet location_xneg9_ypos12_place53_room3_floorc)
	(receptacleatlocation receptacle45_toilet location_xneg8_ypos21_place54_room2_floorc)
	(receptacleatlocation receptacle46_toilet location_xpos9_yneg32_place55_room4_floorc)
	(receptacleatlocation receptacle47_toilet location_xneg7_ypos0_place56_room1_floora)
	(receptacleatlocation receptacle48_toilet location_xpos36_yneg49_place57_room12_floorb)
	(receptacleatlocation receptacle61_sink location_xneg9_ypos13_place60_room11_floorb)
	(receptacleatlocation receptacle62_sink location_xpos7_ypos13_place61_room3_floorc)
	(receptacleatlocation receptacle63_sink location_xpos12_ypos20_place62_room2_floorc)
	(receptacleatlocation receptacle64_sink location_xpos11_ypos41_place63_room2_floorc)
	(receptacleatlocation receptacle65_sink location_xpos0_yneg2_place64_room1_floora)
	(receptacleclass receptacle1_bench bench)
	(receptacleclass receptacle31_couch couch)
	(receptacleclass receptacle32_couch couch)
	(receptacleclass receptacle33_couch couch)
	(receptacleclass receptacle34_couch couch)
	(receptacleclass receptacle39_bed bed)
	(receptacleclass receptacle40_bed bed)
	(receptacleclass receptacle41_bed bed)
	(receptacleclass receptacle42_dining_table diningtable)
	(receptacleclass receptacle43_dining_table diningtable)
	(receptacleclass receptacle44_toilet toilet)
	(receptacleclass receptacle45_toilet toilet)
	(receptacleclass receptacle46_toilet toilet)
	(receptacleclass receptacle47_toilet toilet)
	(receptacleclass receptacle48_toilet toilet)
	(receptacleclass receptacle61_sink sink)
	(receptacleclass receptacle62_sink sink)
	(receptacleclass receptacle63_sink sink)
	(receptacleclass receptacle64_sink sink)
	(receptacleclass receptacle65_sink sink)
	(roomplace place0_door_room12_living_room room12_living_room)
	(roomplace place10_door_room10_home_office room10_home_office)
	(roomplace place11_door_room5_bedroom room5_bedroom)
	(roomplace place12_door_room8_corridor room8_corridor)
	(roomplace place13_door_room3_bathroom room3_bathroom)
	(roomplace place14_door_room13_lobby room13_lobby)
	(roomplace place15_door_room14_staircase room14_staircase)
	(roomplace place1_door_room6_closet room6_closet)
	(roomplace place2_door_room15_staircase room15_staircase)
	(roomplace place3_door_room2_bathroom room2_bathroom)
	(roomplace place4_door_room1_bathroom room1_bathroom)
	(roomplace place5_door_room4_bedroom room4_bedroom)
	(roomplace place6_door_room16_television_room room16_television_room)
	(roomplace place7_door_room11_kitchen room11_kitchen)
	(roomplace place8_door_room9_dining_room room9_dining_room)
	(roomplace place9_door_room7_corridor room7_corridor)
	(roomsconnected room10_home_office room6_closet)
	(roomsconnected room11_kitchen room9_dining_room)
	(roomsconnected room12_living_room room13_lobby)
	(roomsconnected room12_living_room room16_television_room)
	(roomsconnected room13_lobby room12_living_room)
	(roomsconnected room13_lobby room15_staircase)
	(roomsconnected room13_lobby room9_dining_room)
	(roomsconnected room14_staircase room16_television_room)
	(roomsconnected room14_staircase room1_bathroom)
	(roomsconnected room15_staircase room13_lobby)
	(roomsconnected room15_staircase room8_corridor)
	(roomsconnected room16_television_room room12_living_room)
	(roomsconnected room16_television_room room14_staircase)
	(roomsconnected room1_bathroom room14_staircase)
	(roomsconnected room1_bathroom room7_corridor)
	(roomsconnected room2_bathroom room3_bathroom)
	(roomsconnected room3_bathroom room2_bathroom)
	(roomsconnected room3_bathroom room8_corridor)
	(roomsconnected room4_bedroom room8_corridor)
	(roomsconnected room5_bedroom room6_closet)
	(roomsconnected room6_closet room10_home_office)
	(roomsconnected room6_closet room5_bedroom)
	(roomsconnected room6_closet room8_corridor)
	(roomsconnected room7_corridor room1_bathroom)
	(roomsconnected room8_corridor room15_staircase)
	(roomsconnected room8_corridor room3_bathroom)
	(roomsconnected room8_corridor room4_bedroom)
	(roomsconnected room8_corridor room6_closet)
	(roomsconnected room9_dining_room room11_kitchen)
	(roomsconnected room9_dining_room room13_lobby)
  )
  (:goal (and
	(classrelation vase toilet)
	(classrelation cup sink)
	(classrelation bottle toilet)
	(classrelation bottle bed)
	(classrelation book sink)))
)
