
(define (problem shelbianataskographyv4medium5problem184) (:domain taskographyv4medium5scrub)
  (:objects
        chair - rclass
	clock - iclass
	item14_clock_mediumitem - item
	item15_clock_mediumitem - item
	item1_kite_largeitem - item
	item2_kite_largeitem - item
	item3_kite_largeitem - item
	kite - iclass
	location_xneg12_yneg1_place20_room11_floora - location
	location_xneg13_ypos48_place10_room6_floora - location
	location_xneg19_ypos17_place18_room11_floora - location
	location_xneg19_ypos9_place2_room11_floora - location
	location_xneg39_ypos20_place8_room4_floora - location
	location_xneg47_ypos50_place5_room7_floora - location
	location_xneg49_ypos28_place19_room1_floora - location
	location_xneg54_ypos12_place22_room1_floora - location
	location_xneg54_ypos17_place4_room1_floora - location
	location_xneg57_ypos36_place21_room7_floora - location
	location_xneg58_ypos16_place25_room1_floora - location
	location_xneg59_ypos24_place19_room1_floora - location
	location_xpos14_yneg5_place27_room3_floora - location
	location_xpos17_ypos11_place9_room5_floora - location
	location_xpos17_ypos36_place26_room2_floora - location
	location_xpos18_ypos29_place3_room2_floora - location
	location_xpos18_ypos61_place7_room10_floora - location
	location_xpos20_ypos2_place6_room3_floora - location
	location_xpos27_ypos24_place17_room2_floora - location
	location_xpos31_yneg3_place23_room3_floora - location
	location_xpos45_ypos28_place24_room8_floora - location
	location_xpos48_ypos52_place0_room9_floora - location
	location_xpos50_ypos75_place12_room9_floora - location
	location_xpos51_ypos13_place1_room8_floora - location
	location_xpos60_yneg6_place13_room8_floora - location
	location_xpos66_ypos58_place11_room9_floora - location
	location_xpos9_ypos61_place14_room10_floora - location
	place0_door_room9_empty_room - place
	place10_door_room6_empty_room - place
	place11_item1_kite - place
	place12_item2_kite - place
	place13_item3_kite - place
	place14_item14_clock - place
	place17_receptacle6_sink - place
	place18_receptacle7_sink - place
	place19_receptacle8_sink - place
	place1_door_room8_empty_room - place
	place20_receptacle9_refrigerator - place
	place21_receptacle10_refrigerator - place
	place22_receptacle11_refrigerator - place
	place23_receptacle12_refrigerator - place
	place24_receptacle13_refrigerator - place
	place25_receptacle16_toilet - place
	place26_receptacle17_toilet - place
	place27_receptacle18_chair - place
	place2_door_room11_kitchen - place
	place3_door_room2_bathroom - place
	place4_door_room1_bathroom - place
	place5_door_room7_empty_room - place
	place6_door_room3_closet - place
	place7_door_room10_empty_room - place
	place8_door_room4_corridor - place
	place9_door_room5_corridor - place
	receptacle10_refrigerator - receptacle
	receptacle11_refrigerator - receptacle
	receptacle12_refrigerator - receptacle
	receptacle13_refrigerator - receptacle
	receptacle16_toilet - receptacle
	receptacle17_toilet - receptacle
	receptacle18_chair - receptacle
	receptacle6_sink - receptacle
	receptacle7_sink - receptacle
	receptacle8_sink - receptacle
	receptacle9_refrigerator - receptacle
	refrigerator - rclass
	robot - agent
	room10_empty_room - room
	room11_kitchen - room
	room1_bathroom - room
	room2_bathroom - room
	room3_closet - room
	room4_corridor - room
	room5_corridor - room
	room6_empty_room - room
	room7_empty_room - room
	room8_empty_room - room
	room9_empty_room - room
	sink - rclass
	toilet - rclass
  )
  (:init 
	(atlocation robot location_xneg54_ypos17_place4_room1_floora)
	(classrelation clock sink)
	(inanyreceptacle item15_clock_mediumitem)
	(inplace robot place4_door_room1_bathroom)
	(inreceptacle item15_clock_mediumitem receptacle8_sink)
	(inroom robot room1_bathroom)
	(itematlocation item14_clock_mediumitem location_xpos9_ypos61_place14_room10_floora)
	(itematlocation item15_clock_mediumitem location_xneg49_ypos28_place19_room1_floora)
	(itematlocation item1_kite_largeitem location_xpos66_ypos58_place11_room9_floora)
	(itematlocation item2_kite_largeitem location_xpos50_ypos75_place12_room9_floora)
	(itematlocation item3_kite_largeitem location_xpos60_yneg6_place13_room8_floora)
	(itemclass item14_clock_mediumitem clock)
	(itemclass item15_clock_mediumitem clock)
	(itemclass item1_kite_largeitem kite)
	(itemclass item2_kite_largeitem kite)
	(itemclass item3_kite_largeitem kite)
	(locationinplace location_xneg12_yneg1_place20_room11_floora place20_receptacle9_refrigerator)
	(locationinplace location_xneg13_ypos48_place10_room6_floora place10_door_room6_empty_room)
	(locationinplace location_xneg19_ypos17_place18_room11_floora place18_receptacle7_sink)
	(locationinplace location_xneg19_ypos9_place2_room11_floora place2_door_room11_kitchen)
	(locationinplace location_xneg39_ypos20_place8_room4_floora place8_door_room4_corridor)
	(locationinplace location_xneg47_ypos50_place5_room7_floora place5_door_room7_empty_room)
	(locationinplace location_xneg49_ypos28_place19_room1_floora place19_receptacle8_sink)
	(locationinplace location_xneg54_ypos12_place22_room1_floora place22_receptacle11_refrigerator)
	(locationinplace location_xneg54_ypos17_place4_room1_floora place4_door_room1_bathroom)
	(locationinplace location_xneg57_ypos36_place21_room7_floora place21_receptacle10_refrigerator)
	(locationinplace location_xneg58_ypos16_place25_room1_floora place25_receptacle16_toilet)
	(locationinplace location_xneg59_ypos24_place19_room1_floora place19_receptacle8_sink)
	(locationinplace location_xpos14_yneg5_place27_room3_floora place27_receptacle18_chair)
	(locationinplace location_xpos17_ypos11_place9_room5_floora place9_door_room5_corridor)
	(locationinplace location_xpos17_ypos36_place26_room2_floora place26_receptacle17_toilet)
	(locationinplace location_xpos18_ypos29_place3_room2_floora place3_door_room2_bathroom)
	(locationinplace location_xpos18_ypos61_place7_room10_floora place7_door_room10_empty_room)
	(locationinplace location_xpos20_ypos2_place6_room3_floora place6_door_room3_closet)
	(locationinplace location_xpos27_ypos24_place17_room2_floora place17_receptacle6_sink)
	(locationinplace location_xpos31_yneg3_place23_room3_floora place23_receptacle12_refrigerator)
	(locationinplace location_xpos45_ypos28_place24_room8_floora place24_receptacle13_refrigerator)
	(locationinplace location_xpos48_ypos52_place0_room9_floora place0_door_room9_empty_room)
	(locationinplace location_xpos50_ypos75_place12_room9_floora place12_item2_kite)
	(locationinplace location_xpos51_ypos13_place1_room8_floora place1_door_room8_empty_room)
	(locationinplace location_xpos60_yneg6_place13_room8_floora place13_item3_kite)
	(locationinplace location_xpos66_ypos58_place11_room9_floora place11_item1_kite)
	(locationinplace location_xpos9_ypos61_place14_room10_floora place14_item14_clock)
	(placeinroom place0_door_room9_empty_room room9_empty_room)
	(placeinroom place10_door_room6_empty_room room6_empty_room)
	(placeinroom place11_item1_kite room9_empty_room)
	(placeinroom place12_item2_kite room9_empty_room)
	(placeinroom place13_item3_kite room8_empty_room)
	(placeinroom place14_item14_clock room10_empty_room)
	(placeinroom place17_receptacle6_sink room2_bathroom)
	(placeinroom place18_receptacle7_sink room11_kitchen)
	(placeinroom place19_receptacle8_sink room1_bathroom)
	(placeinroom place1_door_room8_empty_room room8_empty_room)
	(placeinroom place20_receptacle9_refrigerator room11_kitchen)
	(placeinroom place21_receptacle10_refrigerator room7_empty_room)
	(placeinroom place22_receptacle11_refrigerator room1_bathroom)
	(placeinroom place23_receptacle12_refrigerator room3_closet)
	(placeinroom place24_receptacle13_refrigerator room8_empty_room)
	(placeinroom place25_receptacle16_toilet room1_bathroom)
	(placeinroom place26_receptacle17_toilet room2_bathroom)
	(placeinroom place27_receptacle18_chair room3_closet)
	(placeinroom place2_door_room11_kitchen room11_kitchen)
	(placeinroom place3_door_room2_bathroom room2_bathroom)
	(placeinroom place4_door_room1_bathroom room1_bathroom)
	(placeinroom place5_door_room7_empty_room room7_empty_room)
	(placeinroom place6_door_room3_closet room3_closet)
	(placeinroom place7_door_room10_empty_room room10_empty_room)
	(placeinroom place8_door_room4_corridor room4_corridor)
	(placeinroom place9_door_room5_corridor room5_corridor)
	(placelocation location_xneg12_yneg1_place20_room11_floora place20_receptacle9_refrigerator)
	(placelocation location_xneg13_ypos48_place10_room6_floora place10_door_room6_empty_room)
	(placelocation location_xneg19_ypos17_place18_room11_floora place18_receptacle7_sink)
	(placelocation location_xneg19_ypos9_place2_room11_floora place2_door_room11_kitchen)
	(placelocation location_xneg39_ypos20_place8_room4_floora place8_door_room4_corridor)
	(placelocation location_xneg47_ypos50_place5_room7_floora place5_door_room7_empty_room)
	(placelocation location_xneg54_ypos12_place22_room1_floora place22_receptacle11_refrigerator)
	(placelocation location_xneg54_ypos17_place4_room1_floora place4_door_room1_bathroom)
	(placelocation location_xneg57_ypos36_place21_room7_floora place21_receptacle10_refrigerator)
	(placelocation location_xneg58_ypos16_place25_room1_floora place25_receptacle16_toilet)
	(placelocation location_xneg59_ypos24_place19_room1_floora place19_receptacle8_sink)
	(placelocation location_xpos14_yneg5_place27_room3_floora place27_receptacle18_chair)
	(placelocation location_xpos17_ypos11_place9_room5_floora place9_door_room5_corridor)
	(placelocation location_xpos17_ypos36_place26_room2_floora place26_receptacle17_toilet)
	(placelocation location_xpos18_ypos29_place3_room2_floora place3_door_room2_bathroom)
	(placelocation location_xpos18_ypos61_place7_room10_floora place7_door_room10_empty_room)
	(placelocation location_xpos20_ypos2_place6_room3_floora place6_door_room3_closet)
	(placelocation location_xpos27_ypos24_place17_room2_floora place17_receptacle6_sink)
	(placelocation location_xpos31_yneg3_place23_room3_floora place23_receptacle12_refrigerator)
	(placelocation location_xpos45_ypos28_place24_room8_floora place24_receptacle13_refrigerator)
	(placelocation location_xpos48_ypos52_place0_room9_floora place0_door_room9_empty_room)
	(placelocation location_xpos50_ypos75_place12_room9_floora place12_item2_kite)
	(placelocation location_xpos51_ypos13_place1_room8_floora place1_door_room8_empty_room)
	(placelocation location_xpos60_yneg6_place13_room8_floora place13_item3_kite)
	(placelocation location_xpos66_ypos58_place11_room9_floora place11_item1_kite)
	(placelocation location_xpos9_ypos61_place14_room10_floora place14_item14_clock)
	(receptacleatlocation receptacle10_refrigerator location_xneg57_ypos36_place21_room7_floora)
	(receptacleatlocation receptacle11_refrigerator location_xneg54_ypos12_place22_room1_floora)
	(receptacleatlocation receptacle12_refrigerator location_xpos31_yneg3_place23_room3_floora)
	(receptacleatlocation receptacle13_refrigerator location_xpos45_ypos28_place24_room8_floora)
	(receptacleatlocation receptacle16_toilet location_xneg58_ypos16_place25_room1_floora)
	(receptacleatlocation receptacle17_toilet location_xpos17_ypos36_place26_room2_floora)
	(receptacleatlocation receptacle18_chair location_xpos14_yneg5_place27_room3_floora)
	(receptacleatlocation receptacle6_sink location_xpos27_ypos24_place17_room2_floora)
	(receptacleatlocation receptacle7_sink location_xneg19_ypos17_place18_room11_floora)
	(receptacleatlocation receptacle8_sink location_xneg59_ypos24_place19_room1_floora)
	(receptacleatlocation receptacle9_refrigerator location_xneg12_yneg1_place20_room11_floora)
	(receptacleclass receptacle10_refrigerator refrigerator)
	(receptacleclass receptacle11_refrigerator refrigerator)
	(receptacleclass receptacle12_refrigerator refrigerator)
	(receptacleclass receptacle13_refrigerator refrigerator)
	(receptacleclass receptacle16_toilet toilet)
	(receptacleclass receptacle17_toilet toilet)
	(receptacleclass receptacle18_chair chair)
	(receptacleclass receptacle6_sink sink)
	(receptacleclass receptacle7_sink sink)
	(receptacleclass receptacle8_sink sink)
	(receptacleclass receptacle9_refrigerator refrigerator)
	(receptacleopeningtype receptacle10_refrigerator)
	(receptacleopeningtype receptacle11_refrigerator)
	(receptacleopeningtype receptacle12_refrigerator)
	(receptacleopeningtype receptacle13_refrigerator)
	(receptacleopeningtype receptacle9_refrigerator)
	(roomplace place0_door_room9_empty_room room9_empty_room)
	(roomplace place10_door_room6_empty_room room6_empty_room)
	(roomplace place1_door_room8_empty_room room8_empty_room)
	(roomplace place2_door_room11_kitchen room11_kitchen)
	(roomplace place3_door_room2_bathroom room2_bathroom)
	(roomplace place4_door_room1_bathroom room1_bathroom)
	(roomplace place5_door_room7_empty_room room7_empty_room)
	(roomplace place6_door_room3_closet room3_closet)
	(roomplace place7_door_room10_empty_room room10_empty_room)
	(roomplace place8_door_room4_corridor room4_corridor)
	(roomplace place9_door_room5_corridor room5_corridor)
	(roomsconnected room10_empty_room room2_bathroom)
	(roomsconnected room10_empty_room room6_empty_room)
	(roomsconnected room10_empty_room room9_empty_room)
	(roomsconnected room11_kitchen room4_corridor)
	(roomsconnected room1_bathroom room4_corridor)
	(roomsconnected room2_bathroom room10_empty_room)
	(roomsconnected room2_bathroom room5_corridor)
	(roomsconnected room3_closet room5_corridor)
	(roomsconnected room3_closet room8_empty_room)
	(roomsconnected room4_corridor room11_kitchen)
	(roomsconnected room4_corridor room1_bathroom)
	(roomsconnected room4_corridor room7_empty_room)
	(roomsconnected room5_corridor room2_bathroom)
	(roomsconnected room5_corridor room3_closet)
	(roomsconnected room6_empty_room room10_empty_room)
	(roomsconnected room6_empty_room room7_empty_room)
	(roomsconnected room7_empty_room room4_corridor)
	(roomsconnected room7_empty_room room6_empty_room)
	(roomsconnected room8_empty_room room3_closet)
	(roomsconnected room9_empty_room room10_empty_room)
  )
  (:goal (and
	(classrelation kite chair)
	(classrelation kite refrigerator)
	(classrelation clock refrigerator)
	(classrelation clock toilet)
	(classrelation kite toilet)))
)
