
(define (problem highspiretaskographyv4medium5problem59) (:domain taskographyv4medium5scrub)
  (:objects
        bed - rclass
	book - iclass
	bottle - iclass
	bowl - iclass
	chair - rclass
	clock - iclass
	item29_tv_largeitem - item
	item30_tv_largeitem - item
	item31_tv_largeitem - item
	item32_tv_largeitem - item
	item33_laptop_mediumitem - item
	item44_book_smallitem - item
	item45_clock_mediumitem - item
	item46_vase_mediumitem - item
	item47_vase_mediumitem - item
	item48_teddy_bear_mediumitem - item
	item4_bottle_smallitem - item
	item5_bowl_smallitem - item
	item6_bowl_smallitem - item
	laptop - iclass
	location_xneg13_yneg13_place26_room10_floorb - location
	location_xneg14_yneg19_place48_room4_floorc - location
	location_xneg14_yneg1_place47_room4_floorc - location
	location_xneg14_ypos19_place12_room16_floorb - location
	location_xneg17_yneg12_place48_room4_floorc - location
	location_xneg19_yneg30_place37_room6_floorc - location
	location_xneg20_ypos20_place15_room15_floora - location
	location_xneg22_ypos9_place2_room7_floora - location
	location_xneg26_ypos12_place13_room8_floorb - location
	location_xneg31_yneg14_place37_room6_floorc - location
	location_xneg31_yneg7_place6_room6_floorc - location
	location_xneg42_yneg31_place21_room13_floorb - location
	location_xneg43_yneg16_place7_room13_floorb - location
	location_xneg43_yneg32_place22_room13_floorb - location
	location_xneg44_yneg15_place30_room6_floorc - location
	location_xneg44_yneg9_place31_room6_floorc - location
	location_xneg48_ypos15_place4_room14_floora - location
	location_xneg53_yneg27_place29_room6_floorc - location
	location_xneg57_yneg22_place29_room6_floorc - location
	location_xneg57_ypos12_place18_room14_floora - location
	location_xneg57_ypos15_place19_room8_floorb - location
	location_xneg57_ypos7_place20_room14_floora - location
	location_xneg5_yneg14_place10_room4_floorc - location
	location_xneg8_yneg11_place28_room10_floorb - location
	location_xneg8_yneg17_place5_room10_floorb - location
	location_xneg8_yneg19_place27_room10_floorb - location
	location_xpos11_ypos13_place52_room2_floorb - location
	location_xpos13_yneg13_place53_room12_floorb - location
	location_xpos14_ypos23_place46_room1_floora - location
	location_xpos15_yneg7_place0_room5_floora - location
	location_xpos17_ypos18_place8_room2_floorb - location
	location_xpos18_yneg14_place1_room11_floorc - location
	location_xpos18_yneg21_place36_room5_floora - location
	location_xpos20_yneg11_place3_room12_floorb - location
	location_xpos22_yneg28_place45_room12_floorb - location
	location_xpos22_ypos19_place9_room1_floora - location
	location_xpos27_ypos14_place11_room3_floorc - location
	location_xpos27_ypos3_place54_room12_floorb - location
	location_xpos30_yneg31_place45_room12_floorb - location
	location_xpos30_ypos19_place50_room1_floora - location
	location_xpos30_ypos3_place54_room12_floorb - location
	location_xpos31_yneg16_place39_room11_floorc - location
	location_xpos31_yneg31_place39_room11_floorc - location
	location_xpos32_yneg12_place32_room11_floorc - location
	location_xpos33_ypos0_place33_room11_floorc - location
	location_xpos33_ypos0_place34_room11_floorc - location
	location_xpos34_ypos6_place49_room3_floorc - location
	location_xpos4_yneg25_place51_room4_floorc - location
	location_xpos5_ypos26_place16_room16_floorb - location
	location_xpos5_ypos9_place14_room9_floorc - location
	location_xpos6_yneg16_place25_room12_floorb - location
	location_xpos6_yneg29_place24_room12_floorb - location
	location_xpos7_yneg7_place53_room12_floorb - location
	oven - rclass
	place0_door_room5_bedroom - place
	place10_door_room4_bathroom - place
	place11_door_room3_bathroom - place
	place12_door_room16_staircase - place
	place13_door_room8_corridor - place
	place14_door_room9_corridor - place
	place15_door_room15_staircase - place
	place16_item33_laptop - place
	place18_item6_bowl - place
	place19_item46_vase - place
	place1_door_room11_home_office - place
	place20_item47_vase - place
	place21_item29_tv - place
	place22_item30_tv - place
	place24_receptacle7_chair - place
	place25_receptacle8_chair - place
	place26_receptacle9_chair - place
	place27_receptacle10_chair - place
	place28_receptacle11_chair - place
	place29_receptacle12_chair - place
	place2_door_room7_corridor - place
	place30_receptacle13_chair - place
	place31_receptacle14_chair - place
	place32_receptacle15_chair - place
	place33_receptacle16_chair - place
	place34_receptacle17_chair - place
	place36_receptacle20_bed - place
	place37_receptacle21_bed - place
	place39_receptacle23_dining_table - place
	place3_door_room12_kitchen - place
	place45_receptacle34_oven - place
	place46_receptacle35_sink - place
	place47_receptacle36_sink - place
	place48_receptacle37_sink - place
	place49_receptacle38_sink - place
	place4_door_room14_lobby - place
	place50_receptacle39_sink - place
	place51_receptacle40_sink - place
	place52_receptacle41_sink - place
	place53_receptacle42_sink - place
	place54_receptacle43_refrigerator - place
	place5_door_room10_dining_room - place
	place6_door_room6_bedroom - place
	place7_door_room13_living_room - place
	place8_door_room2_bathroom - place
	place9_door_room1_bathroom - place
	receptacle10_chair - receptacle
	receptacle11_chair - receptacle
	receptacle12_chair - receptacle
	receptacle13_chair - receptacle
	receptacle14_chair - receptacle
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle20_bed - receptacle
	receptacle21_bed - receptacle
	receptacle23_dining_table - receptacle
	receptacle34_oven - receptacle
	receptacle35_sink - receptacle
	receptacle36_sink - receptacle
	receptacle37_sink - receptacle
	receptacle38_sink - receptacle
	receptacle39_sink - receptacle
	receptacle40_sink - receptacle
	receptacle41_sink - receptacle
	receptacle42_sink - receptacle
	receptacle43_refrigerator - receptacle
	receptacle7_chair - receptacle
	receptacle8_chair - receptacle
	receptacle9_chair - receptacle
	refrigerator - rclass
	robot - agent
	room10_dining_room - room
	room11_home_office - room
	room12_kitchen - room
	room13_living_room - room
	room14_lobby - room
	room15_staircase - room
	room16_staircase - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bathroom - room
	room4_bathroom - room
	room5_bedroom - room
	room6_bedroom - room
	room7_corridor - room
	room8_corridor - room
	room9_corridor - room
	sink - rclass
	teddybear - iclass
	tv - iclass
	vase - iclass
  )
  (:init 
	(atlocation robot location_xneg43_yneg16_place7_room13_floorb)
	(classrelation book refrigerator)
	(classrelation bottle oven)
	(classrelation bowl sink)
	(classrelation clock bed)
	(classrelation teddybear sink)
	(classrelation tv chair)
	(inanyreceptacle item31_tv_largeitem)
	(inanyreceptacle item32_tv_largeitem)
	(inanyreceptacle item44_book_smallitem)
	(inanyreceptacle item45_clock_mediumitem)
	(inanyreceptacle item48_teddy_bear_mediumitem)
	(inanyreceptacle item4_bottle_smallitem)
	(inanyreceptacle item5_bowl_smallitem)
	(inplace robot place7_door_room13_living_room)
	(inreceptacle item31_tv_largeitem receptacle12_chair)
	(inreceptacle item32_tv_largeitem receptacle23_dining_table)
	(inreceptacle item44_book_smallitem receptacle43_refrigerator)
	(inreceptacle item45_clock_mediumitem receptacle21_bed)
	(inreceptacle item48_teddy_bear_mediumitem receptacle37_sink)
	(inreceptacle item4_bottle_smallitem receptacle34_oven)
	(inreceptacle item5_bowl_smallitem receptacle42_sink)
	(inroom robot room13_living_room)
	(itematlocation item29_tv_largeitem location_xneg42_yneg31_place21_room13_floorb)
	(itematlocation item30_tv_largeitem location_xneg43_yneg32_place22_room13_floorb)
	(itematlocation item31_tv_largeitem location_xneg57_yneg22_place29_room6_floorc)
	(itematlocation item32_tv_largeitem location_xpos31_yneg31_place39_room11_floorc)
	(itematlocation item33_laptop_mediumitem location_xpos5_ypos26_place16_room16_floorb)
	(itematlocation item44_book_smallitem location_xpos30_ypos3_place54_room12_floorb)
	(itematlocation item45_clock_mediumitem location_xneg19_yneg30_place37_room6_floorc)
	(itematlocation item46_vase_mediumitem location_xneg57_ypos15_place19_room8_floorb)
	(itematlocation item47_vase_mediumitem location_xneg57_ypos7_place20_room14_floora)
	(itematlocation item48_teddy_bear_mediumitem location_xneg17_yneg12_place48_room4_floorc)
	(itematlocation item4_bottle_smallitem location_xpos30_yneg31_place45_room12_floorb)
	(itematlocation item5_bowl_smallitem location_xpos7_yneg7_place53_room12_floorb)
	(itematlocation item6_bowl_smallitem location_xneg57_ypos12_place18_room14_floora)
	(itemclass item29_tv_largeitem tv)
	(itemclass item30_tv_largeitem tv)
	(itemclass item31_tv_largeitem tv)
	(itemclass item32_tv_largeitem tv)
	(itemclass item33_laptop_mediumitem laptop)
	(itemclass item44_book_smallitem book)
	(itemclass item45_clock_mediumitem clock)
	(itemclass item46_vase_mediumitem vase)
	(itemclass item47_vase_mediumitem vase)
	(itemclass item48_teddy_bear_mediumitem teddybear)
	(itemclass item4_bottle_smallitem bottle)
	(itemclass item5_bowl_smallitem bowl)
	(itemclass item6_bowl_smallitem bowl)
	(locationinplace location_xneg13_yneg13_place26_room10_floorb place26_receptacle9_chair)
	(locationinplace location_xneg14_yneg19_place48_room4_floorc place48_receptacle37_sink)
	(locationinplace location_xneg14_yneg1_place47_room4_floorc place47_receptacle36_sink)
	(locationinplace location_xneg14_ypos19_place12_room16_floorb place12_door_room16_staircase)
	(locationinplace location_xneg17_yneg12_place48_room4_floorc place48_receptacle37_sink)
	(locationinplace location_xneg19_yneg30_place37_room6_floorc place37_receptacle21_bed)
	(locationinplace location_xneg20_ypos20_place15_room15_floora place15_door_room15_staircase)
	(locationinplace location_xneg22_ypos9_place2_room7_floora place2_door_room7_corridor)
	(locationinplace location_xneg26_ypos12_place13_room8_floorb place13_door_room8_corridor)
	(locationinplace location_xneg31_yneg14_place37_room6_floorc place37_receptacle21_bed)
	(locationinplace location_xneg31_yneg7_place6_room6_floorc place6_door_room6_bedroom)
	(locationinplace location_xneg42_yneg31_place21_room13_floorb place21_item29_tv)
	(locationinplace location_xneg43_yneg16_place7_room13_floorb place7_door_room13_living_room)
	(locationinplace location_xneg43_yneg32_place22_room13_floorb place22_item30_tv)
	(locationinplace location_xneg44_yneg15_place30_room6_floorc place30_receptacle13_chair)
	(locationinplace location_xneg44_yneg9_place31_room6_floorc place31_receptacle14_chair)
	(locationinplace location_xneg48_ypos15_place4_room14_floora place4_door_room14_lobby)
	(locationinplace location_xneg53_yneg27_place29_room6_floorc place29_receptacle12_chair)
	(locationinplace location_xneg57_yneg22_place29_room6_floorc place29_receptacle12_chair)
	(locationinplace location_xneg57_ypos12_place18_room14_floora place18_item6_bowl)
	(locationinplace location_xneg57_ypos15_place19_room8_floorb place19_item46_vase)
	(locationinplace location_xneg57_ypos7_place20_room14_floora place20_item47_vase)
	(locationinplace location_xneg5_yneg14_place10_room4_floorc place10_door_room4_bathroom)
	(locationinplace location_xneg8_yneg11_place28_room10_floorb place28_receptacle11_chair)
	(locationinplace location_xneg8_yneg17_place5_room10_floorb place5_door_room10_dining_room)
	(locationinplace location_xneg8_yneg19_place27_room10_floorb place27_receptacle10_chair)
	(locationinplace location_xpos11_ypos13_place52_room2_floorb place52_receptacle41_sink)
	(locationinplace location_xpos13_yneg13_place53_room12_floorb place53_receptacle42_sink)
	(locationinplace location_xpos14_ypos23_place46_room1_floora place46_receptacle35_sink)
	(locationinplace location_xpos15_yneg7_place0_room5_floora place0_door_room5_bedroom)
	(locationinplace location_xpos17_ypos18_place8_room2_floorb place8_door_room2_bathroom)
	(locationinplace location_xpos18_yneg14_place1_room11_floorc place1_door_room11_home_office)
	(locationinplace location_xpos18_yneg21_place36_room5_floora place36_receptacle20_bed)
	(locationinplace location_xpos20_yneg11_place3_room12_floorb place3_door_room12_kitchen)
	(locationinplace location_xpos22_yneg28_place45_room12_floorb place45_receptacle34_oven)
	(locationinplace location_xpos22_ypos19_place9_room1_floora place9_door_room1_bathroom)
	(locationinplace location_xpos27_ypos14_place11_room3_floorc place11_door_room3_bathroom)
	(locationinplace location_xpos27_ypos3_place54_room12_floorb place54_receptacle43_refrigerator)
	(locationinplace location_xpos30_yneg31_place45_room12_floorb place45_receptacle34_oven)
	(locationinplace location_xpos30_ypos19_place50_room1_floora place50_receptacle39_sink)
	(locationinplace location_xpos30_ypos3_place54_room12_floorb place54_receptacle43_refrigerator)
	(locationinplace location_xpos31_yneg16_place39_room11_floorc place39_receptacle23_dining_table)
	(locationinplace location_xpos31_yneg31_place39_room11_floorc place39_receptacle23_dining_table)
	(locationinplace location_xpos32_yneg12_place32_room11_floorc place32_receptacle15_chair)
	(locationinplace location_xpos33_ypos0_place33_room11_floorc place33_receptacle16_chair)
	(locationinplace location_xpos33_ypos0_place34_room11_floorc place34_receptacle17_chair)
	(locationinplace location_xpos34_ypos6_place49_room3_floorc place49_receptacle38_sink)
	(locationinplace location_xpos4_yneg25_place51_room4_floorc place51_receptacle40_sink)
	(locationinplace location_xpos5_ypos26_place16_room16_floorb place16_item33_laptop)
	(locationinplace location_xpos5_ypos9_place14_room9_floorc place14_door_room9_corridor)
	(locationinplace location_xpos6_yneg16_place25_room12_floorb place25_receptacle8_chair)
	(locationinplace location_xpos6_yneg29_place24_room12_floorb place24_receptacle7_chair)
	(locationinplace location_xpos7_yneg7_place53_room12_floorb place53_receptacle42_sink)
	(placeinroom place0_door_room5_bedroom room5_bedroom)
	(placeinroom place10_door_room4_bathroom room4_bathroom)
	(placeinroom place11_door_room3_bathroom room3_bathroom)
	(placeinroom place12_door_room16_staircase room16_staircase)
	(placeinroom place13_door_room8_corridor room8_corridor)
	(placeinroom place14_door_room9_corridor room9_corridor)
	(placeinroom place15_door_room15_staircase room15_staircase)
	(placeinroom place16_item33_laptop room16_staircase)
	(placeinroom place18_item6_bowl room14_lobby)
	(placeinroom place19_item46_vase room8_corridor)
	(placeinroom place1_door_room11_home_office room11_home_office)
	(placeinroom place20_item47_vase room14_lobby)
	(placeinroom place21_item29_tv room13_living_room)
	(placeinroom place22_item30_tv room13_living_room)
	(placeinroom place24_receptacle7_chair room12_kitchen)
	(placeinroom place25_receptacle8_chair room12_kitchen)
	(placeinroom place26_receptacle9_chair room10_dining_room)
	(placeinroom place27_receptacle10_chair room10_dining_room)
	(placeinroom place28_receptacle11_chair room10_dining_room)
	(placeinroom place29_receptacle12_chair room6_bedroom)
	(placeinroom place2_door_room7_corridor room7_corridor)
	(placeinroom place30_receptacle13_chair room6_bedroom)
	(placeinroom place31_receptacle14_chair room6_bedroom)
	(placeinroom place32_receptacle15_chair room11_home_office)
	(placeinroom place33_receptacle16_chair room11_home_office)
	(placeinroom place34_receptacle17_chair room11_home_office)
	(placeinroom place36_receptacle20_bed room5_bedroom)
	(placeinroom place37_receptacle21_bed room6_bedroom)
	(placeinroom place39_receptacle23_dining_table room11_home_office)
	(placeinroom place3_door_room12_kitchen room12_kitchen)
	(placeinroom place45_receptacle34_oven room12_kitchen)
	(placeinroom place46_receptacle35_sink room1_bathroom)
	(placeinroom place47_receptacle36_sink room4_bathroom)
	(placeinroom place48_receptacle37_sink room4_bathroom)
	(placeinroom place49_receptacle38_sink room3_bathroom)
	(placeinroom place4_door_room14_lobby room14_lobby)
	(placeinroom place50_receptacle39_sink room1_bathroom)
	(placeinroom place51_receptacle40_sink room4_bathroom)
	(placeinroom place52_receptacle41_sink room2_bathroom)
	(placeinroom place53_receptacle42_sink room12_kitchen)
	(placeinroom place54_receptacle43_refrigerator room12_kitchen)
	(placeinroom place5_door_room10_dining_room room10_dining_room)
	(placeinroom place6_door_room6_bedroom room6_bedroom)
	(placeinroom place7_door_room13_living_room room13_living_room)
	(placeinroom place8_door_room2_bathroom room2_bathroom)
	(placeinroom place9_door_room1_bathroom room1_bathroom)
	(placelocation location_xneg13_yneg13_place26_room10_floorb place26_receptacle9_chair)
	(placelocation location_xneg14_yneg19_place48_room4_floorc place48_receptacle37_sink)
	(placelocation location_xneg14_yneg1_place47_room4_floorc place47_receptacle36_sink)
	(placelocation location_xneg14_ypos19_place12_room16_floorb place12_door_room16_staircase)
	(placelocation location_xneg20_ypos20_place15_room15_floora place15_door_room15_staircase)
	(placelocation location_xneg22_ypos9_place2_room7_floora place2_door_room7_corridor)
	(placelocation location_xneg26_ypos12_place13_room8_floorb place13_door_room8_corridor)
	(placelocation location_xneg31_yneg14_place37_room6_floorc place37_receptacle21_bed)
	(placelocation location_xneg31_yneg7_place6_room6_floorc place6_door_room6_bedroom)
	(placelocation location_xneg42_yneg31_place21_room13_floorb place21_item29_tv)
	(placelocation location_xneg43_yneg16_place7_room13_floorb place7_door_room13_living_room)
	(placelocation location_xneg43_yneg32_place22_room13_floorb place22_item30_tv)
	(placelocation location_xneg44_yneg15_place30_room6_floorc place30_receptacle13_chair)
	(placelocation location_xneg44_yneg9_place31_room6_floorc place31_receptacle14_chair)
	(placelocation location_xneg48_ypos15_place4_room14_floora place4_door_room14_lobby)
	(placelocation location_xneg53_yneg27_place29_room6_floorc place29_receptacle12_chair)
	(placelocation location_xneg57_ypos12_place18_room14_floora place18_item6_bowl)
	(placelocation location_xneg57_ypos15_place19_room8_floorb place19_item46_vase)
	(placelocation location_xneg57_ypos7_place20_room14_floora place20_item47_vase)
	(placelocation location_xneg5_yneg14_place10_room4_floorc place10_door_room4_bathroom)
	(placelocation location_xneg8_yneg11_place28_room10_floorb place28_receptacle11_chair)
	(placelocation location_xneg8_yneg17_place5_room10_floorb place5_door_room10_dining_room)
	(placelocation location_xneg8_yneg19_place27_room10_floorb place27_receptacle10_chair)
	(placelocation location_xpos11_ypos13_place52_room2_floorb place52_receptacle41_sink)
	(placelocation location_xpos13_yneg13_place53_room12_floorb place53_receptacle42_sink)
	(placelocation location_xpos14_ypos23_place46_room1_floora place46_receptacle35_sink)
	(placelocation location_xpos15_yneg7_place0_room5_floora place0_door_room5_bedroom)
	(placelocation location_xpos17_ypos18_place8_room2_floorb place8_door_room2_bathroom)
	(placelocation location_xpos18_yneg14_place1_room11_floorc place1_door_room11_home_office)
	(placelocation location_xpos18_yneg21_place36_room5_floora place36_receptacle20_bed)
	(placelocation location_xpos20_yneg11_place3_room12_floorb place3_door_room12_kitchen)
	(placelocation location_xpos22_yneg28_place45_room12_floorb place45_receptacle34_oven)
	(placelocation location_xpos22_ypos19_place9_room1_floora place9_door_room1_bathroom)
	(placelocation location_xpos27_ypos14_place11_room3_floorc place11_door_room3_bathroom)
	(placelocation location_xpos27_ypos3_place54_room12_floorb place54_receptacle43_refrigerator)
	(placelocation location_xpos30_ypos19_place50_room1_floora place50_receptacle39_sink)
	(placelocation location_xpos31_yneg16_place39_room11_floorc place39_receptacle23_dining_table)
	(placelocation location_xpos32_yneg12_place32_room11_floorc place32_receptacle15_chair)
	(placelocation location_xpos33_ypos0_place33_room11_floorc place33_receptacle16_chair)
	(placelocation location_xpos33_ypos0_place34_room11_floorc place34_receptacle17_chair)
	(placelocation location_xpos34_ypos6_place49_room3_floorc place49_receptacle38_sink)
	(placelocation location_xpos4_yneg25_place51_room4_floorc place51_receptacle40_sink)
	(placelocation location_xpos5_ypos26_place16_room16_floorb place16_item33_laptop)
	(placelocation location_xpos5_ypos9_place14_room9_floorc place14_door_room9_corridor)
	(placelocation location_xpos6_yneg16_place25_room12_floorb place25_receptacle8_chair)
	(placelocation location_xpos6_yneg29_place24_room12_floorb place24_receptacle7_chair)
	(receptacleatlocation receptacle10_chair location_xneg8_yneg19_place27_room10_floorb)
	(receptacleatlocation receptacle11_chair location_xneg8_yneg11_place28_room10_floorb)
	(receptacleatlocation receptacle12_chair location_xneg53_yneg27_place29_room6_floorc)
	(receptacleatlocation receptacle13_chair location_xneg44_yneg15_place30_room6_floorc)
	(receptacleatlocation receptacle14_chair location_xneg44_yneg9_place31_room6_floorc)
	(receptacleatlocation receptacle15_chair location_xpos32_yneg12_place32_room11_floorc)
	(receptacleatlocation receptacle16_chair location_xpos33_ypos0_place33_room11_floorc)
	(receptacleatlocation receptacle17_chair location_xpos33_ypos0_place34_room11_floorc)
	(receptacleatlocation receptacle20_bed location_xpos18_yneg21_place36_room5_floora)
	(receptacleatlocation receptacle21_bed location_xneg31_yneg14_place37_room6_floorc)
	(receptacleatlocation receptacle23_dining_table location_xpos31_yneg16_place39_room11_floorc)
	(receptacleatlocation receptacle34_oven location_xpos22_yneg28_place45_room12_floorb)
	(receptacleatlocation receptacle35_sink location_xpos14_ypos23_place46_room1_floora)
	(receptacleatlocation receptacle36_sink location_xneg14_yneg1_place47_room4_floorc)
	(receptacleatlocation receptacle37_sink location_xneg14_yneg19_place48_room4_floorc)
	(receptacleatlocation receptacle38_sink location_xpos34_ypos6_place49_room3_floorc)
	(receptacleatlocation receptacle39_sink location_xpos30_ypos19_place50_room1_floora)
	(receptacleatlocation receptacle40_sink location_xpos4_yneg25_place51_room4_floorc)
	(receptacleatlocation receptacle41_sink location_xpos11_ypos13_place52_room2_floorb)
	(receptacleatlocation receptacle42_sink location_xpos13_yneg13_place53_room12_floorb)
	(receptacleatlocation receptacle43_refrigerator location_xpos27_ypos3_place54_room12_floorb)
	(receptacleatlocation receptacle7_chair location_xpos6_yneg29_place24_room12_floorb)
	(receptacleatlocation receptacle8_chair location_xpos6_yneg16_place25_room12_floorb)
	(receptacleatlocation receptacle9_chair location_xneg13_yneg13_place26_room10_floorb)
	(receptacleclass receptacle10_chair chair)
	(receptacleclass receptacle11_chair chair)
	(receptacleclass receptacle12_chair chair)
	(receptacleclass receptacle13_chair chair)
	(receptacleclass receptacle14_chair chair)
	(receptacleclass receptacle15_chair chair)
	(receptacleclass receptacle16_chair chair)
	(receptacleclass receptacle17_chair chair)
	(receptacleclass receptacle20_bed bed)
	(receptacleclass receptacle21_bed bed)
	(receptacleclass receptacle34_oven oven)
	(receptacleclass receptacle35_sink sink)
	(receptacleclass receptacle36_sink sink)
	(receptacleclass receptacle37_sink sink)
	(receptacleclass receptacle38_sink sink)
	(receptacleclass receptacle39_sink sink)
	(receptacleclass receptacle40_sink sink)
	(receptacleclass receptacle41_sink sink)
	(receptacleclass receptacle42_sink sink)
	(receptacleclass receptacle43_refrigerator refrigerator)
	(receptacleclass receptacle7_chair chair)
	(receptacleclass receptacle8_chair chair)
	(receptacleclass receptacle9_chair chair)
	(receptacleopeningtype receptacle34_oven)
	(receptacleopeningtype receptacle43_refrigerator)
	(roomplace place0_door_room5_bedroom room5_bedroom)
	(roomplace place10_door_room4_bathroom room4_bathroom)
	(roomplace place11_door_room3_bathroom room3_bathroom)
	(roomplace place12_door_room16_staircase room16_staircase)
	(roomplace place13_door_room8_corridor room8_corridor)
	(roomplace place14_door_room9_corridor room9_corridor)
	(roomplace place15_door_room15_staircase room15_staircase)
	(roomplace place1_door_room11_home_office room11_home_office)
	(roomplace place2_door_room7_corridor room7_corridor)
	(roomplace place3_door_room12_kitchen room12_kitchen)
	(roomplace place4_door_room14_lobby room14_lobby)
	(roomplace place5_door_room10_dining_room room10_dining_room)
	(roomplace place6_door_room6_bedroom room6_bedroom)
	(roomplace place7_door_room13_living_room room13_living_room)
	(roomplace place8_door_room2_bathroom room2_bathroom)
	(roomplace place9_door_room1_bathroom room1_bathroom)
	(roomsconnected room10_dining_room room12_kitchen)
	(roomsconnected room10_dining_room room8_corridor)
	(roomsconnected room11_home_office room4_bathroom)
	(roomsconnected room12_kitchen room10_dining_room)
	(roomsconnected room12_kitchen room2_bathroom)
	(roomsconnected room13_living_room room8_corridor)
	(roomsconnected room14_lobby room7_corridor)
	(roomsconnected room15_staircase room7_corridor)
	(roomsconnected room15_staircase room8_corridor)
	(roomsconnected room16_staircase room8_corridor)
	(roomsconnected room16_staircase room9_corridor)
	(roomsconnected room1_bathroom room5_bedroom)
	(roomsconnected room2_bathroom room12_kitchen)
	(roomsconnected room3_bathroom room9_corridor)
	(roomsconnected room4_bathroom room11_home_office)
	(roomsconnected room4_bathroom room6_bedroom)
	(roomsconnected room4_bathroom room9_corridor)
	(roomsconnected room5_bedroom room1_bathroom)
	(roomsconnected room5_bedroom room7_corridor)
	(roomsconnected room6_bedroom room4_bathroom)
	(roomsconnected room7_corridor room14_lobby)
	(roomsconnected room7_corridor room15_staircase)
	(roomsconnected room7_corridor room5_bedroom)
	(roomsconnected room8_corridor room10_dining_room)
	(roomsconnected room8_corridor room13_living_room)
	(roomsconnected room8_corridor room15_staircase)
	(roomsconnected room8_corridor room16_staircase)
	(roomsconnected room9_corridor room16_staircase)
	(roomsconnected room9_corridor room3_bathroom)
	(roomsconnected room9_corridor room4_bathroom)
  )
  (:goal (and
	(classrelation bowl refrigerator)
	(classrelation bottle chair)
	(classrelation laptop chair)
	(classrelation clock sink)
	(classrelation vase chair)))
)
