
(define (problem IhlenTaskographyv5Tiny5Bagslots5Problem51) (:domain taskographyv5tiny5bagslots5)
  (:objects
        apple - iclass
	backpack - iclass
	bagslot1 - bagslot
	bagslot2 - bagslot
	bagslot3 - bagslot
	bagslot4 - bagslot
	bagslot5 - bagslot
	banana - iclass
	baseballbat - iclass
	baseballglove - iclass
	bed - rclass
	bench - rclass
	bicycle - iclass
	boat - rclass
	book - iclass
	bottle - iclass
	bowl - iclass
	cake - iclass
	cellphone - iclass
	chair - rclass
	clock - iclass
	couch - rclass
	cup - iclass
	diningtable - rclass
	frisbee - iclass
	handbag - iclass
	item30_potted_plant_largeitem - item
	item31_potted_plant_largeitem - item
	item32_potted_plant_largeitem - item
	item6_cup_smallitem - item
	item7_book_smallitem - item
	item8_vase_mediumitem - item
	keyboard - iclass
	kite - iclass
	knife - iclass
	laptop - iclass
	location_Xneg11_Yneg10_place39_room12_floorA - location
	location_Xneg12_Ypos59_place11_room6_floorA - location
	location_Xneg14_Yneg1_place39_room12_floorA - location
	location_Xneg15_Ypos58_place20_room11_floorB - location
	location_Xneg20_Ypos68_place14_room14_floorA - location
	location_Xneg20_Ypos6_place39_room12_floorA - location
	location_Xneg23_Ypos105_place44_room4_floorB - location
	location_Xneg25_Ypos22_place31_room9_floorB - location
	location_Xneg25_Ypos59_place16_room11_floorB - location
	location_Xneg26_Ypos12_place32_room9_floorB - location
	location_Xneg2_Ypos80_place6_room15_floorA - location
	location_Xneg30_Ypos17_place9_room9_floorB - location
	location_Xneg30_Ypos18_place47_room9_floorB - location
	location_Xneg31_Ypos22_place48_room9_floorB - location
	location_Xneg31_Ypos52_place0_room11_floorB - location
	location_Xneg31_Ypos61_place15_room16_floorA - location
	location_Xneg31_Ypos61_place16_room11_floorB - location
	location_Xneg31_Ypos91_place4_room4_floorB - location
	location_Xneg33_Ypos104_place21_room15_floorA - location
	location_Xneg33_Ypos13_place33_room9_floorB - location
	location_Xneg34_Ypos23_place34_room9_floorB - location
	location_Xneg34_Ypos96_place44_room4_floorB - location
	location_Xneg35_Ypos25_place26_room8_floorA - location
	location_Xneg36_Ypos18_place46_room9_floorB - location
	location_Xneg38_Ypos25_place7_room8_floorA - location
	location_Xneg39_Ypos22_place24_room8_floorA - location
	location_Xneg40_Ypos26_place45_room8_floorA - location
	location_Xneg41_Ypos33_place25_room8_floorA - location
	location_Xneg42_Ypos25_place27_room8_floorA - location
	location_Xneg46_Ypos77_place35_room4_floorB - location
	location_Xneg48_Ypos44_place25_room8_floorA - location
	location_Xneg48_Ypos47_place18_room11_floorB - location
	location_Xneg8_Ypos24_place29_room12_floorA - location
	location_Xneg9_Ypos16_place5_room12_floorA - location
	location_Xpos0_Ypos53_place12_room7_floorB - location
	location_Xpos0_Ypos96_place1_room2_floorB - location
	location_Xpos14_Yneg12_place37_room13_floorB - location
	location_Xpos16_Ypos104_place28_room3_floorB - location
	location_Xpos17_Ypos60_place40_room5_floorB - location
	location_Xpos20_Ypos4_place10_room13_floorB - location
	location_Xpos26_Ypos46_place3_room5_floorB - location
	location_Xpos27_Ypos21_place41_room13_floorB - location
	location_Xpos28_Yneg12_place38_room13_floorB - location
	location_Xpos30_Ypos51_place43_room5_floorB - location
	location_Xpos30_Ypos90_place8_room3_floorB - location
	location_Xpos31_Ypos19_place13_room10_floorA - location
	location_Xpos32_Ypos40_place43_room5_floorB - location
	location_Xpos37_Ypos93_place42_room3_floorB - location
	location_Xpos3_Ypos104_place22_room2_floorB - location
	location_Xpos40_Ypos96_place2_room1_floorA - location
	location_Xpos43_Ypos99_place23_room1_floorA - location
	location_Xpos44_Ypos104_place19_room1_floorA - location
	location_Xpos7_Ypos23_place30_room12_floorA - location
	location_Xpos8_Ypos19_place36_room13_floorB - location
	location_Xpos8_Ypos98_place17_room2_floorB - location
	microwave - rclass
	motorcycle - iclass
	mouse - iclass
	orange - iclass
	oven - rclass
	place0_door_room11_kitchen - place
	place10_door_room13_living_room - place
	place11_door_room6_corridor - place
	place12_door_room7_corridor - place
	place13_door_room10_garage - place
	place14_door_room14_staircase - place
	place15_door_room16_storage_room - place
	place16_receptacle1_oven - place
	place17_receptacle2_sink - place
	place18_receptacle3_sink - place
	place19_receptacle4_sink - place
	place1_door_room2_bathroom - place
	place20_receptacle5_refrigerator - place
	place21_receptacle9_bench - place
	place22_receptacle10_toilet - place
	place23_receptacle11_toilet - place
	place24_receptacle12_chair - place
	place25_receptacle13_chair - place
	place26_receptacle14_chair - place
	place27_receptacle15_chair - place
	place28_receptacle16_chair - place
	place29_receptacle17_chair - place
	place2_door_room1_bathroom - place
	place30_receptacle18_chair - place
	place31_receptacle19_chair - place
	place32_receptacle20_chair - place
	place33_receptacle21_chair - place
	place34_receptacle22_chair - place
	place35_receptacle23_chair - place
	place36_receptacle24_chair - place
	place37_receptacle25_chair - place
	place38_receptacle26_chair - place
	place39_receptacle27_chair - place
	place3_door_room5_bedroom - place
	place40_receptacle28_chair - place
	place41_receptacle29_couch - place
	place42_receptacle33_bed - place
	place43_receptacle34_bed - place
	place44_receptacle35_bed - place
	place45_receptacle36_dining_table - place
	place46_receptacle37_dining_table - place
	place47_receptacle38_dining_table - place
	place48_receptacle39_dining_table - place
	place4_door_room4_bedroom - place
	place5_door_room12_living_room - place
	place6_door_room15_storage_room - place
	place7_door_room8_dining_room - place
	place8_door_room3_bedroom - place
	place9_door_room9_dining_room - place
	pottedplant - iclass
	receptacle10_toilet - receptacle
	receptacle11_toilet - receptacle
	receptacle12_chair - receptacle
	receptacle13_chair - receptacle
	receptacle14_chair - receptacle
	receptacle15_chair - receptacle
	receptacle16_chair - receptacle
	receptacle17_chair - receptacle
	receptacle18_chair - receptacle
	receptacle19_chair - receptacle
	receptacle1_oven - receptacle
	receptacle20_chair - receptacle
	receptacle21_chair - receptacle
	receptacle22_chair - receptacle
	receptacle23_chair - receptacle
	receptacle24_chair - receptacle
	receptacle25_chair - receptacle
	receptacle26_chair - receptacle
	receptacle27_chair - receptacle
	receptacle28_chair - receptacle
	receptacle29_couch - receptacle
	receptacle2_sink - receptacle
	receptacle33_bed - receptacle
	receptacle34_bed - receptacle
	receptacle35_bed - receptacle
	receptacle36_dining_table - receptacle
	receptacle37_dining_table - receptacle
	receptacle38_dining_table - receptacle
	receptacle39_dining_table - receptacle
	receptacle3_sink - receptacle
	receptacle4_sink - receptacle
	receptacle5_refrigerator - receptacle
	receptacle9_bench - receptacle
	refrigerator - rclass
	remote - iclass
	robot - agent
	room10_garage - room
	room11_kitchen - room
	room12_living_room - room
	room13_living_room - room
	room14_staircase - room
	room15_storage_room - room
	room16_storage_room - room
	room1_bathroom - room
	room2_bathroom - room
	room3_bedroom - room
	room4_bedroom - room
	room5_bedroom - room
	room6_corridor - room
	room7_corridor - room
	room8_dining_room - room
	room9_dining_room - room
	sink - rclass
	spoon - iclass
	sportsball - iclass
	suitcase - iclass
	surfboard - iclass
	teddybear - iclass
	tie - iclass
	toaster - rclass
	toilet - rclass
	toothbrush - iclass
	tv - iclass
	umbrella - iclass
	vase - iclass
	wineglass - iclass
  )
  (:init 
	(atlocation robot location_Xpos20_Ypos4_place10_room13_floorB)
	(classrelation book bed)
	(classrelation cup bed)
	(classrelation pottedplant chair)
	(classrelation pottedplant oven)
	(classrelation vase chair)
	(inanyreceptacle item30_potted_plant_largeitem)
	(inanyreceptacle item31_potted_plant_largeitem)
	(inanyreceptacle item32_potted_plant_largeitem)
	(inanyreceptacle item6_cup_smallitem)
	(inanyreceptacle item7_book_smallitem)
	(inanyreceptacle item8_vase_mediumitem)
	(inplace robot place10_door_room13_living_room)
	(inreceptacle item30_potted_plant_largeitem receptacle27_chair)
	(inreceptacle item31_potted_plant_largeitem receptacle13_chair)
	(inreceptacle item32_potted_plant_largeitem receptacle1_oven)
	(inreceptacle item6_cup_smallitem receptacle34_bed)
	(inreceptacle item7_book_smallitem receptacle35_bed)
	(inreceptacle item8_vase_mediumitem receptacle27_chair)
	(inroom robot room13_living_room)
	(itematlocation item30_potted_plant_largeitem location_Xneg20_Ypos6_place39_room12_floorA)
	(itematlocation item31_potted_plant_largeitem location_Xneg48_Ypos44_place25_room8_floorA)
	(itematlocation item32_potted_plant_largeitem location_Xneg31_Ypos61_place16_room11_floorB)
	(itematlocation item6_cup_smallitem location_Xpos30_Ypos51_place43_room5_floorB)
	(itematlocation item7_book_smallitem location_Xneg23_Ypos105_place44_room4_floorB)
	(itematlocation item8_vase_mediumitem location_Xneg14_Yneg1_place39_room12_floorA)
	(itemclass item30_potted_plant_largeitem pottedplant)
	(itemclass item31_potted_plant_largeitem pottedplant)
	(itemclass item32_potted_plant_largeitem pottedplant)
	(itemclass item6_cup_smallitem cup)
	(itemclass item7_book_smallitem book)
	(itemclass item8_vase_mediumitem vase)
	(largeitem item30_potted_plant_largeitem)
	(largeitem item31_potted_plant_largeitem)
	(largeitem item32_potted_plant_largeitem)
	(locationinplace location_Xneg11_Yneg10_place39_room12_floorA place39_receptacle27_chair)
	(locationinplace location_Xneg12_Ypos59_place11_room6_floorA place11_door_room6_corridor)
	(locationinplace location_Xneg14_Yneg1_place39_room12_floorA place39_receptacle27_chair)
	(locationinplace location_Xneg15_Ypos58_place20_room11_floorB place20_receptacle5_refrigerator)
	(locationinplace location_Xneg20_Ypos68_place14_room14_floorA place14_door_room14_staircase)
	(locationinplace location_Xneg20_Ypos6_place39_room12_floorA place39_receptacle27_chair)
	(locationinplace location_Xneg23_Ypos105_place44_room4_floorB place44_receptacle35_bed)
	(locationinplace location_Xneg25_Ypos22_place31_room9_floorB place31_receptacle19_chair)
	(locationinplace location_Xneg25_Ypos59_place16_room11_floorB place16_receptacle1_oven)
	(locationinplace location_Xneg26_Ypos12_place32_room9_floorB place32_receptacle20_chair)
	(locationinplace location_Xneg2_Ypos80_place6_room15_floorA place6_door_room15_storage_room)
	(locationinplace location_Xneg30_Ypos17_place9_room9_floorB place9_door_room9_dining_room)
	(locationinplace location_Xneg30_Ypos18_place47_room9_floorB place47_receptacle38_dining_table)
	(locationinplace location_Xneg31_Ypos22_place48_room9_floorB place48_receptacle39_dining_table)
	(locationinplace location_Xneg31_Ypos52_place0_room11_floorB place0_door_room11_kitchen)
	(locationinplace location_Xneg31_Ypos61_place15_room16_floorA place15_door_room16_storage_room)
	(locationinplace location_Xneg31_Ypos61_place16_room11_floorB place16_receptacle1_oven)
	(locationinplace location_Xneg31_Ypos91_place4_room4_floorB place4_door_room4_bedroom)
	(locationinplace location_Xneg33_Ypos104_place21_room15_floorA place21_receptacle9_bench)
	(locationinplace location_Xneg33_Ypos13_place33_room9_floorB place33_receptacle21_chair)
	(locationinplace location_Xneg34_Ypos23_place34_room9_floorB place34_receptacle22_chair)
	(locationinplace location_Xneg34_Ypos96_place44_room4_floorB place44_receptacle35_bed)
	(locationinplace location_Xneg35_Ypos25_place26_room8_floorA place26_receptacle14_chair)
	(locationinplace location_Xneg36_Ypos18_place46_room9_floorB place46_receptacle37_dining_table)
	(locationinplace location_Xneg38_Ypos25_place7_room8_floorA place7_door_room8_dining_room)
	(locationinplace location_Xneg39_Ypos22_place24_room8_floorA place24_receptacle12_chair)
	(locationinplace location_Xneg40_Ypos26_place45_room8_floorA place45_receptacle36_dining_table)
	(locationinplace location_Xneg41_Ypos33_place25_room8_floorA place25_receptacle13_chair)
	(locationinplace location_Xneg42_Ypos25_place27_room8_floorA place27_receptacle15_chair)
	(locationinplace location_Xneg46_Ypos77_place35_room4_floorB place35_receptacle23_chair)
	(locationinplace location_Xneg48_Ypos44_place25_room8_floorA place25_receptacle13_chair)
	(locationinplace location_Xneg48_Ypos47_place18_room11_floorB place18_receptacle3_sink)
	(locationinplace location_Xneg8_Ypos24_place29_room12_floorA place29_receptacle17_chair)
	(locationinplace location_Xneg9_Ypos16_place5_room12_floorA place5_door_room12_living_room)
	(locationinplace location_Xpos0_Ypos53_place12_room7_floorB place12_door_room7_corridor)
	(locationinplace location_Xpos0_Ypos96_place1_room2_floorB place1_door_room2_bathroom)
	(locationinplace location_Xpos14_Yneg12_place37_room13_floorB place37_receptacle25_chair)
	(locationinplace location_Xpos16_Ypos104_place28_room3_floorB place28_receptacle16_chair)
	(locationinplace location_Xpos17_Ypos60_place40_room5_floorB place40_receptacle28_chair)
	(locationinplace location_Xpos20_Ypos4_place10_room13_floorB place10_door_room13_living_room)
	(locationinplace location_Xpos26_Ypos46_place3_room5_floorB place3_door_room5_bedroom)
	(locationinplace location_Xpos27_Ypos21_place41_room13_floorB place41_receptacle29_couch)
	(locationinplace location_Xpos28_Yneg12_place38_room13_floorB place38_receptacle26_chair)
	(locationinplace location_Xpos30_Ypos51_place43_room5_floorB place43_receptacle34_bed)
	(locationinplace location_Xpos30_Ypos90_place8_room3_floorB place8_door_room3_bedroom)
	(locationinplace location_Xpos31_Ypos19_place13_room10_floorA place13_door_room10_garage)
	(locationinplace location_Xpos32_Ypos40_place43_room5_floorB place43_receptacle34_bed)
	(locationinplace location_Xpos37_Ypos93_place42_room3_floorB place42_receptacle33_bed)
	(locationinplace location_Xpos3_Ypos104_place22_room2_floorB place22_receptacle10_toilet)
	(locationinplace location_Xpos40_Ypos96_place2_room1_floorA place2_door_room1_bathroom)
	(locationinplace location_Xpos43_Ypos99_place23_room1_floorA place23_receptacle11_toilet)
	(locationinplace location_Xpos44_Ypos104_place19_room1_floorA place19_receptacle4_sink)
	(locationinplace location_Xpos7_Ypos23_place30_room12_floorA place30_receptacle18_chair)
	(locationinplace location_Xpos8_Ypos19_place36_room13_floorB place36_receptacle24_chair)
	(locationinplace location_Xpos8_Ypos98_place17_room2_floorB place17_receptacle2_sink)
	(mediumitem item8_vase_mediumitem)
	(placeinroom place0_door_room11_kitchen room11_kitchen)
	(placeinroom place10_door_room13_living_room room13_living_room)
	(placeinroom place11_door_room6_corridor room6_corridor)
	(placeinroom place12_door_room7_corridor room7_corridor)
	(placeinroom place13_door_room10_garage room10_garage)
	(placeinroom place14_door_room14_staircase room14_staircase)
	(placeinroom place15_door_room16_storage_room room16_storage_room)
	(placeinroom place16_receptacle1_oven room11_kitchen)
	(placeinroom place17_receptacle2_sink room2_bathroom)
	(placeinroom place18_receptacle3_sink room11_kitchen)
	(placeinroom place19_receptacle4_sink room1_bathroom)
	(placeinroom place1_door_room2_bathroom room2_bathroom)
	(placeinroom place20_receptacle5_refrigerator room11_kitchen)
	(placeinroom place21_receptacle9_bench room15_storage_room)
	(placeinroom place22_receptacle10_toilet room2_bathroom)
	(placeinroom place23_receptacle11_toilet room1_bathroom)
	(placeinroom place24_receptacle12_chair room8_dining_room)
	(placeinroom place25_receptacle13_chair room8_dining_room)
	(placeinroom place26_receptacle14_chair room8_dining_room)
	(placeinroom place27_receptacle15_chair room8_dining_room)
	(placeinroom place28_receptacle16_chair room3_bedroom)
	(placeinroom place29_receptacle17_chair room12_living_room)
	(placeinroom place2_door_room1_bathroom room1_bathroom)
	(placeinroom place30_receptacle18_chair room12_living_room)
	(placeinroom place31_receptacle19_chair room9_dining_room)
	(placeinroom place32_receptacle20_chair room9_dining_room)
	(placeinroom place33_receptacle21_chair room9_dining_room)
	(placeinroom place34_receptacle22_chair room9_dining_room)
	(placeinroom place35_receptacle23_chair room4_bedroom)
	(placeinroom place36_receptacle24_chair room13_living_room)
	(placeinroom place37_receptacle25_chair room13_living_room)
	(placeinroom place38_receptacle26_chair room13_living_room)
	(placeinroom place39_receptacle27_chair room12_living_room)
	(placeinroom place3_door_room5_bedroom room5_bedroom)
	(placeinroom place40_receptacle28_chair room5_bedroom)
	(placeinroom place41_receptacle29_couch room13_living_room)
	(placeinroom place42_receptacle33_bed room3_bedroom)
	(placeinroom place43_receptacle34_bed room5_bedroom)
	(placeinroom place44_receptacle35_bed room4_bedroom)
	(placeinroom place45_receptacle36_dining_table room8_dining_room)
	(placeinroom place46_receptacle37_dining_table room9_dining_room)
	(placeinroom place47_receptacle38_dining_table room9_dining_room)
	(placeinroom place48_receptacle39_dining_table room9_dining_room)
	(placeinroom place4_door_room4_bedroom room4_bedroom)
	(placeinroom place5_door_room12_living_room room12_living_room)
	(placeinroom place6_door_room15_storage_room room15_storage_room)
	(placeinroom place7_door_room8_dining_room room8_dining_room)
	(placeinroom place8_door_room3_bedroom room3_bedroom)
	(placeinroom place9_door_room9_dining_room room9_dining_room)
	(placelocation location_Xneg11_Yneg10_place39_room12_floorA place39_receptacle27_chair)
	(placelocation location_Xneg12_Ypos59_place11_room6_floorA place11_door_room6_corridor)
	(placelocation location_Xneg15_Ypos58_place20_room11_floorB place20_receptacle5_refrigerator)
	(placelocation location_Xneg20_Ypos68_place14_room14_floorA place14_door_room14_staircase)
	(placelocation location_Xneg25_Ypos22_place31_room9_floorB place31_receptacle19_chair)
	(placelocation location_Xneg25_Ypos59_place16_room11_floorB place16_receptacle1_oven)
	(placelocation location_Xneg26_Ypos12_place32_room9_floorB place32_receptacle20_chair)
	(placelocation location_Xneg2_Ypos80_place6_room15_floorA place6_door_room15_storage_room)
	(placelocation location_Xneg30_Ypos17_place9_room9_floorB place9_door_room9_dining_room)
	(placelocation location_Xneg30_Ypos18_place47_room9_floorB place47_receptacle38_dining_table)
	(placelocation location_Xneg31_Ypos22_place48_room9_floorB place48_receptacle39_dining_table)
	(placelocation location_Xneg31_Ypos52_place0_room11_floorB place0_door_room11_kitchen)
	(placelocation location_Xneg31_Ypos61_place15_room16_floorA place15_door_room16_storage_room)
	(placelocation location_Xneg31_Ypos91_place4_room4_floorB place4_door_room4_bedroom)
	(placelocation location_Xneg33_Ypos104_place21_room15_floorA place21_receptacle9_bench)
	(placelocation location_Xneg33_Ypos13_place33_room9_floorB place33_receptacle21_chair)
	(placelocation location_Xneg34_Ypos23_place34_room9_floorB place34_receptacle22_chair)
	(placelocation location_Xneg34_Ypos96_place44_room4_floorB place44_receptacle35_bed)
	(placelocation location_Xneg35_Ypos25_place26_room8_floorA place26_receptacle14_chair)
	(placelocation location_Xneg36_Ypos18_place46_room9_floorB place46_receptacle37_dining_table)
	(placelocation location_Xneg38_Ypos25_place7_room8_floorA place7_door_room8_dining_room)
	(placelocation location_Xneg39_Ypos22_place24_room8_floorA place24_receptacle12_chair)
	(placelocation location_Xneg40_Ypos26_place45_room8_floorA place45_receptacle36_dining_table)
	(placelocation location_Xneg41_Ypos33_place25_room8_floorA place25_receptacle13_chair)
	(placelocation location_Xneg42_Ypos25_place27_room8_floorA place27_receptacle15_chair)
	(placelocation location_Xneg46_Ypos77_place35_room4_floorB place35_receptacle23_chair)
	(placelocation location_Xneg48_Ypos47_place18_room11_floorB place18_receptacle3_sink)
	(placelocation location_Xneg8_Ypos24_place29_room12_floorA place29_receptacle17_chair)
	(placelocation location_Xneg9_Ypos16_place5_room12_floorA place5_door_room12_living_room)
	(placelocation location_Xpos0_Ypos53_place12_room7_floorB place12_door_room7_corridor)
	(placelocation location_Xpos0_Ypos96_place1_room2_floorB place1_door_room2_bathroom)
	(placelocation location_Xpos14_Yneg12_place37_room13_floorB place37_receptacle25_chair)
	(placelocation location_Xpos16_Ypos104_place28_room3_floorB place28_receptacle16_chair)
	(placelocation location_Xpos17_Ypos60_place40_room5_floorB place40_receptacle28_chair)
	(placelocation location_Xpos20_Ypos4_place10_room13_floorB place10_door_room13_living_room)
	(placelocation location_Xpos26_Ypos46_place3_room5_floorB place3_door_room5_bedroom)
	(placelocation location_Xpos27_Ypos21_place41_room13_floorB place41_receptacle29_couch)
	(placelocation location_Xpos28_Yneg12_place38_room13_floorB place38_receptacle26_chair)
	(placelocation location_Xpos30_Ypos90_place8_room3_floorB place8_door_room3_bedroom)
	(placelocation location_Xpos31_Ypos19_place13_room10_floorA place13_door_room10_garage)
	(placelocation location_Xpos32_Ypos40_place43_room5_floorB place43_receptacle34_bed)
	(placelocation location_Xpos37_Ypos93_place42_room3_floorB place42_receptacle33_bed)
	(placelocation location_Xpos3_Ypos104_place22_room2_floorB place22_receptacle10_toilet)
	(placelocation location_Xpos40_Ypos96_place2_room1_floorA place2_door_room1_bathroom)
	(placelocation location_Xpos43_Ypos99_place23_room1_floorA place23_receptacle11_toilet)
	(placelocation location_Xpos44_Ypos104_place19_room1_floorA place19_receptacle4_sink)
	(placelocation location_Xpos7_Ypos23_place30_room12_floorA place30_receptacle18_chair)
	(placelocation location_Xpos8_Ypos19_place36_room13_floorB place36_receptacle24_chair)
	(placelocation location_Xpos8_Ypos98_place17_room2_floorB place17_receptacle2_sink)
	(receptacleatlocation receptacle10_toilet location_Xpos3_Ypos104_place22_room2_floorB)
	(receptacleatlocation receptacle11_toilet location_Xpos43_Ypos99_place23_room1_floorA)
	(receptacleatlocation receptacle12_chair location_Xneg39_Ypos22_place24_room8_floorA)
	(receptacleatlocation receptacle13_chair location_Xneg41_Ypos33_place25_room8_floorA)
	(receptacleatlocation receptacle14_chair location_Xneg35_Ypos25_place26_room8_floorA)
	(receptacleatlocation receptacle15_chair location_Xneg42_Ypos25_place27_room8_floorA)
	(receptacleatlocation receptacle16_chair location_Xpos16_Ypos104_place28_room3_floorB)
	(receptacleatlocation receptacle17_chair location_Xneg8_Ypos24_place29_room12_floorA)
	(receptacleatlocation receptacle18_chair location_Xpos7_Ypos23_place30_room12_floorA)
	(receptacleatlocation receptacle19_chair location_Xneg25_Ypos22_place31_room9_floorB)
	(receptacleatlocation receptacle1_oven location_Xneg25_Ypos59_place16_room11_floorB)
	(receptacleatlocation receptacle20_chair location_Xneg26_Ypos12_place32_room9_floorB)
	(receptacleatlocation receptacle21_chair location_Xneg33_Ypos13_place33_room9_floorB)
	(receptacleatlocation receptacle22_chair location_Xneg34_Ypos23_place34_room9_floorB)
	(receptacleatlocation receptacle23_chair location_Xneg46_Ypos77_place35_room4_floorB)
	(receptacleatlocation receptacle24_chair location_Xpos8_Ypos19_place36_room13_floorB)
	(receptacleatlocation receptacle25_chair location_Xpos14_Yneg12_place37_room13_floorB)
	(receptacleatlocation receptacle26_chair location_Xpos28_Yneg12_place38_room13_floorB)
	(receptacleatlocation receptacle27_chair location_Xneg11_Yneg10_place39_room12_floorA)
	(receptacleatlocation receptacle28_chair location_Xpos17_Ypos60_place40_room5_floorB)
	(receptacleatlocation receptacle29_couch location_Xpos27_Ypos21_place41_room13_floorB)
	(receptacleatlocation receptacle2_sink location_Xpos8_Ypos98_place17_room2_floorB)
	(receptacleatlocation receptacle33_bed location_Xpos37_Ypos93_place42_room3_floorB)
	(receptacleatlocation receptacle34_bed location_Xpos32_Ypos40_place43_room5_floorB)
	(receptacleatlocation receptacle35_bed location_Xneg34_Ypos96_place44_room4_floorB)
	(receptacleatlocation receptacle36_dining_table location_Xneg40_Ypos26_place45_room8_floorA)
	(receptacleatlocation receptacle37_dining_table location_Xneg36_Ypos18_place46_room9_floorB)
	(receptacleatlocation receptacle38_dining_table location_Xneg30_Ypos18_place47_room9_floorB)
	(receptacleatlocation receptacle39_dining_table location_Xneg31_Ypos22_place48_room9_floorB)
	(receptacleatlocation receptacle3_sink location_Xneg48_Ypos47_place18_room11_floorB)
	(receptacleatlocation receptacle4_sink location_Xpos44_Ypos104_place19_room1_floorA)
	(receptacleatlocation receptacle5_refrigerator location_Xneg15_Ypos58_place20_room11_floorB)
	(receptacleatlocation receptacle9_bench location_Xneg33_Ypos104_place21_room15_floorA)
	(receptacleclass receptacle10_toilet toilet)
	(receptacleclass receptacle11_toilet toilet)
	(receptacleclass receptacle12_chair chair)
	(receptacleclass receptacle13_chair chair)
	(receptacleclass receptacle14_chair chair)
	(receptacleclass receptacle15_chair chair)
	(receptacleclass receptacle16_chair chair)
	(receptacleclass receptacle17_chair chair)
	(receptacleclass receptacle18_chair chair)
	(receptacleclass receptacle19_chair chair)
	(receptacleclass receptacle1_oven oven)
	(receptacleclass receptacle20_chair chair)
	(receptacleclass receptacle21_chair chair)
	(receptacleclass receptacle22_chair chair)
	(receptacleclass receptacle23_chair chair)
	(receptacleclass receptacle24_chair chair)
	(receptacleclass receptacle25_chair chair)
	(receptacleclass receptacle26_chair chair)
	(receptacleclass receptacle27_chair chair)
	(receptacleclass receptacle28_chair chair)
	(receptacleclass receptacle29_couch couch)
	(receptacleclass receptacle2_sink sink)
	(receptacleclass receptacle33_bed bed)
	(receptacleclass receptacle34_bed bed)
	(receptacleclass receptacle35_bed bed)
	(receptacleclass receptacle36_dining_table diningtable)
	(receptacleclass receptacle37_dining_table diningtable)
	(receptacleclass receptacle38_dining_table diningtable)
	(receptacleclass receptacle39_dining_table diningtable)
	(receptacleclass receptacle3_sink sink)
	(receptacleclass receptacle4_sink sink)
	(receptacleclass receptacle5_refrigerator refrigerator)
	(receptacleclass receptacle9_bench bench)
	(receptacleopeningtype receptacle1_oven)
	(receptacleopeningtype receptacle5_refrigerator)
	(roomplace place0_door_room11_kitchen room11_kitchen)
	(roomplace place10_door_room13_living_room room13_living_room)
	(roomplace place11_door_room6_corridor room6_corridor)
	(roomplace place12_door_room7_corridor room7_corridor)
	(roomplace place13_door_room10_garage room10_garage)
	(roomplace place14_door_room14_staircase room14_staircase)
	(roomplace place15_door_room16_storage_room room16_storage_room)
	(roomplace place1_door_room2_bathroom room2_bathroom)
	(roomplace place2_door_room1_bathroom room1_bathroom)
	(roomplace place3_door_room5_bedroom room5_bedroom)
	(roomplace place4_door_room4_bedroom room4_bedroom)
	(roomplace place5_door_room12_living_room room12_living_room)
	(roomplace place6_door_room15_storage_room room15_storage_room)
	(roomplace place7_door_room8_dining_room room8_dining_room)
	(roomplace place8_door_room3_bedroom room3_bedroom)
	(roomplace place9_door_room9_dining_room room9_dining_room)
	(roomsconnected room10_garage room12_living_room)
	(roomsconnected room11_kitchen room14_staircase)
	(roomsconnected room11_kitchen room4_bedroom)
	(roomsconnected room11_kitchen room7_corridor)
	(roomsconnected room11_kitchen room9_dining_room)
	(roomsconnected room12_living_room room10_garage)
	(roomsconnected room12_living_room room8_dining_room)
	(roomsconnected room13_living_room room5_bedroom)
	(roomsconnected room14_staircase room11_kitchen)
	(roomsconnected room14_staircase room16_storage_room)
	(roomsconnected room14_staircase room6_corridor)
	(roomsconnected room15_storage_room room1_bathroom)
	(roomsconnected room15_storage_room room6_corridor)
	(roomsconnected room16_storage_room room14_staircase)
	(roomsconnected room16_storage_room room8_dining_room)
	(roomsconnected room1_bathroom room15_storage_room)
	(roomsconnected room2_bathroom room3_bedroom)
	(roomsconnected room2_bathroom room4_bedroom)
	(roomsconnected room3_bedroom room2_bathroom)
	(roomsconnected room4_bedroom room11_kitchen)
	(roomsconnected room4_bedroom room2_bathroom)
	(roomsconnected room5_bedroom room13_living_room)
	(roomsconnected room5_bedroom room7_corridor)
	(roomsconnected room6_corridor room14_staircase)
	(roomsconnected room6_corridor room15_storage_room)
	(roomsconnected room7_corridor room11_kitchen)
	(roomsconnected room7_corridor room5_bedroom)
	(roomsconnected room8_dining_room room12_living_room)
	(roomsconnected room8_dining_room room16_storage_room)
	(roomsconnected room9_dining_room room11_kitchen)
	(smallitem item6_cup_smallitem)
	(smallitem item7_book_smallitem)
  )
  (:goal (and
	(classrelation cup chair)
	(classrelation pottedplant sink)
	(classrelation vase sink)
	(classrelation cup toilet)
	(classrelation book diningtable)))
)
